프로젝트 관리 앱 [STEP 2-2] 지성, 제인
yagom-academy/ios-project-manager pull request #101
Opened 2022-03-12 11:27 UTC by siwonkim0

안녕하세요 제이슨 @ehgud0670 🚀

지성, 제인입니다

말씀드린 기한보다 많이 늦어서 죄송합니다... 🥲

이번 스텝은 2-2로 CRUD와 데이터 바인딩, 비즈니스 로직에 대한 UnitTest를 진행하였습니다.

잘부탁드립니다~!

# MVVM + Clean Architecture 구조
![Untitled](https://user-images.githubusercontent.com/60725934/158015804-8aca501c-9774-46ec-90ad-e57f0b2559a8.png)

### Model

- Project가 가진 정보를 가지고 있는 모델입니다.
- 테스트를 위해 Equatable을 채택해주었습니다.

### View

- ListVC는 테이블뷰를 가지고 있는 VC입니다.
- 은 DetailVC를 상속받고 있습니다. 이유는 두 VC의 공통된 부분을 묶어주기 위해 상위 VC를 생성하여 주었습니다.
- 하나의 ViewModel을 사용하기 위해 ListVC, AddDetailVC, EditDetailVC에 생성자 주입을 해주었습니다.

### ViewModel

- UseCase를 갖고있으며 UseCase가 Repository를 통해 갖고온 데이터를 View에 보여줄 데이터로 변환해주는 역할을 합니다.
- 바인딩을 위해 클로저를 가지고 있으며 View에서 요청이 들어오면 서버단의 데이터까지 업데이트한 후 클로저에 정의한 작업을 수행하게 하였습니다.
- tableViewDataSource를 채택하고 있습니다. 가지고 있는 데이터를 통해 tableView에 데이터를 뿌려줍니다.

### UseCase

- 비즈니스 로직이 구현되어 있는 곳입니다.
- Repository를 갖고있으며 viewModel과 연관이 없어 테스트하기 용이하고, 실제로 해당 UseCase 테스트를 진행하였습니다.

### Repository

- Repository는 Key로 ID, Value로 Project타입을 가진 딕셔너리를 가지고 있습니다. (Entity)
- Local, Remote 저장소에 특정 작업을 요청하는 곳이며, 현재는 변수에 저장하는 식으로 구현이 되어있습니다.
- 해당 클래스를 추상화하고 Mock을 만들어 변수에 가짜 데이터를 넘겨주고, 비즈니스 로직을 테스트할 수 있도록 하였습니다. (네트워킹을 하지 않는 테스트)

## 데이터 전달

AddDetailVC, EditDetailVC 에서 할일 추가나 수정이 될때 ListVC에 바로 데이터를 전달하는 것이 아니라

ViewModel → UseCase → Repository → Server 에 업데이트하고 

ListVC는 Server에 업데이트된 정보를 다시 가져와서 뷰에 보여주는 방식으로 구조를 설계했습니다. 

# 고민했던 부분

### 의존성 역전
 - repository, useCase, viewModel 의존성 주입 SceneDelegate에서 처리
 - viewModel에게 tableViews를 주입해주는 작업은 ListVC에서 처리
 - ListVC에서 ListVC와 addDetailVC, editDetailVC에 viewModel을 주입해주는 작업 처리
 
### ListVC에서 테이블 뷰 셀 클릭시 DetailVC로 데이터 전달: 클로저 활용
    
기존 DetailVC 메서드에 직접 접근하던 방식을 클로저를 이용한 방식으로 변경해주었습니다.
    
- ListVC의 ViewDidLoad에서 뷰모델이 가진 onCellSelected 클로저를 정의해주고,
- 셀이 선택되면 호출되는 didSelectRowAt 메서드에서 파라미터로 선택된 인덱스와, 테이블뷰를 받는 viewModel의 didselectRow메서드를 호출합니다.
- didSelectRow 메서드에서는 tableView를 통해 분기처리, 이후 분기하여 나온 데이터 집합을 파라미터로 받은 인덱스를 통해 특정 데이터를 꺼내주었고, 해당 데이터와 인덱스를 onCellSelected의 파라미터로 넣어주고 호출합니다.
- 호출시 이전에 정의해놓은 작업(DetailVC Present)이 실행됩니다.
    
    <코드>
    
- ViewModel
    
```swift
    var onCellSelected: ((Int, Project) -> Void)? // 선언부
    
    func retrieveSelectedData(index: IndexPath, tableView: UITableView) -> Project? {
        var selectedProject: Project?
        switch tableView {
        case tableViews?[0]:
            selectedProject = todoProjects[index.row]
        case tableViews?[1]:
            selectedProject = doingProjects[index.row]
        case tableViews?[2]:
            selectedProject = doneProjects[index.row]
        default:
            break
        }
        
        return selectedProject
    }
    
    func didSelectRow(index: IndexPath, tableView: UITableView) {
        guard let selectedProject = retrieveSelectedData(index: index, tableView: tableView) else {
            return
        }
        onCellSelected?(index.row, selectedProject) //실행부
    }
```
    
- ListVC
    configureBind 메서드에서 셀이 선택될때 EditVC에 선택된 모델을 전달하며 화면을 present하는 로직 정의 
    
```swift
    // 정의부
    func configureBind() {
        viewModel.tableViews = tableViews
        viewModel.fetchAll()
        
        viewModel.onCellSelected = { [weak self] index, project in
            guard let self = self else {
                return
            }
            let editViewController = EditProjectDetailViewController(viewModel: self.viewModel, currentIndex: index, currentProject: project)
            let destinationViewController = UINavigationController(rootViewController: editViewController)
            destinationViewController.modalPresentationStyle = .formSheet
            self.present(destinationViewController, animated: true, completion: nil)
        }
        
        viewModel.onUpdated = {
            self.tableViews.forEach {
                $0.reloadData()
            }
        }
    }
    
    // didSelectRowAt
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        viewModel.didSelectRow(index: indexPath, tableView: tableView)
    }
```
    
### EditDetailVC에서 Done 버튼 클릭시 ListVC를 업데이트: 클로저 활용
1. 서버에 데이터 전달
- 뷰가 dismiss되며 DetailView의 컴포넌트에 적힌 텍스트, date를 활용하여 모델 생성 후 해당 모델을 이용해 viewModel의 메서드를 호출합니다.
    
```swift
    self.dismiss(animated: true) { [self] in
        guard let currentProject = currentProject else {
            return
        }
        let updatedProject = projectDetailView.retrieveViewData(with: currentProject)
        viewModel?.update(with: updatedProject)
    }
```
    
 - 뷰모델 update 메서드 호출시 usecase(domain)의 update 메서드를 호출하여 Repository(local, remote container) 업데이트합니다.
- UseCase의 메서드 내부에선 파라미터로 받은 project(업데이트, 수정된 프로젝트)의 id를 통해 repository의 data 중 특정 id를 만족하는 기존 프로젝트를 불러옵니다.
- 기존 repo의 프로젝트의 title, body, date를 수정합니다.
    
```swift
    //viewmodel
    func update(with project: Project) {
        useCase.update(with: project)
        fetchAll()
        onUpdated?()
    }
    
    //usecase
    func update(with project: Project) {
        let oldProject = fetch(with: project.id)
        let newProject = Project(id: oldProject.id, state: oldProject.state, title: project.title, body: project.body, date: project.date)
        
        projectRepository.update(with: newProject)
    }
    
    // Repository
    func update(with project: Project) {
        projects.updateValue(project, forKey: project.id)
    }
```
    
 2. 뷰에 업데이트된 데이터 반영
 - 이후 업데이트된 repo의 프로젝트(데이터)를 불러와 viewmodel을 업데이트하고, 클로저를 활용하여 테이블뷰 리로드를 통해 ListVC를 업데이트합니다.
    
```swift
    //업데이트 과정
    
    // Repository
    func fetchAll() -> [UUID: Project] { 
        return projects
    }
    
    //usecase
    func fetchAll() -> [Project] { 
        return projectRepository.fetchAll()
            .map { $0.value }
            .sorted { $0.date > $1.date }
    }
    
    //viewmodel
    func fetchAll() {
        projects = useCase.fetchAll()
    }
```
    
```swift
    //ListVC
    viewModel.onUpdated = {
        self.tableViews.forEach {
            $0.reloadData()
        }
    }
```
    

# 질문드리고 싶은 부분

### View에서 화면의 데이터를 반환하는 메서드를 정의하여도 괜찮은지

ProjectDetailView에 정의한 메서드인데 화면 뷰 요소에 담긴 데이터를 모델 형식으로 반환하고 있습니다.

이런식으로 하지않으면 따로따로 전달해서 뷰모델이나 도메인에서 모델 타입으로 만들어줘야할텐데 그 방식보다는 이게 낫다고 생각하였습니다. 그러나 이 방식이 뷰가 모델을 아는것이 되는건지 궁금합니다

```swift
func createViewData() -> Project {
    return Project(
        id: UUID(),
        state: .todo,
        title: titleTextField.text ?? "",
        body: bodyTextView.text ?? "",
        date: datePicker.date)
}

func retrieveViewData(with oldProject: Project) -> Project {
    return Project(
        id: oldProject.id,
        state: oldProject.state,
        title: titleTextField.text ?? "",
        body: bodyTextView.text ?? "",
        date: datePicker.date)
}
```

### tableView.reloadData vs reloadRows

지금으로서는 상세화면에서 할일을 수정시 수정된 데이터를 받아서 ListVC에서 뷰를 업데이트할 때 수정된 row의 내용만 업데이트하는것이 아니라 tableView.reloadData 방식으로 전체 테이블뷰를 업데이트하고 있습니다.

할일의 내용이 제목, 내용, 날짜로 이루어져있고 이미지도 없어서 전체를 매번 업데이트하는 비용이 하나만 업데이트하는 비용에 비해 그렇게 크지 않을 것 같다는 판단하에 이 방식을 사용했습니다.

저희가 생각한 이유가 타당한지 궁금합니다.

### viewModel이 tableView를 가져도 되는지

UITableViewDataSource를 채택하고있는 viewModel이 특정 tableView를 업데이트하거나, 삭제하는 작업을 할 때 어떤 tableView에서 업데이트, 삭제하는지 분기처리를 해줘야하기때문에 viewModel에 프로퍼티 주입을 해주었습니다.

특정 tableView를 분간해내기 위해 해당 작업을 하였는데 올바른 방법인지 궁금합니다.

### useCase에 대한 테스트
mock Repository를 만들어서 테스트를 진행했습니다.
비즈니스 로직에 대한 테스트만 진행하면 된다는 생각에 useCase의 메서드들만 테스트해봤는데 이런 방식으로 진행하는 것이 맞는지 궁금합니다. 

## 아직 구현하지 못한 부분

- 날짜 데이터 포맷팅
- 할일 이동 기능

전체적인 구조를 짜는데 시간이 많이 들어서 세세한 부분은 아직 구현하지 못하였습니다. 😭

저희가 구현해본 데이터 전달 흐름과 구조가 맞는 방향인지 궁금합니다! 

감사합니다 😊

2022-03-13 02:13 UTC, ehgud0670 commented on ProjectManager/ProjectManager/View/ProjectDetailView/EditProjectDetailViewController.swift
> +//    var currentIndex: Int?
이전 코드는 주석처리하면 안됩니다. 지워주세요.

2022-03-13 11:46 UTC, ehgud0670 commented
컴파일 에러 납니다!! PR 올리실때 빌드가 되는지 확인 하시고 PR 올려주세요 🙏

<img width="865" alt="스크린샷 2022-03-13 오후 8 45 50" src="https://user-images.githubusercontent.com/38216027/158057862-58e07856-14db-4ec6-a3a2-e0a200c6d2bd.png">

2022-03-13 13:14 UTC, ehgud0670 requested changes
수고하셨습니다! 글도 잘 설명되어 있어서 따라가기 좋았습니다. 
구조에 대해서 고민을 많이 하신 티가 나서 좋네요! 
서버에 연동하는 것까지 고려하셔서 구현하신 것 좋습니다 😄 
테스트 하신 것도 잘하셨어요. 그럼 마저 글로 리뷰를 달겠습니다.

2022-03-13 13:14 UTC, ehgud0670 commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +}
# 질문드리고 싶은 부분
## useCase에 대한 테스트

* UseCase 를 테스트할 때 목데이터로 Repository를 넘기는 것 잘하셨네요! 해당 객체의 메소드들을 테스트하는데 하위 객체가 필요하다면 지금처럼 모킹하시면 되겠습니다. 
* repository 테스트는 서버로부터 요청하는 객체가 되었을 때 테스트를 하면 의미가 있겠습니다 :)

2022-03-13 13:14 UTC, ehgud0670 commented on ProjectManager/ProjectManager/ViewModel/ProjectViewModel.swift
> +class ProjectViewModel: NSObject, ProjectViewModelProtocol {
final 키워드를 쓴 class 가 없네요. 혹시 final 키워드의 장점을 알고 계실까요? 
꼭 필요한 건 아닌데 면접시 질문이 들어올 수도 있습니다.

2022-03-13 13:14 UTC, ehgud0670 commented on ProjectManager/ProjectManager/View/ProjectDetailView/EditProjectDetailViewController.swift
> +        }
이런 부분은 메소드로 빼서 좀 더 가독성이 있도록 할 수 있을 것 같아요.

2022-03-13 13:15 UTC, ehgud0670 commented on ProjectManager/ProjectManager/View/ProjectListView/ProjectListViewController.swift
>  extension ProjectListViewController: UITableViewDelegate {
추가로 onCellSelected 클로저를 ViewModel이 가지고 있으므로 Delegate 역할은 뷰모델이 하는 것이 더 어울리겠네요~

2022-03-13 13:21 UTC, ehgud0670 commented
# 질문드리고 싶은 부분
## tableView.reloadData vs reloadRows

=> 저는 보통 전체적인 데이터를 한번에 load 된 경우에는 reloadData를 호출하고, 특정 하나만 업데이팅된 경우에는 reloadRow를 각각 호출하도록 구현 했었습니다. 당연히 저도 그 전에는 reloadData 로만 대응하다가 나중에는 reloadRow도 사용했어요. 
아시는 것처럼 하나만 업데이팅하는 것이 효율적이니 한번 시도해보세요 :)

2022-03-13 13:31 UTC, ehgud0670 commented
추가로 EditVC, AddVC로 오버라이딩 잘 하셨어요 ㅎㅎ

2022-03-14 09:04 UTC, yim2627 commented on ProjectManager/ProjectManager/ViewModel/ProjectViewModel.swift
> +class ProjectViewModel: NSObject, ProjectViewModelProtocol {
깜빡하고 빼먹은 것 같습니다 🥲

final 키워드를 붙일시의 장점은 해당 클래스는 상속되지못함을 명시해 런타임시 해당 클래스가 상속되어있는 곳을 찾아다니는 비용을 발생시키는 Dynamic Dispatch를 컴파일 시점에 결정하고 찾아다니는 비용을 발생시키지 않는 Static Dispatch로 변경하여 성능을 높일 수 있는 것으로 알고있습니다.

2022-03-14 09:05 UTC, siwonkim0 commented on ProjectManager/ProjectManager/View/ProjectDetailView/EditProjectDetailViewController.swift
> +    var currentProject: Project?
- 데이터를 반환하는 메서드보다는 뷰모델(뷰모델의 메소드로)에게 전달하는 형식으로 바꾸고 ProjectListViewController에게 넘기는게 더 자연스러워 보이고 다른 팀원들이 보기에도 더 단순해 보이네요 :)
->  ProjectDetailView는 ProjectDetailVC가 가지고 있는 View로서 View는 ViewModel을 알지 못합니다. 따라서 View가 데이터를 반환하여 먼저 VC에 전달하고, VC에서 그 데이터를 다시 ViewModel에 전달하는 방식으로 구현하였던 것이었습니다. 말씀해주신 방법으로 구현하려면 ProjectDetailView가 ViewModel을 알고있어야 할 것 같은데 그건 또 어색한 것 같아서 혼란스럽습니다 ㅜㅜ 

```Swift
self.dismiss(animated: true) { [self] in
    guard let currentProject = currentProject else {
        return
    }
    let updatedProject = projectDetailView.retrieveViewData(with: currentProject)
    viewModel?.update(with: updatedProject)
}
```

2022-03-14 09:17 UTC, siwonkim0 commented on ProjectManager/ProjectManager/View/ProjectDetailView/EditProjectDetailViewController.swift
> +        fatalError("init(coder:) has not been implemented")
해당 부분 모두 이런식으로 프로퍼티를 옵셔널로 설정하여 변경해주었습니다!
```Swift
final class EditProjectDetailViewController: ProjectDetailViewController {
    var viewModel: ProjectViewModelProtocol?
    var currentProject: Project?

    init(viewModel: ProjectViewModelProtocol, currentProject: Project) {
        super.init(nibName: nil, bundle: nil)
        self.viewModel = viewModel
        self.currentProject = currentProject
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }
}
```

2022-03-14 09:27 UTC, siwonkim0 commented on ProjectManager/ProjectManager/View/ProjectListView/ProjectListViewController.swift
> +            headerView.populateData(title: TitleText.todoTableViewTitle, count: viewModel.todoProjects.count)
ProjectState 라는 열거형 타입을 만들어서 그 안에 연산 프로퍼티로 title을 가져올 수 있도록 하였습니다 ! 😄

```Swift
enum ProjectState {
    case todo
    case doing
    case done
    
    var title: String {
        switch self {
        case .todo:
            return "TODO"
        case .doing:
            return "DOING"
        case .done:
            return "DONE"
        }
    }
}
```

2022-03-14 09:28 UTC, yim2627 commented on ProjectManager/ProjectManager/Repository/ProjectRepository.swift
> +    func create(with project: Project)
좋은 의견 감사합니다.
`create`를 `append`로 변경한 뒤 CRUD 관련 메서드들의 네이밍을 다시 확인해본 결과 update, delete 같은 메서드들의 네이밍도  arguement label과 어색한 것 같아 arguement label을 와일드카드 패턴으로 변경해주었습니다.

2022-03-14 11:28 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Repository/ProjectRepository.swift
> +    func create(with project: Project)
넵, 하지만 다시 생각해보니 정답은 없는 것 같기도 하네요.. 다른 사람은 어떻게 생각할지 궁금하네요 😅
일단 저도 계속 고민해보고 질문도 해보고 하겠습니다.
고생하셨습니다.

2022-03-14 11:31 UTC, ehgud0670 commented on ProjectManager/ProjectManager/View/ProjectDetailView/EditProjectDetailViewController.swift
> +        fatalError("init(coder:) has not been implemented")
init을 통해 확실히 받는 경우라면 forced unwrapping 도 좋을 것 같습니다.

2022-03-17 01:46 UTC, ehgud0670 requested changes
갑자기 안보였던 부분들이 보여서 더 코멘트 드렸습니다. 😅
그럼 피드백 확인 부탁드립니다. 🙏

2022-03-17 01:46 UTC, ehgud0670 commented on ProjectManager/ProjectManager/ViewModel/ProjectListViewModel.swift
> +        return selectedProject
retrive 메소드가 해당 indexPath에 대응하는 모델값을 찾아 리턴하는 메소드인데 왜 selectedProject 프로퍼티도 값을 업데이팅할까요. 함수 분리가 필요해 보입니다.

2022-03-17 01:46 UTC, ehgud0670 commented on ProjectManager/ProjectManager/ViewModel/ProjectListViewModel.swift
> +        let project = retrieveSelectedData(indexPath: indexPath, state: state)
retrieveSelectedData 메소드를 사용하면 selectedProject 도 업데이팅이 될텐데 그럴 필요가 있을까요? selectedProject라는 건 사용자가 터치한 셀에 대한 데이터값이라고 생각되어서요.

2022-03-17 01:46 UTC, ehgud0670 commented on ProjectManager/ProjectManager/ViewModel/ProjectListViewModel.swift
> +    }
새로 할일를 추가하는 메소드에서도 selectedProject가 필요할까요? 현재 추가되는 메모의 경우에는 무조건 TODO 쪽으로 가던데 
selectedProject 가 doing 일수도 있는데 selectedProject가 ADDVC와 연관이 없는 듯 합니다.

2022-03-17 01:46 UTC, ehgud0670 commented on ProjectManager/ProjectManager/ViewModel/ProjectListViewModel.swift
> +    }
현재 택한 프로젝트에 대해서 값을 넘겨야 하기 때문에 selectedProject 프로퍼티가 필요한거 압니다. 하지만 꼭 프로퍼티로 들고 있어야 할까요? 현재 기능만 보았을때는 프로퍼티로 갖지 않고 그냥 메소드로만 넘겨줄 수 있는데 어떠신가요. 프로퍼티로 과거의 사용자가 선택했던 모델값을 기억하고 있는 것은 오히려 버그를 유발할 수 있지 않을까요?

2022-03-17 01:46 UTC, ehgud0670 commented on ProjectManager/ProjectManager/ViewModel/ProjectListViewModel.swift
> +    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
여기 메소드에 있는 forced unwrapping 모두 지워주셨으면 합니다. 언뜻 봐도 위험해 보이네요.
swift 언어의 장점은 safe 하다는 것인데 여기 코드들은 unsafe 해보입니다. 🥲

2022-03-17 01:48 UTC, ehgud0670 commented
https://github.com/yagom-academy/ios-project-manager/pull/99#discussion_r825826737
=> 예하한테 코멘트 드렸던 부분인데 같이 참고하시면 좋을 것 같아요. 그냥 이런 방법도 있구나라고 알고 계시면 좋을 듯 합니다. 😄

2022-03-17 06:53 UTC, siwonkim0 commented on ProjectManager/ProjectManager/ViewModel/ProjectListViewModel.swift
> +    }
헉 그렇네요 ... 😅 굳이 selectedProject가 필요없을 것 같아요. AddVM의 이니셜라이저 삭제해주었습니다!

2022-03-17 07:26 UTC, siwonkim0 commented on ProjectManager/ProjectManager/ViewModel/ProjectListViewModel.swift
> +        return selectedProject
selectedProject 프로퍼티도 값을 업데이팅하는 부분 삭제해주었습니다.

2022-03-17 07:29 UTC, yim2627 commented on ProjectManager/ProjectManager/ViewModel/ProjectListViewModel.swift
> +    }
저희도 구현하면서 너무 이상하다라는 생각을 갖고있었습니다. 🥲 
그래서 EditDetailViewModel에 현재 선택된 프로젝트의 index와 state를 주입하여 생성하도록 수정하였습니다.

2022-03-17 08:03 UTC, yim2627 commented on ProjectManager/ProjectManager/ViewModel/ProjectListViewModel.swift
> +    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
정신없이 짜다보니 수정을 놓쳐버렸네요..
배열 안전하게 조회하는 것을 적용하였고, 바인딩을 통해 포스언래핑을 제거해주었습니다

2022-03-17 10:34 UTC, merged