프로젝트 매니저 [STEP 2-2] Ari
yagom-academy/ios-project-manager pull request #104
Opened 2022-03-15 07:43 UTC by leeari95

안녕하세요. 라이언(@ryan-son) 🦁 아리(@leeari95)입니다~
이번 PR은 ViewModel을 개선하고, View 구성 후 바인딩까지 모두 마쳤습니다.
Rx를 익히는데 어려움이 있어서 늦어졌는데, 최대한 할 수 있는 부분 모두 Rx로 구현마치고 PR 보내드리게 되었습니다.
아직도 클린 아키텍처 부분은 능숙치가 않아서.. 부족한 부분이 있을 것 같은데, 이부분 체크해주시면 감사하겠습니다!

## 고민했던 점

### 1. ViewModel을 Input과 Output으로 구분지어 설계
* 가독성을 위해 ViewModel의 Input과 Output을 Nested Type으로 구현하였습니다.
* Input과 Output을 통해 뷰와 뷰모델 간의 바인딩이 매우 간결해졌습니다.

### 2. Coordinator 패턴 적용
* 화면 전환, 화면 제어를 담당하는 타입을 따로 설계하여 화면 전환 시 ViewController에서 사용할 ViewModel을 함께 주입해주는 역할도 동시에 합니다.
* ViewController가 담당하던 일들을 Coordinator 패턴을 통해 분리가 가능해졌습니다.

### 3. Memory leak을 방지
* Rx의 경우 클로저를 활용하여 구성하기 때문에 self 사용에 의한 강한 참조 사이클 발생을 방지하기 위해서 `withUnretained()` operator를 활용했습니다.
* Modal의 경우 버튼이 아니라 modal창 외부를 터치해서 창을 닫았을 때 계속 메모리에서 사라지지않고 남아있는 부분을 확인했으며, View Life Cycle을 통해 뷰가 사라질 때 ViewModel, Coordinator, Controller 모두 메모리에서 사라질 수 있도록 해주었습니다.

> 개선하기 전
![](https://i.imgur.com/hvUBDML.png)

> 개선하고난 후
![](https://i.imgur.com/Ik1TvL9.png)

## 궁금했던 것 / 조언을 얻고 싶은 점

### 1. Coordinator를 적절히 사용했는지??

* Coordinator라는 패턴을 처음 접해서 사용해보았는데, ViewModel 내부에 위치해있습니다. 근데 지금 형태가 괜찮은지...? 이상한 점이 있다면 조언 부탁드리겠습니다.

### 2. ViewModel에 UIKit이 import 되어있는데 괜찮을까요?

* 현재 MainViewController에서 `longPressGesture` 이벤트를 받았을 때 `UITableViewcell`을 ViewModel에게 넘겨주고 있습니다.
    * 넘겨주는 이유는 Cell을 sourceView 삼아서 ActionSheet를 띄우기 위함인데요.
    * ViewModel에 UIKit이 import 되어있는 부분이 몹시 불편합니다... 보통은 UIKit을 import하지 않는다고 들었는데, 이 부분 아무리 생각해도 어떻게 개선해야할지 잘 떠오르지가 않습니다. 이대로 냅둬도 괜찮을까요?

### 3. Memory leak 방지를 위한 동작이 올바른지?

* `DetailViewController` 내부 `viewDidDisappear` 시점에 viewModel과 Coordinator를 `nil`처리 해주고있는데... 괜찮은 방법인지 여쭤보고 싶습니다.

### 4. ViewModel의 transform 메소드 길이

* Input에 대한 부분을 subscribe 해주기 위해서 따로 나누지 않고 쭉 이어서 코드를 작성했는데, 분리하는게 좋을까요?
    * 메소드 길이가 길지만.. 분리하지 않은 이유가 이대로 이어서 쭉 읽는게 더 가독성이 좋다고 느껴서인데... 혹시 더 괜찮은 방법이 있는지? 여쭤보고싶습니다.

### 5. ViewModel에 비즈니스 로직을 넣지 않으려고 했는데요...

* 비즈니스 로직은 UseCase에게 할당해주려고 노력했는데... 어딘가 어색한 부분이 있는지 봐주셨으면 합니다!

### 6. UITableViewDelegate 부분 HeaderFooterView 설정

* 이 부분은 Rx로 할 수 있는 방법이 없는 것 같아서 delegate 채택 후 설정해주었는데, 혹시 Rx로 리팩토링할 수 있는지 여쭤보고 싶습니다.
    * setUpTableView 내부에서 직접 headerView를 할당해주려고 했으나, Storyboard로 만들어둔 객체라 IBOutlet 할당 시점(nil상태)과 엇갈려서... headerView의 configure 메소드를 호출할 수가 없었습니다.

2022-03-17 10:30 UTC, ryan-son requested changes
아리, 이번에도 고생 많으셨습니다! 갈수록 반응형 프로그래밍 프레임워크를 다루는 감각이 늘어가고 있다는게 느껴지네요! 

앱 디자인이 굉장히 깔끔했고, `withUnretained(_:)`와 같이 새로 도입된 연산자를 사용해보시며 메모리 관리를 하셨다는 부분이 굉장히 인상적이었습니다. 전제적으로 오탈자가 다소 발생하고 있는데, 그때그때 체크하기 어려우시다면 아래 그림과 같은 기능을 이용해서 살펴볼 수도 있습니다.
![image](https://user-images.githubusercontent.com/69730931/158782662-e270f272-c425-4612-aa4c-6454722a5e3b.png)

# 질의응답
> 1. Coordinator를 적절히 사용했는지??

네, 코디네이터 패턴이 잘 적용되어 있네요. 저도 어떤 로직에 따라 화면 전환 이벤트가 발생할테니 `View` 보다는 `ViewModel`에 위치하는게 적절하다고 생각해요. `CoordinatorType`은 지금은 필요한지 잘 모르겠네요. 화면 전환 이벤트를 열거형의 케이스로 관리하고 싶으신걸까요?

코디네이터 패턴은 구현해보셨듯이 매 프로젝트마다 보일러플레이트가 다소 발생하는데, 이 때문에 라이브러리가 꽤 있어요. 패턴에 익숙해지시면 이 라이브러리도 참고해보세요. [RxFlow](https://github.com/RxSwiftCommunity/RxFlow)

> 2. ViewModel에 UIKit이 import 되어있는데 괜찮을까요?

`ViewModel`의 태생적 목적상 View와 무관한 상태로 유지하는 것이 가장 이상적이긴 해요. 극단적으로 `View`의 어떤 요소에도 의존하고 있지 않다면, `UIKit`을 사용하는 모바일이든, `AppKit`을 사용하는 데스크탑/랩탑이든 플랫폼에 관계없이 이 로직을 재사용할 수 있으니까요. 하지만 `ViewModel`이 `View`를 모름으로써 생기는 장점 (1:N 관계 형성 가능 등)을 다소 포기하더라도 필요할 때는 아리와 같은 결정을 할 수 있어야 한다고 생각합니다. 절충은 가끔 필요하죠.

> 3. Memory leak 방지를 위한 동작이 올바른지?

누가 memory leak을 일으키고 있나요? 그것이 명확하면 적용하신 방법을 사용하지 않아도 아리가 알고 있는 방법으로 해결할 수 있습니다! 잘 모르겠다면 회의실에서 보시죠 😊

> 4. ViewModel의 transform 메소드 길이

바인딩을 등록하는 메서드의 경우 저는 **한 메서드가 여러가지 일을 한다**라고 생각하지 않습니다. 해당 메서드는 여러가지 일을 하는 것이 아니라 단지 어떤 일이 일어나면 무엇을 할 것인지라는 *바인딩*에 충실한 것이니까요. 그래서 메서드 길이가 문제가 되지는 않는다고 생각합니다. 하지만 하나하나의 바인딩 로직이 같은 동작을 해도 어렵고 길게 만들 수도 있고, 반대의 경우도 가능하기 때문에 최대한 간결해야한다고 생각합니다 (특정 이벤트가 발생했을 때 실행되는 로직이므로 오히려 이것이 하나의 메서드처럼 관리되어야 한다고 생각).

> 5. ViewModel에 비즈니스 로직을 넣지 않으려고 했는데요...

현재는 두 타입 모두 테스트 가능하니 큰 문제 없어보이네요. `ViewModel`은 단지 `View`에 전달할 내용으로 가공하는 타입이다라고 생각하신다면 `UseCase`에 일부 옮겨보는 것도 고려해볼 수 있을 것 같습니다.

> 6. UITableViewDelegate 부분 HeaderFooterView 설정

`tableView.rx.tableHeaderView`에 `next` 이벤트를 전달해서 뷰를 전달해줄 수는 있겠지만 현재 delegate 메서드처럼 변화가 있을 때마다 호출되어 헤더를 갱신시켜주지는 않을거에요. 이 방식을 채택하려면 추가적인 바인딩이 필요할겁니다. ((todo, doing, done) 갯수 변동 이벤트 발행 -> 필요한 뷰로 매핑하여 `tableView.rx.tableHeaderView`에 바인딩)

# 추가
상태값을 할당한 후에 반복적으로 `onNext(_:)`나 `accept(_:)`를 호출하고 있다면, 프로퍼티 옵저버를 활용해본 것도 좋을 것 같네요.

계속해서 화이팅입니다!! 💪 궁금한점, 필요한 것 있으시면 언제든지 말씀해주세요!

2022-03-17 13:27 UTC, leeari95 commented on ProjectManager/ProjectManager/Resource/Storyboards/Base.lproj/Main.storyboard
> +<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="19529" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
오.. 조언 감사합니다.
이번 프로젝트의 경우 혼자서 하는 개인프로젝트이기도 해서 과감하게 스토리보드를 선택했었는데요.
협업할 때에는 스토리보드 사용을 좀 더 고려해봐야겠네요.

2022-03-17 13:38 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Data/Storages/DefaultProjectStorage.swift
> +    }
오...? 이렇게도 줄일 수 있군요. 감사합니다!!
딕셔너리는 고려해봤었는데, 어짜피 로컬을 구현하게 된다면 
이 구현부는 없애버릴 생각으로 간단하게 배열로 구현해보았습니다 ㅎㅎ

2022-03-17 13:39 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Domain/Entities/Project.swift
> +    }
엇.. 그렇네요. 생각치 못한 부분인데, 의견 감사합니다.
적극 반영해보겠습니다!!!  😤

2022-03-17 13:41 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Domain/Entities/Project.swift
> +    }
오.. 문서화 주석... 감사합니다!
안그래도 프로퍼티 이름에 모든걸 넣기가 애매해서... 저렇게 네이밍 처리를 했었는데... 좋은 방법이 있었네요 🥺

2022-03-17 13:44 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Domain/UseCases/DefaultProjectListUseCase.swift
>      }
한줄로 작성 가능할 때는 생략하는 편인데, 컨벤션을 맞추질 않았네요.
이 부분 맞춰주도록 하겠습니다! 🥲

2022-03-17 13:55 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Extensions/Date+extension.swift
> +    static func formattedString(_ date: Date) -> String {
저번에 같이 이야기 나누었을 때, DateFormatter의 인스턴스를 만들 때 생성 비용이 많이 드는 작업임을 파악했었습니다.
그래서 static하게 만들어서 관리해도 괜찮을 지 알아보았는데요.
요즘은 기기들이 스팩이 꽤나 좋아서 static하게 만들지 않아도, 눈에 띄는 성능 저하가 없을 거긴 하지만!!
그래도 가능한 성능을 최대한 절약하는 것이 좋다고 판단되어서 static하게 만들어주었습니다.
또한 static하게 만들기 이전에 `Thread Safe한지?` 도 살펴봐야한다고 조언해주신점도 참고하였습니다 😄

2022-03-17 14:01 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/DetailCoordinator.swift
> +        }
한번 도전해보겠습니다!

2022-03-17 14:14 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/View/DetailViewController.swift
> +    @IBOutlet private weak var leftBarButton: UIBarButtonItem!
뷰가 종료될 때 참조 카운트, 즉 메모리 누수를 피하기 위해 weak 키워드를 쓰는 것으로 알고 있습니다.

IBOutlet이 강한참조로 선언될 경우 순환참조가 가능해지기 때문에 ,
weak 키워드로 만들어주는 것이 적절하다고 판단되어서 작성해주었습니다.

2022-03-18 04:35 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Main/View/ProjectCell.swift
> +    }
뭔가 만들기 애매하다고 생각이 들어서 냅뒀는데.... 역시나.. 만드는게 좋을까요?

2022-03-18 04:37 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Main/View/ProjectCell.swift
> +        }
오잉...? 여긴 왜안썼져....
간결하게 표현될 수 있는 조건문일 경우에는 활용해주는 편입니다!
이부분은 리팩토링 해보도록 할게요~!

2022-03-18 04:42 UTC, leeari95 commented on ProjectManager/ProjectManagerTests/DefaultProjectListUseCaseTests.swift
> +        let result = try? sut?.delete(project2).toBlocking().first()
오... throwing function을 활용해볼 수도 있었군요. 몰랐네요.
찾아보니 실패할경우 테스트가 실패했다고 표시된다고 하네요! 감사합니다 😊

2022-03-18 04:44 UTC, leeari95 commented on ProjectManager/ProjectManagerTests/DefaultProjectListUseCaseTests.swift
>          XCTAssertTrue(try! sut?.fetch().toBlocking(timeout: 1).first()?.count == 2)
엇.. 그렇네요. 리팩토링 진행해봐야겠어요. 감사합니다 😁

2022-03-18 06:54 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Protocol/Coordinator.swift
> +}
해당 타입으로 MainCoordinator 내부에서 childCoordinator를 제거해줄 때 필터링 용도로 활용하고 있습니다!

2022-03-18 08:33 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Domain/UseCases/DefaultProjectListUseCase.swift
> +    }
따로 타입을 만들어서 분리해줄 것 같습니다!

2022-03-18 08:33 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Domain/Interfaces/Repositories/ProjectRepository.swift
> +    func delete(_ item: Project?) -> Single<Project>
음.... 이걸 활용해서 어떤 점을 해결해볼 수 있나요?
제가 감이 잘 오질 않네요... 😭

2022-03-18 16:51 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/View/DetailViewController.swift
> +    var viewModel: DetailViewModel?
신경쓰지 않아도 되지 않을까요?
ViewController만 ViewModel을 참조하고 있는 형태라서.. 괜찮을 것 같다는 생각이 드는데... 맞을까여? 🤔

2022-03-18 17:17 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/View/DetailViewController.swift
> +            didChangeDescription: descriptionTextView.rx.text.changed.asObservable())
`asObservable()`은 Observable 타입으로 다운캐스팅할 때 주로 사용합니다.
사용한 이유는 ViewModel에서 해당 Input들의 타입이 Observable 타입이기 때문에 다운캐스팅을 진행해주었어요.

`rightBarButton.rx.tap`이 `asObservable()`을 사용할 수 있는 이유는 
`tap`의 경우 `ControlEvent` 타입인데, 이 타입 내부에는 `events`라는 옵저버블이 존재하고
 asObservable()을 호출할 경우 이 events를 반환하고 있네요!

2022-03-18 17:18 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/View/DetailViewController.swift
> +            }).disposed(by: disposeBag)
오... 더 Rx스럽네요. 참고하겠습니다!!! 🤩

2022-03-18 17:22 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/ViewModel/DetailViewModel.swift
> +    }
View에서는 Output을 읽기만 해야지, 값을 외부에서 주입할 수 있게 해서는 안된다는 말을 어디서 줏어들어서...
이 의견에 동의하고, 그래서 모두 옵저버블 타입으로 해주었습니다.
Input도 같은 이유에서 모두 읽기전용으로 Observable 타입으로 해주었어요.

Input의 경우 AnyObservable로도 정의해주는 경우를 봤는데, 둘의 차이를 잘모르겠네요... 조언해주실 수 있을까여??

2022-03-18 17:24 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/ViewModel/DetailViewModel.swift
> +        let isDescriptionTextValid = BehaviorRelay<Bool>(value: false)
Relay인 이유는 UI Event에 활용되기 때문에 절대로!! 끊어져선 안되겠다 싶어서 선택하였고,
Behavior인 이유는 초기값을 가지는 것이 좋겠다는 생각이 들어서였습니다.

2022-03-18 17:29 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Main/MainCoordinator.swift
> +    init(_ navigationController: UINavigationController = UINavigationController()) {
헉.. 제가 기본값 주는걸 좋아하다보니까 이런 실수를... 개선하겠습니다! 🙏🏻

2022-03-18 18:08 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/View/DetailViewController.swift
> +            .disposed(by: disposeBag)
오... 보통은 반대로 바인딩을 해주는군요... 참고하겠습니다!

2022-03-18 18:14 UTC, leeari95 commented
안녕하세요. 라이언!!
코멘트 주신 부분 모두 확인하였고, 개선할 수 있는 부분들을 아래와 같이 리팩토링 해보았습니다~

## 수정사항
- 오탈자 수정
- 좀 더 간결하게 바꿀 수 있는 부분들을 리팩토링 진행
- 테스트 코드 일부 메소드를 throwing function으로 리팩토링
- 문서화 주석을 활용하여 좀더 부가적인 설명이 필요한 곳에 퀵헬프 추가
- 스토리보드를 호출하여 인스턴스화 하는 부분을 타입을 별도로 추가하여 리팩토링
- ProjectState 타입 rawValue를 String > Int로 변경

이외에 몇가지 답변이 잘 이해가 가지 않는 부분들이 있어서 같이 봐주셨으면 합니다!
편하신 시간 때 DM 부탁드리겠습니다! 😊🙏🏻

2022-03-22 01:30 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Storyboards/Base.lproj/Main.storyboard
> +<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="19529" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
스토리보드는 어떤 iOS 개발자가 합류해도 일정한 생산성을 보장할 수 있다는 측면에서 매력적이에요. 스토리보드도 훌륭한 도구입니다!

2022-03-22 01:36 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Domain/Interfaces/Repositories/ProjectRepository.swift
> +    func delete(_ item: Project?) -> Single<Project>
회의실에서 이야기 나누었듯이 [`Hashable`](https://developer.apple.com/documentation/swift/hashable) 구현을 위해 사용되는 [`hash(into:)`](https://developer.apple.com/documentation/swift/hashable/2995575-hash)와 [`Hasher`](https://developer.apple.com/documentation/swift/hasher) 구현에 활용하는 [`combine(_:)`](https://developer.apple.com/documentation/swift/hasher/2995578-combine)을 이용하면 프로젝트 간의 비교를 좀 더 의도에 적합하게 변경할 수 있다는 내용 기록해두겠습니다!

2022-03-22 01:37 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Domain/UseCases/DefaultProjectListUseCase.swift
>      }
아직 수정하지는 않으셨네요~ 의견이 있으시면 말씀해주세요~

2022-03-22 01:41 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Extensions/Date+extension.swift
> +    static func formattedString(_ date: Date) -> String {
정적인 타입 메서드라도 이렇게 구성한다면 이 메서드가 호출될 때마다 새로운 `DateFormatter` 인스턴스가 생성될 것 같은데, 그러면 이 메서드를 어디에서든 호출할 수 있다는 장점만 가지고, 아리가 의도한 장점은 발휘하지 못하는 것 아닐까요? 아리는 어떻게 생각하시나요?

2022-03-22 02:36 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/View/DetailViewController.swift
> +    @IBOutlet private weak var leftBarButton: UIBarButtonItem!
이것도 논쟁거리 중에 하나인데요, [`이 문서`](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/LoadingResources/CocoaNibs/CocoaNibs.html#//apple_ref/doc/uid/10000051i-CH4-SW6)가 근거로 사용되는 경우가 많습니다. 하지만 각종 샘플코드나 WWDC를 보면 애플 구성원들의 공감대도 일치하지 않는 것 같아요. 아리는 어떻게 생각하시나요?

2022-03-22 02:38 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/View/DetailViewController.swift
> +    var viewModel: DetailViewModel?
네, 이 `ViewModel`은 `Coordinator`의 메서드를 통해 생성되는 인스턴스인만큼 해당 메서드가 종료되는 시점에 참조하고 있는 대상이 없으면 인스턴스가 사라집니다. 그래서 이 `ViewController`에서 강한 참조를 하고 있는 것이 적절합니다.

2022-03-22 02:39 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/View/DetailViewController.swift
> +            }).disposed(by: disposeBag)
앞으로 Closure 뿐만 아니라 KeyPath를 이용한 접근 방식도 익숙해져봐요~ (저는 아직 클로저만큼 익숙하지는 않네요.. 😅)

2022-03-22 02:49 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/View/DetailViewController.swift
> +            didChangeDescription: descriptionTextView.rx.text.changed.asObservable())
1. `ObservableType`의 기본 `asObservable()`의 동작이 캐스팅이 아니라 새로운 `Observable`을 생성하는 것이니 엄밀하게 이야기하면 캐스팅이라고 표현하기는 어려울 수 있을 것 같아요. `ControlEvent`의 경우만 놓고 보아도 내부의 `event`를 꺼내서 주는 것이지 상속관계에서 형변환을 일으키는 것과는 거리가 있으니까요.
2. 맞습니다. 아리는 왜 `asObservable()`이라는 메서드를 사용하셨나요? `Type erasure`라는 키워드에 대해서 공부해보셔도 좋을 것 같아요.

2022-03-22 02:53 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/ViewModel/DetailViewModel.swift
> +    }
1. 타입으로 정의하는 방법 이외에도 View에서 ViewModel의 프로퍼티를 읽기 전용으로 보호하는 방법이 있었을 거예요. `private(set)`과 같은 접근제한을 설정해보는거죠.
2. 어제 이야기 나누었을 때 `AnyObserver`에 대한 이야기였죠? `Observer`와 `Observable`에 대한 이야기를 나누었으니 이제 답을 아실 것 같아요 😉.

2022-03-22 02:56 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Presentation/Main/View/ProjectCell.swift
> +    }
엄밀하게 나누는 것을 좋아하시거나 더 복잡한 로직을 다루게 된다면 생각해볼 수 있을 것 같아요. 지금 수준에서는 자유롭게 하시면 될 것 같네요.

2022-03-22 02:57 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Presentation/Main/View/ProjectCell.swift
> +    }
그러고보니 여기의 IBOutlet들은 약한참조로 선언하지 않으셨네요. 이유가 있었나요?

2022-03-22 03:03 UTC, ryan-son commented
아리, 이번 스텝도 훌륭하게 해내셨네요! 👏

질문해주신 부분들에 대해서는 회의실에서 이야기도 나누었고, 이번 리뷰의 코멘트로도 달아두었어요. 구조상 크게 달라져야하는 부분은 없으니 이번 스텝은 현 상태에서 머지하도록 하겠습니다. 

고생 많으셨고 다음 스텝에서 만나요~🚀 화이팅!💪

2022-03-22 03:04 UTC, merged

2022-03-22 05:14 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Domain/UseCases/DefaultProjectListUseCase.swift
>      }
수정했습니다!

2022-03-22 05:16 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Extensions/Date+extension.swift
> +    static func formattedString(_ date: Date) -> String {
앗.. 그렇게되네요...??
제가 말했던 장점을 발휘하려면 싱글턴 패턴을 쓰는 것이 좋겠다는 생각이 드네요. 🤔

2022-03-22 05:58 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Extensions/Date+extension.swift
> +    static func formattedString(_ date: Date) -> String {
헉.. 듣고보니 그렇네요...?
그렇다면.. DateFormatter 인스턴스 생성하는 부분 자체를 정적 타입 프로퍼티로 만들어주어야 할까요...???

2022-03-22 06:00 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Detail/View/DetailViewController.swift
> +    @IBOutlet private weak var leftBarButton: UIBarButtonItem!
맞아요. 찾아보니까 애플에서는 strong으로 쓰라고 권장했던 것을 봤던 것 같아요.
근데 제 생각에는... 정말 끊어지면 안되는!! 특별한 경우가 아니라면 
weak 키워드를 써주는게 순환참조 발생에 있어서 안전한 것 같다는 생각이 들어요.

2022-03-22 06:11 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/Main/View/ProjectCell.swift
> +    }
아뇨. 빼먹은 것 같네요.... ㅎㅎ 😅