프로젝트 매니저 [Step2-2] 릴리
yagom-academy/ios-project-manager pull request #112
Opened 2022-03-23 17:58 UTC by yeahg-dev

안녕하세요 엘림! @lina0322 
릴리입니다! 
벌써 마지막 PR이 될 수도 있겠네요!🥹 아쉽습니다..
이번 리뷰도 잘 부탁드립니다!

## 🕹구현 기능

- 로컬 DB
    - 코어데이터로 프로젝트의 CRUD를 제공하는 `ProjectCoreDataManager` 구현
- 클라우드 DB
    - Firestore로 프로젝트의 CRUD를 제공하는 `ProjectFirestoreManager` 구현
    - Firestore가 기본적으로 제공하는 캐싱기능을 오프라인시 사용
        - 오프라인시 최근 다운로드된 데이터로 CRUD를 진행함
        - 온라인으로 바뀔시 변경사항들이 클라우드에 자동으로 동기화됨
- DB 선택 기능
    - UI를 통해 현재 사용중 DB 표현
    - DB선택 입력을 받을 수 있는 UI 구현 (`DataSourceConfigViewController`)
- 네트워크 오프라인 시 사용자에게 알림 기능
    - 네트워크 상태를 감지하고 처리하는 `NetworkManager` 구현
    - 오프라인시 사용자에게 알럿을 띄워서 알림
  
![프로젝트 매니저 시현](https://user-images.githubusercontent.com/81469717/159763137-acfb1d2a-61a9-4a27-8b23-6b89a436f335.gif)

## 미구현 기능

- 프로젝트 생성/수정/삭제 History 기능
- 키보드 등장시 텍스트 필드 가려지는 현상 수정
- NetworkManager가 네트워크 상태를 반대로 인식하는 버그 (네트워크가 다시 연결되었을 때 `isOn`이 true로 변하는 버그)

<br>

# 🧐고민한 내용

## 1. `Project` 를 어떻게 변환하여 CoreData, Firestore에서 사용할 지

앱의 모델인 `ProjectManager` 에서 사용하는 데이터 타입은 `Project` 입니다. 로컬DB, 클라우드DB와 주고 받을 데이터 타입으로 어떻게 변환시킬지 고민했습니다. 

1. CoreData에 사용되는 타입은 `NSManagedObject` 인데요. 이 타입에는 사용자 정의 타입을 저장할 수 없습니다. 따라서 Project에서 사용되는 `Status` 타입을 `statusString` 이라는 어트리뷰트로 저장하고, `Status` 타입은 `NSManagedObject` 의 익스텐션에서 연산프로퍼티로 구현했습니다.
2. Firestore에는 key-value의 딕셔너리 타입으로 데이터를 저장할 수 있습니다. Firestore에서 지원하지 않는 스위프트 타입에는 `Date` 타입과 사용자 정의 타입이 있었습니다. 최대한 `Project` 프로퍼티의 타입을 유지하면서 사용하는 방법을 찾다가, `JSONSerialization` 을 사용해 `Project` 를 JSON으로 변환한 후 딕셔너리로 바꾸어서 클라우드에 올리는 방법을 선택했습니다. (`Status` 도 Codable을 채택하여 함께 JSON객체로 인코딩되도록 구현했습니다) 다만, `Date` 타입은 딕셔너리로 수정해도, 파이어베이스에서는`Timestamp` 를 사용하기 때문에 동일 시간이라고 해도 날짜가 바뀌어버려서, 딕셔너리를 주고 받기 전 `Date` ↔️ `Timestamp` 간 타입 변환을 해주었습니다. 

<br>

## 2. InMemory, CoreData, FirestoreManager의 공용 인터페이스 정의

데이터 저장소가 어떤 타입이던지 간에 동일한 CRUD 작업을 수행하고 동일한 결과를 반환해야한다고 생각했습니다. 데이터를 사용하는 쪽은 컨트롤러인데 컨트롤러는 저장소 타입이 어떤것인지 알 필요도 없고, 그저 동일한 데이터를 뷰에게 전달만 해주어야 컨트롤러의 로직이 심플해집니다. 

그래서 CRUD를 `DataSource` 프로토콜에 정의하여, 동일한 인터페이스로 3가지 객체를 사용할 수 있도록 추상화 했습니다.

<br>

## 3. 비동기로 받은 데이터를 뷰에 어떻게 반영할지

Firestore의 통신은 비동기로 실행됩니다.  따라서 기존의 리턴값이 있던 `read(of identifier: String) -> Project` 를 사용할 수 없게 되었는데요. 비동기로 받은 데이터를 뷰에 반영하기 위해 생각한 방법은 두가지 입니다.

1. 컴플리션 핸들러를 통해 통신 결과를 ViewController에서 처리하는 방법
2. `ProjectManager` 의 델리게이트로 `ViewController` 를 채택하여, 통신이 도착하면 델리게이트인 컨트롤러에게 뷰를 업데이트 하도록 시키는 방법 

데이터를 사용하는 쪽인 컨트롤러에서 핸들링하도록 하는 것이, 좀 더 컨트롤러의 자율성이 클 것 같아서 1번 방법으로 구현해보았습니다.

<br>

# 🧚 조언을 얻고 싶은 내용

## 1. 코어데이터, 클라우드(서버)와 통신시 데이터 포맷팅 방법

위와 같이 데이터를 주고 받을 때마다 일일이 타입을 변환해주다 보니, 예상치 못한 버그도 많이 마주하게 되고, 하나 하나 타입을 고려해야해서 불편했습니다. 좀 더 편리하고 휴먼에러가 적게 발생할 수 있는 방법이 있을까요??

<br>

## 2. `translateAutoresizingMaskInToConstraints` 를 false로 줘도 적용이어 Constraint와 충돌하는 문제

`DataSourceConfigViewController` 에서 오토리사이징관련 제약과 높이를 정해주는 제약간에 충돌이 발생하는 문제가 발생합니다. 
뷰 컨트롤러의 뷰 사이즈를 설정해주고 싶어서 높이 150이라는 제약을 설정했고, 오토레이아웃을 적용시키기 위해 `self.view.translatesAutoresizingMaskIntoConstraints = false` 로 지정해주었는데 충돌이 나서 정말 의문입니다😲 제가 혹시 놓치고 있는 지점이 있을까요??
<img width="1121" alt="WTF Auto Layout? 2022-03-24 02-39-08" src="https://user-images.githubusercontent.com/81469717/159763631-35c95d19-bf66-4009-81ce-eee557f86179.png">

<br>

추가적으로 엘림과 전에 메시지로 나누었던 부분과 연결되는 질문인데요, 현재 ProjectManager객체를 `ProjectBoardVC`만 소유하도록 설계가 되어있기 때문에, 그 하위 뷰컨트롤러에서는 델리게이트 패턴을 통해 소통하는 구조인데요. 너무 불필요하게 구조가 복잡해졌다는 생각이 들었습니다. 만약 하위 뷰컨들에서 각각 ProjectManager를 소유하도록(상위 뷰컨에서 하위 뷰컨을 present할 때 넘겨주는 방법)하는 것이 설계상 문제가 없다면 그렇게 바꾸어보고 싶은데요! 이에 대한 엘림의 조언 부탁드립니다😊

2022-03-24 14:22 UTC, lina0322 requested changes
안녕하세요, 릴리!

짧은 기간동안 코드에서 많은 발전이 있었어요ㅎㅎ
이제는 프로젝트를 거의 마무리하는 과정이네요. 
캠프도 마무리 과정에 돌입한 것 같고요!!
길게 한 프로젝트니까, 아직 구현 못한 부분들도 꼼꼼히 살펴서 마무리해봅시다~

약간의 버그들이 있어요🤧
이 부분들도 함께 수정할 수 있을까요~?

1. 일부 기종에서 사이드가 짤립니다!
![IMG_0008](https://user-images.githubusercontent.com/49546979/159935915-d0c3214a-5bea-422a-aefc-8f497eddd15e.png)

2. 말 줄임표가 나오지 않아요~
![스크린샷 2022-03-24 오후 10 14 28](https://user-images.githubusercontent.com/49546979/159935989-635f813d-8395-4d1f-9bbc-3ca6b5cafe6e.png)

3. done에서도 빨간 글씨가 유지되고있네요!
![스크린샷 2022-03-24 오후 10 15 00](https://user-images.githubusercontent.com/49546979/159936004-59d9d1a2-7e5f-4083-8c73-0da112d3464c.png)

---

남은 구현 부분도 이번주 가기 전엔 해봅시다.
할 수 있습니다~ 화이팅🎉
이해 안가는 것 있으면 디엠주세욥😎

2022-03-24 14:22 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoard/ProjectListViewController.swift
> -    private func secondStatusModificationPopoverUIAlertAction(with identifier: UUID) -> UIAlertAction {
first랑 second로 나누어진 부분 및 내부 코드들도 상당히 중복되는데, 수정할 수 있는 방법은 없을까요?💁🏻‍♀️

2022-03-24 14:22 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoard/ProjectListViewController.swift
> +    ) -> UISwipeActionsConfiguration? {
`tableView(_:editingStyleForRowAt:)`이 함수도 알아두면 좋겠어요😄

2022-03-25 07:59 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/NetworkAlertController.swift
> +import Foundation
Network가 끊겼을 때 사용자에게 보여줄 alert를 위한 커스텀컨트롤러 였는데요~
NetworkManager안에서 바로 `UIAlertController`로 생성을 해서 present해줘서 삭제했습니다~!

2022-03-25 08:04 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoard/DataSourceConfigViewController.swift
> +class DataSourceConfigViewController: UIViewController {
DONE: fianl 키워드 적용하기✏️

2022-03-25 08:13 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoard/DataSourceConfigViewController.swift
> +    weak var projectManager: ProjectManager?
`DataSourceConfigVC`는 사용자로부터 선택 액션을 받아서 모델인 `ProjectManager`에게 알리고,
`ProjectManager`의 데이터소스타입이 바뀌었을 때 델리게이트 패턴을 통해 `ProjectBoardVC`애게 뷰를 업데이하는 흐름으로 설계했습니다~! 
혹시 `weak` 키워드는 없어야 하는 것일까요..?

2022-03-25 08:43 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Model/ViewNameSpace/DataSourceConfigScene.swift
> +    case firestore = "Cloud"
처음 의도는 DataSourceConfigViewController에서 사용되는 스트링이라 여기에 모아두었는데요~
엘림 조언대로 `DataSourceType`에 관련 스트링이 있는게 관리하기 더 좋을 것 같습니다👍

사용자에게 보여질 문구는 `userDescription`이라는 연산 프로퍼티로 제공하도록 수정했습니다.
```swift
enum DataSourceType {
    
    case inMemory
    case coreData
    case firestore
    
    var userDescription: String {
        switch self {
        case .inMemory:
            return "휘발성"
        case .coreData:
            return "앱"
        case .firestore:
            return "Cloud"
        }
    }
}
```

다만 기존 설계는 DataSourceType의 Int rawValue와 selectedIndex가 의존성이 너무 큰 것이
걸려서 `dataSourceTypes`라는 배열을 만들어서 의존성을 줄여주었습니다.
(기존 설계는 Segment에 반드시 DataSourceType이 case 순서대로 들어가야했습니다. ProjectManager에게 바뀔 DataSourceType을 전해줄 때도 selectedIndex로 DataSourceType을 생성했습니다)
```swift
final class DataSourceConfigViewController: UIViewController {
    
    let dataSourceTypes: [DataSourceType] = [.inMemory, .coreData, .firestore]
  
    private lazy var sourceSegmentedControl: UISegmentedControl = {
        let dataSourceTypeDescriptions = dataSourceTypes.map { dataSource in
            return dataSource.userDescription
        }
        let segmentedControl = UISegmentedControl(items: dataSourceTypeDescriptions)
...
```

`DataSourceConfigViewController`에서만 사용될 "프로젝트 저장소를 선택해주세요☝️"는 어디에 위치하는 것이 좋을까요??
현업에서는 뷰컨트롤러에서 쓰이는 사용자에게 보여지는 String은 어떻게 관리하는지 궁금합니다😃

2022-03-25 09:00 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoard/DataSourceConfigViewController.swift
> +                                                          DataSourceConfigScene.firestore.rawValue])
위 이슈에서 함께 수정했습니다:)

2022-03-25 10:06 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoard/DataSourceConfigViewController.swift
> +    }
popoverController로 뷰컨이 띄어질 경우 뷰컨의 뷰 사이즈를 정의해주고 있습니다. preferredContentSize 사이즈가 따로 정의 되어있지않으면 시스템이 정해둔 default사이즈를 사용한다고 알고 있습니다.

preferredContentSize에 CGSize(width: 300, height: 150)를 대입해서 제약 충돌을 해결해주었습니다👍

그런데 다만 팝오버의 뷰가 뷰디버거에서 보이는 것보다 더 작게 보이더라구요..
<img width="1332" alt="스크린샷 2022-03-25 오후 6 45 14" src="https://user-images.githubusercontent.com/81469717/160096494-5b556065-33d7-4d8d-bd97-fa2b3c9b46c2.png">
그래서 margin으로 준 제약을 10에서 30으로 늘려주었는데요!
조금더 작게 보이는것이 팝오버의 특징인걸까요? 이렇게 해결해주는 것이 최선인걸까요??🥲

2022-03-25 12:07 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoard/DataSourceConfigViewController.swift
> +        segmentedControl.addAction(action, for: .valueChanged)
특정 캐릭터나 범위에 attribute(textcolor, font, shadow등..)을 적용할 수 있는 String이라고 알고 있습니다~!

2022-03-25 14:11 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoard/DataSourceConfigViewController.swift
> +        self.view = .init()
viewDidLoad로 옮겨도 똑같이 작동할 것 같습니다~
좀더 공부해보니 loadView에서는 view만 만들어서 리턴하는 것이 더 맞는 것 같고,
현재 제 코드에서는 커스텀뷰를 뷰컨트롤러의 view로 사용하고 있지 않으니, 
굳이 loadview를 사용할 필요가 없는 것 같습니다!

viewdidload로 작업들 다 옮기도록할게요~!

2022-03-26 06:46 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoard/ProjectListViewController.swift
> -    private func secondStatusModificationPopoverUIAlertAction(with identifier: UUID) -> UIAlertAction {
먼저 각 프로젝트 상태이동을 정의하는 UIAlertAction을 생성하는 메서드를 만든후, 
현재 보유하고 있는 프로젝트의 상태에 따라 두개의 UIAlertAction을 반환하는 메서드를 만들어서 중복되는 코드를 줄여주었습니다!
그럼에도 switch문 내의 코드는 상당히 반복되는 듯한 느낌이 들었습니다🥲

Strategy Pattern이라는 디자인 패턴을 이번에 활동학습을 통해 알게되었는데요~
현재 제가 Status를 열거형으로 정의했고, 이 Status는 행동을 정의할 수 있는 특징이 있습니다. 때문에 Strategy Pattern을 사용해서 각 Status를 각각의 객체로 분리하는 방법도 적용해 볼 수 있을 거라 생각했습니다.

지금과 같은 상황에 StrategyPattern을 적용하는 것이 제 코드의 중복성을 줄이고, 더 나은 코드를 작성하는데 해결방안이 될 수 있을까요??🧐

2022-03-26 07:06 UTC, yeahg-dev commented
엘림! 🧚
이번 리뷰들을 통해서 또 많이 배워갑니다🤓
감사드립니다!!👍

발견해주신 버그들은 아래와 같이 픽스해보았습니다.
> 
> 1. 일부 기종에서 사이드가 짤립니다!
>    ![IMG_0008](https://user-images.githubusercontent.com/49546979/159935915-d0c3214a-5bea-422a-aefc-8f497eddd15e.png)

info.plist에서 ` Launch screen interface file base name` key가 삭제되어 발생하는 버그로 확인했습니다.
LauchScreenStoryBoard 나 info.plist의 ` Launch screen interface file base name`키가 존재하지 않는 경우 앱은 최신 버전이 아닌, 하위버전 호완성(backward-compatibility)만 지원하도록 앱을 실행시켜서 스크린 사이즈가 작아진다고 합니다.[관련 스택오버플로우](https://stackoverflow.com/questions/38264901/how-to-removeor-not-use-launch-screen-storyboard-in-xcode-with-swift)

🔨 **`Launch screen interface file base name` key를 info.plist에 추가해주는 방법으로 해결했습니다**

<br>

> 2. 말 줄임표가 나오지 않아요~
>    ![스크린샷 2022-03-24 오후 10 14 28](https://user-images.githubusercontent.com/49546979/159935989-635f813d-8395-4d1f-9bbc-3ca6b5cafe6e.png)

```swift
 label.lineBreakMode = .byTruncatingTail
```
위 코드를 UILabel에 추가해주었습니다.

<br>


> 3. done에서도 빨간 글씨가 유지되고있네요!
>    ![스크린샷 2022-03-24 오후 10 15 00](https://user-images.githubusercontent.com/49546979/159936004-59d9d1a2-7e5f-4083-8c73-0da112d3464c.png)

프로젝트 상태가 Done일 때만 데드라인이 검정색으로 표시되는데요,
이는 비지니스 로직이라고 생각하여 Project내부에 `deadlineColor`라는 연산프로퍼티를 구현해주었습니다.
다만 모델에 뷰와 관련된 코드가 들어가서 MVC에 위배되는 건 아닌가? 라는 고민도 들었습니다🥲
(조금 뷰모델스러운 코드가 된게 아닌가 싶네요,,,)
```swift
struct Project {
    ...

    var isExpired: Bool {
        let currentDate = Date()
        guard let deadline = self.deadline else {
           return false
        }
        return deadline < currentDate
    }
    
    var deadlineColor: UIColor {
        get {
            if status == .done {
                return .black
            }
            if isExpired == true {
                return .red
            } else {
                return .black
            }
        }
    }
    
```

2022-03-26 07:36 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoard/DataSourceConfigViewController.swift
> +    weak var projectManager: ProjectManager?
아, 약간.. 네이밍이 어색해서 여쭤보았습니당🙏
매니저는 보통 데이터매니저나 뷰모델같은 느낌인데, weak가 있어서 딜리게이트인가? 했던거같아요~🥲

2022-03-26 07:37 UTC, lina0322 commented on ProjectManager/ProjectManager/Model/ViewNameSpace/DataSourceConfigScene.swift
> +    case firestore = "Cloud"
따로 문자열을 관리하는 편이긴하죠! 관련있는 String을 모두 모아서 Enum으로 만드는건 어떨까요?😎

2022-03-26 07:42 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoard/ProjectListViewController.swift
> -    private func secondStatusModificationPopoverUIAlertAction(with identifier: UUID) -> UIAlertAction {
못먹어도 고! 지금은 공부하는 과정이니까, 해볼까 말까 할때는 해보고
각각의 장점 단점을 느껴야해요!!!
회사가면.. 이렇게 해보고 저렇게 해볼 시간이 많이 없으니까요😭

2022-03-26 07:56 UTC, lina0322 approved these changes
릴리~ 이번 프로젝트 정말 고생 많았어요.
사실ㅇ ㅏ직 todo가 많이 남았지만, 다음을 기약하며 요기서 마무리 합시다!
그래도 추가로 궁금한거나 질문 있으면 언제든지 편하게 메세지주세요🙏

2022-03-26 07:56 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoard/DataSourceConfigViewController.swift
> +        }
축약형으로 표현하면 어떻게 할 수 있나욥?!

2022-03-26 07:56 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoard/DataSourceConfigViewController.swift
> +        self.preferredContentSize = CGSize(width: 300, height: 150)
이 코드 viewDidLoad에서하면 어떻게되나요?🤔

2022-03-26 07:57 UTC, merged

2022-03-26 09:58 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoard/DataSourceConfigViewController.swift
> +        self.preferredContentSize = CGSize(width: 300, height: 150)
viewDidLoad에서 호출해주오도 동일한 결과 나타나네요??! 
viewDidLoad에서 호출해주는게 맞을까요??

2022-03-26 09:59 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoard/DataSourceConfigViewController.swift
> +        }
```swift
  let dataSourceTypeDescriptions = dataSourceTypes.map { $0 in
            $0.userDescription
        }
```
이렇게 쓸 수 있을것 같아요~

2022-03-26 13:37 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoard/DataSourceConfigViewController.swift
> +        self.preferredContentSize = CGSize(width: 300, height: 150)
보여줄때마다 사이즈를 정하는 느낌이 아니라, 처음에 로드할 때 정해지는거니까 viewDidLoad가 맞지 않을까요??😀
왜 이전에는 여기에 있었을까요, 히스토리를 다시 떠올려봅시당

2022-03-28 05:56 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoard/DataSourceConfigViewController.swift
> +        self.preferredContentSize = CGSize(width: 300, height: 150)
헛 그러네요! 불필요한 계산일 수 있겠어요~
감사합니다!ㅎㅎ