프로젝트 관리 앱 [STEP2-1] 두기
yagom-academy/ios-project-manager pull request #132
Opened 2022-07-07 11:11 UTC by doogie97

@TTOzzi
안녕하세요 또치!
이번 프로젝트는 분기를 나눠서 PR을 보내도 된다고 하셔서 뷰 구성을 마친 뒤 2-1 PR보냅니다!
***

### 1. 뷰컨트롤러에 구성 vs 뷰 생성후 뷰컨트롤러에서 사용
가장 많이 고민한 부분은 mvvm 패턴을 구현함에 있어 viewcontroller도 뷰의 역할을 하도록 하려고 했는데 지금 
`MainView`처럼 뷰컨트롤러에서 뷰구성을 다 하는게 좋을지 
아니면 `DetailView`처럼 뷰를 만들고 그 뷰를 뷰컨트롤러에서 가져와 쓰면서 추가적으로 구성을 해야하는 경우가 있다면 그럴때만 뷰컨트롤러에서 만들면 좋을지
(ex mainviewcontroller의 navigationBar에 접근하기 위해서는 view에서 접근을 못하니 어쩔 수 없이 뷰컨트롤러에서 추가해줘야함) 

이 부분을 가장 고민을 많이 했는데 코드로 뷰구성을 하게 된다면 보통 어떻게 작성하는지 궁금합니다

### 2. RxSwift
rx를 처음 써보다보니 코드를 작성함에 있어 잘 기준이 서지 않았습니다 그래서 전반적으로 한번 봐주시고 피드백 주시면 너무 감사할 것 같습니다!(사소한 것이어도 너무 좋습니다!)

2022-07-09 15:43 UTC, TTOzzi requested changes
안녕하세요 두기 👋
남겨드린 코멘트와 답변 보시고 이해가 어려운 부분이 있다면 언제든 디엠주세요!
고생하셨습니다 🙇‍♂️ 

### 1. 뷰컨트롤러에 구성 vs 뷰 생성후 뷰컨트롤러에서 사용

> 가장 많이 고민한 부분은 mvvm 패턴을 구현함에 있어 viewcontroller도 뷰의 역할을 하도록 하려고 했는데 지금
> `MainView`처럼 뷰컨트롤러에서 뷰구성을 다 하는게 좋을지
> 아니면 `DetailView`처럼 뷰를 만들고 그 뷰를 뷰컨트롤러에서 가져와 쓰면서 추가적으로 구성을 해야하는 경우가 있다면 그럴때만 뷰컨트롤러에서 만들면 좋을지
> (ex mainviewcontroller의 navigationBar에 접근하기 위해서는 view에서 접근을 못하니 어쩔 수 없이 뷰컨트롤러에서 추가해줘야함)
>
> 이 부분을 가장 고민을 많이 했는데 코드로 뷰구성을 하게 된다면 보통 어떻게 작성하는지 궁금합니다

상황에 따라, 구현하는 사람의 취향..?에 따라 다를 것 같은데 저는 대체적으로 뷰 생성/초기 설정 코드가 길어지거나 재사용될 때 별도의 뷰로 분리해주는 편이에요.
메인화면도 뷰 구성을 뷰컨에서 다 하셨다곤 하셨지만, `HeaderVIew` 같은 건 나눠두셔서 어찌보면 일부분 분리해뒀다고 볼 수도 있을 것 같아요.
코멘트로 남겨둔 `테이블뷰, 헤더뷰 생성 -> 스택뷰 생성이 반복되는 부분` 도 커스텀 뷰 클래스를 만들어 분리할 수도, 뷰컨 내부에서 뷰 생성/설정 후 반환하는 팩토리 메서드를 만들 수도 있어서 정말 선택하기 나름인 것 같습니다 :thinking:
적절히 잘 읽히도록, 특정 파일이 길어지지 않도록 역할에 맞게 분리해주시면 될 것 같아요! (지금도 잘 해주셨어요)

### 2. 뷰의 입체성(?)

> 위 뷰 요소들을 스토리보드에서 옵션 하나하나 살펴봐도 이렇게 입체성을 나타내는 옵션을 찾지 못했는데 이런건 어떤 키워드로 찾아봐야 하는지 여쭤보고싶습니다!

뷰에 그림자 효과를 적용한 것 같네요! `uiview shadow` 정도로 검색해보시면 많이 나올 것 같습니다 :slightly_smiling_face:

### 3. RxSwift

> rx를 처음 써보다보니 코드를 작성함에 있어 잘 기준이 서지 않았습니다 그래서 전반적으로 한번 봐주시고 피드백 주시면 너무 감사할 것 같습니다!(사소한 것이어도 너무 좋습니다!)

이번 PR엔 rx를 활용할만한 곳이 많이 없어서 간단하게만 남겨뒀어요 :bow:

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/Extension/Date + Extension.swift
> +        let dateFormatter = DateFormatter()
매번 호출할 때 마다 `DateFormatter`를 새로 만들게 될텐데, `DateFormatter`는 생성/설정에 리소스가 많이드니 하나만 만들어두고 재사용하도록 구현하는 게 좋을 것 같아요.
앱에서 날짜를 표기하는 부분이 많은 것 같아서요 🤔

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/Detail/DetailView.swift
> +    lazy var naviItem: UINavigationItem = {
`private` 접근 제한을 풀어주기 전, `private`을 유지한 채로 필요한 로직만 외부로 노출하도록 할 순 없을지 한번 고민해보시고 풀면 좋을 것 같아요.
풀어줄 때도 `private` -> `private(set)` -> `internal` 의 순서가 되면 더 좋을 것 같구요.

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/Detail/DetailViewController.swift
> +    }
의존성을 가지는 객체를 생성자로 주입받도록 구현하신 것 너무 좋습니다 🙂 
나중엔 주입받는 객체가 뷰모델이 될 것 같네요.

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/Detail/DetailViewController.swift
> +        self.view = detailView
뷰컨의 뷰를 교체할 땐, 뷰컨의 라이프 사이클에 맞게 `loadView` 시점에 교체해주는 게 좋을 것 같아요.
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621454-loadview

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/Detail/DetailViewController.swift
> +        detailView.bodyTextView.text = list.body
`DetailView`의 내부 구현을 숨기고, `List`를 메서드로 전달해서 `DetailView` 내부에서 업데이트 해줄 순 없을까요? 👀

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +final class HeaderVIew: UIView {
I 가 대문자예요! +_+

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +    lazy var countLabel: UILabel = {
여기도 사용하는 부분을 봤을 때, `private(set)`까진 가능해보이네요.

추가로.. 지금 예시는 조금 과하긴 한데 특정 뷰에 `Reactive` extension 을 구현해서 코드를 축약하거나, 내부 구현의 노출을 줄이는 등의 처리가 가능합니다.
`countLabel`은 `fileprivate` 으로 선언하고, 같은 파일에 `Reactive` extension 을 구현
```swift
extension Reactive where Base == HeaderVIew {
    var countLabelText: Binder<String?> {
        return base.countLabel.rx.text
    }
}
```
사용하는 곳은
```swift
lists
    .map { "\($0.count)"}
    .bind(to: headerView.rx.countLabelText)
    .disposed(by: disposbag)
```
요런식으로요!
유용하게 쓰일 때가 많으니 이런 방법이 있다는 것 정도만 알아두심 좋을 것 같아요.
(방법을 알려드릴 만한 예시가 나와서 말씀드리는 것일 뿐, 현재 구현에선 꼭 이렇게 구현 안 하셔도 됩니다. 과해요!)

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +            $0.top.leading.bottom.equalToSuperview().inset(10)
레이아웃을 설정해줄 땐 항상 4방향(or 높이/너비)을 모두 잡아주셔야 합니다.
현재는 라벨에 표시할 텍스트가 길어지면 가로 화면 범위를 벗어날 것 같네요 🤔

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +    private var disposbag = DisposeBag()
`disposbag` 오타인 것 같아요 +_+

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +        self.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(didTapAddButton))
DM 으로도 질문주셨던 것 같은데, `UIBarButtonItem`의 이벤트 처리도 일관되게 rx를 활용해볼 수 있을 것 같아요.

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +        self.navigationController?.present(detailVC, animated: true, completion: nil)
`navigationController`에서 `present` 해줘야 하는 이유가 궁금해요.
현재 뷰컨에서 `present` 해줄 수도 있지 않나요? 👀

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +            cell.deadlineLabel.textColor = self.mainViewModel.isOverDeadline(list: item) ? .red : .label
요기도 캡슐화를 지켜주면서 셀 내부에서 처리하도록 바꿔볼 수 있을 것 같습니다.

`isOverDeadline` 같은 화면에 표시해주기 위한 가공 로직이 필요하다면, 셀을 위한 뷰모델을 별도로 만들어줄 수도 있을 것 같아요.

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +            .map{ $0.filter { $0.type == type }}
갖고 있는 리스트의 상태를 구분하는 로직은 뷰컨이 아닌, 뷰모델에서 수행해주면 더 좋을 것 같아요.
추가로 리스트의 개수가 많아졌을 때, 효율성에 문제가 생기진 않을까요? 👀

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +                                         doneStackView])
사소하지만 아래의 스택뷰 선언과 미묘하게 컨벤션이 다르네요. 요런 사소한 것도 일관되게 작성해주시면 코드 퀄리티가 좋아보입니다.

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +    }()
테이블뷰, 헤더뷰 생성 -> 스택뷰 생성이 완전히 똑같은 코드로 반복되고 있네요 🤔
줄여볼 수 있을까요?

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +                           forCellReuseIdentifier: "\(ListTableViewCell.self)")
요런건 실수를 줄이기 위해 extension 으로 모든 셀이 타입 이름으로 identifier 를 갖고, 반환할 수 있도록 구현해주는 게 좋아요.
`tableView`의 `register`를 확장해서 `ListTableViewCell` 라는 셀 타입만 넘겼을 때, 알아서 `identifier` 를 뽑아내서 설정하도록 해줄 수도 있을 것 같구요.

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/ViewModel/MainViewModel.swift
> +    var listObservable = BehaviorRelay<[List]>(value: [])
이번 구현의 범위는 UI 만 해당하는 것 같으니, 살짝만 코멘트 남기면 뷰모델 구현하시기 전에 input(or action), output(or state) 구조로 구현된 여러 예시 코드를 쭈욱 훑어 보시고 구현해주세요 🙏 
`rxswift mvvm input output` 이란 키워드로 검색하시거나 `https://github.com/kickstarter/ios-oss` 와 같은 mvvm 으로 구현된 프로젝트들을 찾아보시면 좋을 것 같습니다 🙂

2022-07-09 15:43 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +                self?.didtapCell($0)
사용자의 액션 -> 뷰에 결과 반영 의 흐름은 웬만하면 뷰모델을 거치도록 구현하는 게 좋아요.
뷰모델에 `사용자가 셀을 눌렀어!` 라는 액션을 전달하고, 뷰모델에선 그에 따른 로직(`선택한 index에 맞는 리스트 찾기`)을 거친 후 결과값으로 `상세 화면을 띄워줘!` 라는 걸 뷰컨으로 전달해서 화면을 띄워주도록요.

그래야 나중에 셀을 눌렀을 때 해야하는 로직을 추가/수정해야하는 경우 뷰모델의 수정만으로 비교적 간단하게 해결이 가능합니다.
예를들면.. 셀을 눌렀을 때 서버로 로그를 전송해달라거나, 화면을 이동할 수 있는 상태인지 확인한다거나 하는 케이스가 있겠네요 🤔

2022-07-09 16:04 UTC, TTOzzi commented on ProjectManager/ProjectManager/Model/List.swift
> +struct List {
다른 분 PR 리뷰하다 여기도 놓친 것 같아서 추가로 남깁니다! 
`List`라는 이름보단 하나의 작업 단위임을 명시해줄 수 있도록 이름을 명확하게 바꿔주면 더 좋을 것 같아요.

2022-07-10 02:53 UTC, doogie97 commented on ProjectManager/ProjectManager/Extension/Date + Extension.swift
> +        let dateFormatter = DateFormatter()
date변환 기능은 지속적으로 사용한다고 생각해서 static으로 DateConverter를 만들어서 사용해봤는데 그냥 뷰컨트롤러에서 데이터포메터 인스턴스를 만들어서 하는게 더 나을까요??

그리고 만약에 지금 처럼 객체로 만든다고 가정했을 때 폴더 분류는 어떻게 해야할까요?? (이렇게 데이트 변환을 위한 객체가 들어가야하는 폴더 이름?)

2022-07-10 02:57 UTC, doogie97 commented on ProjectManager/ProjectManager/View/Detail/DetailViewController.swift
> +    }
리뷰가 달리기 전에 기능 구현에 대해서 고민을 해봤는데 또치 말씀대로 나중에는 뷰모델로 변경이 될 것 같습니다!

2022-07-10 02:58 UTC, doogie97 commented on ProjectManager/ProjectManager/View/Detail/DetailViewController.swift
> +        self.view = detailView
말씀하신대로 뷰 교체하는 로직은 `viewDidLoad`로 이동하였습니다

2022-07-10 03:27 UTC, doogie97 commented on ProjectManager/ProjectManager/View/Detail/DetailViewController.swift
> +        detailView.bodyTextView.text = list.body
말씀하신대로 DetailView 구현부를 숨기고 메서드 하나만 열어둬서 뷰를 구성할 수 있게 하였습니다!

2022-07-10 03:28 UTC, doogie97 commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +final class HeaderVIew: UIView {
허걱 
이부분이랑 아래 disposeBag 부분 오타 수정하였습니다!

2022-07-10 03:31 UTC, doogie97 commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +    lazy var countLabel: UILabel = {
아! 이 부분 꼭 뷰에 표시할 때 뿐만 아니라 나중에 디테일 뷰에서 받아올 때 어떤 방법을 써야하나 고민 하던 부분인데 그 때 참고해 보도록 하겠습니다!
(사실 반대로 생각하면 쓸 수 있지 않을까 생각을 하고있는거긴 하지만 직접 해봐야 알 것 같습니다...!)

2022-07-10 03:47 UTC, doogie97 commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +            $0.top.leading.bottom.equalToSuperview().inset(10)
trailing의 제약 또한 설정해주었습니다!

2022-07-10 03:49 UTC, doogie97 commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +        self.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(didTapAddButton))
아 이부분은 제가 질문을 드리고 싶은 부분인데

<img width="651" alt="detailView cancleButton rx tap asObservable()" src="https://user-images.githubusercontent.com/82325822/178130469-c183a77c-4cac-4f20-bae5-ab8bf4887921.png">

1번 방법은 rx를 통해 버튼 연결을 한것이고 2번 방법은 기존 방식대로 objc func를 이용해 연결한 것인데 이 둘의 차이가 없는 것 처럼 느겨져서…
혹이 둘 사이의 차이가 무엇이며 1번 방법 처럼 사용하면 얻는 이점이 어떤게 있는지 여쭤보고 싶습니다!

2022-07-10 03:51 UTC, doogie97 commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +        self.navigationController?.present(detailVC, animated: true, completion: nil)
아 이건 처음에 modal을 띄울 때도 navigationController에서 present하면 navigationBar를 쓸 수 있지 않을까 해서 시도해보다가 수정을 하지 않은 것 같습니다 
self.present 로 수정하였습니다!

2022-07-10 04:00 UTC, doogie97 commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +            cell.deadlineLabel.textColor = self.mainViewModel.isOverDeadline(list: item) ? .red : .label
캡슐화를 해 메서드를 통해 뷰를 구성할 수 있게 하였습니다
다만, `isOverDeadline` 의 경우는 cell이 판단하는 것보다는 mainViewModel이 판단해 넘겨주는 것이 맞다고 생각해 bool값을 넘겨주도록 하였습니다
(cell이 아닌 다른 곳에서도 사용할 여지가 있어서..?)

2022-07-10 04:07 UTC, doogie97 commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +            .map{ $0.filter { $0.type == type }}
리스트를 분리하는 기능은 뷰모델이 갖고있는 기능이 맞네요! 바로 옮겨주었습니다

그리고 리스트의 개수를 말씀해주셨는데 제가 처음에는 todo, doing, done 세 개의 옵저버블을 만들어서 운용을 해보려고 했는데 기능 구현 부분을 공부하던 중에 각각 따로 구현해 줬을 , crud를 적용하게 되면 어떻게 뷰 모델에서 어떤 타입의 리스트의 옵저버블인지 구분을 해야할 지 모르겠더라구요...(사실 정확하게 말하면 할 수 는 있는데 분기를 나누게 되는 로직이 많아져서 관리하는 측면에서 지금의 코드가 더 낫다고 생각했습니다)

또치가 말씀하신 의도는 어떤 방법인지 제가 알 수 있을까요?!

2022-07-10 04:14 UTC, doogie97 commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +    }()
```swift
    private func listsStackView(headerView: HeaderView, tableView: UITableView) -> UIStackView {
        let stackView = UIStackView(arrangedSubviews: [headerView,
                                                       tableView])
        stackView.axis = .vertical
        stackView.spacing = 1
        
        return stackView
    }
```
위와 같이 stackView를 반환해주는 메서드를 통해

```swift
    private lazy var mainStackView: UIStackView = {
        let stackView = UIStackView(arrangedSubviews:[listsStackView(headerView: todoHeaderView,
                                                                     tableView: todoTableView),
                                                      listsStackView(headerView: doingHeaderView,
                                                                     tableView: doingTableView),
                                                      listsStackView(headerView: doneHeaderView,
                                                                     tableView: doneTableView)])
```

이렇게 구성해보았는데 말씀하신 방법이 이런 방법이 맞을까요??

2022-07-10 04:27 UTC, doogie97 commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +                           forCellReuseIdentifier: "\(ListTableViewCell.self)")
제가 나름 실수를 줄이기 위해 항상 해당 `셀.self`를 사용하자 라는 스스로의 규칙으로 사용을 하고 있었는데
`extension`으로 구현을 한다고 하면 어떤걸 extension을 해야할까요??

그리고 두번 째 방법은
![image](https://user-images.githubusercontent.com/82325822/178131162-1f0cafb8-50dc-4656-ad7d-cc9e2ad0865b.png)
이런 방법을 말씀하신건가 생각이 들어 구현해봤는데 위와같은 오류가 뜨더라구요
(확인 해 보니 ListTableViewCell.self를 하면 ListTableViewCell.Type이 나오는 위와 같은 방법으로 하면 그냥 그대로 UITableViewCell만 나와서 적용이 안됐음)

```swift
extension UITableView {
    func register(_ cellType: UITableViewCell.Type) {
        self.register(cellType, forCellReuseIdentifier: "\(cellType)")
    }
}
```
그래서 위와 같은 로직을 통해서 수정해봤는데 이 방법이 말씀하신 방법이 맞을까요??

2022-07-10 04:53 UTC, doogie97 commented on ProjectManager/ProjectManager/ViewModel/MainViewModel.swift
> +    var listObservable = BehaviorRelay<[List]>(value: [])
이 부분은 제가 공부를 조금 해본 뒤 적용해 보도록 하겠습니다!

2022-07-10 04:55 UTC, doogie97 commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +                self?.didtapCell($0)
제가 이 부분이 잘 이해가 되지 않아서 추가 질문을 드려야 할 것 같습니다

`modelSelected`를 사용하면 $0에 List가 바로 들어와서 그걸 그대로 표시해주는 역할을 했는데 이런 방식이 아닌 `itemSelected`를 이용해 선택한 index만 뷰모델로 넘겨주고 뷰 모델에서 해당 index에 해당하는 List를 넘겨줘서 그 List를 뷰에 표시하게 하라는 말씀이 맞을까요??

(이 방식이 맞다면 뷰모델의 옵저버블이 하나로 통합되어있는 것부터 문제가 되니 로직수정이 불가피 할것 같긴하지만...)

2022-07-10 05:09 UTC, doogie97 commented on ProjectManager/ProjectManager/Model/List.swift
> +struct List {
List -> ListItem으로, Lists -> List 가 될 수 있도록 전체적으로 수정하였습니다

2022-07-10 05:11 UTC, doogie97 commented on ProjectManager/ProjectManager/View/Detail/DetailView.swift
> +    lazy var naviItem: UINavigationItem = {
순서 명심하도록 하겠습니다!

2022-07-10 10:20 UTC, TTOzzi commented on ProjectManager/ProjectManager/Model/DateConverter.swift
>          dateFormatter.dateFormat = "yyyy. M. d."
> date변환 기능은 지속적으로 사용한다고 생각해서 static으로 DateConverter를 만들어서 사용해봤는데 그냥 뷰컨트롤러에서 데이터포메터 인스턴스를 만들어서 하는게 더 나을까요??

음 만드신 `DateConverter` 가 큰 역할 없이 사실상 설정된 `DateFormatter`를 한 번 래핑해둔 형태로만 보여서 `DateFormatter`의 extension 으로 static 상수를 하나 선언해두는 것도 괜찮을 것 같아요.
지금도 `DateFormatter`를 설정하는 코드가 매번 불필요하게 반복되고 있는 것 같아서요 🤔 

물론 사용할 땐 `static` 이더라도 직접 접근이 아닌, 외부로부터 주입받을 수 있는 형태로..
현재는 셀을 꾸며주는데에 사용하고 있으니, 셀에 표시할 데이터를 가공하는 로직을 가진 뷰모델을 정의하고 거기다 주입해주면 더 좋겠네요!

> 그리고 만약에 지금 처럼 객체로 만든다고 가정했을 때 폴더 분류는 어떻게 해야할까요?? (이렇게 데이트 변환을 위한 객체가 들어가야하는 폴더 이름?)

개인마다 팀마다 정하기 나름이라 애매한데, 저라면 `Util` 정도로 분류해줄 것 같네요.

2022-07-10 10:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/Detail/DetailViewController.swift
> +        self.view = detailView
헉 요거 `viewDidLoad`가 아닌 `loadView`를 말씀드린거예요!
> You can override this method in order to create your views manually. If you choose to do so, assign the root view of your view hierarchy to the [view](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621460-view) property. The views you create should be unique instances and should not be shared with any other view controller object. Your custom implementation of this method should not call super.

2022-07-10 10:26 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +            $0.trailing.lessThanOrEqualToSuperview()
그냥 궁금증! `trailing`은 다른 제약 조건과 같이 간격을 10 만큼  띄워줄 필요는 없나요? 👀

2022-07-10 10:35 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +        self.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(didTapAddButton))
(음 일단 예시로 주신 코드에서 `asObservable()`은 없어도 될 것 같아요.)

둘의 차이는 rx에서 제공해주는 operator를 사용할 수 있는가가 젤 큽니다.
지금은 단순 이벤트를 받아 함수 호출만 처리하고 있어서 차이가 없어 보일 수 있어요.

예를 들면, 사용자가 짧은 시간에 여러 번 버튼을 누르는 케이스를 막아주기 위해 `throttle` 을 건다거나, `zip`, `combineLatest`와 같은 operator를 활용해 다른 이벤트 흐름과 합쳐준다거나 할 때 훨씬 쉽게 구현할 수 있을거예요.
이벤트를 뷰모델로 전달해줄 때도 일관되게 rx 의 흐름을 사용해서 간결한 구현이 가능하단 장점도 있을 것 같구요 🤔 

지금 구현도 문제가 있는 구현은 아닙니다 🙇

2022-07-10 10:40 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +            cell.deadlineLabel.textColor = self.mainViewModel.isOverDeadline(list: item) ? .red : .label
지금은 규모가 작은 프로젝트라 구현할 로직이 별로 없어서 딱히 문제되진 않아 보이는데요.
메인 화면에서 처리해야 할 로직이 많아질수록, `mainViewModel`에 구현되는 로직이 많아질거예요.
`mainViewModel` 내부에서도 비즈니스 로직을 다른 객체로 나누거나, 뷰 <-> 뷰모델 관계를 세분화하여 데이터를 뷰에 표시하기 위해 가공하는 포멧팅 로직을 적절히 나눠줄 필요가 있습니다.

요건 천천히 스텝 진행하시면서 고민해보아요 🙂

2022-07-10 10:48 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +            .map{ $0.filter { $0.type == type }}
한 곳에서만 변경이 일어나더라도 `listObservable`이 값을 방출하고, 필터링을 위한 세 번의 순회 로직을 수행할거라 비효율적이지 않을까 하는 생각이었습니다!
극단적으로 만들어진 작업의 개수가 만개가 되었다면, 단순히 작업 하나를 todo에 추가하기만 해도 만개 가량의 요소를 총 3번 순회할거라서요 🤔 
해결 방법으론 각각 상태별 리스트를 따로 관리하거나 dictionary를 활용하는 등의 방법이 있을 것 같긴 한데, 앱 퍼포먼스에 영향을 줄 만큼 많은 작업이 만들어지는 상황은 드물 것 같아서 고민해볼만한 포인트인 것 같습니다 🤔 🤔 🤔 
현재 로직에선 뷰모델의 output을 나눈 뒤, 다시 그릴 필요가 있는 상태의 리스트만 값을 방출하도록 해서 `filter` 로직을 줄여볼 순 있을 것 같아요.

2022-07-10 10:53 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +    }()
아하 헤더뷰와 테이블뷰의 참조를 잡아두긴 해야하니 메서드로 줄이기엔 살짝 무리가 있군요.
남아있는 테이블뷰도 3줄짜리 로직이 계속 반복되니 비슷한 방식으로 줄여주면 더 간단해질 것 같습니다.

2022-07-10 11:00 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +                           forCellReuseIdentifier: "\(ListTableViewCell.self)")
넵 실수를 줄인다는 맥락에선 구현하신 방법도 좋은 것 같아요!
셀의 코드만 봤을 때도 이 셀이 어떤 값을 `reuseIdentifier`로 사용하고 있는지 알 수 있도록 해주기 위해, 타입 이름을 `identifier`로 반환하는 프로토콜을 정의해두고 그걸 셀에 채택해준 뒤
```swift
extension UITableView {
    func register(_ cellType: UITableViewCell.Type) {
        self.register(cellType, forCellReuseIdentifier: cellType.identifier)
    }
}
```
의 형태로도 구현해줄 수 있을 것 같아요.

2022-07-10 11:04 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +                self?.didtapCell($0)
넵 뷰모델이 뷰를 표시하기 위한 원천 데이터를 갖고 있을테니, 뷰에선 자기 자신이 어떤 데이터를 표시하고 있는지 / 어떤 데이터가 선택되었는지 알 필요 없이 선택된 셀의 `index` 만을 전달해주고 뷰모델에서 해당하는 데이터를 찾아 다음 동작을 뷰에 전달해주는 형태입니다.

뷰가 알고 있는 정보를 최소화하면, 표시해야할 데이터나 화면과 관련된 로직이 변경되더라도 뷰단의 변경을 최소화 할 수 있을거예요.

2022-07-10 11:05 UTC, TTOzzi approved these changes
요건 머지할게요! 이번 스텝에서 챙기지 못한 부분은 천천히 다음 스텝 진행하면서 챙겨보시죠 🚀

2022-07-10 11:05 UTC, merged

2022-07-11 07:52 UTC, doogie97 commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +            $0.trailing.lessThanOrEqualToSuperview()
![image](https://user-images.githubusercontent.com/82325822/178214811-a315621e-5a75-4eb2-b73b-b74ba7ae069e.png)
그렇게 하게 된다면 이렇게 스택뷰가 뷰를 가득 채우게 되면서 countLabel이렇게 오른 쪽 끝으로 가게됩니다

그렇다고 countLabel의 Priority를 수정해줘서 늘어나게 한다면 circle의 형태로 만듦에 있어 문제가 생겨 스택뷰가 내부의 크기만큼 되도록 설정하였습니다

2022-07-11 15:47 UTC, TTOzzi commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +            $0.trailing.lessThanOrEqualToSuperview()
음 `$0.trailing.lessThanOrEqualToSuperview().inset(10)` 의 형태로 타이틀이 최대로 길어지더라도 10의 간격은 띄워주도록 해줄 수 있지 않을까요?
`countLabel`이 찌그러지는 건 지금도 타이틀이 길어지면 발생할 것 같아요.
지금처럼 `cornerRadius`를 20 고정으로 줄 거라면, `countLabel`의 크기도 40x40으로 고정하는 게 나을 것 같네요 🤔 

요건 사소한 부분이라 꼭 수정하지 않으셔도 됩니다 🙇

2022-07-12 15:06 UTC, doogie97 commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +            $0.trailing.lessThanOrEqualToSuperview()
아 제가 질문을 잘 이해하지 못했었네요 ㅎㅎ
통일감 있게 10을 주었고 원도 찌그러지지 않게 40의 크기로 고정하였습니다!