프로젝트 관리 앱 [STEP2-1] 사파리
yagom-academy/ios-project-manager pull request #133
Opened 2022-07-07 13:25 UTC by saafaaari

# 프로젝트 관리 앱 [STEP2-1]
@TTOzzi
안녕하세요 또치!
사파리 입니다.
정식으로 리뷰를 받는 첫 PR이네요. 
잘 부탁드리겠습니다.

## 구현 사항

이번 스탭에서는 기본적인 UI와 View와 `ViewModel` bind에 포커싱을 맞췄습니다.

![](https://i.imgur.com/UuxONJ3.png)

`Cell`에 들어간 dummy 데이터는 디버그 환경에서만 사용되도록 `#if DEBUG - #endif` 키워드를 사용하였고, `ViewModel` 같은 경우 `protocol`를 이용하여 Input과 Output을 구분지어 주었습니다.

원래 비지니스 로직을 관리하는 타입이 있고, 그 타입을 ViewModel이 의존하는 식으로 구현하려 했으나 현 시점에서 비지니스 로직이 없다고 판단되어 따로 분리하지 않았습니다.

## 다음 구현 계획
- Todo Cell 추가및 삭제
- ViewModel과 UseCase(비지니스 로직을 관리하는 타입) 분리
- Coordinator 패턴 적용

## 조언받고 싶은 부분
1. MVVM 구조

아직 코드 크기가 매우 작아 구조라고 할 것이 없지만, 지금까지 구현 시점에서 MVVM 구조에 벗어난 부분이 있으면 조언 부탁드립니다.

2. Rx사용법

RxSwift를 처음 접하다 보니 많이 어렵다고 느껴졌습니다. 때문에 토니가 보시기에 RxSwift 사용에 있어 어색한 부분이 있으면 말씀 부탁드리겠습니다.

## 변경사항

라이브러리 부분에서 STEP1 RP 때와 달라진 부분이 있습니다. 
전 PR에서 코멘트로 말씀드렸던 대로 SwiftLint 라이브러리를 삭제하였습니다. 이유는 혼자 프로젝트를 진행하는 부분에 있어 SwiftLint를 사용하여 의존성 관리도구를 CocoaPods를 쓰는것 보다 삭제하고 SPM를 사용하는 것이 좀더 큰 이점이 있을거라 판단되어 이 부분이 변경되었습니다. 
README도 업데이트 진행하도록 하겠습니다.

2022-07-07 13:27 UTC, Siwon-L commented on ProjectManager/ProjectManager/Entities/TodoModel.swift
> +}
State 타입을 이용하여 todo, doing, done로 구분지어 주었습니다.

2022-07-07 13:35 UTC, Siwon-L commented on ProjectManager/ProjectManager/Presentation/TodoListViewController.swift
> +              }.disposed(by: bag)
테이블뷰 상단에 있는 숫자 count같은 경우 do 오퍼레이터를 사용하였고, 테이블뷰 같은 경우 bind 오퍼레이터를 사용하였습니다.

2022-07-07 13:36 UTC, Siwon-L commented on ProjectManager/ProjectManager/Presentation/TodoListViewModel.swift
> +protocol TodoListViewModel: TodoListViewModelInput, TodoListViewModelOutput {}
위와 같이 protocol를 이용하여 Input과 Outout을 구분 지었습니다.

2022-07-07 13:38 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoListViewModel.swift
> +        }
`filter`를 활용하여 todo, doing, done으로 구분된 `Observable`을 만들었습니다.

2022-07-07 13:42 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/Utils/Extensions/Date+ToString.swift
> +}
Date 타입을 확장하여 Data 타입을 String 타입으로 변환시키는 기능을 구현하였는데 로직을 이러한 방법으로 관리하는 것이 올바른 방법인지 궁금하고, 올바르지 않다면, 어떤식으로 관리하면 좋을지 이야기를 나눠보고 싶습니다.  🥲

2022-07-07 13:51 UTC, Siwon-L commented on ProjectManager/ProjectManager/Presentation/Utils/Protocols/CellIdentifiable.swift
> +}
CellIdentifiable 프로토콜을 사용하여 채택한 Cell은 identifier를 가지도록 하였습니다.

2022-07-09 18:49 UTC, TTOzzi requested changes
안녕하세요 사파리~!
PR 내용에 남겨주신 조언받고 싶은 부분에 대해선 대부분 코멘트로 해결되었다고 생각되는데, 혹시나 제가 놓친 부분이 있다면 언제든지 말씀해주세요 🙏 
남겨드린 코멘트 중 이해하기 어려운 부분도요!
고생하셨습니다 🙇

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Entities/TodoModel.swift
> +struct TodoMedel {
`TodoMedel` 오타 같아요 +_+
추가로 (개인 취향이 살짝 들어가지만..) 이름에 `Model` 이라는 단어를 붙이기보단 `Todo` 그대로 사용하는 게 더 나을 것 같아요.

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListView.swift
> +    let countLabel: UILabel = {
프로퍼티의 `private` 접근 제한을 해제할 땐, `private`을 유지한 채로 필요한 구현만 노출할 수 있을지 고민해보면 좋을 것 같아요.
`countLabel` 전체를 노출해 `countLabel`의 모든 속성이 변경될 수 있는 상태와 `countLabel`의 `text` 만을 업데이트하는 통로를 만들어 명시적으로 `text`만 변경됨을 표현하는 것은 큰 차이가 있습니다.

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListView.swift
> +        self.title = title
`title` 값을 프로퍼티로 가지고 있을 필요가 있을까요? 👀 
어차피 아래에서 `configureLayout`이 호출되는 시점에 뷰가 생성되니 그 이후 `titleLabel`에 바로 할당해줘도 될 것 같아요.
`titleLabel`의 `text`는 나중에 변경될 수 있는데, 그러면 프로퍼티로 갖고있는 `title`값과 달라져 혼동을 줄 수 있을 것 같아서요 🤔

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListView.swift
> +            make.top.leading.bottom.equalTo(self).inset(8)
레이아웃은 항상 4방향(or 높이나 너비)가 잡혀있어야 합니다.
꼭 고정값이 아니더라도 `lessThanOrEqualTo`, `greaterThanOrEqualTo` 로 뷰의 크기가 커질 때/작아질 때 에 대해 설정을 해줘야 해요.
현재는 `trailing`이 잡혀있지 않아 라벨의 텍스트 길이가 길어진다면, 화면 범위를 벗어날 것 같아요 🤔

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListView.swift
> +final class TodoListView: UIView {
`HeaderView`와는 포함 관계이긴 하지만, 각각의 크기가 꽤 커서 별도의 파일로 분리해주면 좋을 것 같아요.

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListView.swift
> +    }()
테이블뷰, 헤더뷰 생성 후 스택뷰에 추가/생성하는 로직이 각 State 별로 총 세 번 반복되는 것 같아요.
공통 로직을 추려서 줄여볼 수 있을까요? 🤔

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewController.swift
> +    }
뷰모델을 외부로부터 주입받도록 구현하셨군요 👍

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewController.swift
> +        mainView.doneTableView.register(TodoListCell.self, forCellReuseIdentifier: TodoListCell.identifier)
요것도 반복되는 로직으로 구현하신 `TodoListView` 내부에서 처리해줘도 될 것 같아요.

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewController.swift
> +            })
UI 외에 뷰모델도 어느 정도 구현하신 것 같아 코멘트 남깁니다..!

하나의 스트림에서 테이블뷰와 헤더뷰 모두 업데이트하기 보단, 각각의 스트림으로 나눠주는 게 좋을 것 같아요.
`"\($0.count)"`와 같이 리스트의 개수를 가져와 문자열로 바꾸는 포멧팅 로직도 뷰컨에서 뷰모델로 분리해줄 수 있고, 나중에 `todoList`에서 파생되는 값이 아닌 다른 값을 표시하도록 기획이 바뀌더라도 수정이 쉬운 구조가 될 것 같습니다.

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewController.swift
> +                cell.deadlineLabel.text = item.deadlineAt.toString
캡슐화를 지켜주기 위해 각각의 뷰 프로퍼티를 숨기고 `item`을 넘기는 메서드를 만들어 셀 내부에서 뷰를 업데이트하도록 구현해줄 수 있을 것 같아요.

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewController.swift
> +              }.disposed(by: bag)
동일한 구현이 반복되고 있는데요. 공통 로직을 추려내서 반복되는 로직을 줄일 수 있지 않을까요? 👀

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewModel.swift
> +    let listItems = BehaviorSubject<[TodoMedel]>(value: TodoMedel.makeDummy())
디버그 빌드에서만 돌아가도록 전처리문을 사용할 땐, 반드시 릴리즈 빌드도 정상적으로 동작하는지 확인해줘야 합니다.
현재 `makeDummy` 메서드의 선언부를 디버그 빌드에서만 컴파일되도록 해두었으나, 이곳은 따로 전처리문을 선언해두지 않아서 릴리즈 빌드에선 에러가 발생할 거예요.
```suggestion
    #if DEBUG
    let listItems = BehaviorSubject<[TodoMedel]>(value: TodoMedel.makeDummy())
    #else
    let listItems = BehaviorSubject<[TodoMedel]>(value: [])
    #endif
```

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewModel.swift
> +    private(set) lazy var todoList = listItems
`lazy var`로 선언하신 이유가 궁금해요 👀 
`lazy`로 선언한 변수를 여러 스레드에서 동시에 접근하게 되면 여러 개의 인스턴스가 생성될 가능성이 있어서 살짝 위험합니다.
지연 생성해야하는 특별한 이유가 있는 게 아니라면, 상수로 선언해주는 게 좋을 것 같아요.

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewModel.swift
> +            items.filter { $0.state == .todo }
리스트가 수정될 때 마다 세 곳에서 전체 순회 로직을 돌게 될텐데, 리스트의 개수가 많아졌을 때 퍼포먼스에 문제가 생기진 않을까요? 🤔

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/Utils/Extensions/Date+ToString.swift
> +}
`DateFormatter`는 생성/설정에 리소스가 많이 드는 타입입니다.
현재 앱에선 날짜를 표시하는 부분이 굉장히 많아서 매번 `DateFormatter`를 새로 생성해서 사용하는 건 비효율적일 것 같아요 🤔 
필요한 설정값을 가진 `DateFormatter`를 하나 만들어두고, 재사용할 수 있도록 구현하는 게 좋을 것 같습니다.

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/Utils/Protocols/CellIdentifiable.swift
> +}
좋네요!
좀 더 덧붙여보자면, 매번 구현하는 셀에다가 채택할 필요없이 extension 하나 살짝 추가해두면 더 편해질 것 같습니다.
```swift
extension UITableViewCell: CellIdentifiable { }
```

(이건 취향의 영역..) `register`도 따로 만들어서 매번 `.identifier`까지 입력해주는 수고를 덜어줄 수도 있습니다.

```swift
extension UITableView {
    func register(_ cellClass: UITableViewCell.Type) {
        register(cellClass, forCellReuseIdentifier: cellClass.identifier)
    }
}
```

2022-07-09 18:49 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewModel.swift
> +    var listItems: BehaviorSubject<[TodoMedel]> { get }
사파리가 생각하시는 뷰모델의 `input` 이라는 개념에 대해서 설명해주실 수 있을까요? 👀

2022-07-10 06:19 UTC, saafaaari commented on ProjectManager/ProjectManager/Entities/TodoModel.swift
> +struct TodoMedel {
일단 오타 해결했습니다. 네이밍은 좀더 고민해보겠습니다.

2022-07-10 06:28 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoListView.swift
> +    let countLabel: UILabel = {
setCountText(to:) 메서드를 만들어 라벨의 text를 수정할 수 있도록 리팩하였습니다.

2022-07-10 06:44 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoListView.swift
> +final class TodoListView: UIView {
넵 두 타입을 각각 파일로 분리하였습니다.

2022-07-10 06:51 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoListViewController.swift
> +        mainView.doneTableView.register(TodoListCell.self, forCellReuseIdentifier: TodoListCell.identifier)
View 내부에서 처리하도록 수정하였습니다.

2022-07-10 06:58 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoListViewController.swift
> +                cell.deadlineLabel.text = item.deadlineAt.toString
cell 내부에서 메소드를 통해 내부 컨텐츠를 업데이트 하도록 수정하였습니다.

2022-07-10 07:05 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoListViewModel.swift
> +    let listItems = BehaviorSubject<[TodoMedel]>(value: TodoMedel.makeDummy())
감사합니다. 이런부분 까지 생각을 못했습니다. 수정 했습니다

2022-07-10 07:13 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoListViewModel.swift
> +            items.filter { $0.state == .todo }
또치에 말씀이 맞는것 같습니다. 이부분은 Rx의 Operators 중 `distinctUntilChanged`를 사용할 수 있을 것 같습니다. 또치가 허락해주신다면, 이 부분은 다음 PR에서 개선해도 괜찮을 까요? Cell을 추가하는 기능을 구현하면서 같이 해보겠습니다.

2022-07-10 07:23 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoListViewModel.swift
> +    private(set) lazy var todoList = listItems
특별한 이유는 없었던것 같습니다. 이유라면 "좀더 깔끔해 보이지 않을까?" 라는 생각으로 구현하였습니다.

```swift
init() {
        todoList = listItems
            .map { items in
                items.filter { $0.state == .todo }
            }
        
        doingList = listItems
            .map { items in
                items.filter { $0.state == .doing }
            }
        
        doneList = listItems
            .map { items in
                items.filter { $0.state == .done }
            }
    }
```
위와 같이 상수로 하고, init 내부에서 초기화 해주었습니다.

2022-07-10 07:39 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoListView.swift
> +        self.title = title
´´´swift
    init(title: String) {
        super.init(frame: .zero)
        configureLayout()
        titleLabel.text = title
        self.backgroundColor = .systemGray6
    }
´´´
위와 같이 title이라는 프로퍼티를 삭제하고, init 내부에서 처리했는데 괜찮을 까요??

2022-07-10 07:45 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoListViewModel.swift
> +    var listItems: BehaviorSubject<[TodoMedel]> { get }
제가 생각하는 input은 어떠한 이벤트가 들어오는 통로이며, 그 들어온 이벤트가 스트림이 시작되는 시점이라고 생각합니다.
때문에 Subject를 사용함으로써 onNext를 받아 연결시켜 놓은 Observable들이 이벤트를 방출시킬 수 있도록 하였습니다.
추후 Relay로 수정할 계획또한 있습니다. 네이밍 부분이 input의 의미와 어울리지 않는다는 생각이 조금 들기는 하네요...ㅎ

2022-07-10 08:50 UTC, Siwon-L commented on ProjectManager/ProjectManager/Presentation/TodoListView.swift
> +            make.top.leading.bottom.equalTo(self).inset(8)
```swift
labelStackView.snp.makeConstraints { make in
            make.top.leading.bottom.equalTo(self).inset(8)
            make.width.lessThanOrEqualTo(self.snp.width).multipliedBy(0.9)
}        
```
위와 같이 `lessThanOrEqualTo`이용하여 늘어날 수 있는 최대 길이를 지정해주었습니다.

![image](https://user-images.githubusercontent.com/91936941/178137926-744b0b0e-5de0-4719-be87-bd630cdb9d21.png)

사진과 같이 일정 사이즈를 넘어가면 너이상 늘어자니 않고 ...으로 표현되는 것을 볼 수 있었습니다.

2022-07-10 09:12 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoListViewController.swift
> +            })
두 이벤트를 독립된 Observable를 사용하였습니다.

```swift
protocol TodoListViewModelOutput {
    var todoList: Observable<[TodoModel]> { get }
    var doingList: Observable<[TodoModel]> { get }
    var doneList: Observable<[TodoModel]> { get }
    var todoListCount: Observable<String> { get }
    var doingListCount: Observable<String> { get }
    var doneListCount: Observable<String> { get }
}
```

2022-07-10 12:23 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/Utils/Extensions/Date+ToString.swift
> +}
viewModel에 dateFormatter 인스턴스를 만들고, 

```swift
struct TodoCellContent {
    let title: String?
    let body: String?
    let deadlineAt: String?
}

func toTodoCellContents(todoModels: [TodoModel]) -> [TodoCellContent] {
    todoModels.map { item in
        TodoCellContent(title: item.title,
                        body: item.body,
                        deadlineAt: item.deadlineAt.toString(dateFormatter))
    }
}
```
위 처럼 VC에선 cell에 바로 바인딩 할 수 있도록 `TodoCellContent` 구조체와 `toTodoCellContents`메서드를 구현하였습니다.

https://github.com/yagom-academy/ios-project-manager/pull/133/commits/fe460685e08b4676972932527801a94b3f578f8a

2022-07-10 15:35 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListView.swift
> +    }
요렇게 `register` 메서드를 따로 구분해서 정의해두고, 외부에서 호출해줄 필요가 있을까요?
위에서 테이블뷰를 생성해줄 때 바로 해줘도 될 것 같아서요 🤔

2022-07-10 15:39 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListCell.swift
> +    }
분리된 값을 각각 받기보단, `TodoModel`을 넘겨받아 각 뷰에 할당해주는 게 좋을 것 같아요.
지금은 셀 내부에 꾸며줘야하는 뷰가 늘어날수록 인자 개수가 계속 많아질 것 같네요 🤔 

나중에 `TodoModel`이란 raw 한 데이터를 셀에 표현하기 위한 데이터로 변환하는 로직이 생긴다면, 인자가 셀에 대한 뷰모델이 될 수도 있을 것 같구요.

2022-07-10 15:46 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListHeaderView.swift
> +            make.width.lessThanOrEqualTo(self.snp.width).multipliedBy(0.9)
`self`가 곧 `labelStackView`의 `superview`이니 `equalToSuperview`, `lessThanOrEqualToSuperview` 로 표현하는 게 더 좋을 것 같아요.

2022-07-10 15:54 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListHeaderView.swift
>  }
현재 구현이 잘못된 건 아니지만, 보통 rx 관련 extension을 구현할 땐 `Reactive` 를 통해 접근하도록 확장하여 구현합니다.
사용하는 곳에선 `todoHeaderView.rx.countText` 의 형태가 되도록요!
참고만 해주세요 🙇 

```swift
extension Reactive where Base == TodoListHeaderView {
    var countText: Binder<String?> {
        return base.countLabel.rx.text
    }
}
```
(이렇게 구현하려면 `countLabel`이 `fileprivate`이 되어야 할거예요)

2022-07-10 15:58 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewController.swift
> +            .asDriver(onErrorJustReturn: "0")
output을 받는 곳(뷰)에서 스트림에 에러가 발생했을 때 의미없는 값을 방출하도록 정해주기보단, 애초에 output의 타입을 `Signal`이나 `Driver`로 설정해주는 게 좋을 것 같아요 🤔 
`Signal`과 `Driver`의 차이점도 찾아보시고, 의도에 맞게 골라서 사용하시면 더 좋을 것 같습니다.

2022-07-10 16:02 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewController.swift
> +            })
`todoList`도 뷰모델 내부에 있고, `toTodoCellContents(todoModels:)` 메서드도 뷰모델 내부에 있는데, 뷰단에서 이 로직을 수행해야 할 이유가 있을까요? 👀 
처음부터 뷰모델에서 가공한 상태로 방출하고 뷰에선 그대로 받아서 사용하기만 해도 될 것 같아요 🤔

2022-07-10 16:04 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewModel.swift
>  }
지금은 아무 역할을 하지 않는 단순 데이터이지만, 메인화면에서 사용하는 `TodoListViewModel`의 로직을 덜어주는 관점에서 셀과 매칭되는 뷰모델의 역할을 해주도록 구현할 수도 있을 것 같습니다.
생성자에서 `TodoModel` 을 받아 뷰에 보여주기 위한 포멧팅 로직을 수행한 후 자기 자신의 프로퍼티에 할당해주도록요!

2022-07-10 16:05 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/Utils/Extensions/Date+ToString.swift
>      }
extension으로 구현된 `date.toString(dateFormatter)`의 형태로 사용해야 하는 이유가 있을까요? 
바로 `dateFormatter.string(from: date)` 으로 사용해도 큰 차이가 없어보여요 🤔

2022-07-10 16:07 UTC, TTOzzi approved these changes
고생하셨습니다! 이번 스텝에서 챙기지 못한 부분은 다음 스텝에서 챙겨보아요 🙂

2022-07-10 16:07 UTC, merged

2022-07-10 16:18 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListView.swift
> +        self.title = title
넵 괜찮아보입니다!

2022-07-10 16:20 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewModel.swift
> +            items.filter { $0.state == .todo }
`listItems`의 내부 요소의 개수가 늘어났을 때, 항상 해당하는 state의 리스트를 가져오기 위해 순회로직을 돌아야 하는 것 /  todo/doing/done 중 한 곳에서만 수정이 일어나도 세 곳에서 순회 로직을 도는 것을 `distinctUntilChanged`를 활용해 개선할 수 있을까요? 👀 
요건 다음 PR에서 코드로 확인해볼게요!

2022-07-10 16:31 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoListViewModel.swift
> +    var listItems: BehaviorSubject<[TodoMedel]> { get }
보통 뷰모델의 input은 사용자로부터 받는 이벤트, 뷰에서 발생하는 이벤트로 구성하게 되는데요.
말씀해주셨듯이 네이밍도 뷰에서 발생하는 이벤트와는 거리가 있어 보이고, 사용자로부터 뷰에서 불쑥 `[TodoModel]` 배열이 들어오는 상황도 없을 것 같아요 🤔 

현재 로직에선 화면이 로드된 후 뷰에 표시해줄 데이터인 `[TodoModel]`을 어딘가에서 받아와 뷰로 전달해줘야 합니다.
그러기 위해선 input 은 뷰의 라이프사이클에서 발생하는 이벤트인 `viewDidLoad(or viewWillAppear, viewDidAppear)`가 되어야 할 것 같고 뷰모델에선 뷰가 로드됐다는 input 을 전달받았을 때 어딘가(서버 or 로컬 저장소.. 현재는 단순 더미데이터)로부터 데이터를 받아오는 로직을 수행한 후, 그 결과값을 output 을 통해 보내도록 구현되어야 할 것 같아요.

뷰모델 구현 전 rx를 활용한 mvvm 구조의 예시코드/프로젝트를 많이 찾아보시고 참고해서 구현하시면 좋을 것 같습니다 🙂