프로젝트 관리 앱 [STEP2-1] Red, Taeangel
yagom-academy/ios-project-manager pull request #135
Opened 2022-07-07 15:01 UTC by cherrishRed

안녕하세요 토니! @Monsteel
Red, Taeangel 입니다!
STEP 2-1 구현완료 하였습니다. 

SwiftUI 가 처음이라 삽질은 많이 했습니다😭
그 중에 update 하는 로직에 큰 오류가 있는데 고민해 보다가 결국 답을 못찾아 우선 PR 드립니다. 

## 구현한점, 삽질한 점, 조언을 구하고 싶은 점

### NavigationView 가 한쪽으로 솔리고 Title 이 중앙에 오지 않는 현상
<img src="https://i.imgur.com/SqV6YYH.png" width=50%>

Tablelet 모드에서 봤을 때 네비게이션 바가 한쪽으로 치우치는 일이 있었습니다. 
아마도 NavigationView 오류라고(?) 생각합니다. 

```swift
.navigationViewStyle(.stack)
```
아이패드에서 navigationView 가 정상적으로 보임
```swift
.navigationBarTitleDisplayMode(.inline)
```
Navigation Title 이 중앙에 정렬됨.

두가지 코드를 추가하여 문제를 해결 했습니다. 

### List의 Cell 의 inset

![](https://i.imgur.com/SlIHS6Y.png)
이와 같이 셀사이의 간견을 주고 싶었습니다 하지만 padding이나 Spacer()등을 활용해 보아도 cell사이의 간격을 줄 수 없었습니다. 
그래서 우선 cell의 배경색을 흰색으로 넣어주었습니다.  

`.listStyle(.inset)` 을 사용하고, 
`.listRowSeparator(.hidden)` 으로 주어서 간격이 떨어져 보이게끔 (약간야매?)했습니다.
좌우 여백은 `.padding(.horizontal, -24)` 를 주어 없어 보이도록 했습니다. 

질문하고 싶은점은 저희가 한 것처럼 안하고 진짜로 List에서 진짜로 cell사이의 간격을 줄 수 있는 방법이 있는지 궁금합니다. 
SwiftUI 에서 기본적으로 제공하고 있는 디자인에 한계가 있기 때문에 Custom을 하려면 VStack 같은 걸 사용하는게 좋지 않을까 하는 생각도 해보았습니다. 실제로 현업에서는 List 를 자주 사용하는지 궁금합니다.

### EnvironmentObject vs ObservableObject 

EnvironmentObject vs ObservableObject에 대해 저희가 고민을 하였는데 
EnvironmentObject 보다는 ObservableObject가 더 메모리상(?) 효율 적일 것 같아 ObservableObject을 선택하였는데 ObservableObject와 EnvironmentObject의 토니만의 선택기준이 있을까요?

### 왜 List 업데이트 문제

```swift
class Todo: Identifiable, ObservableObject {
  let id: UUID
  @Published var title: String
  @Published var content: String
  @Published var date: Date
  @Published var status: Status
}

class TodoViewModel: ObservableObject {
  func creat(todo: Todo) {
    todoList.insert(Todo(title: todo.title, content: todo.content, status: .todo), at: 0)
}
  
func update(todo: Todo) {
  let willChangeTodo = todoList.filter { todo in
  todo.id == todo.id
    }
}      
    
 List { ForEach(viewModel.read(by: status)) { todo in
  DetailViewButton(viewModel: viewModel, todo: todo, isShowDetailView: $isShowDetailView)
 }   
    
```
저희가 없데이트 메서드를 구현하여 사용하였는데 값을 확인하면 값은 분명히 바뀌었는데 UI 업데이트를 하지 않았습니다. creat 메서드를 사용하였을때는 바로 화면에 List을 추가하여 바로 보여주었는데 왜 update 메서드를 사용하였을때는 화면에 List를 바로 업데이트 해주지 않는지 궁금합니다. 처음에 저희가 생각하기에는 내부 프로퍼티 값을 바꾸어 준 것은 Published가 감지를 못하나 싶어서 `ForEach(viewModel.read(by: status)`부분을 viewModel.todoList으로 바꾸어 주었는데 이경우에는 List화면이 꼬이긴 하나 바뀌는 것을 확인 하였습니다. 왜 업데이트가 되지않고 또 왜 List화면이 꼬이는지 궁금합니다.
(여기서 말하는 List 가 꼬였다 함은 Title1 cell을 눌러보았는데, DetailView 로 이동하면 Title7 으로 내용이 뜬다던가... 하는 오류 입니다. 마치 테이블 뷰에서 cell이 reuse 되어서 뷰의 내용이 꼬인것 같은 현상이 일어 납니다...)

### MVVM

스유를 써보기도 하였고 MVVM UIkit에서도 MVVM 패턴을 많이 사용해 보지 못해서  저희가 최대한 MVVM 패턴에 맞추려 노력하였는데 MVVM 패턴이 맞는지 수정해야할 점이 어딘지 궁금합니다.

SwiftUI를 쓰다보니 View 를 많이 생성하게 되는데, 모든 View 가 ViewModel 을 가져야 하는 것인지 어느정도 까지 ViewModel 을 공유해도 되는지도 궁금합니다. 
또 @State @Binding 등의 상태를 통해 action 을 수행하다 보니 View 마다 들고 있는 변수가 많아지고 마치 이 변수들이 flag 처럼 느껴져서 좋게 생각되지는 않았습니다. 이러한 방향이 맞는 것이지 궁금합니다. 

### NavigationView SafeArea
<img src="https://i.imgur.com/1LrexEz.png" width=50%>

Navigation 부분이 없어진 부분이 많아서 문제가 좀 많았습니다. 
우선, 큰 문제들(뷰가 밀린다든지)은 해결을 했지만, safeArea를 줄일 수가 없었습니다. 
ignoreSafeArea 도 소용이 없고... backgroundColor 를 어떻게 넣어 주었는데... safeArea 부분에는 색상을 넣어주지 않습니다.
NavagationView custom 이 원래 이렇게 자유스럽지 못한 것일까요?
사실 이정도면 CustomNavigation 을 구현하는 것도 낫다는 생각이 들었습니다.😂

### file 분리 
SwiftUI 를 사용하다보니 View를 자잘하게 나눠지게 되었는데요, 이에 따른 파일 분리를 어떻게 해야 하는지 조언을 얻고 싶습니다.

2022-07-08 09:08 UTC, Monsteel commented on ProjectManager/ProjectManager/Extension/Date+Extension.swift
> +  func toString() -> String{
Warning이 발생합니다! ⚠️

2022-07-08 09:32 UTC, Monsteel requested changes
안녕하세요 Red(레드), Taeangel(탱글) :)
Step2-1도 수고많으셨습니다!

## 남겨주신 내용에 대한 저의 답변

### 🚀 NavigationView 가 한쪽으로 솔리고 Title 이 중앙에 오지 않는 현상
> <img src="https://i.imgur.com/SqV6YYH.png" width=50%>
> 
> Tablelet 모드에서 봤을 때 네비게이션 바가 한쪽으로 치우치는 일이 있었습니다. 
아마도 NavigationView 오류라고(?) 생각합니다. 

이 부분에 대해서는 오류가 아니라, Navigation의 columns style이 적용된 화면이기 때문에, 말씀하신 형태로 Navigation이 노출된 것으로 보여집니다. 

이는, Red와 Taeangel이 원하는 작동방식이 아니였기에,
```swift
.navigationViewStyle(.stack)
```
요런 style을 지정해줌으로써, 해소가 되었다고 볼 수 있겠습니다.

그리고 아래에 작성해준 아래의 코드같은 경우에는, navigationBar Title이 보여지는 스타일을 지정해주는 코드입니다.
```swift
.navigationBarTitleDisplayMode(.inline)
```

따라서, 버그와는 거리가 멀고, Style을 지정해서 의도한 Navigation 작동을 이끌어 냈다고 볼 수 있겠습니다.

### 🚀 List의 Cell 의 inset

SwiftUI의 List 같은 경우 기본 스타일이 지정되어 있어, Custom하게 구현하기에는 한계가 있다는 점을 보아
UITableView와 유사한 성질을 가지고 있다는 사실을 알 수 있는데요,

List는 Custom에 제약적이라 Red와 Taeangel이 구현하고자 하는 화면을 구현하기에는 적절치 않을 수 있다는 생각이 듭니다.

`VStack 같은 걸 사용하는게 좋지 않을까 하는 생각도 해보았습니다.`라고 말씀 하셨는데,
`VStack`사용 대신 `List` 를 사용하기를 결정하신 이유가 무엇인가요? 🤔

현업에서 자주 사용하는 방법에 귀를 기울이는것은 좋지만,
List와 VStack을 비교하는 상황에서는 크게 유의미하지 않다고 봅니다.
둘 다 각각의 장단점이 있으니까요.

현업보다는, 좋은 코드를 쫒아가는 본인들만의 기준을 세우고, 그 기준에 따라 고민해보면서 적용해 나가면 어떨까 합니다.

여러분들의 코드의 이유가 "현업에서 사용해서" 와 같은 이유보다는 조금 더 본질적인 이유가 되었으면 합니다.

### 🚀 EnvironmentObject vs ObservableObject

EnvironmentObject와 ObservableObject의 작동양식에 있어서는 큰 차이가 없습니다만

EnvironmentObject를 사용했을 때 경게해야할 부분은 있다고 생각합니다.

EnvironmentObject로 선언한 value에 여러 화면이 의존성을 가지게 되는,
viewModel : view = 1:n 관계가 만들어지게되면, 각각의 역할을 분리하기 어려워지게 되고, 변경사항에 유연한 코드가 작성되기 어려운 환경이 만들어질 수 있습니다.

이러한 경계해야할 문제가 발생할 수 있음을 인지하고 사용한다면 둘 중 어느것을 사용해도 유의미한 차이는 발생하지 않을것이라 생각합니다.

### 🚀 왜 List 업데이트 문제

[Swift UI Debuging](https://www.avanderlee.com/swiftui/debugging-swiftui-views)을 할 수 있습니다

한번 위 아티클에서 소개하는 Debug방법들이 원인을 찾는데에 도움이 되실 수 있을것 같아요! ☀️

### 🚀 MVVM

Red와 Taeangel의 코드는 어떤가요? 확장에는 열려있고 각각의 역할은 잘 분리되어 있나요?
앞서 말씀드린, viewModel:view  = 1:n 관계가 만들어져, 확장에 막혀있는 코드가 된건 아닌가 싶네요.

확장에 열려있는 방향으로 어떻게 개선할 수 있을지 조금 더 고민을 해보면 좋을것 같아요.

viewModel의 의미에 대해 잘 생각해보시고, viewModel이 왜 생겨났고, 어떻게 생겨나게 되었는지를 한번 찾아보시거나, 깊이 고민해보시면 좋을것 같습니다! 🙏

### 🚀 NavigationView SafeArea

하하 CustomNavigation 을 구현하는 것도 나쁘지 않은 선택이긴 합니다..
다만, 개발자의 사용 부주의로 인해 발생한 문제인지, 실제로 Apple의 API서 이슈가 발생했는지 정확하게
판단할 수 있어야 합니다.

써보시고 불편한 부분이 있었다면 그런 점들을 개선한 Navigation을 만드셔도 좋을것 같아요 :)

### 🚀 file 분리 

나누시는 방법적인 부분에서 부족한 부분은 없어 보이는데요!

음.. 한곳에서만 사용하는 경우 한 파일에 private view를 선언하여 사용하는 방법도 있을 것 같아요!

****

수고많으셨어요 👍 
궁금하신 내용은 언제든 이곳 코멘트 or Discord로 말씀 부탁드립니다 ☀️

2022-07-08 09:32 UTC, Monsteel commented on ProjectManager/ProjectManager/Extension/Date+Extension.swift
> +  func toString() -> String{
Warning이 발생합니다! ⚠️

2022-07-08 09:32 UTC, Monsteel commented on ProjectManager/ProjectManager/Model/Todo.swift
> +  let id: UUID
let 선언 좋습니다 🙌

2022-07-08 09:32 UTC, Monsteel commented on ProjectManager/ProjectManager/Scene/ProjectManagerView.swift
> +struct ProjectManagerView: View {
`ProjectManagerView`라는 이름으로 이 화면이 정확히 어떤 역할을 하는지 알기 어렵습니다.
최 상위 Swift view라면, AppView라는 네이밍은 어떤가요? 🙋🏻‍♂️

2022-07-08 09:32 UTC, Monsteel commented on ProjectManager/ProjectManager/Scene/ProjectManagerView.swift
> +    .edgesIgnoringSafeArea(.top)
어떤 의도를 기대하고 작성한 코드인가요?

2022-07-08 09:32 UTC, Monsteel commented on ProjectManager/ProjectManager/Scene/ProjectManagerView.swift
> +      .ignoresSafeArea(.container, edges: .bottom)
어떤 의도를 기대하고 작성한 코드인가요?

2022-07-08 09:32 UTC, Monsteel commented on ProjectManager/ProjectManager/Scene/ProjectManagerView.swift
> +      .font(.title)
어떤 의도를 기대하고 작성한 코드인가요?

2022-07-08 09:32 UTC, Monsteel commented on ProjectManager/ProjectManager/View/TodoList.swift
> +          UITableView.appearance().backgroundColor = .clear
어떤 의도를 기대하고 작성한 코드인가요?

2022-07-08 09:32 UTC, Monsteel commented on ProjectManager/ProjectManager/View/TodoList.swift
> +  @Binding var isShowDetailView: Bool
외부에서 해당 값을 주입받는 이유가 있나요?

2022-07-08 09:32 UTC, Monsteel commented on ProjectManager/ProjectManager/Scene/ProjectManagerView.swift
> +        DetailView(viewModel: self.viewModel, todo: Todo(title: "", content: ""), nonEditable: false, isShow: $isShowDetailView, method: .creat)
DetailView는 CRU를 모두 담당하는 화면입니다. 그 역할을 조금 더 잘 표현할 수 있는 네이밍은 없을까요?

2022-07-08 09:32 UTC, Monsteel commented on ProjectManager/ProjectManager/Scene/ProjectManagerView.swift
> +  @State private var isShowDetailView = false
위의 리뷰와 이어지는 내용입니다만,
DetailView가 CRU를 모두 담당하면서, isShowDetailView가 true가 되었을 때 (C/RU 중) 어떤 역할을 하는 DetailView가 열렸는지 파악하기가 어렵습니다. 디버그 시 자칫 오해를 할 수도 있구요.

2022-07-08 09:32 UTC, Monsteel commented on ProjectManager/ProjectManager/View/TodoList.swift
> +  @State var isShowDetailView: Bool
이 부분 역시 외부로부터 값을 받는 이유가 있나요?

2022-07-08 09:32 UTC, Monsteel commented on ProjectManager/ProjectManager/View/TodoListCell.swift
> +  let todo: Todo
TodoListCell의 `State`라고 볼 수 있을것 같은데, `@State`로 선언하지 않은 이유가 있나요? 🙋🏻‍♂️

2022-07-08 09:32 UTC, Monsteel commented on ProjectManager/ProjectManager/ViewModel/TodoViewModel.swift
> +  func update(todo: Todo) {
update 기능이 정상적으로 작동하나요 ? 👀

2022-07-08 09:33 UTC, Taeangel commented
## NavigationView SafeArea 문제 
```swift
 let navigationBarApperance = UINavigationBarAppearance()
    navigationBarApperance.backgroundColor = UIColor.systemGray6
    UINavigationBar.appearance().scrollEdgeAppearance = navigationBarApperance
```
를 해주어 해결하였습니다. 

## 왜 List 업데이트 문제
TodoListCell에 @ObservedObject 를 채택해주어 해결하였습니다

2022-07-11 09:59 UTC, cherrishRed commented on ProjectManager/ProjectManager/Extension/Date+Extension.swift
> +  func toString() -> String{
lint 오류가 나는데, lint 를 양쪽에 깔지 않고 한 컴퓨터에만 등록해서 lint 오류를 볼 수 없어서 이런 실수 가 난 것 같습니다.
수정했습니다!

2022-07-11 10:31 UTC, cherrishRed commented on ProjectManager/ProjectManager/Scene/ProjectManagerView.swift
> +struct ProjectManagerView: View {
프로젝트 이름이 ProjectManager 라서 ProjectManagerView 라고 이름 붙였는데, AppView 가 조금더 직관적인 네이밍 인 것 같습니다. 수정했습니다!

2022-07-11 10:34 UTC, cherrishRed commented on ProjectManager/ProjectManager/Scene/ProjectManagerView.swift
> +    .edgesIgnoringSafeArea(.top)
NavigationView 관련하여 배경의 여백을 없애줄 수도 있다 라는 생각으로 작성한 코드인데 별다른 효과가 없었던 것 같습니다. 
해당 코드를 삭제하겠습니다. 
NavigationView 의 여백색상은 다른 방식으로 수정하였습니다.

2022-07-11 10:57 UTC, Taeangel commented on ProjectManager/ProjectManager/Scene/ProjectManagerView.swift
> +      .ignoresSafeArea(.container, edges: .bottom)
NavigationView 관련하여 수정을 해주려다 지우지 못한것 같습니다. 삭제하였습니다

2022-07-11 10:59 UTC, cherrishRed commented on ProjectManager/ProjectManager/Scene/ProjectManagerView.swift
> +      .font(.title)
`.background(Color(UIColor.systemGray4))` 코드는 뒤의 회색의 배경색을 두어 셀 사이의 여백이 회색으로 보이도록 해주는 코드 입니다. 
`.font(.title)` 코드는 저희의 예상으로는 Navigation의 title 의 폰트 사이즈가 바뀔 줄 알고 사용했으나, 실제로는 셀 안의 각 todoList 의 숫자를 나타내는 곳에만 적용이 되었습니다.

2022-07-11 11:20 UTC, Taeangel commented on ProjectManager/ProjectManager/View/TodoList.swift
> +          UITableView.appearance().backgroundColor = .clear
```swift
      ZStack {
        Color(UIColor.systemGray5)
        List {
          ForEach(viewModel.read(by: status)) { todo in
            DetailViewButton(viewModel: viewModel, todo: todo, isShowDetailView: $isShowDetailView)
              .listRowSeparator(.hidden)
          }
          .background(Color(UIColor.purple))
        }
        .padding(.horizontal, -24)
        .listStyle(.inset)
        .background(Color(UIColor.purple))
//        .onAppear {
//          UITableView.appearance().backgroundColor = .clear
//        }
```
이와 같이 LIst의 배경색을 지정해주려 하였는데 바뀌지 않아 블로그에서 찾아  onAppear에 `UITableView.appearance().backgroundColor = .clear` 코드를 넣어 배경색을 지정해 주었습니다. List 와 UITableView이 어떤 연관이 있길래 `UITableView.appearance().backgroundColor = .clear` 코드가 List의 배경색을 변경해 주는지 궁금합니다!

2022-07-11 12:21 UTC, Taeangel commented on ProjectManager/ProjectManager/View/TodoList.swift
> +  @Binding var isShowDetailView: Bool
TodoListView의 isShowDetailView값을 연결하여 `.sheet(isPresented: $isShowDetailView)`를 실행시켜 주기위해 사용하였습니다.

2022-07-11 12:30 UTC, Taeangel commented on ProjectManager/ProjectManager/Scene/ProjectManagerView.swift
> +        DetailView(viewModel: self.viewModel, todo: Todo(title: "", content: ""), nonEditable: false, isShow: $isShowDetailView, method: .creat)
CRU를 담당하는 느낌으로 EditView로 네이밍을 변경하였습니다!

2022-07-12 02:48 UTC, Taeangel commented on ProjectManager/ProjectManager/Scene/ProjectManagerView.swift
> +  @State private var isShowDetailView = false
어제 토니가 말씀해 주신대로 `DetailView`를 `EditView`와 `CraeatView`로 분리 하였습니다!

2022-07-12 02:58 UTC, Taeangel commented on ProjectManager/ProjectManager/View/TodoList.swift
> +  @State var isShowDetailView: Bool
isShowDetailView의 값을 Bool값 바인딩으로 전달해 주기 위해서입니다.

2022-07-12 03:01 UTC, Taeangel commented on ProjectManager/ProjectManager/ViewModel/TodoViewModel.swift
> +  func update(todo: Todo) {
```swift
func update(todo: Todo) {
    let willChangeTodo = todoList.filter { filteredTodo in
      todo.id == filteredTodo.id
    }
```
ㅠㅠ 변경하였습니다.

2022-07-12 08:31 UTC, cherrishRed commented
@Monsteel 
안녕하세요 토니! 🐉😱🐲
어제 디스코드에서 조언을 주신 것을 바탕으로 리펙토링을 진행했습니다.

## 추가적인 질문


### Service 객체에 todoList를 private을 붙여주어야 하나요? 
```swift
class TodoService: ObservableObject {
  @Published var todoList: [Todo] = []
}
```
지금 코드는 ViewModel 들에서 todoList에 직접적으로 접근해서 사용하고 있습니다.
private 를 붙이고 func read() 만들어서 읽어주는 캡슐화 과정이 필요한가요?

그리고 필요하다고 하시면, Service 자체에서 CRUD를 가지고 있어도 되는 것인지 궁금합니다. 

### todoService 를 공유하기 위한 방법
EditViewModel와 AppViewModel가 같은 todoService를 공유 해야 하기 떄문에 AppViewModel에 있는 EditViewModel가 있는 곳 까지 todoService를 넘겨 주었습니다. 이것보다 더 좋은 방법이 있는지 궁금합니다.

```swift
@State var isShowEditView: Bool = false
  private let status: Todo.Status
  private let readList: (Todo.Status) -> [Todo]
  let todoService: TodoService
  
  init(todoService: TodoService, status: Todo.Status, readList: @escaping (Todo.Status) -> [Todo]) {
    self.todoService = todoService
    self.status = status
    self.readList = readList
  }
```

저희는 싱글톤 패턴이나 EnvorionmentObject 부분도 생각했었는데 전역적으로 Model 데이터를 공유하는 것이 좋지 않다고 생각되어, 로직이 조금 불편하더라도 위의 처럼 받는 과정을 취했습니다. 

이런 상황에서는 싱글톤을 선택해야 하는 것일까요?

2022-07-12 14:47 UTC, Monsteel approved these changes
질문주신 내용에 대해서는 구두로 말씀을 드렸습니다.
다음 PR에서 해당 내용 반영 부탁드려요 🙏

2022-07-12 14:48 UTC, merged

2022-07-12 14:55 UTC, cherrishRed commented
## 토니가 구두로 해주신 리뷰 

> Service 객체에 todoList를 private을 붙여주어야 하나요?
지금 상황에서는 크게 의미가 있는 일은 아니지만 추후에 realm 을 사용할 것을 생각해서 Service 객체가 realm 객체가 된다면 CRUD 를 미리 구현해 두고 캡슐화를 해두면 나중에 리펙할 때 편할 수 있다. 

> todoService 를 공유하기 위한 방법
지금 하고 있는 방식은 의존성 주입 방식인데 이 방법으로 사용해도 된다. 
싱글톤으로 사용하게되면 데이터의 CRUD 를 어디서든 접근할 수 있게 되는데, 이러면 우리가 만들어 놨던 구조가 일그러지는 일이 될 수 도 있다. 

> Closure 를 넘겨 줌으로 인해서 List 가 update 되지 않는 현상
closure 를 넘겨주라고 말한 부분은, List 에 해당하는 부분이라기 보다는, Tap 되었을 때의 이벤트 같은 부분이고, List 의 부분은 @State 나 @ObservedObject 를 사용하는 것이 좋다. 이미 read 라는 클로저를 todoList 에서 가지고 있는 것 자체가 [Todo] 배열을 가지고 있는 것과 같다. 배열을 소유하고 있지 못할 이유는 없다.