프로젝트 관리 앱 [STEP 2-3] Lingo
yagom-academy/ios-project-manager pull request #137
Opened 2022-07-10 16:03 UTC by llingo

안녕하세요 린생! @jungseungyeo
프로젝트 매니저 STEP 2-3 PR 보냅니다! 잘 부탁드립니다 🙇🏻

## 배경

- 할일을 길게 터치하여 팝오버 메뉴를 표시합니다
    - 팝오버에 표시하는 메뉴는 상황에 따라 달라집니다
        - TODO의 할일 : Move to DOING / Move to DONE
        - DOING의 할일 : Move to TODO / Move to DONE
        - DONE의 할일 : Move to TODO / Move to DOING
    - 본인의 판단에 따라 팝오버는 액션시트로 대체할 수 있습니다

위 요구사항을 만족시킬 수 있도록 진행했습니다.

## 작업 내용

**할일을 길게 터치하여 팝오버 메뉴를 표시합니다**
> Reactive Extension - `ModelLongPressed`
 
길게 터치하는 이벤트가 전달되기 위해 `UILongPressGestureRecognizer`를 사용하였습니다. 해당 이벤트가 발생하고 팝오버 메뉴를 표시하기 위해 처음에는 UIKit스럽게 Target-Action 방식으로 구현을 시도했었습니다. 하지만, Rx를 제대로 활용하지 못한다고 생각했고 아래 코드와 같이 기능을 확장하여 구현했습니다.
 
<img width="800" src="https://i.imgur.com/GOR0539.png"/> <br/>

`modelLongPressed`라는 메서드를 정의하고 Long 제스처를 Base가 되는 TableView에 추가한 후 제스처 이벤트가 발생하면 아래의 과정으로 데이터를 처리한 후 Cell과 데이터를 방출하도록 설계했습니다.

![](https://i.imgur.com/T6tIfJ6.png)

<img width="600" src="https://i.imgur.com/hCNOJni.png"/> <br/>

구현된 `modelLongPressed`를 ViewController에서 사용하여 길게 터치하는 이벤트에 대한 처리를 ViewModel에서 처리하도록 로직을 분리했습니다.

**팝오버에 표시하는 메뉴는 상황에 따라 달라집니다**

팝오버에 표시하는 메뉴는 현재 카드타입과 다른 종류의 타입을 표시해야 하기 때문에 이를 구별해주는 메서드를 구현했습니다.

<img width="600" src="https://i.imgur.com/zSu1Hei.png"/> <br/>

<img width="600" src="https://i.imgur.com/rdlQBgC.png"/> <br/>

**본인의 판단에 따라 팝오버는 액션시트로 대체할 수 있습니다**

요구사항에 맞게 액션시트를 활용하여 팝오버를 띄우는 AlertController를 생성하고 해당 이벤트는 한번만 띄운 후 사용자가 버튼을 클릭할 때 onNext -> onCompleted 가 진행되어야하기 때문에 Single을 사용하여 구현했습니다.

<img width="800" src="https://i.imgur.com/AUxXUis.png"/> <br/>

**마감 시간 순 정렬**

<img width="500" src="https://i.imgur.com/aDOTNIf.png"/> <br/>

TODO와 DOING의 경우 마감 기간까지 얼마남지 않았거나 지나버린 카드를 상단 쪽, DONE의 경우 오래 전 끝난 카드보다 최근에 끝낸 카드가 상단에 보여줘야 한다고 생각했습니다.

따라서, `sorted`로 각각 TODO, DOING, DONE 배열 데이터를 로직에 맞게 ViewModel에서 정렬해주었습니다.

## 리뷰노트

**화면 전환에 대한 고민**
기능 개발이 이뤄지면서 띄워야하는 장면이 증가하고 `present/dismiss` 또는 `push/pop`을 호출해야하는 상황에서 새로운 ViewController를 생성하여 화면 전환을 하게 되는데 

화면을 전환하기 위해서는 해당 ViewController가 다른 ViewController를 소유하고 있어야 하기 때문에 <U>서로 간의 의존성이 증가</U>하고 이곳 저곳에서 구현되어 있는 <U>화면 전환 코드를 관리하기 힘들어질 것 같</U>습니다.

화면 전환 문제에 대해 Coordinator 패턴을 하나의 해결책으로 제시하는 글들을 찾을 수 있었고 이번 STEP2-3에서는 적용하지 못했지만 남은 기간동안 Coordinator 패턴 적용과 Coordinator를 통한 의존성 주입에 대해 고민해보면 좋을 것 같다는 생각이 들었습니다.

**ViewModel과 ViewController**

프로젝트 코드에서 CardListViewController, CardAdditionViewController, CardDetailViewController가 하나의 CardListViewModel 객체를 주입 받는 형태로 구현되어 있고 이렇게 구현된 이유로는 Card를 저장하는 배열을 각각의 ViewController에서 공유해야하기 때문에 1:1이 아닌 1:N의 구조가 되었다고 생각합니다.

> 질문. ViewModel과 ViewController는 1:1과 1:N 어떠한 구조를 가져가는 것이 좋을까요?

저는 ViewModel과 ViewController가 1:N으로 구현이 되어 있다면 CardListViewController에서 사용하지 않는 로직이 CardListViewModel에 구현되어 있는 문제가 있다고 생각했습니다. 하지만, 1:1로 분리하게 된다면 데이터 공유 문제와 중복 로직이 발생할 가능성이 있을 것이며 이를 해결하기 위해 `DataManager`로 공유가 필요한 데이터를 관리하는 계층을 더 추가하는 것도 데이터 공유 문제를 해결할 수 있는 좋은 방법일 것 같습니다.🤔

**남은 기간에 대해**

**프로젝트 매니저 I**의 기능 구현이 생각보다 빠르게 끝난 것 같습니다.🤩 
하지만 남은 기간동안 아래의 항목에 대해 더 고민해보고 프로젝트에 적용해볼 생각입니다!

1. MVVM 패턴과 RxSwift를 잘 사용하기 위한 학습 진행
2. Coordinator 패턴을 고민해보며 프로젝트에 적용 (화면 전환)
3. ViewModel과 ViewController의 1:1, 1:N 관계에 대한 고민 (PR 피드백)
4. Clean Architecture (클린 아키텍처)

질문사항이 생기면 바로바로 DM이나 PR을 통해 남기겠습니다. 🙇🏻

## 스크린샷 및 영상

|[메인 화면] 카드 팝오버 표시|[메인 화면] 카드 팝오버 Section 이동|
|:---:|:---:|
|<img width="800" src="https://i.imgur.com/CoeyFZk.gif"/>|<img width="770" src="https://i.imgur.com/lLARdES.gif"/>|

|[메인 화면] 카드 이동 시 마감 시간순 정렬|
|:---:|
|<img width="370" src="https://i.imgur.com/xNVHnq3.gif"/>|

2022-07-10 17:06 UTC, llingo commented on ProjectManager/ProjectManager/Scene/MainScene/ViewController/CardAdditionViewController.swift
> +  init(viewModel: CardListViewModelable) {
네이밍을 프로토콜답게 CardListViewModelable로 변경했습니다!

2022-07-10 17:11 UTC, llingo commented on ProjectManager/ProjectManager/Scene/MainScene/ViewController/CardListViewController.swift
> +      .disposed(by: disposeBag)
길게 탭하는 (제스처) 이벤트가 발생하면 popOver 띄워주고 Observable로 이벤트를 관측하고 있다가 이벤트가 전달되면 그때 bind(onNext:)로 넘어가서 viewModel의 moveDifferentSection 메서드를 호출할 수 있도록 했습니다.

> moveDifferentSection은 card를 cardType으로 변경하는 메서드입니다!

2022-07-10 17:12 UTC, llingo commented on ProjectManager/ProjectManager/Scene/MainScene/ViewController/CardListViewController.swift
> +      guard let self = self, let cell = cell else {
Pop Over는 Action 이벤트가 발생하면 한번 실행하고 onNext -> onCompleted 되어야하므로 Single로 구현했습니다!

2022-07-10 17:20 UTC, llingo commented on ProjectManager/ProjectManager/Util/Extension/UITableView+Extension.swift
> +    return ControlEvent(events: source)
LongPressGesture 이벤트가 발생할때의 이벤트를 커스텀하여 ControlEvent(UITableViewCell, T)>가 반환되도록 기능을 확장했습니다.

2022-07-12 00:21 UTC, jungseungyeo requested changes
링고 고생하셨습니다.

매번 느끼지만 코드의 상태는 너무 좋은거 같아요. 그래서 조언이나 피드백 할 부분을 찾다가 시간을 많이 잡아 먹는거 같네요 ㅎㅎ..

이번 프로젝트에서 커스텀을 하여 함수를 만들어서 사용하는 것을 보았는데요. 현업에서도 이러한 형태로 필요한 것을 많이 만들어서 사용하고 있어요. 그러한 관점에서 매우 잘 작업을 해준거 같아요.

### 1. modalLogPressed

`이 함수 너무 잘만들었어요. 주의 할 점은 view(cell)를 스트림을 통해서 전달 을 할 떄 참조가 어떻게 이동하는지 관찰하면서 이동하면 좋아요. UIView는 class라 순환 참조가 될 수 있기 때문이고 deinit이 호출이 안되는 경우가 발생 할 수 있어서 이러한 부분만 신경쓰고 작업하면 좋을거같아요. `

### 2. showPopover

`이 함수는 코멘트를 달았지만 이러한 형태가 되면 활용도가 낮아지는 거같아요. alert을 단순히 만들고 호출하고 버튼 클릭 이벤트만 전달하고 전달 받은 곳에서 처리를 한다면 앞으로 만들 앱에서 더 활용도가 높을 거 같아요 ㅎㅎ 이부분은 수정을 한번해보면 좋을거같네요 ㅎㅎ`

### 리뷰노트

### ViewController들 간의 의존도 문제

`이런 고민은 좋은거같아요. 어느 방법을 딴 좋은거는 아니지만 현재 다들 Coornator 패턴으로 해결을 하는 거같아요. 이러한 형태도 좋고 다른 형태도 좋습니다. ㅎㅎ 의도만 명확하면 되는 거같아요. 많은 다른 해결 방법 중 왜 Coordinator인가? 이런 부분만 명확하면 될 거같아요. 다른 해결 책을 Builder 패턴을 사용하는 것도 좋재해요. 그래서 명확한 의도를 왜 많은 해결 책 중 이 패턴인가? 이 부분의 답을 생각하고 진행해주세요 :) `

### 2. 질문. ViewModel과 ViewController는 1:1과 1:N 어떠한 구조를 가져가는 것이 좋을까요?

`단은 1:N이 좋아요. 1:1로 구성이 되게 되면 테스트가 불가능한 코드가 되고 의존도가 더 높아지게 작성이 되는거죠. 1:1의 형태는 MVVM패턴의 기본이 1:N의 구조도 많이 위반하게 될 수 있어요.

질문중에 Manager라는 객체를 만들어서 해결하는 포인트도 있지만 Apple에서는 POP 구조를 통해서 해결을 하는 것을 권장하고 있어요. DataManager라는 객체를 두고 만드는 것도 좋지만 이러한 형태가 많이질수록 주입을 다시 많이 해주어야 하죠? Protocol을 활용하는 방법으로 Apple이 권장하고 있고 객체지향 프로그램에서도 많이 사용하는 방법이예요 ㅎㅎ`

링고 고생하셨습니다. 코멘트와 질문을 보고 수정을 부탁드려요. 감사합니다.

2022-07-12 00:21 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Model/Card.swift
> +  var moveToMenuTitle: String {
제가 좋아하는 스타일이네요 ㅎㅎ

2022-07-12 00:21 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Scene/MainScene/ViewController/CardDetailViewController.swift
> +  private let viewModel: CardListViewModelable
프로토콜의 의미하는 네이밍으로 만들어서 바로 프로토콜인지 인지가 되는거 같아요. 또 프로토콜을 선업하니 의존도가 많이 낮아지죠? ㅎㅎ 이러한 코드를 작성하는 것도 좋지만 의도를 잘 이해하고 설명할수있으면 면접에서 매우 도움이 될 거같아요 ㅎㅎ

2022-07-12 00:21 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Scene/MainScene/ViewController/CardListViewController.swift
> +      .disposed(by: disposeBag)
modelLongPressed를 직접 만들어서 사용했군요 ㅎㅎ 작업을 하다보면 이러한 경우가 많이 생기게 됩니다. 직접 만들어서 사용하는 포인트가 너무 좋습니다.

2022-07-12 00:21 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Util/Extension/UITableView+Extension.swift
> +  func modelLongPressed<T>(_ modelType: T.Type) -> ControlEvent<(UITableViewCell, T)> {
이 함수 너무 좋네요 ㅎㅎ

2022-07-12 00:21 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Util/Extension/UITableView+Extension.swift
> +      .flatMap { [weak view = base as UITableView] indexPath -> Observable<(UITableViewCell, T)> in
weak view를 잘 사용했네요 ㅎㅎ 참조타입의 view를 사용하면 릭이 발생할수있는데 ㅎㅎ적절한거같네요

2022-07-12 00:21 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Util/Extension/UITableView+Extension.swift
> +    return ControlEvent(events: source)
좋네요 ㅎㅎ 롱프레스 이벤트를 만들어서 사용하는 모습이 좋습니다 :)

2022-07-12 00:21 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Scene/MainScene/ViewController/CardListViewController.swift
> +    }.asObservable()
showPopover라는 함수를 보고 너무 잘 만든거 같아서 놀랐습니다. 이러한 함수도 좋지만 그래도 업그레이드?를 조언하자면 이렇게 정의 된 상태로 함수를 만들면 활용도가 적을거같아요. 

여기서는 첫번째 버튼이 늘렸어, 두번째 버튼이 눌렸어 라는 단순한 이벤트만 적용하고 사용하는 곳에서 이벤트의 따라 행동을 정의한다면 추후에도 활용도가 높은 코드가 될 거 같아요.

2022-07-12 09:35 UTC, llingo commented on ProjectManager/ProjectManager/Scene/MainScene/ViewController/CardListViewController.swift
> +    }.asObservable()
아래와 코드와 같이 버튼을 클릭할 시 Int 값을 방출하도록 변경했고
```swift
private func showPopover(
  sourceView: UIView,
  firstTitle: String,
  secondTitle: String
) -> Observable<Int> {
  return Single<Int>.create { [weak self] emitter in
    guard let self = self else {
      emitter(.failure(RxCocoaError.unknown))
      return Disposables.create()
    }
    
    let alert = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
    alert.modalPresentationStyle = .popover
    alert.popoverPresentationController?.permittedArrowDirections = .up
    alert.popoverPresentationController?.sourceView = sourceView.superview
    alert.popoverPresentationController?.sourceRect = CGRect(origin: sourceView.center, size: .zero)
    
    let firstAction = UIAlertAction(title: firstTitle, style: .default) { action in
      emitter(.success(0))
    }
    let secondAction = UIAlertAction(title: secondTitle, style: .default) { action in
      emitter(.success(1))
    }
    alert.addAction(firstAction)
    alert.addAction(secondAction)
    self.present(alert, animated: true)
    
    return Disposables.create {
      alert.dismiss(animated: true)
    }
  }.asObservable()
}
```

이벤트에 따라 행동을 정의해주었습니다.
또한, 중복된 showPopover 코드를 Long Press를 Observable of 로 묶고 merge로 합쳐 줄였습니다.

```swift
Observable.of(
  todoSectionView.tableView.rx.modelLongPressed(Card.self),
  doingSectionView.tableView.rx.modelLongPressed(Card.self),
  doneSectionView.tableView.rx.modelLongPressed(Card.self)
)
.merge()
.flatMap { cell, card -> Observable<(Int, Card, [CardType])> in
  let (first, second) = self.distinguishMenuType(of: card)
  let popover = self.showPopover(
    sourceView: cell,
    firstTitle: first.moveToMenuTitle,
    secondTitle: second.moveToMenuTitle
  )
  
  return Observable.zip(
    popover,
    Observable.just(card),
    Observable.just([first, second])
  )
}
.map { index, card, cardTypes in
  return (card, cardTypes[index])
}
.bind(onNext: { [weak self] card, cardType in
  self?.viewModel.moveDifferentSection(card, to: cardType)
})
.disposed(by: disposeBag)
}
```

2022-07-12 13:40 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Scene/MainScene/ViewController/CardListViewController.swift
> +    }.asObservable()
이런 의도는 아니였는데 ㅎㅎ. UIAlertViewController를 extension으로하여 만드는 것을 이야기한 내용이였어요 ㅎㅎ 

`UialertViewController.present(actionTitle: String, actionTitle: String) -> Single<index> `
이렇게 되어 있어서 flatmap에서 실행하고 다음 스트림에서 index가 넣어오면 처리하는 방식을 이야기한거예요 ㅎㅎ..

다음 스텝에서 한번 만들어보시면 좋을거같네요 ㅎㅎ

2022-07-12 13:41 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Scene/MainScene/ViewController/CardAdditionViewController.swift
> +  init(viewModel: CardListViewModelable) {
너무 좋습니다 :)

2022-07-12 13:42 UTC, jungseungyeo approved these changes
링고 고생하셨습니다 다음스텝에서 presentalert부분을 수정해서 부탁드립니다 :)

2022-07-12 13:42 UTC, merged

2022-07-13 07:03 UTC, llingo commented on ProjectManager/ProjectManager/Scene/MainScene/ViewController/CardListViewController.swift
> +    }.asObservable()
피드백 해주신 내용을 반영하여 UIAlertController에서 Extension으로 present 메서드를 구현하고 Action를 enumerated를 사용하여 각각 이벤트가 발생하면 index를 방출하도록 해보았습니다! 

```swift
extension UIAlertController {
  struct AlertAction {
    let title: String
    let style: UIAlertAction.Style = .default
  }
  
  static func present(
    _ presenter: UIViewController,
    title: String? = nil,
    message: String? = nil,
    preferredStyle: UIAlertController.Style = .actionSheet,
    actions: [AlertAction],
    _ block: ((UIAlertController) -> Void)? = nil
  ) -> Observable<Int> {
    return Single.create { observer in
      let alert = UIAlertController(title: title, message: message, preferredStyle: preferredStyle)
      block?(alert)
      
      actions.enumerated().forEach { index, action in
        let action = UIAlertAction(title: action.title, style: action.style) { _ in
          observer(.success(index))
        }
        alert.addAction(action)
      }
      presenter.present(alert, animated: true)
      
      return Disposables.create {
        alert.dismiss(animated: true)
      }
    }.asObservable()
  }
}
```

PopOver를 iPad에서 구현하는 경우 SourceView와 SourceRect를 Alert에 추가적인 설정이 필요하기 때문에 escaping 클로저를 통해 추가 설정을 할 수 있도록 열어두었습니다. 

**escaping 클로저를 사용하게된 이유**는 해당 설정을 내부에서 해주게되면 PopOver만을 위한 Alert가 될 것이라고 생각했기 때문입니다.

구현된 재사용 UIAlertController를 통해 modelLongPressed를 개선해보면 아래와 같습니다!

```swift
Observable.merge(
  todoSectionView.tableView.rx.modelLongPressed(Card.self).asObservable(),
  doingSectionView.tableView.rx.modelLongPressed(Card.self).asObservable(),
  doneSectionView.tableView.rx.modelLongPressed(Card.self).asObservable()
)
.flatMap { [weak self] cell, card -> Observable<(Card, CardType)> in
  guard let self = self else { return Observable.empty() }
  
  let menuTypes = self.distinguishMenuType(of: card)
  let actions = menuTypes
    .map { $0.moveToMenuTitle }
    .map { UIAlertController.AlertAction(title: $0) }
  
  let actionDidTapEvent = UIAlertController.present(self, actions: actions) { alert in
    let sourceRect = CGRect(x: cell.bounds.midX, y: cell.bounds.midY, width: .zero, height: .zero)
    alert.modalPresentationStyle = .popover
    alert.popoverPresentationController?.permittedArrowDirections = .up
    alert.popoverPresentationController?.sourceView = cell
    alert.popoverPresentationController?.sourceRect = sourceRect
  }.map { menuTypes[$0] }
  
  return Observable.zip(Observable.just(card), actionDidTapEvent)
}
.bind(onNext: { [weak self] card, cardType in
  self?.viewModel.moveDifferentSection(card, to: cardType)
})
.disposed(by: disposeBag)
```

혹시 생각하셨던 방향이 맞을까요?