프로젝트 관리 앱 [STEP 2] 두두, 마이노
yagom-academy/ios-project-manager pull request #138
Opened 2022-07-11 11:53 UTC by Mino777

안녕하세요 올라프 @1Consumption !
프로젝트 매니저 STEP2 PR 보냅니다
Combine, MVVM, CleanArchtiecture, DIContainer, Coordinator를 처음 써보다 보니 구조, 로직, 테스트까지 미숙한 부분이 너무 많을것 같습니다.
올라프의 날카로운 피드백 부탁드립니다!!!

감사합니다!!!

## 실행 화면

### 생성

<img src="https://i.imgur.com/ww6Mp69.gif" width="400">

### 편집

<img src="https://i.imgur.com/kkaGsEA.gif" width="400">

### 이동

<img src="https://i.imgur.com/So8EgG1.gif" width="400">

## 구조

### DIContainer, Coordinator
<img src="https://i.imgur.com/fiGtIdn.png" width="600">

### MVVM, CleanArchitecture
<img src="https://i.imgur.com/rAVuZ8Y.png" width="600">

### Presentation Layer
- UI를 포함하는 계층으로 View와 ViewModel을 포함
- 화면을 보여주는 역할

#### View

- View는 ViewModel에게 이벤트를 전달
- View는 ViewModel을 관찰하고, 변화가 있을때 UI를 업데이트

#### ViewModel
- View에서 이벤트가 발생했을 때 UseCase를 실행시키고, Actions를 실행시켜 UI에 업데이트를 알리는 역할

### Domain Layer
- 비즈니스 로직을 포함하는 계층으로 Entity, UseCase, Repository Interface를 포함

#### UseCase
- ViewModel에서 분리된 비즈니스 로직을 담당하는 객체

#### Entity
- 비즈니스 모델

#### Repository Interface
- 의존성을 역전시켜 Domain Layer인 UseCase가 Data Layer인 Repository를 직접 소유하지 않게 해주는 프로토콜

### Data Layer
- Data Source를 포함하는 계층으로 Repository와 API, DB등을 포함

#### Reposiotry
- 내부 외부 데이터를 가져오고, 가공해주는 역을 하는 객체

## 고민한점 및 궁금한점

#### Delegate 분리

TodoListViewController가 너무 커지다 보니, tableview의 delegate와 dataSource를 분리해 주려 했습니다.
DiffableDataSource를 사용했기에, DataSource의 경우 별도의 class로 문제없이 분리할 수 있었습니다.
그러나 Delegate의 경우 따로 Delegate를 담당하는 객체를 또 만들기 보단 VC를 delegate로 설정했습니다.
그래서 TodoListViewController를 extension해서 별도의 파일로 분리해 주었습니다.

이러다보니 private인 프로퍼티들을 사용하지 못하는 문제가 있었습니다.
private을 풀거나, getter를 구현하는 방법중 고민하다 아래와 같이 getter를 구현했습니다
이게 괜찮은 방법일까요?

```swift
extension TodoListViewController {
    func getViewModel() -> TodoListViewModelable {
        return viewModel
    }
    
    func getTodoListView() -> TodoListView {
        return todoListView
    }
    
    func getTodoDataSource() -> TodoListTableViewDataSource? {
        return todoDataSource
    }
    
    func getDoingDataSource() -> TodoListTableViewDataSource? {
        return doingDataSource
    }
    
    func getDoneDataSource() -> TodoListTableViewDataSource? {
        return doneDataSource
    }
}
```
#### Pop Over -> UIContextMenuConfiguration
Pop Over에 대한 학습을 위해 공식문서를 뒤지다가, UIContextMenuConfiguration이라는 Class를 발견하였습니다. 해당 부분의 경우 13.0부터 지원하고 기존 애플의 메모앱도 Cell을 꾹 눌렀을 때 UIMenu를 띄워주는것을 확인하여 Pop Over를 해당 부분으로 대체하였습니다.

#### MemoryDB만 사용하다보니 Data, Domain 영역이 애매해진 문제

현재는 MemoryDB(그냥 배열)만 사용하고, 또 네트워크 api호출이 아예 없습니다
그러다보니 UseCase가 Repository를 감싸고 있고, 또 Repository가 단순히 storage를 감싸고 있습니다.

어쩔수 없는 부분일까요?

#### Test 관련

현재 UseCase, Repository, Storage Mock 객체를 만들어서 ViewModel 테스트를 진행해보았습니다. 이렇게 테스트 하는것이 맞게 하고있는것인지 궁금합니다😭

#### CellViewModel

저희가 생각하기엔 Cell도 ViewModel을 가져야 한다고 생각이 들었습니다.
그런데 CellViewModel의 경우 주입을 어떤식으로 진행해주는것이 좋을까라는 고민이 있어서, 올라프에게 피드백을 받고 진행을 하는것이 좋을 것 같아 우선 ViewModel없이 진행하였습니다.

기존 대안의 경우 Cell이 ViewModel을 가지고있고 TableViewDataSource에서 CellViewModel을 인스턴스화해서 Cell의 bind(to: ViewModel) 메서드를 통해 각 Cell마다 ViewModel과 Cell을 1대1 관계로 주입을 시켜주려고 하였습니다.

감사합니다!

2022-07-11 18:20 UTC, 1Consumption requested changes
안녕하세요 마이노 두두~ 잘부탁드립니다 🙇
이번 스텝에서 정말 많고 어려운걸 하셨네요ㅎㅎ...  

객체들이 각자의 역할에 충실하게 짜려고 노력한 모습이 보였고, 실제로 대부분 그렇게 짜져 있어서 읽기 좋았습니다.
또한 로직의 흐름에도 통일성이 있어서 코드가 예측이 되어 구조를 파악하기 좋았어요.

다만 아쉬운점은 RC 관리가 미흡하다는 점과, 현재 규모에 맞게 패턴을 타협봤다는 점입니다.
우리는 지금 `학습`을 하고 있으니 타협은 최대한 있어서는 안됩니다.

아래는 고민하신 점에 대한 제 생각입니다.

# 고민한점 및 궁금한점
## Delegate 분리
TodoListViewController가 너무 커지다 보니, tableview의 delegate와 dataSource를 분리해 주려 했습니다.
DiffableDataSource를 사용했기에, DataSource의 경우 별도의 class로 문제없이 분리할 수 있었습니다.
그러나 Delegate의 경우 따로 Delegate를 담당하는 객체를 또 만들기 보단 VC를 delegate로 설정했습니다.
그래서 TodoListViewController를 extension해서 별도의 파일로 분리해 주었습니다.

이러다보니 private인 프로퍼티들을 사용하지 못하는 문제가 있었습니다.
private을 풀거나, getter를 구현하는 방법중 고민하다 아래와 같이 getter를 구현했습니다
이게 괜찮은 방법일까요?

> 코멘트에도 달았는데, 프로퍼티가 있어야할 곳에 있지 않고, 엉뚱한 곳에 있어서 발생한 문제라고 생각됩니다. 

## MemoryDB만 사용하다보니 Data, Domain 영역이 애매해진 문제
현재는 MemoryDB(그냥 배열)만 사용하고, 또 네트워크 api호출이 아예 없습니다
그러다보니 단순하게 UseCase가 Repository의 메서드를 호출하는 역할을 하고, 또 Repository가 단순히 storage의 메서드를 호출하는 역할만 가지고 있습니다.
따라서 현재 요구사항에 대해서는 알맞지 않은 패턴이라고 생각이 드는 것 같습니다.
해당 부분은 비즈니스 로직이 고도화 되지 않는 이상 우선 이번 스텝에서는 이러한 단순한 로직의 경우엔 굳이 이러한 패턴을 사용하지 않아도 될 것 같다 라는 부분만 이해하고 넘어가도 되는 부분일까요?

> 말씀해주신대로 규모가 작아서 발생한 문제이자 역할을 잘게 쪼갠 패턴의 고질적인 문제라고 볼 수있어요. 너무 많고 반복된다고 느끼는 코드가 발생하거든요. 하지만 통일성을 위해 패턴을 지켜주세요. `학습`에 초점을 맞추고 최대한 정석으로 가는 방향으로 잡아봅시다.

## Test 관련
현재 UseCase, Repository, Storage Mock 객체를 만들어서 ViewModel 테스트를 진행해보았습니다. 이렇게 테스트 하는것이 맞게 하고있는것인지 궁금합니다😭

> 아직 테스트더블에 대한 학습이 부족한듯 합니다. 또한 View를 제외한 모든 객체는 테스트를 작성해주세요.

CellViewModel
저희가 생각하기엔 Cell도 ViewModel을 가져야 한다고 생각이 들었습니다.
그런데 CellViewModel의 경우 주입을 어떤식으로 진행해주는것이 좋을까라는 고민이 있어서, 올라프에게 피드백을 받고 진행을 하는것이 좋을 것 같아 우선 ViewModel없이 진행하였습니다.

기존 대안의 경우 Cell이 ViewModel을 가지고있고 TableViewDataSource에서 CellViewModel을 인스턴스화해서 Cell의 bind(to: ViewModel) 메서드를 통해 각 Cell마다 ViewModel과 Cell을 1대1 관계로 주입을 시켜주려고 하였습니다.

> 말씀하신대로 저도 Cell도 View니까 ViewModel을 가져야한다고 생각해요. 그리고 전달하는 시점도 dequeue시점이 좋아보입니다.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Application/AppCoordinator.swift
> +    private let navigationController: UINavigationController
strong하게 잡아야만 하나요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Application/AppCoordinator.swift
> +        sceneCoordinator.start()
이 coordinator는 어디서 들고 있나요? 의도한 코드대로라면 이 메소드를 지나면 rc가 0이 되어 사라져야 하는데 말이죠. 어디선가 잡고있는걸까요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Application/DIContainer/AppDIContainer.swift
> +}
얘를 프로토콜로 만들면 좋겠습니다. 지금은 `TodoListSceneDIContainer`에서는 무조건 `MemoryStorage` 인스턴스를 사용하겠네요.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Application/DIContainer/ToDoListSceneDIContainer.swift
> +    private let dependencies: Dependencies
이 프로퍼티는 왜 strong하게 잡고 있나요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Application/DIContainer/ToDoListSceneDIContainer.swift
> +extension TodoListSceneDIContainer: TodoListSceneCoordinatorDependencies {
DIContainer에서 너무 많은 일을 하는듯 합니다. ViewController를 만드는 factory 정도가 더 있으면 어떨까요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Application/SceneDelegate.swift
> +        appCoorinator = AppCoordinator(navigationController: rootNaivgationController, appDIContainer: AppDIContainer())
appDIContainer는 별다른 매개변수 없이 바로 생성해서 넘겨주네요. 내부에서 바로 생성하지 않고 넘겨주는 이유가 있을까요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Common/Extension/Date.swift
> +}
로직이니 extension말고 로직을 담당하는 객체로 옮겨주세요.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Repository/TodoListRepository.swift
> +    }
얘는 왜 publisher를 반환하나요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Repository/TodoListRepository.swift
> +        }
read 메소드가 퍼블리셔를 반환해서 이런 이상한 구조가 나온거 같아요.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Storages/MemoryStorage.swift
> +    @Published private var items: [TodoListModel] = TodoListModel.dummyData()
`@Published`, `CurrentValueSubject`, `PassthroughSubject`의 차이는 뭔가요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Storages/MemoryStorage.swift
> +    }
items를 AnyPublisher로 변환 후 반환만 했는데, 해당 프로퍼티를 구독시 값을 방출하는 이유는 뭘까요?(별다른 upstream의 변화 가 없음에도 불구하고)

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Storages/MemoryStorage.swift
> +    }
```suggestion
    func delete(_ item: TodoListModel) {
        items.removeAll { $0.id == item.id }
    }
```

이렇게 바꿀수도 있어요.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Storages/MemoryStorage.swift
> +    }
thread safe 한가요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Domain/UseCase/TodoListUseCase.swift
> +}
예전부터 궁금했는데, extension으로 나누는 기준은 뭔가요? 왜 굳이 이렇게 나눴나 싶어서요.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/Coordinators/TodoListSceneCoordinator.swift
> +    private let dependencies: TodoListSceneCoordinatorDependencies
얘는 왜 weak이나 unowned가 아닌가요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/Coordinators/TodoListSceneCoordinator.swift
> +    }
DetailViewController도 Coordinator가 필요해보입니다. 이런식으로 편의를 위해 패턴을 스킵하지 말아주세요.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/View/TodoDetailView.swift
> +final class TodoDetailView: UIView {
여기는 왜 ViewModel이 없나요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/View/TodoDetailViewController.swift
> +    private lazy var todoDetailView = TodoDetailView(frame: self.view.bounds)
어차피 오토레이아웃으로 잡는데, 굳이 lazy var를 사용해서 view의 frame을 넣어야하나요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/View/TodoDetailViewController.swift
> +        title = "TODO"
진짜 엄밀히 따지면 이런 값도 ViewModel에서 가지고 있어야해요.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/View/TodoDetailViewController.swift
> +        }
이런 값들이 실제로 유효한지 아닌지는 ViewModel에서 판단해야할 문제라고 생각합니다.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/View/TodoDetailViewController.swift
> +        }
어떻게보면 아 다르고 어 다르지만, 이런 분기문마저 ViewModel에서 관리해야한다고 봅니다. View는 ViewModel을 바라만 보고 그에 맞는 행동을 할 뿐이죠.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +    var item: Just<TodoListModel> { get }
여기는 왜 Just인가요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +    }
todoListModel을 PassthroughSubject로 만드는거랑 다른게 있나요? 이 코드의 의도가 궁금합니다.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +    private let actions: TodoDetailActions?
이 actions는 왜 옵셔널인가요? 뭔가 꼭 필요해보이는데요.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +        }
```suggestion
        isCreate.send(todoListModel.title.isEmpty && todoListModel.content.isEmpty)
```

반환형이나 넘기는 값이 Bool이면 조건문 자체를 넣어도 됩니다.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +
제가 영어를 잘 못하긴 하는데, didTap~가 더 맞지않나요?
그리고 이런 로직은 UseCase에 들어가는게 더 나아보여요. ViewModel의 View의 로직에만 집중 할 수 있게요. ViewModel도 UseCase에게 이벤트를 보낼 뿐입니다.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +        )
그런데 일반적으로 update 메소드는 실패할 확률이 전혀 없을까요? 물론 지금은 그렇지 않을수도 있는데, 디스크에 저장하기 시작한다면 얘기는 달라질 ㅓㄱ 같아요.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +    let isCreate = CurrentValueSubject<Bool, Never>(true)
is+동사원형은 조금 어색하네요. 코코아터치 프레임워크 네이밍을 참고해보세요.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/Cell/TodoTableViewCell.swift
> +        contentView.frame = contentView.frame.inset(by: UIEdgeInsets(top: 5, left: 0, bottom: 0, right: 0))
음... 이 코드의 의도는 뭔가요? 조금 난해하네요.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/Cell/TodoTableViewCell.swift
> +    }
Cell의 ViewModel에 들어가야할 로직 같습니다.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/TodoListTableViewDataSource.swift
> +}
흠.. 이걸 굳이 분리한 이유가 있을까요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/TodoListTableViewDelegate.swift
> +}
이 코드를 extension으로 뺀 이유가 궁금합니다. 오히려 가독성이 더 안좋은거 같아요.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/TodoListView.swift
> +    }()
`헤더 + 테이블뷰` 를 하나의 class로 묶어서 사용하는게 재사용 측면에서 더 좋지 않을까요? 지금 이 코드에서 `Todo, Doing, Done` 외의 다른 section이 추가된다면 어떻게 해야할까요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/TodoListViewController.swift
> +    private lazy var todoListView = TodoListView(frame: self.view.bounds, tableViewDelegate: self)
tableView의 Delegate를 이 뷰컨이 채택해야만 하는 이유가 있나요? TodoListView가 tableView를 가졌으니 해당 뷰에서 채택하면 안되는걸까요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/TodoListViewController.swift
> +    }
이거를 여기에서 한번에 해야할까 의문입니다. 각 View의 ViewModel에서 할 수 있지 않을까요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/TodoListViewController.swift
> +}
이거 또한 위치가 잘못되었다고 생각해요. 해당 View에서 필요한 정보를 엉뚱한 곳에서 들고 있는게 아닐까요?

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/ViewModel/TodoListViewModel.swift
> +        let item = TodoListModel(title: "", content: "", deadLine: Date().endOfTheDay ?? Date())
빈 모델을 만들고 싶다면 이런 방법도 있습니다.

``` swift
struct TodoListModel: Hashable {
    let id: String
    let title: String
    let content: String
    let deadLine: Date
    var processType: ProcessType
    
    static let empty: Self = .init(title: "", content: "", deadLine: Date().endOfTheDay ?? .init())
    
    init(
        title: String,
        content: String,
        deadLine: Date,
        processType: ProcessType = .todo,
        id: String = UUID().uuidString
    ) {
        self.id = id
        self.title = title
        self.content = content
        self.deadLine = deadLine
        self.processType = processType
    }
}
```

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManagerTests/Mock/MemoryStoregeMock.swift
> +}
Mock과 Stub의 차이는 뭔가요?
[여기](https://martinfowler.com/articles/mocksArentStubs.html)랑 [여기](https://academy.realm.io/kr/posts/making-mock-objects-more-useful-try-swift-2017/)를 참고해보세요.

2022-07-11 18:20 UTC, 1Consumption commented on ProjectManager/ProjectManager.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.5;
테스트 타겟과 프로덕 타겟 버전이 다르네요.

2022-07-12 07:33 UTC, FirstDo commented on ProjectManager/ProjectManager/Application/DIContainer/ToDoListSceneDIContainer.swift
> +extension TodoListSceneDIContainer: TodoListSceneCoordinatorDependencies {
https://github.com/yagom-academy/ios-project-manager/pull/138/commits/4197a260de44c4ef5b6c1b4115b82f59f6d3e3ea

ViewControllerFactory를 만들어보았습니다!

2022-07-12 07:40 UTC, Mino777 commented on ProjectManager/ProjectManager/Application/DIContainer/AppDIContainer.swift
> +}
https://github.com/yagom-academy/ios-project-manager/pull/138/commits/bec9442868782f929849f2975b3d6a966cd11e1a

해당 부분 프로토콜로 추상화 하였습니다!
감사합니다!

2022-07-12 07:43 UTC, Mino777 commented on ProjectManager/ProjectManager/Application/SceneDelegate.swift
> +        appCoorinator = AppCoordinator(navigationController: rootNaivgationController, appDIContainer: AppDIContainer())
https://github.com/yagom-academy/ios-project-manager/pull/138/commits/bec9442868782f929849f2975b3d6a966cd11e1a

AppDIContainer를 프로토콜로 추상화 해주면서 추후 테스트에 용이해진 것 같습니다!

2022-07-12 07:44 UTC, Mino777 commented on ProjectManager/ProjectManager.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 15.5;
https://github.com/yagom-academy/ios-project-manager/pull/138/commits/9517a8cbcc9f1faeab436fa437f71e5570b59f16

앗..! 해당 부분 14.4로 모두 수정하였습니다!

2022-07-12 07:49 UTC, Mino777 commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/ViewModel/TodoListViewModel.swift
> +        let item = TodoListModel(title: "", content: "", deadLine: Date().endOfTheDay ?? Date())
https://github.com/yagom-academy/ios-project-manager/pull/138/commits/c62fb262f2823585378548fa379e859fa5c87947

이런 방법이 있었네요!! 감사합니다!!

2022-07-12 07:59 UTC, Mino777 commented on ProjectManager/ProjectManager/Common/Extension/Date.swift
> +}
https://github.com/yagom-academy/ios-project-manager/pull/138/commits/1f5f906500d190e43611faa89cfc1c8daf8bc46e

해당 부분에서 DateFormatter()를 cell의 경우 생성될 때마다 계속해서 생성되기 때문에 아예 싱글턴으로 가지고 있는게 좋지 않을까? 라는 생각에 아예 DateManager 싱글턴 객체를 만들어서 사용하는 것으로 변경해보았습니다! 올라프는 이 부분 어떻게 생각하실까요?
감사합니다!

2022-07-12 08:02 UTC, Mino777 commented on ProjectManager/ProjectManager/Presentation/Coordinators/TodoListSceneCoordinator.swift
> +    }
https://github.com/yagom-academy/ios-project-manager/pull/138/commits/fe19ea2f28f85438115e187b2dee7cf86aedab89

DetailViewCoordinator 도 추가하였습니다!
감사합니다!

2022-07-12 13:17 UTC, FirstDo commented on ProjectManager/ProjectManager/Application/AppCoordinator.swift
> +    private let navigationController: UINavigationController
navigationController의 경우 굳이 여기서 strong하게 잡지 않아도 참조가 유지되는것을 확인했습니다
weak으로 변경하였습니다

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/9c459f6fef6411483e68d12608002d87112c8f6e

2022-07-12 13:20 UTC, FirstDo commented on ProjectManager/ProjectManager/Application/AppCoordinator.swift
> +        sceneCoordinator.start()
coordinator를 트리구조로 만들어서, 부모 코디네이터가 자식코디네이터를 잡고있도록 수정했습니다.

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/fe19ea2f28f85438115e187b2dee7cf86aedab89

2022-07-12 13:25 UTC, FirstDo commented on ProjectManager/ProjectManager/Data/Storages/MemoryStorage.swift
> +    }
아까 설명해주신대로, @Published 프로퍼티 wrapper가 붙은 것과, CurrentValueSubject는 구독을 했을때, 가장 최근값을 방출하기 때문입니다

2022-07-12 13:27 UTC, FirstDo commented on ProjectManager/ProjectManager/Data/Storages/MemoryStorage.swift
> +    }
밑의 코드가 훨씬 깔금해 보여 변경해 주었습니다!

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/7f6016f5d5b61bf7822c781f5938db73bacd0ccd

2022-07-12 13:29 UTC, FirstDo commented on ProjectManager/ProjectManager/Domain/UseCase/TodoListUseCase.swift
> +}
TodoListRepositorible 프로토콜의 요구사항 매서드들이었습니다
굳이 extension 할 필요는 없을것 같아서 제거하였습니다

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/c3c82b3f9618a5096003ebc6f40e891e7a1c7499

2022-07-12 13:34 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/View/TodoDetailViewController.swift
> +    private lazy var todoDetailView = TodoDetailView(frame: self.view.bounds)
놓친부분인것 같습니다..!
필요없는 lazy var 제거하고 frame을 받는 이니셜라이저 역시 제거해 주었습니다.

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/1013dfe3b798c8af1d30ce6147a3f983667ae22e

2022-07-12 13:39 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/View/TodoDetailViewController.swift
> +        title = "TODO"
title을 ViewModel로 옮겨주었습니다!

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/0dcae948c4a08d1aa01ccd376c64ced86177a19d

2022-07-12 13:45 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/View/TodoDetailViewController.swift
> +        }
guard문으로 검증하는 부분을 ViewModel로 이동하였습니다!

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/82c922c39cf107ba2cbe902a74a0ce275a7bfbae

2022-07-12 13:50 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +    var item: Just<TodoListModel> { get }
최초로 한번만 View에 이벤트를 방출하면 되서 한번만 방출하고 종료하는 Publisher인 Just로 구현했습니다

2022-07-12 13:51 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +    }
PassthroughSubject로 만들면, 이벤트를 더 받을 수 있지만, item은 최초 DetailViewController가 화면에 보여질때 딱 한번만 전달되면 되는 구조라서 Just로 구현했습니다

2022-07-12 13:52 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +    private let actions: TodoDetailActions?
클로져 때문에 rc관리가 너무 힘들어서 actions은 삭제하고, coordinator로 대체했습니다!!

2022-07-12 13:55 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/Cell/TodoTableViewCell.swift
> +        contentView.frame = contentView.frame.inset(by: UIEdgeInsets(top: 5, left: 0, bottom: 0, right: 0))
cell간의 간격을 주기위해서 작성했습니다

<img width="219" alt="스크린샷 2022-07-12 오후 10 55 04" src="https://user-images.githubusercontent.com/69573768/178506923-e5b2a5fc-7987-4ca3-b82b-b5cbe7b9652f.png">

2022-07-12 14:01 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +
didTap ~~~ 으로 변경해주었습니다!

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/1e40e922e87def807e41a33b683c5366465c3af7

if문을 통한 검증로직도 UseCase로 옮겨주었습니다!

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/05983ed38d4e4d1ceae53604018da33bb4bbb454

2022-07-12 14:25 UTC, FirstDo commented on ProjectManager/ProjectManager/Application/DIContainer/ToDoListSceneDIContainer.swift
> +    private let dependencies: Dependencies
코맨트를보고 MemoryStorage가 class니깐, 여기 unowned를 안써주면
MemoryStorage의 RC가 1보다 크다고 생각했습니다.

<img width="1005" alt="스크린샷 2022-07-12 오후 11 21 09" src="https://user-images.githubusercontent.com/69573768/178512711-ae45e8c5-d5f6-4c36-9433-aa9012d67f4c.png">

근데 MemoryGraph에서 Storage의 RC가 1로 나오고, unowned를 붙여서 아무 이상없이 똑같이 동작하는데, 이유를 찾지 못했습니다 ㅠㅠ

2022-07-12 14:28 UTC, Mino777 commented on ProjectManager/ProjectManager/Data/Repository/TodoListRepository.swift
> +    }
Storage의 배열을 바인딩하여 쓰기위해 publisher를 반환하였습니다!

2022-07-13 06:54 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/TodoListTableViewDataSource.swift
> +}
리팩토링하면서 삭제되었습니다..!

2022-07-13 06:55 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/TodoListTableViewDelegate.swift
> +}
마찬가지로 리팩하면서 제거하였습니다!
그냥 같은 파일에 두었습니다

2022-07-13 07:34 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/Cell/TodoTableViewCell.swift
> +    }
cell의 ViewModel로 옮겨주었습니다

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/79e338a9b520bcc944bf6627f153b157cf0f6734

2022-07-13 07:35 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/TodoListView.swift
> +    }()
말씀대로 하나로 묶었습니다!

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/5d73198020c7bcb247b7fca6818500c54931410a

2022-07-13 07:36 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/TodoListViewController.swift
> +    private lazy var todoListView = TodoListView(frame: self.view.bounds, tableViewDelegate: self)
TableView를 포함하고있는 TodoView가 tableview의 delegate, datasource가 되게 변경해주었습니다

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/5d73198020c7bcb247b7fca6818500c54931410a

2022-07-13 07:37 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/TodoListViewController.swift
> +    }
todoView로 합치면서 변경되었습니다!
(이전 코맨트와 동일합니다)

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/5d73198020c7bcb247b7fca6818500c54931410a

2022-07-13 07:37 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoList/View/TodoListViewController.swift
> +}
이전코맨트와 동일합니다!
TodoView를 만들면서 해당 View에 통합되었습니다

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/5d73198020c7bcb247b7fca6818500c54931410a

2022-07-13 07:43 UTC, Mino777 commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +        }
해당 부분 수정하였습니다!

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/e6f36dc66fb48078842383a5a28f2e7a4ef25cf0

2022-07-13 07:48 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/View/TodoDetailView.swift
> +final class TodoDetailView: UIView {
TodoDetailViewModel이 viewModel입니다
여기서 더 분리할 필요는 없다고 생각했습니다

2022-07-13 07:53 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +        )
다음스탭에서 realm storage를 적용하면 실패할 확률이 있을것 같습니다!!
해당 스탭 적용할때 말씀대로 고쳐보도록 하겠습니다!!

2022-07-13 08:32 UTC, Mino777 commented on ProjectManager/ProjectManager/Application/DIContainer/ToDoListSceneDIContainer.swift
> +    private let dependencies: Dependencies
해당 부분을 포함한 상위에서 선언되는 프로퍼티들에 unowned를 적용해 RC 관리를 해보려고 노력해보았습니다!
retainCount로 찍어보았을 때 기본값이 2로 적용된다는것도 알게되었습니다.
감사합니다!

https://github.com/yagom-academy/ios-project-manager/pull/138/commits/67dfa08aae04efd3539e4d1a677a928dfdc4e93a

2022-07-13 08:35 UTC, Mino777 commented on ProjectManager/ProjectManager/Data/Storages/MemoryStorage.swift
> +    }
추후에 디비 연결할 때 thread safe하게 수정하겠습니다!

2022-07-13 08:37 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/Coordinators/TodoListSceneCoordinator.swift
> +    private let dependencies: TodoListSceneCoordinatorDependencies
// SceneDIContainer
```swift
func makeCoordinator(navigationController: UINavigationController) -> TodoListViewCoordinator {
        return TodoListViewCoordinator(navigationController: navigationController, dependencies: self)
    }
```

// App Coordinator

```swift
let sceneDIContainer = appDIContainer.makeTodoListSceneDIContainer()
let sceneCoordinator = sceneDIContainer.makeCoordinator(navigationController: navigationController)
        
childCoordinators.append(sceneCoordinator)
sceneCoordinator.parentCoordinator = self
sceneCoordinator.start()
```

현재 App Coordinator에서 sceneDICotnainer를 만들고 있습니다.
그리고 sceneDIContainer에서 sceneCoordinator를 만들고 있습니다.

sceneCoordinator는 부모Coordinator의 배열에서 잡고있지만, sceneDIContainer는 참조하고 있는 객체가 없습니다.
그래서 sceneCoordinator에 주입할때 strong하게 주입해서, sceneCoordinator가 sceneDIContainer를 잡고 있게 했습니다

2022-07-13 08:42 UTC, Mino777 commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/ViewModel/TodoDetailViewModel.swift
> +    let isCreate = CurrentValueSubject<Bool, Never>(true)
isCreated로 변경하였습니다! 감사합니다!

2022-07-13 11:26 UTC, FirstDo commented on ProjectManager/ProjectManager/Data/Storages/MemoryStorage.swift
> +    @Published private var items: [TodoListModel] = TodoListModel.dummyData()
말씀해주신것처럼
CurrentValueSubject는 초기값이 있고, 가장 최근 값에 대한 버퍼를 유지하고 있습니다.
그래서 새로운 subscriber가 구독했을때 무조건 가장 최근 값을 방출합니다.

반면에 PassthroughSubject는 초기값이 없고, 가장 최근 값에 대한 버퍼를 유지하지 않습니다.
새로운 subscriber가 해당 subject를 구독했다면, 그 이전의 이벤트는 전달되지 않습니다
오직 구독 후에 발생하는 이벤트만 subscriber에게 전달됩니다

`@Published`와 `CurrentValueSubject`는 비슷하다고 생각합니다
다만 `@Published` property wrapper는 

1. 프로퍼티에 해당 property wrapper를 붙이면 publisher처럼 쓸 수 있게 지원해줌
2. class에만 쓸 수 있음
3. 에러를 방출하지 않는다 (Never 타입)

이런 특징을 가지고 있다고 생각합니다

2022-07-13 11:35 UTC, Mino777 commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/View/TodoDetailViewController.swift
> +        }
https://github.com/yagom-academy/ios-project-manager/pull/138/commits/849b9d481107f3de42f5aaff8947ea638530feb1

해당 부분 분기문 ViewModel로 이동하였습니다!

2022-07-13 12:36 UTC, FirstDo commented on ProjectManager/ProjectManagerTests/Mock/MemoryStoregeMock.swift
> +}
Mock은 행위검증
링크도 읽어보고 찾아보니, 이 행동이 일어났는가? (이 매서드가 호출되었는가??) 를 검증합니다

Stub은 상태검증
Stub의 경우에는 이미 반환해야될 결과값이 정해져 있습니다.
예를들어 네트워크 없이 네트워크를 테스트를 할때 MockURLSession을 만들던게 그 예시인것 같습니다.

현재 테스트를 위해 만드는 Storage, UseCase, Repository는 Fake에 가장 가까운것 같아 네이밍을 변경해 주었습니다

2022-07-13 13:47 UTC, FirstDo commented
올라프, 수정해 보았습니다!

하위뷰도 ViewModel을 가지게 하고, 하위 View에서 이벤트가 발생했을때 ViewModel에 알린후, 상위 ViewModel에게 다시 알려주도록 구현해보았는데, 이런식이 맞을까요?
ViewModel끼리의 통신은 delegate를 이용하였습니다

또한 Coordinator를 VC마다 만들었습니다

하지만 여전히 미숙한것 같습니다.. ㅠㅠ
방향성이 틀렸거나, 더 고쳐야 할 부분이 있다면 말씀해주시면 바로 수정하도록 하겠습니다!!

피드백 감사합니다!! :)

2022-07-14 10:36 UTC, 1Consumption commented on ProjectManager/ProjectManager/Common/Extension/Date.swift
> +}
싱글톤일 이유는 없는거같고... 필요한 곳에서 가지고 있으면 될거같아요.

2022-07-14 10:38 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/Coordinators/TodoListSceneCoordinator.swift
> +    private let dependencies: TodoListSceneCoordinatorDependencies
좋습니다. 👍

2022-07-14 10:39 UTC, 1Consumption commented
``` swift
    func dismiss() {
        navigationController?.dismiss(animated: true)
        parentCoordinator?.childCoordinators.removeAll { $0 === self }
    }
```

차일드는 패런트에게 이벤트만 보낼 뿐입니다. 이런 로직은 패런트에서 처리하게 해주세요.

2022-07-14 14:30 UTC, Mino777 commented
> ```swift
>     func dismiss() {
>         navigationController?.dismiss(animated: true)
>         parentCoordinator?.childCoordinators.removeAll { $0 === self }
>     }
> ```

> 차일드는 패런트에게 이벤트만 보낼 뿐입니다. 이런 로직은 패런트에서 처리하게 해주세요.


```swift
// AppCoordinator
extension Coordinator {
    func removeChild(_ coordinator: Coordinator) {
        childCoordinators.removeAll(where: { $0 === coordinator })
    }
}
```

```swift
// TodoDetailViewCoordinator
func dismiss() {
        navigationController?.dismiss(animated: true)
        parentCoordinator?.removeChild(self)
    }
```

Coordinator Protocol에 기본구현으로 진행을 해보았습니다!
감사합니다!

2022-07-14 14:39 UTC, Mino777 commented on ProjectManager/ProjectManager/Common/Extension/Date.swift
> +}
해당 부분 필요한 곳에서 가지고있또록 수정하였습니다!

2022-07-17 16:44 UTC, merged