프로젝트 관리 앱 [STEP 2] Donnie, Grumpy
yagom-academy/ios-project-manager pull request #139
Opened 2022-07-12 09:05 UTC by westeastyear

안녕하세요 라자냐! @wonhee009
Donnie, Grumpy 입니다.
[STEP 2] PR 보내드립니다!
`Reactive Programming`과 `MVVM` 패턴을 프로젝트에 처음 적용시키다 보니  미숙한 점이 많습니다. 
`RxSwift`, `MVVM`에 관련한 많은 조언 부탁드립니다! 잘 부탁 드립니다!! 🙇🏻🙇🏻‍♂️

<br>

## ⏳ 프로젝트 진행과정
- **[STEP 2-1]**
    - 화면 `UI` 구현
- **[STEP 2-2]**
    - 뷰 업데이트 및 비즈니스 로직 구현
- **[STEP 2-3]**
    - `RxSwift`, `RxCocoa`로 뷰의 요소들을 연결
- **[STEP 2-4]**
    - `MVVM` 구조로 비즈니스 로직 리팩토링

> - 위 4단계로 나누어 진행하였고 
> `[STEP 2-1]`, `[STEP 2-2]`를 `[STEP 2-1]브랜치`,
> `[STEP 2-3]`, `[STEP 2-4]`를 `[STEP 2-2]브랜치`로 나누어 작업하였습니다.

<br>

## 🏛 프로젝트 구조
- **사용한 외부 라이브러리**
    - `RxCocoa`
    - `RxSwift`
    - `RxRelay`
    - `RxGesture`
    - `SnapKit`
    - `RealmSwift`
- **View**
    - 사용자에게 보여지는 화면에 해당
- **View Controller**
    - `View`를 생성하고 데이터 바인딩을 통해 `View Model`로 데이터를 전달
    - 화면 이동 등 동작을 수신
- **View Model**
    - `View Controller`로부터 이벤트를 수신하여 비즈니스 로직(데이터베이스의 데이터 저장 등)을 처리하고 값 업데이트를 통해 뷰에 연결된 속성 갱신
- **RealmManager**
    - `Realm` 인스턴스를 갖고 `Real Database`에 조회, 수정, 추가, 삭제 작업을 담당하는 구조체

<br>

## 📺 상세 화면
|생성|수정|
|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/74251593/178438864-c0a64d55-654c-4b12-b6c3-d66a2ef36f40.gif" width="100%">|<img src="https://user-images.githubusercontent.com/74251593/178439799-864456ce-93e2-46a2-8b32-c719decc7ad6.gif" width="100%">|

|셀 삭제|팝오버 뷰|
|:---:|:---:|
|<img src="https://user-images.githubusercontent.com/74251593/178440435-0fff20c0-4641-4e07-9837-f60128939d87.gif" width="100%">|<img src="https://user-images.githubusercontent.com/74251593/178440781-97e2fa3d-6383-43f6-9798-5f44babdb8b3.gif" width="100%">|

|셀 이동|
|:---:|
|<img src="https://user-images.githubusercontent.com/74251593/178441458-0d4aca99-db43-4885-aa89-06441928e49d.gif" width="80%">|

<br>

## 🤔고민한점 및 🤩해결한 부분
### 1. 로컬 데이터베이스 사용
> - 프로젝트 요구사항에서는 __"할일의 모든 변경사항은 디스크에 저장하지 않고 앱 종료 후 다시 실행하면 빈 화면을 출력합니다"__ 라고 나와있습니다.
> - 팀원과 협의 후, 계속해서 빈 화면을 출력하는 로직으로 진행하게 되면 정상적인 기능구현인지 확인하기 어려울거라 판단하였고, `Realm`을 사용하여 데이터를 저장하며 프로젝트를 진행하였습니다.

<br>

### 2. `UI`프로퍼티 생성시, 간결함과 중복을 제거하기 위한 `Then`기능 활용
> - `Then`라이브러리를 그냥 가져다가 사용하지 않고 저희에게 필요한 기능을 가진 부분을 확인하여, 팀원과 한줄한줄 공부한다음 직접 구현하여 사용해 보았습니다.
> - 다른 캠퍼가 이 기능을 사용하는것을 우연히 알게 되었고, `UI`프로퍼티 생성시 당연한 줄만 알았던 중복되는 부분을 제거할 수 있다는 점에 매료되어 이번 프로젝트에 적용해 보았습니다.

```swift
protocol Then {}

extension Then where Self: AnyObject {
    func then(_ block: (Self) throws -> Void) rethrows -> Self {
        try block(self)
        return self
    }
}

extension NSObject: Then {}
```

<br>

### 3. `longPressed` 제스쳐를 테이블 뷰에 추가하는 방법
> - `longPressed` 제스쳐를 추가하려면 `GestureReconizer`를 생성하고 이를 테이블뷰에 추가해주어야 했습니다. 
> - 코드를 리팩토링하면서 `button.rx.tap`처럼 간단하게 `event`를 처리하는 로직이 있지 않을까 알아보다가 `RxGesture`를 통해 필요한 제스쳐에 대한 동작을 쉽게 핸들링할 수 있었습니다.

- 기존 방법
```swift
private func setupLongPressedGesture(at tableView: UITableView) {
    let longPressedGesture = UILongPressGestureRecognizer(target: self, action: #selector(handleLongPress))
    tableView.addGestureRecognizer(longPressedGesture)
}
@objc private func handleLongPress(gestureRecognizer: UILongPressGestureRecognizer) {
    if gestureRecognizer.state == .began {
        ....
    }   
}
```
- `RxGesture`라이브러리 사용 후
```swift
mainView.todoTableView.rx.longPressGesture()
    .when(.began)
    .map { $0.location(in: self.mainView.todoTableView) }
    .subscribe(onNext: { 
        ....
    })
    .disposed(by: disposeBag)
```

<br>

### 4. 기한에 지난 날짜가 있으면 빨간색으로 표시하는 방법
> - 처음엔 저장된 `date`와 현재 시간을 비교하여 기한이 지났는지 확인하는 로직을 사용하였는데, 날짜가 지나야 데드라인을 넘긴 항목으로 처리하도록 수정했습니다.
> - `now`는 오늘의 시작 시간(00:00)이 되어 오늘까지인 항목들은 `Label`을 빨간색으로 표시하지 않습니다.
```swift
let now = Calendar.current.startOfDay(for: Date()).timeIntervalSince1970
```

<br>

## 🧐 조언을 구하고 싶은 부분

### 1. 팝오버 뷰의 잘림 현상
<img src="https://i.imgur.com/SsTbiPa.png" width="50%"><br>

> - 셀을 길게 눌러 팝오버 메뉴를 표시할 때 다음과 같이 화살표가 생기는 쪽의 화면이 잘려서 나오는 현상이 있었습니다. 
> - `UIView`를 상속받은 `PopoverView`를 구현한 뒤 화면에 보여주는 방식 때문일까요? 이 부분에 대해 조언을 구하고 싶습니다.<br>
>    - **초록색: PopoverView의 크기**
>    - **빨간색: 화살표로 인해 윗부분이 잘린 실제 PopoverView의 크기**

<br>

### 2. 엇비슷하게 중복되는 코드 관리
> - 특히나 `MainViewController`에서 `tableView`를 세개나 사용하다 보니 비슷한 코드진행이 3개씩 나오고 있습니다.
> - 알기론 `UI`와 관련된 코드들은 중복을 감수하더라도 각 `UI`에 대한 코드가 따로 있는게 나중에 유지보수 측면에 더 나은 선택이라고 들었어서 코드중복을 감수하였습니다.
> - 이에 대해서 라자냐의 의견과, 만약 중복을 제거 할 수 있다면 어떤 방법이 있을지 조언을 구하고 싶습니다.

<br>

### 3. `View Controller` 내부에서의 `bind` 메서드 구현
> - `View`와 `View Model`간의 데이터 바인딩 과정을 모두 `View Controller`의 `bind()` 메서드 내에서 처리하고 있습니다.
> - 처리해야 하는 데이터가 많아질수록 `bind()` 메서드의 크기가 너무 커지는 것 같은데, `MVVM` 구조에서는 `View Model`이 `View`를 몰라야 한다는 규칙 때문에 극복할 수 없는 한계인지 궁금합니다.

<br>

2022-07-12 11:27 UTC, wonhee009 requested changes
수고하셨습니다 🎉 
코멘트 남겨두었으니 확인 부탁드려요 🙏 

- SPM Dependency들이 master 브랜치를 따라가도록 설정되어 있는데 의도한 부분인지 궁금합니다.
    - Master 브랜치를 따라간다면 어떤 문제가 있을까요?
- `RxGesture`는 `ReactiveX`에서 만들어진 라이브러리가 아닌 `RxSwiftCommunity`에서 만들어진 라이브러리인데 이를 사용한 이유가 있을까요?
    - 이런 라이브러리 사용할시 어떤 단점이 있을 수 있을까요?
- 코드 확인했을때 아래와 같이 SwiftLint가 워닝을 뱉는데 수정이 필요한걸까요?
<img width="1201" alt="스크린샷 2022-07-12 오후 6 50 33" src="https://user-images.githubusercontent.com/30456206/178479197-4e42bd44-fa07-4b8b-ad3a-4dee256092eb.png">

- 팝오버 뷰의 잘림 현상: 제가 확인했을때는 다 잘 나오고 있어서 발생하는 화면이나 경로를 알려주시면 좋을거 같습니다 :)
- View Controller 내부에서의 bind 메서드 구현: 보통은 `bind` 메서드 내에서 전체 연결해주긴 하는데 너무 많거나 길면 bind > bindA, bindB 이런식으로 `bind` 메서드 내에서도 좀 더 나눠서 메서드를 뚫기도 하는거 같습니다.

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Scene/View/TaskHeaderView.swift
> +    }
`lazy`를 사용한 이유가 있을까요?
지연될 필요가 없는 부분 같아 질문 드립니다.

`headerStackView` 같은 경우는 `arrangedSubviews` 때문이라고 이해했는데요.
이 부분 setupSubViews` 메서드 내에서 arrangedSubviews 해주는 방식으로 풀어갈 수 있을거 같습니다.

해당 사항들이 `lazy` 때문에 `var`가 붙어 있는데 사실상 변경이 없는 프로퍼티들이라서 `let`이 더 맞을거 같습니다.

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Scene/View/MainView.swift
> +    private(set) lazy var doneTableView = generateTableView()
`HeaderView`와 `TableView`를 따로 선언한 이유가 있을까요?
`TableView` 내에서 headerView를 지정해줘도 좋을거 같습니다.

> 엇비슷하게 중복되는 코드 관리

해당 질문과 관련한 사항인데요.

```swift
final class TaskTableView: UITableView {
   private let taskType: TaskType
   
   init(taskType: TaskType) {
      self.taskType = taskType
   }

   // 헤더뷰 지정
}
```
todo, doing, done 테이블뷰에서 하는 일이 완전 동일하다면 이런식으로 사용할 수 있지 않을까요?
세 테이블뷰에서 하는 일이 조금씩 다르다면 상속을 이용해도 될거 같구요.

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Scene/View/MainView.swift
> +        }
<img width="60%" alt="스크린샷 2022-07-12 오후 6 49 18" src="https://user-images.githubusercontent.com/30456206/178470886-37cbd7db-9312-4f5f-83b3-c2d80bb89174.png">

하이라키 확인해보면 
MainView > Horizontal StackView > 3개의 Vertical StackView > HeaderView, TableView 로 확인했는데요.
이렇게 Stack > Stack > TableView를 배치한 이유가 있을까요?

MainView > Horizontal StackView > 3개의 TableView로 대응할 수 있지 않을까요?

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Scene/View/TaskTableViewCell.swift
> +import SnapKit
어느 파일에서는 `SnapKit`을 import하고 어느 파일에서는 안하는데 기준이 있는걸까요?

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Scene/View/TaskTableViewCell.swift
> +    }
동일하게 `lazy`를 사용한 이유가 궁금합니다.

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Scene/View/TaskTableViewCell.swift
> +        }
taskType이 done이 아닐 경우에 날짜에 따라 `dateLabel`의 색상을 지정하는게 스펙으로 이해했는데요.
`guard`문을 이용하는 현재 코드로도 스펙을 구현하는데 문제 없을거 같습니다.
다만 `guard`문 [Swift 문서](https://docs.swift.org/swift-book/LanguageGuide/ControlFlow.html)를 확인해보면 
> If that condition isn’t met, the code inside the else branch is executed. That branch must transfer control to exit the code block in which the guard statement appears. It can do this with a control transfer statement such as return, break, continue, or throw, or it can call a function or method that doesn’t return, such as fatalError(_:file:line:).

이런 설명이 있습니다.
```swift
// 1
guard task.taskType != .doen  else { return }

// 2
if task.taskType != .done {
   if now > task.date { ... }
   else { ... }
}
```

위와 같은 방식이 좀 더 `guard`나 `if`의 의미에 맞지 않을까요?

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Utils/Then.swift
> +extension NSObject: Then {}
`Then` 라이브러리를 사용하지 않고 구현한 이유가 있을까요?

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Utils/TestData.swift
> +enum TestData {
사용하는 enum일까요?.?

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Utils/RealmManager.swift
> +    }
해당 메서드가 하나의 task를 fetch하는게 아니라 taskType에 해당하는 모든 task를 가져오는거 같은데요.
메서드 이름으로는 하나의 task를 가져올거 같아서 좀 더 역할이 잘 들어나는 네이밍은 어떨까요?

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Utils/RealmManager.swift
> +    func change(task: Task, taskType: TaskType) {
```suggestion
    func change(task: Task, targetTaskType: TaskType) {
```
이런 파라미터명은 어떤가요?

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Utils/RealmManager.swift
> +            print("업데이트를 실패하였습니다")
이런 에러 상황을 단순 프린트문 출력보다는 유저가 알 수 있도록 alert 활용해 보는건 어떨까요?

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Utils/Extension/UITextField+extension.swift
> +    }
extension으로 분리하는 기준이 있을까요?

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Utils/Extension/Double+extension.swift
> +    }
`Double`의 extension으로 정의되어 있으면 모든 Double 타입이 `formattedString`을 갖게될텐데요.
`formattedString`이 사실상 `DateFormatter`를 이용해 원하는 형식의 dateform으로 변환해주는 역할을 갖고 있는거 같습니다.
해당 역할이 모든 Double 타입이 갖는게 맞을까요?

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Scene/ViewModel/PopoverViewModel.swift
> +}
`Input`, `Output`이라는 네이밍이 어색한거 같습니다.
사용자의 인터랙션을 받아서 `Input`,
인터랙션의 결과물여서 `Output` 인걸까요?

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Scene/ViewModel/EditFormSheetViewModel.swift
> +    func editToTempModel(task: Task) {
`Temp`는 어떤 의미로 붙인걸까요?

2022-07-12 11:27 UTC, wonhee009 commented on ProjectManager/ProjectManager/Scene/ViewModel/MainViewModel.swift
> +    }
task를 지운 후 다시 `fetchData`를 호출하고 있는데요.
삭제 한 번 마다 todo, doing, done 모두를 realm에서 꺼내오고 테이블뷰를 다시 그리고 있는거 같습니다.
fetch하지 않고 해당 task array를 직접적으로 삭제하는 방법이나 해당 taskType만 fetch해오는건 어떤가요?

2022-07-14 01:39 UTC, westeastyear commented
- SPM Dependency들이 master 브랜치를 따라가도록 설정되어 있는데 의도한 부분인지 궁금합니다.
    - Master 브랜치를 따라간다면 어떤 문제가 있을까요?
    
>    → 계속 master 브랜치를 따라가게 되면, 소스가 업데이트가 되었을때 사용법이 변경되었다던지 하는 경우 저희의 소스 코드를 바꿔야 하는 상황이 발생할 수 있습니다. 현재 기준 최신버전으로 바꾸었습니다! 
    
- `RxGesture`는 `ReactiveX`에서 만들어진 라이브러리가 아닌 `RxSwiftCommunity`에서 만들어진 라이브러리인데 이를 사용한 이유가 있을까요?
    - 이런 라이브러리 사용할시 어떤 단점이 있을 수 있을까요?
    
>    → RxGesture을 사용한 이유는 좀더 간결한 코드 작성을 위함이었습니다. 당연히 ReactiveX에서 만든줄 알았는데 다른곳에서 만들었군요! 단점이라면 공식적으로 제공하는 라이브러리가 아니기 때문에 업데이트에 따라 기능의 제한이 생길 수가 있다고 생각합니다. 서로 다른 곳에서 만든 라이브러리이기 때문에 완벽하게 호환이 되지 않을수도 있다는 생각 또한 들었습니다. 
    
- 코드 확인했을때 아래와 같이 SwiftLint가 워닝을 뱉는데 수정이 필요한걸까요?
    
>    → 저희 Xcode에서는 위와 같은 워닝이 발생하지 않고 있습니다. 또 말씀하신 워닝을 검색하여 SwiftLint 홈페이지에서 확인한결과 아래의 이미지의 경우에만 트리거가 발생하는 것을 확인하였습니다!
<img src="https://user-images.githubusercontent.com/74251593/178868487-1cc69868-f7f9-4bba-89bd-9fc38ffb05fc.png" width="70%">

2022-07-14 01:54 UTC, westeastyear commented on ProjectManager/ProjectManager/Scene/View/TaskHeaderView.swift
> +    }
스택뷰를 만들때 위와같은 스타일로 주로 만드는 편인데요(취향?), 팀원과 이야기 해보니 결국 `var`이기 때문에 변경될 수 있다는 위험성을 가지고 있다는 의견을 주고 받았습니다. 
메소드로 추가해 주는 방식이 더 안전한 방식이라고 이해하면 좋을까요?

2022-07-14 02:41 UTC, westeastyear commented on ProjectManager/ProjectManager/Scene/View/MainView.swift
> +    private(set) lazy var doneTableView = generateTableView()
스크롤시 `headerView`를 고정시키는 UI를 원하였어서 이러한 방식으로 구현하였습니다.

2022-07-14 08:15 UTC, grumpy-sw commented on ProjectManager/ProjectManager/Scene/View/MainView.swift
> +    private(set) lazy var doneTableView = generateTableView()
```swift
final class TaskSectionView: UIView {
    private let taskType: TaskType
    private(set) lazy var taskHeaderView = TaskHeaderView(taskType: taskType)
    private(set) var taskTableView = UITableView().then {
        ...
    }
}
```
`UITableView`를 상속하는 대신 각 StackView에 해당하는 SectionView를 만들었습니다. 
원하는 대로 스크롤 시 헤더 뷰가 상단에 고정되고, 내부 프로퍼티인 `taskType` 덕분에 `MainViewController`에서 `bind()` 메서드의 코드 반복을 줄여주는 역할을 합니다.

2022-07-14 08:17 UTC, grumpy-sw commented on ProjectManager/ProjectManager/Scene/View/MainView.swift
> +        }
위에서 말씀드렸듯이 스크롤 시 headerView를 고정시키기 위해 위처럼 구조를 설정했습니다.
테이블 뷰의 헤더에 넣고 이것저것 해보았는데, 해결방법을 찾지 못하였어요 ㅠㅠ
결국 `UITableView`를 상속하는 대신 각 StackView에 해당하는 SectionView를 만들었습니다. 

```swift
final class TaskSectionView: UIView {
    private let taskType: TaskType
    private(set) lazy var taskHeaderView = TaskHeaderView(taskType: taskType)
    private(set) var taskTableView = UITableView().then {
        ...
    }
}
```

원하는 대로 스크롤 시 헤더 뷰가 상단에 고정되고, 내부 프로퍼티인 `taskType` 덕분에 `MainViewController`에서 `bind()` 메서드의 코드 반복을 줄여주는 역할을 합니다.

2022-07-14 08:19 UTC, westeastyear commented on ProjectManager/ProjectManager/Scene/View/TaskTableViewCell.swift
> +import SnapKit
따로 기준은 없고 `import`를 안해도 저절로 자동완성이 되어서 `import`하는 것을 잊었습니다. 현재 사용되는 곳에서 모두 `import SnapKit` 해주었습니다

2022-07-14 08:20 UTC, grumpy-sw commented on ProjectManager/ProjectManager/Utils/TestData.swift
> +enum TestData {
사용하지 않는 데이터입니다! 
원래는 기능구현이 끝나고 나서 디스크에 저장하고 불러오는 로직을 제거한 다음
요구사항의 초기 실행화면과 맞추기 위해 초기 데이터를 설정시키려고 남겨두었던 enum이었습니다.
삭제했습니다 :)

2022-07-14 08:23 UTC, westeastyear commented on ProjectManager/ProjectManager/Scene/View/TaskTableViewCell.swift
> +    }
프로퍼티를 만들때 `lazy var`로 만드는 습관이 있었어서 아무생각 없이 만들게 되었습니다. 현재 수정을 하면서 필요한 곳과 아닌 곳을 구별하여 수정해주었습니다.

2022-07-14 08:27 UTC, westeastyear commented on ProjectManager/ProjectManager/Utils/Then.swift
> +extension NSObject: Then {}
위의 고민한점 및 해결한 부분과 같습니다.
-> `Then`라이브러리를 그냥 가져다가 사용하지 않고 저희에게 필요한 기능을 가진 부분을 확인하여, 팀원과 한줄한줄 공부한다음 직접 구현하여 사용해 보았습니다.
다른 캠퍼가 이 기능을 사용하는것을 우연히 알게 되었고, `UI`프로퍼티 생성시 당연한 줄만 알았던 중복되는 부분을 제거할 수 있다는 점에 매료되어 이번 프로젝트에 적용해 보았습니다.

2022-07-14 08:27 UTC, grumpy-sw commented on ProjectManager/ProjectManager/Scene/View/TaskTableViewCell.swift
> +        }
1번 방법으로 수정했습니다.

2022-07-14 08:33 UTC, grumpy-sw commented on ProjectManager/ProjectManager/Utils/RealmManager.swift
> +    }
`func fetchTasks(type: TaskType) -> [Task]` 로 수정했습니다.

2022-07-14 08:34 UTC, grumpy-sw commented on ProjectManager/ProjectManager/Utils/RealmManager.swift
> +    func change(task: Task, taskType: TaskType) {
`func change(task: Task, targetType: TaskType)`로 수정했습니다. 앞에 task가 들어가서 뒤에는 굳이 없어도 의미가 전달될 것 같습니다.

2022-07-14 08:41 UTC, grumpy-sw commented on ProjectManager/ProjectManager/Scene/ViewModel/EditFormSheetViewModel.swift
> +    func editToTempModel(task: Task) {
리팩토링 과정 중 깜빡한 것 같습니다.
modifyEditableTask로 변경해주었습니다.
감사합니다!

2022-07-14 08:54 UTC, grumpy-sw commented on ProjectManager/ProjectManager/Utils/Extension/Double+extension.swift
> +    }
가장 먼저 시도한 방법은 인터프리터 역할을 하는 타입을 만들어 데이터의 형태를 변환해주는 것이었는데 cell마다 객체를 갖는 것이 오히려 자원 낭비일 것 같아 Double타입의 extension으로 구현하였습니다. 

현재는 TaskTableViewCell 내부의 메서드로 Double타입 데이터를 포맷에 맞게 String타입으로 변환하게 수정하였습니다!

2022-07-14 08:58 UTC, westeastyear commented on ProjectManager/ProjectManager/Utils/Extension/UITextField+extension.swift
> +    }
보통 새로운 기능이 필요할때 확장하여 사용하고 있습니다.

2022-07-14 08:59 UTC, grumpy-sw commented on ProjectManager/ProjectManager/Scene/ViewModel/PopoverViewModel.swift
> +}
네 그렇습니다. 코드를 쭉 살펴보니 View의 event(button tap, tableView item delete)와 View의 값(text, date 등)으로 나눌 수 있을 것 같은데 `~ViewModelEvent`, `~ViewModelState`라는 네이밍은 어떨까요?

2022-07-14 09:08 UTC, grumpy-sw commented on ProjectManager/ProjectManager/Scene/ViewModel/MainViewModel.swift
> +    }
데이터 sync의 안정성을 보장하기 위해 후자의 방법을 선택했습니다. taskType에 따라 해당 데이터만 fetch하도록 수정했습니다.

2022-07-14 13:25 UTC, grumpy-sw commented on ProjectManager/ProjectManager/Utils/RealmManager.swift
> +            print("업데이트를 실패하였습니다")
`DatabaseError`를 정의하여 `throw`된 경우 사용자에게 Alert을 띄우도록 처리하였습니다. 

![스크린샷 2022-07-14 오후 10 20 52](https://user-images.githubusercontent.com/63997044/178992183-7e7badf9-b608-429c-8c2a-873635f667e9.png)
`Realm`의 경우 추가, 삭제, 수정 등에서 에러가 발생한 경우 내부 처리 로직이 돌아가기 때문에 `do~catch`문으로 잡아낼 수가 없더라구요.. 그래서 직접 각 상황에 `throw`로 `DatabaseError`를 던져 테스트하였습니다 :)

궁금한 점이 있는데, 구독하고 있는 상황에서 에러 핸들링을 어떻게 해야하는지 몰라서 error라는 프로퍼티에 DatabaseError가 담긴 이벤트가 발생하면 뷰에서 Alert을 띄우도록 구현하였습니다. 이렇게 하니 에러를 핸들링한다기보다는 에러에 해당하는 이벤트를 처리한다는 느낌이 강하게 들더라구요 ㅠㅠ 이 부분을 좀 더 Reactive한 코드로 바꾸려면 어떻게 해야 할까요?
```swift
// ViewModel.swift
var error: PublishRelay<DatabaseError> = .init()
...
do {
...
} catch {
    self.error.accept(DatabaseError.createError)
}
```
```swift
// ViewController.swift
viewModel.error.asObservable()
    .subscribe(onNext: { error in
        self.showAlert(message: error.errorDescription)
    })
    .disposed(by: disposeBag)
```

2022-07-15 01:02 UTC, wonhee009 commented on ProjectManager/ProjectManager/Scene/View/TaskHeaderView.swift
> +    }
`var` 이라는게 결국은 변할 수 있다는 의미를 가지고 있어서 다른 개발자가 봤을때는 여기서 뭐가 바뀔 수 있구나라고 짐작할 수 있을거 같아요:)

2022-07-15 01:14 UTC, wonhee009 commented on ProjectManager/ProjectManager/Scene/View/MainView.swift
> +        }
제 기억으로는 헤더 뷰를 상단에 고정시킬 수 있는거로 아는데요.
[해당 블로그](https://velog.io/@minni/Custom-TableViewHeaderView-생성하기) 확인해 보셔도 좋을거 같습니다 :)

2022-07-15 01:24 UTC, wonhee009 commented on ProjectManager/ProjectManager/Utils/RealmManager.swift
> +            print("업데이트를 실패하였습니다")
[이런 식으로](https://okanghoon.medium.com/rxswift-5-error-handling-example-9f15176d11fc) rx에서도 에러를 처리하기 위한 메서드가 존재합니다. 
onError를 사용하기도 하구요.

2022-07-15 05:37 UTC, grumpy-sw commented on ProjectManager/ProjectManager/Scene/ViewModel/PopoverViewModel.swift
> +}
변경했습니다~!!

2022-07-15 05:48 UTC, westeastyear commented on ProjectManager/ProjectManager/Scene/View/MainView.swift
> +        }
블로그를 확인하여 저희가 놓친 부분을 확인하였는데 지금 구현해 놓은 것을 굳이 바꿀 필요는 없다고 팀원과 협의를 하였습니다.

2022-07-15 07:56 UTC, wonhee009 approved these changes

2022-07-15 07:56 UTC, merged