프로젝트 관리 앱 [STEP2-2] 사파리
yagom-academy/ios-project-manager pull request #141
Opened 2022-07-13 06:33 UTC by saafaaari

# 프로젝트 관리 앱 [STEP2-2]
@TTOzzi
안녕하세요 또치!
STEP2-2 PR 입니다. 잘 부탁드립니다.

## 구현 사항

### 추가및 수정 기능 구현
| 추가 | 수정 |
|-|-|
|<img src="https://i.imgur.com/0pKVqx9.gif" width="500">|<img src="https://i.imgur.com/Q4RyQbQ.gif" width="500">|
| 상단에 `UIBarButtonItem`를 클릭하면 item을 추가하기위한 View가 올라오고, Done 버튼을 클릭하면 새로운 todoitem이 생성 | Cell을 클릭후 상단에 Edit 버튼을 클릭하면, 쓰기 모드로 변경 컨텐츠를 변경후 Done 버튼을 클릭하면 todoitem이 수정 |

### 클린아키택쳐

![](https://i.imgur.com/swIh8hZ.png)

위 그림은 이번 프로젝트의 의존성 약도 입니다.

Scene의 필요한 의존성을 관리하는 `TodoSceneDIContainer`

Scene의 화면 전환을 담당하는 `TodoListFlowCoordinator`

두 타입을 두어 의존성과 화면 전환을 한 타입 내부에서 모두 처리하였고, Presentation, Domain, Data 레이어가 있고, Domain 레이어는 프로토콜을 이용하여 추상화 시켜 독립시켰습니다.

![](https://i.imgur.com/fFKMGX0.png)

위 그림과 같이 Presentation, Data는 Domain에만 의존할 수 있도록 하였습니다.

## 조언받고 싶은 부분

### 메모리 누수

클린아키택쳐를 사용하다 보니 작은 규모의 프로젝트임에도 다양한 타입이 생기고, 때문에 많은 의존이 생겼습니다. 이런 경우 또치는 메모리 누수 또는 RC를 확인하는 방법이 혹시 있으신가요?? 

### 중복코드

저번 PR때 또치가 언급해 주셔 이 부분에 대해서 이번 스텝에서 개선하려고 했지만, 손쉽게 방법을 찾지 못하였습니다... 내부 로직의 형태는 반복되지만, TableView가 모두 달라 어떤 방법으로 추상화를 해야 할지 감이 잘 오지 않았습니다. 어떤 방법으로 접근해야 할까요?

2022-07-13 06:40 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
> +            }.disposed(by: bag)
editButton을 tap 했을 때 쓰기 모드로 변경되면서 내부 콘텐츠를 변경할 수 있도록 하는 로직입니다. 따로 ViewModel 역할이 없이 구현하였는데 ViewModel의 역할일까요?

2022-07-13 06:42 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoEdit/ViewModel/TodoEditViewModel.swift
> +}
Actions 라는 타입을 만들어 이벤트는 ViewModel이 받지만, 처리는 Coordinator에서 해주도록 구현하였습니다.

2022-07-13 06:43 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoList/View/TodoListCell.swift
> +        deadlineLabel.text = item.deadlineAt
파라미터로 타입을 직접 받도록 수정하였습니다.

2022-07-13 06:43 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoList/View/TodoListHeaderView.swift
> +        return base.countLabel.rx.text
Reactive를 확장하는 방법으로 리팩하였습니다.

2022-07-13 06:48 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoList/View/TodoListViewController.swift
> +
`rx.modelSelected(TodoCellContent.self)`로 item을, `rx.itemSelected)`로 인덱스를 받아
item의 id를 이용하여 선택된 item(TodoCellContent)를 다시 TodoModel로 View에 보여질 수 있도록 하였고,
인덱스를 이용하여 `deselectRow` 해주었습니다.

2022-07-13 06:50 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoList/ViewModel/TodoListViewModel.swift
> +}
input에 대해선 메서드로 정의하였습니다.

2022-07-13 06:51 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoList/ViewModel/TodoListViewModel.swift
> +    }
연산프로퍼티로 수정하고, `toTodoCellContents ` 작업을 ViewModel에서 하도록 수정하였습니다.
연산프로퍼티로 사용한 이유는 init 내부에서 `self`로 접근할 수 있어 연산프로퍼티로 수정하였습니다.

2022-07-13 06:58 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/Utils/Extensions/Date+ToString.swift
> +        return dateFormatter.string(from: self)
toString를 사용한 이유는 좀더 가독성이 좋아보이지 않을까 해서 사용하였습니다.

2022-07-13 07:00 UTC, Siwon-L commented on ProjectManager/ProjectManager/Data/PersistentStorages/MemoryTodoListStorege.swift
> +    }
새로 들어온 data의 id가 이미 존재하면, 수정으로 간주하였고, 새로운 id가 들어오면 추가로 간주하였습니다.
근데 이 로직이 Storeged에 어울리지는 UseCase에 어울리는지 갈피가 잡히지 않습니다.ㅜㅜ

2022-07-14 13:52 UTC, TTOzzi requested changes
안녕하세요 사파리! 
DIContainer나 Coordinator 를 활용하신 부분은 정말 훌륭하네요 :thumbsup:

### 메모리 누수

>  클린아키택쳐를 사용하다 보니 작은 규모의 프로젝트임에도 다양한 타입이 생기고, 때문에 많은 의존이 생겼습니다. 이런 경우 또치는 메모리 누수 또는 RC를 확인하는 방법이 혹시 있으신가요??

Xcode의 `memory graph debugger` 나 `instruments`의 `leaks` 를 활용해서 찾을 수 있어요!
아직 한 번도 사용해보지 않으셨다면, 일부러 누수를 발생시키는 코드를 작성한 뒤 한 번 사용해보시면 좋을 것 같습니다 :slightly_smiling_face:

### 중복코드

> 저번 PR때 또치가 언급해 주셔 이 부분에 대해서 이번 스텝에서 개선하려고 했지만, 손쉽게 방법을 찾지 못하였습니다... 내부 로직의 형태는 반복되지만, TableView가 모두 달라 어떤 방법으로 추상화를 해야 할지 감이 잘 오지 않았습니다. 어떤 방법으로 접근해야 할까요?

음 추상화는 항상 공통 부분과 차이가 있는 부분을 구분한 뒤, 공통 부분은 묶고 차이가 있는 부분은 인자로 전달하는 흐름으로 진행되는데요.

현재 구현하신 뷰를 생성하는 로직에선 상단 `TodoListHeaderView`의 `title` 외엔 모두 공통으로 반복되고 있어, `tableStackView`, `doingStackView`, `doneStackView` 에 해당하는 뷰를 `title`을 인자로 받는 커스텀 클래스로 구현해줄 수 있을 것 같아요.

아니면 좀 더 작은 단위에서 생각하면, `TodoListView` 내부에서 테이블뷰를 만드는 로직을 함수로 빼서 `backgroundColor` 설정, 셀 `register` 등의 처리를 공통으로 해줄 수도 있을 것 같아요.
나머지 스택뷰도 마찬가지로 `arrangedSubviews`를 인자로 받는 함수를 만들어 활용할 수 있을 것 같구요 :thinking:

----

남겨드린 코멘트 중 이해하기 어려운 부분이 있다면 언제든지 말씀해주세요 🙇 
고생하셨습니다!

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Application/DIContainer/TodoSceneDIContainer.swift
> +    let storage = MemoryTodoListStorege()
의존성 주입 객체 나누신 것 정말 좋네요!
이렇게 의존성을 관리하는 객체를 나누면 어떤 이점을 얻을 수 있을까요? 👀 
(`storage`는 `private` 붙여줄 수 있을 것 같아요)

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Application/SceneDelegate.swift
> +    var todoListFlowCoordinator: TodoListFlowCoordinator?
여기 둘도 `private` 붙여줄 수 있을 것 같네요!

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/PersistentStorages/MemoryTodoListStorege.swift
> +protocol TodoListStorege {
`Storege` 오타 같아요 +_+

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/PersistentStorages/MemoryTodoListStorege.swift
> +    private var memoryStorege = BehaviorSubject<[TodoModel]>(value: TodoModel.makeDummy())
헉 `makeDummy`를 사용한 코드만 있어서 릴리즈 빌드는 컴파일 에러가 발생할 것 같아요 🤔 
이제 DIContainer 를 구현하셨으니, 테스트 환경 / 프로덕션 환경 코드 분리를 요렇게 분산해두지 않고 DIContainer 내부에 몰아넣어 관리하기 더 쉬운 구조로 구현할 수 있을 것 같습니다.
`TodoListStorege` 타입으로 추상화되어있으니 디버그 빌드일 땐 더미 데이터가 설정된 스토리지를, 릴리즈 빌드일 땐 비어있는 데이터가 설정된 스토리지를 주입해주도록요!

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/PersistentStorages/MemoryTodoListStorege.swift
> +    }
해당 로직이 메모리를 사용하는 스토리지(`MemoryTodoListStorege`)에만 한정된 로직일까요?
아니면 모든 스토리지에 해당되는 로직이라 다른 스토리지가 추가되면 같은 로직이 구현되어야 할까요?
전자라면 여기 두는 게 좋을 것 같고, 후자라면 스토리지 별 특화 로직이라기보단 구현하신 앱의 로직(도메인 레이어)이라고 봐야할 것 같아, 스토리지에선 CRUD 인터페이스만 노출하고 생성/수정 판단은 외부(UseCase)에서 해주는 게 좋을 것 같아요.

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Repositories/DefaultTodoListRepository.swift
> +final class DefaultTodoListRepository {
오호 `MemoryTodoListStorege`가 이름만 스토리지일 뿐 레포지토리의 역할이라 생각했는데, 별도로 Repository 가 존재하는군요 🤔 
그래서 현재 `DefaultTodoListRepository`가 맡은 역할이 없는 것 같습니다.
`MemoryTodoListStorege`가 데이터의 원천인 `memoryStorege`(정확히는 `BehaviorSubject`에 전달된 `[TodoModel]`)를 내부에 갖고 있으니, 이 계층은 없어도 되지 않을까요? 👀 
테스트가 가능하게끔 `MemoryTodoListStorege`가 생성자를 통해 데이터의 원천을 주입받도록만 구현해주면 Repository의 역할을 하고 있다고 봐도 무방할 것 같아요.

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Domain/UseCase/TodoListUseCase.swift
> +    func saveRepository(to data: TodoModel)
`UseCase`를 사용하는 외부에선 "`Repository`"에서 값을 읽어오고 저장하는지 까지는 알 필요 없지 않을까요?
메서드 이름에 `Repository`가 붙으면서 어떤 것을 읽고 저장하는지 이해하기 어려워진 것 같아요 🤔 
어떤 데이터를 읽어오고, 어떤 데이터를 저장하는지만 명확히 표현할 수 있으면 될 것 같습니다.
프로토콜 이름도 `UseCase`는 너무 일반적인 이름이니 어떤 동작을 수행하는 `UseCase`인지 알 수 있는 이름을 지어주면 좋을 것 같아요.

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditView.swift
> +    private let titleTaxtField: UITextField = {
`titleTaxtField` 오타인 것 같아요 +_+

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditView.swift
> +    }
흠 뷰에게 `id`와 `state` 를 넘겨주고, 뷰에선 그 값들과 자신이 표시하던 값들을 조합해서 데이터를 만들고 있는데요.
뷰는 사용자에게서 텍스트 입력 등의 이벤트를 받을 때 마다 뷰모델로 값을 넘겨주기만 하고, 요런 값을 조립하는 처리는 뷰모델에서 하는 게 나을 것 같아요 🤔 
뷰와 뷰모델을 바인딩해서 뷰에 값이 입력될 때 마다 뷰가 갖고 있는 데이터의 원천인 `TodoModel`을 업데이트해주고, `doneButton`이 눌렸을 땐 별도 처리 없이 뷰모델이 갖고있던 `TodoModel`을 저장할 수 있도록요.

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
> +        self.todoItme = item
`todoItme`이 따로 뷰에 존재해야 하는 이유가 있을까요? (`todoItme` 오타인 것 같아요 +_+)
뷰모델은 뷰에서 발생하는 이벤트를 받아 전달하는 역할도 하지만, 뷰가 표시할 데이터를 갖고 가공하는 역할도 합니다.
뷰모델이 `todoItme`을 내부에 갖고 있고, 뷰는 뷰모델을 통해서만 뷰를 그려주도록 해줘야 할 것 같아요.

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
> +        if todoItme == nil {
`todoItme == nil` 화면에 표시할 `todoItme`이 존재하는가? 도 뷰모델이 화면에 표시할 `todoItme`을 가지고 뷰에선 `isEditMode` 와 같은 가공된 Bool 값으로 전달받으면 더 좋을 것 같습니다.

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
> +        if todoItme != nil {
여기도 위 코멘트와 같아요!

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
> +                self.viewModel.doneButtonDidTap(item: newItem)
여기가 뷰쪽에 코멘트 남긴 대로, 이미 뷰모델에선 입력된 `TodoModel`의 정보를 알고 있는 상태로 아이템을 따로 뷰에서 넘길 필요 없이 self.viewModel.doneButtonDidTap() 형태가 될 것 같습니다.

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
> +                self.editButton.title == Constant.edit
뷰모델에서 지금이 편집 모드인지 여부를 상태값으로 구분하고 있다면, 뷰에서 요런 로직을 걷어낼 수 있을 것 같아요.

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
> +            }.disposed(by: bag)
넵 뷰에선 `editButton`이 탭 됐을 때, 로직 수행 없이 뷰모델로 "`editButton`이 눌렸어!" 만 전달해주고 뷰모델에선 이벤트를 받아 현재 상태(편집 모드 여부)를 보고 뷰에게 다시 변경할 상태를 전달하는 구조가 되어야 할 것 같아요.
로직을 뷰에 둬야 할지, 뷰모델에 둬야 할지 고민이 된다면 현재 구현된 코드가 테스트 코드를 작성할 수 있는 구조인가를 고민해보시면 좋을 것 같아요.

- `editButton`이 탭 액션 발생 -> 편집 모드가 아니라면? -> 편집 모드로 전환(뷰 편집 가능 / `editButton` 텍스트 변경)
- `editButton`이 탭 액션 발생 -> 이미 편집 모드라면? -> 편집 모드 비활성화(뷰 편집 비활성화 / `editButton` 텍스트 변경)

이 두 로직에 대해 뷰와 구분된 독립적인 테스트를 수행하려면 뷰모델에 로직이 있어야 할 거예요.

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/ViewModel/TodoEditViewModel.swift
> +}
뷰에서 발생할 수 있는 이벤트가 더 많지 않나요? 👀 
텍스트도 입력되는 곳이 두 곳이나 있고.. datePicker도 움직이고.. 수정 버튼도 클릭되고..
뷰에서 발생할 수 있는 모든 이벤트에 대해 input을 구현해야 하는 건 아니지만, 지금은 많이 간소화된 구조로 보입니다 🤔

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/ViewModel/TodoEditViewModel.swift
> +    private var actions: TodoEditViewModelActions?
뷰모델에 output이 없어서 뷰를 업데이트하기 위한 데이터가 따로 뷰컨에 존재했군요 🤔 
다른 예시 코드들에서 뷰를 업데이트해주기 위한 데이터를 뷰모델에서 어떻게 관리하고 있는지 찾아보고 적용해보시면 좋을 것 같습니다.

지금 구현된 input 만으로 설명 드리면.. 
기존 데이터에서 취소 버튼을 눌렀을 때(input) **수정이 일어난 상태에서만(뷰모델 로직 수행)** "저장하지 않고 취소하시겠습니까?" 라는 알러트를 띄워줘야(output) 한다던지, 완료 버튼을 눌렀을 때(input) **저장에 실패한 상황에서(뷰모델 로직 수행)** 에러 화면을 띄워줘야(output) 한다면 output 없이는 구현이 힘들거예요.

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/View/TodoListViewController.swift
> +
음! `itemSelected` 만 사용해서 `deselectRow`를 처리하고, 뷰모델은 화면에 보여지는 데이터 배열을 갖고 있으니 선택된 `index`를 뷰모델로 넘겨 뷰모델 내부에서 선택된 데이터를 찾아 로직을 수행할 수 있지 않을까요? 👀

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/ViewModel/TodoListViewModel.swift
> +protocol TodoListViewModelOutput {
이곳은 output도 존재하고, 화면도 뷰모델이 가진 데이터를 기반으로 그려지고 있네요.
편집 화면도 비슷한 구조로 처리해주면 좋을 것 같아요!

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/ViewModel/TodoListViewModel.swift
> +        }
`distinctUntilChanged`를 활용해 업데이트가 일어나지 않은 영역에 대해선 뷰를 업데이트 하지 않지만, 항상 `filter`로 모든 `TodoModel` 배열을 순회하는 로직은 동작할 것 같아요.
효율성에 대해 고민해볼 만한 포인트인 것 같습니다 🤔

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/ViewModel/TodoListViewModel.swift
> +        .distinctUntilChanged { $0 == $1 }
단순 이전값, 현재값을 그대로 비교하는 것이라면 `.distinctUntilChanged()`로 클로저 생략도 가능해요!

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/ViewModel/TodoListViewModel.swift
> +        }
음 반복되는 코드가 많은데 요 부분만 `state`를 인자로 받는 함수로 빼더라도 중복 코드를 많이 줄일 수 있을 것 같아요.

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/ViewModel/TodoListViewModel.swift
> +            TodoCellContent(entity: item, isPast: useCase.checkDeadline(time: item.deadlineAt))
`TodoModel` 데이터를 가져오는 로직과 `TodoModel`의 deadline을 계산하는 로직은 성격이 조금 다른 것 같으니 `UseCase`도 나눠주면 더 좋을 것 같아요 🤔

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/ViewModel/TodoListViewModel.swift
> +}
별도 파일로 나눠줘도 될 것 같아요!

2022-07-14 13:52 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/ViewModel/TodoListViewModel.swift
> +    }()
각각의 `TodoCellContent`가 개별로 `dateFormatter`를 가지면, 결국은 표시할 셀의 개수만큼 `DateFormatter`가 생성될 것 같아요 🤔 
`checkDeadline`과 같이 날짜 형식 변환을 해줄 UseCase를 분리해서 외부에서 변환해서 주입해주거나, 하나의 `dateFormatter`를 만들고 주입해주는 방식으로 불필요한 생성을 막아주면 더 좋을 것 같아요.

2022-07-15 05:25 UTC, saafaaari commented on ProjectManager/ProjectManager/Domain/UseCase/TodoListUseCase.swift
> +    func saveRepository(to data: TodoModel)
`Repository` 네이밍을 삭제하고 item이라고 수정하였고, 프로토콜 이름을 `TodoListUseCase` class 이름을 `DefaultTodoListUseCase`로 수정하였습니다.

2022-07-15 07:09 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditView.swift
> +    }
넵 또치에 말대로 원천 데이터를 뷰모델이 관리하고, 바인딩으로 입력이 들어오면 원천 데이터를 변경해 바로 저장하도록 수정하였습니다.

2022-07-15 07:11 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
> +        self.todoItme = item
```swift
final class DefaultTodoEditViewModel: TodoEditViewModel {
  private var item: TodoModel?

  var setUpView: Observable<TodoModel?> {
      guard let item = item else {
          item = TodoModel(title: nil, body: nil, deadlineAt: Date())
          return Observable.just(nil)
      }
      
      return Observable.just(item)
  }
}
```
위처럼 수정하였습니다.

2022-07-15 07:12 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
> +        if todoItme == nil {
또치에 말씀대로 Bool값을 통해 뷰를 세팅해주었습니다.

2022-07-15 07:13 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
> +                self.viewModel.doneButtonDidTap(item: newItem)
넵 doneButtonDidTap 메서드의 파라미터를 삭제하였습니다.

2022-07-15 07:22 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoEdit/ViewModel/TodoEditViewModel.swift
> +}
넵 또치 말씀대로 titleLable, datePicker, textView에 대응되는 input도 추가되었습니다.

2022-07-15 07:28 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoEdit/ViewModel/TodoEditViewModel.swift
> +    private var actions: TodoEditViewModelActions?
넵 output구조를 추가하였고, 또치가 말씀해주신 얼럿 부분은 다음 스텝이서 적용해보도록 하겠습니다.

2022-07-15 08:02 UTC, saafaaari commented on ProjectManager/ProjectManager/Application/DIContainer/TodoSceneDIContainer.swift
> +    let storage = MemoryTodoListStorege()
`DIContainer`와 같이 의존성을 관리하는 객체가 있으면, 한곳에서 각 타입에 필요한 의존성을 관리해 줄 수 있기 때문에 UseCase같이 여러 타입에 사용되는 인스턴스를 한곳에서 처리해 줄 수 있습니다. 또한 상단에서 부터 의존성을 내부로 주입해 줄 수 있어 타입간 의존성도 떨어트릴 수 있을 것 같습니다. 또한 외부에서 의존성을 주입받는 형태를 가지면, 테스트에도 용의하다고 알고 있습니다.

2022-07-15 08:03 UTC, saafaaari commented on ProjectManager/ProjectManager/Data/PersistentStorages/MemoryTodoListStorege.swift
> +protocol TodoListStorege {
넵 이부분은 다음 스텝이 꼭 수정하겠습니다. 
git Rebase 후에 파일 네이밍을 수정하도록 하겠습니다.

2022-07-15 08:06 UTC, Siwon-L commented on ProjectManager/ProjectManager/Data/Repositories/DefaultTodoListRepository.swift
> +final class DefaultTodoListRepository {
넵 또치 말씀이 맞습니다. 현제 `Repository`는 아무 역할이 없지만, 다음 스텝에서 파이어베이스를 사용하게 된다면, 그땐 "역할이 생기지 않을까?" 생각해서 그런데 그때도 역할이 없다고 생각된다면 삭제하도록 하겠습니다.

2022-07-15 14:16 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoList/ViewModel/TodoListViewModel.swift
> +            TodoCellContent(entity: item, isPast: useCase.checkDeadline(time: item.deadlineAt))
한 뷰모델이 여러개의 UseCase를 가지기도 하나요??

2022-07-17 11:12 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditView.swift
> +    }
요거 굳이 `Observable`로 변환해줄 필요 없이 `ControlProperty` 타입 그대로 반환해도 될 것 같아요.

2022-07-17 11:13 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
> +    private func configureLeftBarButtonItem(createMode: Bool) {
사소하지만 Bool 타입이니 앞에 is 정도는 붙여주면 더 좋을 것 같아요.

2022-07-17 11:15 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
> +        viewModel.isItemNil
요기 output도 뷰에게 명령을 내리는 관점에서 `isItemNil` 보단 "생성 모드로 변경해줘!" 같은 네이밍이면 더 좋을 것 같아요.

2022-07-17 11:17 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/ViewModel/TodoEditViewModel.swift
> +            item = TodoModel(title: nil, body: nil, deadlineAt: Date())
item 이 없을 때 기본값 item으로 처리하는 건 생성자 내부에서 해주고, 여기는 그대로 뷰모델이 가진 item을 넘겨주도록 구현하는 게 더 깔끔할 것 같아요 🤔

2022-07-17 11:20 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
>                  self?.editButton.title = $0 ? Constant.eidting : Constant.edit
요기도 뷰모델의 input을 호출하고 뷰 업데이트는 output을 통해서 하도록 변경하면 좋을 것 같아요.
이제 편집 모드 여부를 관리하는 `isItemNil` output이 생겼으니까요 🤔

2022-07-17 11:22 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/ViewModel/TodoEditViewModel.swift
> +        }
음 output을 한번 더 엮어줘서 output으로 내보내기보단, 뷰모델이 가진 상태값을 기반으로 값을 방출하도록 구현하는 게 더 좋을 것 같아요.
지금은 뷰모델 내에서 현재 뷰가 편집 모드인지 알기 어려워 보이네요 🤔

2022-07-17 11:23 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/View/TodoListView.swift
> +    let todo = TodoListTableView(title: "TODO")
오- 중복 코드가 많이 줄었네요!
사소하지만 이름은 `todo` 보단 뷰임을 명확하게 알 수 있도록 지어주는 게 좋습니다.

2022-07-17 11:24 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/View/TodoListViewController.swift
> +            .bind(to: mainView.todo.tableView.rx.items(cellIdentifier: TodoListCell.identifier,
요런것도 Reactive extension을 잘 활용하면 좀 더 깔끔하게 처리할 수 있을 것 같아요!

2022-07-17 11:25 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/ViewModel/TodoEditViewModel.swift
>          }
아! PR 이후 수정된 부분은 커밋 단위로 보다보니 여기서 로직이 또 바꼈군요.
옵셔널 언래핑 없이 그냥 바로 넘겨줘도 될 것 같네요.

2022-07-17 11:28 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/ViewModel/TodoEditViewModel.swift
> +    }
앞선 커밋에서도 코멘트 남겨뒀듯이 이 로직을 각각의 input 메서드에서 예외처리처럼 실행하기보단, 생성 시점에 수행해주면 좋을 것 같아요.

2022-07-17 11:31 UTC, TTOzzi approved these changes
고생하셨습니다! 전체적으로 중복 코드도 많이 줄었고, Input / output 구조도 어느정도 정리된 것 같네요.
추가로 코멘트 남겨드렸는데, 이해 안되는 부분 있으면 편하게 말씀해주세요 🙇‍♂️

2022-07-17 11:31 UTC, merged

2022-07-18 05:16 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditView.swift
> +    }
또치 말씀대로 `ControlProperty ` 그대로 반환하도록 수정하였습니다.

2022-07-18 05:51 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoEdit/ViewModel/TodoEditViewModel.swift
> +        }
https://github.com/saafaaari/ios-project-manager/commit/cf5cf43d05adbe7d57de989fbbc247f69fa651b5

위와 같이 수정해 보았습니다. 또치가 조언해주신 방향에 맞게 수정한지 모르겠네요..ㅎㅎ

2022-07-18 05:55 UTC, saafaaari commented on ProjectManager/ProjectManager/Presentation/TodoEdit/ViewModel/TodoEditViewModel.swift
> +        }
추가적으로 제가 설명이 부족한 부분이 있었던것 같습니다. 위 코드는 편집모드에 대한 Bool 값이라기 보단 navigationItem의 leftBarButtonItem에 cancel 또는 edit 버튼을 구분해주는 Bool 값입니다.