프로젝트 관리 앱 [STEP2] Tiana, mmim
yagom-academy/ios-project-manager pull request #142
Opened 2022-07-13 08:56 UTC by JoSH0318

## UML
![](https://i.imgur.com/F3hTyj2.png)

## 질문사항
### 1️⃣ viewModel 구조
viewController는 view 역할을 하기 때문에 데이터 가공은 viewModel에서 처리하려고 합니다. 아래 코드처럼 각각의 저장프로퍼티를 사용해서 구현했는데요. RxSwift를 사용했을 때 일반적으로 많이 사용되는 viewModel 구조가 궁금합니다!🤔

<img width="500" src="https://i.imgur.com/ccDbzDZ.jpg"/>

아래 코드처럼 Input, Output 타입을 활용한 구조도 많이 사용하는 것 같습니다. 아래 구조를 활용하면 Input는 tableView tap 이벤트 같은 것이 들어가는 것이 맞을지 궁금합니다.
```swift
class ViewModel {
    struct Input {
        // viewController에서 받아올 이벤트를 담을 타입
    }
    
    struct Output {
        // ViewModel에서 가공한 결과를 담아서 viewController에 전달될 타입
    }
    
    func transform(input: Input) -> Output {
        return Output()
    }
}
```

### 2️⃣ 키보드와 레이아웃
보통 키보드 때문에 textView나 textField가 가릴 때, scrollView의 bottomConstraint, contentInset.bottom, contentOffset.y 등을 keyboardHeight를 이용해 조정해줬습니다.

> 1. scrollView의 bottomConstraint.constant = -keyboardHeight
> 2. scrollView.contentInset.bottom = keyboardHeight
> 3. scrollView.contentOffset.y += keyboardHeight

하지만 iPad의 Modal의 경우 modal의 bottom이 떨어져있고, 기기마다 그 떨어져있는 bottom값이 다릅니다.
따라서 단순히 keyboardHeight만큼 layout값을 조정해주는 것이 어려웠습니다.
<img width="400" src="https://i.imgur.com/Yxb5GRZ.jpg"/>
<img width="400" src="https://i.imgur.com/4VWgfYs.jpg"/>

iPad의 경우, 어떠한 방법으로 키보드가 가리는 문제를 해결할 수 있을지 궁금합니다.

### 3️⃣ enum의 위치
현재 project의 todo, doing, done 상태를 표현하기 위해서 **enum ProjectStatus**를 구현했습니다. 
이 enum의 위치가 적절한지, 어떠한 위치에 있어야하는 지 궁금합니다.

### 4️⃣ MockStorageManager
현 step에서는 데이터를 DB에 저장하지 않습니다. 그렇지만 이후의 코드 수정을 최소화 하기 위해 프로토콜을(`Storagable`) 활용해서 외부 로직과 분리 시켰습니다.

```swift
protocol Storagable {
    func create(projectContents: [ProjectContent])
    func read() -> BehaviorRelay<[ProjectContent]>
    func read(id: UUID?) -> ProjectContent?
    func update(projectContent: ProjectContent)
    func delete(projectContentID: UUID?)
}
```

ProjectUseCase 타입이 인터페이스 입니다.
위 프로토콜을 채택하는 타입(ex. MockStorageManager)으로 ProjectRepository의 storageManager 프로퍼티 초기화만 시키면 Presentation 영역은 수정할 필요없습니다.

### 5️⃣ Clean Architecture
⭐️ 각 그룹의 역할
- Data
    - data soruce: 로컬, 원격에서의 데이터를 담당하는 영역
    - repository(`MockStorageManager`): data soruce의 데이터를 조정하는 책임
- Domain
    - entity(`ProjectContent`): 프로젝트에 사용되는 비지니스 모델. 
    - repository(`ProjectRepository`): Persistence 인터페이스, 프로젝트 내에서 저장소에 CRUD하기 위한 인터페이스를 제공
    - use case(`ProjectUseCase`): Presentaion layer에서 Domain layer로 접근할 수 있는 인터페이스를 제공
- Presentation
    - view: app 이벤트를 처리하고 화면에 보여주는 책임
    - view model: view를 위한 비지니스 로직 구현의 책임

위처럼 layer별로 역할과 책임을 정의해봤고, 그에 따라서 구현했습니다.
저희가 프로젝트에 적용한 Clean Architecture가 제대로 역할 분리가 되었는지 궁금합니다.

### 6️⃣ MVVM
<img src="https://i.imgur.com/DI9yu32.png" height="200">

저희가 만든 Model, View, ViewModel이 제대로 역할 분리가 되었는지 궁금합니다.

* Model: UI에 보여줄 데이터가 존재합니다. UI에서 받은 이벤트로 데이터의 수정이 필요할 때 실제 데이터가 수정 작업을 진행합니다.
* View: 사용자의 이벤트를 받고, 보여줄 UI를 구현합니다.
* ViewModel: Model과 View의 가교로서 View는 ViewModel을 통해 Model에 접근합니다. View에 나타내기 위한 데이터를 가공합니다.

#### VC vs View vs ViewModel vs Model
MVVM에서는 ViewController도 View의 역할로 본다고 이해했습니다. 그렇지만 그 둘에 차이가 있다고 생각합니다. 저희가 구현한 View 타입들에서는(ex.` MainView`, `ProjectCell`) UI 보여주는 기능만 구현하고, 비동기 로직은 VC(ex. `MainViewController`, `PopOverViewController`)에서 구현하도록 했습니다. 이로 인해, View 타입의 프로퍼티(ex. `tableView`, `countLabel`) 은닉화가 어렵습니다.
VC는 View 타입과 VM을 프로퍼티로 가집니다.
ViewModel(ex. `MainViewModel`, `RegistrationViewModel`)에서만 Model(ex. `ProjectUseCase`)에 접근할 수 있습니다.

### 7️⃣ UI 입체적으로 보이는 방법
* 목표
기능 요구서에서 제시한 UI처럼 입체적으로 TextField와 TextView를 그리고 싶었습니다.
구현 시 공부해야 하는 키워드에 대해 조언을 받을 수 있을까요😢
<img src="https://i.imgur.com/taCavbp.png" height="300">

* shadow 주기
쉐도우를 통해 그리려고 했지만 아래처럼 의도와 다르게 그려집니다.
또, textField와 textView에 동일한 두께를 줘도 다른 두께로 보입니다.
<img src="https://i.imgur.com/yZAsutR.png" height="400">

```swift
private func drawShadow(view: UIView, borderWidth: CGFloat = 1, color: UIColor) {
    view.layer.borderWidth = borderWidth
    view.layer.borderColor = color.cgColor
    view.layer.shadowOpacity = 1
    view.layer.shadowColor = color.cgColor
    view.layer.shadowOffset = CGSize(width: 1, height: 1)
}
```
* 테두리 선만 주기
현재는 평면적으로 보이도록 구현했습니다.
<img src = "https://i.imgur.com/ysANPQL.png" height="400">

```swift
private func drawBorder(view: UIView, borderWidth: CGFloat = 2, color: UIColor) {
    view.layer.borderWidth = borderWidth
    view.layer.cornerRadius = 5.0
    view.layer.borderColor = color.cgColor
}
```

2022-07-15 07:55 UTC, SungPyo commented
티아나 밈 안녕하세요?

Step2 고생하셨고 질문에 대한 부분들 먼저 답변 드립니다.

> @SungPyo 안녕하세요! 웨더🌤! 잘부탁드립니다!
> 
> ## UML
> ![](https://camo.githubusercontent.com/8cf9a43c7596d1df012b4bc686d2db9723af5bb70b55a27099a151caee6f899d/68747470733a2f2f692e696d6775722e636f6d2f46336854796a322e706e67)
ㄴ `UML 만큼은 기똥차네요 👏`
> 
> ## 질문사항
> ### 1️⃣ viewModel 구조
> viewController는 view 역할을 하기 때문에 데이터 가공은 viewModel에서 처리하려고 합니다. 아래 코드처럼 각각의 저장프로퍼티를 사용해서 구현했는데요. RxSwift를 사용했을 때 일반적으로 많이 사용되는 viewModel 구조가 궁금합니다!🤔
ㄴ `일반적으로 많이 사용되는 구조 라는것은 알 수 없습니다. 제가 함부로 답변할 수 없어요! 회사마다 다르고 현업에 계신분들마다 다 다르기때문에 어떤 방법이 가장 많이 사용한다! 라고 볼 수 없습니다.`
> 
> <img alt="" width="500" src="https://camo.githubusercontent.com/a15fe8ca1bfadcc4242ae16a9863f9e82cd58d870214de81c702be5af4e5db08/68747470733a2f2f692e696d6775722e636f6d2f636344627a445a2e6a7067">
> 
> 아래 코드처럼 Input, Output 타입을 활용한 구조도 많이 사용하는 것 같습니다. 아래 구조를 활용하면 Input는 tableView tap 이벤트 같은 것이 들어가는 것이 맞을지 궁금합니다.
ㄴ`네 맞습니다. (저의 주관적 기준)`
> 
> ```swift
> class ViewModel {
>     struct Input {
>         // viewController에서 받아올 이벤트를 담을 타입
>     }
>     
>     struct Output {
>         // ViewModel에서 가공한 결과를 담아서 viewController에 전달될 타입
>     }
>     
>     func transform(input: Input) -> Output {
>         return Output()
>     }
> }
> ```
> 
> ### 2️⃣ 키보드와 레이아웃
> 보통 키보드 때문에 textView나 textField가 가릴 때, scrollView의 bottomConstraint, contentInset.bottom, contentOffset.y 등을 keyboardHeight를 이용해 조정해줬습니다.
> 
> > 1. scrollView의 bottomConstraint.constant = -keyboardHeight
> > 2. scrollView.contentInset.bottom = keyboardHeight
> > 3. scrollView.contentOffset.y += keyboardHeight
> 
> 하지만 iPad의 Modal의 경우 modal의 bottom이 떨어져있고, 기기마다 그 떨어져있는 bottom값이 다릅니다. 따라서 단순히 keyboardHeight만큼 layout값을 조정해주는 것이 어려웠습니다. <img alt="" width="400" src="https://camo.githubusercontent.com/8c8757b19e891a1762a8d59088afddfe06ebdf31ad63b7a69182d2f4d97b9fde/68747470733a2f2f692e696d6775722e636f6d2f5978623547525a2e6a7067"> <img alt="" width="400" src="https://camo.githubusercontent.com/fa8bc8252cc43f580ccbb10ef0518cb42f0167f1f5ab0c7523e12c9b240b180f/68747470733a2f2f692e696d6775722e636f6d2f345657676659732e6a7067">
> 
> iPad의 경우, 어떠한 방법으로 키보드가 가리는 문제를 해결할 수 있을지 궁금합니다.
ㄴ `하단과 떨어진 높이가 동적이라면, 동적으로 계산하는 방법 외에는 없다고 생각됩니다. 지금의 경우는 텍스트 수정시 날짜 수정이 불가한 이슈가 있네요. (12.9Inch 기준)`
> 
> ### 3️⃣ enum의 위치
> 현재 project의 todo, doing, done 상태를 표현하기 위해서 **enum ProjectStatus**를 구현했습니다. 이 enum의 위치가 적절한지, 어떠한 위치에 있어야하는 지 궁금합니다.
ㄴ `위치는 정하기 나름이긴 하지만.. 제 기준으로는 별도의 Enum파일을 만들어서 관리하는건 어떨지 의견을 내고 싶네요.`
> 
> ### 4️⃣ MockStorageManager
> 현 step에서는 데이터를 DB에 저장하지 않습니다. 그렇지만 이후의 코드 수정을 최소화 하기 위해 프로토콜을(`Storagable`) 활용해서 외부 로직과 분리 시켰습니다.
> 
> ```swift
> protocol Storagable {
>     func create(projectContents: [ProjectContent])
>     func read() -> BehaviorRelay<[ProjectContent]>
>     func read(id: UUID?) -> ProjectContent?
>     func update(projectContent: ProjectContent)
>     func delete(projectContentID: UUID?)
> }
> ```
> 
> ProjectUseCase 타입이 인터페이스 입니다. 위 프로토콜을 채택하는 타입(ex. MockStorageManager)으로 ProjectRepository의 storageManager 프로퍼티 초기화만 시키면 Presentation 영역은 수정할 필요없습니다.
ㄴ`음... 이건 질문이 뭔지 모르겠네요?`
> 
> ### 5️⃣ Clean Architecture
> ⭐️ 각 그룹의 역할
> 
> * Data
>   
>   * data soruce: 로컬, 원격에서의 데이터를 담당하는 영역
>   * repository(`MockStorageManager`): data soruce의 데이터를 조정하는 책임
> * Domain
>   
>   * entity(`ProjectContent`): 프로젝트에 사용되는 비지니스 모델.
>   * repository(`ProjectRepository`): Persistence 인터페이스, 프로젝트 내에서 저장소에 CRUD하기 위한 인터페이스를 제공
>   * use case(`ProjectUseCase`): Presentaion layer에서 Domain layer로 접근할 수 있는 인터페이스를 제공
> * Presentation
>   
>   * view: app 이벤트를 처리하고 화면에 보여주는 책임
>   * view model: view를 위한 비지니스 로직 구현의 책임
> 
> 위처럼 layer별로 역할과 책임을 정의해봤고, 그에 따라서 구현했습니다. 저희가 프로젝트에 적용한 Clean Architecture가 제대로 역할 분리가 되었는지 궁금합니다.
ㄴ `저의 주관적 의견으로는 역할 분리는 제대로 되었다고 생각되나 역할에 따른 동작이 제대로 되었다고 보기에는 어렵습니다. 각 코드들에 코멘트 남겨놓을테니 참고부탁드려요.`
> 
> ### 6️⃣ MVVM
> <img alt="" height="200" src="https://camo.githubusercontent.com/e87291ef2a9e6c8c695af28f465076e5629afff4640436796fafa7366b7bc6b6/68747470733a2f2f692e696d6775722e636f6d2f444939797533322e706e67">
> 
> 저희가 만든 Model, View, ViewModel이 제대로 역할 분리가 되었는지 궁금합니다.
> 
> * Model: UI에 보여줄 데이터가 존재합니다. UI에서 받은 이벤트로 데이터의 수정이 필요할 때 실제 데이터가 수정 작업을 진행합니다.
> * View: 사용자의 이벤트를 받고, 보여줄 UI를 구현합니다.
> * ViewModel: Model과 View의 가교로서 View는 ViewModel을 통해 Model에 접근합니다. View에 나타내기 위한 데이터를 가공합니다.
> 
> #### VC vs View vs ViewModel vs Model
> MVVM에서는 ViewController도 View의 역할로 본다고 이해했습니다. 그렇지만 그 둘에 차이가 있다고 생각합니다. 저희가 구현한 View 타입들에서는(ex.` MainView`, `ProjectCell`) UI 보여주는 기능만 구현하고, 비동기 로직은 VC(ex. `MainViewController`, `PopOverViewController`)에서 구현하도록 했습니다. 이로 인해, View 타입의 프로퍼티(ex. `tableView`, `countLabel`) 은닉화가 어렵습니다. VC는 View 타입과 VM을 프로퍼티로 가집니다. ViewModel(ex. `MainViewModel`, `RegistrationViewModel`)에서만 Model(ex. `ProjectUseCase`)에 접근할 수 있습니다.
ㄴ `6번 답변과 동일합니다.`
> 
> ### 7️⃣ UI 입체적으로 보이는 방법
> * 목표
>   기능 요구서에서 제시한 UI처럼 입체적으로 TextField와 TextView를 그리고 싶었습니다.
>   구현 시 공부해야 하는 키워드에 대해 조언을 받을 수 있을까요😢
ㄴ `아래 시도하신 방법들 보면 맞는 방법이 맞습니다. 다만 모서리 부분만 쉐도우를 줄 수 있도록 할 수 있으니, 각 메서드들을 살펴보심이 어떨까 싶어요.`
> 
> <img alt="" height="300" src="https://camo.githubusercontent.com/2c1eed90aa3d0a9d5071c5183b67d25fb5f5dbfe2505bcba441ae6dcbb7d7cfc/68747470733a2f2f692e696d6775722e636f6d2f746143617662702e706e67">
> 
> * shadow 주기
>   쉐도우를 통해 그리려고 했지만 아래처럼 의도와 다르게 그려집니다.
>   또, textField와 textView에 동일한 두께를 줘도 다른 두께로 보입니다.
> 
> <img alt="" height="400" src="https://camo.githubusercontent.com/7a3ee5dd03ecbf54059e27892d6a05c3cce732b88d9632e2f26c3bbc6c23267d/68747470733a2f2f692e696d6775722e636f6d2f795a41737574522e706e67">
> 
> ```swift
> private func drawShadow(view: UIView, borderWidth: CGFloat = 1, color: UIColor) {
>     view.layer.borderWidth = borderWidth
>     view.layer.borderColor = color.cgColor
>     view.layer.shadowOpacity = 1
>     view.layer.shadowColor = color.cgColor
>     view.layer.shadowOffset = CGSize(width: 1, height: 1)
> }
> ```
> 
> * 테두리 선만 주기
>   현재는 평면적으로 보이도록 구현했습니다.
> 
> <img alt="" height="400" src="https://camo.githubusercontent.com/3bce1706a2784a9fd70a08e3851e15fc95407a219d44254e2de49ea21442c863/68747470733a2f2f692e696d6775722e636f6d2f7973414e50514c2e706e67">
> 
> ```swift
> private func drawBorder(view: UIView, borderWidth: CGFloat = 2, color: UIColor) {
>     view.layer.borderWidth = borderWidth
>     view.layer.cornerRadius = 5.0
>     view.layer.borderColor = color.cgColor
> }
> ```

나머지 부분들은 코드별 코멘트 참고해주시고, 전체적으로 부족한 부분들이 조금씩 보입니다!

다음 프로젝트(step3 or 프로젝트 관리 앱 II) 를 진행하시면서 수정하셔도 되고, Step2에서 완전히 수정 후 넘어가셔도 됩니다.

해당 부분은 편하신대로 결정하시면 됩니다!

2022-07-15 07:57 UTC, SungPyo commented on ProjectManager/ProjectManager/Domain/Entity/ProjectContent.swift
> +    static func convert(_ titleText: String?) -> ProjectStatus? {
// String으로 ProjectStatus를 만드는 다른 방법이 있는데, 혹시 알고 계신가요?

2022-07-15 07:58 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/PopOver/View/PopOverViewController.swift
> +        let firstButton = popOverView.firstButton
control Event 에 대해 공부해 보시는걸 추천합니다.

2022-07-15 07:58 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/PopOver/View/PopOverViewController.swift
> +                guard let status = ProjectStatus.convert(firstButton.titleLabel?.text) else {
// 이런 방식도 가능하지만 guard문 없이 완전한 ProjectStatus 를 받는 방법이 있을까요?

2022-07-15 07:58 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +
MainViewController에서 할 수 있음에도 분리한 이유가 무엇인가요? 알 수 있을까요?

2022-07-15 07:59 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +    private func setUpSelection() {
이거 세개 묶어서 한번에 처리 할 수 있는 방법을 고민 해 보셨을까요?

2022-07-15 07:59 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +    private func setUpTableCellData() {
기존에 bind라는 함수가 있어서 오버로딩 느낌이 나는데, 다른 좋은 이름이 있었으면 좋겠다는 생각을 해봅니다.

2022-07-15 07:59 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +        bind(projects: viewModel.doneProjects, tableView: mainView.doneTable.tableView)
기존에 bind라는 함수가 있어서 오버로딩 느낌이 나는데, 다른 좋은 이름이 있었으면 좋겠다는 생각을 해봅니다.

2022-07-15 08:00 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +    private func bind(projects: Driver<[ProjectContent]>, tableView: UITableView) {
1. Driver로 하신 이유는?!
2. Driver말고 다른 방법도 있는지?

2022-07-15 08:00 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +    private func deleteProject() {
얘들은 각각 테이블뷰가 변수로 빠져있네요? 안 빠진 애들도 있던데.. 특별한 이유가 있었나요?

2022-07-15 08:00 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +            .drive { [weak self] indexPath in
drive가 그냥 {} 로 되어있는데, 옵션이 어떤것들이 있는지 알 고 있을까요? 옵션을 주지 않고 그대로 사용했을때의 문제점이 있을까요?

2022-07-15 08:01 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +            .map { "\($0.count)" }
문제: map대신 flatMap을 사용해 보시오! flatMap을 사용하려면 어떻게 해야할까요?!

2022-07-15 08:01 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +    private func bindGesture(to tableView: UITableView, status: ProjectStatus) {
👏👏👏

2022-07-15 08:01 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +                    return
어차피 종료시킬거면 guard로 묶어도 될텐데 if를 쓰신 이유는?

2022-07-15 08:01 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/ProjectCell.swift
> +    var contentID: UUID?
var가 최우선인가요?

2022-07-15 08:02 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/ProjectListView.swift
> +    lazy var countLabel: UILabel = {
lazy var 쓰신 이유가 있어요? 그냥 let으로 하면 안되나요?

2022-07-15 08:02 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/ViewModel/MainViewModel.swift
> +struct MainViewModel {
뷰모델은 접근제한자가 굉장히 중요하다고 생각하는데 다 없네요..? 이유가 무엇인가요?
ViewModel에 대한 전체적인 리팩토링이 필요해 보입니다. ex) 뷰모델의 비즈니스로직 직접접근 및 변경 가능, View에 대한 직접적인 처리 등..

2022-07-15 08:02 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/ViewModel/MainViewModel.swift
> +        return ProjectUseCase().repository.read()
useCase를 건너 repository를 바로 접근하네요? 이유가 있을까요?

2022-07-15 08:03 UTC, SungPyo requested changes
티아나 밈 안녕하세요?

Step2 고생하셨고 질문에 대한 부분들 먼저 답변 드립니다.

> @SungPyo 안녕하세요! 웨더🌤! 잘부탁드립니다!
> 
> ## UML
> ![](https://camo.githubusercontent.com/8cf9a43c7596d1df012b4bc686d2db9723af5bb70b55a27099a151caee6f899d/68747470733a2f2f692e696d6775722e636f6d2f46336854796a322e706e67)
ㄴ `UML 만큼은 기똥차네요 👏`
> 
> ## 질문사항
> ### 1️⃣ viewModel 구조
> viewController는 view 역할을 하기 때문에 데이터 가공은 viewModel에서 처리하려고 합니다. 아래 코드처럼 각각의 저장프로퍼티를 사용해서 구현했는데요. RxSwift를 사용했을 때 일반적으로 많이 사용되는 viewModel 구조가 궁금합니다!🤔
ㄴ `일반적으로 많이 사용되는 구조 라는것은 알 수 없습니다. 제가 함부로 답변할 수 없어요! 회사마다 다르고 현업에 계신분들마다 다 다르기때문에 어떤 방법이 가장 많이 사용한다! 라고 볼 수 없습니다.`
> 
> <img alt="" width="500" src="https://camo.githubusercontent.com/a15fe8ca1bfadcc4242ae16a9863f9e82cd58d870214de81c702be5af4e5db08/68747470733a2f2f692e696d6775722e636f6d2f636344627a445a2e6a7067">
> 
> 아래 코드처럼 Input, Output 타입을 활용한 구조도 많이 사용하는 것 같습니다. 아래 구조를 활용하면 Input는 tableView tap 이벤트 같은 것이 들어가는 것이 맞을지 궁금합니다.
ㄴ`네 맞습니다. (저의 주관적 기준)`
> 
> ```swift
> class ViewModel {
>     struct Input {
>         // viewController에서 받아올 이벤트를 담을 타입
>     }
>     
>     struct Output {
>         // ViewModel에서 가공한 결과를 담아서 viewController에 전달될 타입
>     }
>     
>     func transform(input: Input) -> Output {
>         return Output()
>     }
> }
> ```
> 
> ### 2️⃣ 키보드와 레이아웃
> 보통 키보드 때문에 textView나 textField가 가릴 때, scrollView의 bottomConstraint, contentInset.bottom, contentOffset.y 등을 keyboardHeight를 이용해 조정해줬습니다.
> 
> > 1. scrollView의 bottomConstraint.constant = -keyboardHeight
> > 2. scrollView.contentInset.bottom = keyboardHeight
> > 3. scrollView.contentOffset.y += keyboardHeight
> 
> 하지만 iPad의 Modal의 경우 modal의 bottom이 떨어져있고, 기기마다 그 떨어져있는 bottom값이 다릅니다. 따라서 단순히 keyboardHeight만큼 layout값을 조정해주는 것이 어려웠습니다. <img alt="" width="400" src="https://camo.githubusercontent.com/8c8757b19e891a1762a8d59088afddfe06ebdf31ad63b7a69182d2f4d97b9fde/68747470733a2f2f692e696d6775722e636f6d2f5978623547525a2e6a7067"> <img alt="" width="400" src="https://camo.githubusercontent.com/fa8bc8252cc43f580ccbb10ef0518cb42f0167f1f5ab0c7523e12c9b240b180f/68747470733a2f2f692e696d6775722e636f6d2f345657676659732e6a7067">
> 
> iPad의 경우, 어떠한 방법으로 키보드가 가리는 문제를 해결할 수 있을지 궁금합니다.
ㄴ `하단과 떨어진 높이가 동적이라면, 동적으로 계산하는 방법 외에는 없다고 생각됩니다. 지금의 경우는 텍스트 수정시 날짜 수정이 불가한 이슈가 있네요. (12.9Inch 기준)`
> 
> ### 3️⃣ enum의 위치
> 현재 project의 todo, doing, done 상태를 표현하기 위해서 **enum ProjectStatus**를 구현했습니다. 이 enum의 위치가 적절한지, 어떠한 위치에 있어야하는 지 궁금합니다.
ㄴ `위치는 정하기 나름이긴 하지만.. 제 기준으로는 별도의 Enum파일을 만들어서 관리하는건 어떨지 의견을 내고 싶네요.`
> 
> ### 4️⃣ MockStorageManager
> 현 step에서는 데이터를 DB에 저장하지 않습니다. 그렇지만 이후의 코드 수정을 최소화 하기 위해 프로토콜을(`Storagable`) 활용해서 외부 로직과 분리 시켰습니다.
> 
> ```swift
> protocol Storagable {
>     func create(projectContents: [ProjectContent])
>     func read() -> BehaviorRelay<[ProjectContent]>
>     func read(id: UUID?) -> ProjectContent?
>     func update(projectContent: ProjectContent)
>     func delete(projectContentID: UUID?)
> }
> ```
> 
> ProjectUseCase 타입이 인터페이스 입니다. 위 프로토콜을 채택하는 타입(ex. MockStorageManager)으로 ProjectRepository의 storageManager 프로퍼티 초기화만 시키면 Presentation 영역은 수정할 필요없습니다.
ㄴ`음... 이건 질문이 뭔지 모르겠네요?`
> 
> ### 5️⃣ Clean Architecture
> ⭐️ 각 그룹의 역할
> 
> * Data
>   
>   * data soruce: 로컬, 원격에서의 데이터를 담당하는 영역
>   * repository(`MockStorageManager`): data soruce의 데이터를 조정하는 책임
> * Domain
>   
>   * entity(`ProjectContent`): 프로젝트에 사용되는 비지니스 모델.
>   * repository(`ProjectRepository`): Persistence 인터페이스, 프로젝트 내에서 저장소에 CRUD하기 위한 인터페이스를 제공
>   * use case(`ProjectUseCase`): Presentaion layer에서 Domain layer로 접근할 수 있는 인터페이스를 제공
> * Presentation
>   
>   * view: app 이벤트를 처리하고 화면에 보여주는 책임
>   * view model: view를 위한 비지니스 로직 구현의 책임
> 
> 위처럼 layer별로 역할과 책임을 정의해봤고, 그에 따라서 구현했습니다. 저희가 프로젝트에 적용한 Clean Architecture가 제대로 역할 분리가 되었는지 궁금합니다.
ㄴ `저의 주관적 의견으로는 역할 분리는 제대로 되었다고 생각되나 역할에 따른 동작이 제대로 되었다고 보기에는 어렵습니다. 각 코드들에 코멘트 남겨놓을테니 참고부탁드려요.`
> 
> ### 6️⃣ MVVM
> <img alt="" height="200" src="https://camo.githubusercontent.com/e87291ef2a9e6c8c695af28f465076e5629afff4640436796fafa7366b7bc6b6/68747470733a2f2f692e696d6775722e636f6d2f444939797533322e706e67">
> 
> 저희가 만든 Model, View, ViewModel이 제대로 역할 분리가 되었는지 궁금합니다.
> 
> * Model: UI에 보여줄 데이터가 존재합니다. UI에서 받은 이벤트로 데이터의 수정이 필요할 때 실제 데이터가 수정 작업을 진행합니다.
> * View: 사용자의 이벤트를 받고, 보여줄 UI를 구현합니다.
> * ViewModel: Model과 View의 가교로서 View는 ViewModel을 통해 Model에 접근합니다. View에 나타내기 위한 데이터를 가공합니다.
> 
> #### VC vs View vs ViewModel vs Model
> MVVM에서는 ViewController도 View의 역할로 본다고 이해했습니다. 그렇지만 그 둘에 차이가 있다고 생각합니다. 저희가 구현한 View 타입들에서는(ex.` MainView`, `ProjectCell`) UI 보여주는 기능만 구현하고, 비동기 로직은 VC(ex. `MainViewController`, `PopOverViewController`)에서 구현하도록 했습니다. 이로 인해, View 타입의 프로퍼티(ex. `tableView`, `countLabel`) 은닉화가 어렵습니다. VC는 View 타입과 VM을 프로퍼티로 가집니다. ViewModel(ex. `MainViewModel`, `RegistrationViewModel`)에서만 Model(ex. `ProjectUseCase`)에 접근할 수 있습니다.
ㄴ `6번 답변과 동일합니다.`
> 
> ### 7️⃣ UI 입체적으로 보이는 방법
> * 목표
>   기능 요구서에서 제시한 UI처럼 입체적으로 TextField와 TextView를 그리고 싶었습니다.
>   구현 시 공부해야 하는 키워드에 대해 조언을 받을 수 있을까요😢
ㄴ `아래 시도하신 방법들 보면 맞는 방법이 맞습니다. 다만 모서리 부분만 쉐도우를 줄 수 있도록 할 수 있으니, 각 메서드들을 살펴보심이 어떨까 싶어요.`
> 
> <img alt="" height="300" src="https://camo.githubusercontent.com/2c1eed90aa3d0a9d5071c5183b67d25fb5f5dbfe2505bcba441ae6dcbb7d7cfc/68747470733a2f2f692e696d6775722e636f6d2f746143617662702e706e67">
> 
> * shadow 주기
>   쉐도우를 통해 그리려고 했지만 아래처럼 의도와 다르게 그려집니다.
>   또, textField와 textView에 동일한 두께를 줘도 다른 두께로 보입니다.
> 
> <img alt="" height="400" src="https://camo.githubusercontent.com/7a3ee5dd03ecbf54059e27892d6a05c3cce732b88d9632e2f26c3bbc6c23267d/68747470733a2f2f692e696d6775722e636f6d2f795a41737574522e706e67">
> 
> ```swift
> private func drawShadow(view: UIView, borderWidth: CGFloat = 1, color: UIColor) {
>     view.layer.borderWidth = borderWidth
>     view.layer.borderColor = color.cgColor
>     view.layer.shadowOpacity = 1
>     view.layer.shadowColor = color.cgColor
>     view.layer.shadowOffset = CGSize(width: 1, height: 1)
> }
> ```
> 
> * 테두리 선만 주기
>   현재는 평면적으로 보이도록 구현했습니다.
> 
> <img alt="" height="400" src="https://camo.githubusercontent.com/3bce1706a2784a9fd70a08e3851e15fc95407a219d44254e2de49ea21442c863/68747470733a2f2f692e696d6775722e636f6d2f7973414e50514c2e706e67">
> 
> ```swift
> private func drawBorder(view: UIView, borderWidth: CGFloat = 2, color: UIColor) {
>     view.layer.borderWidth = borderWidth
>     view.layer.cornerRadius = 5.0
>     view.layer.borderColor = color.cgColor
> }
> ```

나머지 부분들은 코드별 코멘트 참고해주시고, 전체적으로 부족한 부분들이 조금씩 보입니다!

접근 제한자는 특별히 다시한번 확인 부탁드려요.

다음 프로젝트(step3 or 프로젝트 관리 앱 II) 를 진행하시면서 수정하셔도 되고, Step2에서 완전히 수정 후 넘어가셔도 됩니다.

해당 부분은 편하신대로 결정하시면 됩니다!

2022-07-18 01:11 UTC, JoSH0318 commented on ProjectManager/ProjectManager/Domain/Entity/ProjectContent.swift
> +    static func convert(_ titleText: String?) -> ProjectStatus? {
enum의 init(rawValue:)을 사용하면 될 것 같아요 😊
하지만 string rawValue를 사용해야만 하기 때문에 그 방법을 피한 것 같습니다.
저희가 사용하려는 string 값이 "Move to TODO" 와 같은 버튼 타이틀인데 
이것이 enum의 rawValue 값이 되는게 애매했습니다 🥹
"Move to TODO"은 rawValue이기 보단 좀더 가공된 값이라고 판단했습니다 !!
🙇‍♂️

2022-07-18 01:20 UTC, JoSH0318 commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +
질문을 제대로 이해하지 못했습니다 🥲
말씀하신게 viewDidLoad()에서 할수 있음에도 loadView()에 분리한 이유를 질문하신 걸까요?

[공식문서](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621454-loadview)
> You can override this method in order to create your views manually. If you choose to do so, assign the root view of your view hierarchy to the [view](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621460-view) property. The views you create should be unique instances and should not be shared with any other view controller object. Your custom implementation of this method should not call super.

loadView의 공식문서를 근거로 이렇게 분리했습니다 😊
혹시 저희가 잘 못 생각한 것 일까요?

2022-07-18 01:27 UTC, JoSH0318 commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +    private func setUpSelection() {
현재 bindItemSelected()메서드에 파라미터로 UITableView를 받고 있는데 
이것을 UITableView배열로 받아 forEach를 사용하면 될 것 같습니다 😊
```swift 
tableViews.forEach { tableView in
     tableView.rx
         .itemSelected
         .bind { indexPath in
             tableView.deselectRow(at: indexPath, animated: true)
         }
         .disposed(by: disposeBag)
 }
```
예시로 이러한 형태로 바꿀수 있을 것 같아요!!
하지만 저희가 판단하기엔 위와 같은 방법이 직관적인 코드로 보여지지 않았습니다.
혹시 이 방법말고 어떠한 더 좋은 방법이 있을까요?

2022-07-18 01:41 UTC, JoSH0318 commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +                    return
저희가 분기처리 코드를 변경하면서 남겨놓은 잘 못된 코드인 것 같습니다🥲
guard 문으로 early return 하도록 수정했습니다.

2022-07-18 01:45 UTC, JoSH0318 commented on ProjectManager/ProjectManager/Presentation/Main/View/ProjectListView.swift
> +    lazy var countLabel: UILabel = {
앗 🥲 코드를 변경하면서 수정이 안 된 부분 같아요 😭
let으로 수정했습니다!!!

2022-07-18 01:56 UTC, Kim-TaeHyun-A commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +            .drive { [weak self] indexPath in
```swift
public func drive(
        onNext: ((Element) -> Void)? = nil,
        onCompleted: (() -> Void)? = nil,
        onDisposed: (() -> Void)? = nil
) -> Disposable {
    MainScheduler.ensureRunningOnMainThread(errorMessage: errorMessage)
    return self.asObservable().subscribe(onNext: onNext, onCompleted: onCompleted, onDisposed: onDisposed)
}
```
onNext, onCompleted, onDisposed 매개변수가 있는 것 같습니다.
클로저를 사용하면 onNext를 명시한 것과 동일한데 생략 시 명확성이 떨어질 것 같기도 합니다🤔

onNext는 실패하지 않고 제대로 값이 넘어올 때 수행됩니다.
onCompleted는 onNext로 넘어오는 데이터가 없으면 수행됩니다.
onDiposed는 DisposeBag 프로퍼티에 담긴 diaposable들이 definit 시 자동으로 같이 없어지게 되는데, 그 시점에 수행되는 구문입니다.

2022-07-18 02:13 UTC, Kim-TaeHyun-A commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +        bind(projects: viewModel.doneProjects, tableView: mainView.doneTable.tableView)
`bindCell(to projects: Driver<[ProjectContent]>, at tableView: UITableView) `로 네이밍 수정했습니다!

2022-07-18 02:18 UTC, Kim-TaeHyun-A commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +    private func bind(projects: Driver<[ProjectContent]>, tableView: UITableView) {
1. 자동으로 메인스레드에서 돌아가도록 해줍니다.
2. bind는 scheduler 관리를 따로 해야 합니다.  error 시 fatalError 호출이나 print를 합니다.
 ```swift
 func rxFatalErrorInDebug(_ lastMessage: @autoclosure () -> String, file: StaticString = #file, line: UInt = #line) {
    #if DEBUG
        fatalError(lastMessage(), file: file, line: line)
    #else
        print("\(file):\(line): \(lastMessage())")
    #endif
}
 ```
  subscribe 는 error 처리도 따로 해줘야 합니다.

2022-07-18 02:20 UTC, Kim-TaeHyun-A commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +    private func deleteProject() {
메서드 분리 전에 변수 사용하면 weak self 안해도 돼서 지역변수를 사용했습니다.
현재는 메서드를 따로 분리했기 때문에 통일성을 위해서 지역변수 업이 바로 인자를 전달하도록 수정했습니다!

2022-07-18 02:42 UTC, Kim-TaeHyun-A commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +            .map { "\($0.count)" }
```swift
projects
        .flatMap({
            SharedSequence<DriverSharingStrategy, String>.just(String("\($0.count)"))
        })
        .drive { count in
            tableView.compose(projectCount: count)
        }
        .disposed(by: disposeBag)
```
flatMap을 사용하면 위 코드처럼 바뀔 것 같습니다.

해당 스트림이 다른 스트림에 영향을 주고 싶을 때 사용하는 것 같아서 여기서는 동일 스트림에서 값만 수정하는 map이 더 적절해보입니다!

2022-07-18 02:47 UTC, Kim-TaeHyun-A commented on ProjectManager/ProjectManager/Presentation/Main/ViewModel/MainViewModel.swift
> +        return ProjectUseCase().repository.read()
프로퍼티를 은닉화시키고 메서드로 접근하도록 수정했습니다!

2022-07-18 03:08 UTC, Kim-TaeHyun-A commented on ProjectManager/ProjectManager/Presentation/Main/View/ProjectCell.swift
> +    var contentID: UUID?
접근제어자를 private(set)으로 수정해서 외부에서 직접 수정할 수 없도록 했습니다.

var 대신 let을 사용하려면 init 시 content를 넣어야할 것 같은데 방법을 잘 모르겠습니다😢

```swift 
projects
            .drive(tableView.rx.items(
                cellIdentifier: "\(ProjectCell.self)",
                cellType: ProjectCell.self)
            ) { _, item, cell in
                cell.compose(content: item)
            }
            .disposed(by: disposeBag)
```
위 방식으로 셀을 세팅하는 것 말고 다른 방법이 있는지 궁금합니다!

2022-07-19 12:54 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +    private func setUpSelection() {
결합 관련 오퍼레이터를 사용하거나 생각했었는지가 궁금해서 물어본 질문입니다 :)
좋은 방법이냐 나쁜 방법이냐 자체는 중요하게 보지 않았습니다.

2022-07-19 12:54 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +        bind(projects: viewModel.doneProjects, tableView: mainView.doneTable.tableView)
👍

2022-07-19 12:56 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +    private func bind(projects: Driver<[ProjectContent]>, tableView: UITableView) {
1. 👍
2. 에러 처리가 필수는 아닙니다.
특정 오퍼레이터를 통해 메인 스레드에서 돌아가도록 할 수 있는데 해당 부분을 알고있는지 알아보기 위하여 질문드렸습니다.

2022-07-19 12:56 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +    private func deleteProject() {
👍

2022-07-19 12:57 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +            .drive { [weak self] indexPath in
👍

2022-07-19 12:58 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +            .map { "\($0.count)" }
사용법을 알고있군요!
👍

2022-07-19 12:58 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/MainViewController.swift
> +                    return
👍

2022-07-19 12:59 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/ProjectCell.swift
> +    var contentID: UUID?
접근제한자 관련 질문이었습니다 :)

2022-07-19 12:59 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/View/ProjectListView.swift
> +    lazy var countLabel: UILabel = {
👍

2022-07-19 13:00 UTC, SungPyo commented on ProjectManager/ProjectManager/Presentation/Main/ViewModel/MainViewModel.swift
> +        return ProjectUseCase().repository.read()
👍

2022-07-21 03:45 UTC, SungPyo approved these changes
수정하신 내용들 잘 보았고, 추가 수정되거나 변경되는 부분은 말씀하신대로 다음 스탭(II) 에서 확인할게요 :)

고생하셨습니다

2022-07-21 03:45 UTC, merged