프로젝트 관리 앱 [STEP2-1, 2-2] 쿼카
yagom-academy/ios-project-manager pull request #145
Opened 2022-07-13 11:30 UTC by Quokkaaa

@lina0322 안녕하세요 엘림 😄 
이번에 UIkit으로 기능구현하고 MVVM을 적용해보는것까지가 목표였는데요.
M, V, VM, VC의 역할을 구분이 안되어있는 상태에서 진행하려다보니 혼동을 맛 보았습니다. 😭 
그래서 먼저 역할부터 구분하고 난 다음에 리펙토링을 진행했고 구분한 역할로 리펙토링을 했을때 변경 할게 많지는 않았던것같아요!

MVVM의 구조를 이 코드에서 어떻게 개선해볼 수 있을지 아니면 역할분리는 어떻게 이루어지는게 좋을지에대해서 아직 잘 모르는것 같아서 이 부분을 중점으로 피드백 주시면 감사하겠습니다.

# STEP2-1 
## 고민한점
- TableView or CollectionView 둘 중 무엇을 사용할 것인가 ?
  - TableView
    - 장점
      - CollectionView에 비해 단순하며 구현이 쉽다.
      - Swipe기능을 지원한다.
    - 단점
      - Cell 사이 간격을 View를 넣어서 구현해줘야하는 비용이 발생한다.
      - CollectionView에 비해 기능이 유연하지 않다.
  -  CollectionView
      - 장점
        - TableView에 비해 기능이 유연하다.
        - Apple의 기능 업데이트 지원을 계속 받고 있다(안전성).
        - Cell 사이간격을 View를 넣지않고 띄울 수 있다.
    - 단점
        - Swipe기능을 지원하지 않는다.
        - TableView에 비해 복잡(?) 할 수 있고 구현이 어렵(?)다.

> 이러한 점을 봤을때 향후 
> CollectionView에 기능이 유연하다는 점이 사용자에게 더 많은 기능을 지원해줄 수 있다.(기능추가에 유연함)
> Apple의 기능 업데이트 지원이 계속되기때문에 안정감과 기대감이 있다.
> View를 Cell사이에 삽입하지 않아도 된다
> 라는 점들 때문에 CollectionView를 선택하였습니다.

- UI를 어떻게 구성할 것인가 ?

![](https://i.imgur.com/X70RaXO.png)

> CollectionView로 Section 3개를 나눠서 구현해볼 수 있지않을까 ? 라는 생각으로 시도를 했습니다.  처음에는 section별 horizontal scroll기능이 지원되기때문에 vertical로 지원이 되겠지 싶어서 시작했는데 지원을 하지않는 것 같더라구요.. 😭 그래서 단순하게 CollectionView를 담은 View 3개를 horizontal StackView에 쌓는 구조로 구현하였습니다.

- CollectionView에는 serction별 scroll기능이 vertical은 지원이 안되는것일까 ?
> 사용자가 휴대폰을 사용할때 세로로 스크롤하는 거리보다 가로로 스크롤하는 거리가 더 짧고 엄지손가락을 많이사용하기때문에 ? 사용자 입장에서 편하게 구현되도록? 굳이 section별로 vertical로 스크롤을 지원을 안한것같다고 생각했어요 왜냐하면 사용자가 vertical기능을 사용해야한다고하면 apple이 지원하지않을 것같아 보이진않았습니다!

- DataSource or DiffableDataSource 둘 중 무엇을 사용할 것인가 ?
	- DiffableDataSource의 이점
		- 내부의 데이터 값이 변경될때(추가, 삭제, 수정)마다 자동으로 View를 업로드 해준다.
		- 데이터 동기화를 자동으로 해준다.
		- 코드양 축소

> DataSource를 사용했을때 기본적으로 값을 변경하고 view에 할당한 후 reloadData메서드를 계속 실행 해줬어야 했는데 이런 수동적인 관리를 하지않아도된다는 점에서 바로 사용했던것같습니다(약간..이걸 왜 이제알았을까 싶은 ㅜㅜ)

- CollectionView의 swipe기능을 어떻게 처리할 것인지 ?
> 제가 확인해본 바로는 CollectionView의 Swipe기능을 [지원하지않는](https://stackoverflow.com/questions/63655267/how-to-swipe-left-to-delete-a-collectioncell) 걸로 알고있습니다.
그래서 이를 직접 구현할지 또는 'SwipeCellKit' 라이브러리를 사용할지 두 가지선택지에서 직접구현하면 너무좋겠지만 시간도 빠듯했다보니 그냥 라이브러리를 사용했습니다.

- Popover 표시할 위치를 전체 view의 위치로 선별(TODO/ DOING / DONE)하였는데 이것이 안전한 방법일지 ?
> 팝오버를 띄울때 클릭된 위치의 값을 계산하고 전체 view에 width를 기준으로 1/3 지점이면 Todo, 2/3지점이면 Doing, 그 이외이면 Done으로 선별해주었는데 이와 같은 방법이 안전한 방법인지 궁금합니다. 혹시 제가 모르는 에러를 발생시킬 여지가 있는 그런게 있을까요 ? 혹은 다른 방법이 있는지도 궁금합니다.

# STEP 2-2
## 고민한점
- Model, View, ViewModel, ViewController의 역할을 어떻게 구분할 것인가?

> MVVM 구조를 만들때 viewModel을 생성해야하는데 이 역할과 VC와 많이 혼동되어 viewModel을 분리하는게 어렵더라구요! 그래서 역할 구분을 해보았습니다.

- **ViewModel의 역할**
	- view한테 input으로 이벤트를 받고 이에 맞게 데이터 값을 가공하여 ouput을 뱉는다.
- **ViewController의 역할**
	- view에서 발생한 이벤트를 viewModel에 알려준다.
	- viewModel이 뱉은 output값을 view에 전달해준다.
	- view의 UI Layout을 잡아준다.
	- 화면 전환을 해준다.
	- Model 값을 변경하는 과정에서 UI값을 사용해야할 때가 있는데 이럴떄는 viewModel이 이역할을 대신 할 순 없으니 VC가 해준다.(ex) view.width를 받아서 이값으로 어떤 값을 뱉어야할때)
- **View의 역할**
	- 이벤트를 받아서 VC에게 전달해준다.
	- viewModel의 변경된 output값을 받아 view에 보여준다.
- **Model의 역할**
	- 네트워크, json, 비즈니스 로직 등 데이터를 캡슐화한다.

혹시 덧붙여주실 부분이있다면 말씀 부탁드립니다.

- viewModel은 꼭 class여여만하는가? struct를 사용하면 안되는것인가 ?
> 구글링하여 MVVM관련글을 보면 대부분 viewModel을 class로 구현하였는데 구조체는 안되는걸까 궁금했습니다.

반드시 class로 구현해야하는지? 에대해서는 아직 잘 모르겠습니다. 그런데 class로 사용해야하는 상황과 이점 등을 확인해볼 수 있었습니다!

- 저는 UIKit을 사용했기때문에 크게 상관은 없었지만 Comnine이나 Rx를 사용한다고하면 기본적으로 @ObservedObject @EnvironmentObject, @StateObject등을 사용하게되는데 이가 class에만 사용할 수 있다는 점

- 추가로 viewModel에 있는 Model 값이 변경이될텐데 이때 구조체일 경우 mutating/recreated가 이루어 져야하고 이럴 경우에는 기본 Model 값이 변경될때마다 viewModel을 다시할당할 필요가 없기에 class로 구현하는게 합리적일 수 있다는 점

등이 있었습니다.

- viewModel은 UIKit이 import되지 않아야한다 ?
	- MVVM이 탄생한 배경이 view와의 의존성을 없애고자 만들어졌는데 viewModel에서 view를 사용하게되면 의존성이 생겨 viewModel의 재사용성에 영향을 줄 수 있다는 점
	- UI코드와 독립적인 테스트가 불가합니다.

간단하게 이정도로 확인을 하였는데 추가적인 내용이있으면 말씀 부탁드립니다.

## 어려웠던점
- viewModel을 VC에서 사용할때 동작을 하지않는 이슈가 있었습니다.
> UIKit으로 구현을 해서그런지 모르겠지만 MVVM으로 리펙토링 할게 별로 없었던 것 같습니다. 할 수 있는만큼 리펙토링을 해봤는데요 데이터 값이 변경되지않고 반영이되지않았습니다.

TodoListViewController에서 두가지 분리해야 할게 있었는데
1. Cell을 Swipe해서 삭제할 경우
2. Popover이벤트로 Todo의 상태값을 변경하여 위치를 옮겨줄때

이렇게 있었는데요 이때 수행해야할 기능을 viewModel에 옮겨주고 실행하는데 동작을 하지않았습니다.
유추해보기로는 컴플리션핸들러 내부에서 동작을 하지않았다는 점이있는데 이 부분에대해서 왜 이런 상황이 발생했는지 간단한 설명이나 힌트 좀 부탁드립니다.

2022-07-13 13:51 UTC, lina0322 requested changes
쿼카, 반갑습니다!
마지막 프로젝트인데 정말 고생 많았어요~
다양한 고민과 시도가 느껴지는 코드였습니다!

---

MVVM으로 리팩토링 하면서, 동작을 하지 않는 이슈가 있다고 적혀있었는데요.
ㅎㅎ 요거는 다소 이해가 안가네욥, 아키텍쳐를 바꿨다고 해서 동작하지 않았다는건 뭔가 잘못됐다는 것 같은데
코드가 있으면 더 설명해드리기 좋을거같아욥.
지금 상황만 봐서는 명확하게 파악하기가 힘드네요ㅠㅠ..

----

코드에 코멘트 남겨두었습니다. 확인해보시고 추가적으로 궁금한 점이나 이해가 되는 부분 있으면 편하게 디엠주세요~ 이번 스텝 고생많았습니다. 조금만 더 다듬어봅시다!!
화이팅~!

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/DB/LocalDB.swift
> +  typealias Element = Todo
굳이 typealias로 지정할 필요가 있나요??

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/DB/LocalDB.swift
> +
에러 처리는 나중에 하는건가요? 나중에 할 일이라면 TODO를 달아주시면 좋을거같아요~

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/DB/LocalDB.swift
> +  }
빈 Todo를 배열하는 이유가 있나요?

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/DB/LocalDB.swift
> +  }
어디에 사용되는 걸까요??

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/DB/RealmModel.swift
> +class TodoModel: Object {
상속할 일이 없다면 final 키워드를 사용해주세요~

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Model/ToDo.swift
> +  var identifier: String = UUID().uuidString
id라는 명칭도 괜찮을 것 같네요. identifiable에 대해 찾아보고 적용해보는 것도 좋겠어요!

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Model/ToDo.swift
> +      Todo(title: "test1", content: "쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!쿼카 하이!
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ쿼하!

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +  let todo: Todo
todo가 viewModel로 이동하는건 어떨까요?🤔

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +  }
뷰를 따로 넣어준 이유는 V를 분리하려고 하는걸까욥? 위에서 lazy var로 선언하지 않고 여기서 작업하면 어떻게 되나요?

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +  }
앱이 죽어도 되나요?🤔

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +  }
setupNavigation?

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +        self?.editView.setUserInteractionEnableViews(true)
줄 바꿈이 다소 애매한 것 같습니다~

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +        editedTodoData.identifier = self!.todo.identifier
!!!!!!!!!!!!!!!!!!!!!!!😱

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Cell/TodoCollectionViewCell.swift
> +import SwipeCellKit
사용해보니 어땠습니까ㅎㅎ

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Cell/TodoCollectionViewCell.swift
> +    self.mainStackView.addArrangedSubviews([titleLabel, contentLabel, dateLabel])
self를 명시한 이유가 있나요??

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Cell/TodoCollectionViewCell.swift
> +  }
이건 뭐죠??🧐

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +  var doneDataSource: DataSource!
이게 머선일이죠, 데이터소스가 안생기는 경우는 없나용?😰
데이터 소스를 viewModel로 옮겨보면 어떨까요?

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    snapshot.appendSections([0])
Int로 사용하는 것도 좋지만, 공부를 해야하니까 하나라도 Section을 만들어서 작업해보죠!

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +          withReuseIdentifier: "TodoCollectionViewCell",
"TodoCollectionViewCell"
셀의 이름이 변경되면 여기도 찾아와서 수정해야겠네요?😏

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +  }
??? 갑자기 왜 여기서 프로퍼티들이 나오나요. 반전 드라마인가...?!🤨

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +  }
음.. 코드 정리좀 해주세요...

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +  }
전부 다 반복적인거같은데요. 3가제 뷰에 모두 작업할거면 한번에 할 수도 있지 않을까요?

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    let writeVC = WriteTodoViewController()
VC -> ViewController

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    present(writeNC, animated: true)
NC - > navigationController

(솔직히 VC는 그럴 수 있는데 NC는 진짜 처음봐요 전..ㅎ)

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    let collectionViewState = self.findState(about: collectionView)
self 붙여아하는 부분인가용?

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    todoList[index] = todo
아무리 위에서 점검했다하더라도, 진짜 어쩌다 모르게 터지는 경우가 있어요.
안전하게 인덱스에 접근하는 방법을 찾아보세요!

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    deleteAction.image = UIImage(named: "delete")
String 관리 따로 해주세용~

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    return .done
default에서 `return .done`하면 어떻게되죠?

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    actionsStorage.append(actions[1])
index가 모두 위험해보여요~

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +  }
enum으로 만들지 않았었나용?😣

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListView.swift
> +    configureUI()
오, super를 가운데썼네요ㅎㅎ 어떤거 때문이죠?!

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListView.swift
> +      subitems: [doItem])
띄어쓰기가 다소 이상한데, 마지막 ) 줄바꿈해주는게 더 깔끔할거같아요~

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListView.swift
> +    let layout = UICollectionViewCompositionalLayout(section: section)
compositional을 사용해보니 어땠나용

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Write/Controller/WriteTodoViewController.swift
> +class WriteTodoViewController: UIViewController {
final 붙여주세용!

2022-07-13 13:51 UTC, lina0322 commented on ProjectManager/ProjectManager/Utils/Extension/StringOptional.swift
> +  }
오홍, Wrapped는 어떤 키워드인가용??
왜 Optional에 extension 했나요??

2022-07-15 01:18 UTC, Quokkaaa commented on ProjectManager/ProjectManager/DB/LocalDB.swift
> +  typealias Element = Todo
굳이 지정할 필요가 없는것같은데 따로 지우질 않았떤것같아요!
제거했습니다.

2022-07-15 01:56 UTC, Quokkaaa commented on ProjectManager/ProjectManager/DB/LocalDB.swift
> +  }
저 시점에는 LocalDB가 미완성이었습니다 ㅜㅜ 아래와 같이 구현해주었습니다.
https://github.com/yagom-academy/ios-project-manager/pull/145/commits/f172429b6ceba193aeae4709c6d1acb0dce6b446

2022-07-15 01:57 UTC, Quokkaaa commented on ProjectManager/ProjectManager/DB/LocalDB.swift
> +  }
위와 동일한 이유로 다시 구현해주었습니다.
https://github.com/yagom-academy/ios-project-manager/pull/145/commits/f172429b6ceba193aeae4709c6d1acb0dce6b446

2022-07-15 02:02 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Model/ToDo.swift
> +  var identifier: String = UUID().uuidString
프로토콜을 채택해주고 네이밍도 수정해주었습니다.
DB에 사용하는 identifier네이밍은 마이그레이션하는 방법을 숙지한 후에 수정해볼게요!
https://github.com/yagom-academy/ios-project-manager/pull/145/commits/d97579312d0f85671f1b706447546770041204f2

2022-07-15 02:16 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +  let todo: Todo
```swift
  let viewModel: EditViewModel
  weak var delegate: TodoDelegate?
  lazy var editView = WriteTodoView(frame: view.frame)
  
  init(todo: Todo) {
    self.viewModel = EditViewModel(todo: todo)
    super.init(nibName: nil, bundle: nil)
  }
```
이와 같은 방식을 말씀하시는걸까요 >??

2022-07-15 02:20 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +  }
구성된 view를 사용하기 위함인데요 lazy var로 선언하지않고 LoadView에서 작업하게되면 view를 할당해주지만 내부적으로 view에 접근할 수 는 없지않을까 ? 싶어요

의도하신부분이 프로퍼티 선언하지않고 loadView에서 `view = editView` 같이 바로 할당해주는걸 말씀하시는걸까요 !?

2022-07-15 04:42 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListView.swift
> +    configureUI()
Swift는 super.init을 호출하기 이전에 모든 프로퍼티가 초기화가 되어야합니다. 이는 정확히 어떤말인지 잘 이해가가지는 않으나 super.init이 override되어 일관성없는 상태를 초래하는 메서드를 호출할 경우 발생하는 문제를 방지하기위함? 이라고 확인하였습니다. [참고링크](https://blog.scottlogic.com/2014/11/20/swift-initialisation.html#:~:text=Swift%EC%9D%98%20%EA%B7%9C%EC%B9%99%20%EC%A4%91%20%ED%95%98%EB%82%98%EB%8A%94%20%EC%8A%88%ED%8D%BC%ED%81%B4%EB%9E%98%EC%8A%A4%EB%A5%BC%20%EC%B4%88%EA%B8%B0%ED%99%94%ED%95%98%EA%B8%B0%20%EC%A0%84%EC%97%90%20%ED%81%B4%EB%9E%98%EC%8A%A4%EC%9D%98%20%EB%AA%A8%EB%93%A0%20%EC%86%8D%EC%84%B1%EC%9D%84%20%EC%B4%88%EA%B8%B0%ED%99%94%ED%95%B4%EC%95%BC%20%ED%95%9C%EB%8B%A4%EB%8A%94%20%EA%B2%83%EC%9E%85%EB%8B%88%EB%8B%A4.%20%EC%9D%B4%EB%8A%94%20%EC%88%98%ED%8D%BC%20%EC%9D%B4%EB%8B%88%EC%85%9C%EB%9D%BC%EC%9D%B4%EC%A0%80%EA%B0%80%20%EC%9E%AC%EC%A0%95%EC%9D%98%EB%90%98%EC%96%B4%20%EC%9D%BC%EA%B4%80%EC%84%B1%20%EC%97%86%EB%8A%94%20%EC%83%81%ED%83%9C%EB%A5%BC%20%EC%B4%88%EB%9E%98%ED%95%98%EB%8A%94%20%EB%A9%94%EC%84%9C%EB%93%9C%EB%A5%BC%20%ED%98%B8%EC%B6%9C%ED%95%98%EB%8A%94%20%EA%B2%BD%EC%9A%B0%20%EB%B0%9C%EC%83%9D%ED%95%A0%20%EC%88%98%20%EC%9E%88%EB%8A%94%20%EB%AC%B8%EC%A0%9C%EB%A5%BC%20%EB%B0%A9%EC%A7%80%ED%95%A9%EB%8B%88%EB%8B%A4.%20%EB%AC%B8%EC%A0%9C%EC%97%90%20%EB%8C%80%ED%95%9C%20%EA%B0%84%EB%8B%A8%ED%95%9C%20%EC%84%A4%EB%AA%85%EC%9D%80%20%EC%9D%B4%20%EC%9A%94%EC%A7%80%20%EB%A5%BC%20%EC%82%B4%ED%8E%B4%EB%B3%B4%EC%84%B8%EC%9A%94%20.)

추가로 super.init을 맨뒤에 사용할 경우

<img width="1045" alt="스크린샷 2022-07-15 13 40 02" src="https://user-images.githubusercontent.com/91132536/179151881-5d004558-d7ee-4fd7-99bf-92f5aa04bca5.png">


`'self' used in method call 'registerCells' before 'super.init' call` 이와 같은 에러가 발생합니다.
super.init을 호출하지이전에 self 를 사용할 수 가 없는데 todoCollectionView프로퍼티에 self를 사용하기때문에?
발생하는 에러인것같은(?) 느낌인데 혹시 잘 이해하고 있는걸까요 ?

2022-07-15 04:50 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +  }
xib나 storyboard에서 생성될때에는 이 init을 통해서 객체가 생성되는걸로 알고 있는데요
코드로 UI를 구성하는데에도 앱이 죽을 수가 있나요 ??

2022-07-15 04:51 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Cell/TodoCollectionViewCell.swift
> +import SwipeCellKit
Swipe만 사용했다보니 아직 느낌을 모르겠습니다. 
근데 커스텀하지않아도되니 너무 편하네요

2022-07-15 05:13 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +  }
😭 😭  setUpNavigation으로 수정하였습니다.

2022-07-15 05:32 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +        self?.editView.setUserInteractionEnableViews(true)
```swift
    navigationItem.leftBarButtonItem = UIBarButtonItem(
      systemItem: .edit, primaryAction: UIAction(
        handler: { [weak self] _ in
        self?.editView.setUserInteractionEnableViews(true)
      })
    )
```
아래와 같이 수정하였습니다.

2022-07-15 05:33 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +        editedTodoData.identifier = self!.todo.identifier
```swift
    navigationItem.rightBarButtonItem = UIBarButtonItem(
      systemItem: .done,
      primaryAction: UIAction(handler: { [weak self] _ in
        self?.saveUpdatedTodo()
        self?.dismiss(animated: true)
      })
    )
  }
  
  private func saveUpdatedTodo() {
    let state = viewModel.todo.state
    var editedTodoData = makeFormTodoDate(state: state)
    let id = viewModel.todo.id
    
    editedTodoData.id = id
    
    let todoModel = DBManager.shared.mappingTodoModel(from: editedTodoData)
    let todoDictionary = mappingDictionary(from: editedTodoData)
    
    self.delegate?.updateData(editedTodoData)
  }
```
위험한 친구는 제거해주고..^^ 캡쳐로 인해 내부적으로 옵셔널이 많이들어가고 바인딩을해주다보니 가독성이 떨어지는것같아 메서드로 빼줬습니다.

2022-07-15 05:35 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Cell/TodoCollectionViewCell.swift
> +    self.mainStackView.addArrangedSubviews([titleLabel, contentLabel, dateLabel])
특별한 이유는 없었습니다..^^
덜삭제된던 것 같아 제거해주었습니다.

2022-07-15 05:36 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Cell/TodoCollectionViewCell.swift
> +  }
라인넘버가 3이상인지를 판별하는 메서드를 구현했던 흔적입니다..^^
불필요하여 제거해주었습니다.

2022-07-15 05:37 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +  var doneDataSource: DataSource!
초기에 말씀해주신대로 viewModel로 옮겼었으나 viewModel에는 UIkit이 Import되면 안되는 규칙이있다보니
추가해주지 않았습니다.

2022-07-15 05:56 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListView.swift
> +      subitems: [doItem])
말씀해주신대로 수정하였습니다.
https://github.com/yagom-academy/ios-project-manager/pull/145/commits/f96b5818889298ae8dc0fc6775b4a268f57c33d1

2022-07-15 06:01 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +          withReuseIdentifier: "TodoCollectionViewCell",
프로토콜을 구현하여 채택해주었습니다. 😉 
https://github.com/yagom-academy/ios-project-manager/pull/145/commits/bfe9bf756aa95839db1321c189eeceed486e1ea4

2022-07-15 06:07 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +  }
데이터 소스와 구분해주려다보니.... 반전드라마가 연출된것같은데
현실 드라마로 리펙토링 하였습니다. 😉

2022-07-15 06:09 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +  }
https://github.com/yagom-academy/ios-project-manager/pull/145/commits/a7eeb2e9252cb1d4060a1285932cfce844162a08

2022-07-15 07:07 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +  }
아래와 같이 수정하였는데 의도하신 바가 맞을까요!?
```swift
  func updateListCountlabel() {
    todoListViews.forEach { view in
      State.allCases.forEach { state in
        view.listCountLabel.text = viewModel.findListCount(state).description
      }
    }
  }
  
  private func reloadDataSource() {
    let dictionary: [State: DataSource] = [
      .todo: todoDataSource,
      .doing: doingDataSource,
      .done: doneDataSource
    ]
    
    dictionary.forEach { (state, dataSource) in
      applySnapShot(todoList.filter { $0.state == state }, dataSource: dataSource)
    }
  }
  
  private func setUpDelegate() {
    todoListViews.forEach { $0.todoCollectionView.delegate = self }
  }
```

2022-07-15 07:11 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    present(writeNC, animated: true)
선넘었나요 ...??? 수정하겠습니다.

2022-07-15 07:16 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    let collectionViewState = self.findState(about: collectionView)
습관이 남아있네요 ㅠㅠ 앞으로 주의하겠습니다.

2022-07-15 09:11 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    deleteAction.image = UIImage(named: "delete")
enum을 생성해서 Contant로 할당해주었습니다.

2022-07-17 08:50 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    return .done
.done을 가지고 함수가지고 종료될것같아요!
굳이 switch문이 종료되고난 후에도 return을 해주지않아도될것같네요

2022-07-17 09:09 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    actionsStorage.append(actions[1])
```swift
    guard let moveTodo = actions[safe: 0] ,
          let moveDoing = actions[safe: 1],
          let moveDone = actions[safe: 2] else {
      return [UIAlertAction]()
    }
    
    var actionsStorage = [UIAlertAction]()
    
    switch exceptState {
    case .todo:
      actionsStorage.append(moveTodo)
      actionsStorage.append(moveDoing)
      
      return actionsStorage
    case .doing:
      actionsStorage.append(moveTodo)
      actionsStorage.append(moveDone)
      
      return actionsStorage
    case .done:
      actionsStorage.append(moveTodo)
      actionsStorage.append(moveDoing)
      
      return actionsStorage
    }
```

2022-07-17 09:09 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    actionsStorage.append(actions[1])
safe로 처리하구 아래와같이 수정했습니다.

2022-07-17 09:11 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +  }
위와같이 switch문으로 수정해줬습니다.

2022-07-18 01:47 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListView.swift
> +    let layout = UICollectionViewCompositionalLayout(section: section)
각 섹션별로 나눠서 구성할 수 있다는 점이 유연하고 동적높이를 설정할 수 있어서 너무 좋은 것 같습니다.

2022-07-18 01:49 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Utils/Extension/StringOptional.swift
> +  }
Wrapped는 랩핑이 되어있는 상태를 말하는 걸로 이해하고 있습니다.
text에 할당해야하는 값이 String? 타입이다보니 이와같이 작성해줬었지만 이 역할은 Date의 역할인것같아서
Date extension으로 수정해주었습니다.

2022-07-18 01:50 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +  let todo: Todo
MVVM패턴으로 리펙토링하면서 데이터틑 viewModel의 역할이기때문에 viewModel안으로 넣어주었습니다.

2022-07-18 03:29 UTC, Quokkaaa commented
@lina0322 
엘림! MVVM구조로 리펙토링을 하려다보니 구조변경을 하나하나 코멘트로 남기기가 번거로울 것같아서 정리해서 말씀드릴게요! 구조변경 내용은 아래와 같습니다! 그리고 이전에 어려웠던점에대한 질문을 남겼었는데요 이부분은 리펙토링하면서 해결이되서 따로 질문을 남기진 않았어요!

1. MemoryStorage 싱글턴 구현
- Local, Remote DB저장은 다음 스텝부터 진행되기때문에 일시적으로 더미데이터를 갖는 MemoryStorage를 만들어 대체하였습니다.
- StorageType프로토콜을 추상화하여 어느 뷰컨에서든 사용할 수 있게 의존성 주입을 시켰습니다. 왜냐하면 수정할때 용이하게 만들기 위해서 입니다.
- viewModel이 storageType의 인스턴스를 갖고 이벤트를 받아서 데이터를 가공하는 작업을 storageType과 상호작용하는 방식으로 구현하였습니다.

2. Combine 사용
- Combine을 사용하니 MVVM의 구조를 구현하는데 복잡성이 이전보다 줄어들고 오히려 깔끔해지는걸 느꼈습니다. input과 Output의 구분을 확실하게 해줄 수 있고 데이터의 흐름 구조도 일일이 흐름을 다 파악할 필요없이 값을 연결만 해주면 그 이후로는 크게 신경을 쓰지않아도되서 사용하는게 좋다고 판단했습니다.

3. MVVM파일 구조로 변경
- 기존에는 Controller파일이 존재했는데 이는 MVC에서 적용되는 방법인걸로 이해하였습니다. 그래서 Scene별로 view, viewModel그룹폴더를 만들고 View에는 View와 VC+ Cell, ViewModel은 ViewModel을 넣는 방식으로 분리하였습니다!

2022-07-19 22:30 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +  }
넵, `view = EditView()`처럼 바로 생성하는 것을 의미했고, 쿼카 말대로 생성 시점 이외에 접근 할 일이 생긴다면, 프로퍼티로 선언하는 방식을 따라야할거같습니다!

2022-07-19 22:32 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +  }
저도 이 부분에 대해서 고민이 많았는데요. 
관련해서 저만의 이유를 말해보자면

1. 어쨌든 앱이 죽는 상황은 피하는게 좋을 것 같다.
2. 모든 상황을 컨트롤 할 수 없다.
3. 차후 어떤 방식으로 유지보수를 할지 알 수 없다.

이 정도가 될 것 같습니다. 지금 상황에서는 쿼카말대로 당연히 코드로만 짜기때문에 이쪽에 들어올 일은 없지만,
위와 같은 이유들로 피하는게 더 맞지 않을까 하는 저의 개인적인 의견이긴 했습니다!

쿼카의 의견도 궁금하네요😀

2022-07-19 22:33 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +        editedTodoData.identifier = self!.todo.identifier
메서드로 뺀 부분 정말좋습니다!

2022-07-19 22:33 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +  var doneDataSource: DataSource!
음.... UIkit이 Import되면 안되는 규칙 때문에, 옮기지 않는다는건 다소 의아한데요.
왜 UIkit이 Import되면 안되는 규칙이 있을까요?

2022-07-19 22:36 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +    present(writeNC, animated: true)
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ아니 그정도는 아니지만.. 수정해주셔서 감삼다ㅎㅎㅎㅎ

2022-07-19 23:00 UTC, lina0322 approved these changes
코멘트 달아 두었고, 수정이 필요한 부분이 있는데요!
다음 스텝에서 함께 진행하면 될 것 같아서 우선 머지하고 진행하는 걸로 합시당.
마찬가지로 이해가 안가거나 어려운 부분이 있으면 메세지 주세요!!

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/DB/Realm/LocalDB.swift
> +      print(error)
print는 다른 것으로 대체해주세요!
`debugPrint` or `log`

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/DB/Realm/TodoModel.swift
> +    self.init()
convenience init은 다른 init과 어떤 차이가 있나용?

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Edit/ViewModel/EditViewModel.swift
> +  func doneButtonDidTap(title: String?, content: String?, date: Date?) {
viewModel 내부에서 사용되기에 적합한 네이밍은 아닌거같아요!
tap이 되었을때 동작들은 controller에서 실제로 컨트롤 하기 때문에, 여기서는 updateTodo나 다른 네이밍이 좀 더 좋겠습니답.
역할분리는 아주 잘 되어있네요!

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Edit/ViewModel/EditViewModel.swift
> +  init(storage: StorageType = MemoryStorage.shared, item: Todo) {
LGTM👍

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/View/Cell/TodoCollectionViewCell.swift
> +    }
여러개의 todo를 가지고있을때, 셀이 재활용 되면서 시간이 지나지 않은 셀에서 date가 red인 경우는 없었나용?

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/View/Cell/TodoCollectionViewCell.swift
> +final class TodoCollectionViewCell: SwipeCollectionViewCell, Identifiable {
Identifiable을 채택한 이유가 궁금해욥!

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListViewController.swift
> +fileprivate enum Const {
약자...?!🤔

이거 만약에 private로하면 어떻게되나용ㅎㅎ

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListViewController.swift
> +  private var doneDataSource: DataSource!
!로 작업하면 안전의 문제는 없을까요?🤔

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListViewController.swift
> +        self?.applySnapShot(items, dataSource: self!.todoDataSource)
강제 언래핑은 되도록 제거해주세요.
현업에서는 거의 존재하지 않는 문법이라고 생각하시는게 좋아요~

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListViewController.swift
> +    guard let dataSource = collectionView.dataSource as? DataSource else {
collectionView에 있는 dataSource와 상단에 선언된 dataSource는 어떻게 다를까요?

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListViewController.swift
> +  }
사실상 이렇게 item이라는걸 찾는 로직은 viewModel로 이동해야하는게 맞거든요. 현재 코드에서 이동이 가능할까요??

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListViewController.swift
> +    guard let indexPath = collectionView.indexPathForItem(at: collectionViewPressedPoint) else {
indexPathForItem이 dataSource나 snapShot에도 있던것같은데, 혹시 본적있나용??

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/ViewModel/TodoViewModel.swift
> +  }
반복되는 코드ㄱ ㅏ보입니다~ 하나의 메서드로 동작하긴 어려울까요?

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Utils/Extension/Collection.swift
> +}
LGTM👍

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Utils/Extension/Date.swift
> +    let dateFormatter = DateFormatter()
DateFormatter는 비용이 큰 작업이에요. 함수를 사용할때마다 생성하지 않고, 미리 만들어두는게 좋습니답!

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Utils/Extension/Identifiable.swift
> +}
apple이 [identifiable](https://developer.apple.com/documentation/swift/identifiable)이라는 프로토콜을 이미 사용하고 있어요.
네이밍 변경이 필요해보입니다~

2022-07-19 23:00 UTC, lina0322 commented on ProjectManager/ProjectManager/Scene/Main/View/Cell/TodoCollectionViewCell.swift
> +final class TodoCollectionViewCell: SwipeCollectionViewCell, Identifiable {
아 이거 아래쪽 코드보고 어떤건지 알았습니답! 아래 코멘트처럼 네이밍 변경만 해주면 좋겠습니다~

2022-07-19 23:01 UTC, merged

2022-07-20 04:00 UTC, Quokkaaa commented on ProjectManager/ProjectManager/DB/Realm/LocalDB.swift
> +      print(error)
네 안그래도 전에말씀해주셔서 에러처리를 어떻게할지 고민했었는데요
throws로 에러를 전파하여 VC에서 처리를 해주자니 throws 함수가 너무많아지고 반환타입을 Result같은걸로 받자니 Create같은 메서드는 반환타입이 필요없는데 사용하는게 옳은것일지? 잘 모르겠어서
일단 아래와같이 노티피케이션으로 처리하였습니다.

```swift
  private func postNotification(_ error: Error) {
    NotificationCenter.default.post(
      name: Notification.Name(rawValue: "RealmError"), object: error
    )
  }
```
그런데  제가 원하는건 에러처리도 StorageType 프로토콜에 담아서 같이 추상화할 수 있는 방법은 없을지 여쭤보고싶습니다.
노티피케이션은 일일이 뷰컨에 노티등록을 해주고 처리해줘야하기때문에 유지보수가 좋은 코드인지 모르겠습니다.
만약에 다른 에러처리로 변경한다고 했을때 쉽게 갈아낄 수 있는 구조가 좋은 코드인것같다는 생각이 들었어요

2022-07-20 04:15 UTC, Quokkaaa commented on ProjectManager/ProjectManager/DB/Realm/TodoModel.swift
> +    self.init()
제가 이해한 바로는 convenience가 말그대로 편리하게 사용해준다는 의미를 가지고있습니다.
- init을 하나만 가질 수 있는데 convenience init은 여러개를 가질 수 있습니다.
- 모든프로퍼티의 초기값을 받아서 init하지않고 부분적으로만 초기화를하여 유연하게 사용할 수 있습니다.
- 반드시 기본 Init을 내부에 호출해야합니다.

정도가 있는것같아요!

2022-07-20 04:20 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Edit/ViewModel/EditViewModel.swift
> +  func doneButtonDidTap(title: String?, content: String?, date: Date?) {
아하!! 이런 내이밍은 VC의 역할이니 data를 가공해주는 의미에 네이밍으로 설정해주는군요!!
좋은 피드백 감사합니다 ㅎㅎ

2022-07-20 22:17 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/Controller/TodoListViewController.swift
> +  var doneDataSource: DataSource!
그런규칙이 존재하지는 않는것같습니다. 😅
다만 view와 viewModel 서로 의존성이 생기지는않을까 ? 궁금하네요!

2022-07-20 22:24 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/View/Cell/TodoCollectionViewCell.swift
> +    }
이부분에대해서는 확인을 못하고 넘어갔었는데 감사합니다..ㅎㅎ
```swift
  override func prepareForReuse() {
    super.prepareForReuse()
    titleLabel.text = nil
    contentLabel.text = nil
    dateLabel.text = nil
  }
```
위와 같이 재활용될때마다 text에 nil을 할당해줘서 설정값을 초기화해주었습니다.

2022-07-20 22:27 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/View/Cell/TodoCollectionViewCell.swift
> +final class TodoCollectionViewCell: SwipeCollectionViewCell, Identifiable {
같은 프로토콜 네이밍으로 사용해버렸네요. 😅  수정하겠습니다.

2022-07-20 22:31 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListViewController.swift
> +fileprivate enum Const {
허걱......완젼 착각을 했었네요 ㅜㅜ 
private을 적용하면 그 외부를 둘러싼 범위내에서만 사용할 수 있는데 private enum을 해도 똑같이 file영역에서만 사용할 수 있는거와 같네요!
좋은 지적 감사합니다.

2022-07-20 23:46 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListViewController.swift
> +  private var doneDataSource: DataSource!
예상치 못한 상황에 앱이 죽어버릴 상황이 생길 수 있을것같습니다!!
그래서 옵셔널로 변경하려고하는데요!

```swift
    viewModel.toList
      .sink { [weak self] items in
        guard let self = self else { return }
        self.applySnapShot(items, dataSource: self.todoDataSource ?? .some())
        self.todoView.updateListCount(items.count)
      }
      .store(in: &bag)
```
옵셔널로 변경했떠니 바인딩해줄때 초기값설정이 안되있을수 ? 있는것같아서  nil일 경우에 값을 처리해줘야하는것같더라구요!
여기서 따로 DataSource 값을 초기화해줘야할까요 ?

2022-07-20 23:46 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListViewController.swift
> +        self?.applySnapShot(items, dataSource: self!.todoDataSource)
자제 하도록하겠습니다!

2022-07-20 23:55 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListViewController.swift
> +  }
한번 시도해보겠습니다.

2022-07-21 00:30 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListViewController.swift
> +    guard let dataSource = collectionView.dataSource as? DataSource else {
음 잘 모르겠습니다.
알아봐 보도록 하겠습니다.

2022-07-21 00:36 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/ViewModel/TodoViewModel.swift
> +  }
충분히 가능할것같아요..ㅎㅎ
```swift
  var toList: AnyPublisher<[Todo], Never> {
    return readData(by: .todo)
  }
  
  var doingList: AnyPublisher<[Todo], Never> {
    return readData(by: .doing)
  }
  
  var doneList: AnyPublisher<[Todo], Never> {
    return readData(by: .done)
  }
  
  private func readData(by state: State) -> AnyPublisher<[Todo], Never> {
    return storage.read().map { items in
      return items.filter { $0.state == state }
    }
    .eraseToAnyPublisher()
  }
```
위와 같이 수정하였습니다. 감사합니다!!

2022-07-21 01:15 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Utils/Extension/Date.swift
> +    let dateFormatter = DateFormatter()
[dateFormatter비용 테스트](https://sarunw.com/posts/how-expensive-is-dateformatter/#experiment-%234%3A-how-expensive-is-changing-dateformatter-properties) 이 글을 확인해보니 엘림이 말씀해주신바와같이 실제로 비용이 많이 들어가네요 ㅎㅎ
좋은 피드백 감사합니다.

만일 만든다면 static으로 만들거나 프로퍼티로 미리 초기화를 시켜놓는 방식으로 하면 되겠죠 ?

2022-07-21 01:34 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Utils/Extension/Identifiable.swift
> +}
-> `Identifierable` 이렇게 개선했는데 엘림이 보시기에는 괜찮아 보이나요 ..?

2022-07-21 01:49 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListViewController.swift
> +  private var doneDataSource: DataSource!
예상치 못한 순간에 앱이 죽을 수 있을것같아요!
아래와 같이 수정해주었습니다.

```swift

    viewModel.toList
      .sink { [weak self] items in
        guard let self = self,
              let todoDataSource = self.todoDataSource else { return }
        self.applySnapShot(items, dataSource: todoDataSource)
        self.todoView.updateListCount(items.count)
      }
      .store(in: &bag)
```

2022-07-21 01:59 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Main/View/TodoListViewController.swift
> +    guard let indexPath = collectionView.indexPathForItem(at: collectionViewPressedPoint) else {
[참고](https://developer.apple.com/documentation/uikit/nsdiffabledatasourcesnapshotreference/3182907-itemidentifiers) 여기를 참고해보니 `[func index(ofItemIdentifier: Any) -> Int]` 

지정된 식별자가 있는 스냅샷의 항목 인덱스를 반환합니다. 라고 확인이되는게 이게 맞을까요 ?

2022-07-21 02:05 UTC, Quokkaaa commented
@lina0322  엘림!! 추가적으로 꼼꼼한 피드백 너무감사드려요 ㅎㅎ
많이 배울 수 있었습니다.

추가로 궁금한점 남겼는데 
크게
- CRUD 처리시 Error처리를 Notification으로 하는게 적절할지 ? 그리고 다른 에러처리방식으로 갈아끼우려면 추상화를 잘 시켜놓아야할 것같은데 이를 어떻게 처리해줄 수 있을지 ? 질문드리고싶습니다.
- `collectionView에 있는 dataSource와 dataSource는 어떻게 다를까요?` 이 질문에 대한 자료를 단순하게 구글링 했을때는 확인이 안되는것같은데 공식문서에 있을까요 ??

2022-07-22 05:05 UTC, Quokkaaa commented on ProjectManager/ProjectManager/Scene/Edit/Controller/EditTodoViewController.swift
> +  }
말씀해주신바와 의견에 동의합니다.
사실 선언만했지 실질적으로 required init을 한번도 사용해본적이 없고 엘림 말씀대로 차후 어떤 방식으로 유지보수 할지 알 수 없고 모든상황을 알 수 없을 것 같습니다.
그래서 100% 확신을 할 수 없기때문에 처리를 해두는게 안전한 것같아요!