프로젝트 관리 앱 [STEP 2] OneTool, marisol
yagom-academy/ios-project-manager pull request #149
Opened 2022-07-15 04:01 UTC by marisol-develop

안녕하세요 토니! @Monsteel 🤓
STEP2 PR 보냅니다!
SwiftUI도 처음이고, MVVM 구조도 처음이라서 많이 헤매느라 PR이 늦어졌습니다ㅠㅠ 🥲
이번 리뷰도 잘 부탁드립니다!

---

## 📝 전체적인 구조

- `TaskViewModel`: Task마다 가지고 있는 ViewModel로, title, date, body변수가 Published로 선언되어 있다
- `ContentViewModel`: ContentViewModel이 가지고 있는 ViewModel이다. TaskViewModel을 ObservedObject로 갖고 있고, @Published로 선언된 todoTasks, doingTasks, doneTasks를 갖고 있다
    - `appendData()`: TaskViewModel에 접근해 todo/doing/done에 append해주는 메서드
    - `moveData(_ task: Task, from: TaskType, to: TaskType)`: task를 다른 배열로 이동시켜주는 메서드
- `ContentView`: `TodoView`, `DoingView`, `DoneView`를 NavigationView > HStack으로 보여주는 뷰
- `TodoView`, `DoingView`, `DoneView`: 구독하고 있는 contentViewModel에서 자신의 taskType에 맞는 array의 Task 요소들을 CellView를 통해 보여주는 View
- `CellView`: 위 3가지 타입의 뷰로부터 contentViewModel, cellIndex, taskType을 전달받아 ListRowView로 데이터를 표시하는 뷰
- `ListRowView`: `CellView`로부터 정보를 전달받아 직접 화면에 Text를 통해 정보를 보여주는 뷰
- `RegisterView`, `RegisterElementView`: NavigationView인 `RegisterView`가 `RegisterElementView`를 화면에 표시함
- `EditView`, `EditElementView`: NavigationView인 `EditView`가 선택된 Task의 정보를 `EditElementView`가 화면에 표시함

## 🚀 trouble shooting
### 📌  taskType이 각 Array안에서 변경이 되지 않음

처음에 설계할 때 모든 Task들이 자신의 type을 알고 있어야 한다고 생각했습니다. 
그래서 Task 구조체에 TaskType 타입의 type 프로퍼티를 선언해주었는데, ContentViewModel의 moveTask 메서드에서 Task 자신의 type이 아니라, from이라는 taskType 파라미터를 받아서 그걸 기준으로 다른 type의 array로 옮겨주기 때문에 Task들이 자신의 type을 알고 있을 필요가 없어졌습니다.
그래서 taskType을 model에서 제거해주고, 직접 해당하는 Array에 append 되도록 변경해주었습니다.

### 📌 TaskViewModel의 Task를 ContentViewModel의 todoTasks에 어떻게 접근해서 append 시켜줄수 있을까?

ViewModel을 총 2개를 만들었는데요,
1. 각 Task마다 가지고 있는 TaskViewModel
2. ContentView가 가지고 있는 ContentViewModel

처음으로 사용자가 우측 + 버튼을 눌러서 Task를 생성하는 상황에서,
TaskViewModel 내의 @Published var title, @Published var date, @Published body를 가지고 task를 생성해주고,
그 task를 ContentViewModel의 todoTasks에 append 시켜주고 싶었습니다
그래서 ContentViewModel이 TaskViewModel을 구독하도록 하고, 그 TaskViewModel에 접근해서 자신의 todoTasks에 append하도록하여 해결했습니다

```swift
class TaskViewModel: ObservableObject {
    var task: Task?
    var taskArray: [Task] = []
    @Published var title: String = ""
    @Published var date: Date = Date()
    @Published var body: String = ""
    
    func addTask() {
        task = Task(title: self.title, date: self.date, body: self.body)
        if let finalTask = task {
            taskArray.append(finalTask)
        }
    }
}
```

```swift
class ContentViewModel: ObservableObject {
    @ObservedObject var data = TaskViewModel()
    @Published var todoTasks: [Task] = []
    @Published var doingTasks: [Task] = []
    @Published var doneTasks: [Task] = []
    
    func appendData() {
        data.addTask()
        if let task = data.taskArray.last {
            todoTasks.append(task)
        }
    }
}
```
그런데 혹시 이렇게 한 ViewModel이 다른 ViewModel를 프로퍼티로 갖고 접근하는 것이 바람직하지 않은 방법인지 궁금합니다 🙏

## 🧐 궁금한점

### 📌 Date 비교의 부등호
```swift
 func checkOverdate() -> some View {
        if taskType != .done && taskArray[cellIndex].date + (60*60*24) < Date() {
            return Text(taskArray[cellIndex].date.convertDateToString)
                .foregroundColor(.red)
        } 
```

taskArray의 date 값이 현재보다 더 커져야 한다고 생각해서,
```swift
taskArray[cellIndex].date < Date(timeinterval: 60*60*24, since: Date())
```
이렇게 만들었지만, 정상적으로 결과 값을 얻을 수 없어서 부등호의 방향을 바꿔주고 cell의 date의 시간을 늘려주는 방식으로 해주었더니, 정상적으로 작동했습니다. 정상적으로 작동하였지만 로직을 이해하기 힘들어서 설명해주시면 감사하겠습니다!

### 📌 Popover 버튼 크기와 정렬 설정

popover 버튼이 2개가 필요해서 Form 안에 Button을 2개를 넣었습니다
그리고 Form의 frame을 수동으로 설정해주고, 그 안에서 정렬도 아래와 같이 설정해주었는데요

```swift
Form {
    Button(action: {
                    contentViewModel.moveData(contentViewModel.todoTasks[cellIndex],
                                              from: taskType,
                                              to: .doing)
                }) {
                    Text("Move to DOING")
                }
                Button(action: {
                    contentViewModel.moveData(contentViewModel.todoTasks[cellIndex],
                                              from: taskType,
                                              to: .done)
                }) {
                    Text("Move to DONE")
                }
            } 
            .frame(width: 190, height: 90, alignment: .center)
```

아래와 같이 스크롤이 생기고 alignment도 center가 적용되지 않는 것 같습니다
alignment에 .bottom 이나 다른 설정을 주어도 변경되지 않는 것 같은데, 
기능 요구서와 같이 깔끔하게 나오려면 어떤 다른 설정을 해주어야 할지 조언해주시면 감사하겠습니다 🥲
![](https://i.imgur.com/pmMEfKu.gif)

### 📌MVVM 구조 관련 질문
- 현재 taskViewModel을 task를 처리하는 모든 viewModel이 들고 있는 형태로, 1:N 관계처럼 되는데 1:1 관계처럼 만들어주고, 각 taskViewModel이 필요한 View마다 ViewModel을 하나씩 생성해주어야 하는지 궁금합니다.

- View가 로직을 가지고 있으면 안될 것 같은데, 저희 지금 코드에서는 View가 분기처리를 하는 등의 로직을 갖고 있어서, 이부분에 대해 조언 주시면 감사하겠습니다!🙇‍♀️

2022-07-18 08:30 UTC, Monsteel requested changes
안녕하세요 OneTool, marisol~! Step2수고많으셨습니다 :)

코드에 대한 리뷰는 아래 코멘트를 참고해주시구요!

남겨주신 질문에 대해서는 아래를 참고해주세요!

## 남겨주신 질문에 대한 답변

### 1. Date 비교의 부등호

이 부분에 대해서는 playground를 만들어서 두분이 한번 테스트를 해보면서 확인을 해보시면 좋을것 같아요 ☀️

추가로, 부등호 방향이 헷갈릴때에는
Date에 after, before 와 같은 extension을 만들어서 보다 명확하게 사용할 수 있는 방법도 있습니다.

### 2. Popover 버튼 크기와 정렬 설정
해당 문제를 바라보기 전에, 두가지 포인트를 먼저 고민해 보아야 할 것 같습니다.

Form Item의 height는 어떻게 산출되나요? / Form에 딱 맞는 height를 어떻게 산출할 수 있을까요?

두 질문에 대해 우선 고민해보고,  GeometryReader에 대해 한번 공부해보시면 좋을 것 같습니다 👍


## 3. MVVM 구조 관련 질문

우선, ViewModel을 왜 ViewModel이라고 부르는지에 대해 먼저 고민해보시면 좋을것 같아요.

ViewModel은 말그대로 View의 Model로 해석할 수 있는데요, 

OneTool과 marisol이 구현해준 방법의 경우, View의 Model보다는 기능단위 Domain의 Model에 가까워 보입니다.

특정 기능을 수행하는 view가 viewModel을 가지고 있음으로 인해서

ViewModel : View != 1:n 의 구조는, View 각각의 역할을 분리하기 어려워지게 되고, 변경에 유연한 코드가 작성되기 어려운 환경이 만들어질 위험이 있습니다.

우선, View의 Model에 가까운 ViewModel을 만들기 위해서는 1:1 관계가 조금 더 ViewModel에 가까운 형태가 아닐까 싶습니다.

추가로, Domain(기능) 에 묶이는 로직은 service layer 내지, [repository Pattern](https://gamjatwigim.tistory.com/85)에서의 repository 등의 layer를 두어서 해결 할 수 있습니다.

--- 
리뷰 내용에 대해서 궁금한점이 있으시면 언제든 말씀주세요! :)

감사합니다 ☀️

2022-07-18 08:30 UTC, Monsteel commented on Podfile
> +  use_frameworks! :linkage => :static
`use_frameworks! :linkage => :static` 이 라인은 어떤 의미인가요? 🙋🏻‍♂️

2022-07-18 08:30 UTC, Monsteel commented on ProjectManager/Extension/Date+extension.swift
> +                dateFormatter.locale = .autoupdatingCurrent
들여쓰기가 어색합니다! 👀

2022-07-18 08:30 UTC, Monsteel commented on ProjectManager/Model/NavigationBarModifier.swift
> +struct NavigationBarModifier: ViewModifier {
`ViewModifier`를 쓰셨군요! 👀 좋습니다.

적용해주신 방법과 비교해볼 수 있는 다른 방법으로는 extension을 통한 값 세팅이 있을것 같은데,

extension을 사용하는 방법을 검토해 보셨는지, 검토해보셨다면, 두 방법 중 ViewModifier를 사용하는 방법을 채택한 이유는 어떤것이 있었을까요?! 🙋🏻‍♂️

_둘 중 어느것이 더 좋다는 의미보다는, 두분의 생각의 흐름을 여쭈어 보고 싶었습니다 🙌_

2022-07-18 08:30 UTC, Monsteel commented on ProjectManager/Model/Task.swift
> +    var id = UUID()
id를 var로 선언하신 이유가 있나요? 👀
id는 해당 Data를 식별할 수 있는 수단이라는 특징을 보아, 변경에 폐쇄적인 방향이 더 좋을것 같습니다 🙋🏻‍♂️

추가로, 개인적으로는 initializer를 직접 선언하여 명시적으로 표현하는 방향을 더 선호합니다. 
이유는 가독성이 높아지고 수정에 용이하기 때문이에요. <- 데이터가 많아질수록 조금더 체감이 될 것 같아요.

2022-07-18 08:30 UTC, Monsteel commented on ProjectManager/Model/Task.swift
> +    var title: String {
title을 enum 내에서 별도의 value로 빼셨네요 👍 좋습니다

2022-07-18 08:30 UTC, Monsteel commented on ProjectManager/ProjectManagerApp.swift
> +//  Created by OneTool, marisol on 2022/07/05.
🌈✨🦄

2022-07-18 08:30 UTC, Monsteel commented on Podfile
> +  use_frameworks! :linkage => :static
`use_frameworks! :linkage => :static`이 코드가 어떤 의미를 가지는 코드일까요? 🙋🏻‍♂️

2022-07-18 08:30 UTC, Monsteel commented on ProjectManager/View/RegisterView.swift
> +    @Environment(\.dismiss) var dismiss
`@Environment`를 사용해서 View를 dismiss를 하는 방법도 있지만, initializer를 통해 해당 뷰를 가지고 있는 상위뷰에서,
`isShowingSheet`의 값을 바꾸어 주는 방법으로도 dismiss할 수 있습니다! ✍🏻

당장은 체감되지 않을 수 있지만
@Environment 를 사용하면 State를 변경하는 포인트가 두군데로 늘어나면서, 값 변경을 추적하고 디버깅하기 번거롭거나 어려워 질 수 있습니다.

State를 보다 쉽게 Binding하여 사용할 수 있는 SwiftUI의 특징을 활용해서 구현해 보는것도 좋은 경험일 것 같아요! ✍🏻

2022-07-18 08:30 UTC, Monsteel commented on ProjectManager/View/TodoView.swift
> +    func delete(at offset: IndexSet) {
따로 function 으로 분리해서 얻으려고 하신 이점이 있을까요?
코드를 읽어 내려가다가 delete의 구현을 확인하려면 아래로 내려가서 확인하고 다시 올라와야 하는 번거로움이 생길 수 있을것 같아요.

2022-07-18 08:30 UTC, Monsteel commented on ProjectManager/ViewModel/ContentViewModel.swift
> +        if let task = data.taskArray.last {
오호 굉장히 참신한(!) 방법을 적용해 주셨네요! 🙌 좋습니다.
다만 해당 방법은, ViewModel을 외부에서 어떻게 사용하느냐에 따라서 제대로 작동하지 않을 가능성이 있어보여요.

조금 더 안정적으로 수정이 필요해 보여요 🙌

2022-07-18 08:30 UTC, Monsteel commented on ProjectManager/ViewModel/TaskViewModel.swift
> +        task = Task(title: self.title, date: self.date, body: self.body)
`title`, `date`, `body`를 각각 바인딩해서 진행해 주셨는데요, state를 함수의 인자로 받지 않고, 이러한 방식을 채택한 이유가 있을까요? 👀

2022-07-18 08:30 UTC, Monsteel commented on README.md
> +## 📝 전체적인 구조
이렇게 적어주셔서 아주 편하게 코드를 파악할 수 있었습니다 ☀️

2022-07-19 11:21 UTC, kimt4580 commented on Podfile
> +  use_frameworks! :linkage => :static
기존 cocoapod로 설치한 framework 들은 dynamic type이라서 build 시간이 오래 걸렸습니다. cocoapod는 spm과 다르게 static 으로도 사용이 가능하고 build 속도가 빠르기 때문에 선언해주었습니다!

2022-07-19 11:22 UTC, marisol-develop commented on Podfile
> +  use_frameworks! :linkage => :static
위에 답변 적어두었습니다!

2022-07-20 01:55 UTC, kimt4580 commented on ProjectManager/Model/NavigationBarModifier.swift
> +struct NavigationBarModifier: ViewModifier {
View extention 시키는 방법도 생각했었는데, NavigationView를 사용하지 않는 View들 또한, 이 기능을 들고 있어야 할 것 같아서 ViewModifier를 사용하게 되었습니다.

2022-07-20 01:58 UTC, kimt4580 commented on ProjectManager/Model/Task.swift
> +    var id = UUID()
let으로 변경해주고, init을 사용하여 명시적으로 표현해주었습니다.

2022-07-20 01:59 UTC, kimt4580 commented on ProjectManager/View/RegisterView.swift
> +    @Environment(\.dismiss) var dismiss
다음 스텝에서 MVVM을 적용할 때, 반영하도록 하겠습니다!

2022-07-20 02:05 UTC, kimt4580 commented on ProjectManager/View/TodoView.swift
> +    func delete(at offset: IndexSet) {
```swift
 .onDelete { offset in
    contentViewModel.doneTasks.remove(atOffsets: offset)
}
```
위와 같은 형태로 변경해주었습니다.

2022-07-20 02:06 UTC, kimt4580 commented on ProjectManager/ViewModel/ContentViewModel.swift
> +        if let task = data.taskArray.last {
넵 MVVM 관련된 로직으로 구두로 말씀드린 것 처럼 다음 스텝에서 진행하도록 하겠습니다!

2022-07-20 02:31 UTC, kimt4580 commented on ProjectManager/ViewModel/TaskViewModel.swift
> +        task = Task(title: self.title, date: self.date, body: self.body)
파라미터를 사용하여, 기존에는 TaskViewModel에서 바인딩을 하는 형태였는데, ContentViewModel은 TaskViewModel에게 addTask를 사용하겠다는 것을 알려주고, ContentViewModel에서 바인딩 시키는 형태로 변경해주었습니다.

2022-07-20 02:36 UTC, Monsteel approved these changes
수고하셨습니다! 🙌🙌

2022-07-20 02:36 UTC, merged