프로젝트 관리 앱 [STEP3-1] 두기
yagom-academy/ios-project-manager pull request #153
Opened 2022-07-20 03:22 UTC by doogie97

@TTOzzi 
안녕하세요 또치!
세부 스텝 중 로컬 저장소 구현이 3-1 스텝 완료하여 pr보냅니다

미리 구현해뒀던 MockStorage를 교체하는 작업을 진행하여 시간은 그리 오래 걸리지는 않았지만 잘 구현한지 모르겠어서... 이전 피드백 처럼 상세한 피드백 주시면 정말 감사하겠습니다!!!

### PrimaryKey의 활용
![](https://i.imgur.com/0BkibjS.png)

Realm을 사용하다보면 PrimaryKey 라는 것을 지정해줘야 하는 것으로 확인 했는데 객체마다 고유한 값을 가지도록 하는 기능인 것 같습니다(만약 key를 title로 했을 때 중복되는 title이 생기는 경우 에러가 발생하는 것을 확인 함)

그래서 이것에 대해 더 찾아보는데 add로 업데이트를 했을 때 primaryKey가 중복되는 것이 add가 되면 자동으로 수정이 된다고 하는데 잘 되지 않았습니다

이와 관련해서 PrimaryKey가 같으면 자동으로 업데이트가 되는게 맞는지? 또 이것의 존재 이유와 활용방법? 등이 궁금합니다

### 저장소 안에 배열 3개 vs 객체 3개
![](https://i.imgur.com/GnPTs4j.png)
일단 현재는 PersistantStorage안에 각 타입의 리스트 세 개를 배열로 구현하였는데 이걸 각각의 객체로 분리 구현하는게 좋을지 지금 처럼 해도 괜찮을지 잘 기준이 잡히지 않아서 또치의 의견을 한번 듣고싶습니다

### input/ output

![](https://i.imgur.com/9mieDDw.png)

input은 viewmodel이 이벤트를 받아 해야할 행동
output은 viewmodel이 view로 전달하는 데이터 
정도로 이해를 했는데 알맞게 구현한 것이 맞을까요?

### 저장소의 네이밍
![](https://i.imgur.com/K5Jm3d4.png)
`BehaviorRelay`를 이용해 뷰 반영에 직접적으로 관여하는 객체를 `AppStorage`로, 로컬 저장소 반영에 직접적으로 관여하는 객체를 `PersistantStorage`로 네이밍을 하였고

Realm에 저장되는 객체 이름을 `ListItemDTO`라고 네이밍을 했는데

어떻게 네이밍을 해야할 지 고민이 많이 되었고 아직도 잘 모르겠습니다... 또치의 생각은 어떤지 여쭤보고 싶습니다

2022-07-21 13:33 UTC, TTOzzi requested changes
안녕하세요 두기!
남겨드린 코멘트 중 이해가 어려운 부분이 있으면 언제든 말씀해주세요.
고생하셨습니다 🙇 

### PrimaryKey의 활용

> Realm을 사용하다보면 PrimaryKey 라는 것을 지정해줘야 하는 것으로 확인 했는데 객체마다 고유한 값을 가지도록 하는 기능인 것 같습니다(만약 key를 title로 했을 때 중복되는 title이 생기는 경우 에러가 발생하는 것을 확인 함)
>
> 그래서 이것에 대해 더 찾아보는데 add로 업데이트를 했을 때 primaryKey가 중복되는 것이 add가 되면 자동으로 수정이 된다고 하는데 잘 되지 않았습니다
>
> 이와 관련해서 PrimaryKey가 같으면 자동으로 업데이트가 되는게 맞는지? 또 이것의 존재 이유와 활용방법? 등이 궁금합니다

간단하게는 데이터베이스 테이블에서 행 식별을 위한 고유값 정도로 설명드릴 수 있을 것 같고, 요건 제가 설명드리기 보단 `database table primary key` 라는 키워드로 데이터베이스 테이블에서 primary key가 어떤 용도로 사용되는지 자세히 찾아보시는 게 좋을 것 같아요.
cs 기초 지식이라 지금 찾아보고 공부해두시면 나중에 쓰일 일이 분명히 생길거예요 :bowing_man:

### 저장소 안에 배열 3개 vs 객체 3개

> 일단 현재는 PersistantStorage안에 각 타입의 리스트 세 개를 배열로 구현하였는데 이걸 각각의 객체로 분리 구현하는게 좋을지 지금 처럼 해도 괜찮을지 잘 기준이 잡히지 않아서 또치의 의견을 한번 듣고싶습니다

넵 저번에도 말씀드렸듯이 구현 방식의 차이라 괜찮은 것 같습니다.
중복 코드에 대한 우려가 있었는데, 타입을 인자로 받아 반환하는 메서드도 만들어두셔서 별 문제 없을 것 같네요!

### input/ output

> input은 viewmodel이 이벤트를 받아 해야할 행동
> output은 viewmodel이 view로 전달하는 데이터
> 정도로 이해를 했는데 알맞게 구현한 것이 맞을까요?

제 기준에선 `isOverDeadline` 이란 메서드가 애매한 것 같아요.
요건 input도 아니고 output도 아닌, output으로 리스트 데이터를 뷰로 전달하기 전 수행해야 할 데이터 가공 로직 같아보여서요 :thinking:
`ListItem` 데이터를 `셀을 업데이트하기 위한 데이터(셀 뷰모델?)`로 변환하고 현재 `[ListItem]` 의 형태로 반환하고 있는 output을 `[셀을 업데이트하기 위한 데이터]` 로 변경해볼 수 있을 것 같아요.
`ListItem` 데이터를 `셀을 업데이트하기 위한 데이터`로 업데이트하는 뷰 가공 로직은 지금 셀 내부에서 수행하는 `DateConverter` 로직과 뷰모델에 위치하고 있는 `isOverDeadline`이 될 것 같구요.

요건 제가 생각하는 MVVM의 기준일 뿐이라 꼭 적용하지 않으셔도 됩니다 :bow:
구현에 정답은 없고 역할 분리만 명확히 잘 된다면 어떻게 구현하던 괜찮다고 생각해요.

### 저장소의 네이밍

현재 구현엔 `PersistantStorage`가 없는데 `LocalStorage`를 말씀하신거죠?
데이터 구조 네이밍은.. 저도 어렵네요 :thinking::thinking::thinking:
계층간에 데이터를 전달에 사용한다는 점에서 의미가 맞고, 앱에서 사용하는 데이터와는 구분되고 있으니 이대로도 괜찮을 것 같습니다.

2022-07-21 13:33 UTC, TTOzzi commented on ProjectManager/ProjectManager/Model/ListItem.swift
> +    }
요렇게 변환하는 다른 타입으로 로직을 프로퍼티로 가질지, `ListItemDTO`에 `ListItem`을 인자로 받는 생성자로 만들어줄지 아니면 별도의 매핑 로직을 수행하는 객체를 만들어줄지 고민해볼 만한 포인트인 것 같습니다 🤔

2022-07-21 13:33 UTC, TTOzzi commented on ProjectManager/ProjectManager/Model/ListItemDTO.swift
> +    @objc dynamic var id: String = ""
프로퍼티들을 `@objc dynamic`으로 선언해주신 이유가 있을까요?
최신 버전에선 `@Persisted`로 선언하도록 가이드를 주고 있어서요 🤔 
https://www.mongodb.com/docs/realm/sdk/swift/model-data/define-model/object-models/#std-label-ios-realm-objects
https://www.mongodb.com/docs/realm/sdk/swift/model-data/define-model/object-models/#objective-c-dynamic-property-attributes

2022-07-21 13:33 UTC, TTOzzi commented on ProjectManager/ProjectManager/Model/ListItemDTO.swift
> +    }
`@Persisted`로 선언하면 PK 지정도 다른 방식으로 변경해줘야 할 같네요.

2022-07-21 13:33 UTC, TTOzzi commented on ProjectManager/ProjectManager/Storage/AppStorage.swift
> +    lazy var doneList = BehaviorRelay<[ListItem]>(value: localStorage.readList(.done))
`lazy var`로 선언되어야 하는 명확한 이유가 있는 게 아니라면, 그냥 변수나 상수로 선언하는 게 좋을 것 같아요.
프로퍼티가 아직 초기화되지 않은 상태에서 여러 스레드에서 동시에 접근했을 때, 여러 개의 인스턴스가 생성될 수 있습니다.

2022-07-21 13:33 UTC, TTOzzi commented on ProjectManager/ProjectManager/Storage/AppStorage.swift
> +    private let localStorage = LocalStorage()
`AppStorage`가 앱 전체적으로 사용할 데이터의 원천이 되고, 그 내부에서 로컬db, 리모트db를 각각 관리하게 되는 구조를 생각하신 건가요? 👀 
추가로 의존성을 가지는 `localStorage`는 추상화 후 외부로부터 주입받도록 구현되면 더 유연한 구조를 만들 수 있을 것 같습니다.

2022-07-21 13:33 UTC, TTOzzi commented on ProjectManager/ProjectManager/Storage/AppStorage.swift
> +        return selectList(type).value[index]
`index`로 값에 접근할 때 데이터의 싱크가 안맞아서 `index`의 범위를 벗어나는 케이스에 대한 처리도 해주면 더 좋을 것 같아요.

2022-07-21 13:33 UTC, TTOzzi commented on ProjectManager/ProjectManager/Storage/AppStorage.swift
> +    }
삭제 로직은 `localStorage`의 `deleteItem`을 직접 호출하고, 생성 로직은 `creatItem`을 호출하고 있어 조금 어색한 것 같아요.
`creatItem`에선 생성된 아이템의 타입과 관계없이 `todoList.accept(localStorage.readList(.todo))`를 호출하고 있어 로직 수정이 필요할 것 같습니다 🤔

2022-07-21 13:33 UTC, TTOzzi commented on ProjectManager/ProjectManager/Storage/LocalStorage.swift
> +final class LocalStorage: Object {
음.. `LocalStorage`가 로컬 db에 저장되는 데이터 구조의 역할도 하면서, 동시에 CRUD 로직을 수행하는 객체이기도 하네요.
저장되는 데이터 구조와 로직을 수행하는 객체를 명확하게 분리해주면 좋을 것 같습니다.

2022-07-21 13:33 UTC, TTOzzi commented on ProjectManager/ProjectManager/Storage/LocalStorage.swift
> +            .compactMap { $0.convertedItem }
`LocalStorage`의 역할이 `Realm`에 접근해서 저장된 데이터를 가져오고, `Realm`에서만 사용하는 데이터 구조를 앱에서 사용하는 데이터로 변경하는 로직을 수행하니, 데이터 구조에 컨버팅 로직을 정의하기 보단 여기서 정의해도 될 것 같네요 🤔

2022-07-21 13:33 UTC, TTOzzi commented on ProjectManager/ProjectManager/Storage/LocalStorage.swift
> +    }
실패할 수 있는 로직에 대해 ` try?`로 처리되어 있는 부분이 많은데요.
요런 핵심 로직은 실패에 대한 처리를 반드시 해주어야 합니다.
지금은 로직이 실패했을 때 사용자가 인지할 수 있는 방법이 없네요 😢

2022-07-21 13:33 UTC, TTOzzi commented on ProjectManager/ProjectManager/Storage/AppStorage.swift
> +        todoList.accept(localStorage.readList(.todo))
`createItem` 내부 생성 로직은 비동기로 수행되는데, `completion`을 받아 다음 동작을 수행하는 게 아닌 바로 `readList`로 가져온 값을 넘겨주고 있어서 데이터의 변경이 반영되지 않은 상태의 리스트가 화면에 표시될 수도 있을 것 같아요.

2022-07-21 13:33 UTC, TTOzzi commented on ProjectManager/ProjectManager/Storage/LocalStorage.swift
> +        guard let realm = try? Realm() else {
`Realm` 객체는 매번 새로 생성해줘야 하는 건가요? 👀

2022-07-22 00:28 UTC, doogie97 commented on ProjectManager/ProjectManager/Model/ListItemDTO.swift
> +    @objc dynamic var id: String = ""
최신 가이드를 직접 확인하지 않고 여러 튜토리얼들만 따라하다보니 확인을 못했습니다..
남겨주신 링크 확인 후 수정하였습니다!

2022-07-22 00:44 UTC, doogie97 commented on ProjectManager/ProjectManager/Storage/AppStorage.swift
> +    lazy var doneList = BehaviorRelay<[ListItem]>(value: localStorage.readList(.done))
아래 말씀하신 내용과 함께 local storage를 주입받으면서 리스트 들도 정의해주는 것으로 수정하였습니다

2022-07-22 00:44 UTC, doogie97 commented on ProjectManager/ProjectManager/Storage/AppStorage.swift
> +        return selectList(type).value[index]
데이터의 싱크가 안맞아서 Index의 범위를 초과한다는 말을 잘 이해하지 못했습니다
조금 더 상세하게 설명해 주실 수 있으실까요??

2022-07-22 01:49 UTC, doogie97 commented on ProjectManager/ProjectManager/Storage/AppStorage.swift
> +        todoList.accept(localStorage.readList(.todo))
위에서 코멘트 달아주신 `changeItemType`을 수정하다보니 말씀하신대로 변경된 사항이 제대로 반영되지 않고 어플을 껐다 켜야지만 반영되는 문제가 있었습니다
그래서 해당 로직들을 completion을 통해 아예 ListItem 배열을 리턴할 수 있게 처리하였습니다

2022-07-22 03:13 UTC, doogie97 commented on ProjectManager/ProjectManager/Storage/LocalStorage.swift
> +    }
일단 alert을 통해 사용자가 인지할 수 있도록 구현하였습니다
만약 실제 앱을 출시하게 된다면 버그리포트 보내기 등으로 더 추가적인 기능을 구현 할 수 있을 것 같습니다

2022-07-22 03:32 UTC, doogie97 commented on ProjectManager/ProjectManager/Model/ListItem.swift
> +    }
일단 이 부분은 지금 realm을 위해 정의해놓은 모델또한 나중에 firebase에서 사용될 여지가 있다고 생각해서 지금 수정하기보다는 원격 저장소를 다 구현 할 때 그 때 한번 고민해 보도록 하겠습니다!

2022-07-22 03:32 UTC, doogie97 commented on ProjectManager/ProjectManager/Storage/LocalStorage.swift
> +            .compactMap { $0.convertedItem }
첫 번째 코멘트에 답변 남겨두었습니다!

2022-07-22 03:49 UTC, doogie97 commented on ProjectManager/ProjectManager/Storage/LocalStorage.swift
> +final class LocalStorage: Object {
데이터 구조는 LocalStorage로, CRUD기능은 LocalStorageManager로 분리했습니다

2022-07-22 03:55 UTC, doogie97 commented on ProjectManager/ProjectManager/Storage/LocalStorage.swift
> +        guard let realm = try? Realm() else {
저도 이 부분이 마음에 걸려서 처음에는 전역에
```swift
final class LocalStorageManager: LocalStorageManagerable {
    private let realm = try? Realm()
```

요런식으로 생성을 해주었었는데 전역에서 try를 통해 선언한다는게 뭔가 찜찜해서 메서드 내부에 계속 생성해 준것 같습니다

지금 생각해보니 어차피 전역으로 선언해서 try? 를 통과 못해서 로직진행이 안되나 메서드 내에서 guard구문을 통과 못해서 로직진행이 안되나 매한가지라고 생각되어 처음 한번만 생성할 수 있도록 전역에서 생성해주었습니다

이 방법 이외에 더 좋은 방법이 어떤게 있을지 또치의 생각이 궁금합니다!

2022-07-22 12:30 UTC, TTOzzi commented on ProjectManager/ProjectManager/Storage/LocalStorage.swift
> +        guard let realm = try? Realm() else {
`private let realm = try? Realm()` 내부에서 선언과 동시에 생성되도록 구현하셨는데, 외부로부터 주입받도록 구현하고 DIContainer를 만들어두셨으니 그쪽에서 주입과 `Realm` 이 생성되지 않았을 때의 예외처리를 해주는 게 좋을 것 같아요.
`Realm`을 추상화하는 프로토콜을 구현하고 채택해서 `LocalStorageManager`와 `Realm`과의 의존성을 분리해주고, `LocalStorageManager`만을 독립적으로 테스트할 수 있는 구조를 만들어주면 더 좋을 것 같구요.

2022-07-22 12:32 UTC, TTOzzi commented on ProjectManager/ProjectManager/Scene/Detail/AddViewController.swift
> +            .disposed(by: disposebag)
뷰모델의 output으로 잘 처리해주셨네요 👍

2022-07-22 12:33 UTC, TTOzzi commented on ProjectManager/ProjectManager/Scene/Detail/AddViewModel.swift
> +            }
예상 범위 밖의 에러도 언제든 발생할 수 있으니, 캐스팅이 안될 땐 무시하기보단 "예상치 못한 에러가 발생했습니다. 다시 시도해주세요." 와 같이 일반적인 메세지라도 띄워줘도 뭔가 문제가 발생했음을 사용자에게 인지시켜주는 게 더 좋을 것 같아요 🤔

2022-07-22 12:37 UTC, TTOzzi commented on ProjectManager/ProjectManager/Storage/AppStorage.swift
>      }
요기서 `createError`를 저장했다가 던지는 이유가 궁금해요 🤔 
(비동기인줄 알았으나.. `Realm`의 동작이 동기적으로 동작해서 혼란을 드리긴 했는데 🙏 )만약 `createItem`이 비동기로 동작하고 저 클로저가 escaping 클로저라면, 함수 내에서 로직 실행 순서가 `46번` -> `48번(호출)` -> `57~59번` -> `49~53번(로직 완료 후 completion)` 이 될 수 있습니다.
비동기 로직의 실패는 넘겨줄 때도 비동기로 넘겨줄 수 있어야 해요.

2022-07-22 12:37 UTC, TTOzzi commented on ProjectManager/ProjectManager/Storage/AppStorage.swift
> +        return selectList(type).value[index]
요건 디엠으로 설명드렸습니다 🙇‍♂️

2022-07-22 12:40 UTC, TTOzzi approved these changes
completion 클로저의 결과를 넘기는 부분은 수정이 필요해보이는데, firebase 붙이면서 같이 챙겨보면 좋을 것 같네요!
고생하셨습니다 🙇‍♂️

2022-07-22 12:41 UTC, merged