프로젝트 관리 앱 II [STEP 1] 두두, 마이노
yagom-academy/ios-project-manager pull request #155
Opened 2022-07-21 12:24 UTC by Mino777

안녕하세요 올라프 @1Consumption!
프로젝트 매니저2 STEP1 PR보냅니다
이번스탭에서 구현한 기능은 다음과 같습니다

- 모든 로그를 볼 수 있는 History 기능
- remote DB와 Local DB의 구현 및 연동

잘 부탁드립니다!

## 추가 구현사항 실행화면

### History 기록

<img src = "https://i.imgur.com/sbdTzUi.gif" width = "600">

### 네트워크 연결 O/X 시 UI 변화

<img src = "https://i.imgur.com/LmbQBO8.gif" width = "600">

### 앱 최초 실행시 Remote -> Local 동기화

<img src = "https://i.imgur.com/xEuKj87.gif" width = "600">

### 앱 최초(x) 실행시 Local -> Remote 동기화

<img src = "https://i.imgur.com/cGuD6Lq.gif" width = "600">

## 고민한점 & 궁금한점

### Local DB와 Remote DB

앱의 모든 데이터가 LocalDB인 Realm에 저장이 되는데 대체 RemoteDB의 역할이 대체 뭘까 고민했습니다.
고민끝에 RemoteDB는 LocalDB의 백업/복원을 위한 저장소 정도로 사용하도록 하였습니다.

평소에는 Local DB인 Realm을 사용합니다
앱을 실행할때 해당 유저가 FireBase DB에서 백업받을 필요가 있는지 확인합니다 (UserDefault를 이용)

필요하다면 remote DB -> Local DB로 백업을 받고, 필요하지 않다면 Local DB -> remote DB로 업로드 (동기화) 작업을 수행하도록 하였습니다

### 테스트 코드 작성

View를 제외한 모든부분에 테스트를 작성하라고 하셔서 UseCase와 Repository역시 작성해 보았습니다.

`ViewModel`을 테스트하기 위해서 `StubUseCase`를 작성하여 테스트하였습니다

`UseCase`를 테스트하기 위해서 `MockRepository`를 작성하여 UseCase가 Repository의 매서드를 정상적으로 호출하는지 `행위검증`을 하였습니다

`Repository`를 테스트하기 위해서 `MockStorage`###를 작성하여 Repository가 Storage의 매서드를 정상적으로 호출하는지 행위검증을 하였습니다.

### 오류처리

Realm과 FireBase는 CRUD작업시 오류가 생길 수 있습니다.
이때 발생한 오류는 VC에서 alert을 띄워주고 싶었습니다.

#### Storage, Repository, UseCase

오류가 발생할 수 있는 매서드는 AnyCancellable<Void, StorageError> 를 반환

#### ViewModel

ViewModel에서 모든 오류를 
var showErrorAlert: CurrentValueSubject<String, Never>에 send

#### VC

VC에서 ViewModel.showErrorAlert을 구독하여, 이벤트가 발생할때마다 Alert을 띄우도록 구현했습니다

error handling을 이런식으로 하는게 맞는지 궁금합니다!

### TodoSceneFactory

현재 하나의 Scene에 해당하는 객체들을 모두 하나의 SceneFactory에서 생성하고있습니다.

원래는 각각의 ViewController마다 하나의 Factory를 두려고 했지만, ViewModel 중 Parent, Child ViewModel 끼리의 통신이 필요한 경우나 ChildeViewModel이 Parent로 부터 주입 받아야할 것이 있는 경우에 해당 ViewModel들이 같은 Factory에 있는 것이 더 자연스러울 것 같다고 판단하였습니다.

대안으로 아예 ViewModel, UseCase, Repository 각각의 계층을 생성하는 Factory를 만들어 보려고도 했으나, 이런 경우에 Factory 생성자의 파라미터가 너무 많아진다거나 하는 문제점이 있었습니다.

SceneFactory의 역할을 어떤식으로 나누어주어야 할까요?😭

2022-07-24 18:57 UTC, 1Consumption requested changes
안녕하세요 마이노 두두~
코드가 점점 깔끔해지네요. 👍

코멘트가 중복되는 부분은 생략하고 한군데에만 달았어요. 이부분 참고 부탁드릴게요.

아래는 질문주신 내용 중 코멘트에 달려있지 않은 내용입니다.
------------------------------------------------------ 

[VC에서 ViewModel.showErrorAlert을 구독하여, 이벤트가 발생할때마다 Alert을 띄우도록 구현했습니다
error handling을 이런식으로 하는게 맞는지 궁금합니다!

> 괜찮다고 보는데, 뷰모델의 state를 view가 구독하는 방향은 어떨까요? 이 state에는 viewModel의 모든 output이 들어가는거죠.

궁금한 점이 있으면 언제든 디엠이나 회의실에서 얘기하도록 하죠.

2022-07-24 18:57 UTC, 1Consumption commented on ProjectManager/ProjectManager/Application/DIContainer/SceneFactory/TodoSceneFactory.swift
> +final class TodoSceneFactory {
말씀하신대로 하나의 Factory에서 모든것을 하니까 되게 복잡하고 안읽히네요. 객체의 라이프사이클을 고려해서 factory를 구현해보세요.

2022-07-24 18:57 UTC, 1Consumption commented on ProjectManager/ProjectManager/Application/DIContainer/SceneFactory/TodoSceneFactory.swift
> +    }
items에는 왜 publisher가 들어가나요? 그냥 값을 넘기면 안되나요?
그리고 왜 AnyPublisher인가요? 지금 동작은 CurrecntValueSubject나 Published 프로퍼티가 아니면 안될거 같은데요.

2022-07-24 18:57 UTC, 1Consumption commented on ProjectManager/ProjectManager/Application/DIContainer/TodoSceneDIContainer.swift
> +    }
모든 Coordinator의 dependency가 같은데... 역할이 제대로 안나뉜걸까요?

2022-07-24 18:57 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Repository/TodoHistoryRepository.swift
> +    }
read와 publisher를 반환받는거랑은 조금 다른거같은데요... 네이밍이 이상하다고 생각합니다.

2022-07-24 18:57 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Repository/TodoListRepository.swift
> +        if UserDefaults.standard.object(forKey: "isFirstLogin") != nil {
이런 UserDefaults도 의존성으로 들어가는게 맞아보여요.
테스트를 돌렸을 때 테스트에 의해 앱이 영향을 받으면 안됩니다.

2022-07-24 18:57 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Storages/FirebaseStorage.swift
> +    func backup(_ items: [Todo])
이름이 이상합니다. 백업된 데이터를 받아오는거니까 retrieve~~ 가 되면 좋을거같아요.

2022-07-24 18:57 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Storages/FirebaseStorage.swift
> +    private var cancelBag = Set<AnyCancellable>()
cancellableBag으로 해주세요.

2022-07-24 18:57 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Storages/FirebaseStorage.swift
> +                    .child("todos")
"todos"를 매번 넣지말고 상수로 관리하는건 어떨까요?

2022-07-24 18:57 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Storages/FirebaseStorage.swift
> +    }
계속 말하지만, read라는 메소드 이름이 너무 어색해요. publisher를 반환하는게 어떻게 read인거죠? 차라리 `~~publisher를 반환 한다` 라는 내용의 이름이면 좀 더 명확하겠어요.

2022-07-24 18:57 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Storages/FirebaseStorage.swift
> +    }
매번 새로운 publisher를 만들어서 반환하지말고, `firebaseSubject` 의 value enum이나 struct로 변경해서 내부 프로퍼티나 case를 바꿔서 보내면 어떨까요?

2022-07-24 18:57 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Storages/RealmStorage.swift
> +    }
realmSubject의 Failure로 보내면 어떨까요?

2022-07-24 18:57 UTC, 1Consumption commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/TodoCreate/ViewModel/TodoCreateViewModel.swift
> +    let showErrorAlert = PassthroughSubject<String, Never>()
이름이 조금 어색하다고 느껴져요.

2022-07-25 11:23 UTC, FirstDo commented on ProjectManager/ProjectManager/Data/Storages/FirebaseStorage.swift
> +                    .child("todos")
magic literal들을 private enum 으로 모아서 관리해 주었습니다!
https://github.com/yagom-academy/ios-project-manager/pull/155/commits/1efe8116a4e587d994f4235b7d3c75afc906d929

2022-07-25 11:27 UTC, FirstDo commented on ProjectManager/ProjectManager/Data/Storages/FirebaseStorage.swift
> +    private var cancelBag = Set<AnyCancellable>()
네이밍 변경해 주었습니다

https://github.com/yagom-academy/ios-project-manager/pull/155/commits/4f055302a1cf80b62c771d30a6fdd834cf055939

2022-07-25 11:29 UTC, FirstDo commented on ProjectManager/ProjectManager/Data/Storages/FirebaseStorage.swift
> +    func backup(_ items: [Todo])
해당 매서드는 remoteDB에 데이터를 업로드만 하고있기 때문에 backup이 맞는것 같습니다

2022-07-25 12:02 UTC, FirstDo commented on ProjectManager/ProjectManager/Data/Repository/TodoListRepository.swift
> +        if UserDefaults.standard.object(forKey: "isFirstLogin") != nil {
아 맞네요..!
테스트에 영향이 없게 외부에서 주입해 주는 형태로 바꿨습니다

https://github.com/yagom-academy/ios-project-manager/pull/155/commits/19155426d97065e17409250d552cce43b0e54313

2022-07-25 13:01 UTC, FirstDo commented on ProjectManager/ProjectManager/Presentation/TodoListScenes/TodoDetail/TodoCreate/ViewModel/TodoCreateViewModel.swift
> +    let showErrorAlert = PassthroughSubject<String, Never>()
ViewModel의 Ouput을 말씀하신대로 State로 묶어주었습니다
또한 ~~Event라는 네이밍으로 변경해 주었습니다

https://github.com/yagom-academy/ios-project-manager/pull/155/commits/a25bce9f2d7934265ca8af83bc4c0aa79dd49228

2022-07-25 13:15 UTC, FirstDo commented on ProjectManager/ProjectManager/Data/Repository/TodoHistoryRepository.swift
> +    }
말씀대로 어색한 것 같아 model + Publisher로 네이밍 변경해주었습니다..!

[fcd3db1](https://github.com/yagom-academy/ios-project-manager/pull/155/commits/fcd3db1663bc189a3e24433edc4d8c3023db884a)

2022-07-25 13:16 UTC, FirstDo commented on ProjectManager/ProjectManager/Data/Storages/FirebaseStorage.swift
> +    }
말씀대로 어색한 것 같아 model + Publisher로 네이밍 변경해주었습니다..!

[fcd3db1](https://github.com/yagom-academy/ios-project-manager/pull/155/commits/fcd3db1663bc189a3e24433edc4d8c3023db884a)

2022-07-26 06:30 UTC, FirstDo commented on ProjectManager/ProjectManager/Application/DIContainer/TodoSceneDIContainer.swift
> +    }
각 뷰컨트롤러 별로 DIContainer를 만들어 주었습니다!
그 과정에서 SceneFactory는 의미가 없어져서 (코드가 충분히 잘게 쪼개져서!) 삭제했습니다 :)

https://github.com/yagom-academy/ios-project-manager/pull/155/commits/970129b16f3a1ce226b933337b89cab6328a607e
https://github.com/yagom-academy/ios-project-manager/pull/155/commits/d2fb033dcfc934ed906b876d97bdb696c3233556
https://github.com/yagom-academy/ios-project-manager/pull/155/commits/8f52bc63003be6f4b43e9a28f618e5fd693a386a

2022-07-26 06:31 UTC, FirstDo commented on ProjectManager/ProjectManager/Application/DIContainer/SceneFactory/TodoSceneFactory.swift
> +final class TodoSceneFactory {
말씀대로 각 뷰컨트롤러 별로 DIContainer를 만들어 주었습니다!
그 과정에서 SceneFactory는 의미가 없어져서 (코드가 충분히 잘게 쪼개져서!) 삭제했습니다 :)

https://github.com/yagom-academy/ios-project-manager/pull/155/commits/970129b16f3a1ce226b933337b89cab6328a607e
https://github.com/yagom-academy/ios-project-manager/pull/155/commits/d2fb033dcfc934ed906b876d97bdb696c3233556
https://github.com/yagom-academy/ios-project-manager/pull/155/commits/8f52bc63003be6f4b43e9a28f618e5fd693a386a

2022-07-26 06:50 UTC, FirstDo commented on ProjectManager/ProjectManager/Application/DIContainer/SceneFactory/TodoSceneFactory.swift
> +final class TodoSceneFactory {
밑에 코맨트 달았습니다!
분리하였습니다 :)

2022-07-26 07:56 UTC, FirstDo commented on ProjectManager/ProjectManager/Data/Storages/FirebaseStorage.swift
> +    }
밑의 코맨트와 같습니다!!

2022-07-27 10:44 UTC, 1Consumption commented on ProjectManager/ProjectManager/Data/Repository/TodoHistoryRepository.swift
> +    }
https://www.swiftbysundell.com/tips/computed-properties-vs-methods/
이걸 참고해보세요.

2022-07-27 10:49 UTC, 1Consumption commented
흠... 여전히 read, update, delete를 할 때 퍼블리셔를 반환하네요. 제가 드린 코멘트와는 조금 다른듯 합니다. 이유가 있을까요?

2022-07-28 15:26 UTC, FirstDo commented on ProjectManager/ProjectManager/Data/Repository/TodoHistoryRepository.swift
> +    }
아하... 연산 프로퍼티로 변경해 주었습니다

2022-07-28 15:27 UTC, Mino777 commented
@1Consumption 

말씀해주신 부분들 피드백 반영 완료하였습니다!
감사합니다!

2022-07-31 17:17 UTC, merged