프로젝트 관리 앱 II [STEP 3] Lingo
yagom-academy/ios-project-manager pull request #157
Opened 2022-07-22 04:35 UTC by llingo

안녕하세요 린생! @jungseungyeo
프로젝트 매니저 STEP 3 PR 보냅니다! 잘 부탁드립니다 🙇🏻

## 배경

- Firebase 리모트 서버와 통신하여 동기화
- 로컬 디스크 캐시를 구현하여 네트워크에 연결하지 않아도 기존의 데이터를 사용자에게 표시
    - 네트워크에 연결되어있지 않으면 아이콘으로 알림
    - 네트워크에 접속하면 서버와 변경사항을 자동 동기화합니다
- 화면 왼쪽 위의 ‘History’ 버튼을 선택하면 변경 내역을 팝오버로 표시
    - 추가/이동/삭제/수정

위 요구사항을 만족시킬 수 있도록 진행했습니다.

## 작업 내용

**Firebase 리모트 서버와 통신하여 동기화**
앱을 삭제하고 재설치했을 때 UserDefaults의 "IsAppRunningFirstTime" 키에 대한 값이 없다면 Firebase Realtime Database에서 데이터를 가져온 후 Local 코어 데이터와 동기화를 진행하고 값이 있다면 Local의 데이터를 Firebase Realtime Database와 동기화를 하도록 구현했습니다.

<img width="600" src="https://i.imgur.com/547DAOO.png"/> <br/>

**로컬 디스크 캐시를 구현하여 네트워크에 연결하지 않아도 기존의 데이터를 사용자에게 표시**

Core Data를 사용하여 로컬 디스트 캐시를 구현하여 네트워크에 연결하지 않더라도 사용자에게 표시되도록 했습니다. 네트워크에 연결되면 로컬 디스크의 데이터를 원격 DB에 동기화하도록 했습니다.

**네트워크에 연결되어있지 않으면 아이콘으로 알림**

First-Party로 제공되는 NWPathMonitor를 Rx로 Extension하여 기기의 네트워크 상태에 따라 아이콘이 변경되도록 구현했습니다.

<img width="500" src="https://i.imgur.com/P2raPEt.png"/> <br/>

<img width="600" src="https://i.imgur.com/VQTmrna.png"/> <br/>

**화면 왼쪽 위의 ‘History’ 버튼을 선택하면 변경 내역을 팝오버로 표시 (추가/이동/삭제/수정)**

히스토리 팝오버를 띄우는 CardHistoryViewController에 tableView를 생성하고 데이터를 외부에서 받도록 구현했습니다.

<img width="600" src="https://i.imgur.com/qzAKEVj.png"/> <br/>

PopOverable 프로토콜의 기본 구현을 활용하여 띄워줄 수 있도록 하였으며 아래와 같이 사용할 수 있도록 구현했습니다.

<img width="600" src="https://i.imgur.com/uIlMSbt.png"/> <br/>

## 리뷰노트

> 고민한 점 및 조언 받고싶은 점

### DB - Repository - UseCase - ViewModel - ViewController 데이터 Flow에 대해
이번 프로젝트 매니저 II에서 I과 달리 계층을 늘리는 과정에서 데이터 Flow를 ViewController에서 Disposed 되어야할까? UseCase에서 스트림을 한번 끊어야 할까? 에 대해 고민이 있었습니다.

기본적으로 내부에서 외부를 모르도록 설계하는 것이 클린 아키텍쳐가 지향하는 구조이며 <U>단방향 데이터 흐름</U>을 가져감으로써 아래와 같은 장점을 얻을 수 있다고 생각합니다.

1. 데이터가 한 방향으로만 전달되기 때문에 문제가 발생했을때 어디서 디버깅하기 좋다.
2. 전체적인 앱의 실행 흐름을 파악하기 쉽다.

<img width="500" src="https://i.imgur.com/tbvoj3B.png"/>

[그림 출처](https://medium.com/tiendeo-tech/ios-rxswift-clean-architecture-d7e9eaa60ba) / [참고 자료: Medium_Clean Architecture](https://medium.com/@jonas.schaude/developing-ios-applications-with-uncle-bobs-clean-architecture-572084853cdc)

따라서, View에서 요청을 하면 DB까지 요청 메시지가 전달되고 반환되는 응답 스트림이 끊어지지 않도록 구현했습니다.

### DI Container 
계층이 많아지고 주입해줘야하는 객체가 늘어남에 따라 의존성 관리하는 것이 어려워질 것 같다는 생각이 들었습니다.

<img width="500" src="https://i.imgur.com/vunI3Q0.png"/> <br/>

사용할 때마다 UseCase 인스턴스 하나를 생성하기 위해 위와 같이 작성하다보면 Coordinator 코드도 비대해질 것 같습니다. 이를 해결할 방법으로 DIContainer를 통한 의존성 관리를 고려했고 Swinject, PureDI 등 많은 DI 라이브러리가 있지만 직접 구현해보자고 생각했습니다.

직접 구현할 DIContainer의 주요 목표 기능은

1. 필요할 때 생성할 수 있도록 지연 생성을 지원해야한다.
2. 중복 생성되지 않도록 캐싱을 지원해야한다.
3. 하위 객체부터 상위 객체로 조합하며 생성되어야한다. (IoC)

**1. 필요할 때 생성할 수 있도록 지연 생성을 지원해야한다.**
DIContainer가 필요한 인스턴스를 처음부터 생성하고 가지고 있다면 메모리를 낭비하게되기 때문에 사용할 때 생성될 수 있도록 해야합니다. 지연 생성을 구현하기 위해 <U>클로저의 지연 평가</U>를 활용했습니다.

**2. 중복 생성되지 않도록 캐싱을 지원해야한다.**
이미 생성된 인스턴스를 다시 생성하지 않도록하여 메모리 낭비를 줄여야합니다.

**3. 하위 객체부터 상위 객체로 조합하며 생성되어야한다.**
아래의 그림과 같이 Storage부터 생성되고 ViewController까지 역순으로 생성되어야합니다.

<img width="800" src="https://i.imgur.com/T1hH3Tg.png"/> <br/>

위의 요구조건을 만족하도록 아래와 같이 구현해보았습니다.

<img width="500" src="https://i.imgur.com/BxyOmeB.png"/> <br/>

하지만, Coordinator와 DetailViewController와 같이 추가적인 데이터(ex. Cell을 클릭했을 때의 Card 데이터)가 필요한 곳에서의 한계가 있어 실제로 적용하진 못했지만 🥲 STEP 4에서 개선하여 적용할 수 있도록 도전하겠습니다!

## 스크린샷 및 영상

|[메인 화면] 히스토리 I|[메인 화면] 히스토리 II|
|:---:|:---:|
|<img width="400" src="https://i.imgur.com/SIyPRVM.gif"/>|<img width="400" src="https://i.imgur.com/RZ3feL2.gif"/>|

|[메인 화면] 히스토리 III|[메인 화면] Core Data 캐시|
|:---:|:---:|
|<img width="400" src="https://i.imgur.com/Uj8K0rB.gif"/>|<img width="400" src="https://i.imgur.com/2rYcjQd.gif"/>|

|[메인 화면] Firebase 동기화 - 앱 재설치|[메인 화면] 네트워크 연결 상태|
|:---:|:---:|
|<img width="400" src="https://i.imgur.com/dSzEzXE.gif"/>|<img width="400" src="https://i.imgur.com/porBnvJ.gif"/>|

2022-07-22 15:33 UTC, jungseungyeo requested changes
링고 고생하셨습니다 :) 

### DB - Repository - UseCase - ViewModel - ViewController 데이터 Flow에 대해

구조를 너무 잘 잡아주셔서 좋았습니다. :) 단방향 흐름은 아닌거 같아요 결과적으로 input을 받아서 output으로 이벤트를 받기 때문에 양방향 통신에 더욱 가까운거 같아요. 

### DI Container

코드가 너무 좋습니다. 현재 적용이 안되어 있는게 아쉽네요. 다음 스텝에서 적용을 해주시면 좋을거같아요 :) 
근데 코드를 보면 deinit이 안 불리수도 있을거같네요. container에서 딕션너리에서 가지고 있어 이런 방식이라면 메모리 릭이 발생할수있을거같아요. 만드면서 한번 확인 해주세요 :) 

링고를 코드를 보면서 잘 못 사용하는 코드를 없는거 같아서 코멘트가 많지는 않았는데요. 구조적으로는 몇가지 수정이 필요해보여요.

1. 네트워크 동기화
- 이거는 코멘트에도 달았지만 맨 처음에만 하면 안될 거같아요. 또 캐시를 가져오는 것이 앱이 최초 실행이냐가 아니라. 캐시가 있는지 없는지로 판단해야될거같아요.

2. 또 Core객체와 realtime객체에서 프로토콜을 의존하는게 아닌 객체를 의존하고 있어요 이렇게 되면 클린아키텍쳐의 의도가 깨지는거같아요. 이 부분도 수정하면 좋을거같아요.

크게 두가지 정도인거 같아요. 
코드부분에서는 크게 수정 할 부분을 찾지는 못했는데요. 혹시 코드레벨에서 궁금한 점이 있으면 알려주세요 :) 
감사합니다 :)

2022-07-22 15:33 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Presentation/MainScene/ViewController/CardHistoryViewController.swift
> +  let histories = BehaviorRelay<[CardHistoryViewModelItem]>(value: [])
CardHistoryViewModelItem 이것도 주입받아서 24번 라인을 private으로 만들수있을거같아요.

2022-07-22 15:33 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Presentation/MainScene/ViewController/CardListViewController.swift
> +    viewModel.fetchCards()
이놈이 Observable로 되어야 하는 이유가 있나요? 크게 이벤트를 기다려야하는 이유도 없는거 같고 스트림을 연결하는 부분도 없는거같네요

2022-07-22 15:33 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Data/Repository/DefaultCardRepository.swift
> +      UserDefaults.standard.set(false, forKey: Settings.firstTimeRunningCheckingKey)
UserDefaults로 값이 있는 경우 서버로 fetch를 안하면 서버는 최초 한번만 하는거 같네요 ㅎㅎ

2022-07-22 15:33 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Data/Repository/DefaultCardRepository.swift
> +      UserDefaults.standard.set(false, forKey: Settings.firstTimeRunningCheckingKey)
캐시 정책은 회사마다 다르긴하나 대부분은 한번만 요청하는 경우는 잘 없는거 같아요. 

캐시 -> 먼저 사용자에게 보여줌 -> 서버요청 -> 최신 정보를 가지고 reload를 함 -> 캐시 저장

위와 같은 방식으로 주로 사용하는 편입니다. 토스를 예를 들수 있을거같아요. 
토스를 집인하면 먼저 잔액 정보를 보여주지만 시간이 좀 지나면 업데이트가 되는 걸 수 있을거예요 :) 

또 최초진입을 확인용으로 UserDefaults를 사용하는 것 보다는 캐시가 있냐없냐로 하는게 현재 로직에서는 더 맞을거같네요

2022-07-22 15:33 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Data/Storage/Service/DefaultCardCoreDataService.swift
> +  init(storage: CoreDataStorage = .shared) {
이게 객체로 받는다면 DI를 하는 의미가 없겠죠? 객체를 의존하지 말고 protocol을 의존하면 좋을거같네요

2022-07-22 15:33 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Data/Network/Service/DefaultRealtimeDatabaseService.swift
> +  init(database: DatabaseReference = Database.database().reference()) {
여기도 객체를 의존하여 주입을 받는다면 안되겠죠? protocol을 의존해야 될 거같아요.

2022-07-23 10:16 UTC, llingo commented on ProjectManager/ProjectManager/Presentation/MainScene/ViewController/CardHistoryViewController.swift
> +  let histories = BehaviorRelay<[CardHistoryViewModelItem]>(value: [])
```swift
// CardHistoryViewController.swift

private let disposeBag = DisposeBag()
private let histories = BehaviorRelay<[CardHistoryViewModelItem]>(value: [])

init(histories: [CardHistoryViewModelItem]) {
  self.histories.accept(histories)
  super.init(nibName: nil, bundle: nil)
  configureSubviews()
  configureLayouts()
}
```
위의 코드와 같이 private로 변경하고 생성자로 주입받도록 했습니다!

2022-07-25 08:00 UTC, seu0313 commented on ProjectManager/ProjectManager/Data/Storage/Service/DefaultCardCoreDataService.swift
> +  init(storage: CoreDataStorage = .shared) {
CoreDataStoragable 프로토콜을 추가하여 변경했습니다!

2022-07-25 08:13 UTC, llingo commented on ProjectManager/ProjectManager/Data/Network/Service/DefaultRealtimeDatabaseService.swift
> +  init(database: DatabaseReference = Database.database().reference()) {
Firebase의 DatabaseReference를 FirebaseDatabaseService 프로토콜을 채택하고
Repository가 프로토콜을 의존하도록 변경했습니다.

> DefaultRealtimeDatabaseRepository (구. DefaultRealtimeDatabaseService)

2022-07-25 12:19 UTC, llingo commented on ProjectManager/ProjectManager/Presentation/MainScene/ViewController/CardListViewController.swift
> +    viewModel.fetchCards()
<img width="500" src="https://user-images.githubusercontent.com/94151993/180775819-b99d6d50-158c-4069-ac9f-c45efe73accb.gif"/>

동기화 완료시 표시되는 알림을 추가하여 역할을 부여했습니다!

2022-07-25 16:53 UTC, llingo commented on ProjectManager/ProjectManager/Data/Repository/DefaultCardRepository.swift
> +      UserDefaults.standard.set(false, forKey: Settings.firstTimeRunningCheckingKey)
|동기화 I|동기화 II|
|:---:|:---:|
|![동기화1](https://user-images.githubusercontent.com/94151993/180831253-00d4ed3b-b973-4d83-ab3f-c74700bbc0f3.gif)|![동기화 2](https://user-images.githubusercontent.com/94151993/180831280-d7bdc5b8-77c8-4542-9c0f-bbe1b3c4311d.gif)|

캐시 정책을 변경하여
`사용자 접근 -> 캐시를 먼저 보여줌 -> 서버 요청 -> 서버의 데이터로 갱신 -> 캐시 저장`이 되도록 변경했습니다.

토스를 사용하지 않아서 처음에는 긴가민가 했었는데 사용하던 뱅크샐러드 앱의 갱신 과정을 본 후
말씀의 의미를 이해했고 캐시 정책을 변경했습니다!

2022-07-26 00:30 UTC, jungseungyeo approved these changes
링고 고생하셨습니다 :) 

1. 앱 전반적으로 Data, Domain, UseCase, Presentation의 모든 영역에서 RxSwift가 적용되어 있는 상태입니다.비즈니스 로직은 앱의 중심이며 외부 라이브러리의 영향을 받으면 좋지 않을 것 같다는 생각이 들었습니다.
특히 RxSwift는 서드파티 라이브러리이고 현재 비즈니스 로직들이 라이브러리를 의존하고 있는 문제가 있는 것 같습니다.

`당연히 의존을 안할 수 있으면 안하는 것이 좋습니다. 하지만 rxswift 특성상 그러기는 쉽지 않죠? 따라서 라이브러리를 쓸 때 의존의 범위가 광범위 해지는 효과가 있습니다. 특히 rxswift의 경우 그렇게 되죠. 그래서 라이브러리를 쉽게 사용하는 것은 좋지 않습니다. 현재 코드에서 꼭 걷어내야 되지는 않는거 같아요. rxswift를 쓰는 것도 이런 부분을 쉽게 하기 위해서 사용는 것이기때문에 사용할 수 있으면 사용하는게 저는 좋다고 봅니다. 하지만 라이브러리의 의존이 되는 관점에서는 좋지는 않다는 의견은 당연해보입니다. ㅠ`

2.기존 Service 코드에서 하던 역할을 Repository로 변경하였습니다.

`넵 좋습니다. 이렇게 말한 이유는 collectionView를 예를 들 수 있을거같아요. collectionView의 delegate는 기본적으로 UICollectionViewDelegate를 사용하죠. 하지만 이것 도 UIScrollViewDelegate를 체택하고 있어요. 이러한 느낌으로 점차적으로 기능을 확대할때 사용하면 정말 좋은 방법이에요. :) 제가 의도한 방향으로 잘 작성이 된 거 같아요 :)`

링고 고생하셨습니다. 다음 스텝 진행해도 될거같아요 :)

2022-07-26 00:30 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Data/Repository/DefaultRealtimeDatabaseRepository.swift
> +  init(service: FirebaseDatabaseService) {
좋습니다 :) 프로토콜을 의존하게 수정되었네요 ㅎㅎ

2022-07-26 00:30 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Data/Repository/DefaultLocalDatabaseRepository.swift
> +final class DefaultLocalDatabaseRepository: LocalDatabaseRepository {
좋습니다 :)

2022-07-26 00:30 UTC, merged