[STEP 1] Jay, James, Ian
yagom-academy/ios-project-manager pull request #16
Opened 2021-07-13 09:04 UTC by LeeSungNo-ian

안녕하세요 Cory! 😁  @corykim0829 
날씨가 많이 더워졌네요.. 이럴 때 일수록 냉방병 조심하셔야 하는거 아시죠?!
첫번째 PR이 너무 늦었네요.. 이것 저것 공부하면서 Step1을 진행했더니 다양한 경험을 해본 것 같아요 !
잘 부탁드리겠습니다 !

---

**TableView 내부의 데이터 이동**

![Simulator Screen Recording - iPad Pro (12 9-inch) (5th generation) - 2021-07-13 at 17 53 36](https://user-images.githubusercontent.com/78950704/125423587-dff039b0-dd44-4083-9543-dc026fa896ad.gif)

**TableView 간의 데이터 이동**

![Simulator Screen Recording - iPad Pro (12 9-inch) (5th generation) - 2021-07-13 at 17 54 06](https://user-images.githubusercontent.com/78950704/125423659-9cdaad00-89a6-42f3-a4fd-10f6d2d208d8.gif)

**[프로젝트 구현 내용]**

- 각 셀에는 [제목 / 설명 / 기한] 이 표시됩니다.
    - 서버팀과 2번의 조율을 한 후 받은 JSON Data를 Decode 작업을 통해 각 셀에 구현할 수 있도록 구현했습니다.
- TODO와 DOING의 기한에 지난 날짜가 있으면 빨간색으로 표시합니다.
    - DateFormatter 를 사용하여 현재 한국 시간을 불러온 뒤, JSON Data의 날짜와 비교하여 날짜가 지난 Date는 빨간색으로 처리하였습니다.
- 할일은 잡아끌어(드래그 앤 드롭)서 다른 영역으로 이동할 수 있습니다.
    - Drag, Drop Delegate 를 선언한 후 메소드를 통해 드래그 앤 드롭을 활성화 하였습니다.
- 기한 날짜는 사용자의 지역 포멧에 맞게 표현해야합니다.
    - DateFormatter 를 사용하여 설정했습니다.
<br>

**[프로젝트 미구현 내용]**

- 오른쪽 위의 + 버튼을 선택하면 새로운 할 일을 추가하는 작성양식이 표시됩니다.
- 할일을 터치하면 상세내용을 표시합니다.
- 셀을 왼쪽으로 스와이프하여 삭제 메뉴를 표시하고, 끝까지 스와이프하거나 삭제 메뉴를 선택하면 해당 할 일을 삭제합니다.
<br>

**[코드 구현]**

- `TaskTableViewDataSource` 프로토콜을 생성하고, 이 프로토콜은 `UITableViewDataSource` 를 상속받습니다.

```swift
protocol TaskTableViewDataSource: UITableViewDataSource {  
    
}
```
<br>
- 클래스 `TaskDataSource` 는 `TaskTableViewDataSource` 프로토콜을 채택하였습니다.

```swift
final class TaskDataSource: NSObject, TaskTableViewDataSource {

}
```
<br>
- View Controller에서 `datasource` 는 TableView의 셀과 데이터를 관리합니다.

```swift
private var datasource: TaskTableViewDataSource?
```
<br>
- `datasource` 는 View Controller에서 초기화 될 때 테이블 뷰를 주입받습니다.

```swift
override func viewDidLoad() {
    datasource = TaskDataSource(toDoTableView: toDoTableView, 
		doingTableView: doingTableView, 
		doneTableView: doneTableView)
}
```
<br>
<br>

**[조언을 얻고 싶은 부분]**

- 컨테이너 뷰를 사용하는게 더 좋은 방법인지 궁금합니다.

처음 프로젝트를 접할 때, ViewController 를 3개 만들고 각각의 ViewController 에 3개의 DataSource 를 넣으려고 했는데 자원 낭비라고 생각이 됐습니다. 
그래서 1개의 ViewController 에 3개의 TableView를 생성하여 DataSource Drag & Drop 구현을 하였더니, 분기처리가 많아져서 코드가 복잡해진다는 단점을 발견했습니다. 
이런 방식과 별개로 컨테이너 뷰 를 사용하여 접근하는 방법도 있다고 들었는데, 어떤 방식이 더 간결하고, 성능이 좋은 코드인지 Cory 의 생각이 궁금합니다 !

- 네트워크와의 동기화 시점에 대해 궁금합니다.

저희가 생각하기에는 네트워트 동기화 시점은 앱이 시작할 때(서버로부터 데이터를 받는 것), 앱을 종료시킬 때(서버로 데이터를 보내는 것) 때 동기화를 해야된다고 생각합니다! Cory의 생각으로는 어느 시점에 데이터를 보내는게 바람직한 방법인지 궁금합니다..!
걱정되는 부분은 만약 유저가 앱을 강제 종료를 하거나, 배터리가 부족하여 갑작스럽게 앱이 종료 됐을 때 데이터 손실이 있을 것 같다 라는 생각이 들었습니다. 이런 맥락에서 저희가 생각하는 동기화 시점이 적절하지 않을 수도 있을까요? 다른 방법으로는 동기화 버튼을 하나 만들어서 서버와 데이터를 동기화 해볼까 생각도 해봤습니다..!

- 지운 데이터 관리를 어떻게 해야하는지 궁금합니다.

추후에 유저가 지웠던 TaskData 를 `Undo` 버튼을 통해서 다시 불러 오게 하기 위해서는 지운 데이터를 담을 그릇이 필요하다고 생각이 들었습니다. 지운 데이터들을 담을 수 있는 코어 데이터를 사용해볼까? 라는 생각도 했는데요. 코어데이터 말고 다른 접근 방식이 있을 수 있는지, 다른 더 좋은 대안이 있을지 궁금합니다..!

2021-07-14 17:59 UTC, corykim0829 requested changes
🎉 수고하셨습니다 🎉

Drag & Drop을 너무 깔끔하게 잘 구현하셨네요 👍
꼭 고쳤으면 하는 부분은 Cell을 세개를 구현했는데, 하나로만 재사용을 해도 됩니다. 이 부분은 UITableView의 재사용 원리를 조금 더 알아보면 알 수 있을 것 같아요.

조금만 더 화이팅입니다!! 💪

> - 컨테이너 뷰를 사용하는게 더 좋은 방법인지 궁금합니다.
처음 프로젝트를 접할 때, ViewController 를 3개 만들고 각각의 ViewController 에 3개의 DataSource 를 넣으려고 했는데 자원 낭비라고 생각이 됐습니다.
그래서 1개의 ViewController 에 3개의 TableView를 생성하여 DataSource Drag & Drop 구현을 하였더니, 분기처리가 많아져서 코드가 복잡해진다는 단점을 발견했습니다.
이런 방식과 별개로 컨테이너 뷰 를 사용하여 접근하는 방법도 있다고 들었는데, 어떤 방식이 더 간결하고, 성능이 좋은 코드인지 Cory 의 생각이 궁금합니다 !

➡️ 정답은 없습니다. 상황에 맞게 사용하는 게 맞죠. 지금은 잘 고민해서 dataSource를 하나로 사용해서 관리하는 방법을 사용했는데 컨테이너뷰 보다는 더 적합한 것 같아요. 테이블뷰가 세개이기 때문에 당연히 분기처리는 당연히 감수해야하는 부분입니다.

> - 네트워크와의 동기화 시점에 대해 궁금합니다.
저희가 생각하기에는 네트워트 동기화 시점은 앱이 시작할 때(서버로부터 데이터를 받는 것), 앱을 종료시킬 때(서버로 데이터를 보내는 것) 때 동기화를 해야된다고 생각합니다! Cory의 생각으로는 어느 시점에 데이터를 보내는게 바람직한 방법인지 궁금합니다..!
걱정되는 부분은 만약 유저가 앱을 강제 종료를 하거나, 배터리가 부족하여 갑작스럽게 앱이 종료 됐을 때 데이터 손실이 있을 것 같다 라는 생각이 들었습니다. 이런 맥락에서 저희가 생각하는 동기화 시점이 적절하지 않을 수도 있을까요? 다른 방법으로는 동기화 버튼을 하나 만들어서 서버와 데이터를 동기화 해볼까 생각도 해봤습니다..! 

➡️ 동기화 버튼은 사용자가 원할 때 동기화를 할 수 있다는 장점이 있죠, 가장 좋은 방법은 서버에 변동이 있을 때마다 이를 감지해서 동기화 시키는게 좋은데, 아직 이 부분은 처리하기 어렵기 때문에 특정 시간마다 업데이트 하도록 하는 것도 방법인 것 같아요.
만약 앱을 시작할 때 동기화를 한다면, `유저가 앱을 강제 종료를 하거나, 배터리가 부족하여 갑작스럽게 앱이 종료 됐을 때` 의 상황에도 다시 실행시킬 때 동기화가 되긴해서 괜찮을 것 같기는 합니다. 앱 실행, 종료시 동기화해주는 것처럼 특정 상황에서 클라이언트 단에서 동기화 처리가 필요한 상황은 조금 더 고민해보면 좋을 것 같아요. `앱을 종료시킬 때(서버로 데이터를 보내는 것)`에서 서버로 데이터를 보내는 것은 이해가 잘 안되네요

> - 지운 데이터 관리를 어떻게 해야하는지 궁금합니다.
추후에 유저가 지웠던 TaskData 를 `Undo` 버튼을 통해서 다시 불러 오게 하기 위해서는 지운 데이터를 담을 그릇이 필요하다고 생각이 들었습니다. 지운 데이터들을 담을 수 있는 코어 데이터를 사용해볼까? 라는 생각도 했는데요. 코어데이터 말고 다른 접근 방식이 있을 수 있는지, 다른 더 좋은 대안이 있을지 궁금합니다..!

➡️ 물론 CoreData나 아카이빙, UserDefault와 같은 다른 방법을 사용해서 디바이스 내에 저장할 수도 있지만, 결국에는 서버에 저장되어야하는 부분 같아요. 서버랑 이야기를 해서 고민해보고 구현을 어떻게 할지 결정하면 될 것 같아요.

2021-07-15 05:35 UTC, helloworldjay commented on ProjectManager/ProjectManager/Model/TaskDataSource.swift
> +    }
삭제 했습니다! :)

2021-07-15 05:36 UTC, helloworldjay commented on ProjectManager/ProjectManager/Model/TaskDataSource.swift
> +    func moveTask(at sourceIndexPath: IndexPath, to destinationIndexPath: IndexPath, in tableView: UITableView) {
from으로 변경했습니다!

2021-07-15 05:41 UTC, helloworldjay commented on ProjectManager/ProjectManager/Controller/ViewController.swift
> +            return datasource?.dragItem(taskType: .done, for: indexPath) ?? []
함수는 외부로 빼고 switch문을 통해 taskType만 결정하는 구조로 리팩토링 했습니다. default에서 taskType에 대한 처리가 애매한데 이 부분을 우선 .todo로 처리했습니다. 더 좋은 방법이 있을까요?

2021-07-15 06:01 UTC, helloworldjay commented on ProjectManager/ProjectManager/Controller/ViewController.swift
> +        return 60
정리 했습니다!

2021-07-15 06:10 UTC, helloworldjay commented on ProjectManager/ProjectManager/Model/TaskDataSource.swift
> +        self.doneList = ProjectTaskType.done.model
말씀해주신 부분을 저희는 2가지로 해석했습니다.
1. enum 타입이 datasource 외부에 존재하므로 다른 객체에서 datasource가 가져야하는 정보를 fetching한다.
2. enum이라는 열거형이 데이터를 fetch하는 로직을 갖는 구조가 잘못되었다(enum은 타입을 갖고 fetch는 datasource 내부에서 해야한다).

그래서 해결 방법을 생각해보면
1. ProjectTaskType이라는 enum을 dataSource안에 넣는다.
2. ProjectTaskType이 갖는 func taskArrayFromAsset을 dataSource가 갖게 한다.
입니다. 
혹시 말씀해 주신 부분이 어떤 접근에 가까운 것인가요? 아니면 전혀 다른 방향인가요?

2021-07-15 06:18 UTC, helloworldjay commented on ProjectManager/ProjectManager/Model/TaskDataSource.swift
> +    private weak var doneTableView: UITableView!
저희가 이해하기로는 tableView가 단순히 구분자로서만 사용되는 것이 아니라 실제로 tableView로서 역할이 필요해서(예를 들어 moveTask 메소드에서 tableView.deleteRows) 세가지로 정의한 것인데 혹시 조금 더 힌트를 주실 수 있을까요?

2021-07-15 06:24 UTC, helloworldjay commented on ProjectManager/ProjectManager/Model/TaskDataSource.swift
> +final class TaskDataSource: NSObject, TaskTableViewDataSource {
DataSource가 필요한 데이터를 직접 관리하는 것이 조금 더 객체지향적이라고 생각했습니다. 만약에 ViewController에서 배열이 존재하는 객체에 접근하게 되면 접근하는 것에 필요한 메소드들이 추가로 필요할 것이기 때문에 비효율적인 측면이 존재한다고 생각했습니다. 그래서 생각한 대안이 데이터소스라는 커스텀 클래스를 만들고 그 데이터소스에 필요한 데이터를 배열로 관리하고 그 데이터가 업데이트되면 바로바로 셀에 적용할 수 있게 설계해보았습니다. 제 이유는 이런데 cory는 혹시 다른 관점을 갖고 계시나요?

2021-07-15 06:25 UTC, helloworldjay commented on ProjectManager/ProjectManager/Model/TaskDataSource.swift
> +// MARK: - ParsingModel
수정했습니다!

2021-07-15 06:26 UTC, helloworldjay commented on ProjectManager/ProjectManager/Model/Header.swift
> +class Header: UITableViewHeaderFooterView {
수정했습니다! 좋은 추천 감사합니다 :)

2021-07-18 07:10 UTC, corykim0829 requested changes

2021-07-18 07:10 UTC, corykim0829 commented on ProjectManager/ProjectManager/Model/TaskDataSource.swift
> +    private weak var doneTableView: UITableView!
그 동작은 tableView면 다 가능한 기능이니까 moveTask 함수에서 넘어오는 tableView로도 충분히 처리가 가능해보이네요! 구분만 다른 방식으로 하면 좋겠다는 말이였습니다!

2021-07-18 07:10 UTC, corykim0829 commented on ProjectManager/ProjectManager/Model/TaskDataSource.swift
> +        self.doneList = ProjectTaskType.done.model
enum을 따로 두어서 초기 데이터를 가져오는게 조금 어색해보여서 말씀 드렸습니다!
dataSource - enum 안에서 초기 데이터를 생성하고 있는데, dataSource가 초기 데이터를 외부에서 넘겨받을 수 있는 구조가 되면 추후 기능 구현을 생각했을 때에도 더 편할 것 같네요!

2021-08-25 08:24 UTC, closed without merging