프로젝트 관리 앱 [STEP3-1] 사파리
yagom-academy/ios-project-manager pull request #161
Opened 2022-07-26 05:12 UTC by saafaaari

# 프로젝트 관리 앱 [STEP3-1]
@TTOzzi
안녕하세요 또치!
STEP3-1 PR 입니다.
말씀드린 기한보다 늦게 보내 죄송합니다.
잘부탁드립니다.

## 구현 사항

### History 화면 구현

![](https://i.imgur.com/8n7BAQQ.png)

추가, 삭제, 이동에 대한 변경사항을 볼 수 있는 History View를 구현하였습니다. History의 데이터는 Realm을 활용하여 로컬에만 저장하였습니다. 때문에 앱을 삭제 후 다시 다운받는다면, 해당 기록들은 삭제되도록 하였습니다.

### Firebase를 활용한 BackUp Storage 구현

![](https://i.imgur.com/au7UNRG.gif)

위와 같이 앱이 백그라운드 상태로 진입할때 Realm의 데이터를 Firebase에 저장하도록 하였습니다. 

백업하기 전 firebase의 모든 데이터를 지우고, realm의 데이터를 저장하는 구조 입니다.

로드는 `UserDefaults`를 이용하여 앱이 다운되고 첫 실행때만 firebase의 데이터를 가져오도록 구현하였습니다.

```swift
private var isUser: Bool {
    if UserDefaults.standard.bool(forKey: "isUser") {
        return true
    } else {
        UserDefaults.standard.set(true, forKey: "isUser")
        return false
    }
}

private func upLoad() {
    guard isUser else {
        backUpStorage.allRead()
            .subscribe { [weak self] items in
                items.forEach { [weak self] item in
                    self?.storage.create(to: item)
                }
            } onFailure: { [weak self] _ in
                self?.storage.errorObserver.accept(TodoError.backUpError)
            }.disposed(by: bag)
        return
    }
}
```

### 그외 변경사항

1. coordinator를 viewController가 약한참조로 가지고 있도록 수정하였습니다. 때문에 뷰컨 마다 프로토콜을 coordinator의 메서드를 분리하였습니다.

2. UseCase 메서드를 좀더 세분화하였습니다. UseCase의 메서드를 좀더 사용자에게 제공되는 기능에 초점을 맞춰 분리하였고, 날짜를 체크하는 등의 로직은 viewModel로 이동하였습니다.

3. dateFormatter를 viewModel이 가지도록 하였습니다. 하지만, 
    ```swift
    TodoCellContent(entity: item,
                    isPast: checkDeadline(time: item.deadlineAt),
                    dateFormatter: dateFormatter)
    ```
    생성자가 이러한 식으로 되어 가독성에 문제가 있을까? 고민됩니다.
    
    
## 조언받고 싶은 부분

### Repository UIKit import 문제

위에서 언급했다 시피 firebase에 데이터가 저장되는 시점은 앱이 백그라운드 상태로 진입시 입니다. 이때문에 `TodoListRepository`에 `UIApplication` 타입이 사용되었고, 결과적으로 `UIKit`이 import 되었습니다. 근데 이것이 문제가 될 수 있는지 궁금합니다.

### 에러처리에 대해서

Realm을 사용하면서 에러처리 기능을 구현하였습니다. 
가장 먼저 생각난 에러처리 방법은 

```
func delete(index: Int) -> Completable {
    return Completable.create { [weak self] completable in
        do {
            try self?.realm?.write({
                guard let items = self?.items else { return }
                self?.realm?.delete(items[index])
                self?.storege.onNext(items.map { $0.toTodoModel() })
            })
            completable(.completed)
            return Disposables.create()
        } catch {
            completable(.error(error))
            return Disposables.create()
        }
    }
}
```
위 처럼 `Completable`를 반환하여 해당 viewModel에서 처리하는 방법이였습니다. 

두번째 방법은 

```swift
let errorObserver: PublishRelay<TodoError> = PublishRelay()

func delete(index: Int) {
    do {
        try realm?.write({
            guard let items = items else { return }
            realm?.delete(items[index])
            storage.onNext(items.map { $0.toHistory() })
        })
    } catch {
        errorObserver.accept(TodoError.historySyncError)
    }
}
```
두번째 방법은 `PublishRelay`를 활용하여 계속 에러를 던지는 것입니다. 

결과적으로 두번째 방법을 선택했는데 이유는 모든 에러를 `TodoListViewController`에서 처리해주고 싶기 때문이였습니다. 

또치의 생각은 어떠신가요??

### Realm, Firebase를 위한 Model의 폴더 위치

Realm과 Firebase를 사용하다 보니 저장에 용의하게 `TodoModel`이라는 타입을 매핑할 수 있는 `TodoRealmEntity`, `TodoFirebaseEntity` 같은 타입을 구현하게 되었습니다. 

```swift
//  HistoryEntity+Realm.swift
final class TodoRealmEntity: Object {
    @Persisted private var title: String?
    @Persisted private var body: String?
    @Persisted private var deadlineAt: Date
    @Persisted private var state: String
    @Persisted(primaryKey: true) var id: UUID
    // ..중략
}
```

때문에 위와같은 타입들을 어디에 위치시켜야 할지 고민이 되었습니다. Domain/Entities 인지 Data에 위치 시켜야할지...궁금합니다.

일단은 Domain은 앱에 순수한 타입과 로직이 들어가야한다는 생각에 Data에 위치 시켰습니다.

2022-07-27 15:21 UTC, TTOzzi requested changes
안녕하세요 사파리!
작업량이 상당해서 리뷰가 늦어졌네요.. 죄송합니다 😓 
PR 내용의 조언 받고 싶은 부분과 코드 보고 코멘트 남겨뒀어요.
저도 제 생각을 코멘트로 남기는 것일 뿐이라 보고 이해하기 어려운 부분이 있다면 편하게 말씀해주세요 🙏 
고생하셨습니다! 🙇‍♂️ 

### Repository UIKit import 문제

> 위에서 언급했다 시피 firebase에 데이터가 저장되는 시점은 앱이 백그라운드 상태로 진입시 입니다. 이때문에 `TodoListRepository`에 `UIApplication` 타입이 사용되었고, 결과적으로 `UIKit`이 import 되었습니다. 근데 이것이 문제가 될 수 있는지 궁금합니다.

백그라운드 진입 시점을 잡기 위해선 `didEnterBackgroundNotification` 를 사용해야 하니 어쩔 수 없는 부분이라 문제가 되진 않을 것 같습니다 :thinking:

### 에러처리에 대해서

> 결과적으로 두번째 방법을 선택했는데 이유는 모든 에러를 `TodoListViewController`에서 처리해주고 싶기 때문이였습니다.

코멘트로도 남기긴 했는데, 모든 에러를 `TodoListViewController` 에서 처리해줌으로 얻을 수 있는 이점이 어떤 게 있는지 궁금해요.
개발의 생산성(편의성)도 중요하지만, 저희는 사용자가 직접 사용하는 앱을 구현하는 만큼 사용자 경험도 중요합니다.
모든 에러를 `TodoListViewController` 에서 처리해줬을 때 사용자가 불편을 겪진 않을까요?

추가로 지금 구현에선 큰 문제 없긴 하지만, 나중에 반드시 따로 에러를 처리해줘야만 하는 화면이 추가되었을 때 현재 구조에서 구현/수정이 쉬울까요?

### Realm, Firebase를 위한 Model의 폴더 위치

음 단순 Realm, Firebase 의 데이터 모델의 역할이 아닌, 앱에서 사용할 데이터 모델로 매핑해주는 로직도 포함하고 있어서 Repository의 일부분으로 봐야할 것 같은데, 현재 Repository의 위치가 Data 에도 Domain 에도 있어서 명확히 어디 위치해줘야 할지 모르겠어요 :thinking:
제 생각엔 Repository 를 어디에 포함시킬지를 먼저 정하고, 그에 따라 위치시켜두면 될 것 같습니다.

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/MappingEntities/HistoryEntity+Realm.swift
> +    @Persisted var createAt: Date
사소하지만.. 여기도 `TodoRealmEntity` 처럼 `private` 붙여줄 수 있지 않을까요? 👀

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/MappingEntities/TodoEntity+Firebase.swift
> +        self.state = value["state"] as? String ?? State.todo.rawValue
생성자로 넘겨받은 `value`에 있어야할 값이 없을 때 의미없는 기본값을 넣어서라도 생성해줘야 할지, failable initializer로 구현해 예외처리를 해줘야할지 고민 해볼만한 포인트인 것 같습니다 🤔

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/PersistentStorages/FirebaseTodoListStorage.swift
> +        .reference()
(다음 스텝을 테스트로 생각하고 계신다해서 코멘트 남깁니다..!)
database 를 추상 타입으로, 외부로부터 주입받도록 구현하면 `FirebaseDatabase`와의 의존성을 분리해 `FirebaseTodoListStorage` 가 제공하고 있는 `backUp`, `allRead`의 독립적인 테스트가 가능할 것 같아요.

지금은 `FirebaseTodoListStorage`가 반드시 firebase 서버와 통신하도록 구현되어있어 `FirebaseTodoListStorage`만의 로직을 테스트할 수 없을 것 같습니다.

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/PersistentStorages/FirebaseTodoListStorage.swift
> +    private func allDelete() {
사소하지만 `allRead`, `allDelete` 보단 `readAll`, `deleteAll`이 좀 더 자연스러운 것 같아요..!

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/PersistentStorages/FirebaseTodoListStorage.swift
> +                single(.success(items))
음 `items`를 미리 선언해두고, 이후 append 하는 방식으로 구현하신 이유가 궁금해요 👀 
`let items = data.map { TodoFirebaseEntity(value: $1).toTodoModel() }` 와 같이 바로 생성해서 넘겨줄 수도 있을 것 같아서요 🤔

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/PersistentStorages/RealmHistoryStorage.swift
> +    private let realm = try? Realm()
여기도 마찬가지로 `Realm`과의 의존성을 덜어내어주면 더 좋을 것 같아요.
추가로 현재 `Realm` 생성에 실패하는 경우에 대한 처리가 되어있지 않은데, `Realm` 생성에 실패하면 앱이 어떻게 동작하게 되나요? 👀

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/PersistentStorages/RealmHistoryStorage.swift
> +protocol HistoryStorage: StorageError ,AnyObject {
개인적인 생각으론 `StorageError` 라는 네이밍은 에러 타입이 채택해야만 할 것 같아요 🤔 
Swift에서 제공해주는 `Error`, `LocalizedError` 프로토콜처럼요.
구현을 보니 에러를 넘겨줄 수 있는 통로를 가지도록 강제하는 프로토콜인 것 같은데, "에러를 전달할 수 있다" 혹은 "에러가 발생할 수 있다" 는 것을 명확하게 표현해줄 수 있는 이름이면 더 좋을 것 같아요.

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/PersistentStorages/RealmHistoryStorage.swift
> +                realm?.delete(items[index])
저장 로직 수행 중 중 에러가 발생한다던지 하는 이유로 로컬 저장소에 저장된 데이터와 화면에 보여지고 있는 데이터의 싱크가 맞지 않아 `delete`의 인자로 전달된 `index`가 `items`의 범위를 벗어날 일은 없을까요?

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/PersistentStorages/RealmTodoListStorage.swift
> +}
이 에러와 프로토콜은 `TodoListStorage` 외에 다른 곳에서도 공통으로 쓰이니 따로 파일로 분리해주면 더 좋을 것 같아요.

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/PersistentStorages/RealmTodoListStorage.swift
> +    case historySyncError = "History와 동기화하지 못했습니다."
에러 발생 시 사용자에게 표시할 메세지의 정의는 `rawValue` 보단 용도에 맞게 `errorDescription`을 사용하는 게 좋을 것 같아요.
`rawValue`는 생성자에서 문자열과 case 를 매칭시켜주는 역할도 하니까요.

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/PersistentStorages/RealmTodoListStorage.swift
> +                let item = items.first(where: { $0.id == data.id }) else { return }
`return`에 해당하는 부분이 특정 데이터를 업데이트 하려 했는데(화면엔 해당 데이터가 보이는 상태), 업데이트하려고 보니 로컬에 저장된 데이터엔 없는 상황인 것 같은데요.
이 때의 예외처리는 필요 없을까요? 🤔

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Repositories/DefaultHistoryRepository.swift
> +import UIKit
`Foundation` 지워줄 수 있을 것 같네요! (`UIKit`이 필요없는 것 같기도..?!)

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Repositories/DefaultHistoryRepository.swift
> +    private unowned let storage: HistoryStorage
`unowned`를 사용하신 이유가 궁금해요 👀

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Repositories/DefaultHistoryRepository.swift
> +    private let bag = DisposeBag()
`bag`은 사용되지 않는 것 같아요.

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Repositories/DefaultHistoryRepository.swift
> +}
지난번에도 비슷한 코멘트를 한 적이 있었는데, 요기도 `Repository`의 역할이 애매한 것 같아요.
단순히 `Storage`를 한 번 감싸기만 한 객체가 되어버렸네요 🤔 
구현하신 `Storage`가 `Repository`의 역할을 하고 있기에 이렇게 구조가 짜여졌다고 생각하는데, 사파리가 생각하시는 `Storage`와 `Repository`의 역할이 무엇인지 궁금합니다 👀

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Repositories/DefaultTodoListRepository.swift
> +        }
`"isUser"` 키값은 상수로 빼서 관리해주면 더 좋을 것 같아요.
그리고 `UserDefaults`도 외부로부터 주입받도록 구현해야 실제로 쓰이는 로컬 저장소에 영향을 받지 않도록 테스트 코드를 작성할 수 있을 것 같아요.

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Repositories/DefaultTodoListRepository.swift
> +        }
개인적인 생각으론 현재 guard를 넘어갔을 때의 로직이 없으니, 수행하는 로직을 guard의 else 영역에 두기보단, 조건을 `isUser == false`로 두고 로직을 guard 밑에 작성하는 게 이해하기 더 쉬울 것 같아요.

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Repositories/DefaultTodoListRepository.swift
> +        guard isUser else {
앱 최초 실행 시에만 서버로부터 데이터를 받아오는 이유가 궁금해요 👀 
프로젝트 기획서에 따르면, 서버와 연결되는 앱에선 서버와의 통신이 주가 되고 로컬 저장 로직은 서버와 통신이 끊어졌을 때를 대비하는 케이스가 되어야 할 것 같은데 지금은 최초 실행 이후 서버로부터 데이터를 받아오는 로직은 없는 것 같아서요.

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Repositories/DefaultTodoListRepository.swift
>      }
앱이 백그라운드로 진입하는 시점을 잡아 데이터를 저장하는 건 앱의 비즈니스 로직으로 보고 Repository가 아닌, UseCase 단에서 구현되어야 하지 않을까요?
사파리는 어떻게 생각하시는지 궁금합니다!

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Domain/Interfaces/Repositories/TodoListRepository.swift
> +    var errorObserver: PublishRelay<TodoError> { get }
여기는 `StorageError` 프로토콜로 처리하지 않으신 이유가 있을까요? 👀

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Domain/UseCase/TodoListUseCase.swift
> +        historyRepository.save(to: historyItem)
아이템을 기반으로 히스토리를 만들고, 저장하는 로직이 계속 반복되는데 메서드로 빼줄 수 있을 것 같아요.

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/History/View/HistoryCell.swift
> +class HistoryCell: UITableViewCell, CellIdentifiable {
`final` 붙여줄 수 있을 것 같아요!

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/View/TodoEditViewController.swift
> +                self?.viewModel.createButtonDidTap()
done, create 버튼을 눌러서 데이터를 업데이트 / 생성하게 되는데, 실패했을 땐 현재 화면(사용자가 작성중이던 화면)을 유지한 채로 에러 알러트를 띄워주는 등의 처리는 필요없을까요?
화면을 닫는 처리도 뷰모델에서 로직을 수행한 뒤에, 뷰모델이 뷰로 전달한 output 을 받아 `coordinator`가 처리하도록 구현하면 더 좋을 것 같아요 🤔

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoEdit/ViewModel/TodoEditViewModel.swift
> +        useCase.createItem(to: item)
`TodoListUseCase`에 로직 수행 시 에러를 전달하는 통로는 만들어두셨는데, 이에 대한 뷰단 처리는 없는 것 같네요 🤔 
에러가 발생했을 때 사용자가 인지할 수 있을까요..?

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/View/TodoListViewController.swift
>              }.disposed(by: bag)
이런 곳도 뷰에서 이벤트가 발생했을 때 `뷰모델로 input 전달` -> `뷰모델에서 로직 수행` -> `뷰모델에서 뷰로 output 전달` 의 흐름으로 구현할 필요는 없을지 고민해보시면 좋을 것 같아요.

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/View/TodoListViewController.swift
> +                self?.coordinator?.popoverMoveViewController(cell: cell, item: item)
이곳도 화면을 띄우는 흐름이 뷰모델을 거치지 않으니, "`id`에 해당하는 아이템을 잘 찾아오는가?" 까지는 테스트가 가능하지만 "찾아온 아이템을 popover를 띄우란 output과 함께 뷰로 잘 넘겨주는가?" 에 대한 테스트는 불가능할 것 같아요 🤔

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/View/TodoListViewController.swift
> +            }.disposed(by: bag)
아하..? 에러를 여기서 공통으로 처리하는군요 🤔 
수정 중 에러가 발생했을 때, 수정 중인 화면을 닫고 에러를 표시해주는 게 좋은 사용자 경험일지 고민해볼 필요가 있을 것 같아요.
열심히 작성한 내용이 날아가버리면 슬프니까요 😢

2022-07-27 15:21 UTC, TTOzzi commented on ProjectManager/ProjectManager/Presentation/TodoList/ViewModel/TodoListViewModel.swift
> +    }
셀에 표시하기 위해 데이터를 가공하는 로직을 `HistoryCellContent`로 나눠주신 것 처럼 이 로직도 `TodoCellContent`로 나눠주는 건 어떨까요? 👀

2022-07-28 11:19 UTC, saafaaari commented on ProjectManager/ProjectManager/Data/PersistentStorages/RealmHistoryStorage.swift
> +                realm?.delete(items[index])
`Collection`를 확장하여 예외처리 할 수 있도록 하였습니다.

2022-07-28 11:56 UTC, saafaaari commented on ProjectManager/ProjectManager/Data/PersistentStorages/RealmTodoListStorage.swift
> +                let item = items.first(where: { $0.id == data.id }) else { return }
```swift
guard let items = items else {
    errorObserver.accept(TodoError.unknownItem)
    storage.onNext([])
    return
}
guard let item = items.first(where: { $0.id == data.id }) else {
    errorObserver.accept(TodoError.unknownItem)
    storage.onNext(items.map { $0.toTodoModel() })
    return
}
```
위 코드와 같이 items 자체가 없으면, 다시 빈 배열을 방출, 해당 아이템이 없으면 다시 로컬에 저장되있는 데이터를 방출해 UI를 로컬에 맞게 업데이트 할 수 있도록 수정하였습니다.

2022-07-28 12:01 UTC, saafaaari commented on ProjectManager/ProjectManager/Data/Repositories/DefaultHistoryRepository.swift
> +    private unowned let storage: HistoryStorage
`Storage`는 최상단 `DIContainer`에서 주입을 받는 인스턴스이기 때문에 앱 사용중에 `Storage`가 메모리에서 해제될 일이 없다고 판단했고, 만약 해제가 된다면 `DIContainer` 해제되었다는 소리이기 때문에 그러면 이미 앱은 아무런 동작도 할 수 없기 때문에 `unowned `를 사용했습니다.

2022-07-28 12:03 UTC, saafaaari commented on ProjectManager/ProjectManager/Data/Repositories/DefaultHistoryRepository.swift
> +    private let bag = DisposeBag()
아차차 삭제했습니다.

2022-07-28 12:05 UTC, saafaaari commented on ProjectManager/ProjectManager/Data/Repositories/DefaultHistoryRepository.swift
> +}
그때 물어본다는것을 깜빡했네요. 또치의 말씀대로 단지 그냥 감싸고 있는것 같습니다. 이런경우 UseCase에 바로 Storage를 주입하는 것이 괜찮을 까요???

2022-07-28 12:16 UTC, saafaaari commented on ProjectManager/ProjectManager/Data/Repositories/DefaultTodoListRepository.swift
> +        }
감사합니다. 이런부분 까지 생각하지 못했네요. 외부에서 주입 하도록 수정 하였습니다.

2022-07-28 13:01 UTC, saafaaari commented on ProjectManager/ProjectManager/Domain/Interfaces/Repositories/TodoListRepository.swift
> +    var errorObserver: PublishRelay<TodoError> { get }
프로토콜은 에러를 방출하는 스토리지에 채택하기 위한 프로토콜이였습니다. 때문에 스토리지가 아닌 타입에선 PublishRelay -> Observable로 수정하였습니다.

2022-07-28 13:29 UTC, saafaaari commented on ProjectManager/ProjectManager/Data/PersistentStorages/RealmHistoryStorage.swift
> +protocol HistoryStorage: StorageError ,AnyObject {
네이밍이 참 힘드네요 `ErrorThrowble`로 수정했는데 애매한 느낌이 살짝 드네요..ㅎ

2022-07-28 13:34 UTC, saafaaari commented on ProjectManager/ProjectManager/Data/Repositories/DefaultTodoListRepository.swift
> +        guard isUser else {
음 일단 기획서의 의도를 잘 파악하지 못한것 같습니다. 
백그라운드 시점에만 동기화 시킨 이유는 로컬의 저장소가 좀더 신뢰도가 높다고 생각했습니다. 때문에 로컬을 메인 저장소로 사용하는것이 올바르겠다고 판단했고, 때문에 원격 저장소는 백업을 하는 용도로 사용했습니다. 앱을 삭제했다가 다시 다운받았을 때 원격저장소에 있다면, 데이터를 가져오도록 그렇다 보니 기획서의 내용과 조금 다른 부분이 생겼던것 같습니다.

2022-07-28 13:38 UTC, saafaaari commented on ProjectManager/ProjectManager/Data/Repositories/DefaultTodoListRepository.swift
>      }
UseCase의 로직은 사용자가 할 수 있는 행위라고 생각했습니다. 때문에 백그라운드로 진입시에 백업작업을 하는것은 저장소만의 일이라고 생각했습니다. 하지만 비지니스 로직으로도 볼 수 있을것 같습니다. 하지만 그러면 UIKit이 UseCase에 import될것 같아 고민입니다.

2022-07-28 13:55 UTC, saafaaari commented
리뷰 너무 잘 읽었습니다. 🙇‍♂️
감사합니다. 또치!!

에러 처리에 대한 코멘트가 많아 큰 도움이 되었습니다.
`TodoListView`에서만 에러에 대한 처리를 한 것은 에러가 발생하는 부분이 콘텐츠를 생성, 삭제, 업데이트 시점에 일어난다고 생각했습니다. 때문에 `EditView`또는 `MoveView`가 `dismiss`되고, 에러에 대한 얼럿을 띄우는 것이 사용자에게 접근성이 좋을 것이라 생각했습니다. 또한
`MoveView` 같은 경우 얼럿을 띄울만한 사이즈가 되지 않기 때문에 이 같은 경우 어쩔 수 없이 `TodoListView`에서 에러 처리를 해줘야 했습니다. 이 부분은 프로젝트 기한이 끝나더라도 계속 리팩토링해서 포트폴리오로 사용할 수 있도록 만들어 보겠습니다.

추가적으로 테스트에 유리하게 의존성에 대해 조언해 주셔 감사합니다. 또치의 조언을 지금 바로 다 적용시켜 보지 못했지만, 다음 PR을 보낼 수 있으면 테스트에 대해서 조언 받고 싶기 때문에 또치가 주신 의존성에 대한 리뷰는 모두 적용시켜 보도록 하였습니다.

혹시 이번 리뷰가 마지막 리뷰가 될 수 도 있으니 미리 너무 감사하단 말 전하겠습니다. 감사합니다.🙇‍♂️

2022-07-30 12:17 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/PersistentStorages/RealmHistoryStorage.swift
> +protocol HistoryStorage: StorageError ,AnyObject {
이름은 공통으로 쓰일 것 같은데, 에러는 `TodoError` 만을 넘겨주도록 구현되어 있어서 애매한 것 같아요.
이름을 명시적으로 `TodoErrorThrowable`로 선언해 `TodoError`를 넘겨준다는 것을 표현해주거나, 아니면 프로토콜의 `associatedType`이나 `Error` 프로토콜을 활용해 넘길 수 있는 에러가 무엇이든 넘길 수 있게 해주는 게 좋을 것 같아요.

2022-07-30 12:27 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Repositories/DefaultHistoryRepository.swift
> +    private unowned let storage: HistoryStorage
음 반드시 존재해야 한다는 것을 표현하기엔 좋은데, 앱이 크래시가 날 가능성을 항상 갖고가게 되는 코드라 조금 애매하긴 합니다.
지금이야 `DIContainer`가 항상 살아있고 정상적으로 주입도 될테지만, 만약 나중에 다른 사람이 구조를 변경하다가 놓치는 상황이 생긴다면 앱이 종료되는 것 보단, 히스토리만 보이지 않은 채로 다른 기능은 정상 동작하는 게 나으니까요 🤔

2022-07-30 12:29 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Repositories/DefaultHistoryRepository.swift
> +}
음 다른 곳에선 `Storage`와 `Repository`가 어느 정도 역할을 나눠 갖고 있는 것 같아, 이곳만 예외적으로 다른 구조로 구현하기보단 지금처럼 일관성을 유지한 구조로 두는 게 더 나을 것 같네요 🤔

2022-07-30 13:29 UTC, TTOzzi commented on ProjectManager/ProjectManagerTests/UseCaseTests/TodoListUseCaseTest.swift
> +    }
의존성을 가지는 객체들을 모킹하여 주입한 `DefaultTodoListUseCase` 의 독립적인 테스트를 의도하신 것 같은데, 전체적으로 모의 객체 내부 로직이 디테일하여 모의 객체 내부 로직을 잘못 구현해 테스트에 실패하는 케이스도 생길 수 있을 것 같아요 🤔 
(통합 테스트를 의도하신 게 아니라면)`DefaultTodoListUseCase`의 테스트는 `createItem` 을 호출했을 때, 내부에서 `History` 타입을 만들고 데이터를 의존성을 가지는 객체인 `historyRepository`, `listRepository`의 메서드들로 잘 넘겨주는지(**호출**) 까지만 테스트되어야 합니다.
모의 객체 내부를 실제 객체와 비슷하게 만드는 게 아닌, 메서드의 인자로 받아온 값을 저장하도록 하여 그 값을 꺼내서 확인까지만 할 수 있도록 구현되어야 할 것 같아요.
내부에 로직을 가지지 않고 함수의 호출 / 인자 전달이 잘 이루어졌는지 까지만 확인할 수 있도록요.

2022-07-30 13:39 UTC, TTOzzi commented on ProjectManager/ProjectManagerTests/UseCaseTests/TodoListUseCaseTest.swift
> +        XCTAssertEqual(todoItem, item)
위에서 남긴 코멘트에서 이해가 어려우실까봐 조금 더 덧붙이자면..
구현하신 로직에서 `updateItem` 메서드가 불렸을 때 `UseCase`의 역할은 인자로 넘겨진 `item`을 `listRepository`의 `update` 메서드로 잘 넘겨주는지 까지입니다.
현재는 `TodoListUseCase`의 테스트이지만, `MockListRepository`의 내부 로직에 따라 성공/실패가 갈릴 것 같아요.

`MockListRepository`의 `update` 메서드의 구현은 인자로 넘어온 데이터의 `id`로 값을 찾고 수정하는 게 아닌, 테스트 확인용 프로퍼티를 만들어 넘겨받은 인자를 단순 저장하기만 하고 `update` 메서드가 호출되었는지, 인자로 데이터가 잘 넘어왔는지 확인할 수 있도록 구현되어야 합니다.

2022-07-30 13:47 UTC, TTOzzi commented on ProjectManager/ProjectManagerTests/ViewModelTests/HistoryViewModelTest.swift
> +class HistoryViewModelTest: XCTestCase {
이곳도 마찬가지로 전체적으로 `DefaultTodoHistoryViewModel`의 로직을 테스트함과 동시에 주입한 `MockUseCase` 로직도 테스트하고 있네요 🤔 
구현하신 뷰모델의 역할은 UseCase가 어떤 로직을 수행하는가와 관계 없이 반환된 `BehaviorSubject<[History]>`가 방출하는 값을 `HistoryCellContent`로 매핑하는 것이기에, 이 동작에 대한 테스트만 작성되면 될 것 같아요.

(그리고 방금 확인했는데 `DefaultTodoHistoryViewModel`에 주입되는 `UseCase`의 추상타입은 `TodoListUseCase`를 공통으로 쓰지 말고 따로 나눠주면 더 좋을 것 같아요. `DefaultTodoHistoryViewModel`가 필요로 하는 인터페이스는 `readHistoryItems` 뿐이고 나머지 메서드의 존재를 알 필요는 없으니까요 🙂 )

2022-08-24 00:42 UTC, closed without merging