[Step1] SJ, Kio, Bobby
yagom-academy/ios-project-manager pull request #17
Opened 2021-07-13 14:45 UTC by Babywalnut

@O-O-wl 
# 안녕하세요 붱이🦉

드디어 첫 PR을 보냅니다!😭🙈 기능 구현 내용과 UI 구조에 간단히 기술하고 해결하지 못한 부분에 대해서 적어보았습니다.

피드백 부탁드립니다 🙇🏻🙏
<br><br>
# 📘구현내용

### [ReadME](https://github.com/SoKoooool/ios-project-manager/blob/step1/README.md) 
### UI구현방식 :  코드

### 아키텍쳐 : 
              
* ProjectManagerViewController : 
    NavigationViewController위에 StackView(axis: horizontal)를 올리고 
    각각 StackView내에 TitleLabel과 TableView를 StackView(axis: vertical)로 묶어 올렸습니다.

*  NewTodoFromViewController(Modal View) :
     NavigationViewController 위에 StackView(axis: horizontal)를 올리고
     그 위에 TextField, DatePicker, TextView를 올렸습니다.

* TodoListCell(Custom Cell) :
      Cell위에 StackView를 올리고 위에 titleLabel,  descriptionLabel, DateLabel을 올렸습니다.

![Jul-13-2021 22-57-48](https://user-images.githubusercontent.com/42936446/125465234-f8fc1ea7-d6f3-4e56-abc0-f80ba4b19ee7.gif)
<br><br>

<hr>

### Drag & Drop :

- Cell내에 존재하는 titleLabel, descriptionLabel, dateLabel에 존재하는 세개의 데이터를 한번에 ItemProvider로써 변환하기 위해 CellData라는 타입을 만들었습니다.
     
- 같은 테이블 뷰 Cell을 이동시에는 DataSource메서드인 moveRowAt을 활용하여 Drop이 이루어지고, 다른 테이블 뷰로의 이동시에는 같은 기능을 Drop Delegate 메서드인 dropSessionDidUpdate와 performDropWith 메서드가 해줍니다.

![같은 테이블 drag and drop](https://user-images.githubusercontent.com/65153742/125465943-66dbfdad-e151-41b0-adab-81ad54ee77f3.gif)

![drag and drop to 다른 테이블뷰](https://user-images.githubusercontent.com/65153742/125466165-23d903b2-1d81-4d7c-8c2c-caf3e293dad6.gif)
<br><br>
<hr>

### 새로운 Cell 추가,삭제 및 수정 :

- Cell추가 : Delegate패턴을 이용하여 NewTodoFormViewController가 ProjectManagerViewController의 권한을 위임받아 데이터를 저장하는 배열에 append를 시키고 TableView를 reload 시키고 titleLabel에 개수를 갱신합니다.
      
- Cell삭제 : DataSource의  editingStyle 메서드를 사용하여 구현하였고 삭제시 TableView위에 있는 TitleLabel에 있는 셀의 개수를 Reload를 시켜줍니다.
      
- Cell수정 : Delegate패턴을 이용하여 Cell추가 기능과는 반대로 ProjectManagerViewController가 NewTodoFormViewController의 권한을 위임받아 Cell에 있는 데이터를 TextField, DatePicker 그리고 TextView에 전달해줬습니다. 
      Edit버튼으로 EditingMode를 활성화하여 데이터를 수정하고 Done을 눌러 저장할 시 권한위임을 반대로하여 원래 Data 배열의 값을 갱신 시켜줬습니다.

![NewMemo추가](https://user-images.githubusercontent.com/65153742/125465331-530113f0-5126-403c-9beb-c7e53b18e836.gif)

![delete](https://user-images.githubusercontent.com/65153742/125465462-84a4cb8d-6c08-40b0-a9a6-6a9e5945986b.gif)

![edit-done](https://user-images.githubusercontent.com/65153742/125465526-52f36ae3-49ef-4dad-8c32-4c48f5332645.gif)

    
<br><br>
# 📕 조언을 얻고 싶은점

### 첫 cell수정시 데이터 갱신 안됨

첫 Cell수정을 위해 Cell터치시 DataSource의 didselect메서드가 호출됩니다. Modal view가 load되기 전에 NewTodoFormViewController의 권한을ProjectManagerViewController가 위임받아 터치한 Cell의 tableView와 indexPath정보를 전달되는 순서의 로직이기때문에 전달되지 않습니다.

이 부분에 대해서 어떻게 해결하면 좋을지 조언해주시면 감사하겠습니다!
이외에도 많은 코멘트 부탁드립니다!!🚀🌙

2021-07-14 19:33 UTC, O-O-wl requested changes
타입과 코드들을 잘게 나누려고 한 노력이 많이 보인 것 같아요.
코드를 보면서 팀내의 상속의 기준이 궁금했어요. 속성이 정해진 새로운 TableView등을 새로운 타입으로 선언하기로 정해진 걸까요?

남겨주신 부분은 일단 NewTodoFormViewController를 항상 메모리에 로드해두는 게 아니라 
셀이 클릭되었을 떄 새 인스턴스를 만들면 자연스럽게 해결될 걸로 보이긴하는 데, 추가적으로 궁금한 부분 디스코드에서 이야기해볼까요.?
제가 디스코드를 Off로 두긴하지만 항상 확인하기 때문에 언제든 편하게 불러주세요 🙇‍♂️

2021-07-14 19:33 UTC, O-O-wl commented on ProjectManager/ProjectManager/TitleView 2.swift
> +        count.text = "5"
하드하게 적은 이유가 있을까요?

2021-07-14 19:33 UTC, O-O-wl commented on ProjectManager/ProjectManager/Screen/ProjectManagerViewController+Ext.swift
> +extension ProjectManagerViewController: ProjectManagerDelegate {
프로토콜 네이밍이 어색하게 느껴지네요
자가 자신의 위임자로 자기 자신을 정한 상황인가요 😮

2021-07-14 19:33 UTC, O-O-wl commented on ProjectManager/ProjectManager/Custom Views/NewTodoFromDelegate.swift
> +    func getIndexPath(_ tableView: UITableView, row: Int, data: CellData)
getIndexPath 라는 이름만 봤을 때는 indexPath를 반환 값으로 가지고 있어야할 것 같은데 아니네요
왜 get이라는 이름이 되었을까요?

2021-07-14 19:33 UTC, O-O-wl commented on ProjectManager/ProjectManager/Screen/ProjectManagerViewController.swift
> +    var delegate: NewTodoFormDelegate?
delegate를 이런 형태로 사용해도 되긴하겠지만 다른 곳에서 사용하는 걸 참조해봐도 좋을 것 같아요
`weak var delegate: UITableViewDelegate?`은 어떤 이유로 이렇게 참조방식이 weak으로 되어있을까요?

2021-07-14 19:33 UTC, O-O-wl commented on ProjectManager/ProjectManager/Screen/ProjectManagerViewController.swift
> +    let newTodoFormViewController = NewTodoFormViewController()
새로운 Todo를 작성하는 ViewController를 항상 가지고 있는 이유가 있나요?
새로운 Todo를 추가하지 않아도 해당 ViewController는 메모리에 남아 있기 되지 않을까요>?

2021-07-15 11:18 UTC, Kioding commented on ProjectManager/ProjectManager/Custom Views/ListTitleView.swift
> +class ListTitleView: UIView {
xcode내에서는 파일이 없었는데, Finder에서 보니 있네요😭  xcode와 터미널로 커밋했을 때가 있는데 꼬인 것 같습니다. 덕분에 삭제했습니다!

2021-07-15 12:16 UTC, Kioding commented on ProjectManager/ProjectManager/Custom Views/NewTodoFormNavigationController.swift
> +}
navigaionController 에 backgroundColor를 지정할 필요가 없는 것 같아 파일을 삭제하였습니다!

2021-07-15 12:32 UTC, Kioding commented on ProjectManager/ProjectManager/Screen/ProjectManagerViewController.swift
> +        doneTableView.dragInteractionEnabled = true
```swift
    private func setTableViewControl(tableView: UITableView) {
        tableView.dataSource = self
        tableView.delegate = self
    }
    
    private func setDragAndDrop(tableView: UITableView) {
        tableView.dragInteractionEnabled = true
        tableView.dragDelegate = self
        tableView.dropDelegate = self
    }
```

2021-07-15 12:37 UTC, Kioding commented on ProjectManager/ProjectManager/Screen/ProjectManagerViewController.swift
> +        }
앗? 필요없는 코드인데 이렇게 작성했네요😱 수정하였습니다!

2021-07-15 12:56 UTC, Kioding commented on ProjectManager/ProjectManager/Screen/DropDelegate+Ext.swift
> +            dropProposal = UITableViewDropProposal(operation: .move, intent: .insertAtDestinationIndexPath)
앱 내에서 움직일 경우와, 앱 밖에서 올 경우를 생각했는데 로직이 같아서 한줄로 통일하였씁니다!

2021-07-15 13:02 UTC, Kioding commented on ProjectManager/ProjectManager/TitleView 2.swift
> +        count.text = "5"
위에서 말했는데, 위에서 커밋이 꼬이면서 아직 남아있던 것 같습니다. 파일 삭제하고, count는 데이터 전달 받게 하였습니다 :)

2021-07-15 13:20 UTC, Babywalnut commented on ProjectManager/ProjectManager/Screen/ProjectManagerViewController.swift
> +    var delegate: NewTodoFormDelegate?
저렇게 weak를 사용하는 이유를 물어보신 걸까요??😂
저희가 공부하기로는 weak를 사용하는 이유는 두 객체가 상호참조하여 강한 참조가 일어날때 외부에서 참조하는 reference가 
해제되어도 서로가 서로를 참조하기 때문에 reference count가 0이되지 않습니다. 때문에 참조는 하지만 reference count를 
올려주지 않고 참조하고 참조하는 객체가 메모리에서 해제되면 해당 프로퍼티를 nil로 변경해주기 위해서 사용하는 걸로 알고있습니다!

2021-07-16 08:29 UTC, Babywalnut commented on ProjectManager/ProjectManager/Screen/ProjectManagerViewController.swift
> +    let newTodoFormViewController = NewTodoFormViewController()
넵 +버튼을 누를때와 Cell을 선택했을때 ViewController 인스턴스를 생성하고 Delegate연결도 해주어 modalView가 사라지며 dismiss되었을 때 메모리에서 해제될 수 있도록 수정하였습니다.🙃

2021-07-16 08:31 UTC, Babywalnut commented on ProjectManager/ProjectManager/Custom Views/NewTodoFromDelegate.swift
> +    func getIndexPath(_ tableView: UITableView, row: Int, data: CellData)
presentingViewController에서 ModalView로 데이터를 전달할 경우
즉, Cell을 눌렀을때 데이터를 전달할 때 Delegate패턴을 사용하기 때문에 만들었던 메서드인데
Delegate를 사용하는 것이 옳지않다고 판단하여 해당 Delegate와 메서드는 삭제하였습니다!

2021-07-16 09:04 UTC, Babywalnut commented on ProjectManager/ProjectManager/Custom Views/ListTitleView 2.swift
> +class ListTitleView: UIView {
넵 적용했습니다!

2021-07-16 10:11 UTC, Babywalnut commented
@O-O-wl 
# 안녕하세요 붱이2 🦉
작성해주신 코멘트를 반영해서 코드를 리펙토링해봤습니다!

> 타입과 코드들을 잘게 나누려고 한 노력이 많이 보인 것 같아요.
> 코드를 보면서 팀내의 상속의 기준이 궁금했어요. 속성이 정해진 새로운 TableView등을 새로운 타입으로 선언하기로 정해진 걸까요?

- TableView를 제외한 다른 content View들은 전부 custom으로 정의하였습니다.
- custom으로 정의된 View들은 View 내부에서 자체적으로 속성을 정해주었고 add되어지는 ViewController에 constraints를 선언해주었습니다.
- custom이 아닌 View들은 View가 add되어지는 ViewController에 속성과 constraints를 선언해주었습니다.
- StackView 중첩되는 구조를 많이 사용하다보니 custom StackView를 정의할 때 자체 속성설정만 해주고 addSubView는 StackView들이 사용되어지는 ViewController에서 추가하기로 했습니다.
- StackView가 아닌 customView를 정의할 때는 속성 설정과 addSubview까지 한번에 처리해 주었습니다.


<br><br>
> 남겨주신 부분은 일단 NewTodoFormViewController를 항상 메모리에 로드해두는 게 아니라
> 셀이 클릭되었을 떄 새 인스턴스를 만들면 자연스럽게 해결될 걸로 보이긴하는 데, 추가적으로 궁금한 부분 디스코드에서 이야기해볼까요.?

저희가 ModalView에서 PresentingViewController로 데이터 전달할 때와 반대로 PresentingViewController에서 ModalView로 전달할 때 모두 Delegate패턴을 사용했었는데,
ModalView에서 PresentingViewController로 데이터를 전달할 때는 이미 메모리에 PresentingViewController가 존재하므로 Done버튼을 클릭시 데이터를 전달하는데에 있어서 별 문제가 없었습니다.

반대의 경우 tableView메서드인 `tableView(_:didSelect)` 메서드를 통해 Cell을 클릭하여 PresentingViewController에서 ModalView로 데이터를 전달할 때는 아직 ModalView의 `viewDidLoad()`메서드가 실행되지않아 delegate선언이 되기전에 delegate메서드를 호출하는 문제가 발생하였습니다.

때문에 Delegate를 사용하기 위해서는 `pushNewTodoFormViewController()`나 `tableView(_:didSelect)`함수가 호출될때가 아닌 ProjectManagerViewController에 전역 프로퍼티로 사용할 수 밖에 없었습니다.

이런 문제로 인하여 저희가 구현한 코드에서 PresentingViewController에서 ModalView로 데이터를 전달할 떄 delegate보다는 직접전달하는 것으로 해결하였고 자연스럽게 ViewController내의 전역변수 역시 메서드내에서 선언해줄 수 있게되었습니다. 

<br><br>
## 궁금한 점: 
- **PR코멘트 중에 translatesAutoresizeingMaskIntoConstraInts를 설정에 관해서 해당 View를 정의할때가 아닌 addSubview 및 constraints를 설정해줄 때 해주라는 의미일까요?
(정의할 때 이미 설정을 해주었습니다.)**

2021-07-17 02:57 UTC, O-O-wl commented on ProjectManager/ProjectManager/Screen/ProjectManagerViewController.swift
> +    var delegate: NewTodoFormDelegate?
해당 경우도 delegate와 자신과의 retain cycle을 만들지 않음 보장하기 위해서는 위와같이 구현하는건 어떨까 했습니다

weak으로 하지 않을 때의 리스크가 한계가 생길 것 같아서요

2021-07-17 03:08 UTC, O-O-wl commented
> @O-O-wl
> 
> # 안녕하세요 붱이2 🦉
> 작성해주신 코멘트를 반영해서 코드를 리펙토링해봤습니다!
> 
> > 타입과 코드들을 잘게 나누려고 한 노력이 많이 보인 것 같아요.
> > 코드를 보면서 팀내의 상속의 기준이 궁금했어요. 속성이 정해진 새로운 TableView등을 새로운 타입으로 선언하기로 정해진 걸까요?
> 
> * TableView를 제외한 다른 content View들은 전부 custom으로 정의하였습니다.
> * custom으로 정의된 View들은 View 내부에서 자체적으로 속성을 정해주었고 add되어지는 ViewController에 constraints를 선언해주었습니다.
> * custom이 아닌 View들은 View가 add되어지는 ViewController에 속성과 constraints를 선언해주었습니다.
> * StackView 중첩되는 구조를 많이 사용하다보니 custom StackView를 정의할 때 자체 속성설정만 해주고 addSubView는 StackView들이 사용되어지는 ViewController에서 추가하기로 했습니다.
> * StackView가 아닌 customView를 정의할 때는 속성 설정과 addSubview까지 한번에 처리해 주었습니다.
> 
> 
> 
> 
> > 남겨주신 부분은 일단 NewTodoFormViewController를 항상 메모리에 로드해두는 게 아니라
> > 셀이 클릭되었을 떄 새 인스턴스를 만들면 자연스럽게 해결될 걸로 보이긴하는 데, 추가적으로 궁금한 부분 디스코드에서 이야기해볼까요.?
> 
> 저희가 ModalView에서 PresentingViewController로 데이터 전달할 때와 반대로 PresentingViewController에서 ModalView로 전달할 때 모두 Delegate패턴을 사용했었는데,
> ModalView에서 PresentingViewController로 데이터를 전달할 때는 이미 메모리에 PresentingViewController가 존재하므로 Done버튼을 클릭시 데이터를 전달하는데에 있어서 별 문제가 없었습니다.
> 
> 반대의 경우 tableView메서드인 `tableView(_:didSelect)` 메서드를 통해 Cell을 클릭하여 PresentingViewController에서 ModalView로 데이터를 전달할 때는 아직 ModalView의 `viewDidLoad()`메서드가 실행되지않아 delegate선언이 되기전에 delegate메서드를 호출하는 문제가 발생하였습니다.
> 
> 때문에 Delegate를 사용하기 위해서는 `pushNewTodoFormViewController()`나 `tableView(_:didSelect)`함수가 호출될때가 아닌 ProjectManagerViewController에 전역 프로퍼티로 사용할 수 밖에 없었습니다.
> 
> 이런 문제로 인하여 저희가 구현한 코드에서 PresentingViewController에서 ModalView로 데이터를 전달할 떄 delegate보다는 직접전달하는 것으로 해결하였고 자연스럽게 ViewController내의 전역변수 역시 메서드내에서 선언해줄 수 있게되었습니다.
> 
> 
> 
> 
> ## 궁금한 점:
> * **PR코멘트 중에 translatesAutoresizeingMaskIntoConstraInts를 설정에 관해서 해당 View를 정의할때가 아닌 addSubview 및 constraints를 설정해줄 때 해주라는 의미일까요?
>   (정의할 때 이미 설정을 해주었습니다.)**

아 그렇게 하라는 건 아니엇는데 궁금햇엇어요
의도상 오토 리사이즈마스크를 끄는 건 위에서 꺼주는 거보다 사용하는 쪽에서 레이아웃을 하는 방식에 따라 끄는 게 더 일반적이라고 생각햇엇어요 다른 UIView처럼  :) 그래서 만약 저렇게 해도 다른 사람이 아래에서 오토레이아웃을 적용할 때는 꺼져잇어도 다시 끄지 않을까 하는 생각이 들엇어요

2021-08-25 08:24 UTC, closed without merging