프로젝트 관리 앱 [STEP 2-1, 2-2] 수꿍, 휴
yagom-academy/ios-project-manager pull request #188
Opened 2022-09-11 10:29 UTC by Hugh-github

@ryan-son 
안녕하세요 라이언!!
추석 연휴 잘 보내고 계시나요 🙇🏻
저희가 나눈 하위 STEP 2-1, 2-2에 대한 PR 보냅니다.
TableView의 Cell이 생성되는지 확인하기 위해 임의의 데이터를 생성해서 넣어주었습니다. 이 부분 같은 경우 STEP 2-3 을 구현하면서 수정할 예정입니다.

## 📱 화면 구현

- TODO, DOING, DONE 화면을 각각 TableView를 이용해 구현
![](https://i.imgur.com/aw3o1ry.png)

- Modal의 formSheet 스타일로 AddView 구현
![](https://i.imgur.com/inAFoRU.png)

## 📃 기능 설명
    
- MainView
    - 3개의 Table View를 하나의 Custom StackView에 저장해 관리
    - Table View의 header로 사용할 Custom View 구현
    
- AddView
    - Modal Style 중 form sheet 사용
    - Date Picker를 사용해 날짜를 선택하는 View 구현
    - Text Field와 Text View에 shadow 효과 추가
--- 
    
## 2️⃣ STEP 2-1, 2-2

### STEP 2-2 Questions & Answers

#### Q1. Collection View의 Section 가로 배치 문제
- Collection View로 Section을 추가할 경우 세로 방향으로 추가되는 걸 확인했습니다. FlowLayout을 사용할 경우 scroll 방향을 horizontal로 해주면 가로 방향으로 추가되는 걸 확인할 수 있었지만 Section 별로 스크롤 방향을 주는 방법이 어려웠습니다. 
혹시 이번 프로젝트의 View를 구현할 때 어떠한 방법을 주로 사용하는지 궁금합니다. 
    
#### Q2. TextView Shadow 적용 문제
    
- UITextField의 경우에는 아래의 코드와 같이 layer에 shadow를 넣어주기만 하면 정상적으로 작동하였습니다.
    
```swift
private let scheduleTitleTextField: UITextField = {
        let textField = UITextField()
        ...
        textField.layer.shadowOpacity = 1
        textField.layer.shadowOffset = CGSize(width: 0, height: 2)
        textField.layer.shadowColor = UIColor.gray.cgColor
        
        return textField
}()
```
    
- 이와 달리, UITextView의 경우에는 위와 동일한 방법으로 layer에 shadow를 적용하였으나, shadow가 정상적으로 화면에 표시되지 않는 문제를 발견하였습니다. 이를 해결하기 위하여 처음에는 clipsToBounds 프로퍼티를 true로 설정하면, 정상적으로 shadow가 표시되나 TextView의 내용이 길어지면, 위에 있는 글자가 TextView를 벗어나는 에러를 발견하였습니다. 
- 현재는 이를 해결하기 위한 다른 방법으로 UIView를 하나 생성하여 shadow를 적용하고, 그 위에 TextView를 addSubview메서드를 통해 추가하였습니다.
- 별도의 UIView 생성 없이 TextView 자체에 shadow를 정상적으로 적용하기 위한 방법이 있을지 질문드리고 싶습니다.
- 추가로, UITextField와 UITextView의 차이가 아래의 View Hierarchy에서의 위치에서 비롯되는 것일지 의문이 듭니다.
- ![](https://i.imgur.com/ZOXcoL2.jpg)

2022-09-13 06:28 UTC, ryan-son requested changes
휴, 수꿍, Step을 나눠보시고 2-2까지 수행하시느라 고생하셨어요.

# 질의응답

#### Q1. Collection View의 Section 가로 배치 문제
> - Collection View로 Section을 추가할 경우 세로 방향으로 추가되는 걸 확인했습니다. FlowLayout을 사용할 경우 scroll 방향을 horizontal로 해주면 가로 방향으로 추가되는 걸 확인할 수 있었지만 Section 별로 스크롤 방향을 주는 방법이 어려웠습니다. 
>혹시 이번 프로젝트의 View를 구현할 때 어떠한 방법을 주로 사용하는지 궁금합니다. 

개인적으로 이러한 형태의 뷰는 table view를 여러 개 사용하여 구현했었어요. table view마다 독립된 data source가 존재하니 관리하기 편했었습니다.

#### Q2. TextView Shadow 적용 문제
>- UITextField의 경우에는 아래의 코드와 같이 layer에 shadow를 넣어주기만 하면 정상적으로 작동하였습니다.
>- 이와 달리, UITextView의 경우에는 위와 동일한 방법으로 layer에 shadow를 적용하였으나, shadow가 정상적으로 화면에 표시되지 않는 문제를 발견하였습니다. 이를 해결하기 위하여 처음에는 clipsToBounds 프로퍼티를 true로 설정하면, 정상적으로 shadow가 표시되나 TextView의 내용이 길어지면, 위에 있는 글자가 TextView를 벗어나는 에러를 발견하였습니다. 

`UITextField`는 적은 양의 텍스트를 입력 받는 도구로 설계되어 스크롤 기능이 없습니다. 그래서 요소의 크기가 예측가능하여 기본적으로 `clipsToBounds`가 `false`로 설정되어 있습니다. 반면 `UITextView`는 기본적으로 스크롤 기능을 제공하며, 이 기능이 기본적으로 활성화되어 있습니다. 요소의 크기가 내부에 존재하는 요소의 크기와 관계가 없으므로 기본적으로 `clipsToBounds`가 `true`로 설정되어 있습니다 (그러니 `clipsToBounds`를 `false`로 설정하고 글자가 UI 영역 밖으로 나가는 것은 에러가 아닙니다). 여러분들이 적용하신 방법대로 `UITextView`를 이용하려면 스크롤 기능을 비활성화하여 self-sizing text view를 구성하면 되고, 지금처럼 text view 자체가 스크롤 가능하면서 shadow를 적용하려면 현재와 같은 방법을 사용하시면 됩니다.

>- 현재는 이를 해결하기 위한 다른 방법으로 UIView를 하나 생성하여 shadow를 적용하고, 그 위에 TextView를 addSubview메서드를 통해 추가하였습니다.

👍. [ClipsToBounds](https://developer.apple.com/documentation/uikit/uiview/1622415-clipstobounds)가 어떤 기능을 수행하는지 알아보시면 좋을 것 같네요. 유사한 내용으로 CALayer의 [maskToBounds](https://developer.apple.com/documentation/quartzcore/calayer/1410896-maskstobounds)도 함께 알아봅시다~

> - 추가로, UITextField와 UITextView의 차이가 아래의 View Hierarchy에서의 위치에서 비롯되는 것일지 의문이 듭니다.

말씀을 이해하지 못했어요. 회의실에서 만나서 이야기 나눠봅시다~

궁금하신 내용 있으시면 언제든지 찾아주세요~ 화이팅~ 💪

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/.swiftlint.yml
> +  - trailing_whitespace
`Xcode` Preferences에서 Text Editing > Editing 탭을 아래와 같이 설정하시면 trailing whitespace를 자동으로 잡아줍니다. 이 설정과 관계없이 trailing whitespace 룰을 없애시고 싶으신걸까요?

![image](https://user-images.githubusercontent.com/69730931/188598905-d06dad7c-2861-43de-9fce-e2eb344734e4.png)

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/.swiftlint.yml
> +  - ProjectManager
작성하지 않아도 린팅이 잘 작동하는 것으로 확인되는데, 명시적으로 작성하신 이유가 있으실까요?

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +    },
`Package.resolved` 파일의 역할은 무엇이었나요? 아래 자료를 읽어보시고, 이 파일이 `.gitignore`에 포함할 것인지 여부를 논의해보면 좋을 것 같아요. 여러분들이 알고계시는 라이브러리 등 오픈소스 프로젝트에서는 어떻게 처리하고 있을까요?

- [Resolving Versions (Package.resolved File) - apple/swift-package-manager GitHub repo](https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#resolving-versions-packageresolved-file)

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager.xcodeproj/xcshareddata/xcschemes/ProjectManager.xcscheme
> +   </BuildAction>
`*.xcscheme`과 `xcshareddata`도 알아볼까요?

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
> +        })
load 후 completion 단계에서는 해 줄 일이 없었던걸까요?

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
> +    }()
[P2]
현재 구성은 실제 디바이스 저장공간의 데이터를 이용하는 방법 외에 다른 옵션은 없어보이네요. 향후 단위테스트가 추가되면 `LocalDatabaseManager`의 테스트 과정에서 실제 앱의 데이터를 생성, 수정, 삭제하게 될 수 있을 것 같은데, 선택적으로 in memory 모드로 인스턴스를 생성하는 방법을 제공해주는건 어떨까요?

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
> +        let context = persistentContainer.viewContext
`NSManagedObjectContext`의 역할은 무엇이었나요? `NSPersistentContainer`가 기본적으로 제공하는 `viewContext`는 어떤 성질을 가지고 있나요?

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
> +        }
[P4]
매번 context에 변경사항이 있는지 확인하고 저장하는 작업을 수행하고 있는데, 이 작업을 재사용 가능하도록 분리해서 사용하는건 어떨까요? 저장 과정에서 에러처리도 해당 메서드에서 수행하면 에러 발생 위치를 더 명확하게 표시할 수도 있을 것 같아요.

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionController.swift
> +    private func configNavigationItems() {
의도하신 줄임 표현일까요?
```suggestion
    private func configureNavigationItems() {
```

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionController.swift
> +    @objc private func didTappedDoneButton() {
[P3]
영문 표현으로 보면 아래 중 하나를 선택하는 것이 더 자연스러울 것 같아요.
1. `doneButtonTapped`
3. `didTapDoneButton`

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionScrollView.swift
> +        datePicker.minimumDate = Date()
`Date()`, `UUID()`와 같이 무작위 성질을 가지고 있는 이니셜라이저 또는 메서드는 테스트하기 까다롭기 때문에 일반적으로 외부에서 로직 또는 결과를 주입받는 형식으로 구성해요. 지금 단계에서는 이르고, MVVM 구조를 구성하여 테스트하기 용이하게 만드려면 로직을 어떻게 구성해야할지 고민하는 단계에서 다시 살펴봅시다.

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionScrollView.swift
> +final class ProjectAdditionScrollView: UIScrollView {
Text view 자체가 scrollable 성질을 가지고 있는데, 컨텐츠를 Scroll View로 구성하신 이유는 무엇인가요? Text view와 별도로 scrollable 성질을 가지려면 레이아웃 설정을 조금 변경해야할 필요가 있어보이네요.

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/View/MainView/ProjectManagerController.swift
> +        )
[P4]
테스트 또는 프리뷰 목적으로 이러한 형식의 데이터가 필요하다면, `ProjectUnit`의 타입 프로퍼티로 두는건 어떨까요?

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/View/MainView/ProjectManagerController.swift
> +        toDoViewdataSource?.apply(toDoViewSnapshot!)
강제 옵셔널 언래핑..?

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/View/MainView/ProjectManagerController.swift
> +                }
cell의 register, dequeue 과정은 프로젝트가 진행되며 계속 해야할 번거로운 작업으로 보이는데, identifier 자체를 입력하지 않도록 만들어볼 수 있을까요? 가능하면 타입캐스팅도 생략할 수 있다면 더 좋을 것 같네요.

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/View/MainView/ScheduleStackView.swift
> +    }
`super`의 메서드를 이용한 `SectionHeaderView`와 달리 `fatalError`를 이용하셨네요. 이 이니셜라이저의 역할은 무엇이고 언제 호출되나요? 이 이니셜라이저가 호출될 가능성이 없다고 판단하셔서 `fatalError`를 적용하셨던걸까요?

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/View/MainView/SectionHeaderView.swift
> +    private func circleAroundDigit(
[P5]
`Around` 대신 `Bordered`라는 표현을 사용하는건 어떨까요?

2022-09-13 06:28 UTC, ryan-son commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionScrollView.swift
> +    }()
`TextField` 요소 사용하고 있으니 HIG도 읽어볼까요? 보완할만한 내용이 있을까요?

- [Text fields - Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/components/selection-and-input/text-fields/)

2022-09-14 05:31 UTC, Jeon-Minsu commented on ProjectManager/.swiftlint.yml
> +  - trailing_whitespace
저희의 목적은 메서드를 구분하기 위하여 whiteSpaces를 사용하고 있습니다. 그러나, SwiftLint 적용시 클래스 내부의 메서드 간 줄간격을 하나만 주어도, 아래와 같은 오류가 발생합니다. 
```
Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
```

저희가 생각하는 코드 컨벤션은 메서드 간 구분을 위해 줄간격을 한 줄 주어야 한다고 생각하여 SwiftLint의 disabled_rules에 적용하였습니다. 라이언께서 코멘트해주신 Preferences에서 Text Editing > Editing 설정을 적용하여도 여전히 SwiftLint 에러 메시지가 발견되어 이와 같이 진행하였습니다.

2022-09-14 05:34 UTC, Jeon-Minsu commented on ProjectManager/.swiftlint.yml
> +  - ProjectManager
included는 SwiftLint 검사에 포함할 파일 경로를 작성하기 위하여 사용됩니다. 
확장성을 고려하여 Lint 검사가 필요없을 경로를 모두 Lint 검사에 포함하기 보다는 명시적으로 사용되는 지점을 표현하는 것이 좋지 않을까 생각하여 위와 같이 진행해보았습니다. 
이를 다시 고민해보니, SwiftLint에서 정의한 코드 컨벤션이 지정되지 않은 경로만을 따로 excluded로 표현하는 것이 더욱 좋은 방법이 아닐까 하는 의문도 듭니다. 예를 들어, 테스트 코드의 경우 SwiftLint 규칙을 적용할 필요가 없기때문에 excluded로 추후 적용하지 않음을 명시해주는 것도 하나의 방법일 것 같습니다!

2022-09-14 06:18 UTC, Jeon-Minsu commented on ProjectManager/ProjectManager.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +    },
Package.resolved 파일의 역할은 SPM을 통해 패키지의 최상위 수준에 있는 dependency 해결 결과를 기록하는 역할을 담당한다. 
.gitignore 파일을 통해 dependency 버전을 조정할 수 있습니다. 
이를 통해 얻을 수 있는 이점은 규모가 큰 프로젝트 단위에서 통일된 dependency 버전을 가질 수 있고, 이를 통해 conflict를 예방할 수 있습니다. 
또한, 기존 버전에서는 작동하던 기능이 업데이트를 통해 해당 기능을 지원하지 않을 수 있기 때문에, 버전을 동결시켜 팀원간 충분한 협의 끝에 업데이트 여부를 결정하는 것이 더욱 프로젝트를 안전하게 관리할 수 있다고 판단하였습니다. 
이러한 이점을 바탕으로 저희 또한 .gitignore 파일에 Package.resolved를 포함시켜보았습니다.

2022-09-14 06:19 UTC, Hugh-github commented on ProjectManager/ProjectManager.xcodeproj/xcshareddata/xcschemes/ProjectManager.xcscheme
> +   </BuildAction>
`.xcscheme` 같은 경우 빌드, 실행, 테스트, 성능 분석 등을 할 때 발생하는 작업 및 구성입니다.
`xcshareddata`는 공유 설정을 저장하는데 사용합니다.

2022-09-14 06:32 UTC, Jeon-Minsu commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
> +        })
load 후 completion 단계에서 에러가 발생할 시, 이를 처리해주는 코드를 fatalError로 작성해보았습니다.

2022-09-14 06:43 UTC, Hugh-github commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
> +        let context = persistentContainer.viewContext
`NSManagedObjectContext` 는 인스턴스에 대한 변경사항을 추적하고 인스턴스가 생성되고 해제될 때까지의 life - cycle을 관리합니다.
`NSPersistentContainer` 인스턴스는 모델, context 및 store coodinator를 한 번에 설정합니다. 
context는 life - cycle에서 유효성 검사, inverse relationship handling 및 undo/redo 에 이르기까지 life cycle에 중요한 역할을 하는 개체입니다. viewContext 같은 경우 main queue에 영구 container를 만들고 관리합니다.

2022-09-14 06:45 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionController.swift
> +    private func configNavigationItems() {
configureNavigationItems로 수정했습니다.

2022-09-14 06:45 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionController.swift
> +    @objc private func didTappedDoneButton() {
didTapDoneButton으로 수정했습니다.

2022-09-14 06:46 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/MainView/SectionHeaderView.swift
> +    private func circleAroundDigit(
Around를 Bordered로 수정했습니다!

2022-09-14 07:30 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/MainView/ProjectManagerController.swift
> +        toDoViewdataSource?.apply(toDoViewSnapshot!)
강제 옵셔널 언래핑 제거했습니다.

2022-09-14 07:34 UTC, Jeon-Minsu commented on ProjectManager/ProjectManager/View/MainView/ScheduleStackView.swift
> +    }
해당 이니셜라이저는 xib 나 스토리보드에서 생성이 될때 init(coder: NSCoder) 를 통해서 객체가 생성됩니다.
라이언의 코멘트를 통해 다시 고민해보니, 혹시라도 사용될 가능성을 염려하여, super.init(coder: coder)로 리팩토링 진행하였습니다.

2022-09-14 08:02 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/MainView/ProjectManagerController.swift
> +                }
디스코드에서 알려주신 방향으로 수정했습니다 👍

2022-09-14 08:05 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/MainView/ProjectManagerController.swift
> +                }
디스코드에서 알려주신 방향으로 수정했습니다 👍

2022-09-14 08:06 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/MainView/ProjectManagerController.swift
> +        )
타입 프로퍼티로 수정했습니다. 해당 프로퍼티는 STEP 2-3 진행하면서 제거할 예정입니다.

2022-09-14 08:12 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionScrollView.swift
> +        datePicker.minimumDate = Date()
init을 통해 외부에서 주입해 주도록 주성했습니다.

2022-09-14 08:19 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionScrollView.swift
> +    }()
Text Field에 clear Button이 필요할 것 같아 추가했습니다.

2022-09-14 08:39 UTC, Jeon-Minsu commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
> +        }
해당 작업을 save(_ context: NSManagedObject) 메서드를 통해 분리하였고, do-catch 문을 통해 저장 실패의 경우, DatabaseError.failedContextSave 에러를 throw하여 기존의 에러와 구분이 갈 수 있도록 처리해보았습니다.

2022-09-14 09:17 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionScrollView.swift
> +final class ProjectAdditionScrollView: UIScrollView {
Text View의 scroll은 불가능하게 설정하고 ScrollView의 bounds가 늘어나도록 설정했습니다.

2022-09-14 09:43 UTC, Jeon-Minsu commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
> +    }()
프로젝트 내부에서는 in memory 방식이 아닌 on disk 방식으로 사용하는 것이 맞다고 생각합니다.
대신, 테스트의 경우에는 in memory 방식을 통해 Container를 생성하여 CRUD 메서드를 테스트하는 것이 더욱 적절하다 판단하여, MockLocalDatabaseManager 및 InMemoryCoreDataContainer를 생성하였습니다.

2022-09-15 02:00 UTC, ryan-son commented on ProjectManager/.swiftlint.yml
> +  - trailing_whitespace
먼저, trailing whitespace는 연속된 코드에서 코드가 작성되지 않은 라인에 들여쓰기 (indentation)만 존재하는 경우를 의미합니다. 제가 말씀드린 설정은 새로 편집되는 내용에 한해 적용되므로 기존에 있던 trailing whitespace를 제거해주지는 않습니다. 기존에 있던 것들을 지워주려면 SwiftLint autocorrection을 이용하는 방법을 이용해볼 수 있습니다. 제가 말씀드린 옵션이 어떤 기능을 하는지 궁금하시다면 타입 내 함수, 프로퍼티 정의 및 구현 등 자동 들여쓰기가 적용되는 구간에서 return (enter) 키를 누르고 편집하지 않은 상태로 엔터키로 이동한 라인이 아닌 라인으로 이동했다 돌아와보세요. 들여쓰기가 적용되어있지 않을겁니다. 물론 이 rule을 적용할지 무시할지 여부에 대해서는 여러분이 결정하시면 됩니다.

2022-09-15 02:02 UTC, ryan-son commented on ProjectManager/.swiftlint.yml
> +  - ProjectManager
일반적으로는 수꿍이 말씀하신대로 검사 대상을 명시하는 방식보다 검사하지 않을 대상을 명시하는 방식을 사용하고 있습니다. 검사에서 제외할 대상은 대부분 외부 의존성인 Pods 폴더 등이 있습니다.

2022-09-15 02:25 UTC, ryan-son commented on ProjectManager/ProjectManager.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +    },
1. 여러분이 말씀해주신 내용에 따르면 외부 의존성의 버전을 고정하려면 `Package.resolved` 파일을 `.gitignore`에 포함시키지 않는 편이 좋지 않을까요?
2. conflict이라는 표현보다는 의존하는 라이브러리에서 제공하는 API가 동일하므로 동일한 기능 제공을 보장한다는 표현이 괜찮을 것 같아요. `Package.resolved`를 공유하지 않는 팀이라면 `upToNextMajor` 또는 `upToNextMinor` 설정을 통해 유사한 버전을 사용함으로써 라이브러리에서 제공하는 API가 호환성이 있음을 기대할 수 있다라고 표현할 수 있겠네요.
3. 2에서 말씀드렸듯이 `Package.resolved`를 이용하지 않아도 `Project > Package Dependencies`에서 `upToNextMajor`, `upToNextMinor`, `exact` 설정을 통해 라이브러리의 버전을 통제할 수 있어요. 여러 프레임워크 또는 라이브러리에서 사용하는 Versioning 방식에 대해 더 알아보려면 `Semantic versioning` 또는 `유의적 버전`이라는 키워드로 알아보시면 됩니다.
4. 여러분의 `.gitignore` 파일을 열어보았더니 유사한 내용이 네 번 반복해서 사용되고 있는 것을 확인했어요. 정리해보시면 좋을 것 같습니다.

2022-09-15 02:29 UTC, ryan-son commented on ProjectManager/ProjectManager.xcodeproj/xcshareddata/xcschemes/ProjectManager.xcscheme
> +   </BuildAction>
이 내용을 git을 통해 팀 내부에서 공유하는 것에 대해 여러분들은 어떻게 생각하시나요?

2022-09-15 02:30 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
> +        })
그렇게 작성하신 이유를 함께 공유해주시면 더 좋을 것 같아요.

2022-09-15 02:35 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
> +    }()
로직은 동일하고 저장 공간만 다른 것이라면 Mock을 두지 않고 `NSPersistentStoreDescription`의 URL을 in memory로 변경하여 사용할 수 있도록 구성하는 방법도 생각해볼 수 있을 것 같아요.

2022-09-15 02:38 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
> +        let context = persistentContainer.viewContext
좋습니다! viewContext가 main queue와 연관된 context임을 알았으니 context에서 무거운 작업을 수행해야 할 때는 적합하지 않다는 것을 느끼셨을거에요. 이를 위해 백그라운드에서 동작하는 context를 만들고 private queue에서 작업을 수행할 수 있는데, 필요하다면 이 내용에 대해서도 파악해봅시다.

2022-09-15 02:43 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
> +        }
[P2]
좋습니다. 여기에서 생각해볼 수 있는 것은, `CoreData`와 같은 프레임워크에서 기본적으로 제공하는 에러가 문제 해결에 큰 도움이 될 수 있기 때문에 `failedContextSave` 케이스에 associated value를 정의하여 프레임워크에서 발생한 에러를 함께 제공해주면 더 좋을 것 같습니다.

2022-09-15 02:48 UTC, ryan-son commented on ProjectManager/ProjectManager/View/MainView/ProjectManagerController.swift
> +        )
여러분의 선택이지만 `UUID`와 `Date`만 테스트 가능한 형태로 변경하면 프리뷰나 테스트 목적으로 사용할 수 있을 것 같으니 그냥 두어도 괜찮을 것 같습니다. 다만 기존 로직과의 명확한 구분을 위해 extension 또는 mark 주석을 이용해 분리해두면 좋겠네요.

2022-09-15 02:50 UTC, ryan-son commented on ProjectManager/ProjectManager/View/MainView/ScheduleStackView.swift
> +    }
확신이 있으시다면 그렇게 처리하셔도 괜찮습니다. 다만 이와 유사하게 절대 일어날리 없다고 확신하는 로직의 경우에는 원격 환경에서 로그를 받아볼 수 있도록 구성하여 문제가 발생하더라도 대응할 수 있게 구성해 두실 것을 권장드립니다.

2022-09-15 03:25 UTC, ryan-son approved these changes
여러분 고생 많으셨습니다. 피드백을 몇 개 남겨두었으니 참고하시고 필요하시다면 다음 과정에서 고려해보시면 되겠습니다.

제가 코멘트에서 P 태그를 사용하고 어떤 의미인지는 설명해두지 않았더라구요. 아래에 설명 남겨두겠습니다.

# 개별 피드백 P 태그 안내
각 코멘트에는 P1 ~ P5까지의 태그가 포함되어있습니다. 태그의 의미는 아래와 같으니 참고하세요. [뱅크샐러드 개발 문화](https://blog.banksalad.com/tech/banksalad-code-review-culture/)에서 차용하였습니다.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/69730931/176375527-04436d3c-bb00-4abd-a1d9-224b1c65b9eb.png">

그럼 언제나처럼 도움이 필요하시거나 이해가 되지 않는 피드백이 있다면 언제든지 말씀해주세요. 😄

2022-09-15 03:25 UTC, ryan-son commented on ProjectManager/ProjectManager/Model/ProjectUnit.swift
> +    )
개별 피드백에서도 작성해두었듯이 이 내용을 프리뷰 또는 테스트 목적으로 활용하되, `UUID`, `Date`와 같은 요소를 예측 가능한 형태 (하드코딩 등)로 구성하여 테스트가 가능하고 원하는 형태로 보이게끔 만들어보시는 것도 좋아요. 기존 로직과의 혼동을 방지하기 위해 extension이나 mark 주석을 이용해 분리해보는 방법도 고려해보시면 좋을 것 같아요.

2022-09-15 03:25 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
> +    }()
`LocalDatabaseManager`가 제공하는 API의 로직이 동일하다면, database manager 인스턴스를 생성할 때 `NSPersistentContainer`의 `NSPersistentStoreDescription`의 URL을 in memory 형식의 URL로 변경하여 사용할 수 있도록 구성하는 방법도 고려해볼 수 있을 것 같아요.

2022-09-15 03:25 UTC, ryan-son commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionScrollView.swift
> +final class ProjectAdditionScrollView: UIScrollView {
이전에는 스크롤뷰의 크기가 페이지와 동일해서 상하좌우 제약을 스크롤뷰에 잡아주면 크기를 알 수 있었지만, 스크롤뷰에서 스크롤이 가능해지니 text view가 어디까지 늘어나야할지 모를 것 같네요. 어떻게 해결해볼까요?

2022-09-15 03:25 UTC, ryan-son commented on README.md
> +```
향후 문서를 읽어볼 다른 사람의 혼동을 방지하기 위해 변경사항이 생기면 문서도 함께 최신화해주는 것도 중요합니다. 열심히 하시고 계신 것 같네요~! 👍

2022-09-15 03:27 UTC, merged