프로젝트 관리 앱 [STEP 2] Groot
yagom-academy/ios-project-manager pull request #191
Opened 2022-09-13 15:26 UTC by Groot-94

안녕하세요 제이크 @jryoun1 

Step2 도 잘 부탁드립니다!
이번 프로젝트는 기본적으로 MVC와 객체지향을 최대한 지키려고 노력하면서 진행했습니다.
객체지향과 MVC 구조를 제대로 지켰는지 집중적으로 봐주시면 감사하겠습니다!
그리고 PR 제출 후 MVVM 패턴도 가능하면 적용해보려고 합니다:)

## 📌 배경
- 프로젝트를 관리 할 수 있는 앱 구현
## 📌 작업 내용
- Project를 관리하는 Model 구현 (CRUD)
- Project를 List로 보여주기 위한 TableView 구현
- Project를 생성 및 수정화면 구현
- Model의 Project CRUD를 뷰와 연결
- Data에 맞춰 뷰 상세 화면 구현
### 화면구성
||
|:---:|
|프로젝트 추가 화면||
| <img src = "https://i.imgur.com/IHQMv8X.gif" width="800" height="500">|
|프로젝트 상태 이동 화면||
| <img src = "https://i.imgur.com/i74yEzg.gif" width="800" height="500">|
|프로젝트 편집 화면||
| <img src = "https://i.imgur.com/Ay55tR5.gif" width="800" height="500">|
|프로젝트 삭제 화면||
| <img src = "https://i.imgur.com/iUfo9mg.gif" width="800" height="500">|
## 📌 테스트 방법
- 아이패드 시뮬레이터를 사용하여 테스트합니다.
## 📌 리뷰 노트
### 📍 느낀 점
#### 🔗 MVC 패턴을 적용하여 구현하면서 느낀 점
- 저는 이번 프로젝트에서 함수는 최대 15줄, 파일은 최대 250줄을 지키려고 했으나 MVC 패턴을 적용하면서 viewController에서 굉장히 많은 일을 처리하고 있어 controller의 길이를 250줄 이하로 지키지 못 했습니다.
- tableView의 reloadData를 여러군데에서 호출하게되는 중복코드가 많았습니다.
- 기능을 분리하는 부분에서 controller의 많은 함수들이 서로 의존하고 있어서 리팩토링에 어려움이 많았습니다.
### 📍 고민했던 점
#### 🔗 비동기 처리를 어디서 사용해야 할 지.
- 이번 스텝은 어떤 부분에서 비동기 처리를 사용해야 하는지 감이 오지 않았습니다. 현재는 CoreData나 Firebase를 사용하지 않기 때문에 비동기 처리가 필요가 없는건지 아니면 제가 아직 프로젝트를 이해하지 못 하는지 궁금합니다..
#### 🔗 Singleton pattern 지양하고 여러 ViewController에서 Data 처리를 어떻게 할 지.
- 아래와 같은 이유로 가능하면 Singleton pattern을 사용하지 않기 위해서 고민을 했습니다.
    1. Singleton pattern을 사용해 클래스간 결합도가 높아지게 되면, 유지보수가 힘들고 테스트도 원활하게 진행할 수 없는 문제점이 발생한다.
    2. 멀티 스레드 환경에서 동기화 처리를 하지 않았을 때, 인스턴스가 2개가 생성되는 문제도 발생할 수 있습니다.
- UpdateViewController를 분리하면서 Data 처리를 어떻게 할 지 고민을 하다 Delegate pattern을 사용해서 처리하였습니다. 제가 적용한 방법이 혹시 문제가 있다면 의견주시면 감사하겠습니다!
#### 🔗 TextView 클릭 시 나타나는 경고메세지.
- TextView를 클릭 시 아래와 같은 경고가 나타났습니다.
![](https://i.imgur.com/TriXZCY.png)

![](https://i.imgur.com/FfQPwvq.png)
- 이 문제를 해결하기 위해 WTF에 메세지를 입력해봤으나 이해할 수 없어서 `TUISystemInputAssistantView` 키워드 검색을 통해 StackOverFlow에서 관련 문제에 대해 찾았습니다.

`The layout constraint error message has nothing to do with your layout.
It's an internal issue (could be considered a bug) with the Input Assistant View - the auto-complete options shown above the keyboard.`

- 자동완성 뷰 내부에서 생기는 문제라는 글을 보고 텍스트 뷰에 **textView.autocorrectionType = .no** 옵션을 추가하여 경고창이 뜨지 않도록 했습니다.
- 제가 해결한 방법이 정상적인 방법인지 단순한 편법일지 혹시 알고계시다면 답변 해주시면 감사하겠습니다!

[참고사이트](https://stackoverflow.com/questions/61687035/swift-textfields-always-show-layout-constraint-error)

2022-09-15 13:58 UTC, jryoun1 requested changes
@Groot-94 
고생하셨습니다! 
전반적으로 코드를 잘 작성해주셔서 읽기가 편했던 것 같네요. 💯👍🏻

말씀하셨던 것처럼 현재는 비동기로 처리가 될 만한 부분은 없는 것 같아보입니다. 
Coredata, Firebase를 사용하게 될 때 비동기 처리가 필요해보이네요 🙂

싱글톤을 지양하신 이유를 잘 설명해주신 것 같고, 이를 delegate pattern을 사용해서 처리하신 부분도 좋은 것 같네요 👏👍🏻

다만 몇 가지 수정이 되었으면 하는 사항들이 있어서 코멘트를 남겨두었습니다. 
확인부탁드릴게요~

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager.xcodeproj/project.pbxproj
>  		};
대체로 grouping을 잘해주신 것 같아요. 👏
다만 AppDelegate, SceneDelegate, LaunchScreen이 Resource에 포함되는것이 어색한 것 같습니다.

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/DataModel/ProjectDTO.swift
> +    }
서버와 동일한 key값들을 사용하는 것 같은데 CodingKeys를 정의하신 이유가 있을까요?

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/DataModel/ProjectDTO.swift
> +struct ProjectDTO: Decodable {
DTO라고 뒤에 접미사를 붙인 이유가 궁금합니다 🙋‍♂️

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/DataModel/ProjectDAO.swift
> +struct ProjectDAO {
여기도 DAO라는 네이밍을 붙인 이유가 궁금합니다 🙋‍♂️

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/DataModel/ProjectDAO.swift
> +        data = data.filter { $0.id != id }
removeAll(where:)을 사용할수도 있을 것 같은데 filter를 사용하신 이유가 있을까요?
두 개의 차이점은 무엇일까요?

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/DataModel/ProjectDAO.swift
> +    }
update라고 했을 때 기본적으로 떠오르는 update 로직과는 조금 다른 로직인 것 같습니다. 🤔
만약 서버에서 생성 날짜와 수정 날짜를 기록하고, 이를 통해서 `최근 수정순`, `작성된 날짜순` 이런 정렬을 가져가려고 한다면 이 방법으로는 해결이 되지 않을 것 같은데 어떻게 생각하시나요? 

추가로 edit를 하게 되면 지금은 삭제되었다가 다시 append되어서, 해당 할일이 가장 아래로 붙게 되는데 개인적으로는 좋은 UX라고 생각이 되지는 않는 것 같습니다.

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Extension/Date+Extension.swift
> +        dateFormatter.dateStyle = .long
dateStyle이 명세서에 나와있는 형식과 다른 것 같은데 확인부탁드려요.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/45090197/190405403-5c66864b-5e39-4d61-9168-6671adc10b9f.png" >

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Resource/AppDelegate.swift
> +final class AppDelegate: UIResponder, UIApplicationDelegate {
final을 붙여주셨네요 👏

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Resource/SceneDelegate.swift
> +        mainViewController.view.backgroundColor = .systemBackground
해당 vc의 속성을 여기서 설정해주는 이유가 있을까요?

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/Controller/ProjectManagerViewController.swift
> +    static let navigationTitle: String = "PROJECT MANAGER"
이 변수들만 타입명시를 해주셨는데 특별한 이유가 없다면 convention을 통일해주세요 🙏🏻

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/Controller/ProjectManagerViewController.swift
> +        self.view.addGestureRecognizer(longPress)
self를 사용하시는 기준이 궁금합니다 🙋‍♂️

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/Controller/ProjectManagerViewController.swift
> +    }
이 함수 이후 다음 코드를(함수) 작성하실 때 순서가 이 함수 내부 함수의 호출 순서대로 작성되면 좀 더 읽기 편할 것 같아요 🙏🏻 전반적으로 프로젝트 내부 모든 코드를 작성할 때도 함수의 작성순서를 고려해주세요!

지금은 이 함수 아래에 `showAlert` 가 있는데 그것보다는 `longPressGesture` 함수가 먼저 나오는 것이 읽기 편할 것 같아요. 그렇지 않으면 해당 함수의 동작을 확인하기 위해서 수직 스크롤을 많이하게 될 것 같네요 😭
이와 관련해서는 [글](https://data-make.tistory.com/635)을 참고해보시면 좋을 것 같아요.

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/Controller/ProjectManagerViewController.swift
> +                                         handler: actionHandlers[1])
배열의 직접 index로의 접근은 crash를 유발할 가능성이 있습니다. 🚨
subscript를 사용하거나 first, last와 같은 프로퍼티를 사용해보는 건 어떨까요 🤔

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/Controller/ProjectManagerViewController.swift
> +        default: return [nil]
convention관련 질문이 있습니다. 🙋‍♂️
줄바꿈을 하는 기준이 있을까요?

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/Controller/ProjectManagerViewController.swift
> +        tableViewsReloadData(todoTableView, doneTabelView, doingTableView)
실제로 바뀐 tableview들만 reload를 하는 것이 아니라 모든 tableview를 reload하는 이유가 있을까요? 🤔

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/DataModel/ProjectState.swift
> +            return ("Move To TODO", "Move To DONING")
DONING 오타가 있네요 🙂

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/Controller/ProjectManagerViewController.swift
> +        default: return nil
여기도 convention관련 위에 질문과 동일합니다 🙏🏻

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/Controller/ProjectManagerViewController.swift
> +       let navigationController = configurePresentNavigationController(item: item)
intent가 다른것 같아요🙏🏻

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/View/ProjectTableHeaderView.swift
> +        stackView.axis  = .horizontal
띄어쓰기가 두 번 된 것 같네요

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/View/ProjectTableHeaderView.swift
> +        stackView.distribution = .fill
distribution의 기본값은 fill입니다 🙏🏻

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/View/ProjectTableHeaderView.swift
> +    }
어떤 곳에서는 NSLayoutConstraint.activate를 사용하고 어떤 곳에서는 .isActive 를 사용하시는데 둘을 사용하는 기준이 따로 있으신가요? 🙋‍♂️

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/View/ProjectTableViewCell.swift
> +
불필요한 줄바꿈은 제거해주세요.

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerUpdate/Controller/ProjectUpdateViewController.swift
> +final class ProjectUpdateViewController: UIViewController {
프로젝트를 생성할 때도 동일한 vc를 사용하는데 네이밍이 update로 되어있어서 오해를 일으킬 수도 있을 것 같네요. 
생성할때와 업데이트 할 때 두 가지를 포괄하는 이름은 없을까요? 🙋‍♂️

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerUpdate/View/ProjectUpdateView.swift
> +        stackView.axis  = .vertical
여기도 space가 2번 들어갔네요

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerUpdate/View/ProjectUpdateView.swift
> +        textView.autocorrectionType = .no
말씀하셨던 이슈는 apple의 textview에서 발생하고 있는 이슈가 맞는 것 같네요. 
관련해서도 [논의](https://github.com/hackiftekhar/IQKeyboardManager/issues/1616)가 있었고, 수정하신 방법대로 수정하면 해결된다고 하네요 👍🏻👏

2022-09-15 13:58 UTC, jryoun1 commented on ProjectManager/ProjectManager/Scene/ProjectManagerUpdate/View/ProjectUpdateView.swift
> +
불필요한 줄바꿈은 지워주세요.

2022-09-15 14:02 UTC, jryoun1 commented
추가로 firebase, coredata를 적용하는 부분은 step2-1에서 적용하실 예정이신가요?

2022-09-16 01:56 UTC, Groot-94 commented on ProjectManager/ProjectManager/DataModel/ProjectDAO.swift
> +        data = data.filter { $0.id != id }
찾아보니 removeAll(where:)은 값을 복사해서 다시 리턴해주는 형태가 아닌 배열의 값 자체를 지우는 방법이고, filter는 filtering된 값을  제거한 값을 복사해 다시 리턴해주는 방식임을 알게되었습니다.

현재 기능에는 removeAll이 더 적합하다고 생각해서 수정했습니다 :)

2022-09-18 16:07 UTC, Groot-94 commented on ProjectManager/ProjectManager.xcodeproj/project.pbxproj
>  		};
application 그룹을 만들어서 AppDelegate, SceneDelegate를 넣어주었습니다 :)

다른 코드를 참고해보니 Resources의 Base.lproj 라는 폴더에 LaunchScreen을 넣어주는 형태로 보여서 Base.lproj 폴더에 넣어주려고 했습니다.
확인해보니 기본적으로 Base.lproj라는 폴더에 LaunchScreen이 있는거로 확인했습니다.. 
Base.lproj 폴더가 궁금해서 찾아보니 Localization을 관리하는 폴더라는 내용을 봤는데 여기에 왜 LaunchScreen이 들어있는지 궁금증이 생겼습니다..

2022-09-18 16:10 UTC, Groot-94 commented on ProjectManager/ProjectManager/DataModel/ProjectDTO.swift
> +    }
이 부분은 저도 모르게 습관적으로 사용했던 것 같습니다.. 수정했습니다.

2022-09-18 16:33 UTC, Groot-94 commented on ProjectManager/ProjectManager/DataModel/ProjectDAO.swift
> +struct ProjectDAO {
DAO(Data Access Object)라는 뜻으로 실제로 데이터의 CRUD를 담당한다고 생각해서 이름을 붙였습니다.
가능하면 축약형을 쓰지 않아야 하는게 맞다고 생각해서 수정했습니다 :)

2022-09-18 16:35 UTC, Groot-94 commented on ProjectManager/ProjectManager/DataModel/ProjectDTO.swift
> +struct ProjectDTO: Decodable {
DTO(Data Transfer Object)는 코어데이터나 FireBase에서 저장되어있는 데이터를 변환하기 타입이라 생각해서 사용해봤습니다.
조금 더 명확하게 Model 로 수정하였습니다.

2022-09-18 16:37 UTC, Groot-94 commented on ProjectManager/ProjectManager/DataModel/ProjectDAO.swift
> +    }
이 부분도 말씀해주신  내용을 보고 수정해야 한다고 생각해서 실제 데이터를 제거하고 추가해주는 방법이 아닌 데이터를 교체해주는 방법으로 수정했습니다.

2022-09-19 03:14 UTC, Groot-94 commented on ProjectManager/ProjectManager/Extension/Date+Extension.swift
> +        dateFormatter.dateStyle = .long
수정했습니다!

2022-09-19 03:16 UTC, Groot-94 commented on ProjectManager/ProjectManager/Resource/SceneDelegate.swift
> +        mainViewController.view.backgroundColor = .systemBackground
단순하게 초기 Scene을 설정하는 부분이라 생각해서 배경도 설정해줘도 괜찮을거다 라고 생각했습니다. 
다시 생각해보니 해당 View의 설정은 View 내부에서 하는게 가장 좋다고 생각해서 수정했습니다.

2022-09-19 04:36 UTC, Groot-94 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/Controller/ProjectManagerViewController.swift
> +        default: return [nil]
기본적으로 90자를 기준으로 줄바꿈을 하려고 했으나 ","에서 줄바꿈을 하도록 수정했습니다 :)

2022-09-19 04:48 UTC, Groot-94 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/Controller/ProjectManagerViewController.swift
> +        default: return nil
고차함수도 90자를 기준으로 구분하려고 했으나, 모든 고차함수를 통일성있게 줄바꿈 해주는게 좋다고 생각이 들어서 수정했습니다.

2022-09-19 04:49 UTC, Groot-94 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/View/ProjectTableHeaderView.swift
> +        stackView.distribution = .fill
기본값은 제거해주는 방향으로 수정했습니다. :)

2022-09-19 04:51 UTC, Groot-94 commented on ProjectManager/ProjectManager/Scene/ProjectManagerList/View/ProjectTableHeaderView.swift
> +    }
설정값이 여러개이면 NSLayoutConstraint.activate를 사용하고 단일일 경우엔 isActive로 해줘도 괜찮다고 생각했습니다.
이 부분도 통일성을 주는게 좋다고 생각이 들어서 수정했습니다 :)

2022-09-19 05:26 UTC, Groot-94 commented on ProjectManager/ProjectManager/Scene/ProjectManagerUpdate/Controller/ProjectUpdateViewController.swift
> +final class ProjectUpdateViewController: UIViewController {
기존 Manager VC를 List로 수정하고, 관리한다는 의미를 사용해서 Update VC를 management로 수정했습니다

2022-09-19 05:29 UTC, Groot-94 commented on ProjectManager/ProjectManager/Scene/ProjectManagerUpdate/View/ProjectUpdateView.swift
> +        textView.autocorrectionType = .no
감사합니다!

2022-09-22 08:44 UTC, Groot-94 commented
@jryoun1 
안녕하세요 제이크..!
MVVM + Clean-Architecture를 처음 공부해보고 적용하느라 시간이 많이 걸렸습니다.... 하지만 아직도 모르겠습니다.
MVVM 자체도 어려운데 Clean-Architecture를 적용하려고 했던게 무리였다는 생각이 듭니다..ㅎㅎ
그리고 ViewModel에서 어디까지 처리를 해줘야 할 지 몰라 최대한 View는 그냥 보여주기만 한다는 생각으로 했습니다...

2022-09-24 07:02 UTC, jryoun1 requested changes
@Groot-94
고생하셨습니다 👏

처음으로 mvvm, clean-architecture를 적용해보셨을텐데 잘 적용해주셨네요 👍🏻💯

다만 코드 리뷰에도 남겨두었지만, 현재 vm과 repository들이 전부 특정 타입에 종속이 되어있습니다.
mvvm, clean-architecture를 적용하는 이유 중에 하나는 테스트 코드를 작성하기 쉽게 각 타입, 레이어간의 종속성을 없애려고 합니다. 그러나 지금 작성해주신 코드들은 init 시점에 특정 타입들을 주입받는 형식이 아닌 전부 특정 타입으로 종속이 되어있습니다.
해당 부분 한 번 확인해주세요 🙏🏻

또한 한 가지 개선되었으면 하는 부분이 있습니다.
아래와 같이 이미 생성된 프로젝트를 눌렀을 때 asis는 항상 오늘 날짜로 캘린더가 표시되게 됩니다.
해당 부분을 저장되어있는 날짜가 표시되도록 하면 좀 더 사용자 친화적인 UX가 될 것 같습니다.
예를 들어 아래 이미지의 경우에는 9월 24일이 아닌 2월 22일로 처음에 표시되는 것을 말씀드린 것입니다 🙏🏻
해당 부분은 필수는 아니니 추후에 개선해보셔도 좋을 것 같아요!
<img src="https://user-images.githubusercontent.com/45090197/192084695-33df490d-cac3-4191-a1a7-a3950f887d3c.png" width=500 height=350>

나머지는 코멘트 확인해주시면 감사하겠습니다 🙇🏻‍♂️

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Data/Protocol/ProjectRepositoryProtocol.swift
> +protocol ProjectRepositoryProtocol {
프로토콜 네이밍을 지을 때 꼭 뒤에 protocol이 붙지 않아도 될 것 같네요. 🙏🏻

~Repository, ~Usecase와 같은 것들은 주로 **명사**로 작성합니다. 
예를 들면 Swift의 **Collection** protocol이 명사로 지어진 네이밍이 될 수 있겠네요. 

반면에 할수있음을 나타내는 프로토콜의 경우에는 아래와 같은 **suffix**가 주로 붙게 됩니다. 
`~able, ~ible, ~ing` 
예를 들면 **Equatable**가 될 수 있겠네요.

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Domain/UseCase/Protocol/ProjectUseCaseProtocol.swift
> +protocol ProjectUseCaseProtocol {
여기도 동일합니다. 네이밍에 Protocol은 없어도 될 것 같아요 🙏🏻

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Data/TemporaryRepository/TemporaryProjectRepository.swift
> +    private var temporaryStore: [ProjectModel]
`~store`라는 네이밍은 저장소이기 때문에 지어진걸까요?
사실상 저장소가 아닌 ProjectModel의 배열이므로 `projects` 라고 지어도 괜찮아보입니다.

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Data/TemporaryRepository/TemporaryProjectRepository.swift
> +struct TemporaryProjectRepository: ProjectRepositoryProtocol {
class가 아닌 struct 타입으로 생성한 이유가 있을까요? 🙋‍♂️
두 개의 차이점은 무엇일까요?

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Data/TemporaryRepository/TemporaryProjectRepository.swift
> +    }
주입을 받는 것이 아닌 빈배열로 초기화를 시켜주고 있는데, 이렇게 되면 추후에 TemporaryProjectRepository에 대한 테스트 코드를 작성하기 어려울 것 같습니다. 

주입을 받는 것과 어떠한 차이가 있을까요?

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Domain/UseCase/ProjectUseCase.swift
> +    }
여기도 위의 코멘트와 동일합니다. 
ProjectUseCase는 ProjectRepositoryProtocol을 준수하는 타입을 주입받는 것이 아니라 항상 TemporaryProjectRepository()로 초기화가 되고 있습니다.
이렇게 되면 해당 useCase가 다른 repository를 사용해야하는 경우에는 또 다른 타입이 생성이 되어야할 것 같네요. 🤔

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Domain/UseCase/ProjectViewModel.swift
> +//  ProjectTranslater.swift
파일 이름이 잘못된 것 같습니다.

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Domain/UseCase/ProjectTranslater.swift
> +}
해당 프로토콜과 프로토콜의 extension을 구현해주신 이유가 궁금합니다 🙋‍♂️

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Domain/UseCase/ProjectUseCase.swift
> +    var repository: ProjectRepositoryProtocol
외부에서 접근할 수 있을 것 같은데, 의도하신 걸까요?

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/View/ProjcetListView.swift
> +final class ProjcetListView: UIView {
오타가 있는것 같네요 🙏🏻

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/View/ProjectListViewController.swift
> +    private let mainView = ProjcetListView()
가능하다면 생성하는 인스턴스와 비슷한 이름을 가져가는 것이 좋을 것 같네요. 
`mainView` 보다는 `listView` 가 더 괜찮을 것 같은데 어떻게 생각하시나요 🙋‍♂️

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/View/ProjectListViewController.swift
> +    private func configureObserverBind() {
모든 함수명을 꼭 configure로 시작하지는 않아도 될 것 같아요.
bindObservers() 라고 해도 될 것 같아요.

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/View/ProjectListViewController.swift
> +    }
개인적으로 코드를 읽을 때 순서대로 읽히는 것을 선호합니다.
`viewModel.todoListObserverBind` 보다는
`viewModel.bindTodoListObserver` 라는 함수명으로의 변경은 어떠할까요? 
실제로 사용하는 곳에서 어떻게 읽히게 될지를 고민해서 네이밍을 지으면 좋을 것 같아요 🙏🏻

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/View/ProjectListViewController.swift
> +    }
이 함수는 실제로 사용되는 부분이 아래 이후인 것 같은데, 가능하다면 실제 호출되는 부분 아래에 있으면 코드 읽기가 편할 것 같네요. 
```swift
// MARK: - Extension UITableViewDataSource
```

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/View/ProjectListViewController.swift
> +        let deleteSwipeActions = viewModel.makeSwipeActions(state: state,
삭제 액션 하나 인 것 같은데 ~actions라는 복수형이 붙은 이유가 있을까요? 🙋‍♂️

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/View/ProjectTableHeaderView.swift
> +//  TableHeaderView.swift
파일명과 클래스 명을 통일해주세요!

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/ViewModel/ProjectListViewModel.swift
> +    }
여기도 위에서 드린 코멘트와 동일합니다.
viewModel을 가지고 테스트 코드를 짠다고 했을 때, 현재 ProjectListViewModel은 ProjectUseCase에 종속이 되어있습니다. 
이보다는 ProjectUseCase를 추상화한 프로토콜 타입인 ProjectUseCaseProtocol을 채택하는 타입을 주입받을 수 있도록해서, viewModel을 떼어내서 테스트 코드를 작성한다고 할 때, mock usecase를 넣어서 사용할 수 있도록 구현해주세요 🙏🏻

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/ViewModel/ProjectListViewModel.swift
> +    private var doneListObserver: Observable<[ProjectViewModel]>
뒤에 `~Observer`를 꼭 붙이지 않아도 될 것 같습니다. 🙏🏻
`todoList`라고만 해도 될 것 같아요.

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/ViewModel/ProjectListViewModel.swift
> +    }
위에서 언급했는데 함수명 한 번 고민해봐주세요!

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/ViewModel/ProjectListViewModel.swift
> +    func configureNumberOfRow(state: ProjectState) -> Int {
함수명에 configure는 없어도 될 것 같아보입니다!

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/ViewModel/ProjectListViewModel.swift
> +    func makeTableHaederView(state: ProjectState) -> ProjectTableHeaderView {
함수명에 오타가 있는 것 같아요.

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/ViewModel/ProjectListViewModel.swift
> +    }
이 함수의 코드 내 위치도 다시 한 번 고민해봐주세요.

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/ViewModel/ProjectListViewModel.swift
> +              let lastActionHandler = actionHandlers.last
index를 통한 접근을 잘 수정해주셨네요 👏

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/ViewModel/ProjectListViewModel.swift
> +    }
이 함수명의 네이밍이 fetch인데 실질적으로 하는 것은 useCase에서 read한 것들을 분류해서 값들을 업데이트 하고 있는 것 같습니다. 
fetch는 해당 값을 가져올 때 사용합니다. 예를들면 서버로부터 list를 가져오면 fetchList 와 같이 사용하게 됩니다. 다른 함수명을 고민해봐주세요!

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectManagement/View/ProjectManagementView.swift
> +final class ProjectManagementView: UIView {
ProjectDetailView는 어떨까요? 
Management는 관리해주는 view인것 같은데 어떻게 생각하시나요? 🙋‍♂️

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectManagement/View/ProjectManagementView.swift
> +        stackView.axis  = .vertical
space가 2개 군요 👀

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectManagement/View/ProjectManagementViewController.swift
> +        view.addSubview(projectManagementView)
이 부분은 configureViewLayout()함수에 같이 포함되도 괜찮을 것 같아요.

2022-09-24 07:02 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectManagement/View/ProjectManagementViewController.swift
> +    private let projectManagermentViewModel = ProjectManagermentViewModel()
listView쪽과는 다르게 projectManagement를 앞에 붙여준 이유가 있을까요? 🙋‍♂️

이미 해당 클래스가 ProjectManagementViewController이므로 viewModel과 같은 general한 이름을 사용해도 될 것 같아요.

2022-09-26 06:31 UTC, Groot-94 commented on ProjectManager/ProjectManager/Data/TemporaryRepository/TemporaryProjectRepository.swift
> +struct TemporaryProjectRepository: ProjectRepositoryProtocol {
class와 struct의 가장 큰 차이점은 참조와 값 타입이라고 생각합니다. 현재까진 참조타입이나 상속을 사용하지 않기 때문에 class를 사용해야 할 이유가 없다고 판단해서 struct로 구현했습니다!

2022-09-26 06:37 UTC, Groot-94 commented on ProjectManager/ProjectManager/Domain/UseCase/ProjectTranslater.swift
> +}
ViewModel에선 Model을 모르는 상태로 View에 보여질 데이터에 대해서만 알 수 있도록 하기 위해서 Entity타입을 ViewModel에서 사용 할 타입으로 변환해주기 위해서 사용했습니다.

extension은 나중에 기능에 대해 조금 더 확장하기 쉽도록 프로토콜 기본구현을 사용해 봤습니다..

2022-09-26 06:44 UTC, Groot-94 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/View/ProjectListViewController.swift
> +    private func configureObserverBind() {
함수명을 통일성 있게 작성 해봤는데 적절하지 않았나보네요 ,,ㅎㅎ

2022-09-26 07:20 UTC, Groot-94 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectManagement/View/ProjectManagementView.swift
> +final class ProjectManagementView: UIView {
scene의 용도가 생성 및 수정이라서 관리라는 의미로 지어봤는데 뷰 자체는 DetailView라고 해도 무방하겠네요... 이럴 경우는 ViewController과 이름을 다르게 지어주는게 좋은 방법일까요...?

2022-09-26 07:27 UTC, Groot-94 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/View/ProjectListViewController.swift
> +    }
UITableViewDataSource에 포함된 함수가 아니라는 생각에 UITableViewDataSource을 채택하기 위한 extension 안에 넣기보단 실제 클래스 가장 하단에 넣어줬습니다..

2022-09-26 07:34 UTC, Groot-94 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/ViewModel/ProjectListViewModel.swift
> +    func configureNumberOfRow(state: ProjectState) -> Int {
행의 수를 설정한다 라는 의미로 사용했는데, NumberOfRow 만으로도 그런 의미가 담긴 걸까요..??

2022-09-26 08:01 UTC, Groot-94 commented on ProjectManager/ProjectManager/Domain/UseCase/ProjectUseCase.swift
> +    var repository: ProjectRepositoryProtocol
프로토콜로 추상화 하면서 private를 사용하지 못 했었네요.. 하지만, 프로토콜에서 굳이 추상화 하지 않아도 괜찮겠다는 생각이 들어 프로토콜에서 제거하고 은닉화 했습니다.

2022-09-26 11:27 UTC, Groot-94 commented on ProjectManager/ProjectManager/Data/TemporaryRepository/TemporaryProjectRepository.swift
> +    private var temporaryStore: [ProjectModel]
수정했습니다.

2022-09-26 11:27 UTC, Groot-94 commented on ProjectManager/ProjectManager/Data/Protocol/ProjectRepositoryProtocol.swift
> +protocol ProjectRepositoryProtocol {
명사형 프로토콜은 잘 사용을 안해봤었네요.. 다시 네이밍 가이드를 읽어봐야 할 것 같습니다..

2022-09-26 11:31 UTC, Groot-94 commented on ProjectManager/ProjectManager/Data/TemporaryRepository/TemporaryProjectRepository.swift
> +    }
의존성 주입을 통해서 초기화를 해주면 테스터용 데이터와 실제 사용 데이터를 갈아끼우며 init을 해주는게 가능해서 테스트에 용이할 것 같습니다..!

2022-09-26 11:32 UTC, Groot-94 commented on ProjectManager/ProjectManager/Domain/UseCase/ProjectUseCase.swift
> +    }
수정했습니다!

2022-09-26 11:36 UTC, Groot-94 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/ViewModel/ProjectListViewModel.swift
> +    }
reloadList라는 네이밍으로 바꿔봤습니다...

2022-09-26 11:38 UTC, Groot-94 commented
안녕하세요 제이크! 제가 기본 컨벤션이 정말 많이 부족하다는걸 느꼈습니다... 신경을 쓴다고 했는데 쉽지가 않네요...

그리고 말씀해주신 내용은(편집 시 원래의 날짜로 피커를  설정하는 기능) 다음 스텝에서 적용해보도록 하겠습니다!

2022-09-26 13:08 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/ViewModel/ProjectListViewModel.swift
> +    func configureNumberOfRow(state: ProjectState) -> Int {
아래와 같이 실제 해당 함수를 사용하는 곳에서 봤을때에도 어색해보이지 않는것 같네요 🙂
```swift
return viewModel.numberOfRow(state: state) 
```
다만 argument label을 `viewModel.numberOfRow(with: state)` 라고 작성하는게 더 괜찮아보입니다.

2022-09-26 13:09 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectManagement/View/ProjectManagementView.swift
> +final class ProjectManagementView: UIView {
음 가능하다면 동일하게 가는게 좋을 것 같네요. 
이 부분은 기존 네이밍을 유지하고 추후에 좀 더 고민해보시죠 ㅎㅎ

2022-09-26 13:12 UTC, jryoun1 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/ViewModel/ProjectListViewModel.swift
> +    }
여기는 여전히 의존성 주입이 적용되지 않은 것 같네요 🤔
확인부탁드려요!

2022-09-26 13:13 UTC, jryoun1 approved these changes
@Groot-94 
고생하셨습니다.

잘 수정해주셨네요 👍🏻👏💯
코멘트 하나 달아두었는데 해당 코멘트는 추후 스텝에서 같이 적용해주세요~

2022-09-26 13:13 UTC, merged

2022-09-27 09:01 UTC, Groot-94 commented on ProjectManager/ProjectManager/Presentation/Scene/ProjectList/ViewModel/ProjectListViewModel.swift
> +    }
뷰컨에서 주입해주는 방법으로 수정했습니다!