프로젝트 매니저 [ STEP2 ] brad, bard
yagom-academy/ios-project-manager pull request #199
Opened 2022-09-16 15:58 UTC by bar-d

### STEP2 PR
안녕하세요 토니!  @Monsteel 
브래드@bradheo65  와 바드입니다 @bar-d
생각보다 PR이 많이 지연된 점 죄송합니다  
이번 PR도 잘 부탁드리겠습니다🙇‍♂️🙇‍♂️

## 프로젝트 진행하면서 경험한 점

## Experience 
### E1. UI 구성

<img src = "https://i.imgur.com/Qjrs4Lw.png" width="550" height="300">  
<img src = "https://i.imgur.com/4L7UelS.png" width="550" height="300">  

#### UI 초기 설계

처음 UI를 구현하는데, 브래드와 바드의 의견이 갈렸고 각자 서로에 대한 UI에 대한 설명을 하고,  
브래드의 의견으로 초기 UI를 구현을 완료해보았습니다.

#### 문제점

하지만, UI를 구현을 완료하고나서 현재 구성이 각각의 `UIViewController`를 유지 보수하는데에는 용이하겠지만, 
현재 프로젝트로써는 중복되는 뷰였기에, 굳이 각각의 `UIViewController`로 구현해줄 필요가 없다고 판단하게 되었습니다.

#### 결과

하나의 `UIViewController` 내부에 (스택 뷰 내부에)`UITableView` 3개를 넣어주어 리팩토링을 해주었습니다.
  
<img src = "https://i.imgur.com/JPG8bRI.png" width="550" height="300">  
<img src = "https://i.imgur.com/jgY3q8Y.png" width="550" height="300">  

### E2. ViewModel
![](https://i.imgur.com/yjmhIg7.png)
- 현재 ViewModel 하나로 위의 그림과 같이 전체 데이터를 관리할 수 있다고 생각하여 하나의 ViewModel로 구현

### E3. Data Binding
- `Swift`로 Data Binding을 이스케이핑 클로저를 통해 구현해보았습니다.   
 각 프로퍼티마다 모델의 객체마다 이스케이핑 클로저를 통해 `Data Binding`을 해줌

### E4. 화면 전환
- `UITableView` 내부에서 셀을 선택하거나, 길게 누르면 각각 `ProjectDetailViewController`, `UIAlertController`를 보여줌
- `UITableView` 내부에는 뷰 컨트롤러를 보여 줄 수 있는 `present(:animtated:)` 메서드가 없기에 `Presentable`이라는 Protocol을 만들어 주어서 `Delegate Pattern`으로 화면을 이동하는 역할을 위임시켜줌

### E5. UITableViewDelegate, UITableViewDataSource
- 처음 `UITableViewDelegate`, `UITableViewDataSource`를 `MainViewController`에 채택을 해주었는데, `MainViewController`가 들고 있으면,   
각 테이블 뷰의 타입 별로 `switch case` 구문을 적용시켜 줘야하기에, `ProjectTableView`에 `UITableViewDelegate`, `UITableViewDataSource`를 채택  
또한 `UITableViewDelegate`, `UITableViewDataSource`는 `TableView`와 관련된 프로토콜인데, `ViewController`가 들고 있는 모양이 어색하다 판단

### E6. UILongPressGestureRecognizer
- `ProjectTableView`에 `UILongPressGestureRecognizer`관련 메서드를 작성해 주었고,  
 이로 인해서 `UILongPressGestureRecognizer`를 통해 `CGPoint`를 받아와 `UITableViewCell`에 대한 `indexPath` 값을 알아와서,   
 각 인덱스에서 UIAlertController를 popOver해 줄 수 있도록 구현
 
 - `didCellTappedLong` @objc 함수가 아름답지 못하다고 판단  
 추후 코드 개선 필요

## 궁금한 점

### Q1. IndexPath

- 기존의 데이터를 수정해주기 위해 해당 `index`를 알아야 하기때문에 TableView의 cell indexPath값이 필요했습니다.  
현재 전역변수로 `indexPath`를 선언해주었고 이 값을 통해 Cell Click 이벤트가 발생되었을 때 저장해주고 delegate 패턴을 통해 `Edit` 버튼 클릭 시 기존 데이터 수정이 되는 로직으로 구현해보았는데,  
전역변수를 통해 해당 값을 가져오는 방법이 알맞는 방법인지,   
아니면 TableView의 Cell에서 몇 번째 cell인지 전달해주는 방법이 좋은 건지 궁금합니다!

### Q2. ViewModel
- 구현해 보니 각 프로퍼티마다 모델의 객체마다 이스케이핑 클로저를 통해 Data Binding을 해주어야 했었습니다.   
 한 개의 `ViewModel`에서 가지고 있는게 맞는지, 아니면 각 프로퍼티마다 `ViewModel`을 만들어주는게 맞는지 현 프로젝트에서 적절한 접근인지 궁금합니다.

### Q3. ViewModel의 역할 범위
- 아무래도 처음 `MVVM` 과 `ViewModel`을 적용하다 보니 `ViewModel`의 크기가 점점 커지고 로직이 많아져 `ViewModel`로써 책임 커진다고 생각되었습니다.  
 `ViewModel`은 데이터의 상태를 받아와 `View`에 뿌려주는 것인데, ViewModel`의 책임을 잘 위임한 것인지 궁금합니다.

### Q4. 명세서

|TODO Item 추가 UI|TODO Item 수정 UI|
|:---:|:---:|
|<image src = "https://i.imgur.com/uaiqLMC.png" >|<image src = "https://i.imgur.com/4NzIc0j.png">|
    
- 위의 그림을 보았을떄 추가 UI의 `Cancel` 버튼 위치와 수정 UI의 `Edit` 의 위치가 동일하게 왼쪽으로 되어있는데 의미상 `Edit`가 저장기능을 가지고 있고 `Done`이 취소 의미로 생각이 되는데 수정 UI의 `Edit` 위치와 `Done`위치가 서로 바뀌어야 한다고 생각 됩니다.
이 부분에 대해서 토니의 의견이 궁금합니다!!

### Q5. 모델의 구조

|JSON Data 구조 비교|
|:---:|
|<img src = "https://i.imgur.com/RZ1nHuT.png" >|

- 처음 뷰에 모델 값을 잘 보여주고 있는지 확인하기 위해 JsonData를 이용하였습니다.  
초기 JSONData의 구조는 `title`, `description`, `timeLimit`, `type` 이라는 프로퍼티를 들고 있는 구조였습니다.
하지만, 해당 형식 보다는 각 타입별로 나누어준 `[ToDoItem]`　프로퍼티를 들고 있다는 것이 맞다고 생각하여,   
JSONData의 구조를 `ItemListCategory`라는 모델을 들고 있고, 해당 모델은 `todo`, `doing`, `done` 이라는 `[ToDoItem]` 타입의 프로퍼티를 들고 있도록 구현을 해주었습니다.
물론 정답은 없겠지만, 토니가 생각했을 때, 위의 사진에서 어떤 구조가 실제 데이터베이스에 저장 시  더 좋은 방법이라고 생각하시는지 의견이 궁금합니다!!

2022-09-17 09:20 UTC, bar-d commented
처음 PR E6.에서 설명드린 `@objc didCellTappedLong` 함수를   
 `UIAletController`를 생성해주는 함수와 @objc 함수로 따로 기능을 분리해 주었고 [f904848](https://github.com/yagom-academy/ios-project-manager/pull/199/commits/f904848614c7b53346eeab13189530b7a6e69a20)  
최종적으로는 `UIAletController` 타입을 만들어주어서 `AletController`를 생성해주었습니다. [aa6681a](https://github.com/yagom-academy/ios-project-manager/pull/199/commits/aa6681a94c04225db093befa9f4dd6fabee11c36)

2022-09-19 15:51 UTC, Monsteel commented on ProjectManager/ProjectManager/Scene/Main/Model/MockToDoItemManager 2.swift
> +//
`ProjectManager/ProjectManager/Scene/Main/Model/MockToDoItemManager.swift` 파일과 동일한 의미를 가지는 파일인것 같아요. 의도하신 파일인가요?

2022-09-19 15:57 UTC, Monsteel commented on ProjectManager/ProjectManager/Scene/Main/View/MainView/ProjectTableView/AlertController.swift
> +        // super.init(title: nil, message: nil, preferredStyle: .alert)
`deadcode` 제거가 필요해보입니다 👀

2022-09-19 17:11 UTC, Monsteel requested changes
안녕하세요 브레드 바드 :)
step2 수고 많으셨습니다.

코드는 깔끔하게 읽기좋게 잘 정리해 주셔서, 코드에 대해서는 크게 리뷰남길 사항들이 없었네요 💯

남겨주신 질문에 대한 답변을 중심으로 이번 리뷰 진행할게요 👍 

>### Q1. IndexPath
> 기존의 데이터를 수정해주기 위해 해당 index를 알아야 하기때문에 TableView의 cell indexPath값이 필요했습니다.
현재 전역변수로 indexPath를 선언해주었고 이 값을 통해 Cell Click 이벤트가 발생되었을 때 저장해주고 delegate 패턴을 통해 Edit 버튼 클릭 시 기존 데이터 수정이 되는 로직으로 구현해보았는데,
전역변수를 통해 해당 값을 가져오는 방법이 알맞는 방법인지,
아니면 TableView의 Cell에서 몇 번째 cell인지 전달해주는 방법이 좋은 건지 궁금합니다!

우선 지금 적용해주신 방법을 저는 개인적으로 지양하는 방식중 하나입니다.
많은 이유가 있겠지만, 전역변수 하나를 두고 값을 바꿔가며 사용하게 되면, 정확한 시점을 확인하기 어려워, 값을 추적하기 어려워지고, 코드의 흐름을 파악하기 어려워 지기 때문인데요,

지금 당장은 코드의 수도 작고, 범위가 그렇게 넓지 않으니 한눈에 잘 들어오는듯 보이겠지만,
이러한 상황들이 여럿 생기고, 다른 코드들과 섞이기 시작하면 단점이 더 커지지는 않을까 걱정됩니다.

대체할 수 있는 다른 방법을 찾아보는게 좋을것 같아요 👍

> ### Q3. ViewModel의 역할 범위
> 아무래도 처음 MVVM 과 ViewModel을 적용하다 보니 ViewModel의 크기가 점점 커지고 로직이 많아져 ViewModel로써 책임 커진다고 생각되었습니다.
ViewModel은 데이터의 상태를 받아와 View에 뿌려주는 것인데, ViewModel`의 책임을 잘 위임한 것인지 궁금합니다.

적용해주신 viewModel의 경우 viewModel보다는 domainModel이라는 이름이 더 어울릴 정도로 domain에 종속되어 있는 형태로 보여집니다.

[viewModel이라는 개념을 처음으로 소개한 글](https://learn.microsoft.com/ko-kr/archive/blogs/johngossman/introduction-to-modelviewviewmodel-pattern-for-building-wpf-apps) 을 한번 보시면 좋을 것 같아요.
viewModel을 근본적으로 이해하는데 도움이 될거라 생각합니다.

해당 글에서는

> The term means "Model of a View"

viewModel을 view의 Model 이라고 소개하고 있습니다.

> ### Q4. 명세서
> 위의 그림을 보았을떄 추가 UI의 Cancel 버튼 위치와 수정 UI의 Edit 의 위치가 동일하게 왼쪽으로 되어있는데 의미상 Edit가 저장기능을 가지고 있고 Done이 취소 의미로 생각이 되는데 수정 UI의 Edit 위치와 Done위치가 서로 바뀌어야 한다고 생각 됩니다.
아니면 등록해주는 UI 처럼 Cancel버튼이 왼쪽, Done버튼이 오른쪽에 위치할 수도 있고요.
이 부분에 대해서 토니의 의견이 궁금합니다!!

명세서에 따르면, `TODO Item 수정 UI`라고 말씀주신 화면은, `TODO 상세` 화면이라고 판단되는데요,
저는 상세 화면에서 Edit 버튼을 눌렀을 때, 수정이 가능해지는 시나리오로 이해하고 있습니다.

명세서에 따르면 TODO 추가/수정 화면은 상단 navigationBar의 구성이 같아 보입니다.

[프로젝트 관리 앱 명세서](https://camp.yagom-academy.kr/camp/61d414e5e4081120ba7884d2/projects/63116bb72b3d440eb03cfc1f)

우선 저는 이렇게 이해했는데, 다시한번 확인을 부탁드려도 될까요?

> ### Q5. 모델의 구조
> 처음 뷰에 모델 값을 잘 보여주고 있는지 확인하기 위해 JSONData를 이용하였습니다.
초기 JSONData의 구조는 title, description, timeLimit, type 이라는 프로퍼티를 들고 있는 구조였습니다.
하지만, 해당 형식 보다는 각 타입별로 나누어준 [ToDoItem]　프로퍼티를 들고 있다는 것이 맞다고 생각하여,
JSONData의 구조를 ItemListCategory라는 모델을 들고 있고, 해당 모델은 todo, doing, done 이라는 [ToDoItem] 타입의 프로퍼티를 들고 있도록 구현을 해주었습니다.
물론 정답은 없겠지만, 토니가 생각했을 때, 위의 사진에서 어떤 구조가 실제 데이터베이스에 저장 시 더 좋은 방법이라고 생각하시는지 의견이 궁금합니다!!

가공된 데이터의 형태와, raw하게 저장되는 데이터의 형태는 추구해야 하는 방향이 다르다고 생각합니다.

저장되는 데이터의 경우, 무결성을 보호할 수 있고, 조건 처리 및, 편리한 가공이 가능한 등의 형태가 이점이 있을 수 있을것 같고,

가공된 데이터의 경우, 보다 사용에 용이하고, 필요한 데이터만 존재하는 등의 형태가 이점이 있을것 같아요.

고민하면 좋은 포인트들에 대해 간단히 제 생각을 적어봤는데요, 데이터베이스에 저장 시 어떤 방법이 조금 더 유리한 방향일까요? 한번 고민해보시면 좋을 것 같아요.


사실 [프로젝트 매니저] 프로젝트의 경우 코드에 대한 리뷰 보다는, 코드리뷰에 담지 못하는 전체적인 구조, 설계에 대한 리뷰가 주를 이루게 되는것 같아요.

남겨주신 질문들을 통해서 구조/설계에 대한 부분에 대한 피드백들 드렸는데, 한번 확인해보시고 고민해주시면 감사하겠습니다 :)

수고하셨어요 !

2022-09-29 13:39 UTC, bar-d commented
안녕하세요 토니 @Monsteel 
생각보다 많은 시간이 걸렸네요
토니의 말을 따라서 메인 뷰 모델이 뷰모델들의 계층을 관리하도록 다시 리팩토링 해보았습니다
![스크린샷 2022-09-29 오후 10 36 44](https://user-images.githubusercontent.com/92622931/193046456-f3994f88-ddae-4ee3-a938-24daf828f2a8.png)

2022-10-03 14:05 UTC, Monsteel approved these changes
PR 확인이  늦었습니다! 🙏
주말은 다들 잘 보내셨나요 ?

반영된 사항 잘 확인했습니다! ✨ 원초적인 ViewModel 개념을 코드에 잘 녹여내 주신것 같아요 👍

이번 프로젝트를 진행하시면서, ViewModel에 대한 이해도와, Reactive programming의 필요성에 대해 조금 더 이해하는 프로젝트가 되셨길 바래봅니다! ✨

프로젝트기간동안 정말 수고 많으셨습니다! 🙇🏻‍♂️👍

2022-10-03 14:05 UTC, merged