[Step 1] JM, Fezz
yagom-academy/ios-project-manager pull request #20
Opened 2021-07-22 11:37 UTC by Fezravien

# [Step 1] Project Manager Client

@AppleCEO 

안녕하세요 `도미닉` step 1 PR 보냅니다 👋👋

---

### 📌 구현사항 📌

#### Task 추가 버튼 동작

<img src="https://raw.githubusercontent.com/Fezravien/UploadForMarkdown/forUpload/img/126629327-b6ceabc7-ba38-4dcc-8f4d-bfb53e9a8f45.gif" alt="PM01" width="60%" /> 

<br>

#### Task 추가하기 (Done Button)

- Title
- date
- description
- 모두가 값을 가지고 있어야 한다 !

<img src="https://raw.githubusercontent.com/Fezravien/UploadForMarkdown/forUpload/img/126629344-8b0c6505-1037-4a8c-86c1-673f891845d6.gif" alt="PM02" width="50%" /><img src="https://raw.githubusercontent.com/Fezravien/UploadForMarkdown/forUpload/img/126629347-ca8aa76b-1223-45c9-939c-32ee237c964e.gif" alt="PM03" width="50%" />  

<br>

#### Drag and Drop

<img src="https://raw.githubusercontent.com/Fezravien/UploadForMarkdown/forUpload/img/126629352-cda644fc-4c93-427c-afb6-c8d4abcd869a.gif" alt="PM04" width="60%" /> 

- Collection View 간의 (+ 자기 뷰) 드레그 앤 드랍 

<br>

#### Cell Delete

<img src="https://raw.githubusercontent.com/Fezravien/UploadForMarkdown/forUpload/img/126629364-a23581e9-47dc-451e-a0eb-e4308e157669.gif" alt="PM05" width="60%" /> 

- Custom swipe 구현 

<br>

#### Edit

<img src="https://user-images.githubusercontent.com/75533266/126631393-234965a7-fa92-4813-81bf-c74f3e5c7473.gif" alt="PM06" width="60%" /> 

- Edit 버튼 누르기 전에는 모든 데이터 수정 불가 
- Edit 버튼 누를시 (버튼 색상 `blue` -> `gray`) Edit 모드로 진입
- Done 버튼을 통해 업데이트 

<br>

---

### 고민사항 🤔

- 셀 간의 레이아웃 문제에 대해서 고민했습니다.
- MVVM 설계에 대해서 고민했습니다.
- Custom swipe에 대해서 고민했습니다.

<br>

---

### 조언을 얻고 싶은 부분 🗣

- MVVM 아키텍처 설계에 대해 조언을 얻고 싶습니다.

  컨트롤러, Cell마다 `ViewModel`을 가지고 있어야 하는지 그리고 컨트롤러는 어떤 기능을 가지고 있어야하는지 궁금합니다.

  MVVM에서 바인딩이라하면 Model의 변화가 있을시 View에 반영한다라고 생각했는데 저희 프로젝트에서 어떻게 바인딩 작업을 해줘야할지 조언을 얻고 싶습니다.

- Custom swipe에 대해서 조언을 얻고 싶습니다.

  셀 간의 레이아웃을 구현하기 위해서 `HIG`를 참조했는데, TableView로는 해당 레이아웃을 구현할 수 없다고 판단하여 CollectionView를 사용했는데 

  ```swift
  let config = UICollectionLayoutListConfiguration(appearance: .insetGrouped)
  ```

  이런 레이아웃을 통해서만 swipe기능을 사용할 수 있었습니다. 그래서 Custom swipe를 구현하였는데 이 부분에 대해서 조언을 얻고 싶습니다.

<br>

2021-07-23 06:49 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
Jm & Fezz 고생하셨습니다.
리뷰 남겨드렸습니다. 

MVVM 아키텍처 설계에 대해 조언을 얻고 싶습니다.

컨트롤러, Cell마다 ViewModel을 가지고 있어야 하는지 그리고 컨트롤러는 어떤 기능을 가지고 있어야하는지 궁금합니다.

- ViewModel은 뷰컨트롤러마다 매칭되지는 않습니다. 하나의 뷰모델을 만들어서 여러 뷰컨트롤러와 셀에서 공유하는 형태가 좋을 것 같습니다. 컨트롤러에서는 뷰모델과 뷰를 생성하고 뷰모델과 뷰를 바인딩해주는 역할 정도만 있으면 될 것 같습니다. 

MVVM에서 바인딩이라하면 Model의 변화가 있을시 View에 반영한다라고 생각했는데 저희 프로젝트에서 어떻게 바인딩 작업을 해줘야할지 조언을 얻고 싶습니다.

- [발표자료](https://www.slideshare.net/joonjhokil/rx-mvvm) 참고해주세요. 발표자료 보시면 바인딩을 하는 방법이 4가지 있는데 어떤 것이 가능할지 고민해보시고 질문 주시면 같이 도울게요! 

Custom swipe에 대해서 조언을 얻고 싶습니다.

셀 간의 레이아웃을 구현하기 위해서 HIG를 참조했는데, TableView로는 해당 레이아웃을 구현할 수 없다고 판단하여 CollectionView를 사용했는데

let config = UICollectionLayoutListConfiguration(appearance: .insetGrouped)
이런 레이아웃을 통해서만 swipe기능을 사용할 수 있었습니다. 그래서 Custom swipe를 구현하였는데 이 부분에 대해서 조언을 얻고 싶습니다.

- 원하는 대로 안정적으로 동작한다면 어떤 방식을 사용하든 괜찮다고 생각합니다. https://stackoverflow.com/questions/14270023/how-to-implement-uitableviews-swipe-to-delete-for-uicollectionview 문서를 참고하면 다른 방식들도 있는 것 같네요!

2021-07-23 06:49 UTC, AppleCEO commented on ProjectManager/ProjectManager/Controllers/AddTaskViewController.swift
> +}
열거형으로 상태의값을 저장한 것 아주 좋습니다! 👍

2021-07-23 06:49 UTC, AppleCEO commented on ProjectManager/ProjectManager/Controllers/AddTaskViewController.swift
> +    }()
코드로 UI를 작성해보셨군요~ 💯 
어떤 부분이 좋고 스토리보드 불편한 점은 어떤 점이 있던가요?

2021-07-23 06:49 UTC, AppleCEO commented on ProjectManager/ProjectManager/Controllers/AddTaskViewController.swift
> +    }()
어떤 날짜가 저장되는지 이름에 드러나도 좋을 것 같네요 🔢

2021-07-23 06:49 UTC, AppleCEO commented on ProjectManager/ProjectManager/Controllers/AddTaskViewController.swift
> +        if mode == .edit {
이 mode 변수는 이 뷰컨트롤러의 프로퍼티 같은데요.
그렇게 뷰컨트롤러의 프로퍼티에 접근할 때는 self를 붙여주는 것이 혼돈이 적습니다.
아래 setState에서처럼요.
https://github.com/StyleShare/swift-style-guide
참고해주세요~

2021-07-23 06:49 UTC, AppleCEO commented on ProjectManager/ProjectManager/Controllers/AddTaskViewController.swift
> +    }
닫기 버큰을 눌렀다는 메소드명으로 보이는데요.
push 대신에 iOS 용어인 tap 을 사용하는 것은 어떨까요? 
https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/gestures/
제스처 용어들 참고해주세요!

2021-07-23 06:49 UTC, AppleCEO commented on ProjectManager/ProjectManager/Resources/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
이 부분도 조금 어색하네요.
self.window와 window 가 혼용되고 있는 것 같아서요.
어떻게 개선해 볼 수 있을까요?

2021-07-23 06:49 UTC, AppleCEO commented on ProjectManager/ProjectManager/Views/Cells/TaskCollectionViewCell.swift
> +            changedX = self.frame.width/2 - 150
하드코딩 되어있는 숫자들을 혹시 하드코딩 되지 않도록 개선해 볼 수 있을까요?

2021-07-23 06:51 UTC, AppleCEO commented
확인 부탁드립니다. @alwaysblu,  @Fezravien

2021-07-26 07:40 UTC, Fezravien commented on ProjectManager/ProjectManager/Controllers/AddTaskViewController.swift
> +}
🙆‍♂️

이 부분을 리팩토링하며 새로운 파일로 만들어서 뺐습니다 
`TaskState.swift`

2021-07-26 07:47 UTC, Fezravien commented on ProjectManager/ProjectManager/Controllers/AddTaskViewController.swift
> +    }()
대부분 이전 프로젝트에서 스토리보드를 사용했고, 팀원간 페어 프로그래밍을 통해서 진행했기 때문에 별 문제가 발생하지 않았습니다. 하지만이번에는 팀원과 기능에 따른 역할분담을 했고, 각각의 브랜치에서 기능을 만든후 merge 하는 방식으로 진행했습니다. 이렇게 진행하게 되면서 생각한 스토리보드의 단점은

- 단일 스토리보드로 했을때 서로 기능이 분배되었다고 해도 git 충돌의 위험성이 존재했고, 충돌에 따른 수정 또한 힘든 부분이 있다고 판단했습니다. 
- 스토리보드로 UI를 작성하고 추후 리펙토링을 할 때, 레이아웃과 같은 부분이 하나하나 찾기가 힘들다고 생각했습니다. 이 부분을 코드로 작성하므로써 명확하게 판단할 수 있다고 생각했습니다.
- 마지막으로 저희가 의도했던 모양을 구성하는데 자율성이 높습니다.

2021-07-26 07:48 UTC, Fezravien commented on ProjectManager/ProjectManager/Controllers/AddTaskViewController.swift
> +    }()
`Model` 에서 사용한 DeadLine과 일관성있게
```swift
private let deadLineDatePickerView ... 
```
으로 수정했습니다.

2021-07-26 07:48 UTC, Fezravien commented on ProjectManager/ProjectManager/Controllers/AddTaskViewController.swift
> +        if mode == .edit {
🙆‍♂️

2021-07-26 07:50 UTC, Fezravien commented on ProjectManager/ProjectManager/Controllers/AddTaskViewController.swift
> +    }
🙆‍♂️ `tap` 으로 수정했습니다.
주신 자료를 읽어보고 앞으로 네이밍을 잘 생각해볼게요 😃

2021-07-26 07:51 UTC, Fezravien commented on ProjectManager/ProjectManager/Resources/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
```swift
self.window = UIWindow(windowScene: scene)
self.window?.rootViewController = UINavigationController(rootViewController: ProjectManagerViewController())
self.window?.makeKeyAndVisible()
```
self를 일관성 있게 수정했습니다.

2021-07-26 08:35 UTC, Fezravien commented
# [Step 1] Project Manager Client 📑 - 2

@AppleCEO 

안녕하세요 `도미닉` 👋 피드백 감사합니다 😀

피드백 주신 부분과 전체적인 코드를 리펙토링을 해봤습니다.


---

### 추가 및 수정 사항 

#### MVVM

View와 ViewModel간 `DataBinding` 구현

<br>

#### 새로운 Task 추가 제약사항

- `Title`

  100자 미만

- `Description`

  1000자 미만

<img src="https://raw.githubusercontent.com/Fezravien/UploadForMarkdown/forUpload/img/Simulator%20Screen%20Shot%20-%20iPad%20Pro%20(12.9-inch)%20(5th%20generation)%20-%202021-07-26%20at%2017.06.52.png" alt="Simulator Screen Shot - iPad Pro (12.9-inch) (5th generation) - 2021-07-26 at 17.06.52" width="50%" /><img src="https://raw.githubusercontent.com/Fezravien/UploadForMarkdown/forUpload/img/Simulator%20Screen%20Shot%20-%20iPad%20Pro%20(12.9-inch)%20(5th%20generation)%20-%202021-07-26%20at%2017.07.56.png" alt="Simulator Screen Shot - iPad Pro (12.9-inch) (5th generation) - 2021-07-26 at 17.07.56" width="50%" />

<br>

### CollecionView Swipe Action Custom

#### 스와이프 애니메이션 수정

<img src="https://raw.githubusercontent.com/Fezravien/UploadForMarkdown/forUpload/img/Simulator%20Screen%20Recording%20-%20iPad%20Pro%20(12.9-inch)%20(5th%20generation)%20-%202021-07-26%20at%2017.04.36.gif" alt="Simulator Screen Recording - iPad Pro (12.9-inch) (5th generation) - 2021-07-26 at 17.04.36" width="80%" />

<br>

---

### 고민사항 

#### Task 추가 후 추가된 cell 삭제시 이상현상

추가된 Cell을 삭제하게 되면 그것을 트리거로 다른 cell들이 Delete가 보이면서 레이아웃이 깨지는 문제 ... 🤔

<img src="https://raw.githubusercontent.com/Fezravien/UploadForMarkdown/forUpload/img/Simulator%20Screen%20Recording%20-%20iPad%20Pro%20(12.9-inch)%20(5th%20generation)%20-%202021-07-26%20at%2017.09.53.gif" alt="Simulator Screen Recording - iPad Pro (12.9-inch) (5th generation) - 2021-07-26 at 17.09.53" width="80%" />

<br>

#### MVVM Data Binding 

```swift
// ProjectManagerViewController
private func setDataBindingWithViewModel() {
        toDoViewModel.updateTaskCollectionView = { [weak self] in
            self?.updateCount(self!.toDoCollectionView)
            self?.toDoCollectionView.reloadData()
        }
        doingViewModel.updateTaskCollectionView = { [weak self] in
            self?.updateCount(self!.doingCollectionView)
            self?.doingCollectionView.reloadData()
        }
        doneViewModel.updateTaskCollectionView = { [weak self] in
            self?.updateCount(self!.doneCollectionView)
            self?.doneCollectionView.reloadData()
      }
}
    
func updateData(state: State, indexPath: IndexPath, _ data: Task) {
        switch state {
        case .todo:
            toDoViewModel.updateTaskIntoTaskList(indexPath: indexPath, task: data)
        case .doing:
            doingViewModel.updateTaskIntoTaskList(indexPath: indexPath, task: data)
        case .done:
            doneViewModel.updateTaskIntoTaskList(indexPath: indexPath, task: data)
      }
}

```

기능적인 부분에서는 모두 동작했지만 `reloadData`를 해줌으로써 Cell 삭제시 애니메이션 효과 없이 사라지는 어색함이 존재했습니다.

이 부분에서 좀더 개선할 수 있는 방법이 있을지 궁금합니다 🤔

<br>

---

커스텀 스와이프 부분은 스탭을 진행해가면서 `하드코딩`, `애니메이션` 부분을 개선해 나가도록 하겠습니다 😁

2021-07-26 12:19 UTC, AppleCEO commented
Fezz, JM 고생하셨습니다~
머지를 원하시나요?
reloadData 대신에 reloadSections 을 사용해보는 것은 어떨까요?

2021-07-26 12:31 UTC, AppleCEO reviewed
Fezz, JM 고생하셨습니다~
코드가 전체적으로 간결하고 의미가 명확해졌네요.
머지 해드리면 될까요?

기능적인 부분에서는 모두 동작했지만 reloadData를 해줌으로써 Cell 삭제시 애니메이션 효과 없이 사라지는 어색함이 존재했습니다.

이 부분에서 좀더 개선할 수 있는 방법이 있을지 궁금합니다 🤔

- reloadData 대신에 reloadSections 을 사용해보는 것은 어떨까요?

2021-07-26 12:31 UTC, AppleCEO commented on ProjectManager/ProjectManager.xcodeproj/project.pbxproj
> +		C7431F0A25F51E1D0094C4CF /* ProjectManagerViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = C7431F0925F51E1D0094C4CF /* ProjectManagerViewController.swift */; };
뷰컨트롤러의 이름을 명확하게 한점 좋습니다!

2021-07-26 12:31 UTC, AppleCEO commented on ProjectManager/ProjectManager/Controllers/ProjectManagerViewController.swift
> +    private let doneHeader: TaskHeader = {
private 접근제어자를 적극적으로 활용한 부분 좋습니다!

2021-07-26 12:31 UTC, AppleCEO commented on ProjectManager/ProjectManager/Views/Cells/TaskCollectionViewCell.swift
> +    private func setTaskDeadlineLabel() {
간결해졌네요!

2021-07-26 12:31 UTC, AppleCEO commented on ProjectManager/ProjectManager/Controllers/ProjectManagerViewController.swift
> +            self.doneCollectionView.widthAnchor.constraint(equalTo: doneHeader.widthAnchor),
하드코딩되지 않아 숫자를 바꿀 일이 있으면 모아놓은 숫자 하나를 바꾸면 될 것 같아서 보기에도 좋고 의미가 명확해졌네요 💯

2021-07-26 12:31 UTC, AppleCEO commented on ProjectManager/ProjectManager/Models/TaskStatus.swift
> +}
열거형을 따로 새로운 파일에 빼낸 부분 좋습니다~ 🥇

2021-07-26 12:32 UTC, AppleCEO commented
확인 부탁드립니다. @alwaysblu, @Fezravien

2021-07-26 13:07 UTC, merged

2021-07-29 03:38 UTC, AppleCEO commented
https://jcsoohwancho.github.io/2019-10-12-TableView의-변화를-처리하는-방법(1)-Batch-Update/ 이 글 참고해보세용~