프로젝트 관리 앱 [STEP 2-3, 2-4] 수꿍, 휴
yagom-academy/ios-project-manager pull request #200
Opened 2022-09-18 10:48 UTC by Hugh-github

@ryan-son 
안녕하세요 라이언 PR이 늦어져서 정말 죄송합니다 🙇🏻
처음 MVVM을 적용하고 Test Code를 작성했으나 미흡한 점이 많은 것 같습니다.
PR 잘 부탁드립니다!

## 📱 화면 구현

- TODO, DOING, DONE 화면을 각각 TableView를 이용해 구현
![](https://i.imgur.com/aw3o1ry.png)

- Modal의 formSheet 스타일로 AddView 구현
![](https://i.imgur.com/inAFoRU.png)

- Add 버튼을 통한 프로젝트 추가 구현
![](https://i.imgur.com/Hbqt1ro.gif)

- Popover 표시 및 버튼 클릭으로 인한 프로젝트 이동 구현
![](https://i.imgur.com/yZSXUN4.gif)

- 기존 프로젝트 수정 구현
![](https://i.imgur.com/DQrGl7c.gif)

## 📃 기능 설명
    
- MainView
    - ~~3개의 Table View를 하나의 Custom StackView에 저장해 관리~~ (2022.09.17)
    - 3개의 Table View를 각각의 View Controller로 구현
        - 각각의 Table View에서 사용하는 ViewModel이 다르다고 판단(TODO, DOING, DONE에서 사용하는 데이터 및 기능이 다르다.)
    - Table View의 header로 사용할 Custom View 구현
    
- AddView
    - Modal Style 중 form sheet 사용
    - Date Picker를 사용해 날짜를 선택하는 View 구현
    - Text Field와 Text View에 shadow 효과 추가
    
- EditView
    - EditView에서 사용하는 기능을 추상화(Editable)
    - TapGesture가 인식되면 EditView로 이동

- PopoverController
    - PopoverController에서 사용하는 기능 추상화(Readjustable)
    - LongPressGesture가 인식되면 popover View로 이동
    
- ViewModel
    - ToDoViewModel, DoingViewModel, DoneViewModel 구현
    - **공통기능**
        1. swipe delete 이벤트를 처리하는 로직
        2. Table View에서 보내주는 indexPath로 데이터를 가져오는 로직
        3. 데이터의 Section을 이동시키는 로직(Readjustable 채택)
        4. 데이터의 content를 수정하는 로직(Editable 채택)
    -  **차이점**
        1. 각각의 Section(Table View)에서 사용할 데이터
        2. 데이터를 추가하는 로직(ToDoViewModel)

## 🚀 TroubleShooting
### STEP 2-4
#### T1. InMemory 방식의 Core Data의 invalid fetch request 문제
- OnDisk 방식에서의 Core Data Manager에 대하여 Popover내 버튼 클릭으로 인한 프로젝트 이동 구현 시, Core Data를 업데이트 하는 과정에서는 아무런 문제가 발견되지 않았습니다. 그러나, InMemory 방식의 Core Data Manager에서는 각각의 섹션으로부터 프로젝트를 이동시킬 때마다, invalid fetch request 에러가 발견되었습니다. 디스크 저장 방식에서는 정상적으로 작동되나, 메모리 저장 방식에서 비정상적으로 작동되는 원인을 살펴본 결과, 아래와 같이 각각의 Core Data Manager 인스턴스를 만들었기 때문에, 각 섹션에 고유한 저장소를 사용한 것이었습니다. 이에, 싱글턴 인스턴스를 생성하여, 공통된 Core Data Manager를 사용함으로써, 오류를 해결할 수 있었습니다.
- 수정 전 코드
```swift
final class ToDoViewController {
    private let viewModel = ToDoViewModel(databaseManager: MockLocalDatabaseManager())
    ...
}

final class DoingViewController {
    private let viewModel = DoingViewModel(databaseManager: MockLocalDatabaseManager())
    ...
}

final class DoneViewController {
    private let viewModel = DoneViewModel(databaseManager: MockLocalDatabaseManager())
    ...
}
```

- 수정 후 코드
```swift
final class ToDoViewController {
    private let viewModel = ToDoViewModel(databaseManager: MockLocalDatabaseManager.shared)
    ...
}

final class DoingViewController {
    private let viewModel = DoingViewModel(databaseManager: MockLocalDatabaseManager.shared)
    ...
}

final class DoneViewController {
    private let viewModel = DoneViewModel(databaseManager: MockLocalDatabaseManager.shared)
    ...
}
```

## 2️⃣ STEP 2-3, 2-4
### STEP 2-3 Questions
#### Q1. ViewModel과 ViewController 분리
- 하나의 ViewModel과 ViewController에서 각각 분리한 이유: 
    1. 분기 처리가 많아 코드가 복잡해짐
    2. 하나의 ViewModel이 3개의 data를 가지고 있는 게 어색함
    3. ViewController(View)의 코드가 너무 길어짐
- 각각 하나의 ViewModel과 ViewController를 사용했으나, 분기 처리가 많아 TableView 하나를 하나의 ViewController로 사용하고 해당 View(ViewController)에서 사용할 ViewModel을 따로 구현했습니다. 분기 처리는 하지 않지만 똑같은 코드가 여러 곳에서 사용되다 보니 이상하다는 느낌이 들었습니다. 또한 ViewController를 여러개 생성해서 구현하는게 어색하다고 생각했습니다. 이에 대하여 라이언의 의견을 여쭈어보고 싶습니다!
    
#### Q2. ViewModel Test Code
- ViewModel에 대한 Test Code를 구현했지만 Observable의 클로저가 잘 호출되는지 확인하기 위해 관찰하고 있는 data가 변할 때마다 전역변수로 선언해 준 count를 1씩 증가시켰습니다. ViewModel에서 구현한 클로저를 test 하는 방법이 궁금합니다. 또한 ViewModel 어떤 방식으로 Test 하는지 감이 오질 않습니다.
    
### STEP 2-4 Questions
#### Q1. InMemory 방식의 Core Data에 관한 Singleton 생성 고민
- STEP 2-4 TroubleShooting에 언급한 바와 같이, InMemory 방식의 Core Data의 경우, 각각의 섹션 뷰 컨트롤러에 대하여 싱글턴 객체를 사용하여 공통된 Core Data Manager를 설정해보았습니다. 이에 대하여 해당 해결방법이 적절한 방식이었는지, 그리고 이보다 더 좋은 방법은 무엇이 있을지 질문드리고 싶습니다!
#### Q2. InMemory 방식의 Core Data 유닛 테스트 방법 고민
- InMemory 방식의 Core Data에 대하여 sut를 `ToDoViewModel(databaseManager: MockLocalDatabaseManager.shared`로 설정을 하면, `func test_viewModel이_코어데이터에_저장된_projectUnit을_정상적으로_삭제하는지_테스트()` 메서드가 위에서 실행된 `func test_viewModel이_projectUnit을_정상적으로_코어데이터에_저장하는지_테스트()`메서드로 인한 Core Data에 저장된 값이 영향을 미치고 있음을 확인하였습니다.
- 이로 인하여, sut를 `ToDoViewModel(databaseManager: MockLocalDatabaseManager()`와 같이, 싱글톤 객체가 아닌 인스턴스를 생성한 결과, 각각 독립적인 테스트가 적용된 것 같습니다. InMemory 방식에서의 테스트를 어떻게 적용해야 하는지 조언을 구하고 싶습니다.

2022-09-20 12:55 UTC, ryan-son requested changes
수꿍, 휴, Step 2 수행하시느라 고생 많으셨어요. 변경사항들을 보니 여러분이 고생하신 모습이 많이 엿보였어요.

코드에 대한 피드백은 개별 코멘트를 참고해주세요.

# 질의응답

>### STEP 2-3 Questions
>#### Q1. ViewModel과 ViewController 분리
>- 하나의 ViewModel과 ViewController에서 각각 분리한 이유: 
>    1. 분기 처리가 많아 코드가 복잡해짐
>    2. 하나의 ViewModel이 3개의 data를 가지고 있는 게 어색함
>    3. ViewController(View)의 코드가 너무 길어짐
>- 각각 하나의 ViewModel과 ViewController를 사용했으나, 분기 처리가 많아 TableView 하나를 하나의 ViewController로 사용하고 해당 View(ViewController)에서 사용할 ViewModel을 따로 구현했습니다. 분기 처리는 하지 않지만 똑같은 코드가 여러 곳에서 사용되다 보니 이상하다는 느낌이 들었습니다. 또한 ViewController를 여러개 생성해서 구현하는게 어색하다고 생각했습니다. 이에 대하여 라이언의 의견을 여쭈어보고 싶습니다!

프로그래밍을 하는 것 자체도 트레이드 오프 과정의 연속입니다. 우리가 내리는 결정은 항상 좋은 방향만 있기는 어렵습니다. 여러분이 구현한 방식도 마찬가지입니다. 개별 코멘트에도 고민해보자는 내용을 적었지만, 이 부분에 대해서는 여러분이 직접 고민해보고 저와 이야기 나누어보았으면 좋겠습니다. 코드의 모양이 어색하기보다 목적에 따라 여러분이 방식을 정하는 것입니다. 고를 수 있는 선택지 중에서 어떤 선택지가 우리의 방향과 조금이라도 더 맞을지 고민해봅시다.
    
>#### Q2. ViewModel Test Code
>- ViewModel에 대한 Test Code를 구현했지만 Observable의 클로저가 잘 호출되는지 확인하기 위해 관찰하고 있는 data가 변할 때마다 전역변수로 선언해 준 count를 1씩 증가시켰습니다. ViewModel에서 구현한 클로저를 test 하는 방법이 궁금합니다. 또한 ViewModel 어떤 방식으로 Test 하는지 감이 오질 않습니다.

개인적으로 여러분이 테스트하신 방식대로 spy 형태의 테스트를 수행해볼 것 같습니다. 잘 호출되는지 검증하는 것 자체가 목적이니까요. true/false 형태의 테스트는 복수 호출될 수 있기 때문에 횟수 형태로 많이 진행합니다.

>### STEP 2-4 Questions
>#### Q1. InMemory 방식의 Core Data에 관한 Singleton 생성 고민
>- STEP 2-4 TroubleShooting에 언급한 바와 같이, InMemory 방식의 Core Data의 경우, 각각의 섹션 뷰 컨트롤러에 대하여 싱글턴 객체를 사용하여 공통된 Core Data Manager를 설정해보았습니다. 이에 대하여 해당 해결방법이 적절한 방식이었는지, 그리고 이보다 더 좋은 방법은 무엇이 있을지 질문드리고 싶습니다!

ViewController 자체를 테스트 할 것이 아니라면 실제 제품 로직에는 실제 CoreData 로직을 구현한 인스턴스를 사용해도 될 것 같네요. 앱 내부에서는 일반적으로 저장 공간을 공유하는 로직을 많이 구현하므로 싱글턴 패턴을 사용해도 괜찮을 것 같다는 의견입니다.

>#### Q2. InMemory 방식의 Core Data 유닛 테스트 방법 고민
>- InMemory 방식의 Core Data에 대하여 sut를 `ToDoViewModel(databaseManager: MockLocalDatabaseManager.shared`로 설정을 하면, `func test_viewModel이_코어데이터에_저장된_projectUnit을_정상적으로_삭제하는지_테스트()` 메서드가 위에서 실행된 `func test_viewModel이_projectUnit을_정상적으로_코어데이터에_저장하는지_테스트()`메서드로 인한 Core Data에 저장된 값이 영향을 미치고 있음을 확인하였습니다.
>- 이로 인하여, sut를 `ToDoViewModel(databaseManager: MockLocalDatabaseManager()`와 같이, 싱글톤 객체가 아닌 인스턴스를 생성한 결과, 각각 독립적인 테스트가 적용된 것 같습니다. InMemory 방식에서의 테스트를 어떻게 적용해야 하는지 조언을 구하고 싶습니다.

각 테스트가 이루어지기 전 항상 동일한 초기 상태임을 보장해주어야 합니다. 이를 위해 여러분이 적용하신 방식이나 테스트 케이스 타입 내부에 저장공간을 비워주기 위한 편의성 메서드를 구성하는 방식을 생각해볼 수 있습니다.

고생 많으셨습니다!

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Database/MockDataBase/MockLocalDatabaseManager.swift
> +        let container = InMemoryCoreDataContainer(name: "ProjectManager")
컨테이너를 제외하고는 로직이 동일해보이는데, `DatabaseManager`를 따로 구성하신 이유가 있으실까요? 이렇게 구성해두면 `LocalDatabaseManager`의 로직이 업데이트될 때 이 타입의 로직도 동일하게 변경해주어야해서 번거롭기도 하고 실수로 인해 둘 간의 로직이 달라질 수도 있을 것 같아서 여쭤봅니다~!

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Extensions/Date+Extension.swift
> +    }
[P3]
Swift API Design Guidelines에는 ['복잡도가 O(1)이 아닌 계산 프로퍼티는 문서화를 한다'](https://www.swift.org/documentation/api-design-guidelines/#general-conventions)라는 권고사항이 있어요. 이를 통해 Swift 사용자들은 연산 프로퍼티를 사용할 때 복잡한 로직이 아닐 것이라고 판단할거라고 추측해볼 수 있겠네요. 현재 프로퍼티의 구현부에서 `Locale`을 찾고 `DataFormatter` 인스턴스를 생성하고 세팅한 후에 포매팅하는 작업을 수행하고 있는데, 로직을 나누어볼 수 있을까요? 과거에 `DateFormatter`의 인스턴스 생성 비용에 대한 논의가 진행된 적이 있으니 아래 내용 참고해서 리팩토링 해보시면 좋겠어요. 여러분의 생각도 알려주세요~

- [How expensive is DateFormatter - Sarunw](https://sarunw.com/posts/how-expensive-is-dateformatter/)
- [How Expensive is DateFormatter? - Matthias Deuschl](https://deuschl.net/swift/how-expensive-is-dateformatter/)
- [25 iOS App Performance Tips & Tricks - Reuse Expensive Objects - Raywenderlich.com](https://www.raywenderlich.com/2752-25-ios-app-performance-tips-tricks#reuseobjects)
- [Is caching a NSDateformatter application-wide good idea? - Stack Overflow](https://stackoverflow.com/questions/27321993/is-caching-a-nsdateformatter-application-wide-good-idea)

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Extensions/Notification.Name+Extension.swift
> +}
[P2]
todo, doing, done 이외의 공간이 늘어갈수록 케이스가 기하급수적으로 많아질 것으로 예상되는데, 다른 해결 방법을 고민해보실 수 있으실까요?

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Extensions/OSLog+Extension.swift
> +}
`OSLog`를 이용하셨네요! 👍 Apple이 공식적으로 제공하는 로거라 콘솔에서도 내용 확인이 가능하다는 장점이 있어요. 여러분이 `OSLog` 프레임워크를 사용하신 이유는 무엇이었나요?

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Extensions/UIButton+Extension.swift
> +}
[P3]
구현부를 보고 기능은 이해했는데, 이 메서드가 어디에서 어떤 목적으로 사용될지 찾아보지 않고서는 알기 어려워보이네요. 문서화 주석을 남겨주실 수 있으실까요?

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Extensions/UIButton+Extension.swift
> +        }
`map(_:)` 메서드가 원하는 것은 `(Self.Element) -> T` 형식의 클로저이므로 아래와 같이 이니셜라이저를 직접적으로 전달해주는 방법도 있어요. 참고만하세요~

```swift
var splitText = text.split(separator: " ").map(String.init)
```

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/NameSpace/Section.swift
> +}
[P4]
전역 스코프에서 정의된 열거형이니 `Section` 보다 자신을 더 자세하게 설명할 수 있는 이름으로 정해두면 더 좋을 것 같아요. 이 요소들을 정의하는데 구조체, 클래스가 아니라 열거형을 사용한 이유가 있었나요?

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionController.swift
> +    var viewModel: ToDoViewModel?
[P3]
이 `ViewController`는 프로젝트를 추가하는 목적으로만 사용되는 것으로 보이는데, 자신이 필요한 기능보다 많은 기능을 가진 `ToDoViewModel`에 의존하고 있네요. 저는 두 가지 방향이 떠오르는데, 여러분은 어떤 방향이 더 나아보이시나요?

1. [ISP](https://en.wikipedia.org/wiki/Interface_segregation_principle)에 따라 필요한 인터페이스만 정의해서 사용한다.
2.  `ProjectAdditionController`가 `ProjectModificationController`와 유사한 UI와 로직을 다루므로 두 `ViewController`를 합친다. 그리고 `ToDo`, `Doing`, `Done` `ViewModel`이 수행하는 로직이 거의 유사하므로 이 또한 합치고 `ViewController`가 해당 `ViewModel`을 사용하도록 한다. 이 방식으로 사용하지 않는 인터페이스를 사용하게 구성한다.

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionScrollView.swift
> +    let datePicker: UIDatePicker? = {
UI 프로퍼티들을 공개하신 이유는 무엇이었나요?

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionScrollView.swift
> +            scheduleDescriptionTextView.bottomAnchor.constraint(equalTo: shadowView.bottomAnchor),
컨벤션 관련한 내용이라 팀마다 적용하는 방법이 다르다는 점 미리 말씀드릴게요. 일부 팀에서는 이렇게 쉼표 추가로 인해 변경사항을 만들지 않기 위해 마지막 요소에 쉼표를 추가하여 커밋하기도 합니다.

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionScrollView.swift
> +            right: 0.0)
보통 줄바꿈 컨벤션을 이렇게 정의하면 아래와 같이 적용하는 경우가 많아요.

```suggestion
        let contentInset = UIEdgeInsets(
            top: 0.0,
            left: 0.0,
            bottom: 15,
            right: 0.0
        )
```

그리고, UI 관련 상수 값은 namespace에 정의해두고 사용하시는 편이 이후에 추적하기 편하실거에요. 저는 `Metric`이라는 이름으로 정의해서 사용하곤 해요.

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/View/EditView/ProjectModificationController.swift
> +    var indexPath: Int?
프로젝트 추가나 수정 뷰는 유사해보이는데, 이 타입을 `ProjectAdditionController`와 별도로 구성하신 이유가 궁금해요~

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/View/MainView/DoingViewController.swift
> +                }
[P3]
이 로직은 순수하게 시간 간의 관계를 비교하고 있으니 특정 `ViewModel`에 종속시키지 않아도 좋을 것 같아요. 구현 방식은 두 가지 정도 생각해볼 수 있겠네요.

1. `deadline`은 `ProjectUnit`의 개념이므로 `ProjectUnit`의 연산 프로퍼티로 구성한다. `project.isDeadlinePassed` or `project.isExpired`
3. '기한이 지났다'라는 개념은 `ProjectUnit` 이외에도 활용될 수 있으므로 `Date`의 기능을 확장한다. `project.deadline.isExpired`

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/View/MainView/DoingViewController.swift
> +        }
이 subscription은 언제까지 유지되어야 하나요? 화면이 사라지는 등 이벤트가 발생했을 때 이 subscription을 폐기하여 
`ViewModel`로부터 `Observable` 요소를 메모리에서 해제하여 메모리 관리를 해야할 필요가 생길 것입니다. 이 문제를 다른 프레임워크에서는 어떻게 해결하고 있는지 알아봅시다.

- 키워드
  - `RxSwift`: `Disposable`, `DisposeBag`
  - `Combine`: [`Cancellable`](https://developer.apple.com/documentation/combine/cancellable), [`AnyCancellable`](https://developer.apple.com/documentation/combine/anycancellable)

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/View/MainView/DoneViewController.swift
> +    }
ViewController와 ViewModel을 `ToDo`, `Doing`, `Done`으로 구성해두셨는데, UI나 기능이 유사하다고 보이네요. PR을 통해 의도는 이해했어요. 여러분이 구현한 방식은 어떤 장단점이 있나요? 다른 구현 방법은 어떤 것이 있고 어떤 장단점을 가질지 생각해보는 것도 좋을 것 같아요.

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManager/View/MainView/PopoverController.swift
> +    var viewModel: Readjustable?
`Readjustable`이라는 이름만으로는 어떤 것을 재배치할지 예상하기 어려워 보일 수 있을 것 같아요.

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +    var sut2: DoingViewModel!
목적을 알고있으니 숫자 네이밍보다 더 좋은 이름을 지어줄 수 있을 것 같아요.

2022-09-20 12:55 UTC, ryan-son commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +    }
[P3]
삭제 테스트가 `addProject(title:body:date:)` 메서드의 성공 여부에 의존하도록 구성되어 있네요. 이니셜라이저를 통해 초기값을 구성하는 방식이나 테스트케이스 타입 안에 편의성 메서드를 구성하는 방식으로 테스트의 신뢰성을 확보해보는건 어떨까요?

2022-09-22 11:44 UTC, Hugh-github commented on ProjectManager/ProjectManager/Resource/Extensions/UIButton+Extension.swift
> +        }
감사합니다!

2022-09-22 11:47 UTC, Hugh-github commented on ProjectManager/ProjectManager/Resource/Database/MockDataBase/MockLocalDatabaseManager.swift
> +        let container = InMemoryCoreDataContainer(name: "ProjectManager")
`LocalDatabaseManager`와 `MockDatabaseManager`가 동일한 로직을 가지고 있다고 판단하여 CoreData의 동작 방식을 생성자를 통해 주입받도록 수정했습니다.

2022-09-22 11:49 UTC, Hugh-github commented on ProjectManager/ProjectManager/Resource/NameSpace/Section.swift
> +}
Section을 ProjectStatus로 수정했습니다. 
Name Space를 제거해주기 위해 사용한 타입입니다. struct 사용하지 않은 이유는 enum을 사용하면 생성자를 통한 불필요한 초기화를 막을 수 있다고 생각했습니다.

2022-09-22 12:02 UTC, Hugh-github commented on ProjectManager/ProjectManager/Resource/Extensions/UIButton+Extension.swift
> +}
`This property gets the last title from the button title` 문서화 주석을 추가했습니다.

2022-09-22 12:36 UTC, Jeon-Minsu commented on ProjectManager/ProjectManager/Resource/Extensions/Date+Extension.swift
> +    }
라이언이 코멘트해주신 문서들을 살펴보기 전에는 DateFormatter를 생성 비용이 그렇게 높을 줄 상상도 하지도 못하였습니다.
이에 성능을 향상시키기 위하여, DataFormatterManager를 생성하여 formatter라는 이름으로 DateFormatter 인스턴스를 미리 생성하고, 필요한 종류에 따라 기능을 달리하기 위하여, 저희의 경우에는 locale을 미리 선언하여, dateFormatter 인스턴스에 기존에 생성한 fomatter의 설정을 일부 바꾸고 반환하여, 관련 메서드를 정의하는 방식으로 구성해보았습니다.
그리고 싱글톤을 활용하여 추가적인 DateFormatter 생성을 지양하였습니다.
이를 통해, DateFormatter 생성 비용의 시간 복잡도를 1로 줄일 수 있었습니다.

2022-09-22 12:55 UTC, Jeon-Minsu commented on ProjectManager/ProjectManager/Resource/Extensions/OSLog+Extension.swift
> +}
OSLog를 사용하여 원격 환경에서 해당 로직에 대한 로그를 확인할 수 있고, 모든 level의 시스템에서 메시지를 캡쳐할 수 있는 효율적인 단일 고성능 API를 제공한다는 점이 유용하다고 생각하여 사용했습니다.

2022-09-23 08:03 UTC, Hugh-github commented on ProjectManager/ProjectManager/Resource/Extensions/Notification.Name+Extension.swift
> +}
Delegate 패턴을 사용해도 Protocol을 6개 만들어야 할 것 같습니다. 그렇다면 관리해야 하는 Protocol의 수가 많아져 해당 코드를 관리하기 어렵다고 생각합니다.
라이언이 생각하신 방식은 어떤 건지 조언을 구하고 싶습니다. 아래와 같은 방식으로 수정을 하면 `Notification`의 수는 줄어들지만 에러가 발생할 경우 어떤 Post에서 에러가 발생했는지 추적이 어려울 것 같습니다.
```swift
class A {
    init() {
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(addData(:)),
            name: Notification.Name("TODO"),
            object: nil
        )
    }

    @objc func addData( notification: NSNotification) {
        print("TODO 받음")
    }
}

class B {
    func postToDO() {
        NotificationCenter.default.post(name: Notification.Name("TODO"), object: nil)
    }
}

class C {
    func postToDO() {
        NotificationCenter.default.post(name: Notification.Name("TODO"), object: nil)
    }
}

let a = A()
let b = B()
let c = C()

b.postToDO()
c.postToDO()
```

2022-09-23 08:04 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionController.swift
> +    var viewModel: ToDoViewModel?
1번 방법으로 처리했습니다. 1번 방법을 선택한 이유는 저희가 생각했을 때 `ProjectAdditionController`와 `ProjectModificationController`의 각 버튼에서 처리하는 로직이 다르다고 생각합니다. 또한 각각의 ViewModel을 하나로 합치는 것보다 Protocol을 이용해 공통된 로직을 처리하는 `CommonViewModelLogic`을 만들고 다른 각각의 Protocol 또한 where 조건을 사용하여 처리하는 방향으로 수정을 했습니다.

2022-09-23 08:06 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/AddView/ProjectAdditionScrollView.swift
> +    let datePicker: UIDatePicker? = {
`TextField`, `TextView`, `DatePicker`가 현재 가지고 있는 text 및 date를 ViewModel에 전달하기 위해 접근제어를 설정하지 않았습니다.

2022-09-23 08:06 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/EditView/ProjectModificationController.swift
> +    var indexPath: Int?
가지고 있는 View는 유사하지만 각각의 버튼이 눌렸을 때 처리해야 하는 로직이 다르다고 생각해 별도로 구성했습니다.

2022-09-23 08:07 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/MainView/DoneViewController.swift
> +    }
저희가 처음에 해당 ViewController를 3개로 쪼갠 이유는 tableView가 사용하는 데이터가 다르다고 판단했습니다. 만약 3개를 쪼개서 사용할 경우 각각 ViewController에 대해 수정이 필요할 경우 따로 구현을 했기 때문에 장점이 있을 것 같습니다. 하지만 동일한 기능과 View를 가지게 된다면 코드의 중복이 발생하고 전체적인 수정이 필요할 때 각각의 ViewController를 모두 수정해야 하기 때문에 유지 보수 측면에서 비용이 증가할 것 같습니다.
리팩토링 과정에서 각각의 ViewModel은 유지하지만 ViewController 같은 경우 하나의 ViewController 생성하고 init을 통해 각각의 ViewModel을 주입하는 방식으로 수정했습니다.

2022-09-23 08:07 UTC, Hugh-github commented on ProjectManager/ProjectManager/View/MainView/PopoverController.swift
> +    var viewModel: Readjustable?
`StatusChangable`로 수정했습니다.

2022-09-23 08:16 UTC, Jeon-Minsu commented on ProjectManager/ProjectManager/View/MainView/DoingViewController.swift
> +        }
현재, 진행된 프로젝트 과정에서는 앱이 실행되고 있는 동안 subscribe가 해제되면 아니 될 것 같습니다.
처음에는 subscribe를 하지 않은 상태에서 이벤트가 감지 될 때, 해당 뷰컨트롤러의 뷰모델에서 subscribe를 시작해야 하나 고민을 해보았으나, 다른 뷰모델로 데이터가 move할 수 있기 때문에, subscribe를 함부로 해제하여서는 안 될 것 같습니다.
이에, 프로젝트가 좀 더 확장되어, 다른 화면으로 넘어가, 현재 화면이 disappear 된다면 그 시점에서는 unsubscribe를 해야 될 것 같은데,
라이언의 의도가 이에 부합하는지 궁금합니다.
일단, 해제시키는 기능은 Observable 내에서 unsubscribe 메서드로 구현을 해보았습니다!

2022-09-23 08:24 UTC, Jeon-Minsu commented on ProjectManager/ProjectManager/View/MainView/DoingViewController.swift
> +                }
1번 코멘트에 따라, isDeadlinepassed 연산 프로퍼티를 사용하여, ViewModel에 종속되었던 기능을 Project Unit으로 이전시켰습니다.

2022-09-24 01:14 UTC, Jeon-Minsu commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +    var sut2: DoingViewModel!
각각의 뷰모델을 이용하였으므로, toDoSut, doingSut으로 네이밍 변경하였습니다

2022-09-24 01:15 UTC, Jeon-Minsu commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +    }
아래와 같이 이니셜라이저 방식을 통해 초기값을 구성하여 삭제 기능만을 온전히 테스트 할 수 있도록 구성해보았습니다.

```swift
let firstProjectUnit = ProjectUnit(
    id: UUID(),
    title: "타이틀1",
    body: "바디1",
    section: toDoSut.identifier,
    deadLine: Date()
)
let secondProjectUnit = ProjectUnit(
    id: UUID(),
    title: "타이틀2",
    body: "바디2",
    section: toDoSut.identifier,
    deadLine: Date()
)
toDoSut.data.value = [firstProjectUnit, secondProjectUnit]
```

2022-09-26 19:25 UTC, ryan-son approved these changes
고생하셨습니다. 설계 관련한 질문은 만나서 이야기 나눠보도록 해요~

2022-09-26 19:25 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Database/LocalDatabaseManager.swift
>      }()
`isInMemory`가 `CoreDataContainer`를 초기화하는 것 이외에 사용되지 않는다면 이 값을 프로퍼티로 가지지 않고 이니셜라이저에서 `persistentContainer` 생성에 바로 이용할 수도 있을 것 같네요. `lazy` 키워드를 적용하신 이유가 있으실까요?

2022-09-26 19:25 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/DateFormatter/DateFormatterManager.swift
> +}
제가 소개해드린 내용에 대해 여러분들은 어떻게 생각하셨나요? 단순하게 블로그 글을 링크한 것이라 신뢰도가 떨어질 수도 있다고 생각하는데, 수용하신 이유는 무엇이었나요?

2022-09-26 19:25 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Extensions/UIButton+Extension.swift
> +        var splitedText = text.split(separator: " ").map(String.init)
지금은 해당되는게 없겠지만, 이 방식을 적용하신다면 앞으로 등장하는 동일한 형식을 같은 컨벤션으로 작성하셔야 한다는 점을 기억해둡시다~!

2022-09-26 19:25 UTC, ryan-son commented on ProjectManager/ProjectManager/View/AddView/ContentScrollView.swift
>          super.init(coder: coder)
`@available` attribute를 사용해보셨네요~ 어떤 이유로 적용해보게 되었나요?

2022-09-26 19:25 UTC, ryan-son commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
>      func test_바인딩하는_클로저가_정상적으로_호출되는지_테스트() {
테스트는 메서드 이름이 `test`로 시작하니 테스트라는 이름 대신에 Given-When-Then의 형식에 따라 '~는~하면~한다' 또는 '~는~일 때~이다'와 같은 이름으로 지어줘도 좋을 것 같아요.

2022-09-26 19:28 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Extensions/Date+Extension.swift
> +    }
제가 공유해드린 링크는 공식문서가 아니므로 100% 신뢰해서는 안 됩니다. 그런 논의가 이루어진 적이 있다는 것 뿐이지, 정말 그런지 확인해보는 과정이 필요할 수 있어요. 링크의 문서와 질의를 읽어보고 여러분이 찾아본 내용이나 알아본 내용이 있으신가요? 여러분의 의견도 궁금해요.

2022-09-26 19:44 UTC, ryan-son commented on ProjectManager/ProjectManager/Resource/Extensions/Notification.Name+Extension.swift
> +}
모든 경우에서 최고의 결과를 보여주는 해법은 없습니다. 여러 요소들을 절충해서 상황과 여러분에게 맞는 최선의 방법을 선택할 뿐인 거죠. 저라면 코드 응집도를 높이는 방향을 선택해서 아래 방법을 적용해볼 것 같네요.

- `ViewModel` 타입에서 `todo`, `doing`, `done` 요소를 가지고 View에서 전달받은 Action에 따라 요소의 상태를 변경

2022-09-26 19:54 UTC, ryan-son commented on ProjectManager/ProjectManager/View/EditView/ProjectModificationController.swift
> +    var indexPath: Int?
버튼과 같은 동작 요소에는 조건문이 포함되지 않는 것이 좋다라는 의견이실까요?

2022-09-26 19:57 UTC, ryan-son commented on ProjectManager/ProjectManager/View/MainView/DoingViewController.swift
> +        }
`RxSwift`와 `Combine`에서는 각각의 subscription들을 명시적으로 unsubscribe하는 인터페이스를 제공하지 않고, `DisposeBag`과 `Set<AnyCancellable>`에 담아두었다 `onComplete` 이벤트가 발생하면 구독을 종료하는 방식으로 메모리를 관리합니다. 참고하세요.

2022-09-26 19:59 UTC, ryan-son commented on ProjectManager/ProjectManager/View/MainView/DoneViewController.swift
> +    }
'tableView가 사용하는 데이터가 다르다고 판단했습니다'라는 부분에 대해 더 자세히 이야기 나눠보면 좋을 것 같네요. 세 tableView에서 다루는 데이터는 `ProjectUnit`의 상태 이외에 어떤 점이 다른가요?

2022-09-26 19:59 UTC, merged