프로젝트 관리 앱 [STEP 2] BaekGom
yagom-academy/ios-project-manager pull request #203
Opened 2022-09-23 13:28 UTC by Baek-Gom-95

안녕하세요 토니! @Monsteel 
MockData를 사용하지않고 바로 Realm 데이터베이스를 사용할려고 설계를 하다보니
생각보다 너무 오래 걸렸습니다 리뷰 잘부탁드립니다. 🙇‍♂️🙇‍♂️

## 📱 실행 화면
| 프로젝트 메인화면 |+ 버튼 터치 시 추가화면 |
| :--------: | :--------: |
| ![](https://i.imgur.com/K8hRmrJ.png) |![](https://i.imgur.com/svkCpB8.png)|

| 할일 추가 화면 |할일 추가후 리스트 화면 |
| :--------: | :--------: |
| ![](https://i.imgur.com/Wro7qNx.png) |![](https://i.imgur.com/0DzuCwN.png)|

| Realm 에 데이터 추가 |
| :--------: |
|![](https://i.imgur.com/IHnOyvr.png) |

## 🗂 폴더 구조

```
.
.
├── AppDelegate.swift
├── Assets.xcassets
│   ├── AccentColor.colorset
│   │   └── Contents.json
│   ├── AppIcon.appiconset
│   │   └── Contents.json
│   └── Contents.json
├── Base.lproj
│   └── LaunchScreen.storyboard
├── Coordinator
│   └── ApplyCoordinator.swift
├── Enum
│   ├── TodoCategory.swift
│   ├── TodoDetailButtonType.swift
│   └── TodoDetailType.swift
├── Extension
│   └── String+Extension.swift
├── Info.plist
├── ManageDatabase
│   ├── DatabaseManger.swift
│   └── RealmDatabaseManager.swift
├── Model
│   ├── TodoLocalModel.swift
│   └── TodoModel.swift
├── Protocol
│   ├── Coordinator.swift
│   ├── ReuseIdentifying.swift
│   └── TodoDatabaseManager.swift
├── SceneDelegate.swift
├── TodoDetail
│   └── TodoDetailViewController.swift
├── TodoDetailViewModel
│   └── TodoDetailViewModel.swift
├── TodoList
│   └── TodoListViewController.swift
├── TodoListView
│   ├── TodoListCell.swift
│   └── TodoListView.swift
└── TodoListViewModel
    └── TodoListViewModel.swift

```

## 🧑‍💻 코드 설명
- `ApplyCoordinator`: Coordinator 패턴을 사용해서 화면 전환을 위한 코드 입니다
- `DatabaseManager`: 데이터 베이스 관련 기능을 구현한 코드 입니다.
- `RealmDatabaseManager`: Realm 데이터 베이스 기능을 구현한 코드 입니다.
- `TodoModel`: Todo 모델입니다
- `TodoLocalModel`: Realm 모델 입니다
- `TodoListView`: TodoList 화면을 구현하는 코드 입니다.
- `TodoListCell`: TodoList에 TableCell을 구현하는 코드 입니다.
- `TodoListViewController`: TodoList 를 관리하는 컨트롤러 입니다.
- `TodoDetailViewController`: TodoDetail 을 관리하는 컨트롤러 입니다.
- `TodoListViewModel`: TodoListViewController 에서 받은 Action 처리
- `TodoDetailViewModel`: TodoDetailViewModel 에서 받은 Action 처리

## 🤔 궁금한점
- 두번째로 혼자하는 프로젝트이다 보니 전체적인 구조를 완벽하게 짜고 싶었습니다 재사용성은 올리고 의존성을 떨어뜨린다 를 목적으로 설계를 하고 싶었고 하지만 이때까지 코드를 짜놓고 조금씩 수정을 거쳐가며 구조를 고쳐왔기에 기초부터 구조를 잡고 들어가는것이 도저히 감이 잡히지 않았습니다 기초설계에 대해서 조언을 구하고 싶습니다.

- MVVM 설계에 대해서 ViewModel 파일의 코드가 구현되어야 하는 것이 컨트롤러에서 처리해야할 로직을 VM에서 처리하는 것으로 생각해서 구현했지만 역할이  정확하게 구분되어진 것인지 잘모르겠습니다.

2022-09-26 12:12 UTC, Monsteel requested changes
안녕하세요 백곰 :)
Step2 고생 많으셨습니다 ㅎㅎ ~~

우선 전체적인 구조는 잘 잡아주신 것 같아요.
조금 더 세밀한 디테일들(네이밍, 역할분리 등.)만 조금씩 다듬어 주시면 좋을것 같아요 👍 

이번 프로젝트에서 백곰이 집중했던 부분은 `재사용성은 올리고, 의존성은 떨어트린다` 군요!
그 두 밸런스가 참 어려울텐데도 신경써서 잘 작성해 주신것 같아요 👍 

다만, 각자의 역할이 조금 명확하게 구분되지는 않은것 같아요.(백곰이 질문주신 내용의 일부이긴 합니다)

viewModel이라는 개념에 대해 헷갈리신다면, [viewModel이라는 개념을 처음으로 소개한 글](https://learn.microsoft.com/ko-kr/archive/blogs/johngossman/introduction-to-modelviewviewmodel-pattern-for-building-wpf-apps)을 시작으로, 1차 소스에 가까운 내용들을 바탕으로 쭉 읽어보시면 좋을것 같아요.

viewModel은 여러 사람의 입과 코드를 거쳐가면서, 구현하는 사람의 해석에 따라서 여러 구현 레퍼런스들이 구현되다 보니, 사람마다 그 해석은 조금씩 다 다릅니다.

이럴때일수록, viewModel이라는 본질, 조금 더 근본적인(1차 소스에 가까운) 내용들을 통해 핵심을 들여댜 보는 것이 중요하다고 생각합니다.

이러한 방식이 viewmodel을 활용한 설계 전반에 대한 백곰의 이해도를 높히는데에 도움이 될거라 생각합니다!

==

구조에 대한 질문을 주셨는데, 조금 풀어서 위에 녹여내 봤습니다.
코드에 대한 리뷰는 아래에 달린 코멘트를 참고해주세요!

궁금하신점이 있으시면 언제든 말씀 부탁드립니다.

2022-09-26 12:12 UTC, Monsteel commented on ProjectManager/ProjectManager/Enum/TodoDetailButtonType.swift
> +    static let title = "Title"
Type들을 static let 으로 선언 해 주신 이유가 있나요~?! 🙋🏻‍♂️

2022-09-26 12:12 UTC, Monsteel commented on ProjectManager/ProjectManager/Extension/String+Extension.swift
> +struct DateManager {
Date를 format할 때 계속해서 DateManager인스턴스를 생성해 주는 방식으로 사용되는걸까요?
(코드상 사용부는 한 곳으로 파악되긴 합니다만!)

Date의 extension으로 처리해 볼 수 있을것 같은데, 요런 방법을 선택하신 이유가 있나요?!

2022-09-26 12:12 UTC, Monsteel commented on ProjectManager/ProjectManager/ManageDatabase/DatabaseManger.swift
> +        self.todoListViewBehaviorRelay.accept(self.todoListViewBehaviorRelay.value + [todoData])
accept 한 데이터와 realm에 저장된 데이터가 같다는 보장이 없습니다.

만약, self.realm.create(todoData: todoData) 가 실패하는 상황을 가정해 보았을 때,
21라인이 실패하고, 22라인이 성공하는 경우 데이터의 무결성이 깨지게 됩니다.

조금 더 안전하게, realm에 데이터를 저장하고, realm의 데이터를 accept해주면 어떨까요?

데이터의 관리 주체(원천)는 하나로 통합되어야, 무결성이 깨지는(실제와 다른 데이터가 생겨나는) 혹시모를 상황을 예방할 수 있습니다.

해당 `DatabaseManager` 전체 코드에 해당하는 리뷰입니다!

2022-09-26 12:12 UTC, Monsteel commented on ProjectManager/ProjectManager/ManageDatabase/RealmDatabaseManager.swift
> +            print(Realm.Configuration.defaultConfiguration.fileURL!)
`print`문은 debug를 위해 적어주신걸까요? debug를 목적으로 임시로 작성한 코드는 삭제 부탁드립니다!

2022-09-26 12:12 UTC, Monsteel commented on ProjectManager/ProjectManager/TodoDetail/TodoDetailViewController.swift
> +                    self.todoDetailViewModel.doneButtonClick(todo: self.createTodoContents(), todoDetailType: self.todoDetailType)
해당 tapped 이벤트를 처리할 때, Rx를 사용하여 처리하는것과, Rx를 사용하지 않고 처리하는 방법에는 어떤 차이가 있나요?

2022-09-26 12:12 UTC, Monsteel commented on ProjectManager/ProjectManager/TodoDetail/TodoDetailViewController.swift
> +    private func fetchNavigationBarButton() {
`fetchNavigationBarButton` 이름만 봤을땐, navigationBarButton을 return하는 함수처럼 보이지만, 실제로는 navigation의 leftbarButton의 title을 변경하는 역할에 그칩니다.

조금 더 적절한 네이밍을 지어주면 좋겠습니다 ✍🏻

전체적으로 함수의 이름이 함수가 하는 역할을 잘 표현하고 있는지 확인해보면 좋을것 같아요 ✨

2022-09-26 12:12 UTC, Monsteel commented on ProjectManager/ProjectManager/TodoList/TodoListViewController.swift
> +    private let realm = try! Realm()
불필요한 선언입니다.
전체적으로 legacy 정리가 필요해 보입니다 ✨

2022-09-26 12:12 UTC, Monsteel commented on ProjectManager/ProjectManager/TodoListView/TodoListView.swift
> +        .map { String($0.count) }
이곳에서 0과, 1이 각각 무엇을 나타고 있나요?
조금 더 명시적으로 처리할 수 있는 방법은 없을까요?

아래에도 유사한 코드가 보입니다!

2022-09-26 12:12 UTC, Monsteel commented on ProjectManager/ProjectManager/TodoListViewModel/TodoListViewModel.swift
> +    let todoData: Driver<[TodoModel]>
Driver를 사용하신 이유가 궁금합니다! 🙋🏻‍♂️

2022-09-26 12:12 UTC, Monsteel commented on ProjectManager/ProjectManager/Model/TodoLocalModel.swift
> +class TodoLocalModel: Object {
Local이라는 이름도 좋지만, [Entity](https://rh-cp.tistory.com/78)라는 이름은 어떤가요?
범용성에서 오는 이점으로 인해, 별다른 설명 없이 해당 model의 역할을 잘 나타낼 수 있을것 같아요!

2022-09-28 08:58 UTC, Baek-Gom-95 commented on ProjectManager/ProjectManager/Enum/TodoDetailButtonType.swift
> +    static let title = "Title"
- 첫번째는 뜻하지 않는 초기화를 하지 않기 위해서
- 두번째는 순수히 namespace 로서만 작동 시키기 위해서 입니다.
- 세번째는 자주 안 변하고 전역 변수 마냥 공통으로 관리하는 공용 자원이라서 입니다.

2022-09-28 09:17 UTC, Baek-Gom-95 commented on ProjectManager/ProjectManager/Extension/String+Extension.swift
> +struct DateManager {
토니의 말을 듣고 생각해보니 굳이 인스턴스를 생성하지 않아도 될거 같아  Date 의 extension으로 처리를 해보았습니다 🤔

2022-09-28 09:43 UTC, Baek-Gom-95 commented on ProjectManager/ProjectManager/ManageDatabase/RealmDatabaseManager.swift
> +            print(Realm.Configuration.defaultConfiguration.fileURL!)
Realm CRUD 확인을 위해 필요한거였는데 삭제를 안했었네요 삭제했습니다 😭

2022-09-28 10:10 UTC, Baek-Gom-95 commented on ProjectManager/ProjectManager/ManageDatabase/DatabaseManger.swift
> +        self.todoListViewBehaviorRelay.accept(self.todoListViewBehaviorRelay.value + [todoData])
데이터를 CUD할때  DataManager의 `func read() {
        self.todoListViewBehaviorRelay.accept(self.realm.read())
    }`를 호출해서 realm 의 데이터를 accept 해주었습니다 이렇게 하면 토니가 말씀하신 무결성이 안깨지는 것이 맞는걸까요? 🤔

2022-09-28 10:28 UTC, Baek-Gom-95 commented on ProjectManager/ProjectManager/TodoDetail/TodoDetailViewController.swift
> +                    self.todoDetailViewModel.doneButtonClick(todo: self.createTodoContents(), todoDetailType: self.todoDetailType)
- Rx 처리는 UI 이벤트 데이터를 갱신했을 때의 처리가 쉬워지고
- 코드가 훨씬 복잡해 집니다

2022-09-28 10:31 UTC, Baek-Gom-95 commented on ProjectManager/ProjectManager/TodoDetail/TodoDetailViewController.swift
> +    private func fetchNavigationBarButton() {
토니의 의견을 듣고 보니 네이밍이 부적절한거 같아 `func fetchLeftNavigationBarButtonTitle` 로 변경하였습니다😊

2022-09-28 10:33 UTC, Baek-Gom-95 commented on ProjectManager/ProjectManager/TodoList/TodoListViewController.swift
> +    private let realm = try! Realm()
`private let realm = try! Realm()` 가 쓰이는곳이 없어 삭제했습니다 😊 확인을 더 철저히 하겠습니다 😭

2022-09-28 12:27 UTC, Baek-Gom-95 commented on ProjectManager/ProjectManager/TodoListView/TodoListView.swift
> +        .map { String($0.count) }
0은 TodoCategory 가 무엇인지에 따라 filter를 해주기위해서 카테고리의 값을 가지고 있고
1은 그해당 카테고리의 시퀀스를 나타내고 있습니다
filter는  `.filter { (todoCategory) -> Bool in
            todoCategory.0 == self.todoStatus }` 로 좀더 명시적으로 처리했습니다
flatMap 같은경우에는 찾아보고 몇번 시도해봤지만 의도대로 풀어서 써지지 않았습니다 혹시 이부분 알려주실수 있을까요?

2022-09-28 12:29 UTC, Baek-Gom-95 commented on ProjectManager/ProjectManager/TodoListViewModel/TodoListViewModel.swift
> +    let todoData: Driver<[TodoModel]>
Driver는 UILayer에서 반응형 작업을 좀 더 직관적으로 사용할 수 있도록 제공되는 개념이고 Driver는 MainScheduler로 지정되어 있습니다. 때문에 UI 관련적용에는 MainThread 에서 처리를 해야하기 때문에  Driver를 사용하여 실수를 방지하는 것이 좋을거 같다 생각했습니다

2022-09-28 12:31 UTC, Baek-Gom-95 commented on ProjectManager/ProjectManager/Model/TodoLocalModel.swift
> +class TodoLocalModel: Object {
범용성을 생각해보니 Entity가 더 나을거 같아 변경하였습니다 😊

2022-09-29 09:11 UTC, Monsteel commented on ProjectManager/ProjectManager/TodoListView/TodoListView.swift
> +        .map { String($0.count) }
이 부분은 해당 부분에서 사용한 RxSwift의 operators들이 각각 어떤 역할을 하는지 학습해보시면 이해에 도움이 되실것 같아요 ✨

2022-09-29 09:17 UTC, Monsteel approved these changes
ㅎㅎ 수고 많으셨습니다 백곰 !

새롭게 사용한 모든 기술에 대해 높은 이해도를 가지는건 백곰뿐만 아니라, 당장 저에게도 어려운 일일텐데요! 😭

이번에 프로젝트에서 사용하신 기술들에 대한 지식을 조금 더 고도화 시키는 작업(?), 조금 더 깊게 이해하는 과정이 꼭 이어졌으면 좋겠습니다! 🍀

수고하셨습니다 백곰 :)

2022-09-30 08:20 UTC, merged