프로젝트 관리 앱 [STEP 2] 키위
yagom-academy/ios-project-manager pull request #205
Opened 2022-09-27 10:25 UTC by kiwi1023

안녕하세요 태태(@uuu1101) 😁!
드디어 PR을 보내게 되네요..ㅜㅜ!! 
항상 디스코드 답장도 잘해주시고, 많이 도와주셔서 정말 감사드립니다!
리뷰 잘 부탁드립니다! 

# 👨🏻‍💼 프로젝트 매니저
> 기간: 2022-09-05 ~ 2022-09-16
> 
> 팀원: [Kiwi](https://github.com/kiwi1023)
> 
> 리뷰어: [태태](https://github.com/uuu1101)

## 📦 파일 구조
```
.
├── AppDelegate.swift
├── Assets.xcassets
│   ├── AccentColor.colorset
│   │   └── Contents.json
│   ├── AppIcon.appiconset
│   │   └── Contents.json
│   └── Contents.json
├── Info.plist
├── Model
│   ├── Extension
│   │   └── Date+formatter.swift
│   ├── Manager
│   │   ├── Protocol
│   │   │   └── DBManagerable.swift
│   │   └── TodoDataManager.swift
│   ├── Status.swift
│   └── Todo.swift
├── SceneDelegate.swift
├── View
│   ├── MainView.swift
│   ├── NavigationBarModifier.swift
│   ├── TodoContentView.swift
│   ├── TodoListRow.swift
│   └── TodoListView.swift
└── ViewModel
    ├── MainViewModel.swift
    ├── TodoContentViewModel.swift
    ├── TodoListRowViewModel.swift
    └── TodoListViewModel.swift
 ```
 
## 🤔 고민한 점 및 궁금한 점

### 1.
1. todoData status 변경시
![](https://i.imgur.com/d7k8fYG.gif)

2. 삭제 시 
![](https://i.imgur.com/gJTBH0O.gif)

위에 영상처럼 status를 변경하거나, 삭제를 할 경우 뷰에서 제대로 업데이트를 하지 못하고 각각의 row뷰의 내용들이 뒤죽박죽 섞이는 현상을 겪었었습니다. 뿐만아니라 Edit을 하였을 때에도 변경사항을 반영하지 못하는 경우가 있었습니다. 

하지만 todoDataManager 내부의 모델 데이터는 문제 없이 변경이 되었기 때문에 이는 뷰의 문제라고 생각하였습니다. 

그래서 해당 데이터를 담당하는 뷰인 TodoListRow 뷰를 리팩토링 하기 시작 하였고 여러 고민 끝에 아래의 사진들 처럼(1번을 2번으로) StateObject를 ObservedObject로 변경하였더니 모든 문제가 사라졌습니다.
1. ![](https://i.imgur.com/ofwfjaa.png)
2. ![](https://i.imgur.com/gYfF03F.png)

하지만 문제를 해결했음에도 불구하고 어떠한 원인 때문에 이런 현상이 발생하였는지 모르겠습니다. 또한 애플에서는 Observable Object를 처음 초기화할 때는 StateObject를 사용하고, 이미 객체화된 것을 넘겨 받을 때 ObservedObject의 사용을 추천하고 있는데, 해당 뷰모델을 처음 초기화 함에도 불구하고 왜 ObservedObject에서는 일어나지 않는 문제가 StateObject에서는 일어나고 있는지 궁금합니다!

### 2.
1. ![](https://i.imgur.com/cKhLtYC.png)
2. ![](https://i.imgur.com/yyu7shJ.png)

내용을 Edit하거나 Add 할때 사용 하는 뷰인 TodoContentView를 띄운다음 작업을 진행하고 해당 뷰를 화면에서 사라지게 하면 위에 사진에서 보이는 오류가 계속해서 발생하고 있습니다. 

이와 관련하여 구글링을 해본결과 1번 사진 같은 경우는 [xcode업데이트로 인한 문제](https://developer.apple.com/forums/thread/711899)라고 찾았으나, 이후 낮은 xcode 버전에서 실행한 결과 동일한 문제가 발생 되었습니다.

또한 2번 사진 같은 경우도 [스택오버플로우 등](https://stackoverflow.com/questions/65316497/swiftui-navigationview-navigationbartitle-layoutconstraints-issue) 여러곳을 찾아 보았지만 `.navigationViewStyle(.stack)`을 추가하라는 말만 나오고 있고(이미 추가를 진행) 이것으로는 해결이 되지 않았습니다.

swiftUI에 대한 전반적인 이해가 부족하여 그런것이 겠지만, 제가 생각한 바로는 swiftUI는 선언형UI로 뷰를 선언한 이후에 padding등으로 layout을 잡는것으로 알고 있는데 왜 이런 문제가 생기는지 궁금하고, 이에 대한 태태의 생각이 궁금합니다!

### 3.
프로젝트의 파일분리를 어떤식으로 하는지 몰라 일단 저의 임의 대로 하였는데요. 물론 이는 정답이 없는 것으로 알고 있지만 태태가 혹시 추천하시는, 또는 선호하시는 스타일이 있는지 궁금합니다!

2022-09-29 07:35 UTC, uuu1101 requested changes
안녕하세요 @kiwi1023 !
처음 사용해보는 기술스택으로 STEP 진행하시느라 고생하셨습니다 :) 

## 궁금한점에 대한 답변
1번 경우에는 StateObject 와 ObservedObject의 차이점이 무엇이 있는지 확인해보시면 원하는 답을 얻을 수 있을 것 같은데요. 말씀해주신 추천하는 사용법 말고 왜 StateObject와 ObservedObject를 사용하는지 둘의 차이점은 무엇이고 어떻게 동작하는지를 생각해보신다면 해당 질문에 답을 찾으실수 있을 것 같습니다 😊 

2.해당 부분은 이런 저런 동작을 다해보았는데, 저에게는 오류가 노출되지 않고 있어서 확인을 제가 못하였는데요. 에러가 노출되는 시나리오를 알려주시면 한번 더 확인해보도록 하겠습니다!  

3. 프로젝트의 폴더링에 관련해서 질문을 주셨는데, 저는 관심사에 따라서 분류를 합니다. 
<img width="276" alt="스크린샷 2022-09-29 오후 4 27 56" src="https://user-images.githubusercontent.com/49808034/192967671-cac28e7e-f839-4174-8de4-6094faf38a91.png">

물론 디자인 패턴이나 사용하는 기술스택에 맞추어서 폴더를 관리하고 있고 현재 키위가 해두신 분류와 비슷하다고 생각이 듭니다.   
**설계한 구조와 동일하게 끔** 폴더를 관리하는게 좋다고 생각합니다.  

4. 이렇게도 해결이 가능하군요. Nested ObservableObjects를 인식하는 못하는 이유에 대해서 여러가지 시도를 해보았는데, 해당 ObservableObject가 Struct일 경우에는 제대로 동작을하고 Class일 경우에는 동작을 하지 않더라구요. 
해당 방법도 좋은 해결 방안인것 같습니다. 해당 부분에 대해서 이해하신바를 설명해주실수 있을까요?

2022-09-29 07:35 UTC, uuu1101 commented on ProjectManager/ProjectManager/Model/Todo.swift
> +struct Todo: Equatable, Identifiable {
Equatable 과 Identifiable을 사용하신 이유가 궁금합니다 👀

2022-09-30 05:14 UTC, kiwi1023 commented on ProjectManager/ProjectManager/Model/Todo.swift
> +struct Todo: Equatable, Identifiable {
뭐에 씌였었는지 id를 비교할때 equatable이 생각 하였는데 UUID는 이미 Equatable이 채택된 타입이라 불 필요하다 생각하여 삭제 해주었습니다. 또한 Identifiable은 프로젝트 초기 list 구현에 필요하여 채택을 해주었는데 수정과정에서 필요 없어졌으나 삭제하는 것을 깜빡하였습니다! 이또한 수정 하였습니다!

2022-10-01 07:17 UTC, uuu1101 commented
STEP2 고생하셨습니다!
Nested ObservableObjects과 관련하여 디스코드에서 이야기를 나눴었고, STEP3 관련하여서도 구현하신 부분을 잘 보았습니다. 
로직적인 부분에서는 문제가 없어서 이야기 나눴던 방향으로 리팩토링을 진행하시면 될 것 같습니다.

2022-10-01 07:17 UTC, merged