프로젝트 매니저 [STEP 2] 스톤
yagom-academy/ios-project-manager pull request #240
Opened 2023-01-18 07:56 UTC by lws2269

안녕하세요! 올라프(@1Consumption) 
STEP2 구현이 완료되어 PR요청 드립니다.
MVVM패턴을 통해 구현하려고 노력해보았는데 아직 미흡한점이 많은 것 같습니다.
잘부탁드립니다 🙇‍♂️🙇🏻‍♂️🙇🏼‍♂️🙇🏽‍♂️🙇🏾‍♂️🙇🏿‍♂️

---
## 구현 내용 - 화면
### 새로운 일정 등록
![](https://i.imgur.com/tOOnAoI.gif)
### 상태 변경
![](https://i.imgur.com/bFGyCKv.gif)
### 일정 삭제
![](https://i.imgur.com/tWtjxOc.gif)
### 일정 수정 - edit 버튼 클릭 전까지 비활성화
![](https://i.imgur.com/vl0wY0e.gif)

## 구현 내용 - 코드
### Model
- Category
    - work에 대한 상태 todo, doing, done을 가진 enum타입입니다. 해당 상태에 필요한 요소를 반환하는 계산속성을 포함하고있습니다.
- Work
    - 각 Cell에 필요한 정보를 가지고 있는 구조체입니다.
### View
- ListCell
    - ListView -> tableView에서 사용되는 CustomCell입니다.
- ListView
    - todo, doing, done 각 상태에 대한 정보를 표시하는 커스텀 뷰입니다. tableView를 포함하고 있습니다.
- MainViewController
    - 3개의 ListView를 가지고 있는 메인이되는 상위 뷰입니다.
- WorkFormController
    - edit, add시 표현되는 모달 View입니다.
- CircleLabel
    - ListView 내부에서 각 Category에 대한 갯수를 표현하기 위한 둥글게 커스텀된 UILabel입니다.
### ViewModel
- MainViewModel
    - MainViewController의 뷰 모델입니다. 해당 뷰모델에서 3개의 ListView에 대한 데이터를 다룹니다..
- WorkFormViewModel
    - WorkFormController의 뷰 모델입니다. 해당 부분에서 work을 반환하고, 데이터의 업데이트에 대한 부분은 MainViewModel에서 다룹니다.
- ListViewModel
    - ListView에 대한 뷰 모델입니다. category의 count에 대한 내용을 다룹니다.
- ListCellViewModel
    - ListCell의 뷰 모델입니다.

---
# 고민했던 점
## UITableView Delegate, Datasource
- `ListView`에서 각 테이블뷰에 대한 `Delegate`, `Datasource`를 구현하려 했으나, 세가지 리스트 뷰의 데이터를 동기화 하는 과정에서 어려움을 겪어 `MainViewController`에서 세가지 테이블뷰에 대한 모든 `Delegate`, `Datasource`를 구현하였습니다.
```swift
func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    switch tableView {
    case doneListView.tableView:
        return viewModel.doneList.count
    case doingListView.tableView:
        return viewModel.doingList.count
    case todoListView.tableView:
        return viewModel.todoList.count
    default:
        return 0
    }
}

func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    guard let cell = tableView.dequeueReusableCell(withIdentifier: ListCell.identifier, for: indexPath)
            as? ListCell else { return ListCell() }

    cell.delegate = self

    switch tableView {
    case doneListView.tableView:
        cell.configureData(work: viewModel.doneList[indexPath.row])
    case doingListView.tableView:
        cell.configureData(work: viewModel.doingList[indexPath.row])
    case todoListView.tableView:
        cell.configureData(work: viewModel.todoList[indexPath.row])
    default:
        break
    }

    return cell
}

func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle,
               forRowAt indexPath: IndexPath) {

    switch tableView {
    case doneListView.tableView:
        viewModel.deleteWork(data: viewModel.doneList[indexPath.row])
    case doingListView.tableView:
        viewModel.deleteWork(data: viewModel.doingList[indexPath.row])
    case todoListView.tableView:
        viewModel.deleteWork(data: viewModel.todoList[indexPath.row])
    default:
        break
    }
}

func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    let workFormViewController = WorkFormViewController()
    let navigationViewController = UINavigationController(rootViewController: workFormViewController)

    switch tableView {
    case doneListView.tableView:
        workFormViewController.viewModel.work = viewModel.doneList[indexPath.row]
    case doingListView.tableView:
        workFormViewController.viewModel.work = viewModel.doingList[indexPath.row]
    case todoListView.tableView:
        workFormViewController.viewModel.work = viewModel.todoList[indexPath.row]
    default:
        break
    }

    workFormViewController.viewModel.isEdit = false
    workFormViewController.delegate = self
    navigationViewController.modalPresentationStyle = UIModalPresentationStyle.formSheet

    present(navigationViewController, animated: true)
}
```

# 조언을 얻고싶은 부분
## 하위 뷰에서 상위 뷰의 뷰모델
- `UITableView` `Delegate`, `Datasource`를 각 `ListView`에서 채택하여 구현하려면 `ListView`에서 `MainViewModel`을 가지고 있어야 될 것 같은데 하위 뷰에서 상위 뷰의 뷰 모델을 가지고 상위 뷰의 데이터를 조작하는 방법도 하나의 방법일까요?

## MVVM
`MVVM` 패턴을 구현하는데에 있어 부족한 점이 많은 것 같습니다. 이번 프로젝트에서는 MVVM을 이해하는 것을 목표로 하고싶습니다. 구현함에 있어서 잘못된 점이나 이해가 부족하다 싶은 부분에 대해 아낌없는 조언 부탁드립니다. 감사합니다

2023-01-18 19:09 UTC, 1Consumption requested changes
고생하셨습니다. @lws2269 

MVVM이 처음이라 많이 어려우셨을거라 생각이됩니다.
아직 조금 아쉽지만 대략적인 컨셉은 이해하신듯 합니다.
코드에 대해 디코에서 같이 얘기를 하면 좋겠어요.

아래는 질문주신 점에 대한 제 생각입니다.

`UITableView` `Delegate`, `Datasource`를 각 `ListView`에서 채택하여 구현하려면 `ListView`에서 `MainViewModel`을 가지고 있어야 될 것 같은데 하위 뷰에서 상위 뷰의 뷰 모델을 가지고 상위 뷰의 데이터를 조작하는 방법도 하나의 방법일까요?
> 아니요. 이러면 은닉화가 깨진다고 생각해요. 
`MainViewModel` 전체가 하위 뷰에서 필요한게 아니라고 생각됩니다. 따라서 이는 `view` 끼리 delegate를 통해 이벤트를 전달하여 해결하면 될 문제 같아요.

--------------------
나머지는 코멘트를 참고해주세요.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager.xcodeproj/project.pbxproj
> +	objectVersion = 54;
이 변경사항은 의도된건가요?

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/AppLifeCycle/AppDelegate.swift
> +class AppDelegate: UIResponder, UIApplicationDelegate {
final을 붙여도 좋겠습니다.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/AppLifeCycle/AppDelegate.swift
> +    }
필요없는 주석은 과감하게 제거해주세요.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/Model/Category.swift
> +    var description: String {
[CustomStringConvertible](https://developer.apple.com/documentation/swift/customstringconvertible) 이라는 프로토콜을 적용해보세요. 직접 `description`을 사용하는건 안좋아 보이네요.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/Model/Category.swift
> +    }
음... 이 프로퍼티는 정확히 어떤 일을 하는지 이름만 봐서는 모르겠네요. other이 뭘까요? 그리고 꼭 튜플을 반환해야할지 의문입니다.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/Model/Work.swift
> +    let id = UUID()
이 id를 외부에서 알아야하나요?

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/Model/Work.swift
> +    var endDateToString: String {
변수명에 type이 들어가는건 중복이라 안좋다고 생각합니다. 이미 type으로 확인을 할 수 있으니까요.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/Model/Work.swift
> +}
이거는 여기에 왜 있는건가요?

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/CircleLabel.swift
> +    }
왜 이 시점에 이 코드를 실행하나요? 이유가 궁금합니다.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/CircleLabel.swift
> +    }
이 메소드는 어떤 역할을 하나요?

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListCell.swift
> +    var viewModel = ListCellViewModel()
이 뷰모델을 외부에서 알아야하나요? 그리고 `viewModel`이 가리키는 주소가 바뀔일이 있을까요?

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListCell.swift
> +    func showPopover(cell: ListCell)
오우.. cell 자체를 보내지말고 필요한 정보만 보내도록하죠.
사용하는 곳을 보니 `ListCell`이 필요한게 아니라 `Work`가 필요하고, `sourceView`가 필요하니 `UIView` 정도로 추상화 해서 보내면 좋겠습니다.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListCell.swift
> +            self?.dateLabel.textColor = work.endDate < Date() ? .red : .black
MVVM에서 View는 멍청해야한다고 생각합니다. date를 비교하는거도 로직이라고 생각해요. 그래서 이부분도 viewModel이 담당해야할거같습니다.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListCell.swift
> +    func configureData(work: Work) {
띄어쓰기가 안되어있네요.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListCell.swift
> +        viewModel.work = work
매번 ViewModel을 바꾸는게 낫지 않을까요? 이러면 ViewModel이 가지고 있는 상태를 초기화하기 어렵습니다.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListCell.swift
> +    }
이 메소드들을 extension으로 뺀 기준이 뭘까요?

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListCell.swift
> +        if gestureRecognizer.state == .ended {
이거도 로직 같아요. viewModel에서 해야할 일 같습니다.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListCell.swift
> +    @objc func handleLongPress(gestureRecognizer: UILongPressGestureRecognizer) {
외부에서 몰라도 되는 메소드 같습니다.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListView.swift
> +    lazy var categoryLabel: UILabel = {
lazy var인 이유가 있나요?

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListView.swift
> +        backgroundColor = .systemGray5
backgroundColor를 바꾸는 작업도 layout에 해당될까요?

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +        }
view의 viewModel에 직접 접근하는건 너무 추상화가 안되어있다고 생각해요. 차라리 view에 메소드를 하나 만들고, 그 내부에서 각 작업을 진행하는건 어떨까요?

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +        }
view로 분기를 안치는 방법은 없을까요?

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +            cell.configureData(work: viewModel.todoList[indexPath.row])
여기서 cell에 필요한 viewModel을 만들어서 넘겨주면 좋겠습니다.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/WorkFormController.swift
> +        }
여기도 마찬가지입니다. 기본값이나 분기가 들어간 부분도 viewModel에서 처리해야할 부분이라고 생각합니다.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/MainViewModel.swift
> +            todoList.append(data)
이부분은 if문 내에서 return을 하는게 아니라 if else문을 사용하는게 가독성이 더 좋아보입니다.

2023-01-18 19:09 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/MainViewModel.swift
> +            }
여기는 else절이 없으니 guard문으로 바꾸는게 어떨까요?

2023-01-24 15:47 UTC, lws2269 commented on ProjectManager/ProjectManager/AppLifeCycle/AppDelegate.swift
> +class AppDelegate: UIResponder, UIApplicationDelegate {
넵! 명시해주었습니다!

[fbf8d42](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/fbf8d42669765fea8ed7b33f0388c28eb3f30974)

2023-01-24 15:48 UTC, lws2269 commented on ProjectManager/ProjectManager.xcodeproj/project.pbxproj
> +	objectVersion = 54;
의도한 사항은 아닙니다. 커밋남길때 신경쓰도록 하겠습니다😅

2023-01-24 15:49 UTC, lws2269 commented on ProjectManager/ProjectManager/AppLifeCycle/AppDelegate.swift
> +    }
제거하였습니다! 신경쓰겠습니다.

[fbf8d42](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/fbf8d42669765fea8ed7b33f0388c28eb3f30974)

2023-01-24 15:50 UTC, lws2269 commented on ProjectManager/ProjectManager/Model/Category.swift
> +    var description: String {
description이 이 프로토콜로 구현되어있었군요..!!! 가르침 감사합니다 🫡

[1e2b220](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/1e2b220a0e25b28ba171ad69afc504334fb8f401)

2023-01-24 15:53 UTC, onestone23 commented on ProjectManager/ProjectManager/Model/Category.swift
> +    }
MainViewModel에서 해당 로직 처리하도록 리팩토링 진행하면서 삭제 하였습니다!

[cad8346](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/cad83467af9ba01dc6f0296ab049b388c6492fb1)

2023-01-24 15:56 UTC, lws2269 commented on ProjectManager/ProjectManager/Model/Work.swift
> +    let id = UUID()
Equatable 프로토콜 채택을 통해 id로 비교하는 로직을 Work끼리 비교하도록 리팩토링 진행했습니다.

[079cc5f](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/079cc5ff8742333bfce7dd736b7f5be0c9b5f98e)

2023-01-24 15:59 UTC, lws2269 commented on ProjectManager/ProjectManager/Model/Work.swift
> +}
Work에 대한 로직이라 생각되어 Work와 같은 위치에 두었는데, 말씀해주신대로 WorkForm에 대한 Delegate여서 WorkFormDelegate로 네이밍 변경하고 위치변경하였습니다. 
감사합니다!

[a473b46](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/a473b46a6e1a64b579b4a96f6d1e5e1f76f8b25c)

2023-01-24 16:07 UTC, onestone23 commented on ProjectManager/ProjectManager/View/ListCell.swift
> +    var viewModel = ListCellViewModel()
기존의 로직에서는 let으로 선언해도 되었다고 생각합니다. 
아래 코멘트를 참고하여 ViewModel을 갈아치우는 로직으로 리팩토링 진행하면서 let 키워드를 사용하지 못하게되어 var 키워드 그대로 보존하였습니다.

[a4bdec5](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/a4bdec5cbdb63523c07965667ac9486931d6720f)

private 키워드 명시
[a8fba04](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/a8fba043d16dd13bb782b3ff26417ca1f6fa8ae0)

2023-01-24 16:10 UTC, onestone23 commented on ProjectManager/ProjectManager/View/ListCell.swift
> +    func showPopover(cell: ListCell)
cell을 그대로 보내버리는 무지막지한 코드를 작성해버렸네요.. 죄송합니다..
말씀해주신대로 리팩토링 진행해보았습니다.

[27bd527](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/27bd5273770824912850323a69b2b250d5161f90)

2023-01-24 16:14 UTC, lws2269 commented on ProjectManager/ProjectManager/View/ListCell.swift
> +            self?.dateLabel.textColor = work.endDate < Date() ? .red : .black
textColor에 대한 로직을 viewModel에서 처리하게 되다보니, UIColor를 반환하는 로직이 필요하다고 생각되어 UIColor를 반환하는 로직을 뷰모델에 구현하였습니다.
근데 여기서 ViewModel이 UIKit을 import하고 있는게 굉장히 어색하게 느껴지는데 올라프의 의견은 어떠신가요 ..?
 
[5a456a2](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/5a456a23bd7354760364218100864838f8069263)
[291c600](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/291c60067fba306d2142306a2a2346995b6e5d3d)

2023-01-24 16:14 UTC, lws2269 commented on ProjectManager/ProjectManager/View/ListCell.swift
> +    func configureData(work: Work) {
처리해주었습니다! 조금 더 꼼꼼히 보겠습니다 감사합니다
[8d60a4f](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/8d60a4ff8dd6f855b585f252da505eb8b221144f)

2023-01-24 16:15 UTC, lws2269 commented on ProjectManager/ProjectManager/View/ListCell.swift
> +        viewModel.work = work
재사용 되는 시점에 ViewModel을 갈아치우도록 진행해보았습니다.
[a4bdec5](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/a4bdec5cbdb63523c07965667ac9486931d6720f)

2023-01-24 16:16 UTC, lws2269 commented on ProjectManager/ProjectManager/View/ListCell.swift
> +    }
제스쳐에 관한 로직을 분리한다고 분리해보았는데 다시 한번 보니 어색함이 있는 것 같아 extension을 삭제하였습니다 감사합니다.
[8d60a4f](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/8d60a4ff8dd6f855b585f252da505eb8b221144f)

2023-01-24 16:19 UTC, lws2269 commented on ProjectManager/ProjectManager/View/ListCell.swift
> +        if gestureRecognizer.state == .ended {
해당 부분 ViewModel로 분리하여 로직에대한 처리를 해주었는데, 이부분에서도 UILongPressGestureRecognizer 에 대한 state가 필요하다보니 ViewModel에서 UiKit을 import 하게 되었는데, 이 부분이 조금 어색하게 느껴집니다. 올라프의 의견은 어떠신가요?

[a4bdec5](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/a4bdec5cbdb63523c07965667ac9486931d6720f)

2023-01-24 16:20 UTC, lws2269 commented on ProjectManager/ProjectManager/View/ListCell.swift
> +    @objc func handleLongPress(gestureRecognizer: UILongPressGestureRecognizer) {
명시해 주었습니다. 꼼꼼히 체크하도록 노력해보겠습니다 😅

[b02b505](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/b02b505caaf166eda8906ddea224ca31e6b5a62a)

2023-01-24 16:23 UTC, onestone23 commented on ProjectManager/ProjectManager/View/ListView.swift
> +    lazy var categoryLabel: UILabel = {
접근 시점에 category에 대한 값을 가져오기 위해 lazy var로 선언하였습니다.

let으로 키워드를 변경하고 configureData 메서드를 구현하여 메서드 내부에서 값들을 configure해주는 방식으로 리팩토링 진행하였습니다.
[997082e](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/997082eb411a9d432b4f3adabb7738aae401a080)

2023-01-24 16:23 UTC, onestone23 commented on ProjectManager/ProjectManager/View/ListView.swift
> +        backgroundColor = .systemGray5
init 시점에 처리하도록 변경하였습니다.
[786d4d9](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/786d4d9da14e1305c1d5195e601cfd69b4b8f653)

2023-01-24 16:25 UTC, lws2269 commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +        }
didChangeCountValue라는 메서드를 ListView 내부에 구현해줌으로써 처리하도록 진행하였습니다

[997082e](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/997082eb411a9d432b4f3adabb7738aae401a080)

2023-01-24 16:27 UTC, lws2269 commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +        }
MainViewController 내부에서 UITableViewDelegate, UITableViewDatasource를 채택하여 구현한 부분을 모두 제거하고 ListView에서 채택함으로써 분기처리에 대한 부분을 해결하였습니다. 데이터 전달에 대해서는 delegate를 선언하여 처리해주었습니다.
이렇게 처리함으로써 코드가 조금 더 깔끔해 진 것 같습니다.
- section을 통한 분기처리를 시도하려 했지만, 각각의 테이블 뷰여서 섹션으로 분기처리 할 수 없어 위와 같이 진행하였습니다.

[9db130f](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/9db130f813c3bb2f74871247d8207a9a35b6c160)

2023-01-24 16:29 UTC, lws2269 commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +            cell.configureData(work: viewModel.todoList[indexPath.row])
아래 커밋에서 viewModel을 만들어 넘기는 로직으로 변경하였습니다.
[a4bdec5](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/a4bdec5cbdb63523c07965667ac9486931d6720f)

리팩토링하는 과정에서 분기처리 하는 부분도 해결되었습니다.
[9db130f](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/9db130f813c3bb2f74871247d8207a9a35b6c160)

2023-01-24 16:33 UTC, lws2269 commented on ProjectManager/ProjectManager/View/WorkFormController.swift
> +        }
해당 부분도 ViewModel에서 UIColor를 반환하는 로직으로 리팩토링 진행하다보니 UiKit을 import하고있습니다. ㅠㅠ 
위 코멘트 들과 같은 상황인데 올라프의 의견이 궁금합니다.

[abddd68](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/abddd6891486fdcfef7f42278477b8476989a0dc)

2023-01-24 16:35 UTC, lws2269 commented on ProjectManager/ProjectManager/ViewModel/MainViewModel.swift
> +            todoList.append(data)
정말 return을 사용하는거보다 else문이 조금 더 가독성이 좋은 것 같네요. 좋은 조언 감사합니다!
[1b3aa70](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/1b3aa7094cb4f279242c07747b1c6b54d8e965a9)

2023-01-24 16:44 UTC, lws2269 commented on ProjectManager/ProjectManager/ViewModel/MainViewModel.swift
> +            }
조언 감사합니다! 들여쓰기도 줄어들고 보기 좋아진 것 같습니다.

[1b3aa70](https://github.com/yagom-academy/ios-project-manager/pull/240/commits/1b3aa7094cb4f279242c07747b1c6b54d8e965a9)

2023-01-24 17:42 UTC, lws2269 commented on ProjectManager/ProjectManager/View/CircleLabel.swift
> +    }
draw 시점에 rect의  height 크기의 반의 값으로 layer를 둥글게하여 원처럼 보이게하기 위해 해당 시점에 선언하여 사용하였습니다.

기존에는 CircleLabel이아닌 UILabel을 클로저를 통해 사용하려했지만 height의 크기를 가져올 수 없어서 해당 방법을 사용하였습니다.

2023-01-24 17:43 UTC, lws2269 commented on ProjectManager/ProjectManager/View/CircleLabel.swift
> +    }
label에 패딩을 주기 위한 메서드로 사용하였습니다. 공식문서를 참고했을때 지정된 사각형에 레이블의 텍스트를 그린다고 합니다.
사용할 때는 정확한 역할은 알지 못하고 사용했습니다...🙇🏽‍♂️

2023-01-25 11:58 UTC, 1Consumption approved these changes
고생하셨습니다. 코멘트에 적은 내용은 다음 스텝에 반영해주세요.

2023-01-25 11:58 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListView.swift
> +        categoryLabel.text = viewModel.category.description
`description`을 직접 사용하지말고 아래와 같이 사용할 수 있습니다.
```suggestion
        categoryLabel.text = "\(viewModel.category)"
```

2023-01-25 11:58 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListCell.swift
> +            self?.dateLabel.textColor = work.endDate < Date() ? .red : .black
UIColor 자체를 UI로 볼것이냐 아니면 조금 더 데이터에 가까운 쪽으로 볼 것이냐의 차이라고 생각됩니다. 저는 이정도는 데이터라고 생각해요

2023-01-25 11:58 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListCell.swift
> +        if gestureRecognizer.state == .ended {
위에 적은 UIKit 관련 코멘트와 같습니다.

2023-01-25 11:58 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ListView.swift
> +    weak var workFormDelegate: WorkFormDelegate?
Delegate가 너무 많네요ㅠ view 하나에는 delegate 하나만 있어야한다고 생각합니다. listView의 하위뷰에서 온 이벤트를 전달하기 위함이라면 ListViewDelegate라는 것을 만들어서 여기서 모아서 전달하는건 어떨까요?

2023-01-25 11:59 UTC, merged