프로젝트 매니저 [STEP 2] Mangdi
yagom-academy/ios-project-manager pull request #242
Opened 2023-01-18 11:56 UTC by MangDi-L

@leejun6694 
안녕하세요 쿠마! 프로젝트 매니저 STEP2 PR을 드디어 보내게되었습니다.  
아직 firebase나 realm같은 기술스택적용은 시작도안했는데 벌써부터 어렵네요 ㅎㅎ

## 실행화면
|생성|
|:--:|
|![1](https://user-images.githubusercontent.com/49121469/213162906-d77695a3-47d8-40a9-9538-4c1f3b400fd1.gif)|
|**수정**|
|![2](https://user-images.githubusercontent.com/49121469/213162896-a3814553-4486-4ede-aab0-55fe2fdfe96c.gif)|
|**popover 이동**|
|![3](https://user-images.githubusercontent.com/49121469/213162869-a2c5a4d4-d46e-4d17-9291-17b717ba9954.gif)|
|**swipe 삭제**|
|![4](https://user-images.githubusercontent.com/49121469/213163533-be1fe0b1-e681-455d-8d6c-14a467d273cd.gif)|

## 🤔 고민했던 점
- **collectionView 3개 사용으로 인한 중복코드 발생**
todo, doing, done 세가지영역을 관리하는 collectionView 3개를 만듬으로 인해 dataSource나 layout, swipeAction 등등 거의 비슷한 코드들을 3번씩 작성한것으로 MainViewController의 코드줄 수가 많이 발생하게되었습니다.  
그래서 줄수를 조금이라도 줄이려고 비슷한 코드를 찾아서 어떻게 압축시킬수 있을지 고민했습니다.

## 🙏 조언을 얻고 싶은 부분
- **파일분리에 대해서..**
MainViewController파일의 경우 코드가 650줄이 나오는데 이를 파일 분리를 통해 좀 줄여야겠다는 생각이 들었습니다.  
만약 분리를 한다면 화면에 보여주는 view랑 관련된 11번줄부터 181번줄까지를 다른 파일로 옮기는 생각도 해봤는데 MainViewController에서 UIView들을 옮긴 파일을 어떤식으로 사용해야하는지 감이 잘 잡히지가 않습니다..  
UIView랑 관련된 애들만 따로 파일을 만들어서 관리하고싶은데 이것에 대해 조언을 주시면 감사하겠습니다.

- **DoneContentView를 생성하지 않고도 구현하는법**
요구사항 중 `TODO와 DOING의 기한에 지난 날짜가 있으면 빨간색으로 표시합니다.` 라고 명시되어있었습니다.
기존에는 todo, doing, done 모두 TodoContentView를 적용받고 있어서 TodoContentView의 dateLabel을 빨간색으로 표시하면 todo, doing, done 모두가 적용될수밖에 없었습니다.
그래서 지금은 done 전용 DoneContentView를 하나 생성해서  
todo, doing은 TodoContentView를,
done만 DoneContentView를 적용해서 요구사항대로 구현 할 수 있었습니다.  
그런데 DoneContentView를 생성하지 않고도 할 수 있는 방법이 없을까 많이 고민해보고 시도해봤는데 잘 되지 않았습니다.  
DoneContentView를 생성하지 않고도 구현 할 수 있는 방법에 대해 조언주시면 감사합니다!

2023-01-19 12:35 UTC, leejun6694 requested changes
MangDi 안녕하세요 : )
step 2 구현하느라 고생 많으셨습니다~!
고민하셨던 부분인 view 의 코드가 중복되는 것은 개선되면 좋을 것 같습니다!
시간 괜찮으시면 내일 디스코드로 말씀 나눠보시죠 ㅎㅎ
-
간단한 코멘트들도 남겼는데, 확인 부탁드립니다.

2023-01-19 12:35 UTC, leejun6694 commented on ProjectManager/ProjectManager/Controller/CellPopoverViewController.swift
> +
property 와 method 들이 구분 없이 코드가 나열되어 있습니다.
간단한 주석을 추가해보는건 어떨까요? (MARK)

2023-01-19 12:35 UTC, leejun6694 commented on ProjectManager/ProjectManager/Controller/CellPopoverViewController.swift
> +    private let firstButton: UIButton = {
button 의 이름이 다소 불친절하다고 느껴집니다.
괜찮은 이름을 지어줄까요?

2023-01-19 12:35 UTC, leejun6694 commented on ProjectManager/ProjectManager/Controller/CellPopoverViewController.swift
> +        configureSubViews()
빠진 코드가 있습니다.
필요 없는 코드일텐데, 왜 우리는 작성을 해주고 있을까요?

2023-01-19 12:35 UTC, leejun6694 commented on ProjectManager/ProjectManager/Controller/CellPopoverViewController.swift
> +            firstButton.setTitle("Move to DOING", for: .normal)
자주 쓰는 string 값은 따로 정의해두면 좋을 것 같아요 : )

2023-01-19 12:35 UTC, leejun6694 commented on ProjectManager/ProjectManager/Controller/DetailViewController.swift
> +    private lazy var navigationBar: UINavigationBar = {
lazy property 와 아닌 property 는 차이점이 있을까요?

2023-01-19 12:35 UTC, leejun6694 commented on ProjectManager/ProjectManager/Controller/DetailViewController.swift
> +        }
버튼은 각각 만들어두고 넣어주기만 하면 어떨까요?
버튼을 2개만 만들어도 될 것 같네요~!

2023-01-19 12:35 UTC, leejun6694 commented on ProjectManager/ProjectManager/Controller/DetailViewController.swift
> +        NSLayoutConstraint.activate([
layout 코드는 길어지게 되면, 저는 파일의 하단에 작성하는 편입니다.
참고만 부탁드려요 ㅎㅎ

2023-01-19 12:35 UTC, leejun6694 commented on ProjectManager/ProjectManager/Controller/DetailViewController.swift
> +        let formatter = DateFormatter()
https://soooprmx.com/swift-tip-nsdateformatter는-singleton으로-사용하라/
이런 글도 참고해보면 좋겠네요 : )

2023-01-19 12:35 UTC, leejun6694 commented on ProjectManager/ProjectManager/Model/CellPopoverViewDelegate.swift
> +protocol CellPopoverViewDelegate: AnyObject {
`AnyObject` 는 어떤 이유로 작성해주셨나요~?

2023-01-19 12:35 UTC, leejun6694 commented on ProjectManager/ProjectManager/View/DoneContentView.swift
> +            dateLabel.text = "nil"
nil 이라는 텍스트가 들어가나요..!?

2023-01-22 06:41 UTC, MangDi-L commented on ProjectManager/ProjectManager/Controller/CellPopoverViewController.swift
> +
프로퍼티와 메서드를 구붐하는 MARK 주석을 추가했습니다!
[d7ba7e5](https://github.com/yagom-academy/ios-project-manager/pull/242/commits/d7ba7e5c1489655ebfc26ee68d22099e5e8ab450)

2023-01-22 06:44 UTC, MangDi-L commented on ProjectManager/ProjectManager/Controller/CellPopoverViewController.swift
> +    private let firstButton: UIButton = {
어디 콜렉션뷰에서 호출하느냐에 따라 button의 text가 바뀌게되어서 그저 first와 second라고 지었는데 다소 모호한 부분이 있었던것같습니다.
그래서 변수명을 poppverFirstButton과 popoverSecondButton 으로 수정했습니다!
[c5f2fe3](https://github.com/yagom-academy/ios-project-manager/pull/242/commits/c5f2fe347974e8ddd613308e31a54dd31a348171)

2023-01-23 11:39 UTC, MangDi-L commented on ProjectManager/ProjectManager/Controller/CellPopoverViewController.swift
> +        configureSubViews()
super.viewDidLayoutSubviews()를 작성하는걸 깜빡잊고있었네요 
그런데 이걸 왜 꼭 써주어야하는지 정확한 이유를 알기위해서 한번 알아봤습니다!
[Stack Overflow - Why/when do we have to call super.ViewDidLoad?](https://stackoverflow.com/questions/40151723/why-when-do-we-have-to-call-super-viewdidload)
위 링크를 통해 알아본 바, 
슈퍼클래스가 필요한 설정 (속성 초기화, 배치 등)을 완료한 후에 모든 하위클래스 설정을 수행하는 것이 IOS가 일반적으로 하는일인데.
변경을 시작하기 전에 super.method같은 상위 클래스에 모든 설정을 처리할 기회를 주지 않으면 이상한 버그와 동작이 발생할 수 있다고 합니다.
그래서 항상 super.method를 호출하는걸 습관화하는게 좋다고 합니다!

2023-01-23 11:52 UTC, MangDi-L commented on ProjectManager/ProjectManager/Controller/CellPopoverViewController.swift
> +            firstButton.setTitle("Move to DOING", for: .normal)
자주 사용하는 값들을 모아둔 Literal 파일 생성했습니다!
[105cc17](https://github.com/yagom-academy/ios-project-manager/pull/242/commits/105cc179282b90d27f115c99c0f7454f3169286d)

2023-01-23 13:09 UTC, MangDi-L commented on ProjectManager/ProjectManager/Controller/DetailViewController.swift
> +    private lazy var navigationBar: UINavigationBar = {
lazy property는 처음 사용되기 전까지 메모리에 올라가지않으며
초기화되기 전에 값이 없을수도있기때문에 무조건 var로 선언해야합니다.
일반 propert에 비해 메모리를 절약할수있다는 이점이 있습니다.

2023-01-23 14:06 UTC, MangDi-L commented on ProjectManager/ProjectManager/Controller/DetailViewController.swift
> +        }
leftBarButtonItem 와 rightBarButtonItem 만들어서 넣어주도록 코드 수정했습니다!

2023-01-23 15:12 UTC, MangDi-L commented on ProjectManager/ProjectManager/Model/CellPopoverViewDelegate.swift
> +protocol CellPopoverViewDelegate: AnyObject {
원래 class로 작성했었는데 
'Using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead' 
'Replace 'class' with 'AnyObject' 
이러한 경고문에 떠서 AnyObject로 바꾸게 되었습니다

2023-01-23 15:14 UTC, MangDi-L commented on ProjectManager/ProjectManager/View/DoneContentView.swift
> +            dateLabel.text = "nil"
앗..수정했습니다!
[879ad60](https://github.com/yagom-academy/ios-project-manager/pull/242/commits/879ad6013f45a7107692bd1fb711b8e4323240f0)

2023-01-25 04:22 UTC, leejun6694 commented on ProjectManager/ProjectManager/Controller/DetailViewController.swift
> +    private lazy var navigationBar: UINavigationBar = {
일부 property 만 lazy 로 만들어져있어서 여쭤봤습니다 : )

2023-01-25 04:24 UTC, leejun6694 reviewed
@MangDi-L 
step 2 구현도 고생 많으셨습니다. 같이 논의한 부분으로 코드가 더 마음에 드셨으면 좋겠네요 ㅎㅎ
step 3 도 잘부탁드립니다~!

2023-01-25 04:24 UTC, leejun6694 commented on ProjectManager/ProjectManager/Controller/CellPopoverViewController.swift
> +    private let poppverFirstButton: UIButton = {
first, second 는 뺄 수 없는 네이밍일까요...!?

2023-01-25 04:25 UTC, leejun6694 approved these changes

2023-01-25 04:25 UTC, merged

2023-01-25 06:34 UTC, MangDi-L commented on ProjectManager/ProjectManager/Controller/CellPopoverViewController.swift
> +    private let poppverFirstButton: UIButton = {
두 버튼을 구분짓기위해 first, second를 사용한건데 별 다른 네이밍이 잘 떠오르지 않네요 ㅠㅠ.. 혹시 추천하시는 네이밍이 있으신가요?