프로젝트 매니저 [Step2] Kyo
yagom-academy/ios-project-manager pull request #244
Opened 2023-01-19 03:36 UTC by KyoPak

안녕하세요! 올라프(@1Consumption)
MVVM의 구조를 여러번 바꾸고 고민을 많이 하다보니 PR이 늦어졌습니다..
MVVM이 익숙하지 않아 이것저것 바꿔보다보니 커밋도 많아지고 뷰컨트롤에도 많은 로직이 있어보입니다...

많은 조언과 피드백 잘 부탁드립니다!!

## 진행 단계 : Step 2

## 적용하며 배운 점

✅ MVVM 패턴
✅ ViewModel에 대한 UnitTest 적용
✅ UILongPressGestureRecognizer를 이용한 Gesture 추가
✅ Popover Present 사용
✅ Formsheet Present 사용

## 흐름

가장 처음에 생각을 했을 때, `DataManager`라는 싱글톤 클래스에서 데이터를 관리하고,
`MainViewModel`의 역할은 `DataManager`의 데이터를 각 리스트에 보여주고, `DataManager`의 변경사항에 따라 `MainViewModel`이 가지고 있는 데이터가 갱신되게끔 구현하였습니다.

하지만 `DataManager`의 역할을 `MainViewModel`이 가지고 있어도 될 것이라고 생각되었고, 굳이 싱글톤을 사용하지 않아도 된다 느껴 아래처럼 설계를 변경하였습니다.

- `MainViewModel`
    - 모든 Process(todo, doing, done)에 대한 데이터를 가지고 있게끔 하였습니다.
    - 수정, 삭제, 이동은 한번에 한 개씩 이루어지므로 `updateDataProcess`와 `updateDataIndex`로 변경될, 변경 중인 Data에 대한 Process와 index을 관리하는 역할을 주었습니다.
    - 데이터의 변경이 필요한 경우, Process, index를 업데이트 해준 후, `MainViewModel` 내부에서 Data를 찾아 return, delete, process change 하도록 구현하였습니다.

- `DetailViewModel`
    - `MainViewModel`에게 전달받은 Data를 UI로 보여주고, Edit할 수 있는지에 대한 로직이 담겨있는 ViewModel입니다.
    - `DetailViewModel`이 생성될때 주입되는 Data가 nil이라면 새로운 데이터를 추가,  nil이 아니라면 Data 변경으로 로직이 작동되게끔 구현하였습니다.

- `CellViewModel`
    - `CellViewModel`은 Data를 UI에 보여주고, DeadLine을 넘겼을 경우 날짜 Label의 색상을 변경하는 로직을 담았습니다.

- Data를 `DetailView`에서 입력 후, `MainViewModel`로 넘기는 과정
    - `DetailViewModel`에서 Data를 입력후 Done버튼을 누르면 `DetailViewModel`의`createData()`를 통해 Todo데이터가 만들어지고, 이 만들어진 데이터를 Delegate메서드`shareData()`를 통해 `MainViewModel`에게 넘겨주었습니다.

## 고민한 부분,조언을 얻고 싶은 부분 

### 1️⃣ 3개의 StackView, DataSource

`TodoStackView`, `DoingStackView`, `DoneStackView`에서 각각 Process에 대한 데이터를 보여주다 보니깐 DataSource도 많아지게되고, View도 많아지면서 `MainViewController`내부에서 어떤 View를 사용할 것인지 결정해줘야하는 코드가 많이 들어가 게 되었습니다. (TodoViewModel, DoingViewModel, DoneViewModel 3개를 만들어야하나 생각도 했습니다..)

때문에 DataSource나 View를 배열로 바꿔보기도 하였지만, 크게 코드가 줄지는 않았던것같습니다. 

해당 부분에 대해 올라프의 생각이 궁금합니다.,!

### 2️⃣ ViewModel이 다른 ViewModel을 알고 있어도 될까?

구조를 고민하면서 `DetailViewModel`에서 추가(변경)할 데이터를 만들고,
이 데이터를 지금의 방식인 delegate로 넘겨주는 것이 아닌 직접적으로 MainViewModel을 가지고 있게 한 후, MainViewModel에 넣어주는 방법도 생각을 했었습니다. 

**뷰모델이 다른 뷰모델을 프로퍼티를 가지고 있어도 되는지 궁금합니다**. 

## 3️⃣ MVVM의 테스트 용이성

실제로 MVVM패턴으로 ViewModel에게 로직을 분담시킨 후, 로직의 테스트가 쉬워진다는게 체감되었습니다. 하지만 bind해주는 메서드는 따로 테스트를 진행하지 않았는데,
올라프라면 명확한 테스트를 위해 bind하는 메서드도 테스트를 진행하시는지 궁금합니다.!

잘부탁드립니다!

2023-01-19 23:14 UTC, 1Consumption requested changes
고생하셨습니다 @KyoPak 

MVVM과 유닛테스트를 코드에 잘 녹여주셨네요.
그런데 `GoogleService-Info.plist` 파일이 없어서 실제로 빌드를 해보지는 못했습니다.
다음부터는 피알을 보내기 전에 본인의 로컬 레포를 삭제한 후 클론을 받아 빌드 에러가 발생하지는 않는지 확인 해주세요.

아래는 고민한 점에 대한 제 코멘트입니다.

------------------------

### 1️⃣ 3개의 StackView, DataSource

`TodoStackView`, `DoingStackView`, `DoneStackView`에서 각각 Process에 대한 데이터를 보여주다 보니깐 DataSource도 많아지게되고, View도 많아지면서 `MainViewController`내부에서 어떤 View를 사용할 것인지 결정해줘야하는 코드가 많이 들어가 게 되었습니다. (TodoViewModel, DoingViewModel, DoneViewModel 3개를 만들어야하나 생각도 했습니다..)

때문에 DataSource나 View를 배열로 바꿔보기도 하였지만, 크게 코드가 줄지는 않았던것같습니다. 

해당 부분에 대해 올라프의 생각이 궁금합니다.,!

> 알면 안되는 곳에서 알고 있으니 코드가 길어졌다고 생각합니다. 왜 `MainViewController`에서 모두 들고 있나요? 이부분 관련해서 코드에 코멘트를  남겼습니다. 코멘트를 참고해주세요.

### 2️⃣ ViewModel이 다른 ViewModel을 알고 있어도 될까?

구조를 고민하면서 `DetailViewModel`에서 추가(변경)할 데이터를 만들고,
이 데이터를 지금의 방식인 delegate로 넘겨주는 것이 아닌 직접적으로 MainViewModel을 가지고 있게 한 후, MainViewModel에 넣어주는 방법도 생각을 했었습니다. 

**뷰모델이 다른 뷰모델을 프로퍼티를 가지고 있어도 되는지 궁금합니다**. 

> 저는 구체적으로 알면 안된다고 생각해요. delegate로 이벤트를 전달하거나, view와 view 사이에서 이벤트를 전달하는건 어떨까요?

### 3️⃣ MVVM의 테스트 용이성

실제로 MVVM패턴으로 ViewModel에게 로직을 분담시킨 후, 로직의 테스트가 쉬워진다는게 체감되었습니다. 하지만 bind해주는 메서드는 따로 테스트를 진행하지 않았는데,
올라프라면 명확한 테스트를 위해 bind하는 메서드도 테스트를 진행하시는지 궁금합니다.!

> bind 해주는 메소드가 뭘 말하는지 잘 모르겠습니다.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/AppDelegate.swift
>  class AppDelegate: UIResponder, UIApplicationDelegate {
final을 붙여도 좋겠습니다.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/Model/Process.swift
> +    }
[CustomStringConvertible](https://developer.apple.com/documentation/swift/customstringconvertible) 이라는 프로토콜을 적용해보세요.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/Model/Todo.swift
> +struct Todo: Hashable {
흠... Todo라는 이름이 어색하네요. Done에도 Todo가 있을 수 있는거 아닌가요?

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/Protocol/IdentifierUsable.swift
> +protocol IdentifierUsable where Self: UIView { }
`Identifiable`이라는 이름은 어떨까요?

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +    private lazy var doneDataSource = configureDataSource(process: .done)
이 정보를 MainView에서 알아야할까요? `ProcessStackView`가 가져야할 정보 같아요.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +        }
이부분이 한번 더 추상화 되어야한다고 생각합니다. 클로저 내부에서는 `ProcessStackView`에 이벤트만 던져주는거죠.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +    }
분기를 치는건 로직이라고 생각합니다. view의 역할이 아니라 viewModel의 역할 같아요.
또한 view로 분기를 치지말고 `Process` enum으로 분기를 치는게 더 깔끔해보입니다.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +    }
`MainView`의 역할은 어디까지인가요? 제가 생각하기에는 하위 뷰들을 layout하고, 사용자 이벤트를 종합해 뷰모델에게 넘기는거라고 생각합니다. 이렇게 구체적인 작업은 하위 view가 알게 하는건 어떨까요?

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +    }
여기도 마찬가지라고 생각합니다.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +            self.viewModel.deleteData()
음... 여기서 너무 구체적으로 viewModel의 메소드를 호출하고있네요. 저라면 하나의 메소드만을 사용해 viewModel에게 이벤트를 보내고, viewModel 내부에서 메소드 순서나, 로직을 처리하겠어요.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +    }
여기도 view의 역할이 아닌 코드가 있다고 생각해요.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/ProcessStackView.swift
> +final class ProcessStackView: UIStackView {
외부에서 StackView라는 이름을 알아야할까요?

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/ProcessStackView.swift
> +        delegate?.relayGesture(sender, indexPath: indexPath, cell: cell)
popup메뉴를 띄우기 위해 꼭 cell이 필요한건 아니고 view가 필요한거니 UIView를 보내면 좋겠습니다.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/ProcessTableViewCell.swift
> +    }
외부에서 직접 프로퍼티에 접근하지말고 메소드로 viewModel을 넘겨주면 좋겠습니다.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/ProcessTableViewCell.swift
> +    let dateLabel = UILabel(fontStyle: .body)
외부에서 몰라도 되는 프로퍼티 같습니다.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/ProcessTableViewCell.swift
> +    }
이 메소드는 언제 불리나요?

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/ProcessTableViewCell.swift
> +    }
override method인데 super를 호출하지 않은 이유가 있을까요?
그리고 이 메소드는 언제 호출되나요?

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/ProcessTableViewCell.swift
> +            guard let data = data else { return }
data를 옵셔널로 넘기지말고, 옵셔널 바인딩된 결과를 closure로 넘기면 좋겠습니다. 옵셔널 바인딩도 결국은 분기거든요.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/ProcessTableViewCell.swift
> +        guard let viewModel = viewModel else { return }
꼭 viewModel을 옵셔널 바인딩 해야하나요?

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/SubScenes/DetailViewController.swift
> +        dismiss(animated: true)
엄밀하게 따지면 이부분도 바로 dismiss를 하는게 아니라 viewModel에 이벤트를 보내야한다고 생각해요.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/CellViewModel.swift
> +    }
bind하는 메소드에서 왜 handler를 실행하나요?

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/CellViewModel.swift
> +        return false
if문의 결과로 Bool을 반환하는 경우는 if문 컨디션을 그대로 리턴해도 좋겠습니다.
```suggestion
        return data.isOverDeadLine
```

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/DetailViewModel.swift
> +    private var description: String = Constant.defaultText {
swift에서 제공하는 프로퍼티와 이름이 겹치니 다른 이름으로 변경하는건 어떨까요?

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/DetailViewModel.swift
> +        }
```suggestion
        return mode == .new
```

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/DetailViewModel.swift
> +    }
위에서도 말했지만, 여기서 왜 handler를 한번씩 실행하는지 잘 모르겠어요. 메소드 이름만 보고 동작을 유추할수가 없네요.

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/DetailViewModel.swift
> +    }
이부분을 메소드로 감싼이유가 있을까요?

2023-01-19 23:14 UTC, 1Consumption commented on ProjectManager/ProjectManagerTests/MainViewModelTest.swift
> +    }
given when then 명시 좋습니다 👍

2023-01-20 02:08 UTC, KyoPak commented on ProjectManager/ProjectManager/AppDelegate.swift
>  class AppDelegate: UIResponder, UIApplicationDelegate {
넵 수정했습니다! SceneDelegate도 오버라이드를 사용하지 않아 동일한 키워드를 붙혔습니다.

2023-01-20 02:11 UTC, KyoPak commented on ProjectManager/ProjectManager/Model/Todo.swift
> +struct Todo: Hashable {
올라프 말을 듣고보니 그러네요..! 조금 더 포괄적인 Plan으로 Renaming하였습니다.

2023-01-20 02:30 UTC, KyoPak commented on ProjectManager/ProjectManager/Protocol/IdentifierUsable.swift
> +protocol IdentifierUsable where Self: UIView { }
해당 부분도 Usable을 줄 일수 있겠네요! Identifierable로 Renaming하였습니다!

2023-01-20 05:45 UTC, KyoPak commented on ProjectManager/ProjectManager/Model/Process.swift
> +    }
오..사용해보니깐 훨씬 직관적이네요! 반영해보았습니다! case별로 나눌수있어서 활용성이 좋은것같네요
추가로 `String.init(describing: self).uppercased()` 요걸 써도 깔끔한 것 같다는 생각이 들었습니다!

2023-01-20 16:07 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +    private lazy var doneDataSource = configureDataSource(process: .done)
수정하였습니다! DataSource, Snapshot 연관 로직은 ProcessView에서 구현해주었습니다.

[99a954d](https://github.com/yagom-academy/ios-project-manager/pull/244/commits/99a954d3b447cd28b4310d3f3f009cc220d95e81)

2023-01-20 16:28 UTC, KyoPak commented on ProjectManager/ProjectManager/ViewModel/CellViewModel.swift
> +        return false
수정했습니다! :)

2023-01-20 16:31 UTC, KyoPak commented on ProjectManager/ProjectManager/ViewModel/CellViewModel.swift
> +    }
아까 말씀을 못드렸는데.. 확인을 해보니깐 가장 처음에 실행을 하였을 경우, 데이터의 카운트를 0으로 표시해줘야하기 때문에 
handler(data)로 클로저를 가장 초기에 한번 실행해주었었습니다!

2023-01-20 16:34 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/ProcessTableViewCell.swift
> +    }
해당 메서드는 Cell을 재사용할 때 마다 호출되는 메서드로 알고 있습니다. 
Data의 갯수가 많아져 Cell이 많아질 경우에 스크롤을 하면서 Cell이 재사용이되는데 이 경우마다 호출되는 메서드로 알고있습니다.

super는 바로 수정하였습니다 ! 

[7f3d50b](https://github.com/yagom-academy/ios-project-manager/pull/244/commits/7f3d50bbd13ba77e3973cf002dd536fa6c48fdb1)

2023-01-21 15:05 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +        }
해당 부분도 `ProcessView`로 이벤트를 던지고 `ProcessView`에서 다시 `ProcessViewModel`을 호출하여 로직을 처리하게 끔 변경하였습니다

2023-01-21 15:06 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +    }
해당 부분은 ProcessView에 역할 분리를 한 후에 ProcessViewModel이 Proecss를 가지게 되어서 불필요하다 판단하여 삭제하였습니다.

2023-01-21 15:09 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +            self.viewModel.deleteData()
ProcessView에서 MainViewController에게 Delegate로 이벤트의 발생을 알리고, MainViewModel에서 로직을 처리하게 해주었습니다. 
```swift
extension MainViewController: DataManageable, EventManageable {
    func shareUpdateEvent(process: Process, index: Int?) {
        viewModel.prepareForEvent(process: process, index: index)
        
        presentDetailView()
    }
    
    func shareDeleteEvent(process: Process, index: Int) {
        viewModel.deleteData(process: process, index: index)
    }
    
    func shareData(data: Plan) {
        viewModel.updateData(data: data)
    }
}
```

2023-01-21 15:11 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/ProcessStackView.swift
> +final class ProcessStackView: UIStackView {
굳이 StackView인 것 까지는 알필요가 없는 것 같네요..! 해당부분도 ProcessView로 변경하였습니다

2023-01-21 15:22 UTC, KyoPak commented on ProjectManager/ProjectManager/ViewModel/DetailViewModel.swift
> +    private var description: String = Constant.defaultText {
description이 포함된 메서드, 프로퍼티 모두 content로 대체하였습니다.

2023-01-21 15:54 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/ProcessStackView.swift
> +        delegate?.relayGesture(sender, indexPath: indexPath, cell: cell)
cell이라는 구체적인 view 대신 올라프 말대로 UIView를 보내도록 수정하였습니다.

2023-01-21 16:24 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/ProcessTableViewCell.swift
> +    let dateLabel = UILabel(fontStyle: .body)
private 키워드 추가하였습니다!

2023-01-22 04:02 UTC, KyoPak commented on ProjectManager/ProjectManager/ViewModel/DetailViewModel.swift
> +    }
`isEdiatable`을 private(set) 으로 변경하여 해당메서드 삭제하였습니다

2023-01-22 04:05 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/ProcessTableViewCell.swift
> +    }
Cell의 ViewModel을 메서드로 주입받을 때 setupBind()메서드가 호출되게끔 변경했습니다.

2023-01-22 05:46 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/ProcessTableViewCell.swift
> +            guard let data = data else { return }
CellViewModel의 bindData에서 넘겨주는 데이터를 옵셔널 타입이 아니게끔 변경하였습니다!
추가로 bindDate를 bindData로 renamaing하였습니다.

2023-01-22 05:47 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/ProcessTableViewCell.swift
> +        guard let viewModel = viewModel else { return }
viewModel을 바인딩하지 않고 viewModel의 메서드를 호출하여 guard문을 활용하였습니다.
```swift
private func checkDeadLine() {
        guard viewModel?.checkOverDeadLine() != true else {
            dateLabel.textColor = .red
            return
        }
    }
```

2023-01-22 12:54 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +    }
MainView의 역할을 전체적인 데이터 관리, 이벤트를 받고 그에 따른 데이터 변경, 추가, 삭제 로 정하였고 이벤트 처리는 다른 View가 담당하게 끔 변경하였습니다.

2023-01-22 13:34 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/ProcessTableViewCell.swift
> +    }
`layoutSubView`는 View의 크기를 조절하고, SubView를 추가할때 자동으로 호출됩니다. 때문에 cell을 추가할때마다 View의 크기를 계산하기 위해 layoutSubview가 호출되게 됩니다.

- 왜 다른 메서드에서 호출하면 안될까요? 에 대한 답변입니다.
위는 Constraint에서 사이즈를 조절하는게 아닌 직접 View를 재계산해주는 코드이기 때문에 해당 메서드에서 bounds를 변경하는 구현을 해줘야했습니다. 
bound 뿐만 아니라 frame을 변경하고자할때도 해당 메서드에서 구현을 해줘야합니다..!

2023-01-23 12:33 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +    }
```swift
 Process.allCases.filter {
            $0 != selectProcess
        }.forEach { process in
```
위의 코드를 
```swift
 viewModel.configureButtonProcess().forEach { process in
```
으로 수정하였으며 filter 로직은 viewModel에서 수행되게끔 변경하였습니다.

2023-01-24 14:34 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +    }
추가적으로 MainViewModel 내부에 `popOverProcessList`를 추가하였으며,
Gesture에 대한 Delegate 메서드인 `shareLongPress()`가 호출되어 `mainViewModel`의 프로퍼티가 바뀔 때 자동으로 PopOver가 구성되는 `showPopOver()`메서드가 호출되게끔 변경하였습니다.

[45a101b](https://github.com/yagom-academy/ios-project-manager/pull/244/commits/45a101beac3a7309f0227e43bd20b27e129e19c9)

2023-01-24 15:37 UTC, KyoPak commented on ProjectManager/ProjectManager/View/SubScenes/DetailViewController.swift
> +        dismiss(animated: true)
해당 부분에서 viewModel의 finishEdit() 메서드를 실행시켜 viewModel에서 dismiss되도록 변경하였습니다.

2023-01-25 04:52 UTC, KyoPak commented on ProjectManager/ProjectManager/ViewModel/CellViewModel.swift
> +    }
초기에 bind 한 handler 부분을 초기에 한번 실행시켜려고 하였습니다.
하지만 현재는 viewModel과 VC와 바인드를 한 후에 초기 값을 주거나, 값을 줘서 실행될수 있도록 변경하였습니다.

[42f38de](https://github.com/yagom-academy/ios-project-manager/pull/244/commits/42f38de816a69a72c3c588df5b2abbff3d96df43)

2023-01-25 11:35 UTC, 1Consumption approved these changes
고생하셨습니다. 코멘트는 참고만 해주세요.

2023-01-25 11:35 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/MainViewModel.swift
> +    }
굳이 이 메소드를 호출해야하는 이유가 있나요?

2023-01-25 11:35 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +    func shareUpdateEvent(process: Process, index: Int?)
현재 코드에서는 index가 옵셔널일 이유가 없어보입니다. 불필요한 옵셔널 바인딩 코드만 더 생겼네요.

2023-01-25 11:35 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/DetailViewModel.swift
> +        }
data가 nil이면 아래 코드를 실행하지 않는것이 의도된 코드인가요? 아니면 isEditable만 바뀌는게 의도된 코드인가요?

2023-01-25 11:36 UTC, merged

2023-01-25 13:50 UTC, KyoPak commented on ProjectManager/ProjectManager/View/MainScenes/MainViewController.swift
> +    func shareUpdateEvent(process: Process, index: Int?)
만약 index가 nil이라면 add, 특정 index가 존재한다면 존재하는 데이터의 편집기능이 이루어지도록 구현하였습니다.

2023-01-25 13:52 UTC, KyoPak commented on ProjectManager/ProjectManager/ViewModel/DetailViewModel.swift
> +        }
의도된 코드입니다. data가 nil이라면 새로 신규 Plan데이터를 추가하는 것이기 때문에 아래 코드가 실행되지 않고, isEditable(편집가능)이 true로 변경 후, return 되도록 하였습니다.

2023-01-25 14:26 UTC, KyoPak commented on ProjectManager/ProjectManager/ViewModel/MainViewModel.swift
> +    }
올라프 말대로 굳이 호출 할 필요가 없다고 생각이 들어서.. 해당 메서드를 삭제하고 직접 countLabel에 0을 셋팅해주었습니다.
해당 부분 Step3에서 반영하겠습니다!