프로젝트 매니저 [STEP 2] GUNDY
yagom-academy/ios-project-manager pull request #246
Opened 2023-01-19 10:32 UTC by Gundy93

@July911
안녕하세요 줄라이! 계획단계를 집중적으로 고민해서 프로젝트를 진행한 것은 처음이다보니 난항도 겪고, 아키텍처에 대한 이해도 맞게 된 것인지 잘 모르겠습니다. 하지만 최대한 레이어 간의 의존성의 방향이 안쪽으로 흐르게 하고자 노력하였고, 의존성 방향의 위반될 경우 DIP를 통해 해결하고자 하였습니다! 인사말에 뭘 이리 주절주절 적는지 모르겠습니다!

이번 스텝도 잘부탁드립니다! 늘 이거저거 알려주셔서 감사합니다 😃

## 고민했던 점

### 앱의 목표와 역할

#### 앱의 목표

**할 일(계획)** 을 **관리(생성, 상태변경)** 한다.

#### 각 계층의 역할

<details>
<summary> 
역할 펼쳐보기
</summary>

#### Model

- 계획
    - 제목
    - 설명
    - 기한
    - 상태
- 상태
    - to do
    - doing
    - done

#### ViewModel: 값이 변하면 뷰 또한 변한다.

- 전체 화면에 대응하는 뷰모델
    - 상태별 계획의 배열
    - 계획의 생성
    - 계획의 수정
    - 계획의 상태 변경
        - to do -> doing, done
        - doing -> to do, done
        - done -> to do, doing
    - 계획 삭제
- 상세 화면 및 셀에 대응하는 뷰모델
    - 계획
    - 기한 포맷팅
    - 기한 유효성
    - 수정 가능 여부
- 상수
    - 네비게이션 타이틀
    - 헤더 타이틀
    - 플레이스 홀더
    - 바버튼 타이틀
    - 팝오버 버튼 타이틀

#### View: 입력을 뷰모델에 전달한다.

- 전체 화면
    - 네비게이션 바
        - `+` 버튼을 통해 새로운 계획 생성 화면을 띄운다.
            - `cancel` 버튼을 누르면 추가하지 않고 취소한다.
            - `done` 버튼을 누르면 뷰모델에 새로운 계획 생성을 요청한다.
    - to do, doing, done의 세 리스트
        - 각 리스트는 계획의 수를 레이블로 표시
            - 뷰모델에 count 요청
        - 계획의 수만큼의 셀을 갖는다.
        - 셀을 누르면 상세 화면을 모달로 띄운다.
        - 셀을 꾹 누르면 팝오버를 띄운다.
            - 팝오버의 버튼을 통해 계획의 위치를 이동시킨다.
                - 뷰모델에 상태변화를 요청한다.
        - 스와이프 기능을 갖는다.
            - 왼쪽으로 밀면 삭제 버튼이 나온다.
            - 삭제 버튼을 누르거나 왼쪽 끝까지 밀면 셀을 삭제한다.
                - 뷰모델에 계획 삭제 요청을 한다.
- 셀
    - 리스트의 셀은 계획의 제목, 설명, 기한의 레이블을 갖는다.
        - 제목은 한 줄이고, 길면 생략한다.
            - text는 뷰모델에 요청한다.
        - 설명은 최대 세 줄이고, 길면 생략하며, 설명 글의 높이에 따라 셀의 높이가 변한다.
            - text는 뷰모델에 요청한다.
        - 기한이 경과했을 경우 빨간 색으로 표시한다.
            - text, 기한 경과 여부는 뷰모델에 요청한다.
- 계획 화면
    - 상세/추가 화면은 제목을 표시하는 텍스트 필드, 기한을 표시하는 데이트 피커, 설명을 표시하는 텍스트 뷰로 구성한다.
        - 상세 화면의 경우 `Edit` 버튼을 누르면 작성이 가능해진다.
            - 작성이 가능한지 여부를 뷰모델에 묻는다.
        - 제목 텍스트 필드는 플레이스 홀더를 갖는다.
            - 이 플레이스 홀더에 들어갈 값은 네임 스페이스에서 가져온다.
        - 텍스트 필드와 텍스트 뷰는 그림자를 보여준다.
    
</details><br>

> **기한 산정 기준**
> 위 앱의 분석 기준에 따라 모델 -> 뷰모델 -> 뷰의 순서로 작업을 할 생각입니다. 뷰 작업 시 뷰모델과의 바인딩 작업이 동반하기 때문에 뷰모델보다 더 긴 시간이 소요된다고 생각했고, 이에 따라 모델, 뷰모델에 소요되는 시간을 2일, 뷰에 소요되는 시간을 3~4일, 수정 및 PR 작성에 1일이 소요된다고 생각하여 기한을 산정하였습니다.

> **클린 아키텍쳐로의 변경**
> 위 사항은 클린 아키텍쳐를 접목시키기로 결정하기 전의 분석이므로 현재 적용된 역할 구분과는 다릅니다. 처음에 어떤 기준으로 기한을 산정했는지 보여드리는 것이 좋을 것 같아서 남겨두었습니다!

### MVVM + Clean Architecture

#### MVVM 역할 구분

![](https://i.imgur.com/swRAYE2.png)

- Model
    - 데이터와 관련된 코드
        - 앱 내부(Domain)로의 모델과 외부(DB, Web)로의 모델로 구분될 것이다.
- View
    - UI와 관련된 코드
        - 직접적으로 컴포넌트를 그리는 뷰와 이를 컨트롤하는 뷰컨트롤러가 포함될 것이다.
- ViewModel
    - 뷰에서 그려질 값을 제공하는 코드
        - MVVM뿐이라면 모델의 포맷을 뷰에 제공하기 알맞게 변경하는 로직또한 이 계층에 포함될 것이다.
- 그렇다면 위 세 경우에 해당하지 않는 부분은?
    - 서비스 로직에 해당하는 코드
        - 데이터베이스에 연결하고, 서버와 통신하는 등의 도메인 로직과 깊은 관련이 없는 코드
        - 이 코드들은 M, V, VM 중 어디에 위치해야 하는가?

![](https://i.imgur.com/v3Q6N6Z.png)

MVVM의 역할 구분에 대해 생각해보니 이런 그림을 그려볼 수 있었습니다. 어쩌면 MVC, MVP, MVVM 모두 사실은 이런 부분들이 생략되어 있었고, 해당 로직이 집중하는 가운데 부분(C, P, VM)이 비대해지는 것은 너무 당연한 것이 아닐까 하는 생각도 들었습니다. 세 개의 역할군만으로는 앱의 모든 코드를 규정할 수 없는 것 같았습니다. 그렇다보니 최소 4개의 레이어로 구분되는 클린 아키텍쳐의 경우가 계층의 관심사 분리가 더욱 명확해진다고 생각했습니다. 그렇기 때문에 클린 아미텍쳐의 적용을 경험해보는 것이 좋은 경험이 되리라고 확신하게 되었습니다.

### 클린 아키텍쳐 레이어 구분

<details>
<summary> 
레이어 펼쳐보기
</summary>

![](https://i.imgur.com/Kq55dgL.png)

### Entity

계획 그 자체와 관련된 코드, 즉 모델이 위치할 것입니다.

- 프로젝트
- 프로젝트의 상태

### Use Cases

계획을 직접적으로 관리하는 코드(도메인 로직)가 위치할 것입니다.

- 계획 관리
    - 계획의 생성
    - 계획의 수정
    - 계획의 상태변경
    - 계획의 삭제

### Interface Adapters

Controllers, Gateways, Presenters 등이 속하는 계층이므로 ViewController, ViewModel, 각종 DBManager의 코드가 위치할 것입니다.

- ViewModel
    - 뷰에 보여주기 적절하게끔 계획을 포맷팅
    - 뷰에 값을 전달
- ViewController
    - 사용자의 상호작용에 따라 제어의 흐름을 Use Cases에 전달
        - Use Cases 내부에서 도메인 로직이 실행된 이후 ViewModel에 전달,
        - 전달 받은 ViewModel은 해당 데이터를 가공해서 View에 전달
- 각종 Mananger
    - 내부의 값을 DB에 맞게 변경하는 등의 로직
    - 그 외에도 다양한 Manager 객체들

### Frameworks and Drivers

DB, 프레임워크, UI 같은 것들이 위치할 것입니다.

- Local DB
    - CoreData
- Remote DB
    - Firebase
- UI
    - View(CustomComponent)
    
</details><br>

#### List 화면 관련 레이어 구분
![](https://i.imgur.com/y2ZVQpC.png)<br>

#### Detail 화면 관련 레이어 구분
![](https://i.imgur.com/rV9FDXr.png)

## 해결이 되지 않은 점

![](https://i.imgur.com/2zUpVcf.png)

뷰 계층 구조에서 보라색 아이콘이 생성되었는데, 보라색은 보통 오토레이아웃이 깨질때 나타나는 것으로 알고 있습니다! 하지만 전구모양의 아이콘은 처음이고, 다른 아이콘처럼 스케일 인스펙터에 늘 나오는 안내문구가 없었습니다...이유를 모르겠습니다. 구글링을 해봐도 전구에 대한 이야기가 쉽게 나오지 않네요!<br>

현재는 텍스트필드와 텍스트뷰만이 갖는 문제이므로 혹시 shadow 때문인것도 같습니다.

## 조언을 얻고 싶은 부분

### HeaderView

UITableView 헤더를 통해 각 리스트의 제목을 작성하려고 했습니다. 하지만 스크롤 시 헤더 또한 움직이는 문제나, plain이 아닐경우엔 위로 스크롤하면 사라지기도 했습니다. 때문에 이 헤더를 따로 분리하여 스택뷰에 넣는 방향으로 구현하였습니다.

### 데이터 바인딩

현재 저는 클로저에 의한 콜백으로 데이터 바인딩을 해결해주었습니다! 하지만 이 밖에도 옵저버 패턴이나 델리게이션, RxSwift나 Combine을 통해서도 바인딩을 해줄 수 있는 것으로 알고 있습니다. 이번 프로젝트와 같은 경우에 어떤 방법을 취하는 것이 적절한지 궁금합니다!

2023-01-20 06:03 UTC, July911 requested changes

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Domain/Model/Project.swift
> +extension Project: Hashable { }
왜 채택을 밑에서 하신걸까요 ? 특별한 이유가 없다면 처음 들어갔을때 보이게 하는게 좋을 것 같아요. 
파일 뎁스를 모른다면 파싱을 위한 타입인지, 프로젝트 전반적으로 쓰일 타입인지 아니면 셀에 쓸 타입인지 모를 것 같습니다.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Util/Constant/Constant.swift
> +    enum Number {
enum으로 하드코딩을 막아주신점은 너무 좋습니다. 
하지만 cancelButton의 경우 한곳에만 쓰이는 것이 아닐수도 있습니다. 
또한 navigation title역시도 프로젝트가 조금만 더 커진다면 모호한 이름이 될 수도 있습니다. 명확하게 하나의 뎁스를 더 두셔서 
읽는쪽에서 잘 읽을 수 있게 빼주시는게 좋을 것 같습니다.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Util/Constant/Constant.swift
> +        static let listTitleMargin: CGFloat = 8
UI의  spacing이나 inset같은 경우도 빼야할지는 생각해보셨으면 좋겠습니다.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Util/Extension/Date+.swift
> +        dateFormatter.locale = Locale(identifier: Locale.preferredLanguages[0])
<img width="1615" alt="스크린샷 2023-01-20 오전 11 34 12" src="https://user-images.githubusercontent.com/90888402/213605756-d73d9bf2-1ff9-41e9-918b-619d0dfd3ec7.png">

참고하시면 좋을 것 같습니다.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Domain/UseCase/Detail/DefaultDetailUseCase.swift
> +            return project.description
기존에 있는 이름과 같은 이름을 써야 할 이유는 없는 것 같습니다.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Domain/UseCase/List/DefaultListUseCase.swift
> +    var listOutput: ListOutput?
굳이 필요한 프로토콜 일까요 ? 
ViewModel이 채택하고 있고, 거기 내부에서 구현해주신걸로 봤는데, 그럼 usecase의 역할과 viewModel의 역할은 무엇일까요 ? 
왜 viewModel이 usecase를 들고있는데 이러한 작업이 필요할까요 ?

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Domain/UseCase/List/DefaultListUseCase.swift
> +        }
데이터를 들고있어야하는 객체일까요 ?

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Domain/UseCase/List/DefaultListUseCase.swift
> +    }
이건 왜 private일까요?

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Domain/UseCase/Detail/Protocol/DetailUseCase.swift
> +    var state: State { get }
state를 Usecase가 가지고 있어야하나요 ?

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Domain/UseCase/Detail/DefaultDetailUseCase.swift
> +    var state: State {
project를 init으로 받으면 state는 필요 없을 것 같습니다. 
이전의 state를 기억하기를 원하시는 구조일까요 ?

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +    private let  titleTextField: DetailTextField = {
인덴트 맞춰주세요 !

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +    var delegate: DetailProjectDelegate?
강한 참조여도 괜찮을까요 ?

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +        return stackView
스택뷰를 잘 활용하시는것은 좋습니다
생각보다 스택뷰로 할 수 있는 일이 많은데 이러한 부분을 공부해보시면 좋을 것 같습니다. 
하나의 팁을 드리자면 스택뷰에 들어간 뷰 마다의 커스텀 스페이싱을 줄 수 있습니다.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +        let textView = DetailTextView()
detail text view를 따로 만드셨는데, 만드신 이유가 무엇일까요 ? 
layer의 값을 단순하게 바꾼다고 하면 굳이 필요한건가 싶은데요. 
이유를 적어주시면 좋을 것 같습니다. 
만약, 그림자를 가지는 text view가 필요하다면 네이밍이 너무 추상화가 안되어있는 것 같습니다.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +            descriptionTextView.isEditable = false
메서드로 분리 가능한 것 같네요

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +            if isEditable == true {
메모리 릭이 안난다는 보장을 할 수 있을까요 ? 
밑에는 캡쳐리스트를 적어주셨는데 쓰신 이유와 안쓰신 이유를 알려주세요.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +                self.descriptionTextView.isEditable = true
분기를 치셨는데, 분기를 하실거면 false상황도 정의를 하시는게 맞다고 생각합니다. 
```swift
self.datePicker.isEnabled = isEditable ? true : false
```
형태로요

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +            }
self?.descriptionTextView.layer.borderWidth = isValid ? .zero : Style.detailTextViewBoderWidth

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +                    self.dismiss(animated: true)
읽기 어려운 코드 같습니다. 추후 긴 코멘트에서 따로 말씀드리겠습니다.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/List/View/CircleLabel.swift
> +
draw는 언제 사용할까요 ?

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/List/View/ListCell.swift
> +    @available(*, unavailable)
어떤 의미로 쓰신걸까요 ?

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/List/View/ListCell.swift
> +
정말 많이 쓰이는 콜이죠. 
어떤 경우에 쓰시는게 좋을까요 ?

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/List/View/ListCell.swift
> +        }
항상 분기는 둘 다를 염두해야합니다.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/List/View/ListHeaderView.swift
> +        stackView.axis = .horizontal
기존 다른 프로젝트의 stackview이름은 stackview인데, 여기는 스택뷰라는 명시도 없네요.
하나의 생각으로 맞춰주세요.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/List/View/ListHeaderView.swift
> +    private let titleLabel: UILabel = UILabel()
titleLabel: UILabel = UILabel() 
뭔가 복잡해보이지 않으신가요 ?

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/List/View/ListView.swift
> +    private(set) var state: State
일전에 말씀드린 것 처럼 뷰에 상태가 그대로 있는건 구조상 잘못된거라고 생각합니다. 
수정해주세요.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/List/ViewController/ListViewController.swift
> +        stackView.backgroundColor = Color.listViewSpacing
이 VC 에서 스택뷰는 전체 뷰를 의미하는데, 스택뷰라는 이름으로 괜찮을까요 ?

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/List/View/CircleLabel.swift
> +
You do not need to override this method if your view sets its content in other ways. For example, you do not need to override this method if your view just displays a background color or if your view sets its content directly using the underlying layer object.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/List/View/CircleLabel.swift
> +
어디있는 글일까요 ?

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/List/ViewController/ListViewController.swift
> +        let listView = ListView(state: .doing, frame: .zero, style: .plain)
lazy의 명확한 이유를 말씀해주세요.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/List/ViewController/ListViewController.swift
> +        let listView = ListView(state: .doing, frame: .zero, style: .plain)
절대 나쁘다고 생각하지 않습니다. 성능을 향상시킬수 있는 방법 중 하나니까요.

2023-01-20 06:03 UTC, July911 commented on ProjectManager/ProjectManager/Presentation/List/ViewController/ListViewController.swift
> +        }
VM에서 해야할 일이라고 생각합니다

2023-01-20 06:14 UTC, July911 commented
정말 고생하셨습니다 :) 짧은 기간인데 고생하셨습니다 :) 
전체적으로 본다면, 상세 구현은 잘하셨다고 생각합니다. 

## 질문 
HeaderView
UITableView 헤더를 통해 각 리스트의 제목을 작성하려고 했습니다. 하지만 스크롤 시 헤더 또한 움직이는 문제나, plain이 아닐경우엔 위로 스크롤하면 사라지기도 했습니다. 때문에 이 헤더를 따로 분리하여 스택뷰에 넣는 방향으로 구현하였습니다.

--> 추후에 섹션 헤더로 바꾼다고 하셨고, 확장을 위해 콜렉션뷰로 바꾼다고 하셨으니 해결될 것이라고 생각합니다. 

데이터 바인딩
현재 저는 클로저에 의한 콜백으로 데이터 바인딩을 해결해주었습니다! 하지만 이 밖에도 옵저버 패턴이나 델리게이션, RxSwift나 Combine을 통해서도 바인딩을 해줄 수 있는 것으로 알고 있습니다. 이번 프로젝트와 같은 경우에 어떤 방법을 취하는 것이 적절한지 궁금합니다!

--> 저라면 개인적으로 RxSwift를 사용할 것 같습니다. 하지만 combine역시도 애플에서 만든것이라 좋은 선택지가 될 수도 있을 것 같습니다.  

뷰 컨트롤러의 로직
최대한 뷰모델이 뷰컨트롤러에게 값을 제공하여 판단할 일이 없도록 하고 싶었으나, 가령 색상 등의 UI 요소를 반환하게끔 한다면 기껏 뷰와 분리시켜 놓아 생긴 장점이 흐려질 것이라고 생각해 Bool 타입의 값 등을 반환하였습니다. 반환된 Bool 값에 따라 색상을 설정하게 하는 등의 로직은 뷰컨트롤러가 가지고 있는데 이런 로직이나 비슷한 로직들의 경우 현재 위치가 적절하게 분리되었는지 잘 모르겠습니다.

 분기에 대한 말씀을 드린다면, 뷰모델에서 한번에 분기를 쳐서 액션을 정의하시는게 좋아보입니다.
지금은 모든 메서드에서 수정인지 추가인지에 대한 분기를 치고 있어서 너무 코드가 복잡해진 것 같습니다. Bool값 같은 경우는 연산프로퍼티로 존재해도 괜찮을 것 같습니다. 


## 전체적인 구조 

전체적으로 본다면 클린아키텍쳐를 어느정도 이해하신 것 같습니다. 
하지만 UseCase가 가지고 있는 명확하지 않은 객체와, Domain 이 과연 분리가 되어있는가? 는 잘 모르겠습니다.
또한 뷰모델에서 최대한 판단하시고자 하는점은 명확했지만, 분기처리나 로직 등이 아직은 VC에 남아있는 모습입니다.

VC에서 가져가야될 문제를 VM로 빼신 와중에 View에 오히려 로직을 넣어버린감도 없지않아 있는 것 같습니다. 

또한 커스텀 UI를 만드신 목적이 너무 하나의 뷰에서 쓰일 용도로 만드신 것 같아 이러한 부분도 조금 더 범용적으로 사용 될 수 있게 바꾸시거나, 아니면 VC에서 View를 만들때 View 프로퍼티를 바꿔주는 방법으로 바꾸시고 네이밍을 조금 더 명확하게 가져가시는게 좋을 것 같습니다. 

일전에 디스코드 통화로 많은 대화를 했다고 생각합니다. 앞으로의 구조 변경이나, 방향성에 대해 오늘의 코멘트와 어제 나눈 이야기를 바탕으로 더 공부해보실 수 있을 것 같습니다. 
MVVM이 처음이실텐데 고생하셨습니다. 좋은 연휴 보내세요.

2023-01-23 07:25 UTC, Gundy93 commented on ProjectManager/ProjectManager/Domain/Model/Project.swift
> +extension Project: Hashable { }
네! 현재는 Hashable이 필요하지 않기 때문에 삭제하였고, 앞으로는 이런 상황에서는 바로 보이도록 하겠습니다. 😃

2023-01-23 07:27 UTC, Gundy93 commented on ProjectManager/ProjectManager/Util/Constant/Constant.swift
> +    enum Number {
어디에서 사용되는지 뎁스를 추가하여 명확히 하도록 하겠습니다! 혹은 사용하는 파일에 추가하는 것이 더 적절할지 고민해보도록 하겠습니다.

2023-01-23 07:28 UTC, Gundy93 commented on ProjectManager/ProjectManager/Util/Constant/Constant.swift
> +        static let listTitleMargin: CGFloat = 8
레이아웃과 관련된 숫자들마저  enum으로 관리하니 오히려 가독성이 떨어져버렸습니다. 이번 프로젝트에선 해당 사항들은 enum으로 빼지 않도록 하겠습니다! 😃

2023-01-23 07:31 UTC, Gundy93 commented on ProjectManager/ProjectManager/Util/Extension/Date+.swift
> +        dateFormatter.locale = Locale(identifier: Locale.preferredLanguages[0])
오늘 [Data Formatting Guide](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DataFormatting/DataFormatting.html#//apple_ref/doc/uid/10000029-CJBCGJCJ)의 [Date Formatters](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html#//apple_ref/doc/uid/TP40002369-SW1) 파트를 모두 읽어보았습니다. 앞으로는 아카이브에 있는 문서 목록에 사용하려는 기능 관련 아티클 등이 있는지 확인해보고 읽어보는 습관을 들여보겠습니다! 감사합니다. 또한, 이런 비용이 많이 드는 작업에 대해서 static을 사용할 수 있도록 하겠습니다! 감사합니다 😃

2023-01-23 07:33 UTC, Gundy93 commented on ProjectManager/ProjectManager/Domain/UseCase/Detail/DefaultDetailUseCase.swift
> +            return project.description
ProjectTextItem의 이름을 model의 데이터와 통일하기보다는 더 가독성이 좋은 네이밍을 고민해보겠습니다!

2023-01-23 07:41 UTC, Gundy93 commented on ProjectManager/ProjectManager/Domain/UseCase/List/DefaultListUseCase.swift
> +    var listOutput: ListOutput?
지금 생각해보니 UseCase가 데이터를 들게하고, 변경되면 자동으로 뷰모델에 전달하려다가 발생한 구조적 문제인 것 같습니다. 아래에 남겨주신 코멘트와 함께 고민해서 처리하도록 하겠습니다! 😃

2023-01-23 07:41 UTC, Gundy93 commented on ProjectManager/ProjectManager/Domain/UseCase/List/DefaultListUseCase.swift
> +        }
데이터를 들지 않고 로직만을 처리하는 방향으로 수정하겠습니다!

2023-01-23 07:44 UTC, Gundy93 commented on ProjectManager/ProjectManager/Domain/UseCase/List/DefaultListUseCase.swift
> +    }
바깥에 공개되어 있는 메서드의 수를 더 적게하려다보니 `saveProject` 메서드 내부에서 add인지 edit인지를 판단하게 해서 호출하게 하였는데, `saveProject` 메서드는 따로 추가적인 작업이 들어가지 않으므로 삭제하고, 바깥에서 판단하는 로직을 통해 add와 edit을 적절히 호출하는 방향으로 수정하겠습니다. 😃

2023-01-23 07:48 UTC, Gundy93 commented on ProjectManager/ProjectManager/Domain/UseCase/Detail/Protocol/DetailUseCase.swift
> +    var state: State { get }
필요하지 않은 것 같습니다. State에 따라 수정기능 활성화/비활성화를 시도하려던 것 같은데, toDo일 경우라고 무조건 새로 작성하는 프로젝트가 아니므로 잘못된 접근이었던 것 같습니다. 삭제하도록 하겠습니다.

2023-01-23 07:49 UTC, Gundy93 commented on ProjectManager/ProjectManager/Domain/UseCase/Detail/DefaultDetailUseCase.swift
> +    var state: State {
위의 코멘트와 같이 삭제하도록 하겠습니다! 해당 유즈케이스와 관련된 화면에선 state는 전혀 필요하지 않으므로 삭제하는 것이 적절할 것 같습니다. 😃

2023-01-23 07:50 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +    private let  titleTextField: DetailTextField = {
놓치지 않도록 하겠습니다! 감사합니다 😃

2023-01-23 07:59 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +    var delegate: DetailProjectDelegate?
Delegate 문서에 따르면 weak를 사용하는 것이 적절하나, 사용하는 방법을 몰라 우선은 강한 참조로 작성하였는데, `DetailProjectDelegate: AnyObject`로 클래스임을 명시하여 weak 키워드를 사용할 수 있게 수정하였습니다! 앞으로는 하나하나 정확한 용법에 맞게 사용하도록 하겠습니다!

2023-01-23 08:04 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +        return stackView
iOS 11.0부터 `setCustomSpacing(_:after:)` 메서드를 사용하여 특정 서브뷰 이후로 커스텀 스페이싱을 넣을 수 있음을 확인하였습니다! 이 밖에도 다양한 기능에 대해서 공식문서를 토대로 공부해보도록 하겠습니다! 😃

2023-01-26 21:54 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +        let textView = DetailTextView()
extension을 통해 그림자를 설정하는 메서드를 추가하는 것으로 텍스트 필드와 텍스트 뷰를 수정하였습니다!

2023-01-26 21:59 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +            descriptionTextView.isEditable = false
configureEditable() 메서드로 분리하여 초기상태를 지정할 때 뿐 아니라, 사용자가 Edit 버튼을 눌렀을 때도 사용하도록 하였습니다!

2023-01-26 22:05 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +            if isEditable == true {
상세화면에서의 클로저는 모두 캡처리스트를 통해 약한 참조를 하도록 변경하였습니다!

![](https://i.imgur.com/q4Vyg7I.png)

앞으로는 위와 같은 과정을 통해 캡쳐리스트를 붙일지 안붙일지 결정하고자 합니다.

2023-01-26 22:09 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +                self.descriptionTextView.isEditable = true
false에서 true로 변하는 경우는 있어도 반대는 없다고 생각해서 그렇게 작성했던 것 같습니다!

```swift
if isEditable == true {
    self?.navigationItem.leftBarButtonItem = self?.makeLeftButton()
    self?.navigationItem.rightBarButtonItem = self?.makeDoneButton()
}
self?.configureEditable()
```
```swift
private func configureEditable() {
    titleTextField.isEnabled = viewModel?.isEditable ?? false
    datePicker.isEnabled = viewModel?.isEditable ?? false
    descriptionTextView.isEditable = viewModel?.isEditable ?? false
}
```

위와 같은 형태로 변경해 viewModel의 값을 따라가도록 하였습니다.

2023-01-26 22:11 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +            }
삼항 연산자를 사용하도록 변경하였습니다! 같은 변수에 값을 할당하는 것만이 로직의 전부일경우 앞으로도 삼항연산자를 사용하는 걸 먼저 고려하겠습니다!

2023-01-26 22:14 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/Detail/ViewController/DetailViewController.swift
> +                    self.dismiss(animated: true)
저장을 할 때에는 항상 화면이 dismiss 되므로, 따로 handler 파라미터를 받지 않고 내부에 dismiss(animated: true) 코드를 넣는 것으로 수정하였습니다!

```swift
case true:
    action = UIAction { [weak self] _ in
        self?.saveProjectIfValid()
    }
```

2023-01-26 22:34 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/List/View/CircleLabel.swift
> +
공식 문서에 따르면 "Subclasses that use technologies such as Core Graphics and UIKit to draw their view’s content should override this method and implement their drawing code there." Core Graphics나 UIKit을 사용할 때 재정의해 사용하라고 합니다.

[draw(_:)](https://developer.apple.com/documentation/uikit/uiview/1622529-draw) Discussion의 첫 번째 문단에 있는 글입니다!

제가 사용한 경우에 대해서는 draw(_:)를 재정의 하지 않는 것이 바람직한 것 같아서 코드의 위치를 옮겼습니다!

2023-01-26 22:36 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/List/View/ListCell.swift
> +    @available(*, unavailable)
@available(*, unavailable)는 혹시라도 접근하게 되면 컴파일 단에서 에러를 표출하는 어트리뷰트입니다! 사용되지 않는 이니셜라이저임을 명시하고자 required init?(coder:)에 사용하였습니다!

2023-01-26 22:43 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/List/View/ListCell.swift
> +
Subclasses can override this method as needed to perform more precise layout of their subviews. You should override this method only if the autoresizing and constraint-based behaviors of the subviews do not offer the behavior you want. You can use your implementation to set the frame rectangles of your subviews directly.

공식문서에 따르면 원하는 동작을 제공하지 않을 경우에 사용하라고 나와있는데, 다른 적절한 방법이 있는지 모르겠습니다!

2023-01-26 22:44 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/List/View/ListCell.swift
> +        }
```swift
deadlineLabel.textColor = isOverDue ? Color.overDue : .label
```

위와 같은 삼항연산자로 수정하였습니다!

2023-01-26 23:02 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/List/View/ListHeaderView.swift
> +        stackView.axis = .horizontal
headerStackView라는 이름으로 수정하였습니다!

2023-01-26 23:03 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/List/View/ListHeaderView.swift
> +    private let titleLabel: UILabel = UILabel()
타입 어노테이션을 삭제하였습니다!

2023-01-26 23:04 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/List/View/ListView.swift
> +    private(set) var state: State
컬렉션 뷰로 변경하면서 수정하였습니다!

2023-01-26 23:05 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/List/ViewController/ListViewController.swift
> +        stackView.backgroundColor = Color.listViewSpacing
컬렉션뷰로 변경하면서 삭제하고, projectListHeaderStackView, projectListStackView라는 이름으로 스택뷰를 네이밍하여 사용하였습니다!

2023-01-26 23:10 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/List/ViewController/ListViewController.swift
> +        let listView = ListView(state: .doing, frame: .zero, style: .plain)
해당 테이블 뷰의 delegate와 dataSource를 self로 설정하기 위해 lazy를 사용했습니다. 하지만 두 작업 모두 "Lazy properties are also useful when the initial value for a property requires complex or computationally expensive setup that shouldn’t be performed unless or until it’s needed."에 해당하는 부분은 아닌 것 같습니다.

앞으로는 self로 지정하기 위해 lazy를 쓰는 것은 더 고민해보고 결정하겠습니다.

2023-01-26 23:28 UTC, Gundy93 commented on ProjectManager/ProjectManager/Presentation/List/ViewController/ListViewController.swift
> +        }
뷰모델에 메서드를 추가하여 다음과 같은 형태로 변경하였습니다.

```swift
let detailViewModel = self.viewModel?.makeDetailViewModel(project: nil)
self.presentDetailView(viewModel: detailViewModel)
```

2023-02-02 02:28 UTC, closed without merging