프로젝트 매니저 [Step 2] inho
yagom-academy/ios-project-manager pull request #248
Opened 2023-01-19 11:44 UTC by inho-98

안녕하세요, 태태! (@uuu1101)
뷰를 그리는 작업이 생각보다 까다롭기도 하고, 
뷰모델을 활용한 코드 흐름을 작성하는 것도 꽤 낯설어서 시간이 많이 들은것 같습니다..!ㅎㅎ

부족한 부분이 많아서 가감없는 리뷰 부탁드리겠습니다~! 🙇‍♂️

## 작동화면
|<img src=https://i.imgur.com/aTxOnuR.gif width=400>|<img src=https://i.imgur.com/9duM1iq.gif width=400>|
|:-:|:-:|
|할일 추가|할일 이동|
|<img src=https://i.imgur.com/LbImbIu.gif width=400>|<img src=https://i.imgur.com/rQfDph6.gif width=400>|
|할일 삭제|할일 편집|

## 이번 프로젝트에서 새로 알게된 점
- **MVVM 디자인패턴**
    - 바인딩을 활용한 뷰에 데이터를 표시하는 방법
    - 뷰모델에 대한 테스트코드
- **iPad환경에서의 modalPresentaionStyle**
    - formSheet
    - popover
- **LongPressGuestureRecognizer 활용**

## 고민했던 점
#### `ListItemCellViewModel`에서 데이터 처리 방법
- 프로젝트의 모델타입인 `ListItem`의 `dueDate` 프로퍼티가 화면에 보여지기 위해서는 `Date`타입에서 `String`타입으로 변환되어야 하고, 이를 관리하는 역할을 뷰모델이 한다고 판단했습니다. 
- 그래서 화면에 보여질 타입과 정보를 반영한 `ListItemData` 구조체를 구현하고 활용했습니다. 
    ```swift
    final class ListItemCellViewModel {
        struct ListItemData {
            var title: String
            var body: String
            var dueDate: String
            var isOverDue: Bool = false
        }
        ...
        private var handler: ((ListItemData) -> Void)?
        private var listItemData: ListItemData {
            didSet {
                self.handler?(listItemData)
            }
        }
        ...
        func bind(_ handler: @escaping (ListItemData) -> Void) {
            self.handler = handler
        }
    }
    ```
    - 뷰에 보여질 타입을 담은 구조체와 handler를 이용해서 뷰에게 전달하는 방식입니다.

#### `MainViewModel`에서 모든 리스트아이템 배열 관리방법
- 기존에는 각 타입`(todo, doing, done)`마다 배열을 생성하였는데요, 이렇게 했을때 해당 타입의 리스트를 불러올때 모든 로직마다 switch문이 반복해서 발생하는 중복이 있었습니다.
- 이런 중복을 줄이기 위해서 `totalListItems` 프로퍼티를 생성해 하나의 이중 배열로 관리하고, 인덱스 관련 오류를 줄이기 위해서 `ListType`열거형에 Int타입 rawValue를 채택하고, 각 rawValue의 순서에 맞게 구성하였습니다.
    ```swift
    enum ListType: Int, CaseIterable {
        case todo
        case doing
        case done
    }

    final class MainViewModel {
        private var totalListItems: [[ListItem]] = [[], [], []] 
        // [[todo배열], [doing배열], [done]배열] 
        ...
    }
    ```
#### 할일 추가/편집 화면을 재사용하는 방법
- 할일을 추가/편집하는 화면의 레이아웃이 동일해서 뷰와 뷰컨을 재사용할 방법을 고민했습니다. 두 화면의 공통점은 입력될 양식을 나타내고 있다고 생각하여 `ListFormView`와 `ListFormViewController`라는 네이밍을 사용했습니다. 
- 두 화면의 차이점은 `ListItem`을 모델로 가지고있는지 없는지에 차이가 있다고 생각했습니다. 그래서 `ListFormViewModel`을 옵셔널 프로퍼티로 선언하여 생성후에 값이 nil일때는 할일을 추가하는 것이고, 값이 있을때는 편집하는 화면으로 구분 가능하도록 구현하였습니다.
    ```swift
    class ListFormViewController: UIViewController {
        ...
        var formViewModel: ListFormViewModel?
        ...

        init(formViewModel: ListFormViewModel? = nil) {
            super.init(nibName: nil, bundle: nil)

            self.formViewModel = formViewModel
        }
        ...
    }
    ```

#### `StackView`에서 `inset`을 지정하는 방법
- 기존에는 `stackView` 내에 여백을 주고싶을때, `stackView.leading`을 container뷰에서 일정 상수만큼 멀어지도록 `constraint`를 지정하였습니다.
- 이번에는 주로 `stackView.layoutMargin` 프로퍼티를 이용해서 한곳에서 여백에 관한 크기를 관리하는 방법으로 구현했습니다.
    ```swift
    class ListItemCell: UITableViewCell {
        private let cellStackView: UIStackView = {
            let stackView = UIStackView()
            ...
            return stackView
        }()
        ...
            cellStackView.isLayoutMarginsRelativeArrangement = true
            cellStackView.layoutMargins = .init(top: 5, left: 15, bottom: 5, right: 15)
        ...
    }
    ```

## 조언을 얻고싶은 부분
#### `View`와 `ViewModel` 간의 흐름
- 이번 코드를 작성하면서 뷰모델의 역할을 생각할때, 뷰나 뷰컨트롤러에서 어떤 액션을 전달받고, 어떻게 데이터를 가공하고, 뷰와 바인딩할것인가 를 중점적으로 생각했습니다. 보여줄 데이터를 중심으로 bind메서드를 구현하고, 뷰모델을 구성했는데, 어색한 부분이나 보완될 부분이 있을것 같아서 의견 부탁드리겠습니다..!🙏

#### 팝오버메뉴를 보여주는 `MenuPresentable` 프로토콜
- 셀에서 longPress 제스쳐가 발생했을때, 팝오버로 이동 메뉴를 보여주도록 구현하는 과정에서, 알럿을 여러 화면에서 재사용하기위해 하나의 타입으로 묶는 방법을 생각했습니다. 보여주는 메뉴가 `UIActionController`이고 이를 `present()`메서드로 뷰에 보여주기 위해서 프로토콜에 ViewController를 상속하였습니다. 그런데 구현하는 과정에서 메인 뷰컨트롤러 내의 다른 테이블뷰로 이동하는 기능이 필요해서 `MainViewController`를 상속하도록 변경하였습니다.
- 결과적으로는 `MainViewController`의 하위클래스에서만 채택가능한 프로토콜이 되었고, `MainViewController`는 한개밖에 없어서 분리의 장점이 없다고 생각되었습니다.
현재는 프로토콜로 분리한 상태인데 태태는 어떻게 생각하시는지, 혹은 더 나은 방향이 있을지 궁금합니다..! 🧐

2023-01-20 09:03 UTC, uuu1101 requested changes
안녕하세요 @inho-98 🙌
Step2 너무 고생하셨어요! 
MVVM도 잘 이해하시고 VM도 잘 구현하셨네요 !
러닝커브가 빠르신것 같아요 👍👍 
코드 가독성도 좋고 폴더링도 잘 해두셨네요 !

--- 
## 조언을 요청하신 부분에 대한 의견 
1. `View`와 `ViewModel` 간의 흐름
해당 부분에 대해서 고민을 많이 하신것 같아요!  View와 ViewModel 간의 역할을 잘 이해하신것 같고 binding에 대한 개념에 대해서도 잘 이해하셨네요! 👍

2. 팝오버 메뉴를 보여주는 `MenuPresentable` 프로토콜
- 저희 의견도 비슷한데요, 결과적으로 MainViewController의 하위 클래스에서만 채택 가능한 프로토콜이 되었기 때문에 의미없는 프로토콜이 되어버린 느낌이에요. 이런 구조로 가져간다면 MainViewController에 해당 메서드를 포함시키는게 좋을것 같아요. 
- 하지만 의도(재사용성과 확정성에 대한 고민)를 고려하여 만약 구조를 변경해 본다면 UIViewController를 상속받고 move 메서드에서 viewModel을 주입 받을때, viewModel도 하나의 타입으로 묶게끔 프로토콜을 채택해주는 방법이 있을것 같아요. 
- 물론 이 방법보단 현재 구조에서는 MainViewController가 해당 메서드를 가지는것 또는 CustomViewController를 하나 더 만들어서 제스처에 해당하는 메서드들을 가지게끔 하여 오버라이딩 하여 사용하는 방법도 있을 것 같아요 ! 
--- 
## 추가적인 사항
UX/UI에 대한부분입니다. Todo를 Add하는 부분에 리스트 타이틀을 변경하여 Add를 하고 있다는 느낌을 사용자에게 주거나 Done버튼타이틀을 Add로 변경해주는것도 하나의 방법인것 같아요 :)

2023-01-20 09:03 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/Protocol/MenuPresentable.swift
> +    func makeAlertAction(of type: ListType, viewModel: ListItemCellViewModel) -> UIAlertAction {
항상 뷰모델을 ListItemCellViewModel 만 주입받는다면,  아래처럼 숨겨줘도 되지 않을까요? 👀
```suggestion
    func makeAlertAction(of type: ListType, _ viewModel: ListItemCellViewModel) -> UIAlertAction {
```

2023-01-20 09:03 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/Protocol/MenuPresentable.swift
> +            title = "Move To DONE"
"Move To TODO" 같은 값들을 따로 관리해주는건 어떠신가요?

2023-01-20 09:03 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/View/AdditionalView/ListFormViewController.swift
> +            title = Constant.done
해당 부분은 따로 String 값을 관리해주셨네요 👍

2023-01-20 09:03 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/View/Base.lproj/Main.storyboard
>  <?xml version="1.0" encoding="UTF-8"?>
스토리보드는 필요한가요?! 👀

2023-01-20 09:03 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/View/ListView/MainViewController.swift
> +    private lazy var doneListDataSource = configureDataSource(of: .done)
lazy var로 설정하신 이유가 있으실까요?

2023-01-20 09:03 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/View/ListView/MainViewController.swift
> +}
Constant 도 포함하고 있는 속성들이 많아진다면 네이밍을 세분화해서 나누어줘도 좋을것 같아요 👍

2023-01-25 14:54 UTC, inho-98 commented on ProjectManager/ProjectManager/Source/Protocol/MenuPresentable.swift
> +    func makeAlertAction(of type: ListType, viewModel: ListItemCellViewModel) -> UIAlertAction {
수정하였습니다..!
> 3a599de

2023-01-25 14:55 UTC, inho-98 commented on ProjectManager/ProjectManager/Source/Protocol/MenuPresentable.swift
> +            title = "Move To DONE"
다른 파일에서와 마찬가지로 NameSpace로 분리하여 관리하도록 수정했습니다!

> a050208

2023-01-25 14:56 UTC, inho-98 commented on ProjectManager/ProjectManager/Source/View/Base.lproj/Main.storyboard
>  <?xml version="1.0" encoding="UTF-8"?>
코드로 전체 화면을 구현하면서 스토리보드가 필요하지 않으면 삭제 가능한걸 알게되어서 삭제하였습니다!

> 73b5a25

2023-01-25 15:02 UTC, inho-98 commented on ProjectManager/ProjectManager/Source/View/ListView/MainViewController.swift
> +    private lazy var doneListDataSource = configureDataSource(of: .done)
dataSource를 생성하는 부분을 같은 파일 내의 `configureDataSource()`메서드로 구현한 상태였고 초기화 전에는 self에 접근할 수 없으니 필요한 시점에 lazy를 이용해서 구현하겠다는 의도로 사용했었습니다!

그런데 lazy 키워드는 당장 초기화할 필요가 없는 무거운 동작을 메모리 절약을 위해 필요한 시점에 초기화 하는 것에 목적이 있고 thread-safe하지 않을 수 있다는 점을 고려해서 해당 부분은 옵셔널 프로퍼티로 변경 후 이니셜라이저에서 값을 변경하도록 수정했습니다!

> 5180fe9

2023-01-25 15:05 UTC, inho-98 commented on ProjectManager/ProjectManager/Source/View/ListView/MainViewController.swift
> +}
짚어주신대로 혼동이 있을 수도 있어서 `todo -> uppercasedTodo`와 같이 네이밍을 좀 더 구체적으로 변경했습니다! 
종류나 갯수가 더 많아질때에는 내부에 enum으로 한번 더 분리를 해줄 수도 있을것 같습니다..!

> d3b2d8b

2023-01-25 15:19 UTC, inho-98 commented
> UX/UI에 대한부분입니다. Todo를 Add하는 부분에 리스트 타이틀을 변경하여 Add를 하고 있다는 느낌을 사용자에게 주거나 Done버튼타이틀을 Add로 변경해주는것도 하나의 방법인것 같아요 :)

- 해당 부분은 네비게이션 타이틀에 TODO라고 명시되어 있어서 완료 버튼이 ADD로 변경되면 Todo에 추가한다는 의미가 더 명확해진것 같아서 의견 주신방향으로 수정하였습니다!ㅎㅎ

  |<img width="341" alt="스크린샷 2023-01-26 오전 12 05 59" src="https://user-images.githubusercontent.com/71054048/214598780-bdc87965-d419-4320-958b-a7ca6a13e814.png">|
  |--|

> 팝오버 메뉴를 보여주는 MenuPresentable 프로토콜
- `MenuPresentable` 프로토콜은 기존 방법대로 유지하는 장점이 없는 것 같아서 프로토콜은 `UIViewController`를 상속하고, 나머지 메서드는`MainViewController`로 이동시켰습니다!
- 새로운 프로토콜을 추가해서 더 나은 방법을 시도했지만 구조가 더 복잡해지고 동시에 그만큼 재사용될 가능성이 크지 않다는 생각도 들어서 뷰컨에 포함하는 정도로 우선 마쳤지만 아쉬움이 계속 남아서 더 고민해봐야 할 것 같습니다..!

2023-01-26 06:32 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/View/ListView/MainViewController.swift
> +    private lazy var doneListDataSource = configureDataSource(of: .done)
lazy에 대해서 잘 이해하고 계시네요 :)

2023-01-26 06:38 UTC, uuu1101 commented
STEP2 진행하시느라 고생하셨습니다 ! 👏👏👏
다음 STEP 진행하시면서 궁금하시거나 도움이 필요하시면 언제든지 DM이나 코멘트 주세요!

2023-01-26 06:38 UTC, merged