프로젝트 매니저 [Step 2] 미니
yagom-academy/ios-project-manager pull request #249
Opened 2023-01-20 03:41 UTC by leegyoungmin

안녕하세요 그린(@GREENOVER)
TCA에 대해서 공부하다 보니 PR이 다소 늦었습니다.
PR은 TCA 자체에 대한 고민들이 많이 담기게 된 것 같습니다.

## 📝 STEP 진행 중 경험하고 배운 것
- TCA를 활용한 SwiftUI 구성하기
- TCA에서 Store를 구성하는 방법

## 구현 내용
![appRecording](https://i.imgur.com/81uVICv.gif)

## 💭 고민한 부분

### 각 리스트에 대한 Reducer의 구성
각 상태에 따른 리스틀 구성하는 것이 아니라 일반화된 리듀서를 활용하는 방법에 대해서 고민해봤습니다. 하지만, 한개의 상태를 통해서 데이터를 이동시키는 과정에서 발생하는 문제들이 생기게 됩니다. 예를 들어서 한개의 리스트에서 이동을 하기 위해서 누른 버튼이 어떤 버튼인지를 알게 하기 위해선 그 상태를 액션에 같이 담아야 하고, 이를 통해서 판단하는 방법이 있습니다. 이 방법은 한개의 ListStore에서 관리하는 여러개의 데이터를 변환시켜주어야 하는 데, reduce 메서드 내에서 값을 변경하는 것이 불편할 수 있다고 생각했습니다. 그래서 한개의 reducer를 선언하는 것이 아니라 여러가지의 Reducer를 구성하여서 각각에 따른 액션을 지정할 수 있도록 하였습니다.

## 🤔 조언을 얻고 싶은 부분
### TCA에서 바인딩을 활용하는 방법
새로운 프로젝트를 작성하거나 디테일 뷰로 이동하는 과정에서 바인딩에 대한 문제가 발생하였습니다. 사용자의 액션에 따라서 상태 값을 변경해주는 방법을 활용하였지만, 이를 통한 방법이 잘 작성된 것인지 궁금합니다. 또한, 그린은 바인딩을 통해서 뷰를 이동시키는 과정을 어떤 식으로 작성하시는 지에 대해서 조언을 얻고 싶습니다. 

### ForEachState를 활용하는 방법
프로젝트에 대한 타입을 활용하는 것이 아닌 이에 준하는 State를 구성하여서 활용하는 방법에 대해서 궁금증이 생겼습니다. 직접 Project의 리스트를 구현하는 방법도 있을 것 같은데 왜 ForEachState를 활용하는 방법이 구성되었는지 궁금합니다. 혹시 pointfree 사이트에 이와 관련된 내용이 있을까요?

### 프로젝트 설계
TCA는 액션을 기반으로 하는 Reducer를 활용하는 것이 특징입니다. 하지만, 이를 통해서 계발을 하게 되면, 다양한 Reducer들이 서로를 포함하고 있는 관계를 구성하게 되는 것처럼 느껴졌습니다. 그렇다면, 이런 것들이 어떤 이점을 가지게 되는 것이고, 이를 해결하는 방법이 없는지 궁금합니다.

2023-01-20 06:31 UTC, GREENOVER requested changes
@leegyoungmin 
미니 스텝2 너무 고생 많으셨습니다!
TCA와 SwiftUI 모두 너무 잘쓰셨는데요?
1~2주 안에 이렇게 러닝커브가 빠르다니... 타고나신게 아닐까 싶네요😲
스텝2 모든 요구사항 잘 만족한다고 보이고 코드도 크게 군더더기 없고 택하신 기술 스택 자체도 아주 잘 이해하신것 같네요!
그럼 리뷰 시작하겠습니다ㅎㅎ
***
### 칭찬 드리고 싶은 부분
- 파일 및 그룹화가 정말 잘 되어 있네요 💯
- 뷰를 잘 쪼개셔서 가독성이 좋습니다 💯
- TCA를 전반적으로 잘 이해하고 사용하신것 같아요 💯
- 세세한 커밋 관리도 아주 좋습니다 💯
***
### 조언을 요청하신 부분에 대한 저의 의견
1. TCA에서 바인딩을 활용하는 방법
- 저는 미니가 현재 프로젝트에서 뷰 간 바인딩을 잘 활용했다고 생각해요!
저또한 state를 get하고 해당 state관련 액션에 대해서 send로 바인딩을 해줍니다.
즉 미니가 한것과 동일하게 구현하고 있습니다!
그래서 사실 이부분에서 조언 드릴건 없는것 같고 지금처럼 잘 사용하시면 될 것 같습니다👍
2. ForEachState를 활용하는 방법
- 말씀하신것처럼 IdenfiedArrayOf 타입으로 State 내부 ID 값 등을 두거나 하여 Idenfitiable하게 State 자체를 만들고 활용해도 좋습니다.
아니라면 지금처럼 해당 Project 프로퍼티를 State에 두고 사용할 수도 있겠죠!?
Project 타입 구현을 보니 Identifiable하고 id도 있기에 State 내부에서 IdenfiedArrayOf 타입으로 프로퍼티를 만들어 사용해도 손색 없을것 같아요.
여기서 질문하셨던 ForEachState를 활용하는 방법이라고 할때는 명확히 IdenfiedArrayOf로 하지 않아야될 이유는 없습니다.
ForEach로 하지 않으면 안돼! 이런 경우가 사실 없다고 생각해요.
그렇기에 이 부분에서 어떤 코드를 가져갈 지 선택사항이라고 저는 생각합니다.
즉, 정리해보자면 IdenfiedArrayOf로 가져가고 View에서 ForEachStore를 사용하는것과 지금처럼 ForEach로 사용하는것에서 기능적 차이는 없다고 생각해요.
State 프로퍼티 관점에서도 두가지 경우 모두 맞아보입니다.
결국 미니가 정해서 컨벤션을 어떻게 가져가서 쓸지 나름이라고 생각합니다!
***
3. 프로젝트 설계
- 하위 리듀서를 상위 리듀서에서 풀백 받아 처리를 해주는것은 TCA 구조의 가장 큰 장점이기도 합니다.
왜냐면 TCA의 결국 가장 중요한 기조는 컴포저블한것인데 각 아주 세부적인것까지 컴포저블하게 관심사를 나누고 이 부품들을 필요한 곳에서 잘 조합하여 쓸 수 있어야 TCA를 적절하게 쓰는거라고 생각합니다.
그렇기에 여쭤보신 리듀서를 나누고 상위에서 여러 리듀서를 포함하게 되는 구조가 이런 이점들을 가져갈 수 있다고 보입니다.
그런데 말씀처럼 이런 리듀서간 설계가 얽히면 한 리듀서에서 모든걸 처리해줘야 할 수도 있고 의존 관계가 역전될 경우도 있습니다.
이에 사실 가장 좋은건 각 도메인 영역들을 프로젝트 초기에 먼저 설계하고 이에 대해 어떤 단위로 쪼갤지와 어느정도로 View/Core를 만들어 리듀서로 가져갈지에 대한 선행이 되는것이 가장 베스트입니다.
사실 프로젝트 코딩 시간보다 아키텍쳐나 도메인 설계를 하는 시간이 더 오래 걸리고 잘 정해야하는 이유도 이와 상응합니다.
그렇기에 결론적으로 말씀드리면 프로젝트 설계 시 어느 단위까지 나누고 사용할지에 대해 구조적으로 잘 설계해야하고 이에 대한 리듀서들을 잘 쪼개서 조합하여 사용하는것이 적절합니다🙌
***
고생 많으셨습니다 미니!
다음 스텝으로 바로 넘어가도 좋지만 한번 생각해볼 포인트들하고 보완되면 좋을 부분이 있어 Request Changes로 남겨두겠습니다!
언제든지 수정 혹은 머지 요청을 해주세요😄

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/Model/Project.swift
> +struct Project: Decodable, Identifiable, Equatable {
인코딩될 여지는 없는 타입일까요?🙋🏻

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/Model/Project.swift
> +struct Project: Decodable, Identifiable, Equatable {
Equatable을 채택하신 이유가 궁금합니다~!
Hashable 채택으로도 컴파일이 될것 같은데 그렇다면 둘은 어떤차이가 있을까요?

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/Model/Project.swift
> +      return ""
해당 코드가 필요한 이유가 궁금합니다🙋🏻

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/Utility/Font.swift
> +}
ViewModifier까지 만드셨다니 아주 최고네요!
그런데 `.font(~~)`만을 적용한것이면 그냥 해당 코드를 직접 Text에 붙이는것도 직관적일것 같은데 만드신 이유가 궁금해요🙋🏻
자주 쓰일때의 이점이 충분해 보이는데 추후 size가 26, 24 등의 커스텀 폰트를 만들어야되면 해당 customTitleStyle 모디파이어 메서드 네이밍이 괜찮을지 궁금합니다.

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/BoardListView/BoardListComponents.swift
> +            project.date << Int(Date().convertDate().timeIntervalSince1970) ? .red : .black
<<는 비트 이동 연산자로 알고 있는데 해당 << 메서드 구현된 내부에서 비트 이동과 다른 느낌의 코드가 담겨있는것 같은데 혹시 <<로 메서드로 만드신 이유가 어떤건지 궁금합니다🙋🏻

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/SheetCoordinator/NavigationBarView.swift
> +          Spacer()
실제 양쪽 Spacer 구현 코드가 없으면 가운데 정렬이 되지 않나요?🙋🏻

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/SheetCoordinator/NavigationBarView.swift
> +        .padding([.vertical, .trailing])
해당 버튼을 title과 한 영역이 아닌 ZStack으로 올려주신 이유가 궁금합니다..!
title과 해당 버튼을 한 영역에 담으면 title의 가운데 정렬 시키기가 어려웠을까요?
또 overlay하고 ZStack이 어떤차이가 있어서 ZStack을 사용하셨는지 궁금해요.

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/SheetCoordinator/SheetCore.swift
> +        state.detailState = DetailState(title: "", description: "", editMode: false)
해당 State를 바꾸는것 자체가 Inner Action으로 볼 수도 있을것 같은데 어떻게 생각하시나요?
조금 더 세부적으로 확장성있게 본다면 State를 변경하는 액션 자체도 만들어서 해당 액션을 통해 관리하는것도 방법일것 같습니다🙋🏻

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/SheetCoordinator/SheetCore.swift
> +  case detailAction(DetailAction)
detailAction 즉, 하위 액션에 대한 모든 처리를 끌고 오는데 디테일 액션 내부에서 유저 액션이 아닌 경우도 내포하기에 User Action 영역으로만 보긴 힘들것 같아보여요🥲
저는 그래서 Action들의 분리를 User Action / Inner Action (business, set state) / Child 로 나누고 있습니다~!

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/StoreTests/ListStoreTest.swift
> +@MainActor
MainActor 프로퍼티 래퍼를 사용하는 이유가 뭘까요~?🙋🏻

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/StoreTests/NavigateStoreTest.swift
> +final class NavigateStoreTest: XCTestCase {
실제 해당 테스트 통과 되나요?🙋🏻

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/AppView/AppCore.swift
> +  case _movingDone(Project)
해당 액션들의 네이밍에 언더바를 붙여주신 이유가 궁금합니다🙋🏻

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/AppView/AppCore.swift
> +
한 라인씩 개행을 해주신것에는 어떤 이유가 있으신가요?

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/BoardListView/Views/TodoBoardListView.swift
> +                  Text("없어짐")
시점에 차이때문에 아래와 같이 간헐적으로 해당 뷰가 노출되는것 같아요🥲
![Simulator Screen Shot - iPad Pro (12 9-inch) (6th generation) - 2023-01-20 at 12 54 56](https://user-images.githubusercontent.com/72292617/213619741-f00687af-ae29-445b-a8d3-04746b0d5dc1.png)
해결 해볼 수 있을까요~?

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/BoardListView/Views/DoingBoardListView.swift
> +struct DoingBoardListView: View {
Todo, Doing, Done 뷰와 코어 모두 사실 전부 같은 구성으로 보입니다🥸
각 보일러플레이트 코드를 만들지 않고 하나로 합쳐서 관리해보면 어떨까요?
합쳐지면서 사실상 해당 프로젝트의 Type만 추가되면 쉽게 구성되지 않을까 싶습니다..!

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/DetailView/DetailView.swift
> +  func body(content: Content) -> some View {
some 키워드를 붙이는 이유가 어떻게 될까요?🙋🏻

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/DetailView/DetailView.swift
> +        .navigationTitle("TODO")
DOING이나 DONE의 할일 시트가 나타났을때도 타이틀이 TODO가 될것 같아요..!

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/DetailView/DetailViewCore.swift
> +//  DetailViewStore.swift
지금까지 작성하신 파일 네이밍 컨벤션 상 DetailCore가 더 적절하지 않을까 싶습니다🙋🏻

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/DetailView/DetailViewCore.swift
> +  let id: UUID = UUID()
Identifiable과 id 프로퍼티가 실제 필요한가요?🙋🏻

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/DetailView/DetailViewCore.swift
> +  case _didChangeDeadLine(Date)
다른 부분에서 State를 변경하는 네이밍으로 _setXXX로 가져갔는데 여기도 동일한 액션 구조지만 네이밍 컨벤션이 조금 다른것 같아요.
하나로 통일되면 컨벤션 유지에 도움이 될 것 같습니다!

2023-01-20 06:31 UTC, GREENOVER commented on ProjectManager/ProjectManager/DetailView/DetailViewCore.swift
> +}.debug()
불필요한 코드는 제거되어도 될 것 같습니다~!

2023-01-24 07:08 UTC, leegyoungmin commented on ProjectManager/ProjectManager/Model/Project.swift
> +struct Project: Decodable, Identifiable, Equatable {
우선적으로 로컬에서 활용하는 것에 초점을 맞춰서 구현하다 보니 Encoding에 대한 부분을 고려하지 않은 것 같습니다.
추가적으로 Encoding의 여지가 있다고 판단하여서 추가하였습니다.
[86f1313](https://github.com/yagom-academy/ios-project-manager/pull/249/commits/86f131394a6f16f54a9f50bd235efabb52f9a163)

2023-01-24 07:41 UTC, leegyoungmin commented on ProjectManager/ProjectManager/Model/Project.swift
> +struct Project: Decodable, Identifiable, Equatable {
Hashable은 hashValue라는 고유한 값을 가질 수 있도록 하는 프로토콜입니다.
Equatable은 `같다.`와 `같지 않다.`라는 논리 연산을 가능하도록 하고, 필요에 의해서 구현할 수 있도록 도와주는 프로토콜입니다.
Hashable은 고유값임을 식별하기 위해서 `==` Operator가 필요하게 됩니다. 그렇기 때문에 Hashable은 Equatable을 상속하고 있습니다.

SwiftUI 구문 중, ForEach를 구현하기 위해서는 Identifiable 하거나, Hashable한 요소들에 대해서만 사용할 수 있습니다.
하지만, Sheet 구문에서 Identifiable한 아이템을 활용하기 위해서, 중복적으로 두가지 프로토콜을 채택하는 것이 아닌, Identifiable을 채택하고, 같음을 연산하기 위해서 필요한 Equatable을 채택하도록 하였습니다.

2023-01-24 07:48 UTC, leegyoungmin commented on ProjectManager/ProjectManager/Model/Project.swift
> +      return ""
원래 의도는 추가적인 상태가 추가되었을 경우, 개발자가 빼먹을 수 있는 부분에 대해서 오류가 나지 않도록 하기 위해서 `@unknown default` 구문을 통해서 `Description` 변수가 누락되지 않도록 하기 위해서 활용하였습니다.

하지만, 위와 같은 값은 다른 개발자가 오류를 통해서 추가 하지 않은 케이스가 있는 것을 알리는 것이 더적절하다고 생각하여서 변경하였습니다.
[046c3b2](https://github.com/yagom-academy/ios-project-manager/pull/249/commits/046c3b221b3c65b4da36a7ba9a826c7037404626)

2023-01-24 07:57 UTC, leegyoungmin commented on ProjectManager/ProjectManager/Utility/Font.swift
> +}
원래의 의도는 Font만을 활용하는 것이 아니라 타이틀에 대한 설정을 가지도록 하려고 하였습니다.
그렇지만, 제목에 대한 설정을 위해서 Font만을 지정할 수 있도록 구현 사항이 변경 되었는데 미처 바꾸지 못한 것 같습니다.
하지만, 이 부분은 Font함수를 일반적으로 활용하는 것이 아닌, 위와 같은 modifier를 통해서 쉽게 구현할 수 있도록 하였으며, 이에 대한 네이밍을 명확하게 변경할 수 있도록 하였습니다.
[7338ecd](https://github.com/yagom-academy/ios-project-manager/pull/249/commits/7338ecdf3f7d94b4623de3fd8ab7abf2be5adfd1)

2023-01-25 02:15 UTC, leegyoungmin commented on ProjectManager/ProjectManager/BoardListView/BoardListComponents.swift
> +            project.date << Int(Date().convertDate().timeIntervalSince1970) ? .red : .black
그린이 말씀 해주신 것 처럼 비트 연산자가 존재하지만, 명확하게 이전의 날짜 라는 것을 표기하기 위해서 다음과 같은 연산기호를 활용하였습니다. 하지만, 로직적으로 잘못된 부분이 존재했으며, 연산 기호의 모호함으로 인해서 Int 타입을 통해서 구현한 부분을 Date와 String을 통해서 비교 연산을 하도록 수정하였습니다.

`timeIntervalSince1970`을 통한 Int 타입의 데이터를 구현하는 방법이 유일한 날짜를 비교할 수 있는 방법이라고 생각했습니다.
하지만, Date타입은 이미 Equatable을 채택한 타입이였으며, 이를 formatting 하여 문자열로 변경하는 방법 또한, Equatable과 Comparable 프로토콜을 채택하였기 때문에 비교 연산이 가능했습니다.

[438f034](https://github.com/yagom-academy/ios-project-manager/pull/249/commits/438f03479218ac1d4fe658ba420c065b1d9bcdce)
[14c347b](https://github.com/yagom-academy/ios-project-manager/pull/249/commits/14c347bf07540fa6472c57ce6ceac2825511e732)

2023-01-25 02:26 UTC, leegyoungmin commented on ProjectManager/ProjectManager/SheetCoordinator/NavigationBarView.swift
> +          Spacer()
`ZStack`은 기본적으로 가운데 정렬이며, 겹겹히 쌓이는 뷰기 때문에 Spacer가 필요하지 않았습니다.
하지만, Custom한 NavigationBar를 구성하는 과정에서 StatusBar의 영역을 버그로 착각하여서 Zstack을 활용하여서 해결하려고 했었고, 이로 인해서 불필요한 코드가 작성되었다고 생각했습니다.
그래서 `HStack`을 통해서 구현할 수 있도록 변경하였습니다.
[e75f376](https://github.com/yagom-academy/ios-project-manager/pull/249/commits/e75f37623d6bec3486ef916772e2c42eae0b64f4)

2023-01-25 02:32 UTC, leegyoungmin commented on ProjectManager/ProjectManager/SheetCoordinator/NavigationBarView.swift
> +        .padding([.vertical, .trailing])
https://github.com/yagom-academy/ios-project-manager/pull/249#discussion_r1086147299
해당 코멘트에서 Zstack에 대한 답변 드렸습니다.
ZStack과 Overlay를 통해서 사용자에게 보여지는 뷰는 동일할 수 있습니다. 하지만, 내부적으로 큰 차이가 있다는 것을 공부하게 되었습니다. ZStack은 자식 뷰들이 Z축을 기준으로 중첩되도록 하는 뷰이고, overlay는 현재 뷰에 secondary View를 overlay하는 modifier입니다. 이들의 차이점은 다음과 같습니다. ZStack 같은 경우는 자식 뷰들이 서로에 대해서 독립적이게 되는 것입니다. 또한, ZStack에 frame을 정해주지 않으면, 가장 큰 자식 뷰를 기준으로 ZStack의 크기가 결정되게 됩니다. 하지만, overlay는 부모 뷰에 종속이 되게 되면서, 부모 뷰의 좌표 공간안에서 존재하게 됩니다.

2023-01-25 02:54 UTC, leegyoungmin commented on ProjectManager/ProjectManager/SheetCoordinator/SheetCore.swift
> +        state.detailState = DetailState(title: "", description: "", editMode: false)
음... 그린이 말씀 해주신 것처럼 Inner Action을 추가하여서 세부적인 확장성을 가지고 갈 수 있다고 생각하였습니다.
또한, concatenate를 통해서 두개의 InnerAction을 조합하여서 활용할 수 있는 장점을 활용할 수 있다고 생각하였습니다.
[a72c3fa](https://github.com/yagom-academy/ios-project-manager/pull/249/commits/a72c3fae9c6aa63d77d617ddee53afadd3cb7443)

2023-01-25 03:01 UTC, leegyoungmin commented on ProjectManager/ProjectManager/SheetCoordinator/SheetCore.swift
> +  case detailAction(DetailAction)
오 저도 Child Action이 User Action이나 Inner Action으로 볼 수 없을 것 같다는 부분에서 공감했습니다.
그린이 말씀 해주신 방법 처럼 Child 영역을 구분지을 수 있도록 했습니다.
[4af7dc1](https://github.com/yagom-academy/ios-project-manager/pull/249/commits/4af7dc121baa41953e61e4d27039073cb073c396)

2023-01-25 04:12 UTC, leegyoungmin commented on ProjectManager/StoreTests/ListStoreTest.swift
> +@MainActor
Swift의 async 함수는 일반적으로 위치를 정해주지 않으면, 기본적으로 백그라운드 쓰레드에서 실행되게 됩니다. 다음과 같은 상황에서 suspend 후 돌아오는 쓰레드는 백그라운드 쓰레드 일 것입니다. 이를 변경하기 위해서는 명시적으로 MainThread에서 수행할 수 있도록 하여야 합니다. 하지만, MainActor를 활용하게 되면, Suspend된 후 돌아왔을 때, 자동적으로 MainActor에서 동작하도록 할 수 있습니다.

이부분에 대해서 공부를 해도 잘 모르는 부분이 있는 것 같네요. 혹시 틀린 부분이 있거나, 부족한 부분이 있으면 말씀해주세요 ㅜㅜ

2023-01-25 05:32 UTC, leegyoungmin commented on ProjectManager/StoreTests/NavigateStoreTest.swift
> +final class NavigateStoreTest: XCTestCase {
해당 테스트는 통과 되지 않았으며, 실제 프로젝트 코드 변경으로 인해서 추가적으로 새로운 테스트 코드를 구성하고, 테스트 코드에 맞춰서 리팩토링을 진행하였습니다.

[9306265](https://github.com/yagom-academy/ios-project-manager/pull/249/commits/93062650e9c8b1f0331267062fe683e124db08e7)
[2db11d6](https://github.com/yagom-academy/ios-project-manager/pull/249/commits/2db11d6560961ad9429f094f7e85cc2236b4cad9)

2023-01-25 05:33 UTC, leegyoungmin commented on ProjectManager/ProjectManager/AppView/AppCore.swift
> +  case _movingDone(Project)
해당 액션을 외부에서 컨트롤할 때, 내부액션이라는 것을 알게 하기 위해서 사용하였습니다.

2023-01-25 05:35 UTC, leegyoungmin commented on ProjectManager/ProjectManager/AppView/AppCore.swift
> +
개인적으로 지키는 컨벤션 중, 한 행의 코드를 100자 이내로 한다는 컨벤션을 지키기 위해서 인자마다 개행을 하도록 하였습니다.

2023-01-25 10:45 UTC, leegyoungmin commented on ProjectManager/ProjectManager/DetailView/DetailViewCore.swift
> +}.debug()
[9018e1b](https://github.com/yagom-academy/ios-project-manager/pull/249/commits/9018e1bfd6a0b69e6b5c18c7e81e31a1dab3645e)
이곳에서 삭제 했습니다.

2023-01-25 10:49 UTC, leegyoungmin commented on ProjectManager/ProjectManager/DetailView/DetailViewCore.swift
> +  case _didChangeDeadLine(Date)
다른 부분이 있는데 미처 파악하지 못한 것 같습니다. 
[fb3c3e7](https://github.com/yagom-academy/ios-project-manager/pull/249/commits/fb3c3e7cf79d644018be8fd42b36e1b2658feb9e)
이곳에서 수정하였습니다.
다음 부터 주의하겠습니다.

2023-01-25 10:53 UTC, leegyoungmin commented on ProjectManager/ProjectManager/DetailView/DetailView.swift
> +  func body(content: Content) -> some View {
some 이라는 키워드는 Opaque Type으로써 모호하다는 의미를 가지고 있습니다. 특정한 타입을 반환하는 것이 아니라 프로토콜을 반환하거나, 프로토콜을 준수하고 있는 타입을 반환시키기 위해서 사용합니다.
다음과 같은 경우는 View라는 프로토콜을 준수하는 뷰를 반환하도록 하였고, 이를 반환시킨 이유는 return이후에 나오는 뷰가 변경될 때 마다, 지속적으로 반환 타입을 변경 시켜주어야 하기 때문입니다.

2023-01-25 10:55 UTC, leegyoungmin commented on ProjectManager/ProjectManager/DetailView/DetailViewCore.swift
> +//  DetailViewStore.swift
[a9c06e9](https://github.com/yagom-academy/ios-project-manager/pull/249/commits/a9c06e9772480ad8739edd1dfaa6775f75ef72df)
이곳에서 변경하였습니다

2023-01-26 05:04 UTC, leegyoungmin commented on ProjectManager/ProjectManager/BoardListView/Views/TodoBoardListView.swift
> +                  Text("없어짐")
해당 오류는 apply를 하는 경우에 selectedState를 지우는 액션이 발동되고, 이로 인해서 ifletStore의 State가 nil이 되면서 화면이 없어지게 되었습니다.
해당 오류를 해결하기 위해서 DetailState의 id를 동일하게 해서 State에 대해서 없어질 수 없도록 하였습니다.

2023-01-26 05:05 UTC, leegyoungmin commented on ProjectManager/ProjectManager/BoardListView/Views/DoingBoardListView.swift
> +struct DoingBoardListView: View {
한개의 뷰와 State로 변경하고 AppCore에서의 액션을 따로 구현하여서 각각 어떤 타입의 액션으로 들어오는 지 확인할 수 있도록 구현하였습니다.

2023-01-26 05:06 UTC, leegyoungmin commented on ProjectManager/ProjectManager/DetailView/DetailView.swift
> +        .navigationTitle("TODO")
DetailState의 프로퍼티를 추가하여서 각각의 DetailView에 각각의 State를 나올 수 있도록 하였습니다.

2023-01-26 05:07 UTC, leegyoungmin commented on ProjectManager/ProjectManager/DetailView/DetailViewCore.swift
> +  let id: UUID = UUID()
sheet의 item 인자를 받는 데이터를 활용하기 위해서 identifiable을 채택하였으며, 또한, UUID 프로퍼티를 받는 이유는 해당 Project의 id를 할당하여서 삭제와 이동 액션을 더 잘 구분하기 위해서 구현하였습니다.

2023-01-26 05:51 UTC, GREENOVER commented on ProjectManager/ProjectManager/AppView/AppCore.swift
> +
@leegyoungmin 
아하 제가 궁금했던건 38번째 빈 라인의 개행이였습니다🙋🏻

2023-01-26 06:12 UTC, GREENOVER approved these changes
@leegyoungmin 
리팩토링 하느라 고생 많으셨습니다 미니!!
전체적으로 더 확실히 보완되고 코드 가독성 및 중복 개선도 잘되었네요👍
기존 코멘트에 대해 한곳 답변 드린 부분도 있고 새롭게 코멘트를 드린 부분도 있습니다ㅎㅎ
이번 스텝은 여기서 마무리 해도 될것 같아 어프로브 및 머지하겠습니다!
다음 스텝 진행 시 해당 코멘트들 확인해보시면 좋을것 같아요🙌🙌

2023-01-26 06:12 UTC, GREENOVER commented on ProjectManager/ProjectManager/BoardListView/BoardListState.swift
> +  case didDelete(IndexSet)
실제 기존에 있던 삭제 액션에 대한 처리가 사라진것 같아요🥲

2023-01-26 06:12 UTC, GREENOVER commented on ProjectManager/ProjectManager/AppView/AppCore.swift
> +  case sheetAction(SheetAction)
pullback해오는 액션이라면 ChildAction으로 볼 수 있지 않을까도 싶습니다🙋🏻
답이 있는건 아니지만 해당 액션을 유저 액션이라 본다면 하위 child action들도 어떻게 보면 user action으로 인한 액션으로 간주 될 수 있지 않을까요!?

2023-01-26 06:12 UTC, GREENOVER commented on ProjectManager/ProjectManager/BoardListView/BoardListComponents.swift
> +            project.date.onlyDate() <= Date().onlyDate() ? .red : .black
해당 처리를 View보다는 다른 extension 혹은 코어에서 해주면 어떨까요?
View에서 계산과 같은 비지니스 로직은 없으면 좋을것 같아요🙋🏻

2023-01-26 06:12 UTC, GREENOVER commented on ProjectManager/ProjectManager/BoardListView/BoardListState.swift
> +
17번째 라인은 크게 불필요한 개행일것 같습니다🙋🏻

2023-01-26 06:12 UTC, GREENOVER commented on ProjectManager/ProjectManager/BoardListView/BoardListState.swift
> +    switch action {
액션의  구현 순서가 위에서 정의한 순서와 맞으면 조금 더 가독성이 좋을것 같은데 어떻게 생각하시나요~?

2023-01-26 06:12 UTC, GREENOVER commented on ProjectManager/StoreTests/ListStoreTest.swift
> +    )
기존 코드가 리팩토링되면서 여기서도 변경되어야 할것 같습니다🙋🏻

2023-01-26 06:12 UTC, GREENOVER commented on ProjectManager/StoreTests/NavigateStoreTest.swift
> +  func testNavigate() async {
테스트 코드에서 메서드명이 어떤곳은 한글+영어 / 영어만 으로 통일성이 조금 떨어지는것 같은데 한쪽으로 통일성 있게 가져가면 더 좋을것 같아요🙋🏻

2023-01-26 06:12 UTC, merged