프로젝트 매니저 [STEP 2-1] Baem
yagom-academy/ios-project-manager pull request #251
Opened 2023-01-20 10:45 UTC by Dylan-yoon

안녕하세요, 도미닉 @AppleCEO 
PR 너무 늦어버렸네요.. 
처음 혼자하다보니 이런저런 방황도 많이하고, 막히는 부분도 많았던 것 같습니다.

현재 MVVM을 적용하기에는 무리가 있다고 생각해서 MVC 로 구현을 했고
이번 PR Merge후 MVVM으로 리팩토링 하는 방향으로 진행하겠습니다.

## 고민 및 조언을 얻고 싶은 부분
### TableView를 하나의 뷰에서 3개를 사용 할 때

```swift
    private let todoTableView = CustomTableView(title: "TODO")
    private let doingTableView = CustomTableView(title: "DOING")
    private let doneTableView = CustomTableView(title: "DONE")
```

위와 같이 선언을 해주었습니다.
제 코드에서는 
Coredata 에서 fetch 해 온 데이터들을 각각 배열에 담아주기 위해
각 tableview의 data 프로퍼티들을 만들어 주었습니다.

```swift
    private var todoData = [TodoModel]()
    private var doingData = [TodoModel]()
    private var doneData = [TodoModel]()
```

이렇게 되면서 많은 부분에서 분기처리를 하게 됩니다.
어떤 방법으로 처리를 해야 더 좋은 방향이 될지 고민이 되어 질문드립니다!

### Navigation
아래 GIF와 같이
`TODO TableView` 를 drag 했을 때에만 NavigationController 변화가 생기는데, 
어느부분을 놓치고 있는지 찾지 못했습니다.
`DOING TableView`, `DONE TableView` 에서는 드래그를 해도 navigationController에 변화가 생기지 않습니다.

![](https://i.imgur.com/fARAtN3.gif)

### MVC -> MVVM 리펙토링

이번 PR이 Merge된 후 MVVM으로 리펙토링을 진행 하려합니다.
MVVM 아키텍쳐를 적용하기 보단 다른 부족한 부분들을 보완해야 한다면, 어떤 방향으로 추후 프로젝트를 진행할지 조언 부탁드리겠습니다.

2023-01-21 12:28 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다.
@Dylan-yoon 고생하셨습니다.
몇가지 문법적인 부분 코멘트 남겼습니다.
확인해주시면 아키텍처 적인 부분들도 조금 더 파악해서 리뷰 드려보도록 할게요!

## 고민 및 조언을 얻고 싶은 부분
### ✅ TableView를 하나의 뷰에서 3개를 사용 할 때
-> 각 테이블 뷰 DataSource 를 다른 객체로 만들어서 그 객체에게 위임하는 식의 방식으로 분기 처리를 제거할 수 있습니다!

### ✅ Navigation
-> 이 부분은 내일 조금 더 제가 살펴보고 답변드리겠습니다~ 

### ✅ MVC -> MVVM 리펙토링
-> MVVM 은 저도 이번에 현업에서 처음 사용하게 될 것 같습니다. 요즘에는 대부분 사용하는 기술이긴 하지만 먼저 앱에 더 익숙해질 필요도 있을 것 같습니다. 우선 제가 코멘트 드린 부분들 확인해보고 개선해보면 더 좋을 것 같습니다.

2023-01-21 12:28 UTC, AppleCEO commented on ProjectManager/ProjectManager/DTO/State.swift
> +    case todo = 0
여기 0이 없다면 어떻게 동작할까요?

2023-01-21 12:28 UTC, AppleCEO commented on ProjectManager/ProjectManager/Extension/UIButton.swift
> +//  UIButton.swift
파일명으로 UIButton 말고 다른 더 적절한 이름이 있을까요? 저의 노심초사일 수 있겠지만 UIKit의 기존 UIButton 파일과 똑같은 것이 좋게 생각이 들지는 않습니다. Extension 이라는 폴더 안에 있긴 하지만요.

2023-01-21 12:28 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/CoreDataManger.swift
> +    func fetch() ->  Result<[TodoModel], CoreDataError> {
무엇을 fetch 하는지 이름이 더 명확하면 좋겠네요! 👍

2023-01-21 12:28 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/CoreDataManger.swift
> +        let context = appDelegate?.persistentContainer.viewContext
다른 함수들에서도 공통으로 이 두 줄이 보이는군요. 공통된 코드의 위치를 변경해서 반복을 제거해 볼 수 있을까요?

2023-01-21 12:28 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/Error.swift
> +enum CoreDataError: Error {
조금 더 긴 파일명이 더 좋은 경우가 많습니다.
여기도 Error.swift 라고 하면 어떤 Error 인지 네트워크 통신의 에러인지 사용자의 에러인지 불명확한 것 같습니다.
더 좋은 파일명을 생각해 볼 수 있을까요?
CoreDataError 도 코어데이터 자체의 에러인지 조금 짧은 것 같습니다. 상세한 설명을 앞에 붙여볼 수 있을까요?

2023-01-21 12:28 UTC, AppleCEO commented on ProjectManager/ProjectManager/SceneDelegate.swift
> -//        guard let _ = (scene as? UIWindowScene) else { return }
사용하지 않은 코드를 제거한 것 좋습니다! 💯

2023-01-21 12:28 UTC, AppleCEO commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +            switch State(rawValue: $0.state) {
아직 $0 을 사용하지 않는 것을 권합니다.
단축해서 편하게 사용할 수 있는데 원래 구조가 어떤지 저 위치에 무엇이 들어가는지 익숙해지고 현업에서 사용하면서 약속을 정해서 조금씩 사용해보시면 좋을 것 같아요.
$0을 사용하지 않고 기본형으로 어떻게 작성하는지 변경해 볼 수 있을까요?

2023-01-21 12:28 UTC, AppleCEO commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +        }
guard let 줄이 너무 복잡하네요 ㅎㅎ
```swift
let dequeuedTableViewHeaderFooterView = tableView.dequeueReusableHeaderFooterView(withIdentifier: "CustomHeaderView")
guard let customHeaderView = dequeuedTableViewHeaderFooterView as? CustomHeaderView else {
  return UIView()
}        
```
이런 방식으로 할당을 먼저 하고 guard let 을 사용하면 어떨까요?

2023-01-21 12:28 UTC, AppleCEO commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +        }
이 코드는 함수로 빼낼 수 있을 것 같은데 빼보면 어떨까요?

2023-01-21 12:28 UTC, AppleCEO commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +
위에 함수로 빼기로 요청드린 것과 비슷한 코드네요~
함수로 빼내어서 이 쪽에도 활용해보면 좋겠군요!

2023-01-21 12:28 UTC, AppleCEO commented on ProjectManager/ProjectManager/View/ModalViewContoller.swift
> +    private let datePicker: UIDatePicker = {
어떤 날짜가 저장되는 변수명인지 더 상세하면 좋겠네요.
writedDatePicker 작성한 날짜라면 이런 변수명도 가능하겠죠.
이런 식으로 작성하면 다른 뷰컨트롤러나 다른 화면에서 같은 DatePicker 를 사용하더라도 구분이 가능해서 좋다고 생각해요. 🔢

2023-01-21 12:28 UTC, AppleCEO commented on ProjectManager/ProjectManager/View/ModalViewContoller.swift
> +extension ModalViewContoller {
아래 함수들을 Extension 으로 빼낸 이유가 있을까요>?

2023-01-21 12:28 UTC, AppleCEO commented on ProjectManager/ProjectManager/View/ModalViewContoller.swift
> +    @objc private func tapDoneButton1() {
여기 함수명 뒤에 1이 붙은 이유가 있을까요?
함수명에 1,2,3,4 등의 숫자를 붙이는 것을 lint 등으로 막는 회사들도 있다고 하는데 붙이신 이유가 궁금합니다~

2023-01-21 22:30 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/DTO/State.swift
> +    case todo = 0
기본적으로 Int의 RawValue는 0으로 시작되고,
명시해주면 그 다음 케이스부터는 명시한 숫자 +1 씩 늘어납니다!
명시적으로 보여주기 위해 기입해 주었지만, 기본값이 0부터 시작하기 떄문에 삭제하도록 하겠습니다 :)

2023-01-21 22:39 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/Extension/UIButton.swift
> +//  UIButton.swift
이 부분은 아직 어떤 방식으로 하는 것이 좋을지 잘 모르겠습니다. ㅠㅠ
다른분들과 팀으로 진행하면서
`UIButton+Extension`, `UIButton+` 
이런 방식으로 여러곳에서의 확장성을 고려해서 따로 네이밍을 생각해보지 않았습니다.
도미닉의 경우 어떤식으로 관리하시는지 조언부탁드립니다!

2023-01-21 22:46 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/Model/CoreDataManger.swift
> +    func fetch() ->  Result<[TodoModel], CoreDataError> {
네이밍에 신경을 안쓴부분인것 같네요.. ㅠ
데이터를 받아온다는 부분에서 fetchData로 변경했습니다!

2023-01-21 22:50 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/SceneDelegate.swift
> -//        guard let _ = (scene as? UIWindowScene) else { return }
감사합니다! ^&^

2023-01-21 22:53 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/View/ModalViewContoller.swift
> +    @objc private func tapDoneButton1() {
create와 edit 두가지상태를 init으로 data가 있을때와 없을때를 구분지어 구현했습니다.
그러다보니 총4개의 objc메서드들이 구현되었고,
이후 right, left 버튼을 각각 2->1개로 통합하다보니 수정중에 오타를 내었습니다.
확인을 미쳐하지 못해 수정했습니다.😭

2023-01-21 22:55 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/View/ModalViewContoller.swift
> +extension ModalViewContoller {
좀 더 정리하고자 Extension 으로 구분지어주려고 했습니다.
굳이 필요없는 부분일까요?

2023-01-23 07:56 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/Model/CoreDataManger.swift
> +        let context = appDelegate?.persistentContainer.viewContext
함수 밖에서 사용하기 위해 context는 아래의 경우 처럼 lazy를 활용 할 수 있지만,
```swift
    private let appDelegate = UIApplication.shared.delegate as? AppDelegate
    private lazy var context = appDelegate?.persistentContainer.viewContext
```

lazy키워드를 사용한다면 생성될 수도 있고 아닐 수도 있는데, 현재는 무조건 생성이 되어야 하기 때문에 lazy를 사용함에 있어 좋지못하다고 판단했습니다.
이 경우 도미닉의 생각은 어떠신가요?
또한 lazy키워드를 사용하지 않는게 좋다고 듣기도 했는데 이 부분은 취향 차이일까요?

추가적으로 CoreDataManager의 경우 자주 사용하기 때문에 Sigleton으로 다시 구현했습니다!

2023-01-23 08:45 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +            switch State(rawValue: $0.state) {
모든 부분에서 의미를 전달 할 수 있도록 변경했습니다!
https://github.com/yagom-academy/ios-project-manager/pull/251/commits/8eb52b19bbceee9a98d53ea7adfa2b61a61e8e0e

2023-01-23 08:51 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +        }
오 이렇게 생각을 안해봤네요.. 
네이밍도 어떡게해야하지 고민했었는데 `dequeued` 를 사용하는 것도 굉장히 인상깊네요!
어떻게 줄여야 할 지 고민했었는데, 감사합니다!

2023-01-23 09:13 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/View/ModalViewContoller.swift
> +    private let datePicker: UIDatePicker = {
deadlineDataPicker 라는 변수명으로 변경했습니다!

또한 textField, textView 역시 상세하게 변경했습니다!😀
` 다른 화면에서 같은 DatePicker 를 사용하더라도 구분이 가능해서 좋다고 생각해요. ` 이부분을 생각을 못했던것 같습니다. 감사합니다!!

2023-01-23 09:27 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +        }
`func saveData(of tableView: UITableView, to indexPathRow: Int) -> TodoModel?`
로 만들어주어 빼보았습니다!

2023-01-23 09:31 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/View/MainViewController.swift
> +
```swift
// MARK: - TableView Business Logic
extension MainViewController {
    func saveData(of tableView: UITableView, to indexPathRow: Int) -> TodoModel? {
        switch tableView {
        case todoTableView:
            return todoData[indexPathRow]
        case doingTableView:
            return doingData[indexPathRow]
        case doneTableView:
            return doneData[indexPathRow]
        default:
            return nil
        }
    }
}
```
위와같이 따로 빼주어서, 같은 로직을 처리했습니다.
다시 집중해서 봤어야 했는데, 감사합니다!

2023-01-23 09:58 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/Model/Error.swift
> +enum CoreDataError: Error {
Error.swift 라고 했던 이유는
다른 Error들도 들어오게 된다면 이 파일에서 관리해주려고 했습니다.
하지만 localization이라던지 다른 기능들을 추가하면 분리해주는게 맞는것 같네요!

생각해본 네이밍은 CoreDataCURDError라고 생각했는데..
도미닉의 경우는 어떤식으로 관리해주시는지 궁금합니다!

2023-01-23 12:33 UTC, AppleCEO commented on ProjectManager/ProjectManager/Extension/UIButton.swift
> +//  UIButton.swift
UIButton+Extension 이런 방식의 네이밍 자주 사용하는 것 같아요.

2023-01-23 12:34 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/CoreDataManger.swift
> +        let context = appDelegate?.persistentContainer.viewContext
아하... lazy 를 활용해야만 하는군요. 싱글톤으로 풀은 것 괜찮은 것 같습니다~

2023-01-23 12:35 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/Error.swift
> +enum CoreDataError: Error {
ㅎㅎ 저는 보통 프로젝트명에서 힌트를 많이 얻는 것 같습니다.
Error 보다는 ProjectManagerError 라고 하면 조금 더 명확할 것 같아요~

2023-01-23 12:38 UTC, AppleCEO commented on ProjectManager/ProjectManager/View/ModalViewContoller.swift
> +extension ModalViewContoller {
정리하려고 한 노력은 좋은 것 같습니다. 그렇다면 extension 과 함께 사용을 자주 하는 것이 있는데 그것이 어떤 것인지 짐작 가실까요?
그 것과 함께 정리하는 방법도 있을 것 같습니다!

2023-01-23 13:41 UTC, AppleCEO commented
코멘트 주신 내용들 확인했습니다. 고생하셨습니다!
일전에 질문주신 첫 번째 테이블 뷰를 스크롤 했을 때만 네비게이션뷰의 색이 바뀌는 것은 간단히 찾아지지는 않네요 ㅜ
한가지 말씀드리고 싶은 것은 코드를 작성한 자신이 프로그램과 코드에 대해서 제일 잘 알아야합니다.
이런 식으로 구성했는데 개선할 점이 있나요? 정도의 질문은 괜찮겠지만 자신이 작성한 프로그램이 왜 이렇게 동작하는지 다른 사람에게 질문하는 것은 조금 어색한 것 같다고 생각했습니다.
MainViewController 가 300줄이 넘어가서 너무 길어진 것 같습니다.
줄일 수 있으면 좋겠습니다~

2023-01-23 14:16 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/Extension/UIButton.swift
> +//  UIButton.swift
감사합니다!

2023-01-23 14:17 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/Model/CoreDataManger.swift
> +        let context = appDelegate?.persistentContainer.viewContext
appDelegate 상수는 전역적으로 사용하지만 context는 함수 내부에서 바인딩 하여 사용하도록 했습니다!

2023-01-23 14:28 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/Model/Error.swift
> +enum CoreDataError: Error {
현재 coreDataManager 에서만 사용중이기 때문에,
추후 변경이 되더라도 파일명도 일단 일치시키는 것이 좋은것 같네요!
변경했습니다.!

2023-01-23 14:48 UTC, Dylan-yoon commented on ProjectManager/ProjectManager/View/ModalViewContoller.swift
> +extension ModalViewContoller {
프로토콜을 통해 Extension을 통한 방법이라고 생각됩니다.
아직 pop로  구현해보는것이 어색해서 아직 사용해보지는 않았습니다.ㅠ

2023-01-23 14:49 UTC, Dylan-yoon commented
> 코멘트 주신 내용들 확인했습니다. 고생하셨습니다!
> 일전에 질문주신 첫 번째 테이블 뷰를 스크롤 했을 때만 네비게이션뷰의 색이 바뀌는 것은 간단히 찾아지지는 않네요 ㅜ
> 한가지 말씀드리고 싶은 것은 코드를 작성한 자신이 프로그램과 코드에 대해서 제일 잘 알아야합니다.
> 이런 식으로 구성했는데 개선할 점이 있나요? 정도의 질문은 괜찮겠지만 자신이 작성한 프로그램이 왜 이렇게 동작하는지 다른 사람에게 질문하는 것은 조금 어색한 것 같다고 생각했습니다.
> MainViewController 가 300줄이 넘어가서 너무 길어진 것 같습니다.
> 줄일 수 있으면 좋겠습니다~

제가 너무 안일하게 잘 알아보지 않고 질문 부터 드린것같네요, 죄송합니다.ㅠ
제 코드에 대해 누구보다 잘 알고 있도록 하겠습니다.

또한 코드 길이도 좀더 줄였습니다. 감사합니다!

2023-01-24 06:09 UTC, AppleCEO commented
여유되시면 코멘트에서 남겼지만 각 테이블 뷰의 Delegate, Datasource 를 다른 객체에게 할당해서 if else 로 되어있는 분기처리를 지워봐도 좋을 것 같네요!
어려운 스텝이었는데 너무나 잘 구현하신 것 같습니다.
추가하시지 않으실거면 머지해드려도 될 것 같네요~
고생 많으셨어요.

2023-01-26 04:37 UTC, Dylan-yoon commented
> 여유되시면 코멘트에서 남겼지만 각 테이블 뷰의 Delegate, Datasource 를 다른 객체에게 할당해서 if else 로 되어있는 분기처리를 지워봐도 좋을 것 같네요!
> 어려운 스텝이었는데 너무나 잘 구현하신 것 같습니다.
> 추가하시지 않으실거면 머지해드려도 될 것 같네요~
> 고생 많으셨어요.

테이블 뷰에 모델데이터를 추가해서 분기처리를 없애주었습니다!!!
이부분을 추가적으로 리펙토링하였는데,
테이블 뷰 자체에서 모델 데이터를 가지고 있어도 괜찮을까 라는 고민이 생겼는데
도미닉의 의견을 듣고싶습니다!

2023-01-26 09:35 UTC, AppleCEO commented
내일까지 확인 후 코멘트 드릴게요. 고생 많으셨습니다! 이 과정 한번 해보면 좋더라고요. 제 영상도 한번 참고해주셔도 됩니다~
https://youtu.be/2I7cjhsmDNU

2023-01-26 12:55 UTC, Dylan-yoon commented
> 내일까지 확인 후 코멘트 드릴게요. 고생 많으셨습니다! 이 과정 한번 해보면 좋더라고요. 제 영상도 한번 참고해주셔도 됩니다~
> https://youtu.be/2I7cjhsmDNU

넵 감사합니다 !!!

2023-01-27 13:11 UTC, AppleCEO commented
@Dylan-yoon 고생하셨습니다!
테이블뷰를 별도로 빼낸 것 좋네요~
질문하셨던 모델 데이터가 테이블뷰에 있는 것보다는요. 
제 영상에서 보이는 것처럼 Datasource 를 self 로 할당하지 않고 다른 객체에 할당하는 식이 더 낫다고 생각합니다.
그렇게하면 MainViewController 의 역할과 책임이 많이 줄어들어서 더 좋아질 것 같아요.
여유 되시면 한번 시도해보셔도 좋을 것 같습니다.
3주동안 프로젝트 진행하느라 수고하셨습니다.

2023-01-28 08:28 UTC, Dylan-yoon commented
좋은 조언해주셔서 감사합니다.
이렇게 객체로 빼는것은 안해봐서 생각하는데 시간이 좀 걸린 것 같습니다.

마지막 질문이 될 것 같습니다.
지금 말씀해주신대로 객체로 분리해주었는데
delegate의 didSelectRowAt 에서 present 해주기 위해 아래와 같이 해주었습니다.

```swift
final class MainTableViewDelegate: NSObject, UITableViewDelegate, TableViewMethoding {
    
    var controller: UIViewController?
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        ...
        controller?.present(modalController, animated: true)
        ...
    }
}
```

```
final class MainViewController: UIViewController {
    ...
    private let tableViewDelegate = MainTableViewDelegate()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        ...
        
        configureLayout()
        ...
    }
}

extension MainViewController {
    private func configureLayout() {
        ...
        [todoTableView, doingTableView, doneTableView].forEach { tableView in
            tableView.delegate = tableViewDelegate
            tableView.dataSource = tableViewDataSource
            stackView.addArrangedSubview(tableView)
        }
        
        tableViewDelegate.controller = self
        ...
    }
}
```

위의 코드와 같이 MainViewContoller에서 tableViewDelegate의 controller 라는 UIViewController 타입의 프로퍼티를 즉 self 를 전달해 주어서 didSelectRowAt 에서 controller.present하여 모달을 띄어주고 있는데, 이렇게 띄워주는게 맞는 방향인지 잘 모르겠습니다..
정상적으로 작동은하지만 self를 넘겨주는것 자체가 찜찜하게 느껴져서 다른 방법이 있는지 궁금합니다.


추가로, saveData, countCell, swipeAction 세가지 함수가 반복적으로 사용되고 다른 객체를 만들어 사용하기보다 protocol의 extension을 사용해서 함수를 구현해주었는데 이부분에 대해 추가적으로 조언 부탁드리겠습니다.
감사합니다

2023-01-29 14:08 UTC, AppleCEO commented
위의 코드와 같이 MainViewContoller에서 tableViewDelegate의 controller 라는 UIViewController 타입의 프로퍼티를 즉 self 를 전달해 주어서 didSelectRowAt 에서 controller.present하여 모달을 띄어주고 있는데, 이렇게 띄워주는게 맞는 방향인지 잘 모르겠습니다..
정상적으로 작동은하지만 self를 넘겨주는것 자체가 찜찜하게 느껴져서 다른 방법이 있는지 궁금합니다.
-> 오.. 괜찮은 것 같아요. 말씀하신 것처럼 테이블뷰 델리게이터에서 뷰컨트롤러를 모르는 것이 더 좋은 방식은 맞다고 생각합니다. 하위 뷰에서 상위 뷰를 모르면 좋으니까요. 이걸 해결하기 위해서는 Notification Center 나 여러 다른 방법이 있을 것 같습니다. 차차 여러 도구들을 알게 되실 것이라고 생각합니다!

추가로, saveData, countCell, swipeAction 세가지 함수가 반복적으로 사용되고 다른 객체를 만들어 사용하기보다 protocol의 extension을 사용해서 함수를 구현해주었는데 이부분에 대해 추가적으로 조언 부탁드리겠습니다.
감사합니다
-> 좋은 방식이라고 생각합니다. 프로토콜을 사용하면 훨씬 체계적으로 코드를 정리할 수 있는 것 같습니다. 추가적으로 제가 extension 으로 메소드들을 빼낸 것들을 어색하다고 말씀드렸었는데요. 그 이유는 extension 은 객체 안에서 선언하기에는 중요도가 덜한 부가적인 메소드들이거나  프로토콜을 채택하여 선언해야 하는 메소드들을 모아놓는 용도로 많이 사용하는데요. configureLayout, fetchData 처럼 중요한 메소드들이 빠져있어서 그렇게 생각했습니다. 이런 내용은 참고해주셔도 좋을 것 같습니다~

2023-02-01 10:06 UTC, merged