프로젝트 매니저 [STEP 2] 애쉬
yagom-academy/ios-project-manager pull request #252
Opened 2023-01-20 11:45 UTC by ash-youu

안녕하세요 엘림~(@lina0322)
프로젝트 매니저의 step2를 구현하게 되어 PR 보내드립니다!
지금까지 사용해왔던 MVC 패턴을 사용했음에도.. 부족한 부분이 많은 것 같습니다.😭
아래에는 조언이 필요한 점을 적어두었습니다.
확인 부탁드리겠습니다!🙂

---

### 🖌 코드 개요
- Model
  - TodoModel: 추후 DB 구현 시 데이터와 매핑될 모델 타입
  
- View
  - TableView: ListTableView의 헤더, 테이블뷰, 셀 파일
  - TodoItemView: 아이템을 추가하거나 편집할 때 보여지는 modal view
  
- Controller
  - MockDataManager: 로컬, 리모트 DB 구현 전으로 MockModel 인스턴스와 메서드를 구현한 타입
  - ListViewController: DiffableDataSource를 사용하는 3개의 테이블뷰를 가진 메인 뷰컨트롤러
  - AddTodoViewController: 새로운 Todo 항목을 추가할 때의 뷰컨트롤러
  - EditTodoViewController: 기존에 존재하는 Todo 항목을 수정할 때의 뷰컨트롤러
---

### 🙋‍♀️ 조언이 필요한 점
#### 테이블뷰의 헤더를 업데이트하는 방법에 대한 문제
- 현재 메인뷰의 테이블뷰는 `DiffableDataSource`를 사용하고, 헤더는 `UITableViewDelegate` 메서드인 `func tableView(_:, viewForHeaderInSection:) -> UIView?` 를 통해 구현되고 있습니다.
- 이 때, 테이블뷰 셀의 데이터는 snapshot을 `apply()` 하면서 자동으로 업데이트되고 있는데 헤더는 `reloadData()` 를 호출하지 않으면 업데이트가 되지 않는 문제가 있습니다.
- 간단히 snapshot을 `apply()`하는 것만으로 UI를 업데이트하고, 자연스러운 애니메이션을 제공받는 것이 `DiffableDataSource`의 장점이라고 생각하는데, 현재는 `apply()`도 하고 reload까지 하니 `DiffableDataSource` 사용의 장점이 없고, 매번 두 메서드를 호출하니 가독성도 떨어진다고 생각했습니다.
- 헤더를 다른 방법으로 제공하는 방법이 있을지 알아보았지만 적절한 방법을 찾기 어려웠던 것 같습니다. 이 문제를 해결할 방법이 있을지 조언을 얻고싶습니다!🥹

#### AddTodoVC와 EditTodoVC의 delegate 패턴에 대한 고민
- 기존에는 로컬 DB 구현 전이니 `ListViewController`에서 데이터의 CRUD를 처리하는 것으로 생각했었습니다.
- 그래서 데이터의 추가와 편집을 delegate 패턴을 통해 `ListViewController` 에서 처리하기 위해 구현했습니다.
- 하지만, `MockDataManager` 타입을 만들고 나니 delegate가 `ListViewController`의 뷰를 업데이트하기 위한 용도가 된 것 같아 delegate보다는 completion handler처럼 사용하고 있다는 생각이 들었습니다.
- 실제 Data Manager 타입을 구현하게 되면 로직이 달라질 수 있겠지만, 이런 경우에는 DB의 변화를 추적하고 UI를 업데이트하기 위해 어떤 방법을 사용하는 게 더 좋았을지 의문이 들어 엘림의 생각은 어떠신지 궁금합니다!

#### 셀의 높이가 자동으로 조정되지 않는 문제
- 현재 TableView의 rowHeight를 `UITableView.automaticDimension`으로 설정해두고, `estimatedRowHeight` 높이도 지정을 해두었지만 앱을 처음 켰을 때 / 기존의 셀 데이터를 수정했을 때(edit 버튼을 한번 눌렀을 때) 높이가 자동으로 조정되지 않는 문제가 있었습니다.
- 스크롤 했을 때, edit 버튼을 두번 눌렀을 때만 셀의 높이가 컨텐츠에 맞게 조정되는 것으로 보아 셀이 재사용될 때만 높이가 자동으로 조절되는 것이라고 추측했습니다. 그래서 아래의 방법들을 시도해보았으나.. 전부 실패했습니다. 😂 제가 놓친 부분이 있는지 궁금합니다!
  - viewWillAppear에서 `view.layoutIfNeeded` 혹은 tableView의 `reloadData()`를 호출
  - 각 tableView의 rowHeight와 estimatedRowHeight를 automaticDimension으로 설정 혹은 delegate에서 관련 메서드를 override해 automaticDimension으로 설정
  - cell의 contents를 설정하기 전후로 `tableView.beginUpdates`와 `tableView.endUpdates`호출

2023-01-23 17:10 UTC, lina0322 requested changes
애쉬, 여러가지로 고민이 많았네요! 고생하셨어요~
테스트하면서 이상해보이는 부분들이 있어서 이미지랑, gif 같이 첨부하면서 말씀드릴게요.

<img width="294" alt="스크린샷 2023-01-24 01 45 00" src="https://user-images.githubusercontent.com/49546979/214098274-fced68a9-cabd-4a31-a7ca-f5f2c8a8e59b.png">

> 설명이 세 줄 이상이면 세 줄 까지만 표시합니다.
설명이 세 줄 이하라면, 설명글의 높이에 맞게 셀의 높이가 맞춰집니다.

이 조건이 충족되지 않은거같아요~

---

<img width="272" alt="스크린샷 2023-01-24 01 46 30" src="https://user-images.githubusercontent.com/49546979/214098672-6b01eaa8-609b-4818-b5e4-64d8d9a5d13a.png">

셀 높이가 이상하게 잡히네요. 내부 제약을 다시 확인해주세요. 아래 셀이 새로 생기니까 위쪽 셀에 라벨 모양이 달라졌어요~
추가로 새로 생성한 메모의 날짜가 보이지 않습니다.

---

> Edit 버튼을 선택하면 수정할 수 있습니다.

이 문구에 대한 정의를 제대로 해야할거같아요. done이라는건 완료라는 뜻인데, 실제로 수정 화면에서 done을 누르면 아무 동작하지 않고 닫기고 있거든요. 다소 어색한 동작인것같은데, 이런 경우에는 기획자랑 상의를 한다거나 해서 스펙을 바꾸는게 좋을 수 있겠어요. done이기 때문에 실제로 수정을 하던지 아니면 cancel로 버튼 이름을 변경하는게 좋겠어요. 그리고 Edit버튼을 눌렀을때 창이 닫기는게 더 자연스럽지 않을까 생각이 듭니다. 이 부분은 ux를 생각하며 좀 더 고민해주세요~ 
(좀 다른 방법으로 디벨롭을 하자면, 처음에 화면이 떴을때는 우측이 cancel이고 아래는 편집을 할 수 없는 상태 -> 좌측 edit을 누르면 편집을 할 수 있는 상태가 되고, 좌측 edit이 done으로 변경된다. 이런 방법도 있겠어요)

--- 

![Uploading 스크린샷 2023-01-24 01.54.58.png…]()

> TODO와 DOING의 기한에 지난 날짜가 있으면 빨간색으로 표시합니다.

done에는 어떻게 되는게 올바른 표현일까요...? 전부 검은색이 맞지 않나 싶기도하고... 
어쨌든 지나지 않은 날짜가 빨간색은 좀 이상하네요. 제가 확인한 지금이 24일인데, 빨간색이라서요😅

---

![Jan-24-2023 02-00-26](https://user-images.githubusercontent.com/49546979/214102075-160f004f-b81c-4842-83c6-3220bdda10ec.gif)

순간 날짜라벨이 검은색으로 깜빡이네요~

---

애쉬가 남겨준 고민들은 대부분 지금 코멘트단 부분들 해결하면 같이 어느정도 해결이 될 것 같은데요. 그래도 이해 안가거나 설명이 더 필요한 부분, 더 궁금한 부분 있으면 디엠주세용~

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddTodoViewController.swift
> +    func addNewTodoItem(with item: TodoModel)
```suggestion
    func add(todo: TodoModel)
```
이런 네이밍도 가능하겠네요~

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddTodoViewController.swift
> +    }
viewController가 생성해주는 view를 사용하지 않고, 굳이 커스텀 뷰로 변경하는 이유가 있나요??

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddTodoViewController.swift
> +        delegate?.addNewTodoItem(with: newTodoItem)
delegate로 꼭 해야하는 부분인가요?? TodoItemView에 addNewTodoItem을 호출하면 될거같아서요👀

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/EditTodoViewController.swift
> +class EditTodoViewController: UIViewController {
AddTodoViewController와 거의 동일해보이는데요~ 중복된 코드들을 하나로 합칠 수 있는 방법은 없을까요?

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +        MockDataManager.shared.mockModels.filter { $0.status == .todo }
MockDataManager안에서 filter를 해서 제공하는게 더 올바를 것 같아요.
ex) `MockDataManager.shared.todoList`

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +    private lazy var doneDataSource: ListDataSource = configureDataSource(of: doneTableView)
lazy로 한 이유가 궁금합니다~

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +        view.backgroundColor = .white
viewDidLoad에서 직접적으로 하기보단 함수로 만들어주세요~

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +
어떤 의미를 가지고 있는 줄바꿈일까요?

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +        configureLayout()
set, configure, setup 등을 어떤 의미로 쓰고 계신가용?

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +    @objc func pressTableView(_ sender: UILongPressGestureRecognizer) {
pressTableViewCell이 더 맞지 않나용?👀

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Extension/NameSpace.swift
> +enum TodoError {
error는 여기에 있는 다른 값들과는 별개로 취급해야할것같네요~

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TableView/ListTableViewCell.swift
> +    static let identifier = ListTableViewValue.identifier
ListTableViewCell 이름 자체를 가져올 수 있는 방법은 없을까요?

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TableView/ListTableViewCell.swift
> +        fatalError("init(coder:) has not been implemented")
fatalError를 하는게 좋은 방법일지에 대해 고민해보는 시간을 가져봐도 좋을거같아요~

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TableView/ListTableViewCell.swift
> +        DispatchQueue.main.async { [weak self] in
weak self는 어떤 키워드인가요??

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TableView/ListTableView.swift
> +        register(ListHeaderView.self, forHeaderFooterViewReuseIdentifier: ListHeaderView.identifier)
함수로 분리 해주세요~

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Model/TodoModel.swift
> +    var status: TodoStatus = TodoStatus.todo
```suggestion
    var status: TodoStatus = .todo
```

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Model/TodoModel.swift
> +    let id: UUID = UUID()
identifiable 이라는 키워드가 있는데, 한번 알아보면 좋을거같네요

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TableView/ListHeaderView.swift
> +        label.layer.cornerRadius = 35 / 2
35 / 2는 어떤 값인가요??🙂

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TableView/ListHeaderView.swift
> +        ])
이런 값들도 상수화를 해두면 나중에 수정하거나, 이 부분을 모르는 사람들이 고칠때 편리해질 수 있답니다!

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/MockDataManager.swift
> +              let index = MockDataManager.shared.mockModels.firstIndex(of: previousItem) else { return }
```suggestion
        guard var previousItem = MockDataManager.shared.mockModels.first(where: { $0.id == item.id }),
              let index = MockDataManager.shared.mockModels.firstIndex(of: previousItem) else { return }
```

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/MockDataManager.swift
> +              let index = MockDataManager.shared.mockModels.firstIndex(of: item) else { return }
```suggestion
         guard let index = MockDataManager.shared.mockModels.firstIndex(where: { $0.id == item.id }) else { return }
```

2023-01-23 17:10 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +            tableView.reloadData()
지금 reloadData의 목적이 헤더뷰를 업데이트하기 위한거라면, 잘 만들어놓은 ListHeaderView의 updateView를 호출하면 될거같은데요?ㅎㅎ 그게 더 맞는 것 같고요.

2023-01-25 07:50 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/AddTodoViewController.swift
> +    func addNewTodoItem(with item: TodoModel)
리팩토링 과정에서 `AddTodoViewDelegate`과 `EditTodoViewDelegate` 을 삭제해 해당 코드에는 반영하지는 못했지만, `MockDataManager`의 CRUD 관련 메서드에 유사하게 반영해보았습니다. 😀

2023-01-25 07:52 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/AddTodoViewController.swift
> +    }
MVC 패턴에서 View의 재사용성을 강조하는 것을 고려해 `AddTodoViewController`와 `EditTodoViewController`에서 동일한 View를 사용하기 위해 커스텀 뷰를 사용했었습니다.
하지만, 두 VC를 하나의 VC로 통합하면서 커스텀 뷰를 사용하지 않게 되었습니다!

2023-01-25 07:55 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/AddTodoViewController.swift
> +        delegate?.addNewTodoItem(with: newTodoItem)
당시에는 `MockDataManager`라는 컨트롤러를 통하기는 하지만, 뷰가 Model 데이터 업데이트에 관련하게 되는 것 같아 delegate를 사용했던 것 같습니다.
리팩토링을 통해 delegate 패턴을 사용하지 않고, VC에서 `MockDataManager` 를 통해 모델 데이터를 추가하는 것으로 수정해보았습니다!

2023-01-25 07:58 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/EditTodoViewController.swift
> +class EditTodoViewController: UIViewController {
위의 코멘트들과 연관지어 `TodoViewController` 컨트롤러를 하나로 통합해보았습니다! 대신, `viewStatus` 프로퍼티를 정의해 뷰의 상태가 todo를 add하는 상태인지, edit하는 상태인지에 따라 다르게 동작할 수 있도록 했습니다.

2023-01-25 08:38 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +        MockDataManager.shared.mockModels.filter { $0.status == .todo }
데이터 제공은 `MockDataManager`의 역할이라는 점을 다시 한번 상기하게 되었습니다.🥲 수정하였습니다!
[0022bd5](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/0022bd535433ca56520a637753b3c3ea3561e4e3)

2023-01-25 09:37 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +    private lazy var doneDataSource: ListDataSource = configureDataSource(of: doneTableView)
DataSource를 반환하는 `configureDataSource(of:) -> ListDataSource` 메서드를 각 프로퍼티에 클로저로 작성하면 코드의 중복도가 너무 높아질 것 같아 메서드를 반환받는 것으로 작성했었습니다!

2023-01-25 09:39 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +        view.backgroundColor = .white
`configureContentView()` 메서드를 만들어 그 안에서 설정하도록 수정하였습니다!

[7e3c2d2](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/7e3c2d2f0caebdb29891c4232992da0325d7e0fd)

2023-01-25 09:42 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +
앗 단순히 제가 놓친 부분인 것 같습니다.😂 위 코멘트에서 `configureContentView()` 메서드를 만들면서 줄바꿈 삭제했습니다.

2023-01-25 10:00 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +        configureLayout()
보통 `set`은 `view.backgroundColor = .white` 처럼 프로퍼티의 값을 설정하는 메서드에 사용하는 편이고, `configure`은 layout을 구성하는 것처럼 구성한다는 의미로 사용했었습니다.
하지만 프로젝트를 보니 명확히 구분된 것 같지 않고... 
생각해보니 '여러 프로퍼티의 값을 설정하는 일련의 코드 = 구성하는 것'이라고 할 수 있을 것 같아 `configure`로 메서드명을 통일하는 것이 좋을 것 같다는 생각이 들었습니다! 혹시 엘림은 어떻게 사용하시는지 조언을 주실 수 있을까요? 🥹

2023-01-25 12:38 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +    @objc func pressTableView(_ sender: UILongPressGestureRecognizer) {
특정 cell의 위치값을 통해 수행되는 메서드니 엘림이 말해주신대로 수정했습니다!
[2210861](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/22108617e17e9ea17d14311d0a5f0a0b01c95e72)

2023-01-25 12:42 UTC, ash-youu commented on ProjectManager/ProjectManager/Extension/NameSpace.swift
> +enum TodoError {
별도의 타입으로 취급해서 소스파일을 분리하는 것으로 리팩토링 했습니다.

[068d5ae](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/068d5aeade8e72e1b041231916bae381ec8fcc49)

2023-01-25 12:52 UTC, ash-youu commented on ProjectManager/ProjectManager/View/TableView/ListTableViewCell.swift
> +    static let identifier = ListTableViewValue.identifier
namespace에서 identifier를 정의해두고 셀이나 헤더를 등록할 때 / 재사용할 때 모두 사용하려고 정의해뒀는데 놓친 부분인 것 같습니다.
혹시 코멘트 주신 게 이 수정 방향이 아니라면 말씀 부탁드리겠습니다!!

[4c2886a](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/4c2886a16f8ac8e5ea003e2f7ea704f42a040a6b)

2023-01-25 13:25 UTC, ash-youu commented on ProjectManager/ProjectManager/View/TableView/ListTableViewCell.swift
> +        fatalError("init(coder:) has not been implemented")
기본으로 fatalError를 구현해주다보니 생각해보지 못한 부분인 것 같습니다. 앱이 중단될 수 있는 가능성을 없애기 위해 `print`메서드를 통해 에러로그를 남기는 것으로 수정했습니다. 🙃

[56d586e](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/56d586e1b20ba73e7054807e25de71bd0eaaeec9)

2023-01-25 13:36 UTC, ash-youu commented on ProjectManager/ProjectManager/View/TableView/ListTableViewCell.swift
> +        DispatchQueue.main.async { [weak self] in
escaping 클로저를 수행할 때, 순환 참조로 할당해제가 불가해질 수 있는 상황을 피하기 위해 self를 약한 참조로 캡쳐하는 캡쳐 리스트의 키워드로 알고있습니다!

2023-01-25 13:41 UTC, ash-youu commented on ProjectManager/ProjectManager/View/TableView/ListTableView.swift
> +        register(ListHeaderView.self, forHeaderFooterViewReuseIdentifier: ListHeaderView.identifier)
별도의 함수로 분리했습니다!

[cc3b5b4](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/cc3b5b432f1c9349a4ffe32fef44f6fc038ddc6a)

2023-01-25 14:07 UTC, ash-youu commented on ProjectManager/ProjectManager/Model/TodoModel.swift
> +    let id: UUID = UUID()
identifiable 프로토콜은 처음 알게 됐습니다! id 프로퍼티를 필수적으로 정의하도록 해당 프토콜을 채택하는 것으로 수정했습니다. 😀

[6872aad](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/6872aad4ae3b3e79383dd822dfb1b882c411e81f)

2023-01-25 14:38 UTC, ash-youu commented on ProjectManager/ProjectManager/View/TableView/ListHeaderView.swift
> +        ])
매직넘버를 가능한 사용하지 않도록 수정하였습니다.
`listCountLabel`의 width는 `cornerRadius`와 연관된 값이라 말씀해주신 것처럼 네임스페이스로 할당해 관리하는 것이 용이할 거라는 생각이 들었습니다. 그런데, constant값은 UI요소가 많아지면 관리해야하는 값이 너무 많아질 것 같은데 해당값도 네임스페이스로 지정하는 것이 용이하다는 얘기이신지 궁금합니다. 🥲
혹시 제가 잘못 이해했을 수도 있을 것 같아 일단은 `countLabelWidth`와 `circleCornerRadius` 값만 네임스페이스로 지정했습니다!

[c631f69](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/c631f6988927071610940eee0627f72fa602a0d6)

2023-01-25 14:39 UTC, ash-youu commented on ProjectManager/ProjectManager/View/TableView/ListHeaderView.swift
> +        label.layer.cornerRadius = 35 / 2
아래의 코멘트와 이어지는 내용이지만, label의 반지름값을 주어 할당했습니다! 의도가 명확히 나타나지 않는 것 같아 매직넘버를 사용하지 않도록 수정했습니다. 🙃

2023-01-25 14:43 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/MockDataManager.swift
> +              let index = MockDataManager.shared.mockModels.firstIndex(of: previousItem) else { return }
제안해주신대로 수정하니 좀 더 의미가 명확히 전달되는 것 같습니다! 반영하였습니다. 😊

[94cb922](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/94cb9222743a5aceab945504a0690efcbb1b7f24)

2023-01-26 13:36 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +        configureLayout()
ㅎㅎㅎ 저도 애쉬가 마지막에말한 configure를 선호하는 편이고, set은 잘 사용하는 일이 없는 것 같습니다🫡

2023-01-26 13:38 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TableView/ListTableViewCell.swift
> +    static let identifier = ListTableViewValue.identifier
음.. ListTableViewCell.identifier을 해서 접근하는 방식은 좋아요!
다만 identifier에 값을 직접 할당해주면 , Cell의 이름을 변경했을때 함께 변경해야하니까요~
`self`로 힌트를 드리면 조금 느낌이 오실까요??

2023-01-26 13:39 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TableView/ListTableViewCell.swift
> +        fatalError("init(coder:) has not been implemented")
fatalError을 하지 않을거라면, 다른 init과 동일하게 해주는게 맞는 것 같아요~
오히려 저부분을 막는거라면 fatal을 둠으로써 개발자가 인지하게 하는게 맞는거구요! 
init이 여러가지가 생성되어있을텐데 각각의 역할을 확인해보면 좋을 것 같고요ㅎㅎ 

사용자가 사용하는 앱에서 콘솔에 보여주는 print라는 불필요한 함수가 필요할까요?ㅎㅎ 
굳이 출력으로서 확인하겠다면 디버깅 상황에서만 동작하는 메서드나 방식으로 변경하는게 좋겠어요~

2023-01-26 13:40 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TableView/ListTableViewCell.swift
> +        DispatchQueue.main.async { [weak self] in
오오, 강한 참조란 어떤걸까요? weak와 비슷한거 어떤게 또 있을까요👀
또 지금 상황은 정말 강한 참조가 생기는 시점일까요?(요건 다소 어려울 수 있으니, 간단히 생각만 해보는 걸로 가져가도 좋아요ㅎㅎ)

2023-01-26 13:43 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TableView/ListHeaderView.swift
> +        ])
저도 같은 고민을 여전히 하고 있답니다..
근데 지금 같은 경우에 보면, 아 이건 명확한 값이야! 라고 생각하지만 이걸 3개월뒤, 6개월뒤 혹은 3년 뒤에 본다고 가정하거나
애쉬가 아니라 다른 사람이 확인한다고 생각했을때, 애쉬 생각처럼 명확히 이 값이 무엇이다!고 안올 수도 있을거같아요.
차후에 유지부수와 관리를 위해 되도록 모든 매직넘버를 없애는게 맞다고 생각하긴 하지만, 애쉬말대로 모든 constant를 관리하는건 관리에 대한 비용이 들기도하죠ㅎㅎ
적절하게 지금 잘 해놓은 것 같으니 추가로 수정할 필요는 없겠습니다만, 저는 되도록 0과 1을 제외하고는ㅎㅎ 관리를 해주려고 하는 편입니다!

2023-01-26 13:56 UTC, lina0322 reviewed
아직 수정중인것 같긴한데, 거의 다 한거같아서 코멘트 달았어요! 조금만 더 수정해보고 다음 스텝으로 넘어가죠~
메세지 답장했는데, 혹시 제 설명이 부족하면 편하게 메세지 또 주세용!!

2023-01-26 13:56 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +    private lazy var doneDataSource: ListDataSource = configureDataSource(of: doneTableView)
아하, 그렇군요!
추가로 굳이 타입명시하지 않아도 될거같습니다🫡

2023-01-26 13:56 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +    }
MockDataManager에서 type을 받아서 반환하는 하나의 함수로 핸들링 할 수도 있을것 같은데요👀 그 방식은 어떨까요?

2023-01-26 13:56 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +    private func showTodoItemView(nextViewController: UIViewController) {
showTodoItemViewController로 하는게 좋을거같습니다! view랑 viewController는 다르니까, 명확하게 해줍시다~

2023-01-26 13:56 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +    }
```suggestion
    private func addTodoObserver() {
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(updateView),
            name: Notification.Name.mockModels,
            object: nil
        )
    }
```

요렇게 줄바꿈 하는 경우가 더 많은거같긴해요ㅎㅎ 
이런건 개인 취향이긴하니까 코멘트 남겨만 두겠습니당.

2023-01-26 13:56 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +        doneTableView.reloadData()
Snapshot을 하고 reloadData 함께 하는건.. 다소 어색해보여요😅

2023-01-26 13:56 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +                                   date: todoItem.date.convertDoubleToDate())
굳이 이렇게 하나씩 넘겨줄 필요 없이 todoItem 하나만 넘겨도 되지않을까요??

2023-01-26 13:56 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +        return headerView
여기 지금 보면 타입캐스팅 하고있죠?? 메세지로 물어보셨던거에 대한 힌트가 여기 있는거같습니다! 
명확한 이해 후 사용하면 더더욱 좋은 코드가 나올 수 있을거에요~

2023-01-26 13:56 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/MockDataManager.swift
> +        }
noti를 통해서 화면개선을 하는게 다소 어색한거같기도해요.
여러 곳에서 받으로 noti를 보내는건데, 실제로 한 화면에만 보내고있거든요🤔

2023-01-26 16:34 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +        configureLayout()
앗 그렇군요 감사합니다 엘림! configure로 통일하는 것으로 수정해보았습니다 😊

[1543022](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/1543022e72dc8d52cc89f31fb8601919cc78100c)

2023-01-26 16:35 UTC, ash-youu commented on ProjectManager/ProjectManager/View/TableView/ListTableViewCell.swift
> +    static let identifier = ListTableViewValue.identifier
네네! identifier에 새로운 값을 할당하기 보다는 기존에 존재하는 타입 프로퍼티 값을 통해 identifier로 활용하도록 수정해보았습니다!

[a22b48d](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/a22b48d4c06721790712b0656c3963a59c3fd04c)

2023-01-26 16:56 UTC, ash-youu commented on ProjectManager/ProjectManager/View/TableView/ListTableViewCell.swift
> +        DispatchQueue.main.async { [weak self] in
강한 참조는 참조 카운트를 증가시키는 것으로 모든 참조를 해제하지 않으면(참조 카운트가 0이 되지 않으면) deinit이 되지 않는 개념으로 알고 있습니다.
또, weak과 비슷한 것으로는 미소유 참조가 있습니다!

처음에는 아래와 같이 생각을 했습니다.
1) DataSource에서 cell의 인스턴스를 생성
2) 셀의 컨텐츠를 구성하는 상황(escaping 클로저)
-> 이 과정 중간에 셀이 삭제 된다거나 하면 self(셀의 인스턴스)가 할당 해제되는 경우도 있을 것이다.
라고 생각해서 약한 참조를 지정했는데 생각해보니 cell은 계속 재사용되기 때문에 강한 참조는 발생하나 할당 해제가 발생하는 상황은 없을 것이라는 생각이 들었습니다.
하지만, 너무나 추측에 가까운 이야기라 혹시 이 부분은 어떤 키워드로 더 공부하면 이해할 수 있을지 조언해주실 수 있을까요?😭

2023-01-26 17:02 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +    }
조언해주신대로 `fetchList(status:)`라는 하나의 메서드를 통해 핸들링할 수 있도록 리팩토링해보았습니다. 🙃

[f63b93b](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/f63b93b178f022adce6f778d933c1a0051faa02f)

2023-01-26 17:05 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +    private func showTodoItemView(nextViewController: UIViewController) {
넵 명확히 구분되도록 리네이밍하였습니다!

[e5c8b9e](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/e5c8b9eb260f3d01697417bf108fa0c56390ccca)

2023-01-26 17:11 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +                                   date: todoItem.date.convertDoubleToDate())
처음에는 view에서 model값을 직접 전달받지 않도록 하려고 했었는데, 컨트롤러를 통해 단순히 값을 전달받고 view를 업데이트하는 것이라 생각해서 todoItem 하나만 전달받아 뷰를 업데이트하도록 수정했습니다. 🥲

2023-01-26 17:56 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +        doneTableView.reloadData()
아래 헤더뷰 관련 내용과 같이 코멘트 남기도록 하겠습니다! 😄

2023-01-26 17:57 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +        return headerView
타입캐스팅을 해서 뷰를 업데이트해주고 있다는 것을 놓치고 있었습니다 😂
`reloadData()`를 하지 않고, headerView의 인스턴스 메서드를 통해 카운트 라벨을 업데이트하는 것으로 수정해보았습니다!

[77e7529](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/77e75299c040e155080ad4c8a5ddb9a1718c518b)

2023-01-26 18:35 UTC, ash-youu commented on ProjectManager/ProjectManager/View/TableView/ListHeaderView.swift
> +        ])
엘림의 조언대로 매직넘버를 사용하는 것보다는 별도로 관리를 해주는 것이 추후 유지보수 차원에서 용이할 것이라고 생각하여 별도의 타입을 정의해주었습니다.
`NameSpace`에 정의하기 보다는 해당 제약을 사용하는 곳에서 중첩 타입으로 정의하는 것이 코드를 읽기 용이할 것 같아 중첩 타입으로 정의해두었습니다!

[20c1040](https://github.com/yagom-academy/ios-project-manager/pull/252/commits/20c10404d9eab3968c3dd280817bde3c1cfd9597)

2023-01-26 18:41 UTC, ash-youu commented on ProjectManager/ProjectManager/Controller/MockDataManager.swift
> +        }
사실 모델단에서 업데이트된 데이터를 어떻게 뷰에 동기화할지에 대해 고민이 많았던 것 같습니다. 아이템을 등록하거나 편집하는 뷰가 모달뷰이기 때문에 view의 life cycle 관련 메서드를 사용할 수 없어 KVO나 Notification을 이용하는 것이 방법이라고 생각했는데, 혹시  이 외에 더 좋은 방법이 있을지 궁금합니다...! 🥲

2023-01-27 11:16 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TableView/ListTableViewCell.swift
> +    static let identifier = ListTableViewValue.identifier
여기 좀 더 디벨롭 할 수 있을건데ㅎㅎㅎ 아예 ListTableViewCell 자체를 쓰지 않는 방법은 없을까요ㅎㅎㅎ
protocol로 만들어서 여기저기에 그냥 프로토콜만 추가하면 identifier를 쓸수있게 하는거죠!

2023-01-27 11:17 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TableView/ListTableViewCell.swift
> +        DispatchQueue.main.async { [weak self] in
https://medium.com/@almalehdev/you-dont-always-need-weak-self-a778bec505ef
요 미디엄 글을 보면 도움이 될거같아요🔥

2023-01-27 11:20 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/MockDataManager.swift
> +        }
아무래도 지금 MockDataManager로 싱글턴을 유지하다보니 접근도 어려워지는 걸 수 있겠는데요!
save하는 타이밍에서 MockDataManager에 접근했던 것 처럼 부모에도 접근할 수 있을거에요~
dismiss하는 타이밍에해도되고 그 이전에 부모뷰컨에 어떻게 접근할 수 있는지 고민해봅시다.

2023-01-27 11:28 UTC, lina0322 approved these changes
애쉬, 고생하셨어요! 
프로젝트 기간에 연휴도 있어서 정신없었을텐데 많이 고민하고 수정한 모습이 보입니다~
저희가 벌써 프로젝트를 마무리 해야할 타이밍이네요!

추가적으로 코멘트 남긴 것 있고, 수정 좀 더 했으면 하는게 있긴한데! 일단 여기서 마무리하면 어떨까 합니다~
원하면 머지 바로 해드릴게요. (원하면 추가적으로 수정해도 좋습니다.)
이번 스텝도 고생하셨어요🫡

2023-01-27 11:28 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +    }
enum들은 같은 곳에 작성해주는게 좋아요. 보통 저는 ListViewController를 extension해서 파일 하단쪽에 enum들 몰아주기도 합니다ㅎㅎ

2023-01-27 11:28 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +    private typealias ListDataSource = UITableViewDiffableDataSource<ListSection, TodoModel>
typealias는 최상단에 선언해서 아래에서 모두 쓰인다는걸 시각적으로 표현하는 것도 좋겠쬬~

2023-01-27 11:28 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +            object: nil)
여기 `)` 줄바꿈 필요해욥!

2023-01-27 11:28 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ListViewController.swift
> +    }
LGTM👏

2023-01-27 11:28 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/MockDataManager.swift
> +    }
```suggestion
    func todoList(by status: TodoModel.TodoStatus) -> [TodoModel] {
        return mockModels.filter { $0.status == status }
    }
```
전 이렇게 네이밍할거같아요ㅎㅎ

2023-01-27 11:28 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/MockDataManager.swift
> +}
여기서 관리하는 것과 파일을 분리해서 전역적으로 관리하는것, 어떤게 더 좋을까요ㅎㅎ 이건 고민한번해보세용 정답은 절대없어용

2023-01-30 06:10 UTC, merged