Step 2
yagom-academy/ios-project-manager pull request #255
Opened 2023-01-25 10:21 UTC by yjjem

**안녕하세요** @forestjae

**STEP-2** 완료하여 PR보내드립니다
이번 스탭도 잘 부탁드리겠습니다 🤓

처음 시도하는 RxSwift라 제대로 활용해보지 못한 것 같아 아쉽습니다.
`MVVM`, `RxSwift`, `Clean Architecture`의 활용을 목표로 진행했기에 뷰의 레이아웃은 최대한 간단하게 잡아봤습니다.
진행하면서 올바른 방향으로 수정해보도록 하겠습니다.

## 실행화면 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/88357373/214537271-4352bbc8-2e41-4486-bcba-84244fcfc33a.gif)

## 프로젝트 구조
<img src="https://i.imgur.com/6E0W4un.jpg"/>

## 경험하고 배운 것
- Clean Architecture를 통해 각 계층간의 관심사 분리를 하였고 이는 의존성 전이 문제를 해결해줄 수 있었고 변경에 용이한 형태로 구현할 수 있었습니다.
- MVVM을 활용하여 View의 책임을 줄이고 ViewModel을 통해 비즈니스 로직을 수행합니다. View는 다른 View가 무엇을 하는지 알아야 될 필요가 없어서 매우 편리합니다. 👍
- RxSwift를 활용해 View와 ViewModel간의 Binding을 쉽게 구현해볼 수 있었습니다.

## 어려웠던 점 😨

#### Clean Architecture의 흐름 구현 

프로젝트 요구사항에 따라 Loacl, Remote 저장소 없이 간단하게 ViewModel에 메모리 저장소 구현을 시도했습니다. 
하지만 Presentation 계층만으로는 Clean Architecture의 "흐름"이 존재하지않아 대부분의 기능 구현에 어려움이 있었습니다.

Forest가 알려주신대로 임시적으로 메모리에서 동작하는 Data 계층 오브젝트를 구현하고 이를 Presentation 계층에서 사용할 수 있도록 해주는 Use Case를 구현하니 문제는 해결되었습니다 👍

## 발생한 문제점 🥊

#### 무명의 트리거

TextView입력값을 실시간으로 받아오는 ViewModel들 (AddTaskViewModel, EditTaskViewModel)에서 
아래와 같은 형태로 무명의 트리거가 발생합니다. 처음에는 상수명을 지정을 해주었지만 사용되지않았단는 경고 문구 때문에 아래와 같이 수정해야했습니다.

> 질문❗️

**아래와 같은 경우는 어쩔 수 없이 무명으로 두어야하는 상황인가요?**

| _ 를 date로 변경시 |
| -------- |
|![](https://i.imgur.com/UDAQuMM.png)|

| 이름과 타입 지정시 |
|---|
|![](https://i.imgur.com/en8ZlkA.png)|

```swift
let _ = input.dateTrigger
            .subscribe(onNext: {
                self.date = $0
            })
            .disposed(by: disposeBag)
```

### 📝 추후 해결해야할 점
- Cell edit창 진입 이후 deselect 되지않는 점
- ~~Edit창에서 이미 expired된 date를 수정할 시 검은 텍스트로 변경되지 않는 점~~
    - prepareForReuse에서 attributedText = nil 설정하여 해결
- Cell switching view가 edit 진입 이후에만 확실하게 작동하는 점 

</br></br></br></br>

2023-01-27 03:55 UTC, forestjae requested changes

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Common/ViewModelType.swift
> +protocol ViewModelType {
이 프로토콜은 Presentation Layer에만 쓰일 것 같은데, 폴더 위치를 고민해보면 좋겠습니다.

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Domain/Entities/Task.swift
> +enum Status {
네이밍이 너무 general 하네요. Task와 연관되어 있다는 것을 나타내주거나, `Nested Type`을 고려해 보세요

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Domain/UseCase/TaskItemsUseCase.swift
> +    private let datasource: DataSourceType
다음 스텝에서는 repository를 사용해보세요!

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Extensions/Date + converted.swift
> +        dateFormatter.setLocalizedDateFormatFromTemplate("yyyyMMMdd")
동일 로직이 중복되네요, 어떻게 개선해 볼 수 있을까요?

모든 Date타입이 이 메서드들을 가질 필요가 있는지도 고민 해보면 좋겠습니다.

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Extensions/UITableView + didLongPress.swift
> +}
`UIGestureRecognizerDelegate`의 메서드를 활용하지 않으신 것 같아요. `UIGestureRecognizerDelegate`문서를 확인해보고 좀 더 쉬운 방법으로 구현할 수 없는지 알아보시면 좋겠습니다.

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/AddTask/AddTaskViewController.swift
> +    private var titleTextView: UITextView = {
var로 선언하신 이유가 있을까요?

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/AddTask/AddTaskViewController.swift
> +    let disposeBag = DisposeBag()
`internal` 프로퍼티가 `private` 프로퍼티 보다 위에 배치되는게 보기 좋을 것 같습니다

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/AddTask/AddTaskViewController.swift
> +        guard let viewmodel = self.viewmodel,
self 키워드를 사용하시는데에 어떤 기준을 적용하시나요?

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +final class ProjectManagerViewController: UIViewController, UIGestureRecognizerDelegate {
1. 이 화면은 폴더링이 안되어 있네요 
2. delegate는 extension에 구현하시는게 어떨까요?

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +fileprivate enum Common {
네이밍 확인 부탁드려요

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +extension ProjectManagerViewController: UITableViewDelegate {
delegate와 관련된 메서드만 위치 시키는게 어떨까요?

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +        bindSelectionActionToCell()
메서드를 하나로 묶을 수 있을 것 같아요

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/TaskStatusInfoView.swift
> +extension TaskStatusInfoView {
mark 를 사용하여 구분해 주셨는데, 다른 프로토콜을 채택하지 않는 상황에서는 굳이 extension 까지 사용해서 분리 할 필요가 없다고 생각합니다.

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/TaskSwitch/TaskSwitchViewController.swift
> +    private func layoutViews() {
layout은 애플에서 view를 `그리다` 라는 의미로 많이 사용되는 단어라서, 네이밍을 한번 고민해 보시면 좋겠습니다!

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/TaskSwitch/TaskSwitchViewController.swift
> +    }
뷰의 hierarchy를 설정하는 부분과, 제약을 거는 내용이 메서드 분리가 되면 보기 좋을 듯 하네요

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/TaskSwitch/TaskSwitchViewController.swift
> +    }
인터널 메서드로 설정된 이유가 무엇인가요?

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +                self.todoStatusView.setUpCount(count: count)
강한참조로 인한 memory leak에 대해 공부해보시고, 이 코드에 대해 다시 한번 생각해 보시면 좋겠습니다.

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/EditTask/EditTaskVIewModel.swift
> +    var task: Task
internal로 열어두신 이유가 있을까요?

2023-01-27 03:55 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/AddTask/AddTaskViewController.swift
> +final class AddTaskViewController: UIViewController {
사실상 edit taskVC와 거의 유사한 view라고 볼 수 있는데, 별도로 구현하신 이유가 있을까요?

좀 더 효율적으로 하려면 어떤 방법이 있을까요?

2023-01-27 04:08 UTC, forestjae commented
수고많으셨어요 제레미!

처음 사용해 보시는 개념들이 많았을텐데, 정말 잘 해주셨습니다.
- RxSwift의 기본 개념을 이해하시고 잘 사용해주셨네요
- Input output 모델을 사용하여 바인딩을 잘 구현해 주셨네요. 👍👍👍 
- Clean Architecture라기엔 Data Layer의 구현이 부족하네요, 추후 스텝에서 사용해보아요.

다만, 가독성 측면에서 개선할 점이 많이 보입니다. 
[StyleShare/swift-style-guide: StyleShare에서 작성한 Swift 한국어 스타일 가이드](https://github.com/StyleShare/swift-style-guide) 를 참고해주세요.

기타 글로 말씀드리기 어려운 내용은 라이브 리뷰 진행하면서 말씀드릴게요.

> 처음 시도하는 RxSwift라 제대로 활용해보지 못한 것 같아 아쉽습니다. `MVVM`, `RxSwift`, `Clean Architecture`의 활용을 목표로 진행했기에 뷰의 레이아웃은 최대한 간단하게 잡아봤습니다. 진행하면서 올바른 방향으로 수정해보도록 하겠습니다.
> 

> ## 실행화면
> 
> ## 프로젝트 구조
> ![](https://camo.githubusercontent.com/71675dc3eb5ab14fff2e2593cf4b1ae15068db4af7756ce5631dcff67c04d9ec/68747470733a2f2f692e696d6775722e636f6d2f3645305734756e2e6a7067)
> 
> ## 경험하고 배운 것
> * Clean Architecture를 통해 각 계층간의 관심사 분리를 하였고 이는 의존성 전이 문제를 해결해줄 수 있었고 변경에 용이한 형태로 구현할 수 있었습니다.
> * MVVM을 활용하여 View의 책임을 줄이고 ViewModel을 통해 비즈니스 로직을 수행합니다. View는 다른 View가 무엇을 하는지 알아야 될 필요가 없어서 매우 편리합니다. 👍
> * RxSwift를 활용해 View와 ViewModel간의 Binding을 쉽게 구현해볼 수 있었습니다.
> 
> ## 어려웠던 점 😨
> #### Clean Architecture의 흐름 구현
> 프로젝트 요구사항에 따라 Loacl, Remote 저장소 없이 간단하게 ViewModel에 메모리 저장소 구현을 시도했습니다. 하지만 Presentation 계층만으로는 Clean Architecture의 "흐름"이 존재하지않아 대부분의 기능 구현에 어려움이 있었습니다.
> 
> Forest가 알려주신대로 임시적으로 메모리에서 동작하는 Data 계층 오브젝트를 구현하고 이를 Presentation 계층에서 사용할 수 있도록 해주는 Use Case를 구현하니 문제는 해결되었습니다 👍
> 


이름을 아예 정의 안하면 됩니다.

> ## 발생한 문제점 🥊
> #### 무명의 트리거
> TextView입력값을 실시간으로 받아오는 ViewModel들 (AddTaskViewModel, EditTaskViewModel)에서 아래와 같은 형태로 무명의 트리거가 발생합니다. 처음에는 상수명을 지정을 해주었지만 사용되지않았단는 경고 문구 때문에 아래와 같이 수정해야했습니다.
> 
> > 질문❗️
> 
> **아래와 같은 경우는 어쩔 수 없이 무명으로 두어야하는 상황인가요?**
> 
> _ 를 date로 변경시
> ![](https://camo.githubusercontent.com/441cf5309b62dca3b91af6e59ae645ac53b033d2a1836231d20e210b68f2a988/68747470733a2f2f692e696d6775722e636f6d2f55444151754d4d2e706e67)
> 이름과 타입 지정시
> ![](https://camo.githubusercontent.com/9dafeab8a6d5c188b332a2c218cb7ef55f65f5dd523e8f7b64e468f985c35b19/68747470733a2f2f692e696d6775722e636f6d2f656e385a6c6b412e706e67)
> ```swift
> let _ = input.dateTrigger
>             .subscribe(onNext: {
>                 self.date = $0
>             })
>             .disposed(by: disposeBag)
> ```
> 
> ### 📝 추후 해결해야할 점
> * Cell edit창 진입 이후 deselect 되지않는 점
> * ~Edit창에서 이미 expired된 date를 수정할 시 검은 텍스트로 변경되지 않는 점~
>   
>   * prepareForReuse에서 attributedText = nil 설정하여 해결
> * Cell switching view가 edit 진입 이후에만 확실하게 작동하는 점

2023-01-27 04:14 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewModel.swift
> +        let delete = input.delete.flatMapLatest { item in
flatMapLatest를 사용하신 이유가 무엇인가요?

2023-01-30 09:40 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewModel.swift
> +        let delete = input.delete.flatMapLatest { item in
Sequence의 제일 마지막 요소만을 받아야할 것 같아서 사용을 했었습니다.
하지만 delete를 예시로 들자면 한 번만 요소가 전달되고 Observable을 생성합니다.
따라서 이 부분은 flatMap이 맞는 것 같습니다.. 수정했습니다 👍 

`📋 수정 내용` c7abfb8

2023-01-30 09:40 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/AddTask/AddTaskViewController.swift
> +final class AddTaskViewController: UIViewController {
viewModel이 받는 Input과 Output의 형태가 달라서 별도로 구현해야겠다고 생각했던 것 같습니다.

뷰 모델에 operationType 프로퍼티를 추가하여 type에 따라 다른 설정과 로직을 수행하도록 했고.
Input과 Output을 통일했습니다.

`📋 수정 내용`  [`c0caef3`](https://github.com/yagom-academy/ios-project-manager/pull/255/commits/c0caef37408b3e3fe41af2e1c5c532b8db3bd41e)

```swift
// UpdateTaskViewModel.swift
let formedTask = input.doneTrigger
            .flatMap {
                let task = self.formTask()
                
                // operation type으로 사용할 UseCase기능을 분기처리
                switch self.operationType {
                case .add:
                    return self.useCase
                        .create(task: task)
                case .edit:
                    return self.useCase
                        .update(task: task)
                }
            }
```

```swift
// UpdateTaskViewController.swift
// 버튼의 타입을 operation type에 따라 분기한 모습
switch operationType {
        case .add:
            navigationItem.leftBarButtonItem = cancelButton
        case .edit:
            navigationItem.leftBarButtonItem = editButton
        }
```

2023-01-30 09:40 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/EditTask/EditTaskVIewModel.swift
> +    var task: Task
private으로 수정했습니다 👍

2023-01-30 09:40 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +                self.todoStatusView.setUpCount(count: count)
disposeBag을 사용하면 memory leak이 발생하지 않을거라고 생각했지만 
onNext의 escaping클로저는 별개이므로 self와 강한 순환 참조를 일으킵니다.
non-escaping인 고차함수의 경우 문제가 없지만 escaping closure인 subscribe의 파라매터 ( onNext )는 
꼭 capture list를 활용해 strong reference를 가지지 않도록 해줘야 한다는 것을 배웠습니다.

프로젝트에서는 [unowned self]를 활용해주었습니다. unowned는 항상 값이 존재해야하고 없다면 앱 크래쉬를 발생시킵니다.
하지만 self의 값들이 항상 존재하고 closure의 lifetime은 객체의 lifetime과 일치하기 떄문에 [unowned self]를 활용해주었습니다.
optional인 weak self와는 다르게 따로 옵셔널 바인딩을 해주지 않아도 되서 편리한 것 같습니다.

다만 크래쉬가 발생할 수 있다는 점으로 인해 잘 사용되지 않는다고 하는데 위와 같은 상황에서도 사용을 최대한 지양해야할까요?

`📋 수정 내용` 5287661

2023-01-30 09:40 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/TaskSwitch/TaskSwitchViewController.swift
> +    }
명확한 이유는 없었습니다 😅

아래와 같이 private 메서드로 지정하여 내부에서 실행되도록 수정했습니다.
상속이 UIAlertController로 바뀌게 되면서 presentationStyle 설정이 불필요하게 되어 아래와 같은 형태를 띄게 되었습니다 👍
```swift
private func configureArrowDirections() {
    popoverPresentationController?.permittedArrowDirections = [.left, .right]
}
```

2023-01-30 09:40 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/TaskSwitch/TaskSwitchViewController.swift
> +    }
아래와 같이 메서드를 분리하였습니다 👍
- hierarchy - `combineViews`
- constraint - `configureViewConstraint`

2023-01-30 09:40 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/TaskSwitch/TaskSwitchViewController.swift
> +    private func layoutViews() {
constraint를 잡는 모든 파일들에서 `configureViewConstraints()`로 네이밍을 수정했습니다 !

2023-01-30 09:40 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/TaskStatusInfoView.swift
> +extension TaskStatusInfoView {
말씀해주신 대로 View의 주요기능이 확장 기능이 들어가야할 곳에 들어가니 맞지않은 것 같습니다 .

`View(s)`, `Function(s)`, `Private Function(s)`, `Override(s)`와 같이 Mark를 나누는 기준을 변경하였고 
기본 구현 기능들은 extension으로 분리하지 않고 클래스 내부에 위치하는 방향으로 수정하였습니다. 
감사합니다 👍

2023-01-30 09:40 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +        bindSelectionActionToCell()
아래와 같이 `performBindings()` 로 묶어주었습니다 👍
```swift
private func performBindings() {
    bindViewModel()
    bindSelectionActionToCell()
}
```

2023-01-30 09:40 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +extension ProjectManagerViewController: UITableViewDelegate {
delegate 콜백 메서드들만 위치하도록 수정했습니다 🌳

2023-01-30 09:41 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +fileprivate enum Common {
좀 더 올바른 방향으로 네이밍을 수정하기 위해서 namespace 에 들어가는 내용물에 따라 
기준을 나누어 아래와 같이 분리하고 네이밍을 수정했습니다 👍
`📋 수정 내용` 820372d

```swift
fileprivate enum Titles { ... }

fileprivate enum Identifier { ... }

```

2023-01-30 09:41 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +final class ProjectManagerViewController: UIViewController, UIGestureRecognizerDelegate {
delegate는 extension에서 구현하는 방향을 수정하였습니다. 👍

`📋 수정 내용` ff2d73b

2023-01-30 09:41 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/AddTask/AddTaskViewController.swift
> +        guard let viewmodel = self.viewmodel,
본인이 self 키워드를 사용하는 기준
- self는 필수적으로 요구되는 곳
- 동명으로 옵셔널 바인딩 시 
- `self.rx` 와 같은 짧은 코드에 붙여서 사용합니다.

하지만 프로젝트 내부에서 self에 대한 일관성과 기준을 잘 지키지 못한 것 같습니다. 
위에서 언급한 기준에 맞춰 불필요한 self 키워드를 삭제하였습니다 👍

2023-01-30 09:41 UTC, yjjem commented on ProjectManager/ProjectManager/Extensions/Date + converted.swift
> +        dateFormatter.setLocalizedDateFormatFromTemplate("yyyyMMMdd")
위의 Date extension 메서드들은 TaskCell에서만 사용됩니다. 다른 곳에서 사용하는 경우도 없습니다.
따라서 TaskCell 파일 내부에 위치하고 private설정해주었습니다.

동일 로직이 반복되는 건에 대해서는 extension의 private 메서드로 
`createTaskCellDateFormatter()`를 추가했습니다.

`📋 수정 내용` 536032c

```swift
private func createTaskCellDateFormatter() -> DateFormatter {
    let dateFormatter = DateFormatter()
    dateFormatter.setLocalizedDateFormatFromTemplate("yyyyMMMdd")
    return dateFormatter
}
```

2023-01-30 09:41 UTC, yjjem commented on ProjectManager/ProjectManager/Domain/UseCase/TaskItemsUseCase.swift
> +    private let datasource: DataSourceType
감사합니다 👍

2023-01-30 09:41 UTC, yjjem commented on ProjectManager/ProjectManager/Domain/Entities/Task.swift
> +enum Status {
Task 열거형에 nest하여 연관성을 나타내는 방향으로 수정했습니다  👍
`📋 수정 내용` 3965fe1

```swift
struct Task: Equatable {
    enum Status {
        case todo
        case doing
        case done
    }
    ...
}
```

2023-01-30 09:41 UTC, yjjem commented on ProjectManager/ProjectManager/Common/ViewModelType.swift
> +protocol ViewModelType {
말씀해주신대로 ViewModelType은 Presentation Layer에서만 사용됩니다.
따라서 아래와 같이 Presentation 폴더의 내부에 위치하도록 했습니다 👍
```
Presentation
└── Common
    └── ViewModelType.swift
```

2023-01-30 09:43 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/AddTask/AddTaskViewController.swift
> +    private var titleTextView: UITextView = {
let 으로 수정하였습니다 😅

2023-01-30 09:51 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/AddTask/AddTaskViewController.swift
> +    let disposeBag = DisposeBag()
수정했습니다 !

2023-01-30 09:56 UTC, yjjem commented on ProjectManager/ProjectManager/Extensions/UITableView + didLongPress.swift
> +}
sender로 들어오는 gestureRecognizer의 값을 통해 
tableview와 cell을 받아오고 이를 기반으로 edit이벤트가 발생하도록 수정했습니다 ! 감사합니다 👍

2023-01-30 23:37 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +final class ProjectManagerViewController: UIViewController, UIGestureRecognizerDelegate {
delegate들은 개별적으로 extension에서 관리하는 방향으로 수정했습니다 !

2023-01-30 23:38 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/TaskSwitch/TaskSwitchViewController.swift
> +    }
hierarchy를 설정하는 부분은 `combineViews()` 제약을 거는 경우 `configureViewConstraints()`로 분리하였습니다 👍

2023-01-31 00:08 UTC, yjjem commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +                self.todoStatusView.setUpCount(count: count)
탈출 클로저가 self를, self가 클로저를 강하게 참조하면서 강한 순환 참조. 즉 memory leak이 발생합니다.
따라서 capture list를 사용하여 강하게 참조하지 않도록 설정해줘야합니다.
[weak self], [unowned self]를  사용하여 캡쳐리스트를 지정해줄 수 있지만 

weak self의 경우 값의 유무가 optional이고 unowned 레퍼런스는 값이 무조건 존재하는 것을 보장해야하고 사용되는 도중에 값이 deallocate된다면 앱 크래쉬가 발생합니다.

현재 프로젝트에는 [unowned self]를 사용해주었습니다. unowned로 인해 강한 참조를 하지않고 self가 먼저 deallocate되는 상황이 없을 것 같아서 사용했습니다. 올바른 방향으로 진행한 걸까요 ?

2023-02-02 02:28 UTC, closed without merging

2023-02-04 08:14 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/AddTask/AddTaskViewController.swift
> +        guard let viewmodel = self.viewmodel,
좋습니다.

2023-02-04 08:15 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +extension ProjectManagerViewController: UITableViewDelegate {
이건 제가 라이브 리뷰하면서 좀 잘못 말씀드린 것 같은데, 콜백 메서드 내부에서만 사용되는 private method들은 이 익스텐션에 있는게 맞을 것 같네요 ㅎㅎ

2023-02-04 08:20 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/AddTask/AddTaskViewController.swift
> +final class AddTaskViewController: UIViewController {
👍👍👍

2023-02-04 08:20 UTC, forestjae commented on ProjectManager/ProjectManager/Presentation/ProjectManagerViewController.swift
> +                self.todoStatusView.setUpCount(count: count)
먼저 deallocate가 되는 상황이 없다는 것에 대한 근거가 명확하면 사용해도 될 것 같아요. 이유가 뭘까요?