프로젝트 매니저 [STEP 2] 토털이
yagom-academy/ios-project-manager pull request #257
Opened 2023-01-26 09:32 UTC by tottalE

@lina0322 안녕하세요 엘림! 늦게 PR 보내드립니다! 제가 많이 PR을 길게 쓰지는 못했지만 제가 정말 열심히 만들어 보았습니다!! 제가 천천히 고쳐 보고 싶은 마음이 있어 꼼꼼히 리뷰해주시면 정말 감사하겠습니다!

## 구현 내용

- Cell의 높이가 dynamic하게 변하는 automaticDimension 구현
- 지난 날짜를 빨간색으로 표시하고, 커스텀 포맷으로 표현
- AddProjectViewController를 통해 할일 추가 기능을 구현
- 할일 터치시 상세내용 표시 및 Edit 버튼을 통한 수정화면, 수정 기능 구현
- 길게 셀을 터치할시, Popover을 띄우고 할일의 수행정도를 수정할 수 있도록 구현
    - TODO의 할일 : Move to DOING / Move to DONE
    - DOING의 할일 : Move to TODO / Move to DONE
    - DONE의 할일 : Move to TODO / Move to DOING
- 기한 날짜를 사용자의 지역 포맷에 맞게 구현
- 셀을 스와이핑시 삭제 메뉴를 표시하고 끝까지 스와이핑 혹은 삭제 버튼을 클릭하면 삭제하도록 구현
    

## 특이사항
### Container View를 통한 로직 분리
메인 Container View에 3개의 Child 뷰를 넣어주어 뷰컨트롤러를 분리해보는 시도를 해보았습니다. 그 과정에서 각각의 ChildView를 TaskListViewController를 subclassing한 각각의 뷰컨트롤러로 만들어주고 싶었는데 시간이 부족해 일단은 각각의 컨트롤러 객체가 분리는 되어있지만 모두 TaskListViewController 클래스가 객체인 상태로 PR을 보내드립니다!

## 조언이 필요한 점

1. MVC

최대한 View와 컨트롤러를 나누어 보려고 노력을 했는데 constraints를 잡아주는 것들이 Controller에서 해주어도 되는 일인가에 대한 의문이 들었습니다. View를 분리한 다는 것에 대한 감이 아직 안오는 것 같은데 MVC에 대한 엘림의 조언 들어볼 수 있을까요?

특히 뷰와 컨트롤러의 관계에 대한 추가 질문이 있습니다!!
- 커스텀 뷰와 컨트롤러 사이에 데이터를 주고 받는 방법에 대한 고민이 많았습니다. 뷰에서 데이터를 줘야 할 때 어떤 방법이 좋은지에 대해 고민해 보았고,  우선은 함수로 해두었습니다. 
```swift
func fetchTask() -> Task? {
        guard let title = titleTextField.text else {
            return nil
        }
        guard let description = descriptionTextView.text else {
            return nil
        }
        
        return Task(id: UUID(), title: title, description: description, date: Date(), status: .todo)
    }
```

2. Delegate의 잦은 사용
컨트롤러 내에 컨트롤러를 넣었기 때문인지, 뷰 사이의 소통이 많이 필요하여 delegate 패턴을 많이 사용해 주었습니다. 제가 잘하고 있는 것인지 의문이 들었습니다. 더 좋은 방법이 있을까요?

3. Cell 사이의 간격
cell 들 사이에 간격을 주기위해 아래와 같이 frame을 변경해 주었는데 깨짐현상이 일어났습니다. 간격을 잘 줄 수 있는 방법이 있을까요? 아래 방법에 뭐가 틀렸는지 힌트를 주시면 감사하겠습니다!
![](https://i.imgur.com/EYuZJ33.png)

```swift=
override var frame: CGRect {
        get {
            return super.frame
        }
        set (newFrame) {
            var frame = newFrame
            frame.origin.y += 8
            frame.size.height -= 8
            super.frame = frame
        }
    }
```

2023-01-27 11:15 UTC, lina0322 requested changes
토털이 고생하셨습니다!! 맥북이 고장난 상황이었다고 들었는데도 열심히 작업한 것 같네요~
코드에서 많이 고민한 흔적들이 보여요.

---
### 조언이 필요한 점
1. MVC
view 코드를 분리하는 시도가 아주 좋았습니다. 전반적으로 잘 분리되어 있는걸로 보이네요.
여러가지 방법을 생각해본 것 중에 왜 저것이었는지, 다른 방법은 뭐가 있었는지 먼저 알고싶어요.

2. Delegate의 잦은 사용
Delegate를 잦게 사용했을때의 단점이 무엇이있나요?ㅎㅎ 왜 Delegate 패턴을 사용할 수 밖에 없었는지에 대해 고민해보고 이런 고민을 같이한 사람들이 어떤 디자인패턴으로 흘러나갔는지 고민하다보면, 좋은 발전을 할 수 있겠어요~!

3. Cell 사이의 간격
cell사이의 간격을 주는 방법도 여러가지가 있을거에요. cell 자체 상단이나 하단에 간격을 줄 수도 있을것이고, 간격을 위한 cell을 만들수도있고, 푸터나 헤더등을 이용하는 방법도 있겠죠.
frame을 변경하는데 왜 깨졌을까요? cell의 크기가 언제 결정되나요?

---

코멘트에 여러가지 남겨두었는데요. 특히 좀 기본적인 것들에 대해서 신경을 더 써야할 것 같아요.
지금 다양한 고민을 해서 좀 정신이 없었는지, 기초적인 부분들에 실수가 많이 눈에 띄었어요.
코드를 잘 짜는기위해서 좋은 코드를 만들기 위해서 기본과 기초가 제대로 잡혀있어야 한다고 생각해요~ 
이 부분도 잊지말고 항상 신경써주세요~

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +}
Task라는 이름보다 다른 이름은 없을까요? 
아무래도 concurrency에서 Task를 사용하고 있기 때문에 혼란을 줄 수 있을거같아요~

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    enum Constant {
내부에서만 사용되는 것으로 보입니다~

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    }
따로 관리하는 부분 좋습니다!

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    weak var delegate: TaskAddDelegate?
외부에서 접근할 수 있도록 둘 다 열어둔건가용?

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    }
viewController에서 자동으로 생성해주는 view를 변경한 이유는 view의 코드를 넘기기 위해선가요??
+ super 호출하지 않아도 괜찮을까요?

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +        view.backgroundColor = .white
메서드로 분리해주세요~

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    func configureNavigationItem() {
private 안붙인 이유가 있나요?

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +        self.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(saveAndDismissCurrentViewController))
컨벤션이 일정하지 않아요. self를 붙이고 안붙이는 것에 어떤 차이를 두고있나요?

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    // MARK: - Helpers
// MARK: - Helpers 는 일단 작성만 한건가요?

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    @objc func dismissCurrentViewController() {
dismiss로 이름 지어도 상관없을거같아요~

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    @objc private func saveAndDismissCurrentViewController() {
함수명 네이밍에 and은 어색하네요. saveTask 또는 save 정도로 하는게 좋겠어요

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/EditProjectViewController.swift
> +class EditProjectViewController: AddProjectViewController {
상속 할 예정이 있는 클래스인가요?

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/EditProjectViewController.swift
> +    }
fatalError를 사용한 이유가 궁금합니다~

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +class AddProjectViewController: UIViewController {
현재 객체를 task로 이름 짓고있으니 AddTaskViewController가 맞는 네이밍일거같네요

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectsViewController.swift
> +    private let stackView: UIStackView = {
접근 제어자나 final을 잘 사용하지 않는 것 같네요.
각각을 왜 사용하는지, 어떤 기능을 가지고 있는지 알고있을까요??👀

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectsViewController.swift
> +    }
viewController들을 배열에 넣고, 반복문을 통하여 중복된 코드를 줄이는 방법도 있을거같아요!

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectsViewController.swift
> +    @objc private func showAddProjectView() {
지금 보여지는게 view인가요 viewController인가요?🤔

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/SubviewControllers/TaskListViewController.swift
> +        })
init되는 시점에 dataSource를 생성하는게 다소 어색해보여요. 
loadView, viewDidLoad 등이 있어서 차후에 view가 생기고 나서 작업하는게 낫지 않을까요?🤔
여기서 해야만 하는거라면 함수로 분리해야할거같고요.

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/SubviewControllers/TaskListViewController.swift
> +        projectListView.dataSource = dataSource
왜 TaskListViewController의 dataSource를 projectListView.dataSource에 할당해주는 방식으로 진행했는지 궁금해요~

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/SubviewControllers/TaskListViewController.swift
> +    }
함수를 정리하는 순서는 어떻게 가져가고 있나요?

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/SubviewControllers/TaskListViewController.swift
> +                                       object: nil)
```suggestion
        NotificationCenter.default.addObserver(
                self,
                selector: #selector(showPopoverMenu),
                name: Notification.Name("cellLongPressed"),
                object: nil
        )
```

이렇게 줄바꿈을 더 많이 하는 것 같아요. 개인 취향이 있을 수 있으니, 한 번 편한대로 골라서 사용해보세욥

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/SubviewControllers/TaskListViewController.swift
> +                                       name: Notification.Name("cellLongPressed"),
cellLongPressed <- 이 상수는 관리 따로 안하나요?

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/SubviewControllers/TaskListViewController.swift
> +        guard let task = notification.userInfo?["task"] as? Task else {
task는 중요한 상수인거 같은데요. 따로 관리가 필요해보입니다.

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Extensions/Date+Extension.swift
> +                dateFormatter.dateFormat = "yyyy. M. d."
여기 앞에 들여쓰기가 이상해요..?!

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/Model/Task.swift
> +}
관련 있지만, 따로 관리하는게 맞을거같아요. 파일 분리해주세요~

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +        context.closePath()
1. 함수분리 해주세요
2. draw에서 작업한 이유가 궁금합니다~

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +
필요한 줄바꿈인가요??

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/View/ProjectListView.swift
> +    }
보통 swift 메서드는 set, get으로 시작하는 네이밍을 하지 않는 것 같습니다. 좋은 이름을 생각해봅시다~

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/View/ProjectListView.swift
> +    }
이건 왜 하는거죠??

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TaskCell.swift
> +class TaskCell: UITableViewCell {
```suggestion
class TaskTableViewCell: UITableViewCell {
```

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TaskCell.swift
> +    static let cellIdentifier = String.init(describing: TaskCell.self)
TaskTableViewCell 선언부 바로 아래로 옮겨주세요.
굳이 init을 적어야하는 이유가 있을까요?

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TaskCell.swift
> +        }
여기는 위쪽과 다른 컨벤션을 쓰고있네요. 가장아래 `)`는 줄바꿈해주는게 맞습니다~

2023-01-27 11:15 UTC, lina0322 commented on ProjectManager/ProjectManager/View/TaskSettingView.swift
> +        }
왜 분리해서 guard를 작성한지 모르겠습니다!

2023-01-29 05:54 UTC, tottalE commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    func configureNavigationItem() {
네, EditViewController에서 오버라이드해서 사용해주기 위해 private을 떼어주었습니다!

2023-01-29 09:41 UTC, tottalE commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +}
네 Project로 모두 변경해 주었습니다!

2023-01-29 09:49 UTC, tottalE commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    weak var delegate: TaskAddDelegate?
네 delegate 같은 경우 delegate를 지정해 주기 위해 열어두었고, settingView 같은 경우 자식 클래스가 사용하기 위해 internal로 열어두었습니다!

2023-01-29 09:49 UTC, tottalE commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    enum Constant {
네 접근제어자 붙여주었습니다!

2023-01-29 09:51 UTC, tottalE commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +        view.backgroundColor = .white
네 분리해 주었습니다!

2023-01-29 09:52 UTC, tottalE commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +        self.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(saveAndDismissCurrentViewController))
실수로 그렇게 하게 된 것 같습니다! 아래에도 모두 컨벤션 통일해 주었습니다.

2023-01-29 09:54 UTC, tottalE commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    // MARK: - Helpers
아네 자동으로 만들어져서 작성만 했는데 수정하겠습니다!

2023-01-29 09:56 UTC, tottalE commented on ProjectManager/ProjectManager/Controller/ProjectsViewController.swift
> +    private let stackView: UIStackView = {
네 final 혹은 접근 제어자를 붙여줄 경우에 더이상 함수가 오버라이드가 되지 않을 것을 알기 때문에 static dispatch를 사용하게 되어 불필요한 연산을 사용하는 dynamic dispatch에 비해 성능이 좋아진다는 이점이 있습니다!

2023-01-29 09:58 UTC, tottalE commented on ProjectManager/ProjectManager/Controller/SubviewControllers/TaskListViewController.swift
> +        projectListView.dataSource = dataSource
projectListView 내부에 tableView를 가지고 있어서 그 테이블 뷰에 datasource를 할당해 주기 위해서 tableview의 데이터 소스를 getter setter로 지정해주어 밖에서 지정해줄 수 있도록 설계해 주었습니다.

2023-01-29 11:14 UTC, tottalE commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +class AddProjectViewController: UIViewController {
넵 수정해 주었습니다.

2023-01-29 11:14 UTC, tottalE commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    @objc func dismissCurrentViewController() {
네 변경해주었습니다!

2023-01-29 11:15 UTC, tottalE commented on ProjectManager/ProjectManager/Controller/AddProjectViewController.swift
> +    @objc private func saveAndDismissCurrentViewController() {
네 바꾸어 주었습니다!

2023-01-29 11:24 UTC, tottalE commented on ProjectManager/ProjectManager/Controller/EditProjectViewController.swift
> +    }
Storyboard interface builder를 사용하여 view의 상태를 수정할 경우, serialization 작업을 Xcode가 init(coder:)를 호출하여 앱 내 view 작업을 저장하고 불러오는 작업을 해줍니다. 저의 경우 코드로 작성해 주었기 때문에 required init이 불릴 일은 없을 것이라 생각하여 fatalError를 사용해 주었습니다!

2023-01-30 06:09 UTC, closed without merging