프로젝트 매니저 [STEP 2] Harry, kokkilE
yagom-academy/ios-project-manager pull request #275
Opened 2023-05-23 15:37 UTC by HarryHyeon

@lina0322 
안녕하세요 엘림! 코낄이, 해리입니다.
MVVM과 반응형 프로그래밍을 처음 적용해본 프로젝트라, 전반적으로 어설프지만 잘 부탁드립니다! :man-bowing: 

## 고민한 점 :thinking:

### 1. UIView의 draw(_ rect: CGRect) 메서드 구현한 점
`TaskListHeaderView`, `CountLabel`, `TaskListCell` 타입에서 `draw(_ rect: CGRect)`메서드를 오버라이드하여 구현하였습니다. 해당 메서드 내에서는 UI요소의 프로퍼티를 설정하는 코드를 구현하였습니다.
**CountLabel**
``` swift
override func draw(_ rect: CGRect) {
    super.draw(rect)

    layer.cornerRadius = bounds.height / 2
}
```
**TaskListHeaderView, TaskListCell**
``` swift
override func draw(_ rect: CGRect) {
    super.draw(rect)

    layer.shadowColor = UIColor.black.cgColor
    layer.shadowOffset = CGSize(width: 0, height: 2)
    layer.shadowOpacity = 0.3
    layer.shadowRadius = 5.0
}
```
 
위와 같이 프로퍼티를 설정하는 작업이 UI요소의 디자인을 결정짓는 요소이기 때문에 `draw()` 메서드 내에 구현하였는데, `draw()` 메서드가 코어그래픽을 활용하여 UIKit으로 나타낼 수 없는 UI요소를 표현하고자 할 때(ex. 햄버거 그리기) 주로 사용하는 메서드인지에 대한 의문이 있습니다.

결론적으로 `draw`에서 정의해주는 방식을 택했는데 엘림의 의견은 어떠신지 궁금합니다!

<br>

### 2. ViewModel에서 AlertController를 구성하는 로직을 가져도 괜찮은가?
`TaskListViewController`가 가지고 있는 `CollectionView`에 `UILongPressGestureRecognizer`를 달아주는 중에 발생한 고민입니다.

처음에는 `TaskListViewModel`에 UIAlertController를 생성하여 반환하는 함수를 정의해서 뷰모델에서 모든 구성을 해서 `TaskListViewController`에서는 해당 UIAlertController를 present만 하는 방식을 선택했었습니다.

하지만 뷰모델이 UI를 다룬다는 점이 뷰와 뷰모델 사이의 의존성을 증가시킨다고 생각했습니다. 
결론적으로 `TaskListViewController`에서 UIAlertController를 구성하게 하였고, 뷰모델에서는 `AlertAction`의 제목과 핸들러에서 해야할 작업을 수행하는 로직을 갖도록 하였습니다.

<br>
<br>

## 조언이 필요한 부분 :bow: 
### 1. bind 네이밍은 뷰와 뷰모델 연결할 때만 사용하는 것 일까요?
`TaskListViewModel`에서 `TaskManager`의 `taskList` 프로퍼티를 구독하고 있습니다. 구독을 하는 시점은 `TaskListViewModel`의 인스턴스가 생성되는 시점입니다. 

구독하는 행위를 `TaskListViewModel`의 `requestFilteredTaskList()`메소드에서 수행하도록 했는데요, 이때 네이밍을 뷰컨트롤러에서 한 것처럼 `bind~~`와 같은 방식으로 해야할지 아니면 보통 사용하는 네이밍 방식이 어떤게 있는지 궁금합니다. 엘림은 어떤 방식으로 네이밍 하시나요?

<br>

### 2. 반응형 프로그래밍의 방출-구독 구조
이번에 반응형 프로그래밍과 MVVM을 함께 적용하면서, 데이터의 전달 흐름에 대한 고민이 많았습니다.
가능하면 **Model → ViewModel → View**로의 일방향 전달을 지향하고자 했습니다. 그러다 보니 작은 기능을 구현하는데도 많은 어려움이 있었습니다. 필요한 경우 반대방향 혹은 양방향 방출으로 방출과 구독하는 구조도 괜찮을까요? :thinking:

### 2-1. 데이터 전달의 방향성 문제로 구현을 미룬 기능
<img src="https://hackmd.io/_uploads/HJDU8U9S3.png" width=400>

요구사항에 명세되어있지는 않았지만, 저희는 `title`과 `body`가 비어있을 때에는 **Done** 버튼을 비활성화하고자 했습니다.
이 기능을 구현하는 데 다음과 같은 문제가 있었습니다.
1. `TaskFormViewModel`이 `TaskFormViewController`의 UI요소인 `textField`와 `textView`의 변경을 구독하고 있어야 합니다. 이는 저희가 생각한 방향성과 맞지 않았습니다.
2. `TaskFormViewModel`이 `TaskFormViewController`의 UI요소를 구독한다면, `textField`와 `textView`가 비어있는 조건을 검사하기 위해 사용자가 텍스트를 작성 중에 계속해서 변경을 관찰하는게 맞는 방법일지에 대한 고민도 있습니다. 크든 작든 성능상의 문제도 있을것이라 생각됩니다.

저희가 생각한 기능을 깔끔하게 구현하기 위해 엘림의 조언을 여쭤보고 싶습니다!

2023-05-24 14:20 UTC, lina0322 requested changes
안녕하세요, 두 분! 구현하느라 고생 많으셨습니다.
새로운걸 다양하게 하면서 어려움과 고민이 많았겠네요ㅎㅎ 자세한 내용은 코멘트로 남겼고,
마지막 질문 관련해서만 첨언하겠습니당!

지금 하시는 방법대로 하다보면 ViewModel에서 View로의 단방향은 적용하기가 쉽죠ㅎㅎ 그리고 그렇게 하는 방향을 추구하고 있고요. 하지만 때로는 View에서 발생하는 사용자 입력이나 상태 변경에 따라서 ViewModel의 데이터를 업데이트해야 하는 일이 있을 수도 있다보니 양방향으로 데이터의 흐름이 발생할 수도 있겠죠. 
여기서! MVVM의 패턴 목표가 뷰와 모델 사이의 의존성을 낮추고, 재사용 가능한 컴포넌트를 분리하는 것으로 본다면 반드시 단향으로만 이루어져야 할 필요는 없을 것이라는게 제 생각입니다ㅎㅎ 

어쨌든 지금 이 사태(?)를 해결(?) 해보자면 저라면,

```swift
final class TaskFormViewModel {
  var title: String = "" {
    didSet {
      if title.isEmpty == false {
        isDone = true
      }
    }
  }
  @Published var isEditable: Bool
  @Published var isDone: Bool
   ...
}

...

final class TaskFormViewController: UIViewController {
  ...
  private func bindContentsEditable() {
    ...
    viewModel.$isDone
      .sink { [weak self] in
        self?.rightBarbutton.isEnabled = $0
      }
      .store(in: &subscriptions)
  }
}

...

extension TaskFormViewController: UITextFieldDelegate {
  func textFieldDidEndEditing(_ textField: UITextField) {
    viewModel.title = textField.text ?? ""
  }
}
```

이런 느낌으로 갈 것 같습니다! (코드 안돌려봤고 예를 들자면 이렇ㄷㅏ는 거에여.. 동작안할 수 있음 주의... 네이밍, 메서드 다 주의..ㅎㅋ)😀
도움이 되셨을까요? 혹시 ㅇㅣ해가 안가거나 이상하면 말씀해주세요. 
여러분이 가진 다른 의견도 있다면 말씀해주세용ㅎㅎㅎ(저도 컴바인을 많이 사용해보지 않은 상태라서 노력중입니답😉)

그럼 이번에도 화이팅!

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/Extension/DateFormatter+Deadline.swift
> +    }()
LGTM👍

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/Extension/UICollectionViewCell+IdentifierType.swift
> +extension UICollectionViewCell: IdentifierType {}
👏👏👏 IdentifierType이라는게 약간 네이밍이 아쉽긴하지만 요렇게 사용하는 부분 아주 좋습니다~

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/Main/MainViewController.swift
> +        navigationItem.title = "Project Manager"
사실 이 정도 규모에서는 상관 없긴 하지만, 그래도 String 관리하는거 잊지말아주세용!

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/Main/MainViewController.swift
> +        self.addChild(doneViewController)
지금까지의 컨벤션과 통일성을 지키기 위해서는 self는 제거해주세요~

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/Main/MainViewController.swift
> +    }
mainStackView를 생성할때 넣어줄 수도 있었을 것 같아요.
바꾸라는게 아니라 그런 방법도 있었을 것이라는거 알고계시라는 뜻의 코멘트입니당!

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/Main/MainViewController.swift
> +            mainStackView.bottomAnchor.constraint(equalTo: safe.bottomAnchor, constant: -safe.layoutFrame.height * 0.05)
요렇게 잡으신 이유가 궁금해요~

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/Model/State.swift
> +enum State: CaseIterable {
어떤 State인지 이름을 조금 더 구체화하면 좋겠어요~

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/Model/State.swift
> +    }
LGMT👍

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/Model/State.swift
> +        return (stateList[0], stateList[1])
인덱스 직접 접근을 피해주시고, 안전하게 접근하는 방법 사용해주세요~

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/Model/Task.swift
> +struct Task: Hashable {
Task도 이름 구체화하면 좋을거같아요.
아무래도 다른 곳에서도 많이 사용되는 이름들이기 때문ㅇㅔ prefix필요해보입니다

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/Model/TaskManager.swift
> +        guard let index else { return }
```suggestion
       guard let index = taskList.firstIndex(where: { $0.id == task.id }) else {
            return
      }
```
이렇게도 할 수 있을 것 같은데, 취향의 차이가 있을 것 같네요 :)

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/Model/TaskManager.swift
> +        taskList[index] = task
array에 안전하게 접근하기..!

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/TaskForm/TaskFormViewModel.swift
> +        taskManager.update(task: task)
`guard let task else { return }`를 맨 처음에 하는거랑 뒤에 하는거랑 다른가요??

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/TaskForm/TaskFormViewModel.swift
> +        taskManager.update(task: task)
만약에 이렇게 전부 다 값을 바꾸는거나 한번에 생성하는거라면
맨 아래처럼, Task를 생성해서 넘기는게 더 좋지 않을까 싶네요. 네이밍 때문인가🤔

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/TaskForm/TaskFormViewModel.swift
> +        }
```suggestion
        if task != nil {
            updateTask(title: title, date: date, body: body)
        } else if title != "" && body != "" {
            addTask(title: title, date: date, body: body)
        }
```
이게 좀 더 명확하지 않을까 싶긴한데요!

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/TaskForm/TaskFormViewModel.swift
> +    }
dismisss는 viewController의 동작이라서 여기서 네이밍을 이렇게 가지고 있으니까 혼란해요..!
viewController가 dismiss되는건 viewController를 봐야 알수있고, 여기서는 어떤 action을 받고 동작하는거니까 다른 이름이 필요할 것 같습니다..?!

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/TaskList/Cell/TaskListCell.swift
> +        backgroundColor = .white
요것도ㅎ_ㅎ 어딘가 들어가면 참 좋을텐데 마땅한 곳이 없었나요..

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/TaskList/Cell/TaskListCellViewModel.swift
> +            return .label
done일때는 빨간색이 아니어야 하지 않나용🧐

2023-05-24 14:20 UTC, lina0322 commented on ProjectManager/ProjectManager/App/Source/TaskList/Cell/TaskListCell.swift
> +            .store(in: &subscriptions)
뭔진 알겠는데.. 음
만약에 TaskListCellViewModel 내부에서 값이 변경이 된다면 Published가 되니까 bind이 효과가 있겠죠?

그럼 bind는 private으로 만들어서 init에서 호출하고 viewModel.updateContents(by: task)만 configure 메서드 따로 만들어서 cell datasource에서 task 받아오면 될거같은데,
실제적으로는 지금 값이 변경되면 datasource에서 변경되면서, 변경될때마다 init이 호출되는 상황이잖아욥?! 
즉 viewModel 내부에서 publish될 일이 없는 것으로 보이는데요🤔
여기서 꼭 bind를 해야할지 여러분의 의견이 궁금합니다.

2023-05-25 06:15 UTC, HarryHyeon commented on ProjectManager/ProjectManager/App/Source/Main/MainViewController.swift
> +            mainStackView.bottomAnchor.constraint(equalTo: safe.bottomAnchor, constant: -safe.layoutFrame.height * 0.05)
특별한 이유는 아니고, 요구사항의 화면과 동일하게 맞춰 주려고 아래쪽 여백을 조금 줬습니다 🤔

2023-05-25 11:07 UTC, HarryHyeon commented on ProjectManager/ProjectManager/App/Source/Extension/UICollectionViewCell+IdentifierType.swift
> +extension UICollectionViewCell: IdentifierType {}
ReuseIdentifying으로 네이밍 변경해주었습니다 ! 🫡

2023-05-25 11:07 UTC, HarryHyeon commented on ProjectManager/ProjectManager/App/Source/Main/MainViewController.swift
> +        self.addChild(doneViewController)
넵! 제거했습니다! 🫡

2023-05-25 11:07 UTC, kokkilE commented on ProjectManager/ProjectManager/App/Source/Main/MainViewController.swift
> +        navigationItem.title = "Project Manager"
따로 네임스페이스화 하면 한눈에 들어오지 않아 불편한 점이 있다고 생각해서, String을 지역 상수로 관리하도록 수정하였습니다.

2023-05-25 11:08 UTC, HarryHyeon commented on ProjectManager/ProjectManager/App/Source/Model/State.swift
> +        return (stateList[0], stateList[1])
`stateList.first, stateList.Last` 로 접근하도록 수정했습니다 !

2023-05-25 11:09 UTC, HarryHyeon commented on ProjectManager/ProjectManager/App/Source/Model/TaskManager.swift
> +        guard let index else { return }
오 넵! 저희도 한 줄로 적는게 더 좋은 것 같아서 수정했습니다 🫡

2023-05-25 11:10 UTC, kokkilE commented on ProjectManager/ProjectManager/App/Source/Main/MainViewController.swift
> +    }
현재 `mainStackView`를 프로퍼티 선언과 동시에 클로저로 생성하고 있는데, `mainStackView`를 생성할 때 넣어주면 `lazy var`로 정의해야 하는 점 때문에 현재 코드 유지하였습니다! 감사합니다 😄

2023-05-25 11:12 UTC, kokkilE commented on ProjectManager/ProjectManager/App/Source/Model/State.swift
> +enum State: CaseIterable {
어떤 State인지 알 수 있도록 `TaskState`로 네이밍 수정하였습니다!

2023-05-25 11:13 UTC, HarryHyeon commented on ProjectManager/ProjectManager/App/Source/TaskForm/TaskFormViewModel.swift
> +        taskManager.update(task: task)
`guard let task else { return }` 구문이 위쪽에 위치하는 것이나 아래쪽에 위치하는 것이나 동작은 같지만,
프로퍼티의 값도 바꿔주기 위해서 아래쪽에 위치하도록 했습니다.
혹여나 나중에 프로퍼티를 사용하게 되는 경우가 생길 수도 있다고 생각해서 아래쪽에 위치하게 했습니다 🤔

2023-05-25 11:15 UTC, kokkilE commented on ProjectManager/ProjectManager/App/Source/Model/Task.swift
> +struct Task: Hashable {
많은 고민을 하다가 `MyTask`라는 이름으로 수정해보았습니다.
보통 예제코드에서 많이 보던 접두어이긴 한데, 의미가 적절한 것 같다고 생각했습니다!

2023-05-25 11:17 UTC, HarryHyeon commented on ProjectManager/ProjectManager/App/Source/TaskForm/TaskFormViewModel.swift
> +        }
넵, 저런식으로 하는 조건 검사도 좋을 것 같습니다🫡

`else if` 의 조건식은 RightBarbutton의 활성/비활성을 체크함에따라 필요없게 되어 제거하였습니다 !

2023-05-25 11:17 UTC, kokkilE commented on ProjectManager/ProjectManager/App/Source/Model/TaskManager.swift
> +        taskList[index] = task
array의 index에 안전하게 접근하도록 `Array+subscript` 파일을 추가하여 `extension Array`에 `subscript`를 구현하였습니다!
범위에 벗어난 인덱스에 접근해도 크래시가 발생하지 않고 `nil`이 반환되도록 구현하였습니다.

2023-05-25 11:18 UTC, HarryHyeon commented on ProjectManager/ProjectManager/App/Source/TaskList/Cell/TaskListCell.swift
> +        backgroundColor = .white
setupView 메서드 안에 넣어주었습니다! 🫡

2023-05-25 11:20 UTC, HarryHyeon commented on ProjectManager/ProjectManager/App/Source/TaskList/Cell/TaskListCell.swift
> +            .store(in: &subscriptions)
넵.. 저희가 좀 잘못 생각하고 구현했던 것 같습니다.
엘림 말씀대로 dequeue 할때마다 bind가 호출되는 것은 불필요하다고 느꼈고, 해당 부분을 TaskListCell에 configure 메서드를 정의해 주었습니다. 
다만 색깔을 결정하는 로직은 뷰모델에 두어 색깔을 받을 수 있도록 수정했습니다 ! 🫡

2023-05-25 11:23 UTC, kokkilE commented on ProjectManager/ProjectManager/App/Source/TaskForm/TaskFormViewModel.swift
> +        taskManager.update(task: task)
update의 경우 `task`의 `id`를 변경하지 않도록 생성을 해서 넘기는게 아닌, 필요한 프로퍼티를 각각 할당하는 방법으로 구현하였습니다.

create의 경우 `doneAction` 메서드에서 생성까지 해서 넘기기보다는 파라미터로 전달받은 데이터를 그대로 `addTask` 메서드로 넘겨주고, `addTask` 메서드에서 `Task`를 생성하는게 말씀해주신 네이밍의 측면에서도 더 적합하다고 생각했습니다.

2023-05-25 11:24 UTC, kokkilE commented on ProjectManager/ProjectManager/App/Source/TaskForm/TaskFormViewModel.swift
> +    }
의견 반영하여 `cancelOrEditAction` 네이밍으로 수정해보았습니다!

2023-05-25 11:26 UTC, kokkilE commented on ProjectManager/ProjectManager/App/Source/TaskList/Cell/TaskListCellViewModel.swift
> +            return .label
저희가 명세에서 놓친 부분이 있었네요. 😭 
done일때는 빨간색이 되지 않도록 수정하였습니다!

2023-05-25 11:27 UTC, kokkilE commented
548b95e5df417145b7ffb868668e6781e6283965

`MyTask`의 `title`, `body`가 비어있을 경우 `Done` 버튼이 활성화되지 않도록 기능 추가 구현하였습니다!

2023-05-28 08:28 UTC, lina0322 approved these changes
고생하셨습니다~ 다음스텝에서 또 만나요😉

2023-05-28 08:28 UTC, merged