프로젝트 매니저 [STEP 2] 리지
yagom-academy/ios-project-manager pull request #276
Opened 2023-05-24 06:58 UTC by yijiye

안녕하세요! 올라프(@1Consumption)
이번 프로젝트에서 MVVM과 Combine을 이해하고 적용하는것이 굉장히 어려웠습니다..!
올라프의 피드백을 받아야 좀 더 확실한 개념이 잡힐 거 같아 많이 부족하지만 PR 올렸습니다.
그럼 잘 부탁드립니다!! 🙇‍♂️

# 고민했던 점

## 1️⃣ 화면간 데이터 전달

새로운 할일을 작성하고 그 화면을 닫으면 메인 화면에서 저장된 Todo가 나타나야 하는데, 이때 화면간 저장된 item을 어떻게 주고받으면 좋을지 고민하였습니다. 

처음 생각한 방법은 `PassthrougSubject`를 만들어 던져주는 것이였는데, LLDB로 찍어보니`Cancellable` 카운트가 계속 쌓이는 것을 확인했고 이걸 사용하면 스트림이 계속 증가하는 문제가 있다고 판단했습니다.

**기존코드**
```swift
// 메인 VC
@objc func plusButtonTapped() {
        let plusTodoViewController = PlusTodoViewController()
        plusTodoViewController.subject
            .map { $0 }
            .sink { item in
                self.todoListViewModel.saveTodoItem(title: item.title, body: item.body, date: item.date)
            }
            .store(in: &cancellables)

        present(plusTodoViewController, animated: false)
    }

// PlusTodoVC
 let subject = PassthroughSubject<TodoItem, Never>()
@objc private func doneButtonTapped() {
        guard let title = self.titleField.text,
              let body = self.textView.text else { return }
        let date = self.datePicker.date
        
        let item = TodoItem(title: title, body: body, date: date)
        subject.send(item)
        self.dismiss(animated: false)
    }

// TodoListViewModel
final class TodoListViewModel {
    
    @Published var todoItems: [TodoItem] = []
    
    var numberOfItems: Int {
        return todoItems.count
    }
    
    func item(at index: Int) -> TodoItem {
        return todoItems[index]
    }
    
    func saveTodoItem(title: String, body: String, date: Date) {
        let item = TodoItem(title: title, body: body, date: date)
        todoItems.append(item)
    }
}
```

이러한 문제 때문에 viewModel에 item의 값을 변경하도록 로직을 수정하였습니다. 이때, Todo 작성하는 화면에서 메인 화면의 viewModel을 갖고 있고 그 viewModel을 통해서 값을 변경한다면 메인 화면의 viewModel과 여러 view가 연결되어 독립성이 떨어진다고 생각하였습니다. 그래서 `Delegate`를 활용하여 viewModel의 item의 값을 변경하도록 수정하였습니다. 

**그런데 이런 상황에서 여러개의 view가 하나의 viewModel에 접근을 해도 문제가 없는 걸까요?** 

## 2️⃣ TableViewCell 이동

todo-doing-done 3개의 tableView에서 cell을 이동시킬 때, 어떤 값을 관찰하여 `tableView`를 reload 할지 고민하였습니다.

- 처음 시도한 방법
viewModel에 `@Published var State` 변수를 두고 viewController에서 구독하여 변화가 생길 때 마다 `tableView.reloadData()` 하도록 하였으나 이는 cell 자체의 State가 아니라 특정 상황에서 오류가 발생하였습니다.
- 리팩토링한 방법
`tableView.reloadData()`는 item이 변화를 구독할 때 해주고 State를 model인 `TodoItem`이 가지고 있도록 하여 값이 추가되거나 다른 `tableView`로 이동할 때 새로운 값으로 업데이트 해주는 방법으로 리팩토링 하였습니다.

이때, 한가지 문제였던 부분은 `@Published` 공식문서에 따르면 `@Published`를 구독할 때 `willSet block`에서 발생하여 변화가 생기고 화면에 업데이트 해주는 순서가 맞지 않았습니다. (예를들어, item은 사라졌는데 화면의 tableView에서는 사라지지 않는 경우) 
이를 해결하고자 update가 모두 완료된 후에 completion block이 호출되도록 해주는 `tableView`의 `performBatchUpdate`를 활용하였습니다.

```swift
// PlanViewController - buttonTapped method 구현부
delete(indexPath)
tableView.deleteRows(at: [indexPath], with: .fade)
tableView.performBatchUpdates(nil, completion: { [weak self] _ in
    updateItem.state = new
    self?.addItem(updateItem)
})
```

## 3️⃣ 지난 날짜 색상 변경

지난 날짜는 빨간색으로 표시되도록 하기 위해 처음 시도한 방법은 `Date`를 활용하는 것이였습니다. `Date`를 활용하니 초단위까지 시간이 측정되어 같은 날짜에 작성해도 과거로 인식되어 빨간색으로 바뀌는 문제가 있었습니다.

이를 해결하고자 `Date` 대신 `Calendar`를 활용하였습니다.

```swift
func compareDate(from date: Date) -> Tense {
        let now = Date()
        let calendar = Calendar.current
        let result = calendar.compare(now, to: date, toGranularity: .day)
        
        switch result {
        case .orderedAscending:
            return .future
        case .orderedSame:
            return .present
        case .orderedDescending:
            return .past
        }
    }
```

DateFormatManager를 구현하여 날짜를 비교해주는 메서드를 정의하였고, Cell에 보여지는 부분이라 `PlanTableCellViewModel`을 만들어 이곳에서 비즈니스 로직을 처리하였습니다.

# 해결하지 못한 점 

## LongPressGesture와 System gesture 간의 충돌 문제

tableView의 Cell을 꾹 느르면 콘솔창에 `[SystemGestureGate] <0x123a05a50> Gesture: System gesture gate timed out.` 라는 문구가 출력되는 문제가 있습니다. 찾아보니 system gesture와 longPress gesture간 충돌이 일어나서 발생하는 오류라는 것을 알게되었습니다.

```swift
 func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
     ...
 }

extension PlanViewController: UIGestureRecognizerDelegate {
    private func setUpLongPressGesture() {
        ...
    }
}
```

이 두가지의 gesture를 분리하고자 시도하였는데 결국 해결하지 못했습니다 🥲
해결하기 위해 아래 2가지를 적용시켜보았습니다.

- `longpressgesture.delayTouchesBegan = true`
제스처 인식기가 시작 단계에서 터치를 보내는 것을 지연시키는지 여부를 결정하는 bool 값을 true로 주어 longpressgesture보다 tap이 먼저 되도록 함
- 두 제스쳐가 동시에 적용되지 않도록 return 값 false로 변경
 ```swift
func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        return false
    }
```

작동이 안되는 문제는 없어진 것 같으나 콘솔창에 오류는 계속해서 나타나고 있는데, 제가 문제의 원인을 잘못 파악하고 있는 것인지...혹시 시도해볼 다른 방법이 있는지 궁금합니다!

# 조언을 구하고 싶은 점

## Actionsheet를 띄우는 로직의 위치

저의 코드에서 Longpress를 처리하는 메서드에서 제스쳐가 시작이 되면 actionsheet가 뜨도록 되어있습니다. 이 부분을 작성하면서 view가 가져도 될 부분과 view가 알 필요가 없는 부분이 혼합되어 있다고 생각했습니다.
- view: actionSheet의 화면 요소 (타이틀이나 화면에 나타나는 위치를 잡는 부분)
- viewModel: 상황에 따라 item의 state를 변경하는 로직

그래서 이를 viewModel로 분리하려고 시도했는데, tableView가 어떤 tableView인지 알아야 하는 로직이라 viewModel로 옮기기가 어려웠습니다.
그래서 현재는 viewController에 모든 코드가 들어있게 되었습니다. 이렇게 view와 로직이 섞여 있는 경우는 어떤 기준점을 가지고 나눌 수 있을까요? 🧐

2023-05-24 23:29 UTC, 1Consumption requested changes
고생하셨습니다.
MVVM과 Combine을 같이 공부하면서 적용하는게 쉽지 않은 일이라 생각됩니다.
하여 대부분 잘 구성해주셨는데, 분명히 아쉬운 점도 있습니다.

1. `PlanViewController`가 너무 많은 일을 하고 있습니다. 이에 따라 `PlanViewModel` 또한 너무 많은 일을 하고 있습니다. 그러다보니 `itemState`을 바꿔가며 로직을 수행하고 있는데요, 이때문에 항상 현재의 `itemState`는 무엇인지를 신경써야합니다. 이는 디버깅할 때 트래킹하기가 쉽지 않습니다.
실제로 현재 추가, 삭제, 이동 동작이 완벽하지 않습니다. 아이템을 여러개 생성하고 이동 후 삭제 동작을 수행하면 앱이 죽거나 엉뚱한 아이템이 삭제되곤 합니다.

하여 이 부분은 `PlanViewController`, `PlanViewModel`의 역할을 보다 더 작은 단위로 나누는 방향을 잡았으면 좋겠습니다. 각각의 `UITableView`를 기준으로 viewModel을 작성해보세요. 그렇다면 `PlanViewController`, `PlanViewModel`에서 수행하던 `UITableView`에 대한 로직 또는 UI를 분리할 수 있을 것이고 `PlanViewController`, `PlanViewModel`는 `tableView 관리 및 통신` 라는 보다 명확한 역할을 가질 수 있을 것입니다.

2. 수정 기능이 구현되어있지 않습니다.
`PlusTodoViewController`이 `PlanViewController`에게 값을 넘길 때는 delegate를 사용해도 좋고, `PlanViewModel`의 publisher를 `PlusTodoViewModel`이 받아서 값을 넘겨도 좋을듯합니다.

나머지는 코멘트를 참고해주세요.

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/CircleLabel.swift
> +    }
왜 draw 시점에 이 코드를 작성하셨나요?

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/CircleLabel.swift
> +        layer.masksToBounds = true
이 코드는 여기에 있어야할까요? init에 있어야할까요?

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +    private var seperatorView = UIView()
var인 이유가 있을까요?

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +    private let title = UILabel()
label이 빠졌네요.

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +    }
오토레이아웃을 사용하지 않은 이유가 있나요?

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ViewController/PlanViewController.swift
> +    private var cancellables: Set<AnyCancellable> = []
`Set<AnyCancellable>`은 왜 필요한가요?

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ViewController/PlanViewController.swift
> +    private lazy var doneHeader = HeaderView(text: "DONE", frame: CGRect(x: 0, y: 0, width: todoTableView.frame.size.width, height: 60))
frame으로 잡아주는 이유가 있나요? 어디는 오토레이아웃을 사용하고, 어디는 frame을 사용하셨는데 기준이 궁금합니다.

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ViewController/PlanViewController.swift
> +    }
똑같은 코드가 반복되고 있네요. 아래에도 똑같은 코드가 반복됩니다. 별도의 클래스로 분리하는건 어떨까요?

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ViewController/PlanViewController.swift
> +            tableStackView.bottomAnchor.constraint(equalTo: safeArea.bottomAnchor, constant: -20),
-20은 왜 해줬나요? 이 숫자의 의미는 뭔가요? 매직넘버보다는 이름을 지어주세요.

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ViewController/PlanViewController.swift
> +    @objc func plusButtonTapped() {
private이 빠졌네요.

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ViewController/PlanViewController.swift
> +            .store(in: &cancellables)
여기서 [weak self]는 왜 해줘야하나요?

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ViewController/PlanViewController.swift
> +            .store(in: &cancellables)
변경점만 업데이트하면 안될까요? 이러면 변경사항이 생길 때마다 매번 tableView를 다시 그리지 않나요?

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/ViewController/PlanViewController.swift
> +        })
이 동작은 여기서 할게아니라 viewModel의 상태 구독하고 있는 클로저에서 해야할 것 같아요.

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/PlanTableViewCell.swift
> +    }()
왜 lazy var인가요?

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/PlanTableViewCell.swift
> +            }.store(in: &cancellables)
여기는 [weak self]가 필요 없나요?

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/PlanTableViewCell.swift
> +    }
굳이 옵셔널바인딩을 해주지 않아도 될 것 같습니다.

```suggestion
    func fetchCellItem() -> TodoItem? {
        return planTableCellViewModel?.fetchItem()
    }
```

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/PlanViewModel.swift
> +    @Published private(set) var doneItems: [TodoItem] = []
Published 말고 다른 Subject를 사용할 수 있을까요?

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/PlanViewModel.swift
> +        itemState = item.state
저는 이 itemState 때문에 가독성이 정말 좋지 못하다고 생각합니다. 디버깅도 어렵고요. 하나의 뷰모델에서 모든 것을 하지말고, 적당히 나누는건 어떨까요? 이건 위에 코멘트 드렸던 중복되는 view를 분리하는 것과 연관된 코멘트입니다.
나눈 view에는 각각의 viewModel이 있겠죠.

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/PlanViewModel.swift
> +    }
viewModel이 view를 알고있어야하나요?

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/PlusTodoViewModel.swift
> +    private(set) var mode: Mode = .create
이 mode는 viewMode의 상태가 아닌가요? 이것도 viewo가 관찰해야할 값 같은데요.

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/PlanTableViewCell.swift
> +final class PlanTableViewCell: UITableViewCell {
cell은 재사용이 되는데, 그렇다는 것은 `cancellables`가 deinit되지 않는다는 것이죠. 그렇다면 `cancellables`에 저장된 `AnyCancellable`들도 계속 남아있지 않을까요?

2023-05-24 23:29 UTC, 1Consumption commented on ProjectManager/ProjectManager/Model/TodoItem.swift
> +    let body: String
title과 body는 바뀔일이 없나요?

2023-05-24 23:29 UTC, 1Consumption requested changes
고생하셨습니다.
MVVM과 Combine을 같이 공부하면서 적용하는게 쉽지 않은 일이라 생각됩니다.
하여 대부분 잘 구성해주셨는데, 분명히 아쉬운 점도 있습니다.

1. `PlanViewController`가 너무 많은 일을 하고 있습니다. 이에 따라 `PlanViewModel` 또한 너무 많은 일을 하고 있습니다. 그러다보니 `itemState`을 바꿔가며 로직을 수행하고 있는데요, 이때문에 항상 현재의 `itemState`는 무엇인지를 신경써야합니다. 이는 디버깅할 때 트래킹하기가 쉽지 않습니다.
실제로 현재 추가, 삭제, 이동 동작이 완벽하지 않습니다. 아이템을 여러개 생성하고 이동 후 삭제 동작을 수행하면 앱이 죽거나 엉뚱한 아이템이 삭제되곤 합니다.
하여 이 부분은 `PlanViewController`, `PlanViewModel`의 역할을 보다 더 작은 단위로 나누는 방향을 잡았으면 좋겠습니다. 각각의 `UITableView`를 기준으로 viewModel을 작성해보세요. 그렇다면 `PlanViewController`, `PlanViewModel`에서 수행하던 `UITableView`에 대한 로직 또는 UI를 분리할 수 있을 것이고 `PlanViewController`, `PlanViewModel`는 `tableView 관리 및 통신` 라는 보다 명확한 역할을 가질 수 있을 것입니다.

2. 수정 기능이 구현되어있지 않습니다.
`PlusTodoViewController`이 `PlanViewController`에게 값을 넘길 때는 delegate를 사용해도 좋고, `PlanViewModel`의 publisher를 `PlusTodoViewModel`이 받아서 값을 넘겨도 좋을듯합니다.

나머지는 코멘트를 참고해주세요.

2023-05-29 03:36 UTC, yijiye commented on ProjectManager/ProjectManager/ViewModel/PlanViewModel.swift
> +    }
viewModel에서는 view를 알 필요가 없다는 것을 놓친 것 같습니다.
따라서 viewModel에서 삭제해주고, 리팩토링하면서 세부 viewController을 나눠 이 코드는 불필요하여 삭제하였습니다.

2023-05-29 03:42 UTC, yijiye commented on ProjectManager/ProjectManager/ViewModel/PlanTableViewCell.swift
> +    }()
lazy var로 할필요가 없어 `let`으로 수정하였습니다.

2023-05-29 03:44 UTC, yijiye commented on ProjectManager/ProjectManager/View/ViewController/PlanViewController.swift
> +            tableStackView.bottomAnchor.constraint(equalTo: safeArea.bottomAnchor, constant: -20),
-20을 준 이유는 명세와 같은 화면을 구현하기 위해 bottom에서 어느정도 띄우도록 구현하고자 준 값입니다.
매직넘버 대신 `let bottomConstant: CGFloat = -20` 라는 상수를 만들어 값을 주도록 수정하였습니다!

2023-05-29 06:06 UTC, yijiye commented on ProjectManager/ProjectManager/View/CircleLabel.swift
> +    }
처음에 Label의 원을 직접그려야한다는 생각에 draw 메서드를 정의하였습니다. 
그런데 현재 코드에서는 직접 그리지 않고 layer 속성설정만 해주기 때문에 뷰의 크기가 변경될때마다 호출되는  `layoutSubviews()` 메서드에 재정의 하는 것으로 수정하였습니다.

2023-05-29 06:14 UTC, yijiye commented on ProjectManager/ProjectManager/View/CircleLabel.swift
> +        layer.masksToBounds = true
공식문서에 확인해보니  `If your custom view is a direct NSView subclass, you do not need to call super.` 이라고 나와있는 것으로 보아 직접적인 NSView의 서브클래스인경우 호출하지 않아도 되는 것으로 이해하였습니다. 
리팩토링 과정에서 draw 메서드가 불필요하여 현재는 삭제하였습니다.

2023-05-29 06:16 UTC, yijiye commented on ProjectManager/ProjectManager/View/HeaderView.swift
> +    }
처음에 stackView안에 TitleLabel, countLabel을 넣어주었더니 countLabel의 크기를 잡아도 stackView를 꽉채워서 사이즈 조절이 어렵다는 문제가 있었습니다. 그래서 따로 분리하는 과정에서 직접 값을 할당하게 되었습니다.
올라프의 피드백을 받고 한가지 방법으로 통일하는 것이 일관성있는 코드라 생각하여 오토레이아웃을 잡아주는 방법으로 리팩토링하였습니다!

2023-05-29 06:32 UTC, yijiye commented on ProjectManager/ProjectManager/View/ViewController/PlanViewController.swift
> +    private var cancellables: Set<AnyCancellable> = []
@Published annotation이 붙어있는 프로퍼티를 관찰하여 구독할 때, sink를 사용하였습니다.
sink의 구조를 확인해보면 

```swift
func sink(receiveValue: @escaping ((Self.Output) -> Void)) -> AnyCancellable
```

이런 구조로 이루어져있고, 리턴값이 AnyCancellable을 확인할 수 있었습니다. 
이 리턴값을 하나의 변수에 저장하여 여러개의 구독을 동시에 관리하고 일괄적으로 취소하기 위해 사용됩니다.
필요한 시점에 한꺼번에 해당 변수를 사용하여 구독취소를 할 수 있다는 장점이 있습니다.

2023-05-29 07:00 UTC, yijiye commented on ProjectManager/ProjectManager/View/ViewController/PlanViewController.swift
> +    private lazy var doneHeader = HeaderView(text: "DONE", frame: CGRect(x: 0, y: 0, width: todoTableView.frame.size.width, height: 60))
tableView의 header를 custom으로 만들면서 원하는 높이를 직접 frame으로 잡았습니다.
이 부분에서는 autolayout으로 잡는 것 보다 header에 들어갈 view를 직접 그리면서 값을 주는 것이 더 직관적이라 생각하여 이렇게 작성하게 되었습니다.

2023-05-29 07:01 UTC, yijiye commented on ProjectManager/ProjectManager/View/ViewController/PlanViewController.swift
> +            .store(in: &cancellables)
강한 순한 참조가 발생하면 메모리 누수 위험이 있고 이를 방지하고자 약한 참조를 하도록 weak self를 사용하였습니다!

2023-05-29 07:03 UTC, yijiye commented on ProjectManager/ProjectManager/View/ViewController/PlanViewController.swift
> +            .store(in: &cancellables)
전반적인 로직이 수정되면서 이 부분도 같이 수정되었습니다.
간략하게 현재는 해당 tableView의 plan 배열을 구독하면서 값이 변할 때, tableView가 reload하도록 구현되어있습니다.

2023-05-29 07:03 UTC, yijiye commented on ProjectManager/ProjectManager/ViewModel/PlanTableViewCell.swift
> +            }.store(in: &cancellables)
self를 접근하고 있는 곳에서 약한 참조를 하도록 수정하였습니다.

2023-05-29 07:05 UTC, yijiye commented on ProjectManager/ProjectManager/ViewModel/PlanViewModel.swift
> +    @Published private(set) var doneItems: [TodoItem] = []
하위 뷰컨에서 하위 뷰모델의 메서드에 접근할 때, passthroughSubject를 활용하여 값을 넣어주면 이를 관리하는 메인뷰모델에서 구독하여 메서드가 실행되도록 적용해보았습니다.

2023-05-29 08:38 UTC, yijiye commented on ProjectManager/ProjectManager/ViewModel/PlusTodoViewModel.swift
> +    private(set) var mode: Mode = .create
view의 상태에 따라 로직이 달라진다고 생각해서 viewModel에 구현했었는데, 올라프의 의견대로 view의 Mode가 맞아 view로 옮겼습니다!

2023-05-29 08:50 UTC, yijiye commented on ProjectManager/ProjectManager/ViewModel/PlanTableViewCell.swift
> +final class PlanTableViewCell: UITableViewCell {
https://github.com/yagom-academy/ios-project-manager/pull/276/commits/a435e48e3cead77f514184871f6d609abbab0b88
이 부분은 아예 생각도 못했었는데 실제로 디버깅해보니 계속 쌓이는 것을 확인할 수 있었습니다. 🥲
cell 이 재사용될때 속성을 초기화시켜는 `prepareForReuse()`메서드에서 삭제해주도록 구현하였습니다.

2023-05-29 09:26 UTC, yijiye commented
올라프 안녕하세요! 리팩토링하는데 너무 많은 시간이 걸린 것 같습니다.
MVVM 패턴에 대한 목적은 명확히 이해했는데, 이를 적용하고 응용시키는 과정이 어려웠던 것 같습니다.

제가 리팩토링한 구조를 그림으로 간단히 정리해보았습니다.

<img src="https://hackmd.io/_uploads/rk6No1MI2.png" width="600">


### 화면구성

메인이 되는 `PlanManagerVC`안에 `PlanVC`를 3개를 만들어주고 이를 stackView로 관리하고 있습니다.

### VC와 VM 구성

`planManagerVM`이 하위 `planVM`을 관리하는 역할로 봤을 때, 저장되는 모든 plan을 `planMangerVM`이 가지고 있고 이를 filter해서 나눠가져야 한다고 생각했습니다.
그래서 새로 저장된 값이 있으면 `planManagerVM`의배열에 들어오게 되고 이를 구독하여 filter 후 각 VM에 전달하도록 했습니다.

그럼 전달받은 VM은 각 VC에서 필요한 메서드를 받아서 수행해야 하는데, 여기서 어떻게 ViewController의 관계랑 ViewModel의 관계를 이어야하는지 고민했습니다.
- `tableView`를 띄우는 역할은 결국 `planVC`가 하는데, 그 `planVC`의 `viewModel`을 관리하는 것은 `PlanManagerViewModel`이라 어떻게 나눠야하지? 이 고민을 굉장히 오랫동안 했습니다.

저는 그림과 같이
- `PlanVC`에서 삭제, 업데이트, 교체와 같은 메서드가 필요할때 해당 `viewModel`의 메서드 호출
- `viewModel`의 메서드가 호출되면 각 `subject`에 값을 send
- `subject`를 `PlanManagerVM`이 관찰하여 메서드를 호출
와 같은 방법으로 해결하였습니다.

이렇게 구현했을 때, `planManagerVM`이 하위 `viewModel`을 관리하는 역할을 하고 있고,`planVC`는 해당`viewModel`을 통해 일을 처리하게 되므로 하나의 VC가 하나의 VM을 가지고 있게 된다고 생각하였습니다. 

### 기타
edit 모드는 edit버튼을 누르면 알림창이 떠 사용자에게 알려주고 변경사항을 입력 후 Done 버튼을 누르면 적용되도록 구현하였습니다!
(나머지 리팩토링 한 부분은 코멘트에 달아두었습니다.)

그럼 올라프의 피드백 기다리겠습니다!!

2023-05-29 23:46 UTC, 1Consumption reviewed
정말 큰 작업이 있었네요. 고생하셨습니다.
어느정도 익숙해지신 것 같네요👍

코멘트를 참고해주세요.

2023-05-29 23:46 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/PlanManagerViewModel.swift
> +                }
이 filter도 오퍼레이터로 처리할 수 있을 것 같습니다.

2023-05-29 23:46 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/PlanManagerViewModel.swift
> +    }
이게 하위 viewModel인지 아닌지는 알 필요가 없다고 생각해요. 하위 viewModel에서 필요한 정보만 프로토콜로 빼는건 어떨까요?

2023-05-29 23:46 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewController/PlanManagerViewController.swift
> +    }
딜리게이트 메소드였군요. 저는 딜리게이트 메소드를 extension으로 빼서 명시를 하는 편입니다.
이렇게 보니까 갑자기 internal 메소드가 나와서 뜬금없기도하고요.

추가적으로 메소드의 이름에서 로직을 알고 있다고 생각해요. view의 이벤트를 이름으로 하는건 어떨까요? 예를 들자면 어떤 버튼이 눌린 것에 대한 이벤트면 `버튼이 눌렸다`가 메소드 이름이 되겠죠.

2023-05-29 23:46 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewController/PlanViewController.swift
> +    }
매번 reloadData를 부르는건 조금 아쉬운데, 변경된 부분만 업데이트할 수는 없을까요?

2023-05-29 23:46 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/State.swift
> +    }
`description` 프로퍼티는 `CustomStringConvertible` 프로토콜의 프로퍼티인데, 공식문서에는 이 프로퍼티를 직접 호출하는 것을지양하라 라고 되어있습니다. 문자열 보간법을 사용해보세요.
https://developer.apple.com/documentation/swift/customstringconvertible/description

2023-05-29 23:46 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewController/PlusTodoViewController.swift
> +    weak var delegate: SavingItemDelegate?
delegate와 viewModel을 나눈 차이는 뭔가요?

2023-05-31 02:10 UTC, yijiye commented on ProjectManager/ProjectManager/ViewModel/PlanManagerViewModel.swift
> +    }
```swift
protocol PlanSubscriber {
    func updatePlan(_ plans: [Plan])
    var deletePublisher: PassthroughSubject<Plan, Never> { get set }
    var changePublisher: PassthroughSubject<(Plan, State), Never> { get set }
}
```
PlanSubscriber라는 protocol을 만들어 적용시켰습니다!

2023-05-31 02:13 UTC, yijiye commented on ProjectManager/ProjectManager/ViewController/PlanManagerViewController.swift
> +    }
```swift
extension PlanManagerViewController {
    func doneButtonTappedForSaving(_ plan: Plan) {
        viewModel.create(plan)
    }
    
    func doneButtonTappedForResaving(_ plan: Plan) {
        viewModel.update(plan)
    }
}
```

올라프의 의견대로 따로 분리해서 관리하는 것이 더 깔끔해보여 분리하였습니다.
네이밍은 저장을 위한 버튼이 눌렸다는 의미와 변경사항을 저장하기위해 버튼이 눌렸다는 의미의 네이밍을 붙였습니다.

2023-05-31 02:13 UTC, yijiye commented on ProjectManager/ProjectManager/ViewController/PlanViewController.swift
> +    }
어제 의논 후 DiffableDataSource, Snapshot을 적용시켜 리팩토링하였습니다!

2023-05-31 02:16 UTC, yijiye commented on ProjectManager/ProjectManager/ViewController/PlusTodoViewController.swift
> +    weak var delegate: SavingItemDelegate?
`PlanManagerViewController`에 addChild로 더해지는 뷰컨은 viewModel로 처리했고
present로 띄우는 경우는 delegate를 처리하였습니다.

2023-05-31 02:54 UTC, 1Consumption approved these changes

2023-05-31 02:54 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewController/PlanViewController.swift
> +            cell.configureCell(with: plan)
3번째 인자를 사용하면 굳이 뷰모델에서 값을 읽어오지 않아도 될 것 같습니다~

2023-05-31 02:54 UTC, merged