프로젝트 매니저 [STEP 2] 레옹아범
yagom-academy/ios-project-manager pull request #277
Opened 2023-05-24 11:27 UTC by fatherLeon

@AppleCEO
안녕하세요 도미닉 
STEP2 UI는 크게 어려움?은 없었지만 MVVM은 처음이다보니 해당 메서드를 뷰 컨트롤러가 가지고 있는게 맞을지 뷰 모델이 온전한 역할을 하고 있는지에 대한 여부 등에 대해 어려움이 많은 스텝인 것 같습니다😅

## 구현

|삭제|할 일 이동|할 일 수정|
|:--:|:--:|:--:|
|![delete](https://github.com/yagom-academy/ios-project-manager/assets/55453151/0a701075-15bc-45d4-b2bd-474366117ba3)|![Moving](https://github.com/yagom-academy/ios-project-manager/assets/55453151/fdcc9a6c-7358-4e2b-ac7c-a075db965b03)|![Editing](https://github.com/yagom-academy/ios-project-manager/assets/55453151/699db530-bc54-4a8b-ad20-c48d944b0e1c)|

## 고민한 점
### 1️⃣ shadowPath
```
The layer is using dynamic shadows which are expensive to render. If possible try setting `shadowPath`, or pre-rendering the shadow into an image and putting it under the layer.
```

* `TodoViewController`내에서 UI그림자를 줄 경우 shadowPath를 주라는 메시지가 있어 shadowPath를 주었습니다.
* 다만 shadowPath를 줄 때 크기를 해당 뷰에 맞는 크기를 주기위해서는 `viewDidLoad`시점에서는 줄 수 없기 때문에 뷰의 크기가 결정 된 이후인 `viewDidAppear`시점에서 그림자를 주도록 설정하였습니다.

### 2️⃣ TextView의 그림자
* `UITextView`의 그림자를 주기위해서 `layer.masksToBound`를 `false`로 주어야하는데 이럴 경우 `UITextView`가 여러줄이 될 때 경계 바깥에서 글자가 보이는 문제가 존재했습니다.
* 따라서 `UIView`안에 `UITextView`를 넣고 `UIVew`에 그림자를 넣어 그림자가 보이도록 구현하였습니다.

### 3️⃣ 할일 이동 메뉴 표시
* 기존 `UIAlertController`를 통하여 구현을 할려했지만 스크롤이 될 경우 원하지 않는 `Task`가 이동되거나, 다른 뷰에서 해당 뷰가 표시되는 문제가 있어 `UIMenu`를 통하여 구현하였습니다.

## 조언을 얻고 싶은 부분
### 1️⃣ MVVM구조
* 뷰의 경우 뷰모델을 통해서만 UI를 표현하고 주요 로직을 뷰모델이 가지고 있어야 할 것 같은데 `ListViewController`의 경우 특정 핸들러, 혹은 `DiffableDatasource`를 통한 `snapshot`의 `apply`메소드 등을 뷰 컨트롤러가 가지고 있어 올바른 MVVM 구조를 구현한 것인지에 대한 의문이 있습니다.

2023-05-25 04:36 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@fatherLeon 고생하셨습니다.
몇가지 생각할 점들 남겨봤습니다.

질문에 대한 답변 

MVVM구조

뷰의 경우 뷰모델을 통해서만 UI를 표현하고 주요 로직을 뷰모델이 가지고 있어야 할 것 같은데 ListViewController의 경우 특정 핸들러, 혹은 DiffableDatasource를 통한 snapshot의 apply메소드 등을 뷰 컨트롤러가 가지고 있어 올바른 MVVM 구조를 구현한 것인지에 대한 의문이 있습니다.
-> 완벽한 아키텍처는 없다고 생각합니다. 그리고 완전히 구현하기도 각자 생각하는게 달라서 어렵고요. 이런 이유들로 저는 코드 리뷰를할 때 구조적인 것보다 문법이나 이름을 위주로 보는데요. 내가 의도한대로 뷰모델이 반응을 해서 처리할 수 있다면 잘 짜신 것이라고 생각합니다.

2023-05-25 04:36 UTC, AppleCEO commented on ProjectManager/ProjectManager/Extension/Date+Extension.swift
> +}
보통 필요한 기능이 있으면 이렇게 extension 으로 많이 구성하시던데 저는 선호하지는 않습니다.
저는 YGFormatter 등의 별도 구조체를 만들어서 static func 로 구현하는 걸 선호하는데요.
두가지 방법이 어떤 장단점이 있을까요? 이렇게 extension 으로 구성한 이유가 있을까요?

2023-05-25 04:36 UTC, AppleCEO commented on ProjectManager/ProjectManager/Extension/Notification.Name+Extension.swift
> +}
저도 이렇게 여러 Notification 을 관리하고 있네요! 👍

2023-05-25 04:36 UTC, AppleCEO commented on ProjectManager/ProjectManager/MainScene/View/TaskHeaderView.swift
> +    }
prepareForReuse 메소드로 셀이 재사용될 때 값을 비워주는 것 좋네요! 💯

2023-05-25 04:36 UTC, AppleCEO commented on ProjectManager/ProjectManager/MainScene/View/TaskListCell.swift
> +    private let dateLabel = {
조금 더 좋은 이름 있을 것 같아요.
작성한 날짜인지? 수정한 날짜인지? 완료 데드라인인지 등에 따라서요.
항상 자세한 이름으로 작성해주는 것이 좋습니다.
변수명은 길어질 수록 뜻이 정확해진다고 생각합니다 ㅎㅎ

2023-05-25 04:36 UTC, AppleCEO commented on ProjectManager/ProjectManager/MainScene/ViewController/TodoViewController.swift
> +    }
한 줄 짜리 코드를 작성해보셨군요! 🥇 
이렇게 함수로 한 줄 짜리를 빼서 다른 함수에서 호출하는 것과 이 한 줄을 바로 호출하는 것 어떤 차이점이 있을까요?
이 방식을 선택한 이유는 무엇인가요?

2023-05-25 04:36 UTC, AppleCEO commented on ProjectManager/ProjectManager/MainScene/ViewModel/MainViewModel.swift
> +
이 코드 너무 복잡하네요 ㅎㅎ
개발을 잘하는 사람은 여러 동작을 하는 코드를 짧게 작성하려고 하지 않고 풀어서 명확하게 쓰고자 노력합니다.
이 부분 풀어서 이해하기 쉽게 작성해 볼 수 있을까요?

2023-05-25 04:36 UTC, AppleCEO commented on ProjectManager/ProjectManager/MainScene/ViewModel/TodoViewModel.swift
> +              backspaceValue == -92 else { return false }
저는 여기 부분은 한 줄로 작성하면 좋겠습니다.
저는 보통 guard 안에 부분을 한 줄로 작성하는 편인데요.
이렇게 하면 작성한 사람은 보기 쉬울 수 있겠지만 다른 사람은 or를 보려고 하는데 다음 줄까지 봐야하고 복잡하게 느낄 수 있습니다!

2023-05-25 04:36 UTC, AppleCEO commented on ProjectManager/ProjectManager/MainScene/ViewModel/TodoViewModel.swift
> +              description != "" else { throw GeneratedTaskError.descriptionEmpty }
여기 guard 의 조건 부분을 한 줄로 작성해보고 기본형으로 한번 변경해볼까요?
그리고 어느게 보기 좋은지 비교해보면 좋겠습니다.
기본형은 저는 아래와 같은 형태라고 생각합니다 ㅎㅎ
```swift
guard let ~ else {
    return
}
```

2023-05-25 04:36 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/GeneratedTaskError.swift
> +    var errorDescription: String? {
타입을 옵셔널로 한 이유가 있을까요? ㅎㅎ

2023-05-25 08:06 UTC, fatherLeon commented on ProjectManager/ProjectManager/MainScene/View/TaskListCell.swift
> +    private let dateLabel = {
```swift
private let deadlineDateLabel = {
    //......
}()
```
마감 날짜라는 의미로 `deadlineDateLabel`로 변경하였습니다.

2023-05-26 08:53 UTC, fatherLeon commented on ProjectManager/ProjectManager/Model/GeneratedTaskError.swift
> +    var errorDescription: String? {
```swift
private func showErrorAlert(_ error: Error) {
    let alertController = UIAlertController(title: error.localizedDescription,
                                            message: nil,
                                            preferredStyle: .alert)
//....
}
```

* 알럿의 메시지 창에 해당 에러에 대한 내용을 띄우기 위해 `LocaliedError`프로토콜을 채택하여 설명을 추가하려 했습니다

```swift
var errorDescription: String? { get }
```
* [LocalizedError-errorDescription](https://developer.apple.com/documentation/foundation/localizederror/2946895-errordescription)
* `LocalizedError`의 프로토콜 내의 `errorDescription`프로퍼티가 `String`옵셔널로 되어 있어 옵셔널로 구현하였습니다!!

2023-05-26 09:09 UTC, fatherLeon commented on ProjectManager/ProjectManager/MainScene/ViewModel/TodoViewModel.swift
> +              description != "" else { throw GeneratedTaskError.descriptionEmpty }
```swift
        guard let title = title, title != "" else {
            throw GeneratedTaskError.titleEmpty
        }
        guard let description = description, description != "" else {
            throw GeneratedTaskError.descriptionEmpty
        }
```

* 위와 같이 변경하였습니다.
* 조건과 조건이 충족하지 않을 때의 `else`문에 대한 각각의 흐름을 파악하기 쉬운것 같아 몇몇 `guard`문도 위와 같이 변경하였씁니다!!

2023-05-26 09:14 UTC, fatherLeon commented on ProjectManager/ProjectManager/MainScene/ViewModel/TodoViewModel.swift
> +              backspaceValue == -92 else { return false }
```swift
guard range.upperBound < 999 || backspaceValue == -92 else { return false }
```
* 위와 같이 변경하였습니다.
* 밑에서 말씀하신 기본형도 한번 써보고 비교해봤는데 `else`문이 짧을 경우 한줄로 작성해도 가독성 좋다고 생각하여 이 부분은 한줄로 작성하였습니다.

2023-05-26 11:27 UTC, fatherLeon commented on ProjectManager/ProjectManager/MainScene/ViewModel/MainViewModel.swift
> +
```swift
let firstIndex = tasks.firstIndex { targetTask in
    return targetTask.id == task.id
}

guard let targetIndex = firstIndex else { return }
```

* index를 구하는 코드, 해당 `index` 옵셔널 바인딩을 하는 작업 두가지로 나누어서 작성하였습니다

2023-05-29 02:57 UTC, fatherLeon commented on ProjectManager/ProjectManager/Extension/Date+Extension.swift
> +}
## 별도의 구조체 생성
#### 장점
* `Formatter`가 여러개 있을경우 어떻게 구현되어있고 무엇이 존재하는지 파악하기 쉬울것 같습니다.
#### 단점
* Extension을 통해 구현할 경우 현재 값에서 바로 메서드나 프로퍼티가 호출가능하지만, 따로 객체를 만들 경우 해당 객체를 통해 접근해야하기 때문에 접근이 불편할 것 같습니다.

## Extension
#### 장점
* 일반 메서드나 프로퍼티 혹은 타입 프로퍼티나 메서드일 경우 확실한 타입을 알 수 있고 타입을 통해 접근 할 수 있기 때문에 접근방식도 쉽고 타입확인도 코드 상 확인하기 편할 것 같습니다.
#### 단점
* `formatter`가 여러개 있을 경우 전부 다 따로 나뉘어져있기 떄문에 복잡해지고 어떤 `formatter`가 구현되어 있는지 파악하기 어려울것 같습니다.

2023-05-29 03:03 UTC, fatherLeon commented on ProjectManager/ProjectManager/MainScene/ViewController/TodoViewController.swift
> +    }
1. 함수 이름을 따로 지정해줌으로 단순히 `dismiss`라는 코드보다는 메서드로 `endEditing`을 써주는게 흐름을 파악하기 더 좋다고 생각했습니다.
2. 코드 수정이나 확장에 있어서 편하기 때문에 따로 분리했습니다. 예를들어 특정 상황에서는 애니메이션을 제거하고 싶다면 인자로 받아 여러곳에서 사용할 수 있기 때문에 분리했습니다

2023-05-29 10:12 UTC, AppleCEO commented on ProjectManager/ProjectManager/Extension/Date+Extension.swift
> +}
ㅎㅎ 좋습니다! 저는 큰 차이점으로 Extension 을 추가하면 모든 Date 객체에 해당 메소드가 추가되는데요. 필요없는 Date 객체에도 해당 메소드가 추가되는 것이 효율적이지는 않겠다는 생각했습니다!

2023-05-29 10:14 UTC, AppleCEO commented on ProjectManager/ProjectManager/MainScene/ViewModel/TodoViewModel.swift
> +              backspaceValue == -92 else { return false }
오... 네 좋습니다. 제가 가장 선호하는 방식은 else 문은 넘기는 것입니다 ㅎㅎ
이 부분은 개인 취향이 있어서 참고해주시면 좋겠네요!

2023-05-29 10:15 UTC, AppleCEO commented on ProjectManager/ProjectManager/MainScene/ViewModel/TodoViewModel.swift
> +              description != "" else { throw GeneratedTaskError.descriptionEmpty }
너무나 보기 좋아졌네요! 저는 이 방식을 선호합니다 ㅎㅎ

2023-05-29 10:16 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/GeneratedTaskError.swift
> +    var errorDescription: String? {
아! 제가 놓쳤군요... 이유를 명확히 이야기할 수 있는 것 너무나 좋습니다.
개발자는 자신이 작성한 코드의 이렇게 작은 부분도 이유가 있고 자신만의 기준이 있어야 합니다! 🥇

2023-05-29 10:36 UTC, AppleCEO commented
<img width="746" alt="image" src="https://github.com/yagom-academy/ios-project-manager/assets/47517256/f8675fab-f289-4bc1-9bf9-a22a86b036ab">
엑스코드로 코드를 좀 보면서 발견했는데 이렇게 띄어쓰기 등으로 자신이 보기 좋게 줄을 맞추면 파란색 바탕 코드처럼 다른 사람 컴퓨터에서는 잘못 보이는 경우도 있습니다.

2023-05-29 10:51 UTC, merged