프로젝트 매니저 [STEP 2] 혜모리
yagom-academy/ios-project-manager pull request #278
Opened 2023-05-24 14:59 UTC by hyemory

안녕하세요 줄라이! (@July911) 
프로젝트 매니저 STEP 2 PR 보냅니다!
첫 판단이 잘못됐는지, UI 작업에 쓴 시간이 너무 길어서 조금 아쉽습니다.
그럼 리뷰 잘 부탁드립니다 🙇🏻‍♀️

---
### MVVM과 관련하여 고려한 점

DM으로 말씀드렸듯 이번 스텝에서 주어진 화면이 전부 밀접한 연관이 있어 
하나의 뷰 모델로 처리하도록 구현하였습니다.

1. View Model에는 UIKit를 import하지 않을 것
2. View에는 데이터를 조작하는 기능을 정의하지 않을 것
3. View에서 작업을 직접 처리하지 않고 View Controller를 통해 처리하게 할 것

---
### 고민했던 점

#### 1️⃣ 리스트 뷰 구성

섹션별로 셀 데이터를 수정하는 구조를 가지고 있어, 처음에는 컬렉션 뷰 하나로 레이아웃을 커스텀하여 사용하였습니다.
그러나 섹션 헤더 뷰가 원하는대로 구성되지 않았고,
[직접 커스텀한 Compositional Layout](https://developer.apple.com/documentation/uikit/uicollectionviewcompositionallayoutconfiguration)에서는 스와이프 버튼을 제공해 주지 않아 
[List configuration](https://developer.apple.com/documentation/uikit/uicollectionlayoutlistconfiguration)를 사용하는 컬렉션 뷰를 각각 3종 구성하는 방향으로 수정했습니다.

#### 2️⃣ notification으로 View 업데이트

2-1. `applySnapshot`

코드에서 컬렉션 뷰를 업데이트하기위한 방법으로 Snapshot을 사용하였습니다.
View Model에서 데이터에 대한 변경사항이 발생하면 Notification을 post하여 컬렉션 뷰를 업데이트 해주도록 구현했습니다.

2-2. `Alert`

재사용이 쉽도록 AlertManager 객체를 만들었는데 Alert은 발송할 Target View Controller가 필요하므로 
View Controller에 옵저버를 등록하여 이벤트 발생 시 alert을 띄워주도록 구현했습니다.

#### 3️⃣ delegate로 값 전달

WorkCollectionView에서 이벤트가 발생하면 관련 값을 담아 대리자(MainViewController)가 처리하도록 구현하였습니다.

3-1. `workCollectionView(_:id:)`

이 메서드는 WorkCollectionView에서 Work의 ID를 전달합니다.
수정 모달로 이동 시 선택한 셀이 무엇인지 알려주고자 구현했습니다.

3-2. `workCollectionView(_:moveWork:toStatus:rect:)`

이 메서드는 Work의 ID, 변경할 상태, 누른 위치를 전달합니다. 
Long press 동작으로 Popover View를 띄워 WorkStatus를 변경하기 위해 구현했습니다.

---
### 조언을 얻고싶은 점

이번 기회에 Collection View의 Compositional Layout과 Diffable DataSource를 처음 사용하였고
특정 뷰모델을 계속 전달해주는 형태라 MVVM에 위배되는게 아닌가하는 걱정이 들었습니다.
전체적으로 MVVM에 적합하지 않는 부분은 없는지 조언을 얻고 싶습니다.
이번 리뷰도 잘 부탁드립니다! 🙇🏻‍♀️

2023-05-25 02:45 UTC, July911 requested changes

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/Application/AppDelegate.swift
> +        FirebaseApp.configure()
지금 스텝에 필요한가요 ?

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/Model/Work.swift
> +struct Work: Hashable {
특정 뷰에서만 사용하는거라면 뷰모델에 위치하게 해주세요.

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Detail/DetailViewController.swift
> +    private enum ViewMode {
뷰모델로 이동할수 있을까요 ?

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Detail/DetailViewController.swift
> +    var viewModel: WorkViewModel?
옵셔널일 필요가 없다면 수정해주세요.

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Detail/DetailViewController.swift
> +        view = workInputView
addsubview. 안하시고 할당을 한 이유가 있을까요 ?

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Detail/WorkInputView.swift
> +    private func createStackView() -> UIStackView {
내부에서 쓰이는 메서드 치고 너무 이름이 모호합니다. 
여러가지 옵션을 줄 수 있는 메서드처럼 보이지만, 사실은 원하는 스택뷰 하나만 나와서 그런 것 같습니다. 수정해주세요.

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Detail/WorkInputView.swift
> +            titleTextField.heightAnchor.constraint(equalToConstant: 40),
쉼표가 하나 더 들어간거같아요 :)

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Detail/WorkInputView.swift
> +    func drawShadow() {
굳이 private extension 일 필요가 있나요 ? 
그냥 바로 세팅해주면 안되나요 ?

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Main/MainViewController.swift
> +        self.doneCollectionView = WorkCollectionView(status: WorkStatus.done, viewModel: viewModel)
기본값 세팅안하고 init에서 해주는 이유는 무엇인가요 ? 
그럼 왜 viewModel은 여기서 안받고 바로 넣어주셨나요 ?

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Main/MainViewController.swift
> +        detailViewController.configureAddMode()
moveTo 는 present인가요 push 인가요 ? 내부에서만 쓰이는거면 굳이 사용하는 쪽에서 다시 이 메서드로 돌아와서 어떤 방식으로 띄어주는지 체크를 해야할까요 ?

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Main/MainViewController.swift
> +            self?.viewModel.currentID = id
guard로 self를 확인안하면 할당시에는 문제가 될 수 있을 것 같아요

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Main/MainViewController.swift
> +        stackView.spacing = 8
저는 스택뷰는 굳이 싶지만 axis distribution spacing alignment 까지는 기본값이여도 적어주는 편이에요. 
이건 진짜 개인취향이라 참고만 해주세요 :)

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Main/MainViewController.swift
> +    private func configureDelegate() {
extension MainViewController: UICollectionViewDelegate, WorkCollectionViewDelegate { 
의 콜 정렬을 맞춰주세요. 어떤게 delegate 인지, 어떤게 역할 분리를 위한 것인지 헷갈리네요.

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Main/WorkCell.swift
> +    private var isExceededDeadline: Bool = false {
왜 맨위에 있을까요 ? 이유가 있나요

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Main/WorkCollectionView.swift
> +    typealias Snapshot = NSDiffableDataSourceSnapshot<WorkStatus, Work>
CollectionView에 dataSource가 있다면 굳이 나눠놓은 이유는 뭘까요 ? 
View는 그냥 View고 어떠한 데이터가 들어갈지, 그 데이터를 어디에 넣어줄지는 다른곳에서 정해야하지 않을까요 ?

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Main/WorkCollectionView.swift
> +    weak var workDelegate: WorkCollectionViewDelegate?
2줄 아래로 가는게 맞아보입니다.

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Main/WorkCollectionView.swift
> +            let section: NSCollectionLayoutSection
NSCollectionLayoutEnvironment -> NSCollectionLayoutContainer 
에 대해서도 알아보세요 :)

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Main/WorkCollectionView.swift
> +
section.visibleItemsInvalidationHandler 에 대해서도 알아보시고 답글 남겨주세요.

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Main/WorkCollectionView.swift
> +    private func makeSwipeActions(for indexPath: IndexPath?) -> UISwipeActionsConfiguration? {
make말고 다른 이름은 어떨까요 ?

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Main/WorkCollectionView.swift
> +        guard let headerView = visibleSupplementaryViews(ofKind: UICollectionView.elementKindSectionHeader).first as? HeaderReusableView else { return }
헤더가 업데이트 안되서 이렇게 하신건가요 ?

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/ViewModel/WorkViewModel.swift
> +        guard let index = works.firstIndex(where: { $0.id == currentID }) else { return nil }
조금 어색합니다. index로 아이템을 조회할 수 있어야 할 것 같은데요. 
currentID 를 계속 갱신해서 찾아주는 방식인 것 같습니다.

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/ViewModel/WorkViewModel.swift
> +    func addWork(title: String, body: String, deadline: Date) {
viewModel에 nested로 타입이 존재한다면 그걸 주고받을 수 있을 것 같아요.

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/ViewModel/WorkViewModel.swift
> +        NotificationCenter.default.post(name: .updateSnapShot, object: nil)
updateSnapShot 은 diffableDataSource 와 연관이 깊은데, 이걸 ViewModel에서 이 이름으로 이벤트를 보내는건가요 ?

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/ViewModel/WorkViewModel.swift
> +        if targetDate < Date() {
삼항 연산자로 바꿔주세요.

2023-05-25 02:45 UTC, July911 commented on ProjectManager/ProjectManager/View/Main/WorkCell.swift
> +
setCustomSpacing 이란것도 있습니다. 알아보시고 답글 남겨주세요.

2023-06-02 03:39 UTC, hyemory commented on ProjectManager/ProjectManager/Application/AppDelegate.swift
> +        FirebaseApp.configure()
스텝에 불필요한 코드라 주석처리해 두었습니다!

2023-06-02 03:40 UTC, hyemory commented on ProjectManager/ProjectManager/Model/Work.swift
> +struct Work: Hashable {
뷰모델로 이동했습니다 👍

2023-06-02 03:40 UTC, hyemory commented on ProjectManager/ProjectManager/View/Detail/DetailViewController.swift
> +    var viewModel: WorkViewModel?
불필요한 옵셔널 제거했습니다

2023-06-02 03:42 UTC, hyemory commented on ProjectManager/ProjectManager/View/Detail/DetailViewController.swift
> +        view = workInputView
workInputView가 모달 내용의 전부라 굳이 서브 뷰로 만들 필요가 없다고 생각했습니다.
혹시 view에 바로 할당해주면 단점이 있을까요?

2023-06-02 03:43 UTC, hyemory commented on ProjectManager/ProjectManager/View/Detail/WorkInputView.swift
> +    private func createStackView() -> UIStackView {
전체적으로 어떤 스택뷰를 만드는 것인지 알 수 있도록 더 자세한 이름으로 변경했습니다!

2023-06-02 03:44 UTC, hyemory commented on ProjectManager/ProjectManager/View/Detail/WorkInputView.swift
> +            titleTextField.heightAnchor.constraint(equalToConstant: 40),
추후에 제약을 추가하기 용이하도록 마지막에도 쉼표를 붙이는 컨벤션을 사용하고 있었습니다.
현재는 전부 삭제해 주었습니다~!

2023-06-02 03:45 UTC, hyemory commented on ProjectManager/ProjectManager/View/Detail/WorkInputView.swift
> +    func drawShadow() {
여러번 쓰이는 기능이 아니므로 말씀해 주신대로 뷰에 바로 세팅하는 것으로 변경했습니다!

2023-06-02 03:46 UTC, hyemory commented on ProjectManager/ProjectManager/View/Main/MainViewController.swift
> +        self.doneCollectionView = WorkCollectionView(status: WorkStatus.done, viewModel: viewModel)
View Controller의 addChild 메서드를 이용하여 수정했습니다! 
viewModel은 init에서 해주도록 변경해 보았습니다 ☺️

2023-06-02 03:47 UTC, hyemory commented on ProjectManager/ProjectManager/View/Main/MainViewController.swift
> +        detailViewController.configureAddMode()
네이밍이 모호하여 moveTo가 아닌 present로 변경했고,
굳이 메서드를 공개해서 호출하지 않고 init에 담아 세팅하도록 변경해 주었습니다

2023-06-02 03:53 UTC, hyemory commented on ProjectManager/ProjectManager/View/Main/MainViewController.swift
> +            self?.viewModel.currentID = id
감사합니다 guard 문으로 변경했습니다!

2023-06-02 03:55 UTC, hyemory commented on ProjectManager/ProjectManager/View/Main/MainViewController.swift
> +        stackView.spacing = 8
말씀해 주신대로 적어주는게 나중에 코드를 읽을 때 더 편할 것 같아 axis, distribution, alignment를 모두 적어주었습니다! 😊

2023-06-02 03:55 UTC, hyemory commented on ProjectManager/ProjectManager/View/Main/MainViewController.swift
> +    private func configureDelegate() {
UICollectionViewDelegate 프로토콜은 불필요하게 채택하였습니다! 현재는 삭제하였습니다.

2023-06-02 03:57 UTC, hyemory commented on ProjectManager/ProjectManager/View/Main/WorkCell.swift
> +    private var isExceededDeadline: Bool = false {
프로퍼티 옵저버라 왠지 가장 위에 있는게 읽기 쉬울거라 생각했는데
다른 객체와 동일하게 UI 프로퍼티 하단에 위치하도록 변경했습니다 🙂

2023-06-02 04:02 UTC, hyemory commented on ProjectManager/ProjectManager/View/Main/WorkCollectionView.swift
> +    typealias Snapshot = NSDiffableDataSourceSnapshot<WorkStatus, Work>
View는 그려주는 역할만 해야하므로 UICollectionView를 바로 사용하도록 수정했습니다.
컬렉션 뷰의 레이아웃을 잡고, 데이터를 넣어주는 주체는 ViewController가 하게 만들었습니다.

2023-06-02 04:10 UTC, hyemory commented on ProjectManager/ProjectManager/View/Main/WorkCollectionView.swift
> +    private func makeSwipeActions(for indexPath: IndexPath?) -> UISwipeActionsConfiguration? {
[iOS App Dev Tutorials - Delete a reminder](https://developer.apple.com/tutorials/app-dev-training/adding-and-deleting-reminders#Delete-a-reminder)에서 사용하는 네이밍 그대로 사용하면 된다고 생각했는데 make는 팩토리 메서드의 이름으로 사용하는 키워드고 그다지 가독성이 좋지 않다고 생각했습니다. 항상 의심하겠습니다 😂

2023-06-02 04:11 UTC, hyemory commented on ProjectManager/ProjectManager/View/Main/WorkCollectionView.swift
> +        guard let headerView = visibleSupplementaryViews(ofKind: UICollectionView.elementKindSectionHeader).first as? HeaderReusableView else { return }
헤더에 셀 카운트가 들어가는 부분을 configureHeaderView에서 해주고 있어 추가하였습니다.

2023-06-02 04:13 UTC, hyemory commented on ProjectManager/ProjectManager/ViewModel/WorkViewModel.swift
> +        guard let index = works.firstIndex(where: { $0.id == currentID }) else { return nil }
외부에서 ID를 주면 viewModel이 인덱스를 확인하여 처리하는 방식으로 변경했습니다.

2023-06-02 04:15 UTC, hyemory commented on ProjectManager/ProjectManager/ViewModel/WorkViewModel.swift
> +        NotificationCenter.default.post(name: .updateSnapShot, object: nil)
Notification에서 이벤트를 post할 때 받는 옵저버를 기준으로 네이밍을 정하고 있었습니다. 😅
현재는 post하는 이벤트를 기준으로 네이밍을 수정해 보았습니다!
`updateSnapShot` -> `worksChanged`

2023-06-02 05:35 UTC, hyemory commented on ProjectManager/ProjectManager/View/Main/WorkCell.swift
> +
추천해주신 키워드 관련하여 DM으로 답변드리겠습니다 ~!

2023-06-22 09:10 UTC, closed without merging