프로젝트 매니저 [STEP2] 송준, vetto
yagom-academy/ios-project-manager pull request #280
Opened 2023-05-26 07:07 UTC by kimseongj

@uuu1101
안녕하세요 태태~
프로젝트 매니저 두번째 PR입니다!
새로운 기술을 적용하느라 시간이 걸린거 같습니다!
부족한 점이 많은거 같아 부끄럽습니다..ㅎ
리뷰 잘부탁드립니다!!

## 고민했던 점
### @Published
![](https://hackmd.io/_uploads/SkehwApSh.png)
> `Published`의 경우 공식문서를 참고한 결과, subscriber는 실제로 속성에 설정되기 전에 새 값을 받습니다. 이 점을 간과하고, 실제 속성에 값을 가져오는 바람에 한박자 늦게 작동되는 오류가 발생했습니다.
이 문제를 깨닫게 되기 전에 `observable`을 사용하여 Binding을 구현하였습니다.. Step3때, Combine으로 리팩토링해볼 생각입니다.

- 변경된 값을 subscriber가 받아 왔을 시
```Swift=
class Weather {
    @Published var temperature: [Double]
    init(temperature: [Double]) {
        self.temperature = temperature
    }
}

var cancellables: Set<AnyCancellable> = []

let weather = Weather(temperature: [20])
weather.$temperature
    .sink() { // $0

        print ("Temperature now: \(weather.temperature)") //viewModel.todoSchedule

    }.store(in: &cancellables)

weather.temperature = [25] // [20]을 호출한다.
```

- 실제 속성 값을 받아와 처리를 하였을 시 
```Swift=
class Weather {
    @Published var temperature: [Double]
    init(temperature: [Double]) {
        self.temperature = temperature
    }
}

var cancellables: Set<AnyCancellable> = []

let weather = Weather(temperature: [20])
weather.$temperature
    .sink() { // $0

        print ("Temperature now: \($0)") //viewModel.todoSchedule

    }.store(in: &cancellables)

weather.temperature = [25] // [20, 25]를 print한다.
```

## 조언이 필요한 점

### 길게 눌렀을 때 경고 메세지
저희는 `UILongPressGestureRecognizer`를 사용하여 cell을 길게 눌렀을 때 데이터와 cell을 옮기는 것을 구현하였습니다. 하지만 cell을 길게 눌러 alert가 띄워지고 바로 아래와 같은 경고 메세지가 뜨는 것을 확인 했습니다. 이와 같은 경고 메세지를 해결하지 못했는데 해결방법을 알려주시면 좋을 거 같습니다.

![](https://hackmd.io/_uploads/SyCBU0pSh.png)

#### ViewModel의 공유
ViewModel의 개수를 ViewController에 맞추어야 될지, 공유하는 데이터에 맞추어야할지 고민 끝에 공유하는 데이터에 맞춰서 ViewModel을 구현했습니다. 그 이유는 ViewModel에 저장되는 스케쥴데이터 값을 여러 ViewController가 공유하기 때문입니다. 만약 ViewModel을 ViewController 개수에 맞춰서 구현한다면, 하나의 데이터 저장 객체에 스케쥴 데이터를 저장하고, 각각의 ViewModel들이 데이터 저장 객체를 불러오는 식으로 처리해야 한다고 생각이 듭니다. 어떤 방향이 더 옳은 방향일까요?

2023-05-29 11:09 UTC, uuu1101 requested changes
안녕하세요! @vetto @kimsengj
커밋을 따라가면서 리뷰를 하다보니, 변경된 코드에도 리뷰가 남겨져 있을거에요.

몇가지 코멘트 남겨두었습니다 ! 확인부탁드려요 ! 

길게 눌렀을 때 경고 메세지
---
system gesture와 longPress gesture간 충돌이 일어나서 발생하는 오류로 보여지는데, 
혹시 어떤 오류로 확인하셨나요?!

ViewModel의 공유
---
먼저 아래 질문에 대해서 생각해보시면 더 좋을 것 같은데요! 🤔
MVVM 에서 VM 은 어떤 역할을 하나요 ?!
그럼, 어떠한 단위로 나눠주는게 좋을까요 ?

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/ViewController.swift
> +//    }()
stackView를 주석 처리하신 이유가 있으실까요?

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/ViewController.swift
> +        collectionView.backgroundColor = .brown
CollectionView.backgroundColor가 `.brown`으로 두신 이유가 혹시 뷰를 확인하기 위함이었을까요?

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/CollectionViewCell.swift
> +            stackView.bottomAnchor.constraint(equalTo: self.safeAreaLayoutGuide.bottomAnchor, constant: -15)
15나 -15 보다는 이름을 지정해서 관리하는게 좋아보입니다 :)

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/CollectionViewCell.swift
> +        dateLabel.text = schedule.expirationDate
label의 이름도 expiration 의미를 담아두는게 좋지 않을까요?!

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/HeaderView.swift
> +        label.layer.cornerRadius = 10
cornerRadius는 Label의 size(너비나 높이값이)가 변경되더라도 동그랗게 그려줄수 있도록 해둘수도 있지 않을까요?

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/ViewController.swift
> +    let schedule = Schedule(title: "asd", detail: "asd", expirationDate: "asd")
테스트를 위한 데이터 였을까요? 🤔

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/ViewController.swift
> +        print("뭐야 도대체")
테스트를 위한 print문 이었을까요?! 커밋을 올릴때는 이런부분들은 포함하지 않는게 더 좋아보입니다 !

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/ScheduleCell.swift
> +class ScheduleCell: UITableViewCell {
collectionView 를 TableView 로 변경하게 되신 히스토리가 궁금합니다 😀

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/TodoView.swift
> +    }
View에서 섹션을 가지는것보다 따로 분리해주면 좋을 것 같습니다!

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/ViewController.swift
> +
여기는 개행을 두개 주신 이유가 있으실까요?

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/TodoView.swift
> +        tableView.backgroundColor = .red
여기 backgroundColor도 뷰 확인을 위해서 해두신걸까요?

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.5;
14.5 로 변경하신 이유가 궁금합니다

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/HeaderView.swift
> +        countLabel.text = "4"
"4"로 고정하면 위에 todoCountString은 어떻게 사용되나요?

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/TodoView.swift
> +        self.collectionView.register(ScheduleCell.self, forCellWithReuseIdentifier: "cell")
forCellWithReuseIdentifier를 "cell"로 두는거 보다 조금더 명확하게 해두시면 좋을 것 같아요.

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/TodoView.swift
> +        var  snapshot = NSDiffableDataSourceSnapshot<Section, Schedule>()
`var  snapshot`의 whitespace가 두 칸 인것 같아요

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/TodoView.swift
> +
여기 개행이 두 개 인것 같습니다. 컨벤션상 개행을 두 번주는 것을 정해두신게 있을까요?👀

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/View/MainViewController.swift
> +    @objc func tabPlusButton() {
`private`으로 설정해두면 더 좋겠습니다

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/View/ModalViewController.swift
> +        ])
매직넘버들을 정의해서 사용하면 더 좋을것 같아요 👍🏻

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/View/ModalViewController.swift
> +        dismiss(animated: true)
`@objc private func` 을 이렇게 쓰기로 컨벤션을 정하신걸까요?

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/View/ModalViewController.swift
> +        contentTextView.isUserInteractionEnabled = true
configureUserInteraction() 의 add case에 대해서도 동일하게 처리해야한다면, 함수로 빼도 좋아보입니다

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/View/ModalViewController.swift
> +            print("")
🤔

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/ViewModel/MainViewModel.swift
> +    func roadSchedules(scheduleType: ScheduleType) -> [Schedule] {
오타가 있는것 같습니다 👀

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/Utility/Namespace.swift
> +}
따로 정의해두신게 좋네요 👍🏻

2023-05-29 11:09 UTC, uuu1101 commented on ProjectManager/ProjectManager/Source/View/Main/DoListViewController.swift
> +            }.store(in: &cancellables)
기존 코드와 차이점은 무엇이었나요? 👀

2023-05-30 01:07 UTC, kimseongj commented on ProjectManager/ProjectManager/ViewController.swift
> +//    }()
주석 처리를 따로 한 이유가 없습니다!
git을 통해 버전 관리를 해준다는 것을 망각하고, 마지막 버전을 보실거라 생각해서... 이거저거 시도하다가 나온 코드 같습니다😂

2023-05-30 01:08 UTC, kimseongj commented on ProjectManager/ProjectManager/CollectionViewCell.swift
> +            stackView.bottomAnchor.constraint(equalTo: self.safeAreaLayoutGuide.bottomAnchor, constant: -15)
넵! 그렇다면 `stackViewLeadingAnchor` 이런식의 네이밍을 하는게 좋을까요..?

2023-05-30 01:09 UTC, gzzjk159 commented on ProjectManager/ProjectManager/ViewController.swift
> +        collectionView.backgroundColor = .brown
collectionView가 들어갔는지 확인하기 위해 적절한 색으로 테스트 해봤던거 같습니다. 해당 코드는 현재는 삭제되었습니다.

2023-05-30 01:09 UTC, kimseongj commented on ProjectManager/ProjectManager/ViewController.swift
> +        print("뭐야 도대체")
넵 주의하겠습니다!

2023-05-30 02:12 UTC, gzzjk159 commented on ProjectManager/ProjectManager/CollectionViewCell.swift
> +        dateLabel.text = schedule.expirationDate
label에 expiration을 붙여 수정하였습니다. b317e2a08537c5d50ffbff20a1ae649a71587ad9

2023-05-30 02:18 UTC, gzzjk159 commented on ProjectManager/ProjectManager/ViewController.swift
> +    let schedule = Schedule(title: "asd", detail: "asd", expirationDate: "asd")
예 맞습니다. 데이터가 잘 나오는지 확인하기 위해 임시로 작성했던 코드입니다. 현재 해당 코드는 삭제되었습니다.

2023-05-30 02:19 UTC, kimseongj commented on ProjectManager/ProjectManager/HeaderView.swift
> +        label.layer.cornerRadius = 10
cornerRadius가 Label의 너비를 기준으로 수정되게 바꿨습니다! dd86e5af6e6c550893602e4d8f787a1307fab3c1

2023-05-30 02:28 UTC, kimseongj commented on ProjectManager/ProjectManager.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 14.5;
14.5 이상일 때, 사용할 수 있는 메서드를 실험했을 때 변경된거 같습니다. 14.1 버젼으로 다시 변경했습니다!
540905751f4cad556ea5a727080ac9c7a8a8ae19

2023-05-30 02:29 UTC, kimseongj commented on ProjectManager/ProjectManager/TodoView.swift
> +        tableView.backgroundColor = .red
네 맞습니다! 혹시 뷰 확인하는 더 좋은 방법이 있을까요??

2023-05-30 02:30 UTC, gzzjk159 commented on ProjectManager/ProjectManager/ScheduleCell.swift
> +class ScheduleCell: UITableViewCell {
처음에는 collectionView를 하나로만 작성하기 위해 collectionView로 작성하였습니다. 하지만 collectionView 1개로 하기 보단 tableView 3개로 구현하는 것이 좋을 거 같아서 TableView로 수정하였습니다. 더 나중에는 tableView 대신 collectionView의 UICollectionLayoutListConfiguration를 사용해보기 위해 collectionView로 구현하였습니다.

2023-05-30 02:33 UTC, gzzjk159 commented on ProjectManager/ProjectManager/ViewController.swift
> +
처음에는 개행에 신경을 쓰지 않고 작성하였다가 나중에 컨벤션에 맞게 일괄적으로 수정하였습니다.

2023-05-30 02:35 UTC, kimseongj commented on ProjectManager/ProjectManager/TodoView.swift
> +    }
넵 분리했습니다!16d45e3a77fbde4781aa43803214023b71283dfa

2023-05-30 02:36 UTC, gzzjk159 commented on ProjectManager/ProjectManager/HeaderView.swift
> +        countLabel.text = "4"
테스트를 해보기위해 작성했던 코드였습니다. 현재 해당 코드는 삭제되었습니다.

2023-05-30 02:37 UTC, kimseongj commented on ProjectManager/ProjectManager/TodoView.swift
> +        self.collectionView.register(ScheduleCell.self, forCellWithReuseIdentifier: "cell")
그 이후에 `IdentifierType`를 채택하여 `ScheduleCell.identifier`로 지정해주었습니다!

2023-05-30 02:39 UTC, gzzjk159 commented on ProjectManager/ProjectManager/TodoView.swift
> +        var  snapshot = NSDiffableDataSourceSnapshot<Section, Schedule>()
현재 문제점을 발견하여 수정하였습니다. bcd3bc1312289b572549cdcd7ac1602cfccece1a

2023-05-30 02:41 UTC, kimseongj commented on ProjectManager/ProjectManager/TodoView.swift
> +
작성 중에 생긴 공백같습니다!! 따로 개행을 두 번 주는 컨벤션은 없습니다.

2023-05-30 02:44 UTC, gzzjk159 commented on ProjectManager/ProjectManager/Source/View/MainViewController.swift
> +    @objc func tabPlusButton() {
72786ebaa49ded75fc4f1f51400313b0a2fb7906  해당 문제점을 발견하여 현재는 수정하였습니다.

2023-05-30 02:47 UTC, gzzjk159 commented on ProjectManager/ProjectManager/Source/View/ModalViewController.swift
> +        dismiss(animated: true)
예 이렇게 attribute가 위에 오도록 컨벤션을 정하였습니다.

2023-05-30 02:47 UTC, kimseongj commented on ProjectManager/ProjectManager/Source/View/ModalViewController.swift
> +        contentTextView.isUserInteractionEnabled = true
그 이후에 `view.isUserInteractionEnabled = true`로 따로따로 처리하지 않고 하나의 `view`의 `isUserInteractionEnabled`을 사용불가 하게 만들었습니다. 그 작업을 함으로써 메서드를 따로 빼주는것 보다 `view.isUserInteractionEnabled = true`만 작성하는게 가독성이 좋다 생각됩니다!

2023-05-30 02:48 UTC, gzzjk159 commented on ProjectManager/ProjectManager/Source/View/ModalViewController.swift
> +            print("")
임시로 case를 처리하기 위해 아무 실행구문이나 넣었던 것 같습니다. 현재 해당코드는 수정되어 삭제되었습니다.

2023-05-30 02:50 UTC, kimseongj commented on ProjectManager/ProjectManager/Source/ViewModel/MainViewModel.swift
> +    func roadSchedules(scheduleType: ScheduleType) -> [Schedule] {
해당 코드는 삭제되었습니다!

2023-05-30 02:52 UTC, kimseongj commented on ProjectManager/ProjectManager/Source/View/Main/DoListViewController.swift
> +            }.store(in: &cancellables)
기존 코드는 Observable을 사용하여 Binding 작업을 해주었다면, 현재 작업 내용은 Combine을 사용하여 Binding 작업을 해주었습니다!
Combine을 사용할 경우 Observable이라는 새로운 타입을 생성할 필요 없이 값이 변할 때마다 쉽게 처리할 수 있었습니다!

2023-05-31 08:33 UTC, uuu1101 commented on ProjectManager/ProjectManager/TodoView.swift
> +        tableView.backgroundColor = .red
이렇게 확인하기도 하고, Xcode의 view hierarchy로 보기도 합니다 !

2023-05-31 08:34 UTC, uuu1101 commented
확인했습니다 !  다음 스텝진행하시면서 매직넘버에 대한 부분도 같이 적용해보시면 좋을 것 같아요 !

2023-05-31 08:34 UTC, merged