프로젝트 매니저 [STEP 2] kaki, 릴라
yagom-academy/ios-project-manager pull request #282
Opened 2023-05-29 08:28 UTC by kak1x

# 프로젝트 매니저 [STEP 2] kaki, 릴라

안녕하세요 올라프(@1Consumption) 카키,릴라 인사드립니다 🙇🏻‍♂️

호기롭게 기술스택을 얘기하였으나 구현하는데 쩔쩔 맸네요,,, 
어떻게 SwiftUI라도 사용해보자 했는데, 제대로 한건지 의문이 드네요🥲

## 해결하지 못한 점
### Delete 버튼 크기 조절

![](https://hackmd.io/_uploads/H1veCRWLn.png)

- onDelete(perform:) 메서드를 사용하여 Delete 버튼을 구현했는데, 요구사항의 셀 모양을 만들기 위해 적용한 `listRowBackground`가 아닌 전체 cell에 버튼이 적용되어 버튼이 보여지는 셀보다 크게 보입니다.
- 이를 해결해주고 싶어 방법을 찾아보았지만 찾지 못하였습니다 🥺🥺🥺 혹시 다른 좋은 방법이 있을까요?

## 고민했던 점

### ViewModel의 데이터 관리

- 처음 시도해본 방식은 각각의 state 에맞는 List 를 만들어 사용을 하는것이었습니다. 

- 위 방법을 사용할 시 각각의 리스트View 에서 자신의 state 에 맞는 List를 넘겨주기만 하면 간편하게 사용이 가능하단 이점이 있었습니다. 하지만 뷰모델이 여러개의 List 를 가지고 있었기에 관리측면에서는 몇몇 어려운점이 있었습니다.

#### 원본데이터의 접근

- 현재 ViewModel 을 environmentObject 로 관리를 하고 있습니다. 만약 데이터의 변경이 일어났다면 viewModel 을 관찰하고 있는 모든 View 들이 바뀌어야 했기에 원본데이터의 접근이 필수불가피 했습니다.

#### 조건에 맞는 분기처리

- viewModel 이 관리하고 있는 list 들이 여러개 였기에 자신의 state와 만약 이동을 해야할 경우 이동할 state 에 맞는 list 를 알아야 했습니다.
- 개발자의 입장에서는 ` 이 state는 맞는 list는 저 list다"` 라는것을 알지만 시스템은 알지 못했기에, 조건에 맞는 분기처리를 모두 진행해야 했습니다.

- 이를 해결 하기위해 기존의 state에 맞는 list를 여러개 만드는것이 아닌 하나의 list 에서 관리를 하는 방식을 사용하기로 했습니다.

- list의 element 에 state 프로퍼티를 사용하게 해 하나의 List 에서 state에 맞는 List 를 구분할 수 있도록 했습니다.

- 이 방법을 사용하니 우리가 접근해야할 원본데이터인 list 가 하나이기에 별도의 분기처리 없이 수월하게 접근을 할 수 있게 되었고, 코드의 길이또한 기존코드에 비교하면 대략 1/5 정도로 줄게되었습니다.

### contextMenu의 사용
- 요구사항을 그대로 구현하기 위해선 contextMenu가 아닌 popover로 구현해주어야 했습니다. 하지만 popover 구현 시 셀 내부에 구현해주지 않으면 작동하지 않았고, 셀의 내용을 누르지 않는 이상 제스처가 동작하지 않았습니다. 또한 iOS에서는 화살표 방향을 지정해줄 수 없어 원하는 형태로 구현이 어려웠습니다.
- 이에 popover 대신 contextMenu를 사용하여 구현해주었습니다.

## 조언받고 싶은 점

### viewModel의 관리
- 현재 저희 프로젝트에선 하나의 MainView 안에 여러개의 하위뷰가 정의되어 호출되고 있습니다. 그러기에 하나의 viewModel 을 가지고 하위뷰에 environmentObject 로 계속해서 전달을 해주고 있으나, 만약 프로젝트의 규모가 커지게 된다면 지금과 같이 viewModel 을 계속 전달을 해줄 수 있을지 의문이 듭니다.

2023-05-30 13:45 UTC, 1Consumption requested changes
고생하셨습니다. 
SwiftUI를 학습하며 사용하는데 많은 어려움이 있었을 것 같습니다.
하지만 도전하는 모습이 보기 좋습니다 화이팅입니다.👍 

Delete 버튼 크기 조절 관련해서 드릴 말씀은 `현재 상황에서는 해결이 불가능하다` 입니다. 애초에 `List`의 item에 spacing을 주는 것을 SwiftUI에서는 지원하고 있지 않은 것 같습니다. 그런데 억지로 spacing을 준 상황이고, 이에 따른 정상 동작은 보장하지 못하는 상황이라고 생각됩니다.

하여 원하는 동작을 하려면 커스텀을 해야하는데... 아래 링크를 참고해보세요.
https://www.youtube.com/watch?v=jXVQDmeNb8A 

또한 말씀해주신대로 environmentObject 사용이 너무 과하다고 생각됩니다. 이러면 싱글톤과 다를게 없습니다. 현재 view에서 필요한 정보만 넘기면 좋겠어요.
Binding이라는 키워드에 대해서 조금 더 알아보면 좋겠습니다.

나머지는 코멘트를 참고해주세요.

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/Model/Project.swift
> +final class Project: Identifiable {
class인 이유가 있을까요?

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/App/ProjectManagerApp.swift
> +                .environmentObject(ProjectViewModel())
environmentObject 모디파이어는 어떤 역할을 하나요?

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/Utill/DateManager.swift
> +    static let shared = DateManager()
싱글톤인 이유가 궁금합니다.

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/Utill/DateManager.swift
> +        }
이렇게 바꿀 수 있을 것 같습니다.
```suggestion
        return target >= today
```

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/Utill/DateManager.swift
> +        return Int(dateText)!
항상 성공하는 강제언래핑인가요?

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainView/ProjectListCell.swift
> +    @EnvironmentObject private var viewModel: ProjectViewModel
ProjectViewModel를 EnvironmentObject로 받아야하는 이유를 잘 모르겠습니다. 코드 전체적으로 EnvironmentObject로 넘기고 있는데, 이유가 궁금합니다.

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainView/ProjectListCell.swift
> +    let model: Project
cell을 위한 viewModel을 만들고, 그 안에 들어가야할 값 같습니다.

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainView/ProjectListContextMenuView.swift
> +    let project: Project
외부에서 알아야하는 값인가요?

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainView/ProjectListContextMenuView.swift
> +    @EnvironmentObject private var viewModel: ProjectViewModel
저라면 이 부분을 클로저로 대체했을 것 같습니다.

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainView/ProjectListHeaderView.swift
> +                Text(String(viewModel.search(state: state).count))
이부분에 대한 변경의 옵저빙이 필요하니 Binding으로 외부에서 받으면 어떨까요?

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainView/ProjectListView.swift
> +}
이거는 왜 extension으로 빼셨나요? 저라면 View로 뺄 것 같습니다. SwiftUI에서는 여러개의 하위 View를 만드는게 자연스럽고, 권장되는 행위입니다.

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/View/MainView/ProjectMainView.swift
> +    @State private var showModal = false
이 두 프로퍼티래퍼의 차이는 뭔가요?

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/ProjectViewModel.swift
> +final class ProjectViewModel: ObservableObject {
ObservableObject는 뭔가요? 왜 사용하셨나요?

2023-05-30 13:45 UTC, 1Consumption commented on ProjectManager/ProjectManager/ViewModel/ProjectViewModel.swift
> +    @Published private var projectList: [Project] = []
`@Published`를 붙여준 이유가 있나요? 이걸 안붙이면 동작이 어떻게 변하나요?

2023-05-31 01:58 UTC, juun97 commented on ProjectManager/ProjectManager/Utill/DateManager.swift
> +    static let shared = DateManager()
dateFormatter 의 경우 사용할 때 마다 인스턴스를 만드는것이 생각보다 비용이 많이 든다는 것을 봤습니다.
그래서 단 하나의 인스턴스만을 만들기 위해 싱글톤을 적용했습니다

2023-05-31 02:01 UTC, juun97 commented on ProjectManager/ProjectManager/Utill/DateManager.swift
> +        return Int(dateText)!
```swift
private let dateFormatter = {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy. M. d."
        
        return dateFormatter
    }()
```

사용하는 dateFormatter 의 format 이 고정이 되어있기에 dateText 의 형식또한 고정이 됩니다.
그래서 불필요한 바인딩을 필요하기 위해 강제언래핑을 사용했습니다

2023-05-31 05:44 UTC, kak1x commented on ProjectManager/ProjectManager/Utill/DateManager.swift
> +        }
조언 주신 대로 변경하였습니다! e445c157d7309e24067ca64bf5f9cedf095f7f1d
추가적으로 표현식 때문에 비교에 오류가 발생하는 부분을 발견하여, enum을 정의해주어 display 용과 calculate 용 표현식을 따로 정의해주어 이를 사용하는 방식으로 변경했습니다.

2023-05-31 05:46 UTC, juun97 commented on ProjectManager/ProjectManager/App/ProjectManagerApp.swift
> +                .environmentObject(ProjectViewModel())
environmentObject 모디파이어는 하위뷰의 environmentObject 를 설정해주는 역할을 합니다

2023-05-31 05:47 UTC, kak1x commented on ProjectManager/ProjectManager/Model/Project.swift
> +final class Project: Identifiable {
기존에 struct로 구현해줬었는데 어디서 문제가 발생한건지 제대로 binding이 되지 않는 문제가 있었습니다.
이때 class로 바꿔보니 제대로 구현되어 class로 임시 변경했었는데, 코드 최종 구현 후 다시 확인해보는 것을 잊었네요😟
현재 코드 상태에서 struct로 제대로 실행되는 것을 확인하였고 변경해주었습니다. e445c157d7309e24067ca64bf5f9cedf095f7f1d

2023-05-31 05:52 UTC, kak1x commented on ProjectManager/ProjectManager/Utill/DateManager.swift
> +        return Int(dateText)!
```swift
func formatDateText(date: Date, mode: DateFormat) -> String {
    if mode == .display {
        dateFormatter.dateFormat = DateFormat.display.expression
        
        return dateFormatter.string(from: date)
    } else {
        dateFormatter.dateFormat = DateFormat.calculate.expression
        
        return dateFormatter.string(from: date)
    }
}

private func convertDateToInt(date: Date) -> Int {
    let formattedText = formatDateText(date: date, mode: .calculate)

    return Int(formattedText)!
}
```

date를 받아 `formatDateText` 메서드를 통해 String으로 변경해주는 과정에서, 지정해준 dateFormatter의 format 형식에 따라 String으로 변환되기 때문에 dateText의 형식또한 고정이 됩니다.
이때문에 무조건 Int로의 변환이 가능하기 때문에 바인딩을 통한 언래핑은 불필요한 과정이라 생각되어 이를 생략하기 위해 강제 언래핑을 사용했습니다.

2023-05-31 06:15 UTC, juun97 commented on ProjectManager/ProjectManager/View/MainView/ProjectListCell.swift
> +    let model: Project
사실상 ProjectListCell 에서는 viewModel의 기능을 사용하고 있지는 않고 단지`ProjectDetailView` 모달에 viewModel을 건내주기 위해 viewModel을 가지고 있습니다 . 

`ProjectDetailView` 의 경우 ProjectMainView 와 모든 하위뷰에서 보여주는 데이터를 추가하거나 수정하는 역할을 하고 있기에 동일한 viewModel 을 넘겨줘야한다 생각했습니다.

또한 `ProjectDetailView` 를 호출하는 위치가 mainView 와 cell 입니다.
만약 cell을 위한 viewModel 을 만들 경우 `ProjectDetailView` 에 어떤 값을 넣어줘야 할지 명확하지가 않아서 지금 방식을 사용했습니다.

이 경우에 어떻게 개선을 할 수 있을까요?

2023-05-31 06:25 UTC, juun97 commented on ProjectManager/ProjectManager/ViewModel/ProjectViewModel.swift
> +    @Published private var projectList: [Project] = []
`@Published`프로퍼티 랩퍼는 프로퍼티의 변경사항이 생길 때 `objectWillChange` 를 자동으로 호출을 해주게 됩니다.

 만약 `@Published` 를 붙이지 않을 경우 프로퍼티가 변경이 이루어져도 감지를 할 수가 없게 됩니다.

2023-05-31 06:29 UTC, juun97 commented on ProjectManager/ProjectManager/ViewModel/ProjectViewModel.swift
> +final class ProjectViewModel: ObservableObject {
`@EnvironmentObject` 프로퍼티 랩퍼를 사용하기 위해선 해당 타입이 `ObservableObject` 를 채택해야 합니다.

ObservableObject는 SwiftUI 앱에서 상태를 관리하기 위해 사용되는 프로토콜입니다. 이 프로토콜을 채택한 객체는 관찰 가능한 속성(@Published)을 가질 수 있으며, 값의 변경을 알릴 수 있습니다.

2023-05-31 06:34 UTC, kak1x commented on ProjectManager/ProjectManager/View/MainView/ProjectListCell.swift
> +    @EnvironmentObject private var viewModel: ProjectViewModel
아직 사용법이 익숙치 않아 혼용하여 사용했었습니다..
프로젝트를 전체적으로 EnvironmentObject를 사용하는 것이 아닌, 메인뷰에 State를 선언해주고 하위뷰에서는 Binding을 통해 접근하는 방식으로 변경해주었습니다.

2023-05-31 06:40 UTC, kak1x commented on ProjectManager/ProjectManager/View/MainView/ProjectListCell.swift
> +    @EnvironmentObject private var viewModel: ProjectViewModel
`EnvironmentObject`는 앱 전역적으로 사용될 데이터에 사용한다고 공부했어서, 현재 프로젝트에서 `ProjectViewModel`은 전역적으로 사용된다고 생각되어 사용했었습니다.
아직 State와 EnvironmentObject를 어떤 시점에 사용하면 되는지 그 차이를 명확히 알지 못해 추가적인 학습이 더 필요하다고 생각되지만, 혹시 현 프로젝트에서 전역적으로 사용되는 `ProjectViewModel`을 `EnvironmentObject`로 받아 사용하는데 좋지 못한 이유를 알 수 있을까요..?

2023-05-31 07:01 UTC, juun97 commented on ProjectManager/ProjectManager/View/MainView/ProjectListContextMenuView.swift
> +    let project: Project
404d89c810c5b33715796440fd6912c4fc964141

기존에 private 을 설정을 해보았는데, 이니셜라이저에서 오류가 발생해 적절한 방법이 아닌줄 알았습니다.  하지만 자료를 찾아보니 프로퍼티에 private 을 설정할경우 initializer 를 커스텀해서 사용을 해야했습니다.

그방식에 맞춰 접근제한자를 다 설정 했습니다.

2023-05-31 07:45 UTC, juun97 commented on ProjectManager/ProjectManager/View/MainView/ProjectListHeaderView.swift
> +                Text(String(viewModel.search(state: state).count))
0a802a0a0e12f373baf612ad638f8d3c94e934a5

외부에서 count 에 대한 바인딩을 진행하고 바인딩 된 값을 넘겨주는것으로 변경했습니다!

2023-06-01 08:53 UTC, kak1x commented on ProjectManager/ProjectManager/View/MainView/ProjectListView.swift
> +}
extention을 제거해주고 `ProjectListSectionView` 를 구현하여 이를 사용하도록 변경하였습니다. d29c8351b6575372054427503979b5a83d54ecb8

2023-06-01 08:55 UTC, juun97 commented on ProjectManager/ProjectManager/View/MainView/ProjectMainView.swift
> +    @State private var showModal = false
EnvironmentObject 는 데이터를 전역적으로 공유하기 위해 사용이 되고 반드시 값을 외부에서 주입을 해야합니다.

State는 뷰 내부에서 사용하는 데이터의 상태를 관리하기 위해 사용하며, Source of Truth입니다.

2023-06-01 08:57 UTC, kak1x commented on ProjectManager/ProjectManager/View/MainView/ProjectListContextMenuView.swift
> +    @EnvironmentObject private var viewModel: ProjectViewModel
뷰모델을 받지 않고 클로저를 전달받는 방식으로 변경하였습니다.
이를 위해 뷰모델을 클래스로 정의해주었습니다. 522e8cce4d1ab97c1439830372ef2b3b05f2aaca

2023-06-22 09:10 UTC, closed without merging