프로젝트 매니저 [STEP 2] Brody, Rowan
yagom-academy/ios-project-manager pull request #283
Opened 2023-05-31 04:03 UTC by Kyeongjun2

# STEP 2 PR
@havilog
안녕하세요 하비! Brody, Rowan 조 STEP 2 PR 보내드립니다 🫡
정말 오래걸렸네요...

compositionalLayout / MVVM에 대해 자세히 알아보는 시간이었습니다..!

이번 리뷰도 잘 부탁드립니다~~

---

## 고민한 점
### 🔸 의존성 주입
각 타입의 프로퍼티에 기본값을 할당하기 보다는 이니셜라이저를 통해 주입받을 수 있도록 했습니다.

예를 들어, DateFormatter의 경우 TaskCellViewModel에서 사용되기 때문에 기본값을 할당하면 여러개의 인스턴스가 생성됩니다.

하나의 인스턴스만 활용하기 위해 DateFormatter를 최상위 뷰컨트롤러에 만들어 사용되는 타입으로 전달할 수 있도록 하였습니다.

모든 프로퍼티가 Protocol타입으로 정의되어있지 않기 때문에 아직 완벽하게 Testable한 코드는 아니지만 protocol만 정의해주면 testable하게 될 것 같습니다.

</br>

### 🔸 요구사항에 맞는 레이아웃 설계
초기에는 하나의 컬렉션 뷰에서 컴포지셔널 레이아웃으로 세 개의 테이블뷰가 보이도록 만들었지만 이는 확장성이 떨어지고 레이아웃 잡는 코드가 복잡하다는 것을 직접 코드를 작성하면서 느꼈습니다.

그래서 하나의 컬렉션 뷰에서 관리하는 것이 아닌 3개의 컬렉션 뷰를 만드는 것이 좋다고 생각했습니다.
하지만 3개의 컬렉션 뷰는 화면에 task를 보여주는 공통의 역할을 하기에 한단계 상위의 뷰컨에서 하나의 컬렉션 뷰 타입을 갖는 여러개의 인스턴스를 갖도록 만들었습니다. 
```swift
// mainViewController.swift
self.addChild(TaskCollectionViewController(viewModel: todoViewModel,
                                           dateFormatter: dateFormatter))
self.addChild(TaskCollectionViewController(viewModel: doingViewModel,
                                           dateFormatter: dateFormatter))
self.addChild(TaskCollectionViewController(viewModel: doneViewModel,
                                           dateFormatter: dateFormatter))
```

그리고 추후 특정 뷰모델에만 기능이 추가되었을 경우. 예를 들어 `DoingViewModel`에만 특정 기능이 추가되었을 경우를 대비해서 하나의 뷰모델타입에서 `enum`타입을 이용해 분기처리하는 것이 아닌 컬렉션 뷰에 매칭되는 각각의 구체적인 뷰모델을 갖도록 만들었습니다. 

```swift
// 뷰모델에서 공통적으로 어떤 함수를 요청하고 받을 지를 추상화한 프로토콜
protocol TaskListViewModel { }

final class TodoViewModel: TaskListViewModel { }
final class DoingViewModel: TaskListViewModel { }
final class DoneViewModel: TaskListViewModel { }
````

</br>

### 🔸 TaskListViewModel - taskList 감지하기
`@Published` attribute를 설정한 프로퍼티가 publisher를 통해 값을 발행하는 타이밍이 프로퍼티 `willSet`이라는 것을 공식문서를 통해 알게 되었습니다.

이에 따라 $를 통해 해당 프로퍼티의 퍼블리셔를 이용하여 sanpshot을 dataSource에 apply하는 메서드를 바인딩하게 되면,
CollectionView에 taskList의 변경사항이 반영되지 않은 채로 snapshot apply가 진행되어 Out of range 크래시가 발생하는 문제가 있었습니다. (ex. createTask의 경우)

이를 해결하기 위해 taskList의 didSet과 PassthroughSubject를 활용하여 taskList가 set 되어진 이후 스트림에 변경된 list를 send 했습니다.

```swift
var taskList: [Task] = [] {
    didSet {
        currentTaskSubject.send((taskList, isUpdating))
    }
}
let currentTaskSubject = PassthroughSubject<([Task], Bool), Never>()
```

</br>

### 🔸 View 관련 Filetree
화면을 기준으로(main, detail, changeWorkState) 폴더를 나누고 매칭되는 뷰와 뷰모델을 모아서 정리했습니다.

</br>

## 조언을 얻고싶은 점

### 🔸 반응형 프레임워크 + Diffable DataSource에서 업데이트 시 전체가 reload되는 문제.
현재 `TodoViewModel`이라는 뷰모델 내의 `taskList`프로퍼티가 변경되었을 때 이를 구독하고 있는 `taskCollectionViewController`에서 변경된`taskList`을 받아, 이를 이용해 스냅샷을 업데이트하고 있습니다.

```swift
private func bindViewModelToView() {
    viewModel
        .currentTaskSubject
        .sink { taskList, isUpdating in
            isUpdating ? self.reloadDataSourceItems() : self.applyLatestSnapshot(taskList)

            self.viewModel.setState(isUpdating: false)
        }
        .store(in: &bindings)
}

private func applyLatestSnapshot(_ taskList: [Task]) {
    let taskIDList = taskList.map { $0.id }

    let section = Section.main(count: viewModel.taskList.count)
    var snapshot = Snapshot()
    snapshot.appendSections([section])
    snapshot.appendItems(taskIDList, toSection: section)
    dataSource?.apply(snapshot)
}

private func reloadDataSourceItems() {
    guard var snapshot = dataSource?.snapshot() else { return }
    let taskListID = viewModel.taskList.map { $0.id }

    snapshot.reloadItems(taskListID)
    dataSource?.apply(snapshot)
}
```

하지만 이 코드는 전달받은 `taskList`에 해당하는 `id`들을 전부 가져와 `reloadItems`를 하고 있기 때문에 특정 셀만 변경되었는데도 불구하고 전체 아이템이 reload되는 문제를 갖고 있습니다.

반응형 프레임워크를 사용하기 전에는 수정되는 task의 id를 반환해서 그 id만 reload한 뒤에 `dataSource.apply(snapshot)`을 호출해서 셀 하나만 업데이트 되도록 만들었는데 현재 상태에서 이와 같이 해결하는 방법을 찾지 못했습니다.

이 문제를 어떻게 해결하면 좋을까요?

</br>

### 🔸 ViewModel이 TaskList를 갖고 있어도 되는가
현재 MainViewModel과 TaskListViewModel에 프로퍼티로 taskList를 가지고 있습니다. 이에 따라 해당 list에 append / remove 하는 등의 로직을 view model이 가지게 되는데 이는 뷰 로직이 아니라 데이터 로직으로 생각될 수도 있을 것 같습니다.

이를 해결하기 위해 Service에서 fetch 할 때, Publisher<[Task], Never>를 반환해주는 식으로 바꿔보는게 어떨까 생각해봤습니다..

하비의 의견은 어떠신가요??? 🤔

</br>

### 🔸 cellProvider에서 셀을 dequeue했을 때 reuseIdentifier가 없을 때 처리
현재 컬렉션 뷰를 갖고있는 `TaskCollectionViewController`안에서 `DiffableDatasource`에 전달하는 `cellProvider`는 다음과 같이 구현되어있습니다.
```swift
private func cellProvider(_ collectionView: UICollectionView, indexPath: IndexPath, identifier: Task.ID) -> UICollectionViewCell? {
    guard let cell = collectionView.dequeueReusableCell(
        withReuseIdentifier: TaskCell.identifier,
        for: indexPath
    ) as? TaskCell else {
        fatalError("cell does not have a reuseIdentifier")
    }

    guard let task = self.viewModel.taskList.filter({ $0.id == identifier }).first else {
        fatalError("There is nonexistent identifier")
    }

    let taskCellViewModel = TaskCellViewModel(task: task, dateFormatter: dateFormatter)
    cell.provide(viewModel: taskCellViewModel)

    return cell
}
```

snapshot에서 주입하는 id가 뷰모델의 `taskList`와 매칭되지 않을 때 `fatalError`로 크래시나게 만들어주고 있습니다. 

**fatalError를 선택한 이유**
* guard 문에서 else에 걸렸을 때 `UICollectionViewCell()`을 리턴해준 경우, cell이 dequeueReusableCell을 통해 반환되지 않았다는 크래시가 발생함

반면에, UICollectionViewDataSource를 채택했을 때는 cellForItemAt 메서드에서 빈 UICollectionViewCell을 반환하는 것이 가능했습니다.

앱을 일부러 크래시 내는 코드는 피하는 것이 좋다고 생각하는데, DiffableDataSource에서도 fatalError를 사용하지 않고 빈 Cell을 반환해주는 방법을 활용할 수 있을까요?

2023-05-31 06:43 UTC, havilog requested changes
![image](https://github.com/yagom-academy/ios-project-manager/assets/57659933/d3eb6e38-ca44-49fa-8a41-31c054016586)

edit 눌렀을 때 timeout이 일어나고 있어요

> 🔸 반응형 프레임워크 + Diffable DataSource에서 업데이트 시 전체가 reload되는 문제.

코멘트 참고

> 🔸 ViewModel이 TaskList를 갖고 있어도 되는가

저는 개인적으로 `Publisher`는 가독성이 좋지 않고, 읽기 힘들다고 생각해서,
만들어도 큰 상관은 없을거 같긴 한데, 여러 방식들을 비교해보고 만들면 좋을거 같아요

> 🔸 cellProvider에서 셀을 dequeue했을 때 reuseIdentifier가 없을 때 처리

크래시는 진짜 최악의 상황에서만 발생해야하는거라..
reuseIdentifier가 없어서 셀 하나가 안보이는 짜친 이슈같은 경우에는,,
디버그일 때만 assert나 preconditionFailure같은거 찍어놓고
그냥 빈 셀 리턴시켜줘도 괜찮을거 같아요


프로토콜을 더 잘 쓰면 좀 더 제너럴하게 쓰이는 MVVM이 될 거 같아요!
두 분 모두 익숙하지 않은 프레임워크 사용하시느라 고생 많으셨구
조금 더 달려봅시다 : )

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/SceneDelegate.swift
> +        ]
이 default로 넣어주는 아이들은 요구사항인가요??
테스트용으로 보여서요

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/Model/Task.swift
> +struct Task: Identifiable {
`Task`라는 이름은 좀 알아보기 힘든거 같아요.
FirstParty에서 async/await에서 쓰이는 Task와 같은 단어라서
다른 네이밍을 찾아보는게 나을거 같다고 생각됩니다!

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/Model/Task.swift
> +    var workState: WorkState
workState가 바뀐다면, id도 바껴서 새 객체를 만들어주는거랑 비슷해보이는데, variable로 선언하신 이유가 있을까요?

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/Model/Task.swift
> +struct Task: Identifiable {
테스트 짜셨는지 확인 안해봤지만,
테스트를 위해서 보통 모델들은 기본적으로 equatable 하면 좋아요

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/Model/WorkState.swift
> +    }
이건 그냥 권장도 아니고 개인 의견인데,
WorkState자체에 rawValue로 주거나, `CustomStringConvertible`을 채택시켜주는 방법도 고려해 볼 수 있을거 같아요

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/Protocols/TaskListViewModelDelegate.swift
> +    func deleteTask(id: UUID)
개인적인 취향이니까 참고만 해주세요 ㅎㅎ

```suggestion
    func create(task: Task)
    func update(task: Task)
    func deleteTask(id: UUID)
```

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/Protocols/TaskListViewModel.swift
> +    func deleteTask(at index: Int)
TaskListViewModelDelegate에서는 id 로 지우고,
여기에서는 index로 지우는데
어떤 기준일까요?

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/Protocols/DetailViewModelDelegate.swift
> +    func updateTask(_ task: Task)
이 두 함수들은 계속 반복적으로 존재하는데,
TaskHandlable(가칭)과 같은 프로토콜 하나로 뺄 수는 없었을까요?

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/Extensions/Combine/UITextField+Combine.swift
> +}
저도 옛날에는 이런 Extension들 많이 만들어 썼었는데요,
이게 쓰면 코드가 이뻐지긴 하는데,
다른 협업하는 사람들이 이코드를 모르고 안쓰면 레거시가 되는 코드라서
이런 간단한 코드는 그냥 뷰에 두는게 나은거 같아요.

또한 여기서 self.text ?? "" 이 부분은 비즈니스로직이라고 불릴 수도 있을거 같은데,
이런 부분은 디버깅 하기도 힘들어지구요

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/Protocols/ChangeWorkStateViewModelDelegate.swift
> +}
보통 프로토콜은 이렇게 프로토콜 폴더에 안모아두고,
해당 프로토콜을 준수하는 객체나,
연관있는 네임스페이스에 정의하는게 나은거 같아요.
아니면 이 프로토콜이 어디서 뭐하는 역할인지 확인하려고 페이지 점핑이 일어날 수 있어서요

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/ChangeWorkStateView/ChangeWorkStateViewController.swift
> +    private var bindings = Set<AnyCancellable>()
요것도 취향이긴 한데, 보통 AnyCancellable를 담는 변수명을 cancellables로 하는게 일반적이라고 알고있어요

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/ChangeWorkStateView/ChangeWorkStateViewController.swift
> +            stackView.bottomAnchor.constraint(equalTo: safe.bottomAnchor, constant: -5)
요것도 취향차이긴 한데,
굳이 지역변수 만들어서 메모리 안잡아먹고 view.safeAreaLayoutGuide로 풀어쓰는게 더 가독성이 좋다는 사람들도 있어서 참고차 말씀드려여
고칠 정도까진 아닌듯

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/ChangeWorkStateView/ChangeWorkStateViewController.swift
> +            .store(in: &bindings)
leak 나겠네여 ㅎㅎ

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/ChangeWorkStateView/ChangeWorkStateViewController.swift
> +    private func bindViewModelToView() {
함수명 bind()로만 해도 괜찮을거 같아여 ㅎㅎ

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/DetailView/DetailViewController.swift
> +    }
여기두 leak 날거 같아여

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/DetailView/DetailViewController.swift
> +    private func bindViewToViewModel() {
네이밍을 bindAction, bindState로 나눠도 괜찮겠네여

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/DetailView/DetailViewController.swift
> +                let rightBarButtonItem = self.navigationItem.rightBarButtonItem
지역변수로 잡아주는 이유가 뭔가여??
+여기도 weak

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/DetailView/DetailViewModel.swift
> +final class DetailViewModel {
어떤 함수, 변수가 뷰컨에서 접근이 가능하고, 불가능한지
즉 viewmodel에 들어갈 input
뷰에서 옵저빙할 output이 명시되면
더 가독성이 좋은 코드가 될거 같아요.

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/MainView/MainViewController.swift
> +    let mainViewModel: MainViewModel
UI Property 사이에 뷰모델이 ..?!

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/MainView/MainViewModel.swift
> +        distributeTask()
workState가 바뀔 때 마다 모든 TaskList를 fetch해와서 전체 리로드가 발생하는거 같아요.
메인 뷰모델에서 todoList, DoingList, DoneList를 가지고 있고,
CRUD에 성공했을 때 메모리에 들고 있는 배열의 element를 바꿔주는 방식은 혹시 고려해보셨을까요??

+ CRUD를 할 때 실패할 수도 있을거 같은데 지금 코드는 로컬 스토리지에서 실패하는 경우를 가정하고 있지 않아요.
이 부분도 고려해서 수정해주세여

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/MainView/TaskCell/TaskCell.swift
> +    }
셀에도 뷰모델이 필요한가?
에 대해서는 정답은 없긴 한데요,

제 생각을 말씀드리면, 뭔가 셀 자체적으로 API를 찌르거나 CRUD를 하거나,
캐싱같은 비지니스 로직들이 들어가게 된다면 필요하다고 보는데,

지금 같은 경우에는 데이터 조각 들(String)만 가지고 셀을 그릴 수 있을거 같아요

역할 분리와 오버엔지니어링은 한끗차이라서 요 부분도 잘 고려해보고 개발하시면 도움될거 같아요 ㅎㅎ

틀렸다는거 아닙니다!

2023-05-31 06:43 UTC, havilog commented on ProjectManager/ProjectManager/MainView/TaskCollectionView/DoingViewModel.swift
> +    }
사실 didSet이 편하긴 한데 ,,,
didSet은 테스트 하기 힘들어져서 저는 잘 안쓰긴 해요 ㅋㅋ

2023-05-31 12:17 UTC, Kyeongjun2 commented on ProjectManager/ProjectManager/Model/Task.swift
> +struct Task: Identifiable {
Equatable 채택했습니다!

2023-05-31 12:18 UTC, seunghyunCheon commented on ProjectManager/ProjectManager/Model/Task.swift
> +struct Task: Identifiable {
`Plan`으로 변경했습니다!

2023-05-31 12:27 UTC, Kyeongjun2 commented on ProjectManager/ProjectManager/Model/WorkState.swift
> +    }
`case.rawValue` 보다는 `case.text`가 좀 더 보기 편하다고 생각해서 현재 상태를 유지했습니다!

CustomStringConvertible 같은 경우, 공식문서 상에서 description 프로퍼티를 정의한 후 해당 프로퍼티에 직접 접근하는 것은 권장되지 않고 `String(describing:)`메서드를 호출해야하기 때문에 이 부분도 `.text`가 더 한 눈에 들어올 것 같다고 생각합니다. 🤔

2023-05-31 12:39 UTC, seunghyunCheon commented on ProjectManager/ProjectManager/Protocols/TaskListViewModel.swift
> +    func deleteTask(at index: Int)
컬렉션 뷰 내에서는 index가 존재하기 때문에 한 번에 index에 접근해서 지웠고, `service`내부의 plan배열에는 workState별로 나눠져있지 않아서 인덱스로 접근하기가 까다로워 id를 통해 해당 요소의 인덱스를 구했습니다. 

추후 todo, doing, done에 해당하는 배열 3개를 가지면서 이 부분을 해결할 것 같습니다.

2023-06-01 05:41 UTC, Kyeongjun2 commented on ProjectManager/ProjectManager/Protocols/DetailViewModelDelegate.swift
> +    func updateTask(_ task: Task)
`PlanManagable` 이라는 프로토콜로 create(task:), update(task:) 메서드를 뽑아 줬습니다!

2023-06-01 05:55 UTC, seunghyunCheon commented on ProjectManager/ProjectManager/ChangeWorkStateView/ChangeWorkStateViewController.swift
> +    private func bindViewModelToView() {
`DetailViewController`의 경우 뷰에서 뷰모델로 바인드하는 부분과 뷰모델에서 뷰에 바인드하는 부분 두 가지가 존재해서 메서드 이름을 구분시켜주었습니다. 이러한 경우에도 `bind`안에 양방향 바인딩하는 부분을 넣어도 될까요?

2023-06-01 06:08 UTC, seunghyunCheon commented on ProjectManager/ProjectManager/DetailView/DetailViewController.swift
> +    private func bindViewToViewModel() {
해당 이름으로 수정하였습니다!

2023-06-01 06:09 UTC, Kyeongjun2 commented on ProjectManager/ProjectManager/Protocols/TaskListViewModelDelegate.swift
> +    func deleteTask(id: UUID)
하비의 suggestion으로 변경했습니다~!  👍

2023-06-01 06:10 UTC, Kyeongjun2 commented on ProjectManager/ProjectManager/Extensions/Combine/UITextField+Combine.swift
> +}
닐 병합 연산자를 삭제하고 AnyPublisher<String?, Never>로 수정하였습니다!

2023-06-01 06:12 UTC, Kyeongjun2 commented on ProjectManager/ProjectManager/ChangeWorkStateView/ChangeWorkStateViewController.swift
> +    private var bindings = Set<AnyCancellable>()
bindings를 모두 cancellables로 수정했습니다!

2023-06-01 06:14 UTC, Kyeongjun2 commented on ProjectManager/ProjectManager/Protocols/ChangeWorkStateViewModelDelegate.swift
> +}
프로토콜을 적절한 위치에 옮겨주었습니다 ~~

`ReusableIdentifier` 프로토콜의 경우에는 여러 타입에서 사용할 수 있을 것 같아서 따로 빼두었는데
이 프로토콜도 Cell 위쪽으로 옮기는게 나을까요? 🤔

2023-06-02 12:03 UTC, Kyeongjun2 commented on ProjectManager/ProjectManager/MainView/TaskCollectionView/DoingViewModel.swift
> +    }
`@Published` attribute를 삭제하면서 didSet이 없어졌습니다~~

2023-06-02 12:05 UTC, seunghyunCheon commented on ProjectManager/ProjectManager/SceneDelegate.swift
> +        ]
요구사항이 아니라서 지웠습니다!

2023-06-02 12:07 UTC, seunghyunCheon commented on ProjectManager/ProjectManager/ChangeWorkStateView/ChangeWorkStateViewController.swift
> +            .store(in: &bindings)
`weak self`붙여주었습니다!

2023-06-02 12:07 UTC, seunghyunCheon commented on ProjectManager/ProjectManager/ChangeWorkStateView/ChangeWorkStateViewController.swift
> +    private func bindViewModelToView() {
해당 이름으로 수정하였습니다!

2023-06-02 12:08 UTC, seunghyunCheon commented on ProjectManager/ProjectManager/DetailView/DetailViewModel.swift
> +final class DetailViewModel {
중첩타입으로 viewModel에 들어갈 이벤트들을 `input`으로, 옵저빙할 요소로 `output`으로 명시해주었습니다.

2023-06-02 12:08 UTC, Kyeongjun2 commented on ProjectManager/ProjectManager/MainView/TaskCell/TaskCell.swift
> +    }
셀 뷰모델을 만들 때 Combine 활용에 대해서 계속 알아보고 있었습니다...
그래서 사용방법도 익힐 겸 바인딩을 해봤는데 하비 말씀대로 string을 그냥 텍스트에 넣어주기만 해도 변경될 일이 없었네요 하하하하 😅

2023-06-02 12:14 UTC, seunghyunCheon commented on ProjectManager/ProjectManager/Model/Task.swift
> +    var workState: WorkState
`workState`가 바뀌면 `id`도 바껴서 새 객체를 만들어주는 것과 비슷하다는 말씀이 이해가 잘 되지 않습니다! 
저희는 `todo`섹션의 셀이 `doing`섹션으로 이동할 때 `id`는 동일하고 `workState`만 변경이 되어야 `DiffableDataSource`에서 변경사항에 대한 스냅샷 차이를 계산할 것이라고 생각이 들어서 `var`로 설정해주었습니다.

2023-06-02 12:15 UTC, Kyeongjun2 commented on ProjectManager/ProjectManager/MainView/MainViewModel.swift
> +        distributeTask()
CRUD에 실패할 경우를 고려하기 위해 스트림을 만들 때 tryMap을 활용해 적절한 Error를 던질 수 있도록 해봤습니다!

말씀해주신 대로 CRUD에 성공하면 메모리에 들고 있는 배열의 plan 인스턴스를 바꿔주도록 변경했습니다. 👍

2023-06-02 12:35 UTC, Kyeongjun2 commented on ProjectManager/ProjectManager/DetailView/DetailViewController.swift
> +    }
ViewModel에 Input/Output을 정의한 뒤 Event Stream이 연결되도록 설계하면서
assign operator는 사용하지 않게 되었습니다. 👀

2023-06-02 12:38 UTC, Kyeongjun2 commented on ProjectManager/ProjectManager/MainView/MainViewController.swift
> +    let mainViewModel: MainViewModel
DateFormatter는 UI Property가 아니라고 생각해서
UI property - internal property - private property 순으로 나열했습니당,,,

2023-06-03 11:23 UTC, havilog commented on ProjectManager/ProjectManager/Protocols/ChangeWorkStateViewModelDelegate.swift
> +}
요건 그냥 Extension에 넣으면 될 거 같아요

2023-06-22 09:10 UTC, closed without merging