프로젝트 매니저 [STEP3] 레옹아범
yagom-academy/ios-project-manager pull request #285
Opened 2023-06-01 08:06 UTC by fatherLeon

@AppleCEO
안녕하세요 도미닉
STEP3까지 나름? 제 시간안에 구현을 한 것 같아 다행인 것 같습니다.
다만, 보너스 스텝, 구조적인 문제, 사용자마다 DB가 나뉘어져야될 거 같은데 여러 부분들에 대한 세부적인 구현이 조금 아쉬웠던 것 같습니다.
마지막 스텝도 리뷰 잘 부탁드리겠습니다🙇

### 네트워크 RemoteDB 실시간 구현
|할일 추가|할 일 수정|할 일 삭제|
|----------|----------|----------|
|<img src="https://github.com/yagom-academy/ios-project-manager/assets/55453151/83d6b66b-4284-4ef0-ba3c-bd6f07c75fef" width=916>|<img src="https://github.com/yagom-academy/ios-project-manager/assets/55453151/9e9f6bb0-f25c-4d9c-a43d-4dfacd5950c1" width=916>|<img src="https://github.com/yagom-academy/ios-project-manager/assets/55453151/8a235bd2-c373-4098-91ac-16da37049dce" width=916>|

## 고민한 점
### 1️⃣ LocalDB(Realm)와 RemoteDB(Firebase)의 사용
* 언제 Local을 사용할지 Remote를 사용할지 두 DB의 동기화, 네트워크 환경에 따른 사용법 등에 대해 고민했습니다.
#### 🛜 온라인
* 온라인 상황일 때는 Firebase를 통해 생성, 수정, 삭제, 불러오기를 하며 Firebase만을 사용하고 Local에 반영을 하도록 만들었습니다.
* 이를 통해 현재 기기뿐만 아니라 외부기기에서도 이전에 등록했던 데이터에 접근할 수 있도록 구현하였습니다.
#### 🛜 오프라인
* 오프라인일 경우 LocalDB를 이용해 현재 기기에 저장된 정보만을 불러오도록 구현하였습니다.
* 생성, 수정, 삭제등에 대한 기능을 막아 RemoteDB와 서로 다른 데이터를 가지지 않도록 구현하였습니다.

### 2️⃣ 네트워크 상태 UI로 보여주기

![스크린샷 2023-05-31 오후 9 42 21](https://github.com/yagom-academy/ios-project-manager/assets/55453151/089de19c-25bc-4496-a621-933452b897a7)

* 우선 네트워크 상태 변화에 따라 Alert을 보여주도록 구현하였습니다.
* 다만 이렇게만 할 경우 앱을 오랫동안 사용할 경우 현재 네트워크 상태를 유저가 다시 확인할 방법이 없다고 생각하여 `NavigationItem`의 `Title`에 변화와 rightBarButtonItem을 비활성화 했습니다

|네트워크가 연결이 되어 있을 경우|네트워크가 연결이 되지 않은 경우|
|:-------:|:-------:|
|![Simulator Screenshot - iPad Pro (11-inch) (4th generation) - 2023-06-01 at 16 41 44](https://github.com/yagom-academy/ios-project-manager/assets/55453151/5a160c8a-6a30-4d24-85d6-608303013fa1)|![Simulator Screenshot - iPad Pro (11-inch) (4th generation) - 2023-06-01 at 16 42 09](https://github.com/yagom-academy/ios-project-manager/assets/55453151/700abf7f-23a1-457d-b3ff-41d9151cbf0f)|

## 해결하지 못한 점
* 현재 원격 DB는 사용자 구별없이 하나의 DB만 공유하기 때문에 다른 사용자가 추가한다면 그 외 사용자들에게도 해당 Task가 보여지는 문제가 있습니다.
* 여러 사용자가 구별할 수 있는 키워드를 어떻게 만들어야할지 현재 상황에서 어떻게 구현해야될지 잘 모르겠습니다.
* 만약 로그인을 하는 앱이라면 사용자 아이디 혹은 닉네임등으로 구별이 가능할 것 같은데 지금과 같이 로그인하지 않는 앱일 경우 사용자들을 어떻게 구별해야될지? 잘 모르겠습니다.

2023-06-01 14:22 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
고생하셨습니다 @fatherLeon 
기한 안에 너무 잘 완수하셔서 멋집니다!
개선할 점들 코멘트로 작성해봤습니다. 확인 부탁드려요~

# 해결하지 못한 점
- 현재 원격 DB는 사용자 구별없이 하나의 DB만 공유하기 때문에 다른 사용자가 추가한다면 그 외 사용자들에게도 해당 Task가 보여지는 문제가 있습니다.
- 여러 사용자가 구별할 수 있는 키워드를 어떻게 만들어야할지 현재 상황에서 어떻게 구현해야될지 잘 모르겠습니다.
- 만약 로그인을 하는 앱이라면 사용자 아이디 혹은 닉네임등으로 구별이 가능할 것 같은데 지금과 같이 로그인하지 않는 앱일 경우 사용자들을 어떻게 구별해야될지? 잘 모르겠습니다.

회원 로그인을 이메일 등으로 구현하거나 핸드폰의 UUID 로 이 기종에서만 데이터를 보이게 해줄 수 있겠습니다!

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/Extension/Date+Extension.swift
> +    var formatedListDateText: String {
이름이 길어지고 명확해졌네요! 👍

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/ListScene/ViewController/ListViewController.swift
> +        }
저는 이 형태를 좋아하긴 합니다! ㅎㅎ 💯

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/ListScene/ViewController/ListViewController.swift
> +        collectionView.deselectItem(at: indexPath, animated: true)
선택한 아이템을 지워주는 것 좋네요~ 🥇

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/ListScene/ViewModel/ListViewModel.swift
> +        guard isNetworkConnecting == true else { return }
이 것과 == true 를 생략한 코드와 어떤 차이가 있을까요?
이 방식을 선택하신 이유를 알 수 있을까요?

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/MainScene/ViewController/HistoryViewController.swift
> +        return cell
여기서 if let 을 쓰면 어떨까요? ㅎㅎ

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/MainScene/ViewController/MainViewController.swift
> +        configureViewModel()
추상화 단계가 다 같아서 정돈되 보이네요~ 🔢

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/MainScene/ViewController/MainViewController.swift
> +        showErrorAlert(error)
여기서 if let 이 더 보기 좋을 것 같아요!
if let 과 guard let 을 쓰는 곳을 구분할 수 있도록 둘 다 시도해보시고 감을 잡아가시면 좋겠습니다.
guard let 만 쓰지 말고요~

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/MainScene/ViewController/MainViewController.swift
> +        navigationItem.title = isConnect == true ? "Project Manager" : "🔴 Project Manager"
3항 연산자를 사용해보셨군요! 👍 
여기도 == true 가 없어도 될 것 같은데요.
이렇게 작성하신 이유가 있을까요?

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/MainScene/ViewController/MainViewController.swift
> +
여기 공백은 어떤 의미일까요?
코드에는 공백이나 줄바꿈 하나에도 의미가 있어야 합니다.
의도를 나타낼 수 있는 최소한의 줄바꿈을 추천드려요.
무조건 적은 줄의 코드가 좋다는 뜻은 아닙니다~

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/DataBase/DBManager.swift
> +        if isConnect {
if문이 명확하네요! == true 가 없어도 보기 좋아요

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/DataBase/LocalDBManager.swift
> +        let objectList = Array(objects).compactMap { storable in
오우... compactMap 을 써보셨군요 🥇

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/DataBase/LocalDBManager.swift
> +        create(object: object)
!= 비교에 else 를 붙이면 좀 복잡해지는 경향이 있습니다.
여기도 if 로 바꿔볼까요?

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/DataBase/RemoteDBManager.swift
> +        guard let ref = self.ref else {
ref 는 무엇의 줄임말일까요? 
저는 코드를 작성할 때 줄임말을 작성하지 않습니다. 나중에 의미가 헷갈리고 명확하지 않아서요.
Xcode 에 tab 을 쓰면 자동완성이 되어서 길게 작성해도 불편하지 않습니다!

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/DataBase/RemoteDBManager.swift
> +            }
여기도 if 를 사용하는 것으로 더 좋아질 수 있을까요?

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/HistoryManager.swift
> +    private var historyList: [History] = []
저는 List 보다는 어떤 값이 배열이면 그 이름에 s 를 붙이는 편이에요.

2023-06-01 14:22 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/HistoryManager.swift
> +        return historyList.sorted { $0.date > $1.date }
여기 $0, $1 을 사용하지 않고 기본형으로 전체를 풀어서 작성해볼까요?

2023-06-02 08:09 UTC, fatherLeon commented on ProjectManager/ProjectManager/MainScene/ViewController/HistoryViewController.swift
> +        return cell
```swift
if let cell = tableView.dequeueReusableCell(withIdentifier: HistoryCell.identifier) as? HistoryCell {
    cell.updateLabel(by: histories[indexPath.row])
    
    return cell
}

return UITableViewCell()
```

* 위와 같이 변경하였습니다.
* `if`문만 존재하여도 가독성부분에서 큰 차이가 없고 오히려 `else`문이 가독성을 해치는것 같아 `if`문만 사용하였습니다.

2023-06-02 08:19 UTC, fatherLeon commented on ProjectManager/ProjectManager/MainScene/ViewController/MainViewController.swift
> +        showErrorAlert(error)
```swift
@objc private func bindErrorHandler(_ noti: Notification) {
    if let error = noti.userInfo?["error"] as? Error {
        showErrorAlert(error)
    }
}
```

* 위와 같이 수정했습니다
* `guard`문보다 코드도 짧고 더 이해하기 쉬운것 같습니다

2023-06-02 08:41 UTC, fatherLeon commented on ProjectManager/ProjectManager/Model/DataBase/RemoteDBManager.swift
> +            }
```swift
if error == nil {
    let snapshotValue = snapshot?.value as? NSDictionary
    var fetchedData: [Storable] = []
    
    snapshotValue?.forEach({ key, value in
        let value = value as? NSDictionary
        
        if let task = Task.convertToStorable(value) {
            fetchedData.append(task)
        }
    })
    
    completion(.success(fetchedData))
    return
}
```

* 해당부분 뿐만 아니라 `forEach`문 안의 부분도 코드가 조금 더 짧아지고 가독성이 좋은것 같아 `if`문으로 바꿨습니다

2023-06-02 08:42 UTC, fatherLeon commented on ProjectManager/ProjectManager/Model/HistoryManager.swift
> +    private var historyList: [History] = []
```swift
private var histories: [History] = []
```

* 복수형으로 바꿨습니다!!

2023-06-02 09:26 UTC, fatherLeon commented on ProjectManager/ProjectManager/Model/HistoryManager.swift
> +        return historyList.sorted { $0.date > $1.date }
```swift
var sortedHistories: [History] {
    return histories.sorted { prevHistory, nextHistory in
        return prevHistory.date > nextHistory.date
    }
}
```
* 기본형으로 바꾸어 보았습니다

2023-06-02 10:35 UTC, fatherLeon commented on ProjectManager/ProjectManager/ListScene/ViewModel/ListViewModel.swift
> +        guard isNetworkConnecting == true else { return }
`== true`의 경우 특정 변수가 `Boolean`타입이라는 것과 확실한 조건을 보여줄 수 있을 것 같습니다.
나름 고민해보니 변수 명이 Boolean타입이라는 점과 어떤 상황일 때 어떤 값일지 확실하게 보여준다고 생각하여 `if`문으로 생략하는 코드로 변경하였습니다.

2023-06-02 10:37 UTC, fatherLeon commented on ProjectManager/ProjectManager/MainScene/ViewController/MainViewController.swift
> +        navigationItem.title = isConnect == true ? "Project Manager" : "🔴 Project Manager"
이 부분도 위에서 답변한 것처럼 조금 더 확실하게 조건문을 보여주기 위해 명시를 해줬는데 변수명이 Boolean타입인것을 확실하게 알려준다고 생각하여 생략하였습니다

2023-06-02 10:41 UTC, fatherLeon commented on ProjectManager/ProjectManager/MainScene/ViewController/MainViewController.swift
> +
크게 신경쓰지 않고 작성을 했던 것 같습니다😅
변수선언끼리 묶어주도록 줄바꿈을 삭제하였습니다

2023-06-02 10:44 UTC, fatherLeon commented on ProjectManager/ProjectManager/Model/DataBase/LocalDBManager.swift
> +        create(object: object)
넵 말씀해주신것 보고 코드 검토해보니
guard문에 조건을 쓸 경우 if문에 비해 불분명한 코드 같아서 `if`문으로 변경하였습니다.

```swift
func update(object: Storable) {
    if realm?.object(ofType: T.self, forPrimaryKey: object.id) == nil {
        delete(object: object)
        create(object: object)
        return
    }
    
    errorHandler?(DatabaseError.updatedError)
}
```

2023-06-02 10:58 UTC, fatherLeon commented on ProjectManager/ProjectManager/Model/DataBase/RemoteDBManager.swift
> +        guard let ref = self.ref else {
```swift
private var databaseReference: DatabaseReference?
```

* `reference`로 할지, `database`로 할지 고민했는데 말씀하신 것처럼 길게 작성해도 크게 불편하지 않을 것 같아 `databaseReference`로 변경하였습니다.

2023-06-22 09:10 UTC, closed without merging