프로젝트 매니저 [STEP 2-1] Minsup, Whales
yagom-academy/ios-project-manager pull request #304
Opened 2023-09-22 14:33 UTC by WhalesJin

안녕하세요 그린(@GREENOVER)!!!
Minsup<img src = "https://hackmd.io/_uploads/rJhCN3qkp.png" width = "20"> & Whales<img src = "https://hackmd.io/_uploads/Bkf_435kT.png" width = "20">
STEP2 PR 올립니다!!!
>스텝의 요구사항을 하위 스텝(2-1, 2-2, 2-3… 등등)으로 나누어 스스로 수행기한을 정해보세요.

라는 요구사항을 보고 말씀 드렸던 것처럼 `2-1` 과 `2-2` 두 파트로 쪼개서 진행해보았습니다!!

**STEP 2-1**
* 할일의 모든 변경사항은 디스크에 저장하지 않고 앱 종료 후 다시 실행하면 빈 화면을 출력합니다.
* 각 셀에는 [제목 / 설명 / 기한]이 표시됩니다.
    * 제목은 한 줄이며, 길면 잘라서 마지막 부분을 …로 표시합니다.
    * 설명이 세 줄 이상이면 세 줄 까지만 표시합니다.
    * 설명이 세 줄 이하라면, 설명글의 높이에 맞게 셀의 높이가 맞춰집니다.
* TODO와 DOING의 기한에 지난 날짜가 있으면 빨간색으로 표시합니다.
* 오른쪽 위의 + 버튼을 선택하면 새로운 할일을 추가하는 작성양식이 표시됩니다.
    * 작성한 할일은 [할일(TODO)] 영역에 추가합니다.
* 기한 날짜는 사용자의 지역 포멧에 맞게 표현해야 합니다.

><details>
>    <summary>STEP 2-2</summary>
>    
>* 할일을 터치하면 상세내용을 표시합니다. <br>
>    * Edit 버튼을 선택하면 수정할 수 있습니다. <br>
>* 할일을 길게 터치하여 팝오버 메뉴를 표시합니다. <br>
>    * 팝오버에 표시하는 메뉴는 상황에 따라 달라집니다. <br>
>        * TODO의 할일 : Move to DOING / Move to DONE <br>
>        * DOING의 할일 : Move to TODO / Move to DONE <br>
>        * DONE의 할일 : Move to TODO / Move to DOING <br>
>    * 본인의 판단에 따라 팝오버는 액션시트로 대체할 수 있습니다. <br>
>* 셀을 왼쪽으로 스와이프하여 삭제 메뉴를 표시하고, 끝까지 스와이프하거나 삭제 메뉴를 선택하면 해당 할일을 >삭제합니다.
></details>

현재, STEP 2-1을 마친 상태에서 PR을 보내고있고, 마무리 되는대로 2-2를 진행해서 한 번 더 PR 보내겠습니다!!

새로운 도전이 많은만큼 배울 점 또한 많을 것이라 예상합니다.
주시는 조언들 다 감사히 배우겠습니다!!
잘 부탁드립니다 🙇🏻‍ 🙇🏻‍♀️

 

## 🤹🏻 고민했던 점
### 🔹 CUSTOM MODIFIER

🚨 **문제점** <br>
- Custom View를 alert 형태로 띄우기 위한 방법을 모색했습니다. 기본 API는 주어지지 않아 직접 구현을 해야했습니다.

💡 **해결방법** <br>
- ZStack으로 배경과 alert을 나누고 그 사이에 검은 불투명 뷰를 넣어 alert이 띄어있는 효과를 만들었습니다. binding을 이용해 최대한 SwiftUI API와 비슷하게 만들었습니다.

### 🔹 파일 분리

Presentation 폴더에서 view와 viewModel을 기준으로 폴더를 분리했는데 기능이 많아질 수록 관리가 힘들어지고 한눈에 구조를 확인할 수 없을 것 같다고 판단하여 기능별로 폴더를 나누고 view와 viewModel을 한 곳으로 위치시켰습니다.

### 🔹 ViewModel - View 안에 있을지 밖에 있을지
🚨 **문제점** <br>
- 처음엔 아래와 같이 ViewModel을 각 View 안에 중첩타입으로 구현했습니다. 해당하는 ViewModel을 포함하는 View에서 다루기 쉽다는 장점이 있었지만, 다른 View에서 ViewModel에 접근할 수 없다는 문제점이 생겼습니다.
    ```swift
    extension KanbanView {
        final class ViewModel: ObservableObject { ... }
    }

    struct KanbanView: View {
        @ObservedObject var vm = ViewModel()
        ...
    }
    ```

💡 **해결방법** <br>
- 전역적으로 사용 가능하게끔 따로 빼내어 타입을 생성하였습니다.
    ```swift
    final class KanbanViewModel: ObservableObject { }
    ```

### 🔹 navigationBar
🚨 **문제점** <br>
- navigationBar의 색상이나 폰트 등을 수정하여 활용하고 싶었으나 iOS15에서는 SwiftUI의 navigationBar 부분이 미흡하여 UIKit을 일부 사용하였습니다. SwiftUI로 프로젝트를 진행하는만큼 UIKit을 쓰지 않고 구현할 수 있는 방법은 없을까 고민을 했습니다.
    ```swift
    init(vm: ViewModel = ViewModel()) {
        self.vm = vm

        let appearance = UINavigationBarAppearance()
        appearance.configureWithOpaqueBackground()
        appearance.backgroundColor = UIColor.systemBackground
        UINavigationBar.appearance().standardAppearance = appearance
        UINavigationBar.appearance().scrollEdgeAppearance = appearance
    }
    ```

💡 **해결방법** <br>
- iOS minimum version 변경 (iOS15 -> iOS16)
최소 버전을 iOS16으로 변경함에 따라 NavigationView가 아닌 NavigationStack으로 구현하면서 SwiftUI에 구현되어있는 modifier로 충분히 프로젝트 요구사항에 맞는 UI를 구현할 수 있게 되었습니다.
    ```swift
    NavigationStack {
        HStack { ... }
        .background(.quaternary)
        .navigationTitle("Project Manager")
        .navigationBarTitleDisplayMode(.inline)
        .toolbarBackground(.visible, for: .navigationBar)
        .toolbar {
            ToolbarItem(placement: .navigationBarTrailing) {
                Button {
                    kanbanViewModel.presentForm()
                } label: {
                    Image(systemName: "plus")
                }
            }
        }
    }
    ```
</br>

## 🎙️ 조언을 얻고싶은 점

### 🔸 뷰와 뷰모델이 1:1 관계여야하는가

현재 최상위뷰인 KanbanView가 Column, Card, TaskForm을 가지고 있습니다. 각 뷰마다 뷰모델을 1:1로 가지고 있는데 어떤 상황에서는 하위뷰가 상위 뷰모델을 가지고 있어야했습니다.

```swift
struct TaskFormView: View {
    //상위 뷰모델
    @EnvironmentObject var kanbanViewModel: KanbanViewModel
    //하위 뷰모델
    @ObservedObject var taskFormViewModel = TaskFormViewModel()
    ...
    Button("Done") {
        let task = taskFormViewModel.returnTask()
        //상위 뷰모델이 필요한 상황
        kanbanViewModel.create(task)
        kanbanViewModel.dismissForm()
    }
```
이런 경우 MVVM을 해치는 상황일까요?
MVVM은 뷰와 뷰모델이 1:1 관계여야 한다고 알고있는데 
지금 상황에서는 1:2인 상황이라고 생각합니다.

또 다른 방법으로는 하위 뷰모델이 상위 뷰모델을 가지고 있는 방법도 생각해봤는데 이 방법은 어떨까요? 

### 🔸 네이밍
```swift
@Published var title: String = ""
@Published var content: String = ""
@Published var date: Date = Date()

func returnTask() -> Task {
    Task(title: title, content: content, date: date)
}
```
title과 content, date를 이용해 Task를 만들어서 return하는 메소드의 네이밍을 고민하고 있었습니다.
make는 팩토리 패턴에서 사용하기 때문에 사용하지 못했습니다. returnTask의 네이밍은 적절할까요? 더 좋은 이름이 있다면 피드백 부탁드립니다

### 🔸 셀 사이의 간격
<img src = "https://hackmd.io/_uploads/B1UdrXskT.png" width = 200>
<현재 상태>

요구사항에는 셀 사이 간격이 존재하는데 SwiftUI에서는 셀 간격을 조절하는 API가 제공되지 않는 것 같습니다.

현재 Xcode 버전에서 나오는 메서드들 중 Separator 와 관련한 메서드들은 딱 구분선에만 관여하여 간격이 떼어지지 않고,[`listRowSpacing(_:)`](https://developer.apple.com/documentation/swiftui/view/listrowspacing(_:))이라는 메서드를 찾았으나 이는 새 Xcode 버전의 메서드라 구현되지 않는 듯 합니다. ([참고 블로그](https://swiftwithmajid.com/2023/06/06/what-is-new-in-swiftui-after-wwdc23/))

우회해서 간격을 설정하는 방법이 있을까요?

2023-09-22 21:46 UTC, GREENOVER requested changes
@WhalesJin @agilestarskim 
두분 스텝 2-1 수고 많으셨습니다!!
동작 구현 아주 잘 되고 코드 자체도 너무 깔끔하고 분리도 잘 되어 있네요 👍
전체적으로 SwiftUI를 목적에 맞게 코드 구성을 잘해주셔서 크게 리뷰할것은 없고 부분 코멘트들을 한번 달아보면서 의견도 여쭤봤습니다!
***
### 칭찬 드리고 싶은 부분
- 전체적으로 SwiftUI 이미 사용해보신것처럼 적절하게 잘 사용하시네요! 💯
- 네이밍과 파일 구조 및 그룹화가 잘 되어 있어요 💯
- 커스텀한 뷰 모디파이어를 만든것 아주 좋아요 💯
- 커밋도 잘 나눠져있고 커밋 컨벤션도 통일되어 있어 보기 좋습니다 💯
***
### 궁금하신 부분에 대한 저의 의견
1. 뷰와 뷰모델이 1:1 관계여야하는가
- 꼭 그럴 필요는 없습니다!
MVVM은 무조건 뷰와 뷰모델이 1:1 관계여야 된다는건 전 잘 모르겠습니다 ㅎㅎ
공식적으로 그렇게 나와있지도 않을뿐더러 1:1 관계를 지향하면 독립적으로 잘 나뉘어서 관리에 더 용이하다이지 MVVM도 추상적인 개념이기에 고정화된 외부 프레임워크를 사용한다면 강제적으로 1:1이 될 수는 있겠지만 개념적으로 1:1 이여야된다는건 아닐것 같아요.
그렇게 된다면 사실 `@EnvironmentObject` 개념 자체는 아예 MVVM 사상에서 벗어난것이지 않을까요!?
그렇기에 지금 구현해주신 코드처럼 많이 사용도 합니다!
또 말씀하신 하위 VM에서 상위 VM을 들고 있는 형태는 사용은 거의 안하긴 합니다.
하위 View에서 상위 VM을 주입받아 사용은 하더라도 하위 VM에서 상위 VM을 들고있는다는것 자체는 역전이 되어 버릴것 같아요.
상위 VM 개념에서 하위 VM 개념을 들고 있는 형태로는 괜찮겠지만요.
예를들어, 상태 관리를 초점을 본다면 TCA라는 외부 프레임워크에서는 상위 상태(뷰모델이라고 이해해도 좋을듯합니다)에서는 하위 상태를 필요에 따라 들고 있기도 합니다.
반대로 하위에서 상위를 들고 있는것은 엄밀히 말하면 피해야될 설계 패턴이긴 합니다.
왜냐면 이 두 뷰모델 사이에는 그렇게 된다면 강결합이 될거고 유지보수가 많이 어려워질거에요 🥲
그래서 지금 어느정도 하신것처럼 하위 VM에서 상위 VM의 일부 데이터 접근이 필요하다면 이닛 시 의존성 주입을 해서 필요한 값들만 넣어주는것이 좋습니다.
즉, 코드 자체가 현재 꼬이지 않고 어떻게든 구현은 될 수 있지만 좋은 설계는 아닐것 같습니다!
그렇기에 너무 개념적인 부분에서 얽매이지 않고 다양하게 바라보셨으면 합니다 👍 (이미 충분히 그렇게 잘하고 계시지만..!)

2. 네이밍
- 요 부분은 제가 코드 리뷰 시 해당 코드 부분에서 코멘트로 메서드 네이밍에 대한 고찰보다 로직적인 의견을 한번 드려봤습니다!
해당 부분 참고해주세요 😉

3. 셀 사이의 간격
- 이건 두가지 방법이 있을것 같습니다.
우선 List를 이용해서 현재 찾아보고 알고 계신것처럼 기본적으로 제공되는 API가 없을거에요.
그렇기에 하나는 ForEach 시 VStack으로 CardView와 Spacer나 Rectangle 등 적절히 배경으로 보일 만한 뷰를 만들어 수직으로 배치하여 color를 입혀 강제적으로 간격이 있는것처럼 보이게 하는 방법일거구요.
두번째로는 List를 사용하지 않고 커스텀하게 ForEach만을 이용해서 만드는 방법입니다.
즉, List 기능이나 스타일 자체를 원하는 입맛대로 커스텀하게 구현하는것입니다 🙋🏻
그렇게된다면 전체적으로는 VStack으로 감싸질거고 최상단에 header 구현 그리고 그 하단부터는 ForEach로 구성이 될때 CardView와 spacing을 적절히 배치하여 이를 구현해낼 수 있을것 같아요.
저는 주로 두번째 방법을 많이 사용합니다!
즉, 기본 API들 중 List 같은 사용도 좋지만 버전마다 아직 스유가 많이 변화하고 있고 안정되지 않은 부분도 있고 또... 아직 없는 기능도 많아서 정말 라이트한 API (Text, Button, H/VStack) 요런 친구들로 최대한 다 커스텀하게 별도 컴포넌트를 만들어 사용하려는 편입니다 🥲
***
### 고민해보면 좋을 부분
- 현재 아래 캡쳐 이미지와 같이 시뮬레이터에서 해당 키보드가 올라왔을때 cancle / done을 누를 수 있는 방법이 없어보입니다ㅠ
사용성적으로 어떻게 개선하면 좋을까요~?
제가 아이패드가 없어 시뮬로 테스트를 하는건데 만약 제가 잘못 테스트한게 있으면 말씀해주세요..!
![Simulator Screenshot - iPad Air (5th generation) - 2023-09-23 at 05 47 43](https://github.com/yagom-academy/ios-project-manager/assets/72292617/84c87168-197a-498e-8743-008ac73a700f)
***
두분 스텝 2-1 다시 한번 고생 많으셨어요!!
정말 SwiftUI 잘쓰시는거에서 놀랐네요ㅎㅎ
사실 요구사항을 전부 만족해서 어프로브 드려도 되지만,
한번 더 마지막 체크하실 부분도 있으실것 같아 Request Changes 드리겠습니다!
언제든 편하게 머지 혹은 재리뷰 요청 해주세요.
좋은 주말 되세요 😀😀😀

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/KanbanViewModel.swift
> +    init(todos: [Task] = [], doings: [Task] = [], dones: [Task] = []) {
인자가 많아질때 적절한 개행을 해주면 좀 더 가독성이 좋을것 같은데 어떻게 생각하시나요~? 🙋🏻

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/KanbanViewModel.swift
> +    }
상태값을 단순히 변화하는 메서드를 하나로 합치는건 어떨까 생각이 듭니다 🤔
추후 이런 state를 변경하는 코드가 많아지면 지금 코드 컨벤션이라면 상태 변화를 위해 각 2쌍의 구현이 생기지 않을까 생각이 들어서요..!

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/KanbanView.swift
> +    @ObservedObject var kanbanViewModel = KanbanViewModel.mock
internal할 필요가 있는지 궁금합니다 🙋🏻

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Utils/CustomAlert.swift
> +struct CustomAlert<Alert: View>: ViewModifier {
LGTM 👍👍👍

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/KanbanView.swift
> +    @ObservedObject var kanbanViewModel = KanbanViewModel.mock
@ObservedObject와 @StateObject는 어떤 차이가 있으며 해당 뷰모델 초기 선언 및 생성 시에는 어떤것이 더 적절할까요~?

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +        VStack {
실제로 VStack spacing을 아무것도 안주게 되면 TextField와 DatePicker 사이 간격이 0이 될까요~!?

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Utils/CustomAlert.swift
> +                .frame(width: 500, height: 600)
아이패드 기기별로 사이즈가 다를텐데 고정적인 frame 대신 기기마다 비율로 가져가는건 어떻게 생각하시나요!?

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +                        .shadow(color: .secondary, radius: 3, x: 2, y: 2)
공통적으로 반복되어 아래에서도 사용되는것 같은데 공통 컴포넌트화 시켜도 좋아보입니다 🙋🏻
아니면 해당 커스텀한 background 모디파이어를 만들어둬도 추후 더 잘 활용될 수 있을것 같아요~!

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +                    let task = taskFormViewModel.returnTask()
returnTask 메서드 네이밍과 흐름이 조금 어색해보이는데요.
이런건 어떨까요?

우선 우리가 하고 싶은것은 제목/날짜/내용 viewModel State를 task로 만들어서 상위 VM의 create를 이용해 생성하는것이라고 생각한다면,

1. TaskFormVM에서 computed property를 활용하여 task 프로퍼티를 생성
2. returnTask 메서드는 제거
3. 해당 TaskFormView에서 kanbanVM.create(task)로 전달

요 부분은 TaskFormVM에서도 간략히 코멘트 남겨둬 보겠습니다!

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormViewModel.swift
> +}
```
final class TaskFormViewModel: ObservableObject {
  @Published var title: String = ""
  @Published var content: String = ""
  @Published var date: Date = Date()
  
  var task: Task {
    Task(title: title, content: content, date: date)
  }
}
```
이렇게 된다면 별도 메서드를 만들 필요 없이 로직이 조금 더 간결해지지 않을까 합니다 🙋🏻

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +                .disabled(taskFormViewModel.title.isEmpty)
이건 그냥 요구사항은 없지만 기획적으로 한번 고민해봐도 좋을것 같아 남겨봅니다!
사용자 입장에서 왜 done 버튼이 뭐때문에 안눌리지?
라고 인식할 수도 있어서 만약 필수 기입 조건이 title이면 조금 더 명확히 사용자가 알 수 있는 장치가 있으면 어떨까 생각이 들어서요..!
개발적으로가 아닌 기획적으로 생각이 든거라 자유롭게 의견 주시면 감사하겠습니다 🙇🏻

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/ColumnView.swift
> +                    Text("\(title)")
title은 이미 String이기에 보간을 해줄 필요가 없어 보입니다 🙋🏻

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/Card/CardView.swift
> +            Text("\(cardViewModel.date)")
문자열 보간을 한번 더 거칠 필요가 없어보입니다 🙋🏻

2023-09-22 21:46 UTC, GREENOVER commented on ProjectManager/ProjectManager.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 16.0;
16으로 변경하여 사용하게된 이유가 궁금합니다 🙋🏻
그때 안전하고 대중적으로 15로 적용해보시는건줄 알았어요..!

2023-09-22 21:46 UTC, GREENOVER commented on README.md
> +# <img src = "https://hackmd.io/_uploads/B1r7f2cya.png" width = "35"> 프로젝트 매니저  <img src = "https://hackmd.io/_uploads/Bkf_435kT.png" width = "30"><img src = "https://hackmd.io/_uploads/rJhCN3qkp.png
크.. 리드미 작성 최고 👍

2023-09-26 01:07 UTC, WhalesJin commented on ProjectManager/ProjectManager/Presentation/Kanban/KanbanViewModel.swift
> +    init(todos: [Task] = [], doings: [Task] = [], dones: [Task] = []) {
fb250987a81f6dd263a890be662ae307dbf0a1bd

알려주신대로 전달인자가 많거나 길어서 가독성을 해치는 부분을 개행해 주었습니다!!!

2023-09-26 01:07 UTC, WhalesJin commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/ColumnView.swift
> +                    Text("\(title)")
fb250987a81f6dd263a890be662ae307dbf0a1bd

오!! 그렇네요!! 전혀 생각하지 못했어요!! 감사합니다 그린 ㅎㅎ

2023-09-26 01:08 UTC, WhalesJin commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/Card/CardView.swift
> +            Text("\(cardViewModel.date)")
fb250987a81f6dd263a890be662ae307dbf0a1bd

알려주신 덕분에 이것도 깔끔히 수정하였습니다!! 😁

2023-09-26 01:08 UTC, WhalesJin commented on README.md
> +# <img src = "https://hackmd.io/_uploads/B1r7f2cya.png" width = "35"> 프로젝트 매니저  <img src = "https://hackmd.io/_uploads/Bkf_435kT.png" width = "30"><img src = "https://hackmd.io/_uploads/rJhCN3qkp.png
리드미까지 봐주시다니 감사합니다 ㅎㅎㅎ🫣

2023-09-26 02:10 UTC, WhalesJin commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +        VStack {
<img width="478" alt="스크린샷 2023-09-26 오전 11 09 52" src="https://github.com/yagom-academy/ios-project-manager/assets/124643545/f1127f7e-73af-4981-9020-a47c3f81a8a3">

preview에서 영역을 확인해보니 간격이 떨어져 있는 것으로 보아
아예 0은 아닌 것 같습니다!!

2023-09-26 02:15 UTC, WhalesJin commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +                .disabled(taskFormViewModel.title.isEmpty)
<img width="370" alt="스크린샷 2023-09-26 오전 11 14 08" src="https://github.com/yagom-academy/ios-project-manager/assets/124643545/80348fef-ae4d-4da1-95b5-a30ad0822f97">

직관적으로 이렇게 `(필수)`라고 적어보았습니다 하핳🫣

2023-09-26 02:22 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/KanbanView.swift
> +    @ObservedObject var kanbanViewModel = KanbanViewModel.mock
전부 private으로 바꾸어주었습니다.

ObservedObject와 StateObject는 전체 뷰를 다시그리냐 바뀌는 부분만 다시 그리냐 차이인것으로 알고있습니다.
ObservedObject를 쓰면 다른 상태도 같이 초기화 되어 부작용을 초래할 수 있을 것 같습니다.
생성 시에는 StateObject로 생성하는 습관을 들여보겠습니다.

2023-09-26 02:24 UTC, WhalesJin commented on ProjectManager/ProjectManager.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 16.0;
그때 그린과의 대화가 계속 맴돌아서 고민을 더 해보았어요!!
특히 SwiftUI는 새로 나온 UI인만큼 쓰는 곳은 minimum target이 높을거라고 하셨던 말씀과
계속 발전함에 따라 변동이 있겠지만 navigation은 새로 업데이트된 stack이 앞으로의 변동이 적을거라는 말씀이요!!

navigationView로 구현해봤으니 navigationStack도 공부해보고 싶었고,
올림에 따른, 그 전에는 쓰지 못했던 `toolbar` 메서드들도 써보고 싶었어요!!
결론적으로 이것저것 다 공부해 볼 수 있어서 좋았습니다 😆

2023-09-26 02:25 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +        VStack {
그럼 의도하시는것이 간격을 아예 없애는거였나요 이렇게 조금이라도 간격이 들어가는걸 의도하셨을까요~?
의도하시는게 간격을 아예 0으로 가져간다면 코드 수정이 필요할것 같아 남겼습니다ㅎㅎ

2023-09-26 02:26 UTC, WhalesJin commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +                    let task = taskFormViewModel.returnTask()
46599e1b8cc54a702fc0f7b66b7e015cfafbc0ed

주신 설명이 너무 좋아서 냅다 적용시켜봤습니다!!!

2023-09-26 02:26 UTC, WhalesJin commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormViewModel.swift
> +}
46599e1b8cc54a702fc0f7b66b7e015cfafbc0ed

와 연산프로퍼티라니...!!
깔끔해서 너무 좋아요 ㅎㅎ 감사합니다 그린!!!

2023-09-26 02:28 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/Utils/CustomAlert.swift
> +                .frame(width: 500, height: 600)
GeometryReader를 통해 전체 뷰 사이즈를 가져오고 적절한 비율로 설정해주었습니다.

2023-09-26 02:29 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/KanbanViewModel.swift
> +    }
setFormOn이라는 메소드로 병합하고 상태를 인자로 받는 방식으로 변경하였습니다.

2023-09-26 02:31 UTC, WhalesJin commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +                        .shadow(color: .secondary, radius: 3, x: 2, y: 2)
두 가지 방법을 다 구현해봤습니다!!
1. 공통 컴포넌트화
```swift
struct TaskFormView: View {
	    ...
    var rectangle: some View {
        Rectangle()
            .fill(.background)
            .shadow(color: .secondary, radius: 3, x: 2, y: 2)
    }
    
    var body: some View {
        VStack {
            TextField("제목을 입력하세요", text: $taskFormViewModel.title)
                .padding(8)
                .background {
                    rectangle
                }
            ...
        }
	    ...
}
```

2. Custom Modifier
```swift
struct ShadowBackground: ViewModifier {
    func body(content: Content) -> some View {
        content
            .padding(8)
            .background {
                Rectangle()
                    .fill(.background)
                    .shadow(color: .secondary, radius: 3, x: 2, y: 2)
            }
    }
}

extension View {
    func shadowBackground() -> some View {
        modifier(ShadowBackground())
    }
}

struct TaskFormView: View {
            ...
    var body: some View {
        VStack {
            TextField("제목을 입력하세요", text: $taskFormViewModel.title)
                .shadowBackground()
            ...
        }
            ...
}
```

Custom Modifier를 이용한 두 번째 방법이 가독성 측면에서 더 마음에 들어서
두번째 방법으로 수정해보았습니다!!!

c98e73e7bb2f72c2c52847ac6de7ed752c403c09

2023-09-26 02:45 UTC, WhalesJin commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +        VStack {
의도는 따로 없었습니다!!
요구사항에 필수로 들어가 있는 조건도 없는 것을 확인했고
간격도 크게 무리가 없을 것 같아서 이대로 진행하려고합니다!!
알려주셔서 감사합니다 그린!!!!😄

2023-09-26 16:44 UTC, agilestarskim commented
# 고민해보면 좋을 부분
 > 현재 아래 캡쳐 이미지와 같이 시뮬레이터에서 해당 키보드가 올라왔을때 cancle / done을 누를 수 있는 방법이 없어보입니다ㅠ
사용성적으로 어떻게 개선하면 좋을까요~?
제가 아이패드가 없어 시뮬로 테스트를 하는건데 만약 제가 잘못 테스트한게 있으면 말씀해주세요..!

테스트할 때 키보드를 안쓰고 자동완성을 쓰는 바람에 키보드 테스트를 못했습니다.
많은 시도와 리팩토링을 거쳐 키보드 문제를 해결하였습니다.


### 1️⃣ 첫 번째 시도
Custom Alert 통채로 ScrollView에 담았었습니다.
하지만 사용자 경험이 좋지 않을 것이라고 판단하여 해당 방법은 포기했습니다.

### 2️⃣ 두 번째 시도
Custom Alert 내부에 ScrollView를 담았습니다.
하지만 ScrollView안에 TextEditor가 들어가는 순간 TextEditor가 스스로 높이를 계산하지 못해서
최소 크기로 줄어들어버렸습니다. 이 문제를 해결하기 위해 전체 크기를 주입받고 적절한 값으로 계산해주었습니다.

```swift
TextEditor(text: $taskFormViewModel.content)
    .frame(height: taskFormViewModel.formHeight * 0.5) // 0.5가 적절한 값인지 아직 의문입니다.😂
    ...  
```

하지만 TextEditor가 Scroll에 의해 너무 많이 올라가서 첫문장이 안보이는 이슈가 발생했습니다.

### 3️⃣ 세 번째 시도

키보드가 올라오면 직접 스크롤을 제어하는 방식으로 시도했습니다.
scroll을 직접 컨트롤하기 위해 `ScrollViewReader`를 사용했습니다.
textEditor에 id를 부여한 후  키보드가 올라오는 것을 감지한 후 textEditor까지 스크롤되게 하였습니다.
하지만 ios16.4 시뮬레이터에서 간헐적으로 textEditor가 예상보다 더 높이 올라가 가리는 이슈가 발생했습니다.
이슈는 원인으로는 키보드에 의해 자동 스크롤되는 것과 저희의 스크롤 제어가 겹치면서 충돌이 발생하는 것으로 보입니다. (확실 x)

### 4️⃣ 마지막 시도

위 이슈를 해결하고자 키보드에 의해 자동으로 스크롤이 되게 하는 것을 막아야겠다고 판단했습니다.
`.ignoresSafeArea(.keyboard, edges: .bottom)`를 이용해 키보드가 올라왔을 때 자동으로 스크롤 되는 것을 막았습니다.
하지만 스크롤 뷰 내부 크기가 커지지 않아 더 이상 스크롤이 되지 않은 이슈가 발생했습니다.
따라서 내부 크기를 키보드만큼 추가하기 위해 키보드 높이만큼 보이지 않는 뷰를 생성했습니다.

```swift
if keyboard.isVisible {
    Spacer(minLength: keyboard.height)
}
```

추가적으로 스크롤 제어시 textEditor가 scrollView 상단에 너무 딱 붙어있는 것이 어색해서 
UnitPoint를 이용해 간격을 추가해주었습니다.

```swift
proxy.scrollTo(textEditor, anchor: UnitPoint(x: 0, y: 0.05))
```
![image](https://github.com/yagom-academy/ios-project-manager/assets/79740398/790784b3-2dad-444b-9f6f-356a4ccc5081)


### 해결한 후 시연 영상입니다.

https://github.com/yagom-academy/ios-project-manager/assets/79740398/27ca0c96-a3be-41fd-a2e1-b00a8c1a1bfa

2023-09-27 00:27 UTC, GREENOVER approved these changes
@WhalesJin @agilestarskim 
두분 스텝 2-1 리팩토링하시면서 기능도 더 추가하시고 아주 고생 많으셨습니다!!
훨씬 보완되고 좋아졌어요ㅎㅎ
간단히? 다음 스텝 2-2에서 같이 고민해볼 수 있는 포인트들 코멘트로 남겼습니다ㅎㅎ
다음 스텝도 화이팅이에요!

아...! 당연히 이미 요구조건은 아주 나이스하게 만족했기에 어프로브 > 머지하겠습니다 👍

2023-09-27 00:27 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/Card/CardViewModel.swift
> +        var states: Set<TaskState> = [.todo, .doing , .done]
칸반보드에서 그럴일은 없겠지만 추후 TaskState가 무수히 많아지면 유지보수가 귀찮지 않을까요!?
TaskState를 CaseIterable 프로토콜을 채택하여 
```
var states: Set<TaskState> = Set(TaskState.allCases)
```
아래와 같이 가져가면 무수히 많아지는 경우가 아니더라도 TaskState 타입의 case가 변화할때 유지보수하지 않아도 되지 않을까 합니다 🙋🏻

2023-09-27 00:27 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/Card/CardViewModel.swift
> +        return stateArray[destinationOrder.rawValue]
혹시 배열 인덱스에 직접 접근할때 찾는 인덱스를 벗어날 경우가 존재하진 않을까요!?
예를들어 쉽게 생각해보면 var states가 현재처럼 되어있을때 TaskState의 케이스가 더 추가되거나 삭제되었을때 혹시 깜빡하고 유지보수를 못한다면 컴파일 타임에서는 에러가 없이 런타임에서 해당 인덱스 접근 시 에러가 날것 같아서요..!

조금 더 안전하게 해당 인덱스 접근 시 체크해서 예외처리도 간단히 넣으면 어떨까요~? 🤔

2023-09-27 00:27 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/Card/CardViewModel.swift
> +    var isOverdued: Bool {
생각해보니 overdue란 뜻이 이미 기한을 지났다는 뜻의 형용사일텐데 과거형처럼 overdued로 표현하는게 조금 어색해보여서요..!
isOverdue로 충분하지 않나 싶습니다 🤔

2023-09-27 00:27 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/KanbanView.swift
> +    @StateObject private var kanbanViewModel: KanbanViewModel
결국 KanbanViewModel도 현재 구조에서는 주입받아서 사용되는것이라면 @ObservedObject가 조금 더 적절하지 않을까 싶습니다 🙋🏻

2023-09-27 00:27 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +    var titleTextField: some View {
한 뷰에서 하위뷰를 나눌때 이렇게 프로퍼티로 빼는것과 구조체로 빼서 구현하는 방법에는 어떤 장/단점이 있을까요!?

2023-09-27 00:27 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +    var titleTextField: some View {
private해도 되지 않을까요~?

2023-09-27 00:27 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +    func contentTextEditor(_ proxy: ScrollViewProxy) -> some View {
현재 코드상에서는 private해도 될것 같아보입니다~! 🙋🏻

2023-09-27 00:27 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +    @ViewBuilder
왜 이럴경우에는 @ViewBuilder를 사용해야하는지 알려주실 수 있을까요~?

2023-09-27 00:27 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Utils/KeyboardManager.swift
> +            }
보통 Combine에서 Cancellable을 사용할때 Set<AnyCancellable>로 저장하여 한번에 이 cancellable을 통해 작업을 관리하는데요.
즉 지금처럼 두개로 별로도 만드는것은 추후 더 생성되면 선언하거나 코드가 더 늘어날 수 있기에 Set으로 관리하는건 어떤가요?

이런식으로 될것 같아요!

```
private var cancellables = Set<AnyCancellable>()

NotificationCenter.default
      .publisher(for: UIWindow.keyboardWillShowNotification)
      .sink { [weak self] notification in
        guard let self = self else { return }
        
        guard let userInfo = notification.userInfo else { return }
        guard let keyboardFrame = userInfo[UIResponder.keyboardFrameEndUserInfoKey] as? CGRect else { return }
        withAnimation {
          self.height = keyboardFrame.height
          self.isVisible = true
        }
      }
      .store(in: &cancellables)
```
요렇게 store을 이용해 많이 사용되니 한번 파악해보셔도 좋을듯 합니다!

2023-09-27 00:27 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Utils/KeyboardManager.swift
> +            }
추가로 현재 init 시 노티피케이션센터에 옵저버를 등록하는데 사실 해당 객체가 해제되면 옵저버를 해제되진 않습니다.
로직이 없어서요..!

그렇기에 현재 사용처럼 갈때 deinit 시 등록된 옵저버를 해제해주는것이 들어가면 더 적절하겠고, 위 예시로 말씀드린것처럼 Cancellable을 Set으로 가져가면 객체가 해제될때 구독이 취소되기에 별도로 옵저버 해제 로직을 추가하지 않아도 됩니다 🙋🏻

2023-09-27 00:27 UTC, merged

2023-09-27 10:21 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/Card/CardViewModel.swift
> +        var states: Set<TaskState> = [.todo, .doing , .done]
좋은 제안 감사합니다.ㅎㅎ 수정했습니다.

2023-09-27 10:22 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/Card/CardViewModel.swift
> +        return stateArray[destinationOrder.rawValue]
subscript를 이용해 인덱스를 벗어날 시 nil을 리턴해주고 싶었지만 

```swift
return stateArray[safe: destinationOrder.rawValue] ??.todo // nil일 경우 default값을 무엇으로 주어야할지..? 
```

아직 default값으로 무엇을 넘겨주어야할지 논의 중입니다.. 에러를 던지기엔 좀 복잡해질 것 같았습니다. 무엇이 좋을까요..?

2023-09-27 10:23 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/Card/CardViewModel.swift
> +    var isOverdued: Bool {
수정하였습니다😉

2023-09-27 10:27 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/KanbanView.swift
> +    @StateObject private var kanbanViewModel: KanbanViewModel
사실 바로 init없이 인스턴스화 하려고 했는데 프리뷰는 moc 객체를 넘겨줘야해서 저런식으로 작성했습니다.
다시 ObservedObject로 수정했습니다!!

2023-09-27 10:30 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +    var titleTextField: some View {
구조체로 빼면 데이터를 다시 전달해야하는 번거로움이 있지만 프로퍼티로 빼면 해당 구조체의 프로퍼티에 바로 접근할 수 있다는 장점이 있습니다. 데이터 바인딩도 간단합니다👍

private으로 변경하였습니다!!

2023-09-27 11:14 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift
> +    @ViewBuilder
ViewBuilder는 클로저 안에서 반환 값으로 여러 개의 뷰를 만드는 것이 가능합니다.
ViewBuilder가 없다면 Stack으로 감싸거나 해야합니다 ( 하나의 뷰로 만들어서 리턴 )

또한 조건부 뷰를 리턴하게 해줍니다. 

(위 두가지를 통해 ViewBuilder를 거치면서 내부적으로 옵셔널 뷰 또는 여러 뷰를 하나의 뷰로 감싸준다고 추측했습니다.)

현재 if 문으로 View가 감싸져있는데 이렇게 되면 타입이 Optional<뷰>가 됩니다. 
`Optional<Spacer>` 

옵셔널 뷰도 some View로 리턴되려면 결국 뷰 형태로 감싸져야합니다. 따라서 ViewBuilder를 통해 하나의 뷰로 감싸기 위해서 ViewBuilder를 붙여야 합니다.

2023-09-27 11:15 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/Utils/KeyboardManager.swift
> +            }
컴바인은 아직 사용법을 익히지 않아서 실수를 했습니다.😇
좀 더 많이 손에 익어야할 것 같습니다 ㅎㅎ

AnyCancellable 배워갑니다🙂

2023-09-27 18:28 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/Card/CardViewModel.swift
> +        return stateArray[destinationOrder.rawValue]
거의 그럴일은 없을거지만 에러처리까지 현재는 번거로워 보이니 디폴트값으로 넘겨도 괜찮을것 같습니다!
선택하기 나름일것 같지만 todo가 제일 무난하지 않을까 싶습니다 🤔