프로젝트 매니저 [STEP 2-2] Minsup, Whales
yagom-academy/ios-project-manager pull request #309
Opened 2023-10-01 11:44 UTC by agilestarskim

안녕하세요 그린<img src = "https://hackmd.io/_uploads/H1pGWNoyp.png" width = "20"> (@GREENOVER)!!!
Minsup<img src = "https://hackmd.io/_uploads/rJhCN3qkp.png" width = "20"> & Whales<img src = "https://hackmd.io/_uploads/Bkf_435kT.png" width = "20">
STEP2-2 PR 올립니다!!!

**STEP 2-2**
    
* 할일을 터치하면 상세내용을 표시합니다. <br>
    * Edit 버튼을 선택하면 수정할 수 있습니다. <br>
* 할일을 길게 터치하여 팝오버 메뉴를 표시합니다. <br>
    * 팝오버에 표시하는 메뉴는 상황에 따라 달라집니다. <br>
        * TODO의 할일 : Move to DOING / Move to DONE <br>
        * DOING의 할일 : Move to TODO / Move to DONE <br>
        * DONE의 할일 : Move to TODO / Move to DOING <br>
    * 본인의 판단에 따라 팝오버는 액션시트로 대체할 수 있습니다. <br>
* 셀을 왼쪽으로 스와이프하여 삭제 메뉴를 표시하고, 끝까지 스와이프하거나 삭제 메뉴를 선택하면 해당 할일을 삭제합니다.

잘 부탁드립니다 🙇🏻‍ 🙇🏻‍♀️

## 🤹🏻 고민했던 점

### 🔹 TaskFormView 재활용
🚨 **문제점** <br>
TaskFormView에서 Create와 Edit을 구현하기 위해 중복된 부분들을 어떻게 처리할까 고민했습니다.

💡 **해결방법** <br>
1️⃣ View의 init에서 분기처리
* view를 init할 때 optinal Task를 사용해, create일 경우 nil, edit일 경우 수정할 task를 주입하여 분기처리를 하였습니다. 단점은 init에 로직이 들어가 복잡해지고 기능이 추가될 때마다 수정할 부분도 많아지고 사용하지 않은 메소드들을 viewModel에 모두 집어넣어야한다는 문제가 있었습니다.

[Optional Task를 이용](https://github.com/WhalesJin/ios-project-manager/blob/f2d72324a03fabdb7f51d02ce3442bcc2aaa28e3/ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift)

2️⃣ Protocol을 이용해 구현하기

Create와 Edit을 관찰해보니 중복되는 부분이 많아서 프로토콜로 기능 정의 후 Create와 Edit의 ViewModel을 각각 따로 만들어서 뷰모델을 주입하는 형식으로 구현해봤습니다. 단점은 기능이 추가될 때마다 각 뷰모델에 똑같은 메소드와 프로퍼티를 억지로 만들어야한다는 단점이 있습니다.

[Protocol 사용](https://github.com/WhalesJin/ios-project-manager/blob/ddea938b958136009b59b3b63a54f7b339904648/ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/TaskFormView.swift)

</br>

### 🔹 Move to 기능 구현하기
기존 코드는 todos, doings, dones를 각각 분리된 배열로 구현되어있어서 한 배열에서 다른 배열로 변경하려면 기존 배열에서 remove하고 다른 배열에서 append 하는 방식으로 진행되어야 했습니다.

```swift
struct Task: Identifiable, Equatable {
    let id = UUID()
    var title: String
    var content: String
    var date: Date
}

final class KanbanViewModel: ObservableObject {
    @Published var todos: [Task]
    @Published var doings: [Task]
    @Published var dones: [Task]
    
    ...
    
    func moveFromTodo(task: Task, to other: String) {
        if other == "DOING" {
            moveToDoingFromTodo(task: task)
        } else {
            moveToDoneFromTodo(task: task)
        }
    }
    
    func moveToDoingFromTodo(task: Task) {
        guard let index = todos.firstIndex(of: task) else { return }
        
        todos.remove(at: index)
        doings.append(task)
    }
    
    func moveToDoneFromTodo(task: Task) {
        guard let index = todos.firstIndex(of: task) else { return }
        
        todos.remove(at: index)
        dones.append(task)
    }
}
```

🚨 **문제점** <br>
- 이렇게 짜게 되면 상태변화에 따른 메서드들의 중복이 늘어나 다른 방법을 고민해보았습니다.

💡 **해결방법** <br>
- 1️⃣ state 속성을 추가해 state를 기준으로 필터링하여 배열을 분리하였습니다.
    이 방법은 실제로 요소를 다른 배열로 이동시키는 것이 아니라 상태만 바꿈으로서 이동하는 것처럼 보이게 할 수 있는 장점이 있습니다.
    하지만 이 과정에서 원본 tasks 배열 순서대로 요소들이 보여지기 때문에 저희가 원하는 순서대로 보여지지 않았습니다.
    따라서 요소의 순서를 어떤 기준으로 보여주어야할지 기획해야했고 결국 date를 기준으로 정렬하여 문제를 해결하였습니다.
    ```swift
    struct Task: Identifiable, Equatable {
        ...
        var state: TaskState
    }

    enum TaskState {
        case todo, doing, done
    }

    final class KanbanViewModel: ObservableObject {
        @Published var tasks: [Task]

        var todos: [Task] {
            return tasks.filter { $0.state == .todo }
        }

        var doings: [Task] {
            return tasks.filter { $0.state == .doing }
        }

        var dones: [Task] {
            return tasks.filter { $0.state == .done }
        }

        init(tasks: [Task] = []) {
            self.tasks = tasks
            self.tasks.sort { $0.date < $1.date }
        }

        ...

        func move(_ task: Task, to state: TaskState) {
            guard let index = tasks.firstIndex(of: task) else { return }
            tasks[index].state = state
        }
    }

    struct CardView: View {
        ...
        var body: some View {
            VStack(alignment: .leading, spacing: 4) { ... }
            .contextMenu {
                switch cardViewModel.task.state {
                case .todo:
                    Button("Move to DOING"){ kanbanViewModel.move(cardViewModel.task, to: .doing) }
                    Button("Move to DONE"){ kanbanViewModel.move(cardViewModel.task, to: .done) }
                case .doing:
                    Button("Move to TODO"){ kanbanViewModel.move(cardViewModel.task, to: .todo) }
                    Button("Move to DONE"){ kanbanViewModel.move(cardViewModel.task, to: .done) }
                case .done:
                    Button("Move to TODO"){ kanbanViewModel.move(cardViewModel.task, to: .todo) }
                    Button("Move to DOING"){ kanbanViewModel.move(cardViewModel.task, to: .doing) }
                }
            }
            ...
        }
    }
    ```
- 2️⃣ move 메서드의 호출부를 유지보수에 용이하게 구현하고 싶어서 아래와 같이 TaskState와 CardViewModel을 수정하였습니다.
    ```swift
    enum TaskState: Int, CaseIterable {
        case todo = 1, doing, done

        var title: String {
            switch self {
            case .todo:
                return "TODO"
            case .doing:
                return "DOING"
            case .done:
                return "DONE"
            }
        }
    }

    final class CardViewModel {
        ...
        var firstDestination: TaskState {
            return destination(of: .first)
        }

        var secondDestination: TaskState {
            return destination(of: .second)
        }

        private func destination(of destinationOrder: DestinationOrder) -> TaskState {
            var states: Set<TaskState> = Set(TaskState.allCases)
            states.remove(task.state)

            let stateArray = Array(states).sorted { $0.rawValue < $1.rawValue }

            return stateArray[safe: destinationOrder.rawValue] ?? .todo
        }

        enum DestinationOrder: Int {
            case first = 0, second
        }    
    }
    ```

</br>

## 🎙️ 조언을 얻고싶은 점

### 🔸 CustomAlert 재활용

현재 CustomAlert을 trigger하는 API가 두 가지 존재합니다.
하나는 (isOn: bool) 방식이고 하나는 (item: T?) 방식입니다.
ViewModifier를 채택하는 객체가 똑같은 내용으로 두 개가 구현되어있는데
하나로 합치는 방법이 있을까요..?

2023-10-01 20:17 UTC, GREENOVER requested changes
@agilestarskim @WhalesJin 
두분 스텝2-2도 너무 고생 많으셨습니다!!
구현 요구사항은 이미 잘 만족하셨고 전체적으로 코드 또한 깔끔하고 좋네요ㅎㅎ
이번 스텝에서는 이미 잘 완성형으로 구현해주셔서 크게 리뷰드리는것은 없고 여러분들의 사용 의도에서 궁금한 부분과 질문에 대한 답으로 간략히 드려봤습니다 🙏🏻
***
### 고민하신 부분에 대한 저의 의견
- CustomAlert 재활용
  - 요 부분 리뷰 코멘트로도 남겨봤지만, 하나의 뷰모디파이어 객체로 재활용하기 위해서 isOn과 item 두 인자를 하나의 객체에서 옵셔널로 받고 분기를 처리하면 될것 같아요! 그 객체를 사용하는 상위인 customAlert 메서드에서는 어떤 타입인지를 구분 지어줄 수 있도록 파라미터 하나 더 추가되면 될것 같습니다ㅎㅎ
  물론 이 외 여러 방법들도 있겠지만 저는 주로 그렇게 사용하곤 합니다!
  혹시 요 부분 하시다가 잘 이해가 안가시거나 막히면 언제든 말씀해주세요 🙏🏻
***
이번 스텝 이미 잘 만족하셔서 바로 머지해도 되지만 customAlert 부분 한번 리팩토링 간단히 해보실것 같아서 우선은 request Changes로 드리겠습니다!
언제든 재리뷰 주시면 최대한 빠르게 확인하겠습니다 😁
이번주도 화이팅입니다..!

2023-10-01 20:17 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/Card/CardViewModel.swift
> +        return stateArray[safe: destinationOrder.rawValue] ?? .todo
LGTM 👍

2023-10-01 20:17 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/ColumnView.swift
> +    var columnInfo: some View {
internal할 필요가 있을까요~? 🙋🏻

2023-10-01 20:17 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/ColumnView.swift
> +                            -$0.width
실제로 어떤 역할을하며 음수로 주어야 하는 이유가 궁금합니다 🙋🏻

2023-10-01 20:17 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/KanbanView.swift
> +                )
고민하셨던것처럼 충분히 합칠 수 있을것 같습니다!
현재 IsOnCustomAlert과 ItemCustomAlert 뷰 모디파이어 구현을 보면 단순히 isOn Bool 프로퍼티를 이용하냐 item을 selectedTask로 받아와 존재하면 이용하냐 차이일것 같은데, 만약 그렇다면 IsOnCustomAlert과 ItemCustomAlert를 합친 뷰 모디파이어를 구성할때 isOn과 item 두 프로퍼티 모두 가져가면서 item이 옵셔널이니 사용하지 않으면 넣어줘도 되고 아니면 View 확장한 메서드인 customAlert에서 enum으로 어떤 얼럿 타입인지 구분받아 사용할 수도 있을것 같습니다 🙋🏻
즉, customAlert은 하나만 합쳐서 사용하되 어떤 얼럿 종류인지는 customAlert 내부와 공통 ItemCustomAlert 뷰 모디파이어(합친 뷰 모디파이어)에서 구현해주면 될것 같아요..!
한번 고민해보시고 감이 안잡히시면 저랑 같이 해보시죠 😀

2023-10-01 20:17 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/Implementaion/TaskCreator.swift
> +final class TaskCreator: TaskFormProtocol {
호출부에서는 ViewModel로 호출하는데 실제 네이밍은 기존 컨벤션과 달리 VM을 붙이지 않고 가신 의도가 궁금합니다~ㅎㅎ

2023-10-01 20:17 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/Interface/TaskFormProtocol.swift
> +protocol TaskFormProtocol: ObservableObject {
프로토콜 활용 너무너무 좋네요! 👍

2023-10-01 20:17 UTC, GREENOVER commented on README.md
> +- 프로젝트 리뷰어: [GREEN <img src = "https://hackmd.io/_uploads/H1pGWNoyp.png" width = "20">](https://github.com/GREENOVER)
ㅋㅋㅋㅋㅋㅋ이미지까지 깨알같이 넣어주셔서 감사합니다!ㅎㅎ
리드미 끝까지 화이팅이에요!

2023-10-03 08:40 UTC, WhalesJin commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/ColumnView.swift
> +                            -$0.width
구분선의 시작점을 지정해주는 `modifier` 입니다.
`-$0.width`로 해줬던 이유는 기본으로 들어가는 간격이 공개되어있지 않아
기기마다 들어가는 간격이 같을지 다를지도 알 수 없는 상황이어서 `width`만큼 앞으로 보내주면 안전하다고 생각했었습니다.

그렇지만 이또한 명확하지 않다는 생각이 들어
`CardView`의 `padding`과 `listRowInsets(.init())`을 이용하여 더 명확하게 처음부터 시작하도록 수정하였습니다.

관련 커밋 : 6d00150603b54c16955a988b1747e81de9199536

2023-10-03 08:40 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/Column/ColumnView.swift
> +    var columnInfo: some View {
https://github.com/yagom-academy/ios-project-manager/pull/309/commits/999f72f5a70508e01a4de44e6575c580f9963e81

수정했습니다.~~

2023-10-03 08:41 UTC, WhalesJin commented on README.md
> +- 프로젝트 리뷰어: [GREEN <img src = "https://hackmd.io/_uploads/H1pGWNoyp.png" width = "20">](https://github.com/GREENOVER)
주신 칭찬 하나하나가 큰 힘이 됩니다
항상 감사드립니다 그린!!!👍🏻🙇🏻‍♀️🙇🏻

2023-10-03 08:42 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/KanbanView.swift
> +                )
https://github.com/yagom-academy/ios-project-manager/pull/309/commits/99694931dfcbff688071714b09558440c3c1eee8

View Extension에 있는 함수 자체는 통합하면 오히여 "함수는 하나의 일만 해야한다"는 원칙에 위배될 것 같아서 나누었고 ViewModifier 객체만 통합하였습니다. 

init에서 기본값을 nil과 false를 주었고 or 연산으로 제어하는 방식으로 통합하였습니다.

2023-10-03 08:54 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/TaskForm/Implementaion/TaskCreator.swift
> +final class TaskCreator: TaskFormProtocol {
https://github.com/yagom-academy/ios-project-manager/pull/309/commits/e56b89be9ae060dac6dcd6f5c445e432bc61cbad

보통 인터페이스와 구현체 네이밍을 할 때
프로토콜의 경우 `~~able`, `~~protocol` 이라고 명명하고
구현체인 경우 `Real~~`, `Default ~~`, `~~tor`, `~~Impl` 이라고 명명하는 것을 많이 보았습니다.

따라서 저희도 관용적인 표현을 사용했는데 ViewModel의 성격을 잘 보여주지 못한 것 같습니다.
ViewModel을 붙이는 것으로 수정하였습니다~~

2023-10-03 09:23 UTC, GREENOVER approved these changes
@agilestarskim @WhalesJin 
고생 많으셨습니다!!
리팩토링으로 더 보완된 코드가 되었네요ㅎㅎ
다음 스텝으로 이제 넘어가보시죠~!
연휴 마무리 잘하시고 이번주도 화이팅입니다😃

2023-10-03 09:23 UTC, merged