프로젝트 매니저 [STEP 2-1] Mary, Dasan
yagom-academy/ios-project-manager pull request #310
Opened 2023-10-02 03:43 UTC by DasanKim

그린🍏(@GREENOVER) 안녕하세요!
드디어 STEP2-1로 인사드립니다!

나름대로 SwiftUI Tutorials도 따라해보고, property wrapper 공식문서 정독은 하였지만 
구현은 처음이라 부족한 점이 많습니다🥹 편하게 조언 부탁드립니다!!🙏 

항상 최고인 그린! 이번에도 잘 부탁드립니다🙇‍♀️💚

## Step2 세부 진행 계획
- [2-1]
    - 각 셀 및 리스트 화면 구현
    - 새로운 할 일 sheet 화면 구현
    - 상세내용 sheet 화면 구현
- [2-2]
    - 새로운 할 일 추가
    - 수정 가능한 상세내용
- [2-3]
    - 팝오버(또는 액션시트) 메뉴 표시
    - 스와이프 삭제

----

## 고민했던 점 🤔
### 1️⃣ List의 Row 구분선 구현
요구사항에 있는 예시처럼 List의 Row 사이의 구분선 UI를 구현하기 위하여 아래와 같은 시도를 하였습니다.
1. List `Separator` 조정
2. List 대신 `Custom한 View`로 UI 구현

🚨 **문제점** <br>
1. List Separator 조정
    - List Separator을 Custom하게 만들어줄 수 있는 API가 있는지 찾아보았으나 SwiftUI에서 제공하는 API를 찾을 수 없었습니다🥲
2. List 대신 Custom한 View로 UI 구현
    - 자유로운 Custom을 위하여 List 대신 Custom한 View를 사용해보려고 했으나 추후에 적용해야할 `Swipe Action`은 List에만 적용되어 List를 사용해야했습니다.

💡 **해결방법** <br>
- List를 사용하되 
    - Row 위/아래에 Custom View인 `HorizontalSpacing`, `HorizontalDivider` 를 추가하고
    ```swift
    // MemoListView.swift
    List {
        Section {
            ForEach(memos) { memo in
                VStack(alignment: .leading, spacing: 2) {
                    HorizontalSpacing()

                    MemoRow(memo: memo)
                        .swipeActions { ... }
                        .padding()

                    HorizontalDivider()
                }
                .listRowSeparator(.hidden)
                ...
            }
            ...
        } header: {
            ListHeader(category: category.description, memoCount: memos.count)
        }
    }
    ```
    - Header 아래에도 `HorizontalDivider` View를 추가해주었습니다.
    ```swift
    // ListHeader.swift
    VStack(spacing: 0) {
        HStack {
            Text(category)
            Image(systemName: "\(memoCount).circle.fill")
            Spacer()
        }
        ...

        HorizontalDivider()
    }
    ```

### 2️⃣ Sheet에서 내용 수정에 따라 움직이는 List Row

🚨 **문제점** <br>
- 띄워진 Sheet에서 Body 내용을 수정에 따라, Row 사이의 간격이 벌어지는 문제가 발생하였습니다.
    <img src="https://github.com/yagom-academy/ios-project-manager/assets/106504779/4b215636-cc37-456e-9dd2-29ad28c697a5" width="500">

💡 **해결방법** <br>
- 이는 HorizontalSpacing의 Rectangle 높이가 정해져있지 않아서 생겼던 문제입니다.
- HorizontalSpacing의 Rectangle 높이를 `.frame(height: 8)` 와 같이 지정해주었더니 문제가 해결되었습니다!
    <img src="https://github.com/yagom-academy/ios-project-manager/assets/106504779/6e6c0c5f-f60a-411a-b14e-3f1be066a369" width="500">

### 3️⃣ 맨 마지막 Row의 메모만 보여지는 오류

🚨 **문제점** <br>
- List의 Row를 선택하면 해당 sheet가 보여져야 했습니다.
- 사용자의 tapGesture에 반응하기위하여 State 속성의 `showDetail` 프로퍼티를 만들고, 해당 값이 `true`일 때 sheet를 띄우도록 하였습니다.
- 하지만 실행해보니, 선택한 Row가 아닌 맨 마지막 Row의 메모만 보여졌습니다.
- <details>
        <summary> 상세 코드 </summary>

    ```swift
    // MemoListView.swift
    ...
    @State private var showDetail: Bool = false

    var body: some View {
        List {
            Section {
                ForEach(memos) { memo in
                    VStack {
                        ...
                    }
                    .onTapGesture {
                        isPresented.toggle()
                    }
                    .sheet(isPresented: $showDetail) {
                        MemoDetail(memo: memo)
                    }
                }
            }
        }
    }
    ```
    </details>

    <img src="https://github.com/yagom-academy/ios-project-manager/assets/106504779/4d1616fb-34aa-4514-bbf1-1e551969d1ad" width="500">

💡 **해결방법** <br>
- 해당 오류는 tapGesture가 인식되었을 때 showDetail이 true로 변경되면서 선택한 메모 뿐만 아니라 모든 메모의 Sheet가 활성화되면서 나타난 문제점으로 파악하였습니다.
- currentMemo 프로퍼티를 생성하여 tapGesture가 인식되었을 때 선택한 Row의 메모를 담고, 해당 메모를 띄우도록 수정하였습니다.

- <details>
        <summary> 상세 코드 </summary>

    ```swift
    // MemoListView.swift
    ...
    @State private var currentMemo: Memo? = nil

    var body: some View {
        List {
            Section {
                ForEach(memos) { memo in
                    VStack {
                        ...
                    }
                    .onTapGesture {
                        currentMemo = memo
                    }
                    .sheet(item: $currentMemo) {
                        MemoDetail(memo: memo)
                    }
                }
            }
        }
    }
    ```
    </details>

    <img src="https://github.com/yagom-academy/ios-project-manager/assets/106504779/4733ef6a-c6c1-4894-a35b-53d20a313221" width="500">

### 4️⃣ List Row의 터치영역

🚨 **문제점** <br>
- List의 Row를 터치하여 detail view를 띄울 때, Content(text) 부분에서만 터치 이벤트가 인식되고 그 외의 빈공간에서는 인식되지 않았습니다.

    <img src="https://github.com/yagom-academy/ios-project-manager/assets/106504779/d9487254-393d-4acf-bcf6-d582dd3aafef" width="500">

💡 **해결방법** <br>
- .contentShape(Rectangle())을 추가해줌으로써 전체 스택을 터치할 수 있도록 수정하였습니다.
    - `contentShape`는 hit testing용 content 모양을 정의합니다.
    - hit testing이란 터치나 드래그 같은 이벤트를 받는 것을 말합니다.
    
    <img src="https://github.com/yagom-academy/ios-project-manager/assets/106504779/075f9dc2-3a98-45fd-accf-6357f4a100b4" width="500">
 
## 🔗 참고링크
- [🍎Apple Docs: SwiftUI Tutorials](https://developer.apple.com/tutorials/swiftui)
- [🍎Apple Docs: Model data](https://developer.apple.com/documentation/swiftui/model-data)
- [🍎Apple Docs: State](https://developer.apple.com/documentation/swiftui/state)
- [🍎Apple Docs: Binding](https://developer.apple.com/documentation/swiftui/binding)
- [🍎Apple Docs: StateObject](https://developer.apple.com/documentation/swiftui/stateobject)
- [🍎Apple Docs: ObservedObject](https://developer.apple.com/documentation/swiftui/observedobject)
- [🍎Apple Docs: ObservableObject](https://developer.apple.com/documentation/combine/observableobject)
- [🍎Apple Docs: EnvironmentObject](https://developer.apple.com/documentation/swiftui/environmentobject)
- [🍎Apple Docs: Property Wrappers](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/properties/#Property-Wrappers)
- [🍎Apple Docs: contentShape](https://developer.apple.com/documentation/swiftui/view/contentshape(_:eofill:))
- [Web: Passing data from a ForEach into a sheet](https://www.reddit.com/r/SwiftUI/comments/pxe739/passing_data_from_a_foreach_into_a_sheet/)
- [Web: SwiftUI ForEach 내부의 Sheet에 대하여](https://www.hohyeonmoon.com/blog/swiftui-sheet-inside-foreach/)

2023-10-03 02:58 UTC, GREENOVER requested changes
@DasanKim @MaryJo-github 
두분 스텝 2-1 고생 많으셨습니다..!!
SwiftUI 처음이라 인고의 시간과... 힘드셨을텐데 아주 잘 해내고 계신것 같아요ㅎㅎ
전체적으로 사용을 어느정도 잘하셔서 VM과 관계 및 조금 더 디벨롭하게 사용할 수 있는 방향으로 리뷰 드렸어요!
***
### 보완되면 좋을 부분
- MemoDetail과 NewMemo는 사실상 거의 중복 코드가 많고 형태가 비슷한 뷰인것 같아요 😲
해당 뷰를 하나로 묶어 코드 재사용성을 높이는 방향으로 리팩토링 되면 좋을것 같습니다ㅎㅎ
- 아래와 같이 각 영역 섹션 타이틀이 현재 TODO / DOING / DONE이 보여져야할텐데 스크롤 시에만 보여지고 기본적으로 위에 숨겨져있는것 같습니다..!
해당 부분 기본적으로 보여질 수 있도록 리팩토링 되면 어떨까요~?
<img width="625" alt="스크린샷 2023-10-03 오전 11 55 56" src="https://github.com/yagom-academy/ios-project-manager/assets/72292617/26b7b958-7387-494f-ba94-e820b23f044f">   

***
스텝 2-1 뷰모델 제외하고 뷰에서만 우선적으로 적용될 수 있는곳 리뷰드려서 한번 천천히 수정해보시면서 조금 더 SwiftUI를 익혀가시면 좋을듯합니다..!
우선 RequestChanges로 드리겠습니다ㅎㅎ
언제든 재리뷰 요청 및 머지 요청을 해주세요!
오늘 마지막 연휴 푹 즐기시고 다시 또 화이팅입니다 👍

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Model/ModelData.swift
> +var memoExample: [Memo] = [
ModelData를 익스텐션해서 static 변수로 stub을 만드는것은 어떤가요~?
현재 해당 프로퍼티는 internal하기에 다른곳에서 호출이 가능하기에 조금 더 캡슐화를 해보는걸 추천드립니다🙋‍♂️

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Utility/ColorSet.swift
> +struct ColorSet {
오오 사용 좋네요! 👍👍
추후엔 컬레 에셋에 직접 넣은것으로 만들어봐도 좋을것 같아요ㅎㅎ

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Memo/Component/HorizontalDivider.swift
> +            .frame(width: nil, height: 1.5)
width를 명시적으로 nil로 주신 이유가 궁금합니다🙋‍♂️

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Memo/Component/ListHeader.swift
> +            HStack {
VStack에서는 spacing을 0으로 주고 HStack에서 spacing을 명시적으로 주지 않은 의도가 궁금해요~!
실제 spacing을 주지 않으면 기본값른 어떻게 되고 실제 간격은 어떻게 될까요..!?🙋‍♂️

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Memo/MemoListView.swift
> +                ForEach(memos) { memo in
ForEach에서 돌려주며 커스텀하게 만든 셀을 보여주는것 같은데 위 감싸는 List와 Section을 사용하신 이유가 궁금합니다🙋‍♂️

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Memo/MemoListView.swift
> +                        currentMemo = memo
추후 뷰모델로 로직을 옮기면 좋을것 같습니다 🙋‍♂️

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Sheet/MemoDetail.swift
> +        modelData.memos.firstIndex(where: { $0.id == memo.id })!
강제언래핑을 지양해보면 어떨까요~?

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Sheet/NewMemo.swift
> +            ZStack {
ZStack과 overlay는 어떤 차이가 있을까요~?

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Sheet/MemoDetail.swift
> +                Color.white
다른곳에서도 이 두 뷰 구성을 합친 뷰가 공통적으로 사용되는데 하나로 통일하면 어떨까요~?
더 나은 방법으로 추천하는건 ZStack을 이용하지 않고 뷰 모디파이어를 직접 만들어 적용될 수 있도록 해보면 더 재사용성이 좋고 코드가 깔끔해질것 같아요..!

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Sheet/Component/DeadlinePicker.swift
> +            .labelsHidden()
라벨을 빈 문자열을 주고 히든을 시키지 않으면 다르게 보일까요~?
만약 동일하게 의도한것처럼 숨겨지게 보인다면 왜 라벨을 꼭 줘야할까요!? 🤔

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Memo/MemoHome.swift
> +                    MemoListView(memos: modelData.doneList, category: .done)
추후 todo / doing / done외 카테고리가 추가되면 추가할 코드가 계속 반복될것 같은데 보일러 플레이트 코드를 한번 줄여보면 어떨까요! 🙋‍♂️

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Utility/ColorSet.swift
> +    enum CustomColor {
internal할 필요가 있을까요~?

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Application/ProjectManagerApp.swift
>              ContentView()
모호한 ContentView 네이밍을 적절히 바꿔보면 어떨까요~?

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Memo/MemoHome.swift
> +    @State private var showDetail: Bool = false
MemoHomeViewModel을 추후 만들어서 뷰의 상태를 관장하는 역할을 하는 친구들도 거기서 관리된다면 더 로직과 뷰 분리가 잘될것 같아요 🙋🏻

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Memo/MemoHome.swift
> +    @EnvironmentObject var modelData: ModelData
internal할 필요가 있는지 궁금합니다 🙋🏻

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Memo/MemoListView.swift
> +    var category: Memo.Category
private하게 가면서 이니셜라이저로 주입받으면 조금 더 안전하지 않을까 생각들어요 🙋🏻

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Sheet/Component/BodyTextField.swift
> +            .padding(EdgeInsets(top: 10, leading: 10, bottom: 10, trailing: 10))
`.padding(.all, 10)`이나 `padding(10)`으로 같은 효과를 더 적은 코드로 줄 수 있습니다 🙋🏻

2023-10-03 02:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Sheet/MemoDetail.swift
> +    var memo: Memo
뷰 단위에서는 private하게 가면서 필요한 생성 주입은 이니셜라이저로 해주는것도 방법입니다 😃

2023-10-03 08:22 UTC, DasanKim commented on ProjectManager/ProjectManager/Model/ModelData.swift
> +var memoExample: [Memo] = [
commit: cd47af8c658052df92d842beaf07f2931790a2f8

말씀대로 ModelData의 익스텐션에 `static private let`으로 캡슐화를 해보았습니다:)

2023-10-03 08:41 UTC, MaryJo-github commented on ProjectManager/ProjectManager/Views/Sheet/MemoDetail.swift
> +                Color.white
commit: 09865ceeb7177aea839bb825b9bd35181e99b862
뷰 모디파이어에 대해 찾아보고 적용해보았습니다!
덕분에 깔끔해진 것 같습니다!! 감사합니다😆

2023-10-03 08:58 UTC, DasanKim commented on ProjectManager/ProjectManager/Views/Sheet/Component/BodyTextField.swift
> +            .padding(EdgeInsets(top: 10, leading: 10, bottom: 10, trailing: 10))
commit: [a095101](https://github.com/yagom-academy/ios-project-manager/pull/310/commits/a09510173c72056f713c3646b049547a6eaf8bad)

우와 코드도 짧아지고 가독성도 좋아지네요! 바로 .padding(10)으로 수정하였습니다😆
감사합니다!

2023-10-03 09:06 UTC, DasanKim commented on ProjectManager/ProjectManager/Application/ProjectManagerApp.swift
>              ContentView()
commit: a09510173c72056f713c3646b049547a6eaf8bad

파일들을 확인해보니
- `ContentView` 네이밍이 모호하다는 점과
- ContentView의 컨테이너 역할을 이미 `MemoHome` View가 하고 있다는 것
을 확인할 수 있었습니다. 

이에 ContentView를 삭제하고 
`WindowGroup` 안에 ContentView()대신 `MemoHome()`을 작성해주었습니다😊

2023-10-03 09:07 UTC, MaryJo-github commented on ProjectManager/ProjectManager/Views/Memo/Component/HorizontalDivider.swift
> +            .frame(width: nil, height: 1.5)
commit: a09510173c72056f713c3646b049547a6eaf8bad

width를 바꿔보면서 테스트해보다가 지우는 것을 깜박한 것 같습니다😹
[공식문서](https://developer.apple.com/documentation/SwiftUI/View/frame(width:height:alignment:))에서 default값이 nil이라는 것도 다시 확인하였습니다!

2023-10-03 09:11 UTC, GREENOVER commented on ProjectManager/ProjectManager/Application/ProjectManagerApp.swift
>              ContentView()
추후 MemoHomeViewModel도 생성될거라면 MemoHomeView의 네이밍이 더 적절하지 않을까요~~?

2023-10-03 09:14 UTC, DasanKim commented on ProjectManager/ProjectManager/Application/ProjectManagerApp.swift
>              ContentView()
와 그린! 정말 그린은 그저 빛... 바로 수정하였습니다💚

2023-10-03 12:08 UTC, DasanKim commented on ProjectManager/ProjectManager/Views/Sheet/Component/DeadlinePicker.swift
> +            .labelsHidden()
테스트 해본 결과 아래와 같이 보였습니다!

|1.  label 값만 줬을 때|
|:--:|
|<img src="https://github.com/yagom-academy/ios-project-manager/assets/106504779/2f929e77-4196-431c-a55a-6e3ab9723b96" width ="300">|
|**2. label에 빈 문자열을 줬을 때**|
|<img src="https://github.com/yagom-academy/ios-project-manager/assets/106504779/b8ad5958-ce8c-4012-8926-e70da0bf0d63" width ="300">|
|**3. labelsHidden()를 적용했을 때**|
|<img src="https://github.com/yagom-academy/ios-project-manager/assets/106504779/a1a223cb-cf29-48cf-9363-4293cd201e85" width ="300">|

1. DatePicker에 label(title)이 들어가면, title과 DatePicker가 각각 leading, trailing으로 정렬되는 것을 확인할 수 있었습니다.
2. label에 빈 문자열이 들어가더라도 label에 값이 있다고 판단하여 이 역시 DatePicker가 trailing으로 정렬되었습니다.

따라서 저희가 원하는 `center` 정렬을 위해서 `.labelsHidden()를` 통해 label를 숨기되,
[SwiftUI에서는 accessibility 등 다른 용도로 레이블을 사용하므로 레이블을 숨기는 경우에도 항상 컨트롤에 대한 레이블을 제공해야 하므로](https://developer.apple.com/documentation/swiftui/view/labelshidden()) 레이블에 값을 넣어줌으로써 `accessibility` 등 다른 용도로도 사용될 수 있도록 하였습니다.

2023-10-03 13:44 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Sheet/Component/DeadlinePicker.swift
> +            .labelsHidden()
크 많이 학습해보셨군요! 아주 나이스합니다👍👍

2023-10-03 14:36 UTC, DasanKim commented on ProjectManager/ProjectManager/Views/Memo/Component/ListHeader.swift
> +            HStack {
#### VStack에서 spacing을 0으로 준 이유 
- VStack에서 spacing을 0으로 준 이유는, 기본적으로 설정되어있는 spacing 값을 없애주기 위해서입니다.
- HStack 뒤에 HorizontalDivider를 간격 없이 붙여주고 싶었기 때문에, HStack와 HorizontalDivider의 간격을 의도적으로 없애주었습니다.
    
#### HStack에는 spacing을 명시적하지 않은 이유
- HStack에는 spacing을 명시적하지 않은 이유는, 명시적으로 주어지지 않았을 때 제공되는 default spacing 값을 그대로 사용하기 위해서입니다. 
- Stack View들의 spacing은 nil을 기본값으로 가지고 있습니다.
   > [인접한 서브뷰 사이의 거리, 스택이 각 서브뷰 쌍에 대해 default 거리를 선택하도록 하려면 nil을 입력합니다.](https://developer.apple.com/documentation/swiftui/hstack/init(alignment:spacing:content:))

#### spacing의 default 값
- SwiftUI 문서에서 spacing default 값이 몇인지 찾지못하였으나, 애플 [AppKit 문서의 spacing](https://developer.apple.com/documentation/appkit/nsstackview/1488945-spacing) 에서 힌트를 얻고 테스트해본 결과 **spacing default** 값이 `8`이라는 것을 알 수 있었습니다.

2023-10-03 14:50 UTC, MaryJo-github commented on ProjectManager/ProjectManager/Views/Sheet/NewMemo.swift
> +            ZStack {
다음과 같이 정리해보았습니다! 🤓

  - [ZStack](https://developer.apple.com/documentation/swiftui/zstack)
      > A view that overlays its subviews, aligning them in both axes. (하위 뷰를 오버레이하여, 양쪽 축에 정렬합니다.)
      - ZStack은 연속되는 각 하위 뷰에 이전 뷰보다 더 높은 z축 값을 할당하므로, 이후 하위 뷰가 이전 뷰의 '위'에 표시됩니다.
      - ZStack의 자식뷰들은 서로에 대해 **independent** 합니다. 그리고 ZStack에 frame을 따로 주지 않은 이상 **크기가 가장 큰 자식뷰를 기준으로** ZStack의 fit이 결정됩니다.
  - [Overlay](https://developer.apple.com/documentation/swiftui/view/overlay(alignment:content:))
      > Layers the views that you specify in front of this view. (이 뷰 앞에 지정한 뷰를 계층화합니다.)
      - overlay는 하나 이상의 뷰를 다른 뷰 앞에 배치할 수 있습니다. 
      - 콘텐츠 클로저에 둘 이상의 뷰를 지정하는 경우 수정자는 클로저의 모든 뷰를 암시적 ZStack으로 수집하여 뒤쪽에서 앞쪽 순서로 가져옵니다.
      - overlay되는 view는 부모뷰에 종속됩니다. 오버레이된 뷰는 **항상** 부모뷰의 위에 위치하고 **부모뷰를 기준으로** fit이 결정됩니다.

2023-10-03 17:12 UTC, MaryJo-github commented on ProjectManager/ProjectManager/Utility/ColorSet.swift
> +    enum CustomColor {
commit: d0e49b8ce915ad2b5a847b4bdffa5b6ebbde52c2

ColorSet 타입내에서만 접근할 수 있도록 private 접근제한자를 붙여주었습니다😆

2023-10-03 17:19 UTC, MaryJo-github commented on ProjectManager/ProjectManager/Views/Memo/MemoListView.swift
> +    var category: Memo.Category
commit: d0e49b8ce915ad2b5a847b4bdffa5b6ebbde52c2

private 접근제한자 붙여주고, 이니셜라이저 생성하였습니다! 감사합니다 그린😁

2023-10-04 00:07 UTC, GREENOVER commented on ProjectManager/ProjectManager/Views/Memo/Component/ListHeader.swift
> +            HStack {
와우...! 정말 딥하게 잘 찾아보셨네요!! 👍👍
결국 nil의 기본값은 시스템에서 결정하기에 플랫폼에 따라 다를 수 있기에 명시적으로 의도한것처럼 명확히 간격을 주려면 0을 주는게 나을거에요ㅎㅎ

2023-10-04 01:34 UTC, DasanKim commented on ProjectManager/ProjectManager/Views/Memo/MemoListView.swift
> +                ForEach(memos) { memo in
- List를 사용한 이유
      - 추후 `swipe action`을 사용하기 위하여 List를 사용하였습니다.
  - List 내에서 Section 사용한 이유
      - Section의 Header를 활용하고자 사용했었습니다.

 요구사항의 UI를 구현하기 위한 방법은 여러가지가 있겠지만 저희는 처음에 listStyle(.grouped)를 사용하여 구현하였습니다. listStyle(.grouped)를 사용하면서 원하는 Header 모양을 얻기 위해 찾았던 방법이 Section의 Header를 활용하는 것이었습니다. 
 하지만 이 방법은 `header가 고정되지도 않고, sticky하지도 않았습니다.`

 이를 수정하기 위해 listStyle도 변경해보고, LazyVStack View의 `PinnedScrollableViews`를 통해 sticky header를 구현하는 방법도 알아보았으나 아래 방법으로 간단(?)하게 해결이 되었습니다😂
   - Section를 삭제하고, `VStack`로 ListHeader와 List를 묶어줌
   - listStyle를 grouped에서 `plain`으로 변경
  ```swift
  VStack(spacing: 0) {
      ListHeader(...)

      List { ... }
      .listStyle(.plain)
  }
  ```

2023-10-04 01:47 UTC, DasanKim commented on ProjectManager/ProjectManager/Views/Sheet/MemoDetail.swift
> +    var memo: Memo
commit: d0e49b8ce915ad2b5a847b4bdffa5b6ebbde52c2

이곳도 private 접근제한자 붙여주고, 이니셜라이저를 생성하였습니다☺️

2023-10-04 01:51 UTC, DasanKim commented on ProjectManager/ProjectManager/Views/Memo/MemoHome.swift
> +    @EnvironmentObject var modelData: ModelData
commit: d0e49b8ce915ad2b5a847b4bdffa5b6ebbde52c2

internal할 필요가 없군요! 
각 뷰에 있던 `@EnvironmentObject` 파라미터에 private 접근제한자를 붙여주었습니다😆

2023-10-04 02:47 UTC, MaryJo-github commented on ProjectManager/ProjectManager/Views/Memo/MemoHome.swift
> +                    MemoListView(memos: modelData.doneList, category: .done)
commit: af80093612faed74341cc47d7602f847a2af5884

추가되는 `category`에 따라 대응할 수 있도록 아래와 같이 수정하였습니다! 
  - ModelData에 category에 따라 메모를 filtering하는 메서드를 추가
  ```swift
  // ModelData.swift
  final class ModelData: ObservableObject {
      @Published var memos: [Memo] = memoExample

      func filterMemo(by category: Memo.Category) -> [Memo] {
          memos.filter { $0.category == category }
      }
  }
  ```
  - Memo.category에 CaseIterable을 채택
  ```swift
  // Memo.swift
   enum Category: CustomStringConvertible, CaseIterable {
      case toDo
      case doing
      case done
       ...
   }
  ```
  - MemoHomeView에서 ForEach문으로 category만큼 MemoListView를 생성
  ```swift
  // MemoHomeView.swift
  ...
  HStack(spacing: 4) {
      ForEach(Memo.Category.allCases, id: \.description) {
          MemoListView(category: $0)
      }
  }
  ...
  ```

2023-10-10 00:47 UTC, merged