프로젝트 매니저 [STEP 3] Minsup
yagom-academy/ios-project-manager pull request #315
Opened 2023-10-05 22:14 UTC by agilestarskim

@GREENOVER 안녕하세요 그린!!
이틀간 밤새서 결국 마무리를 지었습니다. 😇 너무 졸리네요...하하
최대한 복잡하고 얽혀있는 분기처리를 피하기위해 구조적인 부분을 많이 고민했습니다.
감사합니다.!!

## 고민한 점

### Layer

의존 방향을 고려하여 App, Presentation, Domain, Data 레이어를 나누어보았습니다.
의존 방향이 일정하여 코드가 양이 많아지고 복잡해져도 어렵지않게 작업할 수 있었습니다.

![프로젝트매니저3 drawio](https://github.com/yagom-academy/ios-project-manager/assets/79740398/682b35ba-f4ef-4d36-8507-4f3694a1ff5a)

### DIContainer

레이어들이 분리되어있어 조립하는 공간이 필요했습니다.
특히 userRepository를 TaskUserCase와 UserUseCase가 공유해야 했으므로 
인스턴스들을 모두 가지고 있는 객체가 있는 것이 좋다고 판단하여 DIContainer를 만들었습니다.
사용의도와 네이밍이 적절한지는 아직 잘 모르겠습니다. 또한 광범위하게 모든 레이어를 거쳐 의존하는게 맞는지 모르겠습니다.
나름 Single Source of Truth를 구현했다고 생각했는데 더 좋은 방법이 있을까요?

### Manager 레이어 생성

View모델이 너무 비대해졌고 특정 뷰모델이 온 전역에서 사용되고 있어 Presentation Layer 안에서 새로운 Manager Layer를 생성했습니다. 각 매니저들은 해당 UseCases를 가지고 있습니다. 그렇게 됨으로서 뷰모델이 가벼워졌습니다. 매니저들은 온 뷰에서 참조할 수 있도록 Environment를 이용해 Application에서 주입하고 있습니다.

### 네트워크 관찰

`NWPathMonitor`를 이용해 네트워크를 관찰하려고 하는데 시뮬레이터에서는 작동을 안한다는 소식을 들었습니다. 그래서 테스트는 못했습니다. 🥲

### MainActor

Realm 로컬 디비를 사용하고 있는데 이 녀셕은 생성한 스레드와 사용하는 스레드가 다르면 Data race를 방지하기 위해 Crash를 내버립니다. 현재 리모트 디비에서 데이터를 가져올 때 Async를 사용하는데 Task는 처음 실행된 스레드와 await이 끝나고 스레드가 같다고 보장하지 않습니다. 따라서 어쩔 수 없이 연관되어있는Task안에 있던 Realm이 크래시가 계속 일어났습니다.
이 문제를 해결하고자 사용하는 클래스에서 `@MainActor`를 사용하여 MainThread에서 동작하도록 명시함으로서 문제를 해결하였습니다.

Realm을 걷어내고 GRDB를 도입할까 생각해서 실제로 GRDB로 구현하다가 문제를 회피한 것 같은 느낌이 들어 다시 Realm으로 돌아왔습니다. 

MainActor와 Task, Actor 이 부분을 심도있게 공부해봐야겠습니다.

### 기획적인 부분

리모트 디비에 저장하려면 유저를 식별할 정보가 필요했습니다.
어떤 식별자를 사용할 지 고민하다가 직접 아이디를 입력받기로 결정했습니다.
현재 로그인은 요구사항 범위에 없으므로 유효성 검사는 따로 하지 않았습니다.

로컬 디비를 메인으로 하고 리모트 디비를 백업용으로 사용했습니다. (비용과 성능 고려)
로그인하면 해당 아이디의 정보를 통해 리모트 디비에서 가져와 정보를 보여줍니다. 
이 때 로컬 디비가 리모트 디비에서온 정보로 덮어씁니다.

로그아웃 기능을 만들어 하나의 기기에서 여러 아이디를 관리할 수 있게 하였습니다.
계정마다 데이터가 저장되므로 계정을 전환하면 해당 계정의 데이터를 가져올 수 있게 됩니다.

## 실행결과

![Simulator Screen Shot - iPad (10th generation) - 2023-10-06 at 07 05 49](https://github.com/yagom-academy/ios-project-manager/assets/79740398/4a3c021d-ef0e-4ec6-b51b-7a355edd28dc)

![Simulator Screen Shot - iPad (10th generation) - 2023-10-06 at 07 05 55](https://github.com/yagom-academy/ios-project-manager/assets/79740398/9558973a-7619-4e74-a8a3-82d9a0c7f227)

![image](https://github.com/yagom-academy/ios-project-manager/assets/79740398/6a152894-1f24-4054-badb-16278884e905)

## 로그인 시 리모트 저장소에서 데이터 패치

https://github.com/yagom-academy/ios-project-manager/assets/79740398/be3959b8-cf34-4861-84a9-431c30b5937d

2023-10-06 02:06 UTC, GREENOVER requested changes
스텝 3까지 모두 끝내시느라 너무 고생 많으셨습니다!!
특히 로그인까지 간단히 넣어보면서 더 보완되고 차별화된 프로젝트를 만드신것에 감탄했습니다 👍👍👍
전체적으로 구조를 잘 설계하고 관심사가 잘 분리되어 가독성이 좋았고 탄탄하다고 느껴졌어요ㅎㅎ
리뷰는 기간이 기간인만큼 리팩토링 및 완성을 위해서 짜잘한건 쳐내고 잘짜여진 코드 속에서 조금 더 보완되면 좋을것 같은 부분들 위주로 남겨봤습니다!
***
### 칭찬 드리고 싶은 부분
- 정말 구조를 잘 설계하셔서 흐름 파악이 너무 용이하고 명확하네요 💯
- 필수적인 기능뿐 아니라 더 나아가 여러 방면으로 앱을 구현하신것 너무 좋아요 💯
- 코드에 군더더기가 없고 세심한 부분까지 고민한 흔적이 너무 눈에 띕니다 💯
***
### 고민하신 부분에 대한 저의 의견 
- DIContainer
  - 현재 프로젝트 범위와 요구사항에서는 충분히 괜찮은 사용이라고 생각합니다.
  다만 우려하신것처럼 추후에 더 확장이 되고 여러 기능 모듈단으로 나눠질때를 생각하면 모든걸 전역적으로 광범위하게 가져가는것이 독이 될때가 있으니 그럴 경우에 어떻게 하면 좋을까 정도 생각만 가지고 계신다면 충분합니다!
  현재에서도 그렇게 구현할 수 있지만 지금 프로젝트에서는 저는 이 방향이 더 심플하고 맞아보입니다.
  해당 네이밍도 파악이 안되거나 하지 않고 유추가 잘되고 명확하여 다른 네이밍도 있겠지만 지금도 괜찮다고 생각해요!
  추가로, DIContainer와 관련해서 의존성 주입 및 테스팅 관련하여 간단히 코멘트로 리뷰도 남겨봤기에 확인해보시면 좋을듯 합니다ㅎㅎ
- 네트워크 관찰
  - 혹시 어떤게 시뮬레이터상에서 네트워크 단절 등 테스트가 힘드셨을까요~?
  시뮬레이터로는 물론 네트워크 단절 및 재연결 등 다양하게 테스트하는데는 한계는 있지만 단순 단절은 테스트 해볼 수 있는걸로 알아서, 그냥 개인적으로 궁금해져서 여쭤봅니다!ㅋㅋ
***
### 보완되면 좋을 포인트
- GoogleServiceInfo.plist 파일은 gitignore로 관리하는것이 좋을듯해요!
아마 저의 편리한 리뷰를 위해서 남겨두셨을것 같기도하지만ㅎㅎ
레포가 보통 private이 아닌 public일 경우 해당 인포 파일의 API Key가 노출되기도 하기에..?
gitignore가 꼭 필수적이다! 라는건 아니지만 요런 파일들은 왠만하면 노출시키지 않아도 좋을듯 합니다 😀
- 해당 기능의 의도가 궁금한 부분이 있는데요!
  - 계정 로그인되지 않은 상태에서 할일 생성
  - 계정 로그인
  - 로그인되지 않은 상태에서 생성한 할일은 보이지 않음 확인
  - 그러나 History에 해당 계정 로그인전에 생성한 할일들에 대한 기록이 남아있음
요걸 의도하신건지 궁금해서 여쭤봅니다 🙋🏻
***
다시 한번 스텝 3 너무 고생많으셨어요..!
오늘이 플젝 마지막날인걸로 알고 있어서 우선 오늘 보완하실 수 있을 부분도 있을것 같아 Request Changes로 남겨둘께요!
혹시 시간적으로 차후 해보고 싶으시다면 어프로브 > 머지 요청을 해주시면 감사하겠습니다 😀

2023-10-06 02:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Database/Repositories/RealTaskRemoteRepository.swift
> +            print("[\(user.email)] '\(task.title)' 저장에 실패하였습니다. \(error.localizedDescription)")
추후에는 로그 출력에서 더 나아가서 유저에게 다시 시도할 수 있거나 현재 네트워크 사정등 실패했다는 인지를 주어도 좋을것 같아요 🤔

2023-10-06 02:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Database/Repositories/RealTaskRemoteRepository.swift
> +        self.firebase = Firestore.firestore()
현재는 물론 충분하지만 추후에는 테스트도 고려하여 직접 참조하는대신 의존성으로 주입받아 사용한다면 유닛 테스트에서 사용이 편리해질 수 있을것 같습니다 🙋🏻

2023-10-06 02:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Database/Repositories/RealTaskRemoteRepository.swift
> +                                let state = data["state"] as! Int
강제 언래핑으로 사용하신 이유가 궁금합니다 🙋🏻

2023-10-06 02:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Database/Repositories/RealTaskLocalRepository.swift
> +            fatalError("could not load REALM")
파탈에러를 꼭 사용해야 하는지 궁금합니다 🙋🏻

2023-10-06 02:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Database/Repositories/RealTaskLocalRepository.swift
> +        try? realm.write {
에러가 나는 상황에 대한 처리는 필요 없을까요~?

2023-10-06 02:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Database/Repositories/RealUserLocalRepository.swift
> +        try? realm.write {
현재 여러곳에서 try?를 사용하면서 에러들이 무시되고 있는데 에러를 적절히 잘 처리하면 더 보완된 프로젝트가 될것 같아요 🙋🏻

2023-10-06 02:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Database/Repositories/RealUserLocalRepository.swift
> +        try? realm.write {
사용되는곳이 빈번하기에 에러를 공통화시켜 조금 더 손쉽게 작업해도 좋을것 같아요 🤔

2023-10-06 02:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Database/Repositories/RealUserLocalRepository.swift
> +    }()
의존성 주입 방식으로 하는것과 해당 방법으로 하는것은 어떤 장단이 있을까요..!?
또한 파탈에러를 꼭 사용해야한다면 그 이유가 궁금해요 😀

2023-10-06 02:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Domain/Entities/History.swift
> +    init(id: UUID = .init(), title: String, date: Date = .now) {
파라미터 개행 컨벤션 기준이 궁금합니다 🙋🏻

2023-10-06 02:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Application/DIContainer.swift
> +    static let networkManager = NetworkManager()
static의 장점을 잘 사용하셨네요!
그런데 만약 추후에 fake 테스트 등 각 매니저 객체 생성 시 필요한 의존성들이 달라져서 외부에서 주입해야한다면 static 사용이 더 번거로워질 수도 있을것 같다고 느껴졌는데 어떻게 생각하시나요~? 
물론 DIContainer에서 테스트용 static 프로퍼티를 추가해서 사용해도 되지만요..!

2023-10-06 02:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Domain/UseCases/TaskUseCases.swift
> +@MainActor
아래 useCase들 메서드의 모든 경우에서 메인 스레드 실행을 의도한건가요~?
만약 모든 경우에 해당하지 않는다면 필요한 메서드에서 어노테이션을 붙여도 될것 같아보여서요 🤔

2023-10-06 02:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/CloudButtons/ConnectedButton.swift
> +                Button("로그아웃") {
현재 계정 로그인된 상태에서 해당 로그아웃 버튼을 누르면 팝오버은 남아있고 로그아웃 텍스트가 그대로 버튼에 있는것 같습니다 🙋🏻
또한, 다시 열려있는 팝오버에서 로그아웃 버튼을 누르면 동작을 하지 않고 꼭 팝업이 닫히고 클라우드 버튼을 눌러야 다시 계정 로그인이 나타나게 되는데요..!
해당 logout 시 팝업을 닫거나 로그인으로 버튼 레이블을 안내하는등으로 기능 동작을 시켜줘야할것 같아요 🤔

2023-10-06 02:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Register/RegisterView.swift
> +            }
현재 이메일에 빈 String으로 시작할 시 런타임 에러가 나기에 빈공란 시 시작하기 버튼 비활성화 혹은 로직에서 수정되어야할것 같습니다 🙋🏻

2023-10-06 10:21 UTC, agilestarskim commented
> ### 고민하신 부분에 대한 저의 의견

> 네트워크 관찰
혹시 어떤게 시뮬레이터상에서 네트워크 단절 등 테스트가 힘드셨을까요~?
시뮬레이터로는 물론 네트워크 단절 및 재연결 등 다양하게 테스트하는데는 한계는 있지만 단순 단절은 테스트 해볼 수 있는걸로 알아서, 그냥 개인적으로 궁금해져서 여쭤봅니다!ㅋㅋ

시뮬레이터 개발자모드에 네트워크 설정이 없어서 맥 자체 인터넷을 on off 하는 식으로 테스트했습니다.
NWPathMonitor가 네트워크 관찰은 잘하는데 이상하게 값이 바뀌어서 리턴됩니다. 예를들어 와이파이를 끄면 값이 satisfied가 나오고 켜면 unsatisfied가 리턴됩니다. 그래서 개발자 톡방에 여쭤본 결과 이런 답변을 받았습니다.

![스크린샷 2023-10-05 오전 11 20 40](https://github.com/yagom-academy/ios-project-manager/assets/79740398/ef8dee98-c665-4779-a1e6-2e4c79af7f79)

그래서 기능만 구현해두고 테스트는 미뤘습니다. 흑..🥲


> ### 보안되면 좋을 포인트

> 해당 기능의 의도가 궁금한 부분이 있는데요!
계정 로그인되지 않은 상태에서 할일 생성
계정 로그인
로그인되지 않은 상태에서 생성한 할일은 보이지 않음 확인
그러나 History에 해당 계정 로그인전에 생성한 할일들에 대한 기록이 남아있음
요걸 의도하신건지 궁금해서 여쭤봅니다 🙋🏻


정말 기획하는데 많은 고민을했는데 처음 기획은 다음과 같습니다.

`로그인을 하면, 로그인 이전에 로컬에 기록된 데이터를 병합한다.`

이 기획은 여러 계정을 사용하면 모순이 생긴다는 사실을 발견했습니다. 말로 설명하기 복잡한데 간단히말하면 로컬을 비워야하는가 말아야하는가에 대한 고민으로 이어집니다.

1. 로그인을 안한 상태에서 작업을 하다가 새로운 계정으로 로그인을 하면 서버와 로컬을 병합한다.
2. 로그아웃을하고 다른 계정으로 넘어가면 이전 계정과 현재 계정을 분리해야하므로 로컬을 비우고 패치한다.

1번과 2번이 로컬을 비우냐 살리냐 충돌하므로 둘 중 하나는 포기해야겠다고 생각했습니다.
따라서 가장 심플한 방법인 

`로그인을 하면, 이전에 로그인하지 않은 상태에서 작업하던 로컬데이터를 덮어쓴다` 로 결정하였습니다.
즉, 로그인 이전에 기록한 데이터가 사라지는 것을 의도한 것이 맞습니다.
물론 당연히 프로덕트레벨에서는 절대 안되는 기획이지만.. 시간이 없는 관계로 이렇게 하였습니다.😅

히스토리에 기록이 남은 것은 실수입니다. 지우는게 맞는 것 같습니다. 아니면 이 기록도 서버에 기록해서 계정마다 히스토리를 가지고 있는 것도 방법일 수 있을 것 같습니다.

2023-10-06 16:48 UTC, agilestarskim commented on ProjectManager/ProjectManager/Domain/UseCases/TaskUseCases.swift
> +@MainActor
할 일들을 CRUD 할 때는 유저정보가 계속 필요합니다.  현재 로그인되었는가를 판단하는 로직이 필요해서 였는데요,  따라서 TaskUseCases가 UserRepo를 가지고 있습니다. Thread 문제 때문에 MainActor를 붙여주었습니다.

2023-10-06 16:53 UTC, agilestarskim commented on ProjectManager/ProjectManager/Database/Repositories/RealTaskRemoteRepository.swift
> +                                let state = data["state"] as! Int
실수가 맞습니다. 원래는 데이터를 절약하고자 Int8로 했었는데 제대로 동작을 안해서 강제 언래핑을 통해 테스트를 하고 있었습니다. 테스트를 마치고 Int로 해야겠다고 타입을 바꾸어놓고 강제 언래핑은 안 바꾸어놓았네요

2023-10-06 16:57 UTC, agilestarskim commented on ProjectManager/ProjectManager/Database/Repositories/RealTaskLocalRepository.swift
> +            fatalError("could not load REALM")
이 부분이 참 어려운 것 같습니다. 로컬데이터가 동작을 안하면 앱에 큰 영향을 주게되는데 재로드를 하는 방식을 생각해봐야할까요..? 보통 이렇게 큰 영향을 주는 녀석들의 에러는 보통 어떻게 처리하나요?

2023-10-06 17:13 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/CloudButtons/ConnectedButton.swift
> +                Button("로그아웃") {
https://github.com/yagom-academy/ios-project-manager/assets/79740398/b344f1ac-9e15-4b74-a887-0b5ae29f6926

제 환경에서는 잘 되는데 제가 버그 재현을 못 한 것일까요?? UserManager에서 logout 메소드를 호출하면 isRegisterFormOn이 false가 되면서 팝오버가 사라지는 것으로 되어있습니다.

2023-10-06 17:45 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/Register/RegisterView.swift
> +            }
```swift
Button("시작하기"){
    userManager.register()
    taskManager.registerFetch()
}.disabled(userManager.inputEmail.isEmpty)
```

간단한 코드를 추가해 버튼을 막아보려고 했는데 아예 사라져서 보이지 않는 swiftUI 자체 이슈가 있는 듯 합니다.

https://developer.apple.com/forums/thread/728200


![image](https://github.com/yagom-academy/ios-project-manager/assets/79740398/33a5ff37-9574-4ddc-8bce-a69b75448c09)

따라서 Alert 대신 sheet을 사용하여 해결하였습니다. 

![image](https://github.com/yagom-academy/ios-project-manager/assets/79740398/5a0e6c76-671c-4fe4-ba18-19c08a000c8d)


여담이지만 sheet이 ipad에서 이렇게 보이는 지 몰랐습니다. 굳이 힘들게 customAlert를 구현한게 무의미한 걸 깨달았네요..

2023-10-06 17:53 UTC, agilestarskim commented on ProjectManager/ProjectManager/Domain/Entities/History.swift
> +    init(id: UUID = .init(), title: String, date: Date = .now) {
보통 3개 이상이면 내려서 쓰는데 짧아서 눈치를 못챘습니다. 수정하였습니다~~

2023-10-06 17:55 UTC, agilestarskim commented on ProjectManager/ProjectManager/Application/DIContainer.swift
> +    static let networkManager = NetworkManager()
fake 테스트가 무엇일까요..?🥲 좀 어려운 내용인 것 같아서 DM 드리겠습니다!!

2023-10-07 00:35 UTC, GREENOVER commented on ProjectManager/ProjectManager/Database/Repositories/RealTaskLocalRepository.swift
> +            fatalError("could not load REALM")
앱을 재실행하게끔 하는것이 아닌 앱 내에서 최대한 컨트롤 할 수 있게 해봅니다!
로컬에서뿐만 아니라 리모트일때도 동일하겠지만 retry를 시킬 수 있도록 해보는 편이에요.
예를들어, 어떤 앱에서 소셜 로그인 시 해당 네트워크 사정상 로그인이 되지 않을 경우에 내부 SDK에서 60초까지 기다리고 또 retry를 몇번 시키는지 컨트롤하거나 기본으로 구현되어 있는데 이러한 개념을 가져오면 어떨까요?
즉, 계속 무한으로 retry를 시도하게하는것도 사용성에 좋지 않아 적당한 retry를 시도하고 그래도 안되면 재실행해달라는 팝업을 띄워 해당 팝업을 누르면 앱이 종료되고 다시 사용자로 하여금 재실행하게 하면 좋을것 같아서요..!

사용자 입장에서는 아무런 안내없이 앱이 죽어버리는것이 제일 나쁜 경험이라 최대한 피하고자 합니다 저는 🙋🏻

2023-10-07 00:38 UTC, GREENOVER commented on ProjectManager/ProjectManager/Application/DIContainer.swift
> +    static let networkManager = NetworkManager()
아하 제가 도움이 될만한 레퍼런스를 하나 남겨봐드리겠습니다~!
https://blog.pragmatists.com/test-doubles-fakes-mocks-and-stubs-1a7491dfa3da?gi=2cee8a7eb443

2023-10-07 00:48 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/CloudButtons/ConnectedButton.swift
> +                Button("로그아웃") {
음 모종의 이유인지 저는 아래와 같이 버그 재현이 되고 있습니다 🥲
테스트 정보는 iPad Pro (11-inch) 16.4로 진행했습니다.
![Simulator Screen Recording - iPad Pro (11-inch) (4th generation) - 2023-10-07 at 09 41 01](https://github.com/yagom-academy/ios-project-manager/assets/72292617/91cbaa33-0904-4575-8b33-76661bc1bf56)

ConnectedButtonView쪽 코드 같은데요.
말씀하신 isRegisterFormOn은 계정 로그인을 위한 얼럿 팝업인것 같은데 맞을까요?
위 ConnectedButtonView에서 popover를 시켜주는 프로퍼티는 showingPopover로 보이는데 이 showingPopover를 로그아웃을 클릭할때 false 시켜주는 코드가 없어 발생하는것 같다고 추측이되서요!

2023-10-07 00:48 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/CloudButtons/ConnectedButton.swift
> +                Button("로그아웃") {
엇 영상 회전 죄송합니다 😥

2023-10-07 00:56 UTC, GREENOVER commented on ProjectManager/ProjectManager/Presentation/Kanban/Register/RegisterView.swift
> +            }
SwiftUI 자체 컴포넌트는 아직 이슈가 많기에... 저는 가급적 모든것을 기본 컴포넌트 (VStack, Button, Text 등등)만 사용하면서 alert, sheet 등과 같은 제공하는 뷰 모디파이어들은 사용하지 않고 직접 만들어 사용하는걸 선호하긴합니다 ㅠ
아직 스유가 멀었네요ㅎ..

2023-10-07 06:34 UTC, GREENOVER approved these changes
@agilestarskim 
고생 많으셨습니다!!
리팩토링 잘 확인하였고 추가적으로 원래 코멘트에다가 질의하신거나 제 생각들 같이 또 리코멘트로 남겨봤어요ㅎㅎ
요부분 한번 참고해보셔도 좋겠습니다 🙋🏻
기간도 기간이고 이번 스텝의 완성도와 퀄도 좋아 여기서 머지하겠습니다!!
보너스 스텝이나 또 리팩토링해서 리뷰가 필요하면 말씀해주세요~ㅎㅎ
다음주부터 출근이신데 어디서든 잘하실 실력이라 걱정이 안되네요 ☺️
다시 한번 축하드리고 화이팅입니다!!

2023-10-07 06:34 UTC, merged

2023-10-08 16:12 UTC, agilestarskim commented on ProjectManager/ProjectManager/Presentation/Kanban/CloudButtons/ConnectedButton.swift
> +                Button("로그아웃") {
아 생각해보니 그러네요..일단 수정은했습니다. 저는 왜 사라졌던 걸까요..? ㅋㅋㅋㅋㅋㅋ 알 수 없는 세계...