프로젝트관리앱[STEP2] 타코캣
yagom-academy/ios-project-manager pull request #48
Opened 2021-11-02 08:11 UTC by Ldoy

# ProjectManager Step1PR
@jungseungyeo 
안녕하세요 린생🌟 기능구현을 많이 못하고 UI도 신경쓰지 못 했습니다. 하지만 내일까지 붙잡고 있어도 다 못 할 것 같고 현재 구현 방향이 적절한지 불안하기도 하고 궁금하기도 해서 PR 드립니다!! 잘 부탁드립니다 😄😄😄

# 화면
![](https://i.imgur.com/REBK6Ay.gif)

# 고민한 점 
1. input과 output은 무엇일까?
- input은 사용자에 의해 전달되는 값, output은 사용자에게 보여줘야하는 값 또는 관련된 행동으로 생각했습니다. 그래서 사용자가 `+` 버튼 혹은 `List`를 터치했을 때 나오는 View인 `DetailView`에서 입력하는 값을 `input`이라고 생각했고 input의 Date값을 기존의 Date값과 비교하여 outdate인지 아닌지 말해주는 것을 outPut 이라고 생각했습니다. (하지만 output은 타입 정의만 해 두고 사용하 못 했습니다.)

2. 한 주동안 MVVM 패턴으로 구현하면서 느꼈던 MVVM을 사용하는 이유
- input과 output를 통해 테스트가 용이할 것 같다. 
    - EX: 테스트 코드 작성 시 viewModel을 테스트하고 싶을 때 dummy Input을 주면 테스트 가능
- 데이터 전달 흐름을 MVC보다 수월하게 파악할 수 있다. 

3. 터치 이벤트를 담당하는 객체
- 해당 View가 어떤 id를 가지고 있는지 전달 하려면 EventListView 타입 내의 EventView에 추가해야했습니다. 

4. `+` 버튼을 눌렀을 때 새로운 event추가한 후 `Done` 버튼을 누르면 텍스트필드가 가지고 있는 내용으로 update하도록 구현해 보았습니다. 
- create
```swift    
//viewModel
mutating func create(list: Event) {
        self.events.append(list)
}

//model
func create() {
        let newEvent = Event(title: input.titleText,
                             description: input.descriptionText,
                             date: input.dateText,
                             state: input.state,
                             id: input.id)
        self.manager.create(list: newEvent)
    }
```

- update : viewModel이 가지고 있는 input을 통해 event를 업데이트 하도록 했습니다. 
```swift

//model
mutating func update(list: Event) {
        let targetEventIndex = find(list: list)
        self.events[targetEventIndex ?? .zero] = list
}

//viewModel
 func update() {
        let targetEvent = Event(title: self.input.titleText,
                                description: self.input.descriptionText,
                                date: self.input.dateText,
                                state: self.input.state,
                                id: self.input.id)
        self.manager.update(list: targetEvent)
        self.input = Input(titleText: "",
                           descriptionText: "",
                           dateText: Date(),
                           state: .ToDo)
 }
```

5. viewModel역할을 담당하는 객체의 이름을 고민하다가`ProjectEventsManager` 로 명명했는데.. 마음에 들지가 않습니다🤔 조금 더 고민 해 보겠습니다!!!

# 질문
1. 터치 한 후 해당 Event의 세부사항을 보여주도록 하기 위해서 event의 id를 이용해 구분하려했습니다.(기능이 정상적으로 작동되진 않고있습니다)  MVVM의 관점으로 보았을 때 어색하지 않은 흐름인지 궁금합니다. 
 `+` id 로 구분하는 방법외에 다른 방법이 있다면 무엇인지 궁금합니다. 

    ```swift
    struct EventListView: View {
        let state: ListState
        @EnvironmentObject var viewModels: EventsList
        @State var isPresented = false

        var body: some View {
            List {
                ForEach(viewModels.jobs) { event in
                    if event.state == state {
                        EventView(title: event.title,
                                  description: event.description,
                                  date: "\(event.date)")
                            .onTapGesture {
                                isPresented.toggle()
                            }
                            .sheet(isPresented: $isPresented) {
                            } content: {
                                DetailEventView(id: event.id)
                                    .environmentObject(viewModels)
                            }
                    }
                }
            }
        }
    }
    ```
- ![](https://i.imgur.com/PW6KE2a.gif)

2. 지난 번 공유해주신 [링크](https://mildwhale.github.io/2020-04-16-mvvm-with-input-output/)에서 `dependency`라는 개념이 나왔는데 잘 이해가 안되서 우선 `input`과 `output`에 집중해 보았습니다. `dependency`가 무엇인지.. 이것도 포함해서 viewModel(혹은 model)을 구현해야 하는 건지 궁금합니다.

2021-11-05 13:11 UTC, jungseungyeo requested changes
안녕하세요 타코캣. 코드를 보면서 많은 어려움이 보였습니다. 같이 해결 해봐요

1.input과 output은 무엇일까?

> ViewModel에서 input은 이벤트가 들어오는 영역이예요. 작성하신 코드를 보면 Input은 Dependency의 역할을 하고 있어요. 버튼의 이벤트가 혹은 특정 시점에서 이벤트를 넘겨주고 output으로 결과를 전달 하는 형태를 만들어야 해요.

2. 한 주동안 MVVM 패턴으로 구현하면서 느꼈던 MVVM을 사용하는 이유

> MVVM은 테스트의 용이하지만 현재 그게 가능한 구조는 아니죠? 그치만 현재 그 구조를 만드는 것이 어려운 형태가 되고 있는거 같아요. protocol을 활용하면서 해결이 가능 할 거 같아요. 제가 보내준 코드에서 가능할거 같아요. 그치만 현재 이해햐가가 어려울수도 있을거같네요..ㅎㅎ;


4. + 버튼을 눌렀을 때 새로운 event추가한 후 Done 버튼을 누르면 텍스트필드가 가지고 있는 내용으로 update하도록 구현해 보았습니다.

> EventManager객체는 현재 단순히 모델을 만드는 역할만 하고 있어요  이 역할은 ViewModel에서 하면 될 거같아요. 모델을 다른곳에서 생성하다보니 input의 역할이 이상해진거 같아요. 

6. EnvironmentObject에 관하여

> EnvironmentObject는 싱글톤보다는 하나의 객체를 전달하면서 사용하기에 용이 하다고 생각하면 좋을거같아요. 현재 구조도 좋지만 이야기한거 처럼 view 하나당 viewModel 하나로 해보고 그 후에 하나의 viewmodel로 해봐요 ㅎㅎ

> ObservedObject, EnvironmentObject 큰 차이는 없지만 EnvironmentObject는 객체를 외부에서 생성된 것을 주입해주어서 init시점에 초기화가 되지 않아도 동작이 됩니다. ObservedObject는 초기화시점에 안해주면 에러를 나타내고 있어요. 이 차이점을 알고 쓰면 더 좋을거같아요.

**질문**

1. 터치 한 후 해당 Event의 세부사항을 보여주도록 하기 위해서 event의 id를 이용해 구분하려했습니다.(기능이 정상적으로 작동되진 않고있습니다) MVVM의 관점으로 보았을 때 어색하지 않은 흐름인지 궁금합니다.
+ id 로 구분하는 방법외에 다른 방법이 있다면 무엇인지 궁금합니다.

id를 넘겨주고 주입한 viewModel을 하는것보다는 새로운 viewModel을 만들고 거기에 event 모델을 넣어주세요 그러면 좀 더 관리하기도 편할거 같아요.

2.지난 번 공유해주신 링크에서 dependency라는 개념이 나왔는데 잘 이해가 안되서 우선 input과 output에 집중해 보았습니다. dependency가 무엇인지.. 이것도 포함해서 viewModel(혹은 model)을 구현해야 하는 건지 궁금합니다.

> rx의 대한 내용보다는 제가 보내준 블로그 내용으로 참고해주세요 

타코캣 mvvm와 swiftui를 통시해 만들다보니 너무 힘든 내용만 있는거 같아요. 우선 ui를 만드는 것을 최우선으로 하고 다음으로 viewmodel로 관리하는 코드를 작성하게 변경하면 좋을거같아요.

2021-11-08 08:08 UTC, Ldoy commented on ProjectManager/ProjectManager/Model/Model.swift
> +struct EventManager {
넵 MainViewModel을 가지는 방향으로 수정해 보았습니다~!

2021-11-08 08:09 UTC, Ldoy commented on ProjectManager/ProjectManager/Model/ViewModel.swift
> +    var input: Input = Input(titleText: "",
넵!

2021-11-08 08:09 UTC, Ldoy commented on ProjectManager/ProjectManager/View/MainView.swift
> +                VStack {
넵 수정해 보았습니다~!

2021-11-10 14:04 UTC, jungseungyeo approved these changes
타코캣 수정 할 내용이 좀 있긴 하지만 이번 step이 아닌 다음 step을 진행하면서 해도 괜찮을거같아요. 이번 step에서 view와 viewModel을 1대1로 가져가면서 viewModel의 대한 이해도가 좀 생겼을거같아요. 코드를 보면서 input으로 전달하고 output으로 받는 부분이 조금 미흡하여 리뷰에서 남겼습니다. 많은 고민을 하고 작성한거 같아요 고생하셨어요. 

질문 주셨던 viweMdoel을 줄이는 방법은 좋아요. view와 viewModel을 1대1이 꼭 아니기 때문에 이제 1대1 구조에서 생각하신 개선 방향으로 진행 하면 좋을거같아요. 

다음 step에서는 저번에 제가 드렸던 usecase 와 repository 패턴을 활용하여 적용하면 좋을 거 같아요. 완벽하지는 않지만 이 내용이 무엇이고 왜 써야하는지 등을 고민하면서 적용하면 큰 도움이 될 거같아요.

다음 step에서는 ui보다는 내부 로직의 대해서 고민 하는 step인거 같아요. 같이 열심해봐요 :) step2 고생하셨습니다.

2021-11-10 14:05 UTC, merged