프로젝트 관리앱 [Step2] 산체스,예스코치,지스
yagom-academy/ios-project-manager pull request #49
Opened 2021-11-03 08:40 UTC by hrjy6278

@wonhee009 
안녕하세요 ~ 라자냐~ 스텝2 PR을 보내게 되었습니다~ 잘 부탁 드립니다 🤗

## 구현내용
-  스텝2에서는 `Firebase`를 사용하지 않아  `Firebase` 를 사용하지 않는 `Target`을 추가하여 진행하였습니다.
- `MVVM` 디자인패턴을 사용하여 프로젝트를 진행하였습니다.
- Swift UI List를 사용하여 `View`를 구성하였습니다.
- 할일 리스트를 `Enum` 으로 분류하여 관리하게끔 구현하였습니다.
- 하나의 배열에서 `Enum`의 `case`에 따라 `View`에 보여지게끔 구현하였습니다. 
- Body 프로퍼티의 `View` 가 많아지는 경우, 따로 계산프로퍼티를 구현하여 분리하였습니다.
---
## 궁금한점
- MVVM을 구현한다고 했습니다. 😢 `ViewModel`을 만들어 보긴 하였지만  구현한 구조가 적절한지, 아니면 라자냐의 생각은 어떠신지 궁금해요! 가령  저희가 `ViewModel` 을 현재 하나만 사용하고 있습니다. 저희가 줏어들은바로는 `View`마다 `ViewModel`을 가지고 있어야 된다? 라는 말을 들었습니다. 이런 구조를 어떻게 만들어야할지 잘 모르겠습니다.

- 현재 저의 구조가 로컬 저장소와 리모트 저장소를 연결하는 부분이 적절한지 잘 모르겠습니다! (감을 못잡겠습니다)

- `Modal View` 를 현재 하나를 구현하고 Todo add, edit 할때 쓰이고 있습니다. 이 `View` 에 ModalType이라는 변수를 통해 분기처리하고 있습니다.  현재 하나의 View를 통해 두가지 경우를 다 생각하다보니 분기처리가 좀 많습니다. 더 올바른 접근이 있을까요?😢

---
## 해결을 못한점 

- 명세와는 조금 다른 UI가 있습니다.(Cell 간의 간격, popover시에 네모난 버튼부분을 구현하지 못했습니다) 
- List의 Cell을 길게 누르면 popover가 띄워지게 되는데, 동작 후에 계속 `popover View` 가 남아 있는 경우가 있습니다.

2021-11-03 12:18 UTC, wonhee009 requested changes
@hrjy6278 @sanches37 @YesCoach 수고하셨습니다!🎉
몇가지 궁금한 점과 리뷰 남겨두었는데요.
viewModel이 변경될 가능성이 있어서 남겨주신 궁금한점이나 해결하지 못한 점은 이후에 다시 얘기 나눴으면 좋겠습니다!😀

<img width="211" alt="image" src="https://user-images.githubusercontent.com/30456206/140053521-158d0a16-77d7-4905-840b-13acc5780140.png">
현재 폴더 디렉토리 구조가 이러한데요. 어떤 기준으로 순서를 정하셨을까요?🤔

---

투두를 생성하는 모달 datePicker에서 저는 월만 선택할 수 있는데 확인 부탁드려요🙏.

2021-11-03 12:18 UTC, wonhee009 commented on ProjectManager/ProjectManager/View/TodoRowView.swift
> +            return todo.date > Date() ? Color.red : Color.black
이 로직이면 일자가 지나도 검정색일거 같은데요. 확인 부탁드려요.

2021-11-03 12:18 UTC, wonhee009 commented on ProjectManager/ProjectManager/View/TodoRowView.swift
> +            return todo.date > Date() ? Color.red : Color.black
그리고 Date 타입으로 비교를 한다면 시간까지 포함해서 비교가 될텐데 명세상으로는 년월일로만 비교해야할거 같습니다.

2021-11-05 06:39 UTC, sanches37 commented on ProjectManager/ProjectManager/Model/Todo.swift
> +enum SortType: CustomStringConvertible, CaseIterable {
말씀하신대로 SortType 이 어색한 것 같아서 ProjectState 로 네이밍을 변경했습니다. 괜찮을까요? 😀

2021-11-05 06:43 UTC, sanches37 commented on ProjectManager/ProjectManager/Model/Todo.swift
> +struct Todo: Identifiable {
todo, doing, done 을 포괄할 수 있게 Project 타입으로 변경하였습니다 😃

2021-11-05 06:51 UTC, sanches37 commented on ProjectManager/ProjectManager/ViewModel/ToDoListViewModel.swift
> +    @Published private(set) var toDoList: [Todo] = []
감사합니다 `todo` 로 모두 통일 시켰습니다. 😊

2021-11-05 06:54 UTC, sanches37 commented on ProjectManager/ProjectManager/ViewModel/ToDoListViewModel.swift
> +    }
fetchList 가 어색한 것 같아서 filteredList 로 네이밍을 변경했습니다.😁

2021-11-05 07:01 UTC, sanches37 commented on ProjectManager/ProjectManager/ViewModel/ToDoListViewModel.swift
> +    }
말씀하신대로 filter 동작이 여러번 호출 되는 것을 인지하였고, 해결 방안으로 배열을 3개로 사용하는 방법을 고려해봤는데, 코드의 분기가 많이 발생하고 코드가 길어지는 문제가 생겼습니다. 팀원간에 협의한 결과 현재 코드가 괜찮다고 판단되서 그대로 진행해볼까 합니다.
그래도 개선해야할 사항이 있다고 생각하시면 의견 부탁드립니다. 😁

2021-11-05 07:05 UTC, YesCoach commented on ProjectManager/ProjectManager/View/TodoRowView.swift
> +            return todo.date > Date() ? Color.red : Color.black
확인했습니다!! 원래는 시간으로 비교하던 로직에서, Calendar의 compare 메소드를 활용하여 일단위로 비교하도록 수정했습니다.

추가로, 색깔 변경하는 메소드가 (정확히는 상황에 맞는 색상을 반환하는) View에 있었는데, 지금은 Model에서 구현하도록 했는데요. MVVM 패턴에 비추어 보았을때 어디에 있는게 합리적일지 명확하게 알지 못해서 그부분이 많이 궁금합니다!!

2021-11-05 07:06 UTC, sanches37 commented on ProjectManager/ProjectManager/ViewModel/ToDoListViewModel.swift
> +enum Action  {
감사합니다. 이부분도 수정하였습니다 🙂

2021-11-06 07:31 UTC, wonhee009 requested changes

2021-11-06 07:31 UTC, wonhee009 commented on ProjectManager/ProjectManager/Model/Todo.swift
> +//  Todo.swift
주석 포함 파일명도 `Project`로 변경되어야 할거 같습니다!

2021-11-06 07:31 UTC, wonhee009 commented on ProjectManager/ProjectManager/Model/Todo.swift
> +        }
`isOutDated`는 기한이 지난 일자인지 확인하기 위한 프로퍼티인거 같은데요.
Model에 위치한 이유가 있을까요?

2021-11-06 07:31 UTC, wonhee009 commented on ProjectManager/ProjectManager/ViewModel/ProjectListViewModel.swift
> +    }
String 타입을 반환하고 있는데 `todoCount`라는 네이밍은 숫자를 반환할거 같습니다.
`todoCountString`같이 네이밍을 바꿔도 괜찮을거 같고 아니라면 Int형을 반환하고 View에서 String으로 변환하는 것도 괜찮을거 같습니다.

2021-11-06 07:33 UTC, wonhee009 commented on ProjectManager/ProjectManager/ViewModel/ToDoListViewModel.swift
> +    }
코드에 분기가 많이 발생하거나 코드가 길어진다고 나쁜 코드는 아니라고 생각합니다. 
어떤 목적을 가지고 쓰여진 코드인지가 중요하다고 생각합니다.😀
이 부분에 대해서 팀원들끼리 합의가 끝났다면 이대로 진행해도 좋습니다.

2021-11-06 07:34 UTC, wonhee009 commented on ProjectManager/ProjectManager/View/TodoRowView.swift
> +            return todo.date > Date() ? Color.red : Color.black
> 색깔 변경하는 메소드가 (정확히는 상황에 맞는 색상을 반환하는) View에 있었는데, 지금은 Model에서 구현하도록 했는데요.

이 부분이 https://github.com/yagom-academy/ios-project-manager/pull/49#discussion_r744094489 <- 이 부분을 말씀하시는 걸까요?

2021-11-08 05:08 UTC, sanches37 commented on ProjectManager/ProjectManager/Model/Todo.swift
> +//  Todo.swift
주석과 파일명에 남아있던 잘못된 명칭들을 수정했습니다.😀

2021-11-08 05:09 UTC, YesCoach commented on ProjectManager/ProjectManager/View/TodoRowView.swift
> +            return todo.date > Date() ? Color.red : Color.black
네 맞습니다!! viewModel로 다시 리팩토링 진행하려고 하는데 MVVM 패턴에서 각각의 역할에 대해서는 명확히 모르는것 같네요ㅜㅜ

2021-11-08 05:21 UTC, sanches37 commented on ProjectManager/ProjectManager/Model/Todo.swift
> +        }
리뷰주신 것을 생각해보니 비지니스 로직을 모델이 갖고 있는게 맞지 않다고 생각하여 뷰모델로 위치를 옮겼습니다. 😊

2021-11-08 05:25 UTC, sanches37 commented on ProjectManager/ProjectManager/ViewModel/ProjectListViewModel.swift
> +    }
지난 리뷰에서 말씀해주신 3개의 칼럼을 그리기 위해서는 2x3 = 6번 호출되는 문제도 해결하기 위해 todoCount 를 사용하지 않고, ProjectListView 내에서 filteredList 를 상수에 넣고 사용하는 방식으로 수정했습니다. 😃

2021-11-11 02:50 UTC, wonhee009 approved these changes
@hrjy6278 @YesCoach @sanches37 스텝2 수고하셨습니다!🎉
리뷰를 남겨두었는데요. 이 부분은 이후 스텝에서 같이 고민해주셨으면 좋겠습니다!

2021-11-11 02:50 UTC, wonhee009 commented on ProjectManager/ProjectManager/ViewModel/ProjectListViewModel.swift
> +}
해당 Action은 List에서만 일어날거 같은데요.
만약 row에서도 사용자 인터랙션을 받아서 처리해야할 일이 생긴다면 해당 enum에 정의하실 생각이실까요?
그게 아니라면 
```swift
viewModel {
     enum Action { }
}
```
으로 정의해서 각각의 viewModel이 Action을 들고 있는건 어떨까요?

2021-11-11 02:50 UTC, merged