프로젝트 매니저 [STEP2] 수박
yagom-academy/ios-project-manager pull request #50
Opened 2021-11-03 13:28 UTC by soo941226

안녕하세요 쿠마!! @leejun6694 

 아직 미완성된 부분이 있는데 쉽게 해결이 될 것 같지가 않아서 적당히 끊고 PR을 보내게 되었습니다. 실제로 프로젝트를 진행한 시간보단 공부를 하는 데에 더 많은 시간을 보낸 것 같아서, 이런 부분은 좀 더 개선을 했다면 마감을 지킬 수도 있지 않았을까? 하는 아쉬움이 남네요... 한편으로는 이렇게 공부를 했는데도 아직 어렵고 프로젝트 진행이 잘 되지 않았다는 점에서 앞으로 잘 해낼 수 있을까 하는 걱정도 듭니다. 재미는 있는데 낯선 게 너무 많은 거 같아요. 쉽게 쉽게 갔으면 좋겠는데 쉬운 게 하나도 없네요...😅

---

### 고민한 점

1. 프로젝트에서 요구하는 화면을 만들기 위해 많은 고민을 하였고 공부를 하게 되었습니다. 특히 이슈가 있었던 부분은 배경색이나 간격을 주는 부분인데, 이게 내장된 기능들과 매칭시키기에 쉽지 않은 부분이 많았습니다. 그래서 커스텀 modifier를 추가하게 되었는데 그게 backgroundColor와 deleteSwipe입니다.
 backgroundColor의 경우 이에 대한 직접적인 modifier가 존재하지 않아서 꼼수...를 부리게 되었는데요. 사용을 했는덴 편했지만 LLDB로 확인을 해보니 이를 사용한 뷰들은 모두 Background라고 하는 View를 뒤에 깔고 있게 되어서 성능에 이슈가 있지는 않을까 하는 걱정이 들게 되었습니다.
 swipe 기능의 경우 내장된 기능이 2가지가 존재했는데, 첫째로 .onDelete()를 사용하려면 내부에서 IndexSet를 굴리고 있는 List를 사용해야 했습니다. 그런데 List는 프로젝트 요구사항처럼 그리기에는 확장에 너무 닫혀있다고 느껴졌습니다.
 두번째 기능인 swipeActions는 iOS15이상에서 사용이 가능했기에 고민은 했지만 사용할 수는 없다고 판단했습니다
 그래서 적절히 화면을 그리면서 또 적절한 기능을 구현하기 위해서, 화면은 ScrollView와 LazyVStack으로 그리고 Swipe는 기능구현을 하게 되었는데요. 레퍼런스가 있어서 이를 복붙하려다가 제걸로 만들고 싶어서 추가는 따로 하지 않고 걷어내고 네이밍을 다시 해서 사용하게 되었습니다.

2. 특히 data driven과 source of truth에 대해서 공부한 내용을 프로젝트에 잘 녹여내보려고 노력을 하였습니다. 기존의 event driven인 프로젝트들은 양이 많아지긴 하더라도 읽는 건 매우 쉬웠는데, data driven은 저 스스로도 잘 읽히지가 않아서 쓰는 것은 더욱 힘들었던 것 같습니다. 어떤 데이터가 어디서부터 오고, 어떤 뷰에 바인딩 되어서 가공이 되고, 다시 할당이 되는지... 이러한 내용들을 계속 생각을 하면서 프로젝트를 진행했었는데요. 이게 좀 하다 보니까 과부하가 걸려서 머리가 고장나는 거 같더라구요. 그래서 찬바람을 계속 쐬고.. 그러다보니 잠도 깨지고 밤낮이 바뀌고... 아직도 낯설고 어려운 거 같습니다. 이번 PR을 보낸 뒤에 다시 한 번 프로젝트를 돌아보고 더 정리를 할 필요성이 느껴졌습니다

3. MVVM에 대한 내용도 공부를 한 내용을 프로젝트에 잘 녹여보려고 했는데요. 이게 하다 보니까 오히려 MVC의 massive view controller보다 더 massive한 view model이 된 것 같아서 조금 착잡했습니다. 뷰모델도 적절히 내용을 분리를 해야할 것 같았는데, 분리를 하기에는 아직 공부도 부족하고 경험도 부족한 것 같아 어떻게 해야할 지 갈피를 잘 못잡았던 것 같아요.

---

### 궁금한 점
1. 일단 코드가 전체적으로 잘 읽히시고 납득이 되시는지, 이건 아니다 싶은 게 있으신지 궁금합니다... 컨벤션에 대해서는 SwiftLint가 도와줘서 안심이 되는데 네이밍이나 로직에 대해서는 온전히 제 책임이라서 마음이 무겁네요...

2. MVVM
   *  MVVM을 공부하면서, 가장 중요한 것은 ViewModel이라고 생각을 하게 되었는데요. 특히 캠프 초기에 했던 숫자야구게임이나 묵찌빠 게임과 같은 내용이 Model과 View-Model 사이에서 이루어지면서 프로그램이 동작하고, View는 단지 이에 대한 결과로써 화면에 나타나기만 하는 것으로 보았는데 제가 이해한 게 맞을까요?
   * 그렇다고 한다면 묵찌빠게임 같은 경우는 가위바위보와 묵찌빠로 뷰모델을 분리할 수 있었을 것 같은데, 쿠마도 동의할 수 있는 의견인지 궁금합니다...

3. propertyWrapper
   * propertyWrapper인 타입을 읽고 이해하는 것이 굉장히 불편하게 다가왔는데요. MVVM 답게 쓰기 위해서는 인내하고 사용하는 게 맞을까요? 예를 들면 @Publisher에 대해서 한번에 슥슥 읽히지 않고 propertyWrapper를 이해해야 하고, 또 Publisher를 이해해야 @Publisher가 읽히는 게 썩 좋은 문법은 아니지 않을까 하는 생각이 들었습니다...
   * 낯설어서 그런 것일 뿐일까요? 쿠마가 갖고 계시는 propertyWrapper에 대한 의견을 여쭤보고 싶습니다!!

4. View의 body
   * 상위 뷰의 body가 다시 그려지면, 당연히 그 body내에서 그려지고 있는 하위 뷰들의 body도 다시 그려질 줄 알았는데 그러지 않았습니다... 그래서 list까지만 전달하고 있던 viewModel을 listItem까지 전달해서 viewModel이 publish하는 것을 감지하게 했는데요. 뭔가 맞는 것 같기도 하고 아닌 것 같기도 하고 아리송 하더라구요... 동작을 하는 것에 만족을 해야할지 잘 모르겠습니다. 쿠마는 지금의 상태가 괜찮다고 생각되시는지, 혹시 더 좋은 방법이 있을지 궁금합니다..!

5. 뷰에서 모델을 알고 있는 것
   * MemoListItem가 Memo와 연관되어 있고, 이 값들을 이용해서 화면을 그리고 있는데요. 결국엔 뷰가 모델을 알고 있는 것 같아서 조금 꺼림직한 느낌이 들었습니다. 그래서 의존성이라도 낮춰야겠다는 생각에 protocol을 활용해보려는 마음에,

```swift
protocol Memoable {
 associatedtype State: RawRepresentable

 var title: String { get set }
 ...
 var state: State
}
```
   * 위와 같은 타입을 정의하여 사용을 해보려고 했는데, 뷰에서 뷰모델에게 color같은 걸 받기 위해서, 이에 대한 인스턴스를 넘겨줄 인터페이스가 필요했고 메소드를 작성하게 되었는데 여기서 막혀서 진행을 못했었습니다... 혹시 쿠마도 이러한 문제를 겪으셨는지, 혹시 해결할 수 있는 조언을 받을 수 있을지 궁금합니다...

---

항상 감사합니다 쿠마!!

2021-11-04 19:20 UTC, leejun6694 requested changes
안녕하세요 수박~~!
처음 접하는 MVVM 과 SwiftUI 로 고생이 많으셨습니다 👍 
우선, 눈에 띄는 몇가지 부분들에 대해서 리뷰를 드렸습니다. 
질문 주신 내용과 전체적인 구조에 대해서는 저도 고민이 많아지고 생각할 부분들이 많아서, 주말까지 조금 더 살펴보고 같이 논의해도 괜찮을지 양해를 구하려고 합니다.
말씀주신 것처럼 ViewModel 이 비대해지고 있고, 역할이 다른 View 와 1:N 관계가 되고 있는 점에서 비슷한 예제가 있는지도 찾아보겠습니다.
감사합니다 : )

2021-11-04 19:20 UTC, leejun6694 commented on ProjectManager/ProjectManager/ViewModel/MemoViewModel.swift
> +protocol AlertControllerable {
어디에 사용되는 것일까요...?

2021-11-04 19:20 UTC, leejun6694 commented on ProjectManager/ProjectManager/ViewModel/MemoViewModel.swift
> +    @Published private(set) var memoList: [[Memo]] = [[], [], []]
배열 내 배열로 todo, doing, done 을 구분하는 것은 명확하지 못한 부분이 있는 것 같습니다. 사용할 때 위험성도 있어보이네요.
다른 구조를 생각해볼까요?

2021-11-04 19:20 UTC, leejun6694 commented on ProjectManager/ProjectManager/ViewModel/MemoViewModel.swift
> +    @Published private(set) var memoList: [[Memo]] = [[], [], []]
+ 다른 구조가 된다면, Memo 의 State 도 불필요한 부분을 제거할 수 있을 것 같습니다.

2021-11-04 19:34 UTC, soo941226 commented on ProjectManager/ProjectManager/Model/Memo.swift
> +    static func == (lhs: Self, rhs: Self) -> Bool {
저는
type property
type method
instance property
instance method
nested type
와 같은 스타일을 유지하려고 노력하는 편이었는데요.
쿠마의 말씀을 듣고 다시 곰곰히 생각을 해보니 특히 오퍼레이터의 경우에는 우선순위를 낮추어도 괜찮을 것 같아서 nested type 위에 적으려고 하는데 어떻게 생각하시나요?

2021-11-04 19:38 UTC, soo941226 commented on ProjectManager/ProjectManager/Model/Memo.swift
> +        var id: Int {
ForEach라고 하는 뷰가 Identifiable을 채택한 인스턴스를 받으면 id 인자를 생략할 수 있어서, 그리고 그렇게 하고 싶어서 이렇게 작성하게 되었습니다.
그런데 쿠마의 말씀을 듣고 지금 다시 보니 결국 중복되는 값이 하나의 인스턴스에 존재하는 것 같아, 그냥 id에 rawValue를 넘겨주는 게 나을 것 같다는 생각이 들었습니다. 감사합니다~~

2021-11-04 19:39 UTC, soo941226 commented on ProjectManager/ProjectManager/View/Style/UIStyle.swift
> +    static let shadowAmount: CGFloat = 3
반영하였습니다~!! 근데 이유가 궁금합니다!!

2021-11-04 19:46 UTC, soo941226 commented on ProjectManager/ProjectManager/ViewModel/MemoViewModel.swift
> +        if describedTime! < currentTime! {
반영하였습니다~! 프로젝트 요구사항에 강제언랩핑을 사용하지 말라는 게 빠져서 냉큼 사용해보았습니다 😅

2021-11-04 19:48 UTC, soo941226 commented on ProjectManager/ProjectManager/ViewModel/MemoViewModel.swift
> +            let state = Memo.State(rawValue: randomRawValue)!
이 부분은 초기 개발 과정에서만 사용하고 추후 삭제할 코드라서 일단은 내버려두겠습니다..!

2021-11-04 19:50 UTC, soo941226 commented on ProjectManager/ProjectManager/ViewModel/MemoViewModel.swift
> +protocol AlertControllerable {
ViewModel에서 에러가 발생할 경우 delegation pattern을 통해 얼럿을 띄워주려고 했는데요. 
이게 생각을 해보니 이때 AlertControllerable을 채택하는 게 컨테이너 뷰가 될 것 같았고, 그렇게 되면 상태가 아니라 컨테이너 뷰에게 얼럿을 띄우라고 명령을 내리게 될 것 같아서... 버리진 못하고 고민만 하고 있는 상태입니다...

2021-11-04 20:27 UTC, soo941226 commented on ProjectManager/ProjectManager/CoreData/PersistenceController.swift
> +        container.loadPersistentStores { (_, error) in
https://github.com/yagom-academy/ios-project-manager/pull/50/commits/d4b7257aa120af70ffe41d746e1e137efe4cef07
해당 커밋에서 반영하였습니다~! 감사합니다!!

2021-11-05 09:14 UTC, soo941226 commented on ProjectManager/ProjectManager/ViewModel/MemoViewModel.swift
> +    @Published private(set) var memoList: [[Memo]] = [[], [], []]
처음에 구현할 때에는 딕셔너리랑 매트릭스를 고민하다가, 딕셔너리의 경우 항상 옵셔널이 딸려오는 점이 꺼려져서 이렇게 작성을 하게 되었는데요.
다른 방법이 있는지 곰곰히 고민을 해보았는데 이렇다할 생각이 떠오르지 않아서... 조금 더 힌트를 받을 수 있을까요?
일단 명확하지 않은 부분은, State와 연관되어 있다는 점을 표현하기 위해서 로직을
```swift
private(set) var memoList: [[Memo]] = Array(repeating: [], count: Memo.State.allCases.count)
```
이렇게 바꾸기는 했습니다...

2021-11-07 11:27 UTC, leejun6694 commented on ProjectManager/ProjectManager/Model/Memo.swift
> +    static func == (lhs: Self, rhs: Self) -> Bool {
오오 그러셨군요 : ) 수박의 스타일도 좋습니다ㅎㅎ 
저는 property 최상단에 적는걸 선호해서 한번 말씀드려봤습니다~!

2021-11-07 11:28 UTC, leejun6694 commented on ProjectManager/ProjectManager/Model/Memo.swift
> +        var id: Int {
오 SwiftUI 에서 저렇게 사용하는군요.
오히려 제가 스타일에 어긋나는 방식은 아닌가 생각이 드네요 (`\.rawValue` 가 좀 생소해서..)

2021-11-07 11:42 UTC, leejun6694 commented on ProjectManager/ProjectManager/View/Style/UIStyle.swift
> +    static let shadowAmount: CGFloat = 3
아래와 같이 알고 있는데, 정확한 정보는 아닐수도 있습니다ㅎㅎ
예를 들어 `let shadowAmount: CGFloat = 3` 이라고 하면, int형으로 3을 초기화한다음 CGFloat 으로 변환하면서 할당하는 것으로 알고 있습니다.
마이너 성능 이슈지만, 결국 불필요한 동작이 생기는게 아닐까 생각이 드네요 : )

2021-11-07 11:55 UTC, leejun6694 commented on ProjectManager/ProjectManager/ViewModel/MemoViewModel.swift
> +    @Published private(set) var memoList: [[Memo]] = [[], [], []]
CRUD 도 잘 만들어주셔서, dictionary 로 만들어도 옵셔널을 낭비적으로 사용하진 않을 것 같은데 어떠신가요!?

2021-11-07 12:05 UTC, soo941226 commented
안녕하세요 쿠마~ 피드백 주신 내용들을 반영하여 수정하였고, 각각 코멘트를 닿아놓았습니다!

그리고 궁금한 점 5번 같은 경우는 동기 분들과 이야기를 나누면서 해결을 한 거 같습니다. 모델을 바로 아는 것이 아니라 뷰모델을 통해서 알도록 하면서, 뷰모델에서 데이터의 가공이나 상태를 넘겨주어 해결하도록 해결하였습니다~!

2021-11-07 12:13 UTC, leejun6694 commented
안녕하세요 수박 : )

- backgroundColor
요 친구는 View 의 Color 를 바로 지정해줄 수 있지 않나요...? 작성해주신 것처럼 또다른 view 가 하나 더 쌓이는 것은 지양했으면 합니다ㅎㅎ

- swipe 기능
고민하셨던 부분을 레퍼런스가 충족시켜준다면, 사용해도 괜찮지 않을까 생각됩니다 : )

- data driven
맞아요ㅎㅎ 이제까지 공부했던 개념과는 다른 내용이여서 처음에 머리가 많이 복잡하실거에요ㅠㅡㅜ
완벽한 코드가 없듯이, 이 구조의 단점 중에 디버깅이 어려운 점도 있다고 생각됩니다ㅠ

2021-11-07 12:16 UTC, leejun6694 commented on ProjectManager/ProjectManager/ViewModel/MemoListViewModel.swift
> +    private func insert(_ memo: Memo) {
private method 는 위에 주석을 추가해서 구분해주거나 extension 을 따로 두면 더 가독성에 도움이 되지 않을까 생각되네요!

2021-11-07 12:22 UTC, leejun6694 commented
- 코드 가독성
이 부분이 당연히 걱정되시겠지만, 구조를 처음 접하는걸 생각하면 너무나 잘 작성해주신 것 같습니다.
추후에 다른 코드를 참고한다던가, 시야가 넓어지면 오늘의 코드는 못난이가 될 수 있겠지만, 그건 수박이 그만큼 발전하고 계신거니까 걱정 안하셔도 됩니다~!!

- MVVM
네, 작성해주신 것처럼 구분해서 만들 수 있겠네요 : )

- propertyWrapper
이번 MVVM 구조에서 많이 접하게 되셔서 당황스럽겠지만, 저희가 기존에 사용하던 MVC 코드에서도 propertyWrapper 를 만들어서 사용하는 개발자나 팀도 있습니다ㅎㅎ 익숙함의 차이가 있는 이슈라고 생각이 되네요! 점점 괜찮아지실거에요.

- View의 body
해당하는 코드를 알 수 있을까요!?

2021-11-07 12:24 UTC, soo941226 commented on ProjectManager/ProjectManager/Model/Memo.swift
> +    static func == (lhs: Self, rhs: Self) -> Bool {
감사합니다~!!

2021-11-07 12:26 UTC, soo941226 commented on ProjectManager/ProjectManager/View/Style/UIStyle.swift
> +    static let shadowAmount: CGFloat = 3
헉 그런 과정이 또 있군요... 저도 한번 조사를 해보겠습니다~! 좋은 정보 감사합니다~!!!

2021-11-07 12:44 UTC, soo941226 commented on ProjectManager/ProjectManager/ViewModel/MemoViewModel.swift
> +    @Published private(set) var memoList: [[Memo]] = [[], [], []]
한번 도전해보겠습니다!!

2021-11-07 12:58 UTC, soo941226 commented
> * backgroundColor
>   요 친구는 View 의 Color 를 바로 지정해줄 수 있지 않나요...? 작성해주신 것처럼 또다른 view 가 하나 더 쌓이는 것은 지양했으면 합니다ㅎㅎ
> > 이게 제가 질문을 드릴 때 제가 정확히 캐치를 못한 것 같아요..
> > <img width="407" alt="스크린샷 2021-11-07 오후 9 45 07" src="https://user-images.githubusercontent.com/83933153/140645412-ecb36ac1-4418-4960-ba7d-31614ab95368.png">
> > 뷰가 하나 더 쌓이진 않고 오히려 UIKit의 계층구조보다 훨씬 간소화 되는 거 같습니다
> > 그런데 컬러는 처음에 제가 iOS15에서만 바로 줄 수 있는 것 같았는데, .red가 아니라 Color.red처럼 타입을 생략을 안하고 작성하면 바로 줘지네요... backgroudColor가 필요가 없었던 거 같아요😅

> * swipe 기능
>   고민하셨던 부분을 레퍼런스가 충족시켜준다면, 사용해도 괜찮지 않을까 생각됩니다 : )
> > 답변 감사합니다~!😄👍


> * 코드 가독성
>   이 부분이 당연히 걱정되시겠지만, 구조를 처음 접하는걸 생각하면 너무나 잘 작성해주신 것 같습니다.
>   추후에 다른 코드를 참고한다던가, 시야가 넓어지면 오늘의 코드는 못난이가 될 수 있겠지만, 그건 수박이 그만큼 발전하고 계신거니까 걱정 안하셔도 됩니다~!!
> >  칭찬해주셔서 감사합니다😅 말씀을 듣고 보니 안심이 되네요... 지금 코드가 못난이로 보이도록 열심히 노력해보겠습니다~😄

> * MVVM
>   네, 작성해주신 것처럼 구분해서 만들 수 있겠네요 : )
> > 확인 정말 감사합니다~!!

> * propertyWrapper
>   이번 MVVM 구조에서 많이 접하게 되셔서 당황스럽겠지만, 저희가 기존에 사용하던 MVC 코드에서도 propertyWrapper 를 만들어서 사용하는 개발자나 팀도 있습니다ㅎㅎ 익숙함의 차이가 있는 이슈라고 생각이 되네요! 점점 괜찮아지실거에요.
> > 아하... 앱 구조와는 크게 관련이 없는 내용이군요... 답변 감사합니다. 큰 도움이 됐습니다!!👍

> * View의 body
>   해당하는 코드를 알 수 있을까요!?
> > 6d2742b에서는
> > https://github.com/soo941226/ios-project-manager/blob/6d2742b2d5de33e2b6a0e822cdf25233df0666cb/ProjectManager/ProjectManager/View/MemoList.swift
> > https://github.com/soo941226/ios-project-manager/blob/6d2742b2d5de33e2b6a0e822cdf25233df0666cb/ProjectManager/ProjectManager/View/MemoListItem.swift
> > 이렇게 MemoList까지만 뷰모델이 전달되고 있었는데요. viewModel이 갱신되어 list의 body가 다시 그려지면, 하위에 있는 MemoListItem도 다시 그려질 줄 알았는데 그렇지 않더라구요...
> > 그래서 다음 커밋인 d0b6263에서
> > https://github.com/soo941226/ios-project-manager/blob/d0b626321f27103eba9528fffa7970902872ab4f/ProjectManager/ProjectManager/View/MemoListItem.swift
> > 아이템까지도 전달을 해주게 되었습니다...

2021-11-07 12:59 UTC, soo941226 commented on ProjectManager/ProjectManager/ViewModel/MemoListViewModel.swift
> +    private func insert(_ memo: Memo) {
전혀 생각해보지 못했는데 정말 좋은 것 같아요! 바로 반영해보겠습니다!!

2021-11-07 13:12 UTC, soo941226 commented on ProjectManager/ProjectManager/View/Style/UIStyle.swift
> +    static let shadowAmount: CGFloat = 3
<img width="840" alt="스크린샷 2021-11-07 오후 10 10 41" src="https://user-images.githubusercontent.com/83933153/140646320-f0c38468-2c0b-419a-87d3-f2c2a2d10a68.png">

<img width="675" alt="스크린샷 2021-11-07 오후 10 12 13" src="https://user-images.githubusercontent.com/83933153/140646396-4e8859b3-d0f1-48ca-934e-9be551b8ffff.png">

말씀하신 것처럼 내부에서 값을 변환하면서 할당을 하는 것 같아요!! 좋은 정보 정말 감사합니다~!!!

2021-11-08 13:22 UTC, leejun6694 approved these changes
LGTM

2021-11-08 13:22 UTC, merged