프로젝트 관리 앱 [STEP 2] Marco
yagom-academy/ios-project-manager pull request #51
Opened 2021-11-03 14:54 UTC by Keeplo

@YebinKim 

@keeplo

안녕하세요 비비 🤠

주말을 거치며 세부 일정을 지키지 못하고, 기한도 늘려서.. 수요일에 기한을 맞춰보려고 노력해보았습니다 ㅎㅎ;; 
굉장히 늦은 시각이지만 날을 넘기지 않았다며 ㅠㅠ PR을 보내봅니다..
이번 PR 코드 리뷰도 잘 부탁드립니다~!

---
### 동작 시연
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24707229/140078626-c0f88a8a-e62a-4230-ac93-fceb3bc43cc4.gif)

### 궁금한점 🤔
* 기능상세와 다른 부분
최초에 기능상세를 보고 모달뷰의 상태는 show, edit, add 3가지라고 생각했습니다. 
하지만 기능상세를 이해하고 보니 리스트 항목을 tap하면 edit 가능한 상태의 modal이 보여지고 수정을 원하면 Edit 버튼 누르는 형태로 구현을 하는 걸 보았습니다.. 결과적으로 해당 상황에서 Done 버튼을 누르면 Cancel 처럼 수정된 데이터가 반영되지 않는 형태로 구현했는데..
제가 이해한 방향의 구현이 맞는 건지.. Edit-Done -> Cancel-Edit  형태로 버튼의 위치와 용도를 바꾸면 안될지 궁금합니다. 

### 피드백 받고 싶은 부분 😹
* MVVM 동작의 이해 관련.
SwiftUI를 이용하는 과정에서 MVVM 구조를 올바르게 이해하고 적용했는지 피드백을 받고 싶습니다.
View에서 View와 관련되지 않은 동작을 ViewModel에 위임하는 등.. 의식을 해서 변경을 진행해보았는데..
아직 익숙치 않아서 어색합니다..

*  가변 프로퍼티.. (Todo 수정)
요즘 비비가 추천해주신 오브젝트나 객체지향 사실과오해, 엘레강트 오브젝트 등등 OOP 관련 서적을 조금씩 접하며 공부중인데요.
OOP 관점에서는 생성된 인스턴스의 프로퍼티에 직접 접근하는것 뿐만 아니라 가능하면 프로퍼티를 변경하는 것도 지양하는 모습을 배우기도 했습니다. 제 프로젝트에서 model 타입의 인스턴스인 Todo 정보를 수정할때 해당 인스턴스의 프로퍼티의 값을 변경하는 형태의 구현이 되는 것같아서. 현재처럼 구현하게 되었습니다 
```swift
func editTodo(baseTodo todo: Todo, title: String, endDate: Date, detail: String) {
     guard let firstIndex = todos.firstIndex(of: todo) else {
         NSLog("해당 Todo를 찾을 수 없음")
         return
     }
     let editedTodo = Todo(title: title, detail: detail,
                           endDate: endDate.timeIntervalSince1970,
                           completionState: todo.completionState)
     todos[firstIndex] = editedTodo
}
```
ViewModel의 프로퍼티인 배열을 수정하는 점도 동일한 부분으로 볼 수 있는 아이러니한 질문이지만, 이런 상황에서 혹시 어떤 방향을 가지면 좋을지 조언을 부탁드리고 싶습니다.

* Hashable
제가 구현한 방향에서 문제일 수도 있지만 Filtered 된 배열에서 선택된 Todo와 전체 Todos에서 선택된 Todo를 매칭시키는 과정에서 각 인스턴스에 프로퍼티로 id를 가지는 형태보다 인스턴스 자체를 탐색하는 게 로직으로 더 효율적이지 않을까 하는 생각에 현재 형태로 구현해보았습니다. CoreData나 외부저장소를 거치는 데이터 흐름은 고려해보지 않고 하게된 결정인데, 이런 구현 방향도 피드백을 받고 싶습니다.

### 해결하지 못한 부분 🤯
* 기능상세에서 보여지는 UI와 동일하게 만들어보기
   * HStack으로 나열된 List 사이에 배경색상. 
   해당 부분은 어떤 View의 배경 색상으로 봐야할지 잘 모르겠어서 실험을 해보았는데 적용하지 못했습니다.
   이런 디테일도 적용해야겠죠?? ㅠㅠ 
   * popover 적용 -> ActionSheet 적용
   popover로 적용하는 방법이나 몇가지 실험을 통해 원하는 모습은 아니지만 구현해내는데는 성공했습니다.
   하지만 기능상세 같은 형태나 현재 구현된 ActionSheet 같은 모양을 만들어내는데 성공하지 못하고 ActionSheet 적용으로 바꾸어보았습니다. 아직 하드코딩되지 않는 형태 (width 200 height 300 같은 입력)의 frame이나 UI 크기 지정이 익숙치 않은데.. 조언을 부탁드려요 ㅠ
   * NavigationView의 기이한 동작
   최초 구현한 모습에선 NavigationView가 투명한 모습 때문에 처음 문제를 접하게 되었는데 동작하다보니 아래 GIF 처럼
   앞선 두 리스트의 스크롤에서는 NavigationBar가 특별한 변화가 없는데 Done 리스트는 스크롤 하게되면 불투명하게 동작을 해주었습니다.
   관련된 자료를 찾아보아도 잘안나와서.. 현재는 투명한 상태와.. 해당 문제를 해결하지 못했습니다..
   혹시 위 현상에 경험이 있으시다면 조언을 부탁드려도 될까요;;
![ezgif com-video-to-gif-3](https://user-images.githubusercontent.com/24707229/140081201-fa69be0a-7e7b-427f-b643-e5203abeba08.gif)

2021-11-07 20:45 UTC, YebinKim requested changes
말꼬 안녕하세요~
Step2 진행 고생 많으셨습니다! 😆👏
저도 이번에 SwiftUI 를 처음 리뷰해보게 되어 이번 PR은 더 시간을 들여 살펴봤는데요..!!

우선 커밋부터 살펴보자면 **메인 브랜치의 README 파일과 작업 브랜치(step2-4)의 README 파일은 머지 시 충돌이 발생**할 거 같아요 🤔
아마 메인 브랜치에서의 README 업데이트가 잘못 올라간 커밋일 것으로 보이는데요.
이 경우 체리픽으로 커밋을 가져오거나 리베이스로 브랜치를 합침으로써 해결할 수도 있다는 것 알고 넘어가면 좋을 거 같아요~!
그 외의 커밋 단위나 커밋의 내용에 대해서는 특별히 피드백 드릴 부분은 없어보입니다! 😊

그럼 궁금한 점과 피드백 받고 싶다고 작성해주신 부분부터 코멘트 드려볼게요~

---

## 궁금한 점

#### 1. 기능 상세와 다른 부분

오호 저도 이 부분 동작 보면서 어색하다는 생각이 들었는데요 🤔
캠프 디코에도 공유되었다시피 **Edit-Done -> Cancel-Edit(또는 Cancel-Done) 형태로 바꾸어주는 방향**으로 진행을 해보면 좋을 거 같아요~!
예리한 발견이었습니다 🤩



## 피드백 받고 싶은 부분

#### 2. MVVM 동작의 이해 관련

전체적으로 ViewModel이 Model을 가공하는 역할을 수행할 수 있도록 작성을 잘 해주셨네요! 😊👍

저는 MVVM 구조의 핵심이 **데이터 바인딩**과 **View-Model 간의 의존성을 분리**하는 것 그리고 **ViewModel을 재사용**하는 것이라고 생각하는데요.
이 관점에서 생각했을 때 현재 MVVM 구조로서 아쉬운 점을 2가지 꼽아보자면 아래와 같아요.
1. ViewModel 의 데이터에 직접적으로 접근이 가능하고 수정이 가능하다는 점 (TodoViewModel.swift)
2. 뷰에서 ViewModel 외에 Model과 관련한 상태를 가지고 있다는 점 (TodoList.swift)

각각에 관련해서는 `TodoViewModel.swift` 파일과 `TodoList.swift` 파일의 라인별 코멘트에 남겨두었으니 확인 부탁드려요~



#### 3. 객체지향의 관점에서 봤을 때 가변 프로퍼티의 사용을 지양하는 것 관련

모델을 불변타입으로 설정하고자 한 것은 멋진 아이디어라고 생각합니다! 🤩
불변 타입으로 선언함으로써 복사 및 수정에 대한 비용 또한 감소될 수 있겠네요.

ViewModel 내부의 todos 프로퍼티를 가변적으로 사용하게 되었다면 이 프로퍼티 값에 대한 수정은 최대한 제한적으로 이루어질 수 있도록 작성을 해보면 좋을 거 같아요~



#### 4. 모델 타입에 적용한 Hashable 관련

Hashable 프로토콜을 적용함으로써 프로젝트 내에서나 추후 사용할 CoreData 또는 CloudKit 에서는 특별히 문제가 있진 않을 것으로 보입니다!
**Int 타입의 `hashable` 을 구별가능한 키로 사용할 수 있다**고 생각했기 때문인데요.
모델이 명시적으로 구별가능한 키를 가지고 있지 않기 때문에 가독성 면에서는 다소 아쉬운 점이 있긴 하지만,
현재의 구조처럼 `Hashable` 프로토콜을 사용함으로써 Swift 문법을 적극적으로 활용해보는 것 또한 좋다고 생각해요~



## 해결하지 못 한 부분

#### 5. HStack으로 나열된 List 사이에 배경 색상에 관하여

가능하면 요구사항에 맞춰서 콘텐츠를 그려주는게 좋을 거 같아요!
이에 관해 뷰를 그리는 방법은 다양하겠지만.. 저는 List 사이의 배경 색상은 List 를 포함하고 있는 HStack의 색상이라고 생각했어요 🤔

그리고 List 내부의 콘텐츠도 좀 더 기능요구서에 맞게 그려보면 좋을 거 같은데요!
List 사이에 진한 선이 어떤 단위로 나타나는지(콘텐츠의 영역이 어떤 단위로 이루어지는지),
콘텐츠 내부에 그려줄 `TodoRow` 는 얼마나 영역을 차지하는지를 한 번 확인해보면 뷰를 그리는 데 도움이 좀 더 될 거 같아요 😊

UI 구조 파악에 도움이 될 수 있을 거 같은 이미지와 코드를 한 장 첨부해뒀으니 혹시 이미지와 관련해 UI 구조에 대한 감이 잡히지 않는다면 말씀해주세요~!
현재 초록색 영역의 터치에 대해서만 TodoModalView 가 나타나고 있다는 점 또한 사용자의 사용성을 생각해서 터치 영역을 다시 생각해보면 좋을 거 같아요 ☺️

![리스트콘텐츠](https://user-images.githubusercontent.com/38066039/140661218-f14f8b93-402f-4b34-be79-ab7ac23d5c3f.png)


````swift
var body: some View {
        List {
            Section(
                content: {
                    ForEach(filteredTodos, id: \.self) { todo in
                        TodoRow(todo: todo)
                    }
                    .onDelete(perform: self.delete)
                    // MARK: - 새로 추가한 코드 3줄
                    .listRowInsets(EdgeInsets(top: 20, leading: 20, bottom: 0, trailing: 20))
                    .background(Color.green)
                    .listRowBackground(Color.pink)
                    // MARK: 여기까지 -
                },
                header: {
                    HStack {
                        Text(completionState.description)
                            .font(.title)
                            .foregroundColor(.black)
                        ZStack {
                            Image(systemName: "circle.fill")
                                .foregroundColor(.black)
                            Text(filteredTodos.count.description)
                                .foregroundColor(.white)
                        }
                        .font(.title2)
                    }
                }
            )
        }
        .listStyle(.grouped)
    }
````



#### 6. popover 적용의 어려움에 관하여

흠 이 부분 어떤 점이 어려우셨을지 글만 보고는 파악이 잘 되지 않는데요..! 🤔
우선 제가 알기로는 [popover(isPresented:attachmentAnchor:arrowEdge:content:)](https://developer.apple.com/documentation/swiftui/path/popover(ispresented:attachmentanchor:arrowedge:content:)) 를 사용해 뷰를 띄울 때 frame 사이즈를 지정할 수 있고 팝오버뷰 내부에 들어가는 뷰는 버튼을 수직으로 배치한 형태라고 생각했어요~
어떤 점이 어려우셨는지를 좀 더 공유해주시면 저도 더 첨언해볼 수 있도록 할게요 ☺️ 



#### 7. NavigationView의 기이한 동작에 관하여

앗 요거 참 기이하네요 🤔
제가 생각했을 때는 스크롤 동작이 없을 때도 네비게이션바가 보여야 하고, 현재 코드에도 문제가 없어보여요.

그리고 동일한 프로젝트를 동일한 기기로 빌드할 때,
Xcode12 에서 빌드했을 때는 스크롤 동작이 없을 때도 네비게이션바가 잘 나오는데
Xcode13 에서 빌드했을 때는 네비게이션바가 나오지 않고 있어요 😯

![Xcode12](https://user-images.githubusercontent.com/38066039/140661248-55a7556b-b04a-4542-a9b1-546188ae55f0.png)
(Xcode12 에서의 빌드)

![Xcode13](https://user-images.githubusercontent.com/38066039/140661250-ad32eb07-2ba5-47cf-b5ab-db554e7110be.png)
(Xcode13 에서의 빌드)

어쩌면 Xcode 버전 또는 SwiftUI 버전의 문제일 수도 있겠다는 생각이 드는데요.
해당 이슈는 저도 좀 더 찾아보고 다시 공유드릴 수 있도록 할게요!



---

SwiftUI 관련 이슈에 대해 찾아보느라 리뷰 코멘트가 좀 늦어졌어요 😅
(다시 생각해봐도 7번 질문에 대한 동작은 참 기이하네요..🤔)

이번 스텝에서의 핵심 경험을 아래 4가지였는데요!

<img width="294" alt="Step2" src="https://user-images.githubusercontent.com/38066039/140661289-b85fa6b7-95fa-4d9c-8ea8-c0cb7f7596cc.png">

전체적으로 동작이 부드럽고 Word Wrapping 방식 및 스와이프나 Date Picker 구현 또한 잘 되어 있지만 👍👏
**UI를 그리는 부분에 있어서 기능요구서와 다른 부분(popover 동작)이 있어** 수정을 한 번 진행하고 다음 스텝을 이어가면 좋을 거 같아 Request Changes 로 요청 드렸어요 🙏

MVVM 구조와 관련해서는 이번 스텝에서 수정을 진행해도 좋고 다음 스텝에서 구조 개선을 해봐도 좋을 거 같아요~
그 외의 수정사항을 더 반영했으면 하거나 설명이 필요한 코멘트가 있다면 말씀해주세요~ 👀👂

2021-11-11 12:25 UTC, Keeplo commented on ProjectManager/ProjectManager/AppDelegate.swift
> +//@main
말씀해주신 것처럼 프로젝트 시동파일(`@main`) 또한 SwiftUI LifeCycle로 맞추었기 때문에 `AppDelegate.swift` 파일과 `SceneDelegate.swift` 파일은 삭제했습니다.

2021-11-11 12:26 UTC, Keeplo commented on ProjectManager/ProjectManager/LandscapeModifier.swift
> +struct LandscapeModifier: ViewModifier {
말씀해주신 것처럼 프로젝트 시동파일(`@main`) 또한 SwiftUI LifeCycle로 맞추었기 때문에 `AppDelegate.swift` 파일과 `SceneDelegate.swift` 파일은 삭제했습니다.

2021-11-11 12:26 UTC, Keeplo commented on ProjectManager/ProjectManager/View/Todos/TodoRow.swift
> +        .truncationMode(/*@START_MENU_TOKEN@*/.tail/*@END_MENU_TOKEN@*/)
해당 부분은 실수 인것 같습니다 수정했습니다.

2021-11-11 12:26 UTC, Keeplo commented on ProjectManager/ProjectManager/ViewModel/TodoViewModel.swift
> +    @Published var todos: [Todo] = []
viewModel에 프로퍼티인 Model에는 View에서 접근할 수 없도록 접근 수준을 높혀 보았습니다.

2021-11-11 12:27 UTC, Keeplo commented on ProjectManager/ProjectManager/View/TodoModalView.swift
> +    let selectedTodo: Todo?
최초에 아이디어는 사용자의 수정정보를 가진 3가지 데이터와 기존에 수정되기전 
`selectedTodo`를 가지고 수정을 취소하는 경우 수정전 데이터인 selectedTodo를 유지한다는 개념으로 접근했습니다.

구현하고 나서 생각해보니 View에 기존 데이터를 가져오면 자연스럽게 복사된 데이터를 가져오고,
해당 데이터를 업데이터 해줄지, 특별한 동작을 하지 않고 (취소) View를 dismiss 할지, 
결정하면 되겠다는 로직을 생각해내서 

현재는 복사된 데이터 또는 default Todo를 품고 사용자 입력 TextField, DatePicker, TextEditor 와 연동되는 
하나의 프로퍼티만 남기는 형태로 수정했습니다.

2021-11-11 12:27 UTC, Keeplo commented on ProjectManager/ProjectManager/View/TodoModalView.swift
> +                            action: { isPresented.toggle() },
만들땐 중복을 줄인다고 구현하게된 모습인데 가독성이 해칠 수 있다는 점을 확실히 느껴서 좀 더 이해하기 쉽게 메서드로 분리해보았습니다.

2021-11-11 12:27 UTC, Keeplo commented on ProjectManager/ProjectManager/View/Todos/TodoList.swift
> +    var completionState: Todo.Completion
viewModel에서 필터링해주는 연산프로퍼티에 접근해보는 형태로 위치를 변경해보았습니다

2021-11-11 12:27 UTC, Keeplo commented on ProjectManager/ProjectManager/View/Todos/TodoRow.swift
> +        }
동기 캠퍼들의 참조해서 popover의 구현의 이해를 조금 더 할 수 있었습니다. 

하지만 구현이나 난이도가 크게 차이점이 있진 않고, 
ActionSheet에서 제공되는 title을 안내문으로 제공하는 등, 앱의 디자인에도 나쁘지 않은 것 같아서 한번 그대로 진행해보겠습니다.

2021-11-13 13:27 UTC, YebinKim approved these changes
말꼬 안녕하세요~
Step2 수정 진행까지 고생 많으셨습니다 👍
전달 드렸던 UI 이슈들은 말꼬가 잘 파악하고 수정하신 거 같아서 정말 박수를 드리고 싶어요!! 😄👏
MVVM 구조 및 각 프로퍼티들의 프로퍼티 래퍼와 접근제어에도 신경을 많이 써서 작성했음이 보였습니다. 

이번 수정을 통해 Step2 핵심 경험 및 UI 는 충분히 그려졌다고 생각해서 머지 의사 한 번 확인해주시면 바로 머지 진행할게요~
추가로 스크롤뷰 동작과 관련해서는 코멘트를 하나 남겼으니 확인 부탁드려요 😊

2021-11-13 13:27 UTC, YebinKim commented on ProjectManager/ProjectManager/View/TodoList/MainContentView.swift
> +                ScrollView(.horizontal) {
질문주셨던 것 처럼 네비게이션바를 강제로 보여주기 위해 ScrollView를 넣게 되어 셀 스와이프 삭제 동작과 스크롤뷰의 스크롤 동작이 중복되어 아쉬움이 남네요 🤔
Xcode 의 버전을 달리해서 빌드하는 것 또한 해결 방법이겠지만, 이 또한 해결방법일 수 있다고 생각해요 😊
현재 간헐적으로 스크롤이 중복되는 문제가 있으니 스크롤뷰의 스크롤 동작을 막기 위해 스크롤뷰의 onAppear 시점에서 bounces 동작을 막아주면 동작 상의 문제를 해결해볼 수 있을 거 같아요~

2021-11-13 13:27 UTC, YebinKim commented on ProjectManager/ProjectManager/View/TodoList/TodoModalView.swift
> +            .shadow(color: viewPurpose == .show ? .gray : .blue ,radius: 10)
파란색의 쉐도우는 의도한 동작일까요?

2021-11-13 13:51 UTC, Keeplo commented on ProjectManager/ProjectManager/View/TodoList/MainContentView.swift
> +                ScrollView(.horizontal) {
정확하게 확인된점은 아니지만 버그라고 가정 했을 때, 임시적인 조치이지만,
버전을 바꾸는 방향은 swiftUI 최신 버전에 맞춰보고 싶었던 점과 
직접적으로 변경해보았을 때 이전버전과 차이나는 부분이 저의 코드에 너무 많아서 
지금의 조치를 취해보았습니다.

단순히 .disable()로만 접근했다가 말씀해주신 방향처럼 스크롤 동작을 방지하는 방법을 찾다가
[링크](https://stackoverflow.com/questions/57933593/how-to-only-disable-scroll-in-scrollview-but-not-content-view)에서 소개한 방법을 적용해보았습니다.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/24707229/141646172-3c395ccc-8bf1-4c0b-bd1d-7127333201b2.png">
위 프로퍼티는 ScrollView의 옵셔널 프로퍼티로 디폴트는 수직이고,
수직 또는 수평, 수직과 수평 등 선택이 가능한 ScrollView의 특성으로
[수직, 수평] 형태 처럼 [] 의 빈배열은 수직과 수평 모두 동작하지 않음을 의미할 수 있는 형태로 설정이 가능했습니다.

위 링크에서 소개한 방향으로 문제를 해결해보았습니다.

2021-11-13 13:56 UTC, Keeplo commented on ProjectManager/ProjectManager/View/TodoList/TodoModalView.swift
> +            .shadow(color: viewPurpose == .show ? .gray : .blue ,radius: 10)
기능상세에는 없는 동작입니다..

앱의 동작을 보았을 때, 
사용자 입력이 활성화된 상태와 비활성화인 상태가 시각적으로 표시되지 않는 점을 고려해서 개인적으로 추가해보았습니다. 
연습단계인 현재 프로젝트에서 기능을 벗어나는 점이나 조금 더 발전 시켜보려는 독단적인 행동은 조금 생각이 짧았다라는 생각도 드네요..

그런점에서 현업에서 디자인 시안과 조금 다른 방향으로 개발자의 아이디어나 앱성향(iOS HIG)에 조금 더 맞는 아이디어가 있다면 협의가 가능한지 또는 어떤 과정으로 앱을 디자인 하게되는지 궁금하네요 ㅎㅎ;;

2021-11-13 14:01 UTC, YebinKim commented
코멘트 올리자마자 확인하는 말꼬의 속도가 엄청납니다..!! 😵
Step2 는 이대로 머지 진행할게요~!
Step3 도 화이팅입니다! 💪

2021-11-13 14:01 UTC, merged