프로젝트매니저[STEP2] yun
yagom-academy/ios-project-manager pull request #52
Opened 2021-11-04 08:55 UTC by blanche37

2021-11-08 19:20 UTC, YebinKim requested changes
윤 안녕하세요~
Step2 진행까지 고생 많으셨습니다! 😆👏
저도 이번에 SwiftUI 를 처음 리뷰해보게 되어 이번 PR은 더 시간을 들여 살펴봤는데요..!!

우선 커밋부터 살펴보자면 아마 스텝 구현을 모두 완료하신 후 커밋만 나눠서 올리신 것으로 보여요 🤔
작업을 완료한 후 파일 단위로 커밋을 나누게 되면 기능 구현 단위의 히스토리를 확인할 수 없고 빌드가 되지 않는 커밋을 올리거나 작업이 일부 누락될 수 있기 때문에 가능하면 구현을 진행하면서 커밋을 올려주는 게 좋을 거 같아요! 😊

그럼 질문주신 부분에 관해 답변을 드려볼게요!



## 프로젝트를 진행하면서 궁금했던 점

#### 1. MVVM에서 데이터 바인딩을 하는 이유

우선 MVVM 아키텍쳐를 사용하는 이유는 각 구현 단위의 의존성을 줄임으로써 확장성을 늘리고 테스트를 원할하게 하기 위함이라고 생각하는데요.
여기서 각 구현 단위란 View, ViewModel, Model을 의미하며 제가 생각하는 MVVM의 각 구현 단위의 목적은 풀어서 설명해보자면 아래와 같아요!
- **View**는 UI 와 관련된 로직만 가지며, 사용자로부터 이벤트 입력을 받고 ViewModel에 이벤트를 전달한다.
- **ViewModel**은 View로 부터 이벤트를 받으면 Model 데이터에 업데이트를 요청하고, Model의 데이터를 가공하는 로직을 가진다.
- **Model**은 데이터를 저장하고 있으며 ViewModel의 요청이 있을 때 값을 업데이트한다.

즉, View는 현재 상황에 따라 표시하고자 하는 데이터를 ViewModel로 부터 가지고 오지만, ViewModel은 View를 알지 못 한 채로 가공된 데이터를 제공하는 게 목적이라고 생각해요. (왜 ViewModel이 View를 알지 못 한 채로 있어야 할지는 의존성을 중심으로 MVVM 아키텍쳐에 관해 고민해보시면 좋을 거 같아요 ☺️)
이때, ViewModel에 변화가 있는지 확인하고 화면을 갱신시키는 것이 View의 책임이고 **이를 구현할 수 있는 방법이 데이터 바인딩**이라고 생각합니다!

제가 생각하기에 데이터 바인딩 관계는 View-ViewModel 간에는 필요할 수 있지만, ViewModel-Model 간에는 반드시 필요한지 의문이 드는데요 🤔
어떤 부분이 의문인지 공유해주시면 같이 이해를 맞춰나갈 수 있을 거 같아요~ 😆



#### 2. body 프로퍼티가 여러 뷰를 리턴하는 것에 관하여

오호 저도 이 부분 예전에 책에서 봤던 내용이랑 달라서 살펴보았는데요!
구현체를 살펴보니 body 프로퍼티는 [ViewBuilder](https://developer.apple.com/documentation/swiftui/viewbuilder) 속성을 가지고 있기 때문에 여러 뷰를 리턴할 수 있을 것으로 보여요~

<img width="758" alt="ViewBuilder" src="https://user-images.githubusercontent.com/38066039/140803602-b477372b-e807-47cd-9765-05961d179f2a.png">



## 아직 해결하지 못 한 점

네비게이션 타이틀 옆에 뷰를 두는 것과 관련해서는 어떤 네비게이션 타이틀을 말씀하시는지가 헷갈리는데요..!
만약 각 리스트에서의 네비게이션 타이틀을 말씀하시는 거라면 HStack으로 뷰를 가로로 배치하고, 이미지와 레이블이 중첩되는 부분에 대해서는 ZStack 으로 한 번 더 감싸주는 방법 등 Stack 뷰를 활용해볼 수 있을 거 같아요~

그 외 구현사항에 대해서는 기능요구서의 UI를 보고 구조를 파악한 뒤 적용을 진행해보면 좋을 거 같습니다 😊



---

Step2 진행 고생 많으셨어요~ 😆🙌
이번 스텝에서의 핵심 경험은 아래와 같았는데요.

<img width="294" alt="Step2" src="https://user-images.githubusercontent.com/38066039/140803717-dfe0d4e3-302c-45be-bb17-2bf276fd78cd.png">

아직 해결하지 못 한 부분들을 포함해서 Step2는 좀 더 수정을 진행해보면 좋을 거 같아서 Request Changes 로 요청드렸어요 ☺️🙏

추가로 기능요구서에서 누락된 부분이 있어서 이 부분들도 같이 확인 부탁드려요~
- TODO와 DOING의 기한에 지난 날짜가 있으면 빨간색으로 표시합니다 (현재는 모든 내용이 파란색으로 나타나고 있어요)
- 할일을 터치하면 상세내용을 표시합니다 (현재는 할일이 터치되지 않고 있어요)
- 할일을 길게 터치하여 팝오버 메뉴를 표시합니다 (현재는 팝오버 메뉴가 없는 것으로 보여요)
- Date Picker 의 입력 포맷: 시간 상세 입력 -> 날짜 상세 입력 으로 변경

그 외의 수정사항을 더 반영했으면 하거나 설명이 필요한 코멘트가 있다면 말씀해주세요~ 👀👂
구현 중 발생하는 어려움들에 대해서는 그때그때 문제를 공유해주시면 같이 해결 방법을 고민해볼 수도 있으니 언제든 DM 주세요!

2021-11-08 19:20 UTC, YebinKim commented on ProjectManager/ProjectManager/View/DatePicker/TodoListDatePicker.swift
> +        DatePicker(text, selection: $viewModel.date)
DatePicker 는 현재 `.labelsHidden()` 을 통해 표시되는 텍스트를 가려주고 있는 것으로 보이는데,
text 를 DatePicker에 전달하고자 하신 의도가 무엇일까요?

2021-11-13 04:00 UTC, blanche37 commented on ProjectManager/ProjectManager/View/TodoListViewModel.swift
> +    func create() {
수정했습니다!

2021-11-13 04:01 UTC, blanche37 commented on ProjectManager/ProjectManager/View/DatePicker/TodoListDatePicker.swift
> +        DatePicker(text, selection: $viewModel.date)
아하.. 확장성을 생각해서 그렇게 만들었었는데, 라벨을 숨기고 있어서 의미가 없겠네요 😂

2021-11-13 04:01 UTC, blanche37 commented on ProjectManager/ProjectManager/View/TodoListViewModel.swift
> +    func addCount(count: inout Int) {
수정했습니다!

2021-11-20 08:56 UTC, YebinKim commented
프로젝트 수행 기간이 지나 클로즈 처리합니다.
고생 많으셨어요 윤 😊👏

2021-11-20 08:56 UTC, closed without merging