프로젝트 관리 앱 [Step2] Shapiro, Coden
yagom-academy/ios-project-manager pull request #53
Opened 2021-11-05 07:49 UTC by ictechgy

@jungseungyeo 

안녕하십니까 린생!!!! 이제서야 PR을 보냅니다..
화요일까지 보내기로 했는데 막히는 부분이 너무 많았어서 많이 지연이 됐습니다. 😭
잘부탁드립니다..! 🙏

### 동작 GIF
<img src ="https://user-images.githubusercontent.com/39452092/140476056-889bbfc7-9a18-400a-bba9-ea9cbcd0b465.gif" />

## 구현한 내용
1. **'할 일' 추가기능을 구현하였습니다. (우측 상단의 + 아이콘)**
 - 이 기능은 `@State`와 `sheet()`를 이용하여 구현하였습니다.
2. **기존에 추가된 '할 일' 편집 및 저장기능을 구현하였습니다.**
 - '할 일' 추가 화면에서 사용하는 View를 이곳에서도 재사용하는 방식으로 구현하였습니다.
 - [새로운 데이터 추가/기존 데이터 상세보기]에 따라 어떤 데이터를 보여줄 것이냐는 `MemoModel` 내 `presentedMemo`가 가지도록 하였습니다. 새로운 '할 일' 추가시에는 이 데이터에 새 인스턴스를 할당해주었고 기존 '할 일' 상세 보기시에는 사용자가 클릭한 '할 일'이 할당되도록 하였습니다.
3. **추가되어있는 '할 일'을 다른 열로 이동시키는 기능을 구현하였습니다.**
 - 이 기능은 `@State`와 `popover()`를 이용하여 구현하였습니다.
4. **추가되어있는 '할 일' 삭제 기능을 구현하였습니다.**
 - ForEach의 `onDelete()`로 구현하였습니다.
5. **기기 지역포맷에 맞게 날짜가 표시되도록 하였으며 기한이 지난 경우 빨간색으로 나타나도록 구현하였습니다.** 
 - 지역 포맷에 따른 날짜 표시는 `Text(_:style:)`설정에 따라 자동으로 되서 신경써준 부분은 없습니다. 다만 프로젝트 설정에서 Localizations 추가를 안해주면 안먹히는 버그(?)가 있어서 Korean을 별도로 추가해주었습니다.
 - 날짜가 지난 경우 빨간색으로 표시해주는 것은 `MemoRow`에서 해주고 있습니다. 

## 궁금한 내용
1. 린생이 공유해주셨던 Clean Architecture는 STEP3를 구현하면서 적용해보려고 합니다. 현재 구조에서 해당 아키텍쳐로 확장해 나갈때 (현재 저희가 작성한 방식이) 큰 문제가 없을지 궁금합니다. 

2. 현재 View쪽에서 데이터를 보여줘야 하는 부분들은 모델 엔티티(`Memo`)를 가지도록 만들었는데요. 이렇게 해도 괜찮은 것일까요? 아니면 별도의 ViewModel을 가지고 있도록 하는 방식같은 것들이 더 나을까요?? 
3. 결국 List에 있는 Row들끼리 간격을 띄우지는 못했습니다. VStack으로는 구현할 수 있는 것 같은데 List로는 도저히 못하겠더라구요. 혹시 해결책을 찾으셨다면 공유해주시면 감사하겠습니다 ㅠㅠ 
4. 현재 저희는 `MemoModel`에서 데이터를 2차원 배열 형식으로 가지고 있습니다. 이 방식이 괜찮은걸까요? 아니면 1차원 배열이 나은걸까요? (1차원 배열을 사용하면 검색을 위한 순회가 너무 많이 발생하게 되어서 안쓰는 것이 좋겠다고 일단 판단하긴 했습니다. )
5. 기한이 지난 것의 경우 빨간색으로 표시하는 로직을 `MemoRow` 뷰에서 가지고 있도록 하였는데요. 데이터 자체에 대한 것이라기보다는 단순히 보여주기 위한 부분이다보니 뷰에다 두는 것이 좋지 않을까 저희는 생각했습니다. 린생은 어떻게 생각하시나요?

2021-11-05 14:16 UTC, jungseungyeo commented
1. 린생이 공유해주셨던 Clean Architecture는 STEP3를 구현하면서 적용해보려고 합니다. 현재 구조에서 해당 아키텍쳐로 확장해 나갈때 (현재 저희가 작성한 방식이) 큰 문제가 없을지 궁금합니다.

> ViewModel의 역할이 예매해요 MemoModel가 존재하여 viewmodel의 단순히 데이터를 전달하는 DAO의 역할을 하고 있어요. MemoModel의 역할이 viewModel에서 가면 좋을거 같아요.

2. 현재 View쪽에서 데이터를 보여줘야 하는 부분들은 모델 엔티티(Memo)를 가지도록 만들었는데요. 이렇게 해도 괜찮은 것일까요? 아니면 별도의 ViewModel을 가지고 있도록 하는 방식같은 것들이 더 나을까요??

> ViewModel이 가지고 있게 해주세요. Model은 view에 존재하면 안됩니다. 

3. 현재 저희는 MemoModel에서 데이터를 2차원 배열 형식으로 가지고 있습니다. 이 방식이 괜찮은걸까요? 아니면 1차원 배열이 나은걸까요? (1차원 배열을 사용하면 검색을 위한 순회가 너무 많이 발생하게 되어서 안쓰는 것이 좋겠다고 일단 판단하긴 했습니다. )

> 1차원으로 해도 되고 2차원으로 해도 크게 상관은 없는거 같아요. 저는 2차원 배열로 구현을 했을 거 같긴해요 이건 단순히 코드 스타일의 문제인거같아요 

4. 기한이 지난 것의 경우 빨간색으로 표시하는 로직을 MemoRow 뷰에서 가지고 있도록 하였는데요. 데이터 자체에 대한 것이라기보다는 단순히 보여주기 위한 부분이다보니 뷰에다 두는 것이 좋지 않을까 저희는 생각했습니다. 린생은 어떻게 생각하시나요?

> view에서 모델을 접근하면 안되요 view에서 데이터를 알고 있으면 view에서 데이털르 보고 무엇을 보여줄수있을지 판단하는 로직이 생기는 원인이 되고 그렇게 되면 코드 가독성이 떨어지게 되요 Model이 가지고 있는 쪽에서 처리하는 방식이 좀 더 좋을 거 같아요.

코든, 샤피로 고생하셨어요. 기간을 지키지는 못했지만 코드 성능이 좋은거 같아요. 다만 input 의 역할만 수정 하면 좋을거같아요. input은 add, delete와 같은 비지니스 동작을 주는 것보다는 view에서 어떤 행동을 했는지 알려주면 좋을거같아요. add 버튼이 눌렸다든지 아니면 다른 버튼이 눌렸다든지 등의 혹은 화면이 닫혔다던지 이런 이벤트를 주고 내부에서 로직을 수행하면 좋을거같아요. 지급 viewmodel의 역할이 없는거와 같거 같아요.

2021-11-05 14:16 UTC, jungseungyeo requested changes

2021-11-05 14:16 UTC, jungseungyeo commented on ProjectManager/ProjectManager/ViewModel/MemoViewModel.swift
> +extension MemoViewModel: MemoViewModelInput {
input의 역할이 좋지 않으거 같아요. 이벤트를 전달하는 느낌이 아니라 그냥 연결하는 DAO의 역할을 하고 있어요. 단순히 로직이 없이 전달만 한다면 viewModel의 역할을 고민해주세요 :)

2021-11-08 08:39 UTC, shapiro711 commented
@jungseungyeo
안녕하세요 린생...! 바쁘신 와중에 리뷰 감사드립니다!!
린생이 말해주신 부분을 토대로 저희가 수정을 해봤습니다!

## 수정 사항
1. View가 Model을 가지고 있지 않도록 수정
    List의 Row 같은 경우에 각각의 Row를 위한 1대1 ViewModel을 만들어서 적용하였습니다.
2. 비지니스 로직 위치 수정
    기존에 MemoModel이 가지고 있던 비지니스 로직을 ViewModel이 가지고 있도록 변경하였습니다.
3. ViewModelInput 방향성 수정
    기존 비지니스 로직처럼 보이던 Input들의 이름을 View의 상호작용에 중점을 두어 변경하였습니다.
4. View에 있던 상태값과 로직들을 ViewModel이 관리하도록 변경하였습니다.

위와 같이 변경을 해보았는데 아직 감이 잘 오지 않습니다...ㅎㅎ
괜찮게 리펙토링을 한 것인지 궁금합니다!!!

2021-11-08 08:41 UTC, shapiro711 commented on ProjectManager/ProjectManager/ViewModel/MemoViewModel.swift
> +protocol MemoViewModelInput {
네 인풋에 대해서 저희가 감을 잘 못잡았던것 같습니다... 수정해볼게요!!!

2021-11-08 13:09 UTC, jungseungyeo commented
1. View가 Model을 가지고 있지 않도록 수정 List의 Row 같은 경우에 각각의 Row를 위한 1대1 ViewModel을 만들어서 적용하였습니다.

> 넵! 좋아요 하나의 view와 하나의 viewModel을 생각하고 하신거 같아요. 꼭 하나의 view의 viewModel이 있어야 되는거는 아니지만 현재 mvvm을 익숙하기 위해서 1대1 구조도 나쁘지 않은거 같아요.

2. 비지니스 로직 위치 수정 기존에 MemoModel이 가지고 있던 비지니스 로직을 ViewModel이 가지고 있도록 변경하였습니다.

> 이거는 기존의 기능을 하는 manager가 생긴거 같아요. MemoListViewModel에서 해주어야 될 거 같아요.

3. ViewModelInput 방향성 수정 기존 비지니스 로직처럼 보이던 Input들의 이름을 View의 상호작용에 중점을 두어 변경하였습니다.

> 너무 좋아요!

4. View에 있던 상태값과 로직들을 ViewModel이 관리하도록 변경하였습니다.

> 너무 좋아요 상태관리는 viewModel에서 하고 view는 그 상태를 옵저빙 하는게 가장 베스트지만 지금 구조도 좋은 거 같아요. 자신의 상태의 따라 로직이 변경되는게 아니라 액션의 따라 동작이 달라지면 더욱 좋을거같아요.

코든, 샤피로 step2 고생하셨어요. MemoModel의 역할을 MemoListViewModel로 옮기는 작업만 해주면 좋을거 같아요. 이 부분은 step3에서 해주셔도 좋을거같습니다 :)  고생하셨습니다 :)

2021-11-08 13:10 UTC, jungseungyeo approved these changes

2021-11-08 13:10 UTC, merged