프로젝트 관리 앱 [STEP 2] Nala
yagom-academy/ios-project-manager pull request #57
Opened 2021-11-10 08:39 UTC by jazz-ing

안녕하세요, 라자냐!(@wonhee009)
스텝2 PR이 예상 기한보다 훨씬 많이 늦어졌습니다ㅠㅠ
SwiftUI와 MVVM이 처음이다보니 많이 헤맸던 것 같습니다.

지금 View의 코드가 메소드로 하나도 분리가 되어있지 않아 굉장히 복잡합니다ㅠㅠ
그런데 기한이 많이 늦어져서 일단은 PR을 보내놓고 다시 찬찬히 보면서 수정을 진행해보려고 합니다..!

### 중점적으로 리뷰받고 싶은 부분
- MVVM구조를 잘 지켰는지
  - 제가 MVVM을 정확히 파악한건지 잘 모르겠습니다. 사실 SwiftUI는 도구다보니 어떻게든 방법을 찾아 해결할 수 있을 것 같은데
     MVVM에 대한 이해도가 높지 않아서 MVVM 패턴에 맞게 코드를 작성한 것지 확신이 잘 서지 않습니다..!
     MVVM과 맞지 않는 구조나 코드에 대한 지적 촌철살인으로 주시면 감사하겠습니다!!

잘 부탁드립니다😘

2021-11-11 05:15 UTC, wonhee009 requested changes
@jazz-ing 날라 스텝2 수고하셨습니다!
리뷰 남겨두었으니 확인 부탁드려요🙏

2021-11-11 05:15 UTC, wonhee009 commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +    }
파라미터로 받아오는 plan은 id를 사용하기 위해서 받는거 같은데요.
id만 파라미터로 받아와도 되지 않을까요?

2021-11-11 05:15 UTC, wonhee009 commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +    mutating func delete(at indexSet: IndexSet) {
여기에서 받고 있는 indexSet은 PlanListView에서 가져오고 있는거 같은데요.
여기서 받는 indexSet과 plans의 index가 다를거 같은데요.
제가 잘못 이해하고 있는걸까요?🤔

2021-11-11 05:15 UTC, wonhee009 commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +        }
`description`이 결국은 rawValue를 반환하고 있네요🤔
사용하는 곳에서 state.rawValue를 사용하지 않고 `description`을 따로 선언한 이유가 있을까요?
```swift
var description: String {
   switch self {
      case .toDo:
         return "TODO"
   }
}
```
`description`으로 명시적으로 알려주고 싶어서 사용했다면 위와 같이 rawValue를 사용하지 않고 computed property만 선언해줘도 될거 같습니다.
현재는 사용하는 곳에서 `state.rawValue`, `state.description` 모두 열려 있어서 헷갈릴거 같아서요.

2021-11-11 05:15 UTC, wonhee009 commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +struct ProjectToDoList {
또한 해당 파일이 Model 폴더에 있는거 보니 Model로써 작성하신거 같습니다.
`add`, `delete`와 같은 메서드들은 비즈니스 로직이라고 생각이 드는데요.
해당 메서드들이 여기에 위치한 이유가 있을까요?

2021-11-15 02:52 UTC, jazz-ing commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +struct ProjectToDoList {
'ToDoList'라는 단어 자체가 todo, doing, done을 포함하는 일정 관리를 상징할 수 있는 단어라고 생각해 이렇게 네이밍을 했는데요. 
코드에 'todo'라는 것이 직접 쓰이니 해당 네이밍이 todo에 대한 List만을 포함한다고 생각되기가 쉬울 것 같습니다. 
`Plan`이 각 State를 모두 갖고 있기 때문에 `ProjectPlanList`로 바꿔봤는데 괜찮을까요?

2021-11-15 02:53 UTC, jazz-ing commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +struct ProjectToDoList {
struct로 정의한 이유는 `@Published`때문인데요.
ViewModel에서 `@Published`를 이용해 값에 변화가 있을 때 업데이트를 하기 위해서는
참조타입이 아닌 값타입인 struct여야 값 변화를 감지할 수 있기 때문에 struct를 사용했습니다!

2021-11-15 02:56 UTC, jazz-ing commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +struct ProjectToDoList {
MVVM, 특히 Model과 Business Logic에 대해서
- 처음에는 MVVM에서 business logic이 Model에 있어야 한다고 생각해서 해당 타입에 메서드를 정의해놓았는데요. MVVM에 대해 좀 더 찾아보다보니 지금의 구조가 어색하다는 것을 알게 되었습니다.
- 그런데 지금은 Model인 `ProjectToDoList`에서 `Plan`의 배열인 plans를 가지고 있기 때문에 plans를 바꿔줄 비즈니스로직이 Model인 해당 타입에 있어야 할 것 같습니다. 이후 코어데이터나 네트워킹을 다루게 된다면 각각의 비즈니스 로직을 다룰 Service 타입들을 만들어보려고 합니다.
- 이렇게 생각을 한 건 제가 MVVM을 아래와 같이 이해했기 때문인데요. 혹시 틀린점이 있다면 조언부탁드립니다😇
    - Model에 2가지 종류가 있다고 받아들여졌습니다.
      - 우선 data의 form을 정해놓는? 제 코드상에서는 `Plan`과 같은 Data Model이 하나
      - 비즈니스 로직, 즉 앱의 핵심 기능의 로직이 담긴 Service라는 Model 하나
    - ViewModel은 Model과 View를 이어주는 역할로써, Presentation logic을 갖고있음
    (예를 들어 date의 포맷을 View에서 바로 보여줄 수 있는 형식으로 바꿔주는 로직)
    - View는 ViewModel에서 받는 데이터의 상태를 보여주기만 함

2021-11-15 02:57 UTC, jazz-ing commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +    }
edit()을 호출할 때, edit(plan, title...)이라고 보이는게 edit(plan.id, title...)로 보이는 것보다 좀 더 plan을 수정하는 걸로 읽히지 않을까.. 하는 생각을 했었습니다..ㅋㅋ

혹시 매개변수로도 Plan struct자체를 받는 것과 UUID만 받는 것이 성능 차이가 생기는 걸까요?

2021-11-15 02:58 UTC, jazz-ing commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +    mutating func delete(at indexSet: IndexSet) {
`delete()`에서 받고 있는 indexSet은 라자냐가 말씀해주신 것처럼 PlanListView에서 `onDelete()`라는 메소드를 통해 받아오고 있는데요.
`onDelete()`는 ForEach와 함께 쓰이면서, ForEach가 반복하며 만드는 뷰의 기반이 되는 배열, 즉 `plans`의 indexSet을 `onDelete()`의 클로저에 넘겨주기 때문에 서로 같은 index일거라고 생각됩니다!

2021-11-15 02:58 UTC, jazz-ing commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +        }
enum의 case와 완전히 동치되는 값인 경우 rawValue를 사용한다고 알고 있는데요.
즉 case strawberryJuice = "딸기쥬스"
enum밖에서는 rawValue를 직접 쓰는 것이 좋지 않다고 해서(사실 이 얘기를 듣기만 하고 저도 아직 근거를 찾지는 못해서 왜 안 좋은건지 아직 잘 모르겠습니다.. 혹시 라자냐는 아시나요?🥺) rawValue를 준뒤 해당 rawValue를 연산프로퍼티 description을 통해 반환하는 방식으로 써보았습니다. 
그런데 이렇게하면 라자냐가 말씀해주신대로 rawValue와 description이 모두 열려있게되니 좋은 방식이 아닌 것 같습니다. 
연산프로퍼티로 리턴해주는 방식으로 수정했습니다!

2021-11-15 23:31 UTC, wonhee009 requested changes

2021-11-15 23:31 UTC, wonhee009 commented on ProjectManager/ProjectManager/Model/ProjectPlanList.swift
> +
`ProjectPlanList`를 모델로 정의했는데요.
모델로 정의한 이유가 있을까요?

`ProjectPlan`까지를 모델로 생각하고,
VM에서 list를 들고 있어도 되지 않을까 해서요.

2021-11-15 23:33 UTC, wonhee009 commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +        }
> 사실 이 얘기를 듣기만 하고 저도 아직 근거를 찾지는 못해서 왜 안 좋은건지 아직 잘 모르겠습니다.. 혹시 라자냐는 아시나요?🥺

이 부분은 제 생각에는 어떤 값일지 예상을 못해서 아닐까요?
아무리 rawValue가 'enum의 case와 완전히 동치되는 값'이지만 사용하는 곳에서는 `.rawValue`로만 사용될텐데 어떤 값일지 해당 코드에 들어가서 확인해야하지만 `description`과 같은 프로퍼티로 가지고 있다면 이름만 보고도 유추할 수 있어서...?🤔

2021-11-15 23:34 UTC, wonhee009 commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +    mutating func delete(at indexSet: IndexSet) {
`forEach`를 통해서 indexPath를 가져오는데 성능상에 문제는 없을까요?
plan이 너무 많을때에는요?

2021-11-15 23:35 UTC, wonhee009 commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +    }
성능의 문제라기 보단 plan에서 `id`만 사용하는데 다른 프로퍼티들이 불필요해 보여서 의견 드렸습니다😀

2021-11-15 23:42 UTC, wonhee009 commented on ProjectManager/ProjectManager/Model/ProjectToDoList.swift
> +struct ProjectToDoList {
> 이후 코어데이터나 네트워킹을 다루게 된다면 각각의 비즈니스 로직을 다룰 Service 타입들을 만들어보려고 합니다.

현재 "ProjectToDoList에서 Plan의 배열인 plans를 가지고 있기 때문에" plans를 바꿔줄 비즈니스로직이 Model에 있어야 할 것 같다고 말씀해주셨는데요.
어떤 방식으로 Service 타입을 만들지는 모르겠으나 해당 비즈니스로직은 Model과 연관이 있을거 같습니다.🥲

> ViewModel은 Model과 View를 이어주는 역할

또한, 이렇게 말씀해주셨는데요.
`[Plan]`이 viewModel에 있어야하는게 아닌가 생각했습니다.
날라가 말해준 Model의 2종류에 저는 `[Plan]`은 포함되지 않는다고 생각했거든요.

오히려 `[Plan]`은 Presentation logic과 좀 더 가깝지 않나 생각합니다.
사실상 이런 배열은 우리가 화면에 리스트를 보여주기 위해 Plan을 한 번 가공한거라고 생각하거든요.

2022-02-13 13:38 UTC, closed without merging