프로젝트 관리 앱 [Step3-1] Coden, Shapiro
yagom-academy/ios-project-manager pull request #59
Opened 2021-11-14 16:15 UTC by shapiro711

@jungseungyeo 
안녕하세요 린생!!

STEP3 명세에 들어있는 모든 기능을 구현하지는 못했지만 저희가 구현한 Clean Architecture 에 대한 피드백을 받고 싶어 PR을 보냅니다...!

최근에 엄청 바쁘신것 같은데 ㅠㅠ 잘 부탁드립니다 :)

## 프로젝트 구조
![파일구조](https://user-images.githubusercontent.com/57553889/141688940-61b1eeab-2a6d-493c-b095-e2f126c68121.png)

## 구현 사항

1. 클린 아키택쳐 적용
   + Presentation Layer
     + View - Swift UI를 사용하여 화면 요소들을 구현했습니다.
     + ViewModel - View에서 일어난 상호작용들을 받아 상태값을 처리하거나 비지니스 로직이 있는 UseCase에 처리를 요구합니다. 
   + Domain Layer
     + UseCase - 앱의 핵심기능에 대한 로직(CRUD)을 가지고 있습니다. 데이터의 흐름에 따라 ViewModel과 Repository에 데이터를 넘겨줍니다.
     + Entity - 프로젝트에서 사용되는 Data Structure를 구현하였습니다. 
   + Data Layer
     + Repository - UseCase가 Remote, Persistent  중 어떤 Storage와 통신을 할지 고려하지 않고 사용할 수 있도록 연결고리 역할을 합니다. (추후 동기화에 대한 로직 구현 예정)
     + RemoteStorage - Firebase 통신 구현
     + PersistentStorage - CoreData 통신 구현
2. History와 Memo에 대한 flow를 각각 나눠서 구현 (ViewModel, Usecase, Repository, Storage)
3. CoreData를 이용한 Memo CRUD 및 History를 보여주는 기능 구현
4. Firebase - 현재 Firebase를 이용한 CRUD 기능을 구현하고 테스트까지 완료했지만 동기화 문제를 해결하지 못하여 전체 로직에서는 제외하였습니다.

## 궁금한 점

1. 아키택쳐 구성 - 저희 나름대로 열심히 공부하여 클린아키택쳐를 적용해봤습니다. 의존성 규칙도 지켜보려 노력했습니다. 전체적인 구조가 괜찮게 이루어져있는지 린생의 생각이 궁금합니다.
2. 객체 생성시 프로퍼티가 비동기적으로 초기화 됨으로 인해 생기는 문제 
   1. FirebaseStorage CRUD 로직은 uid를 얻은 뒤에 이루어 져야합니다.
   2. FirebaseStorage의 uid 프로퍼티는 비동기적으로 얻어와 초기화 됩니다.
   3. CRUD 로직이 실행될때 uid를 얻어오는 작업이 끝나있지 않으면 에러가 발생합니다.
   4. 저희는 FirebaseStorage 객체를 생성할때 init에 이러한 uid 비동기 작업을 넣어 놨었습니다.
   5. 해결을 하지 못하여 각각의 CRUD 작업마다 매번 uid를 얻어오는 작업을 감싸 해결했습니다.

3. Remote, Local 동기화 문제 - 고려해야할 문제가 너무 많아 어떻게 동기화를 해야할지 감이 안잡힙니다...

   + 여러 기기가 같은 사용자로 동시에 작업이 이루어지는 경우  - 포기했습니다...
   + 기존에 써놓은 메모가 있고, 앱을 삭제후 다시 설치했을때 인터넷 연결이 되어있지 않은 상황에서 메모의 변경이 이루어지는 경우
     + 저희가 생각했던 로직은 remote, local 각각 최근 수정시각을 가지고 있고 비교하여 처리를 하려 했습니다.
     + 하지만 위와 같은 경우에는 이러한 로직이 불가능합니다...

   사실 모든 케이스들은 커버하는 로직을 저희가 짜기엔 무리가 있어보입니다. 어떤 방향을 가지고 이 부분을 해결하면 좋을까요? 린생의 생각이 궁금해요~

2021-11-16 14:31 UTC, jungseungyeo commented
1. 클린 아키택쳐 적용

>이 부분 잘 적용이 된거 같아요. 다만 코멘트로 남겼듯이 repository protocol은 하나로 구성하면 좋을거같아요. 특정 모델을 사용하다보니 여러 repository가 생성 되는 결과를 만들게 되요. 제네릭을 활용하면 해결이 가능할거같아요.

2. History와 Memo에 대한 flow를 각각 나눠서 구현 (ViewModel, Usecase, Repository, Storage)

> 너무 좋아요 제가 의도한 방향으로 잘 구성이 된 거 같아요!

----

## 궁금한 점

1.아키택쳐 구성 - 저희 나름대로 열심히 공부하여 클린아키택쳐를 적용해봤습니다. 의존성 규칙도 지켜보려 노력했습니다. 전체적인 구조가 괜찮게 이루어져있는지 린생의 생각이 궁금합니다.

> 잘 구성이 된 거 같아요. repositry 프로토콜만 수정하면 좋을거같아요. 이 정도로 완성도 높게 만들어 수 있을지 몰랐는데 너무 좋습니다. 각 레이어 단에서 역할이 잘 된 거 같아요. 다만 viewModel의 역할이 단순히 curd를 연결하는 부분 같이요.  viewModel의 역할이 무엇인지 이야기 해주면 좋을같아요. 데이터를 가공하거나 정제하는 부분이 미흡한 거같아요. DAO, DTO의 역할을 viewModel이 어느 정도 해주면 좋을거같아요.

2. 객체 생성시 프로퍼티가 비동기적으로 초기화 됨으로 인해 생기는 문제

> 이 부분은 어쩔수 없을거같아요. SwfitUI 특성상 UUID가 필요하여 이 필수인거같아요. ㅠㅠ

3. Remote, Local 동기화 문제 - 고려해야할 문제가 너무 많아 어떻게 동기화를 해야할지 감이 안잡힙니다...

> 이 부분은 최신 데이터를 어디에 두고 백업을 어디에 할지를 기준을 잡으면 좋을거 같아요. 둘 다 동시에 최신의 데이터를 가진다고 생각한다면 데이터 낭비인거같아요. 최신 데이터를 어디에 두고 백업하는 시전에 데이터를 백업하는 코드로 한다면 최신 데이터를 가져와서 백업에 보내주는 부분만 필요하겠죠? 이런 관점에서 동기화를 한다고 생각하면 좋으러같아요.

코튼, 샤피로 이번에 코드를 보면서 너무 감명을 받았어요. 제가 이제 막 배우는 단계였다면 이런 코드는 못 만들었을거같아요. 정말 처음 접하는 clean mvvm의 형태를 잘 구현한거 같고, 제가 드린 블로그 내용이 잘 반영이 된 거 같아요. 수고하셧습니다. 코멘트에 남기 repositry만 수정하면 머지 될 거같아요. 이 부분 적용해주세요  :)

2021-11-16 14:32 UTC, jungseungyeo requested changes

2021-11-16 14:32 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Presentation/ViewModel/HistoryListViewModel.swift
> +    func didTouchUpHistoryButton()
did를 붙여주는 부분 너무 좋네요 :)

2021-11-16 14:32 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Presentation/ViewModel/HistoryListViewModel.swift
> +    private(set) var historyViewModels: [HistoryViewModel] = []
protocol에서 get으로 선언하고 자동으로 private(set) 되지 않나요?

2021-11-16 14:32 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Presentation/ViewModel/HistoryListViewModel.swift
> +                DispatchQueue.main.async {
Dispatchqueue를 해주는 이유는 무엇인가요?

2021-11-16 14:32 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Presentation/ViewModel/MemoListViewModel.swift
> +    init(memoUseCase: UseCase = MemoUseCase()) {
protocol으로 만든부분 너무 좋아요 :)

2021-11-16 14:32 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Presentation/ViewModel/MemoListViewModel.swift
> +                fatalError(error.localizedDescription)
fatalError는 사용하지 말아주세요 이 부분이 실행되면 apple 리젝사유가 됩니다.

2021-11-16 14:32 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Domain/Interfaces/Repositoryable.swift
> +    func add(memo: Memo, completion: @escaping (Result<Memo, Error>) -> Void)
여기서는 Memo를 받지만 제네릭을 사용하면 범용적으로 사용하는 코드가 될 거같아요

2021-11-16 14:32 UTC, jungseungyeo commented on ProjectManager/ProjectManager/Domain/Interfaces/HistoryRepositoryable.swift
> +    func fetch(completion: @escaping (Result<[History], Error>) -> Void)
Repositoryable의 모델을 제네릭으로 만들면 하나로 만들 수 있을거 같아요 이 부분은 수정 해주세요 :)

2021-11-19 07:28 UTC, shapiro711 commented on ProjectManager/ProjectManager/Presentation/ViewModel/HistoryListViewModel.swift
> +    private(set) var historyViewModels: [HistoryViewModel] = []
저희가 의도한 부분은 외부에서 쓰기 작업을 막으려 했었는데...! 저희가 알기로는 따로 지정을 해두지 않으면 (var historyViewModels: [HistoryViewModel] = []) 프로토콜에서 get으로 선언을 해도 외부에서 쓰기 작업이 가능한 것으로 알고있습니다.
혹시 저희가 린생의 의도를 잘못 파악한걸까요 ㅠ?

2021-11-19 07:31 UTC, ictechgy commented on ProjectManager/ProjectManager/Presentation/ViewModel/HistoryListViewModel.swift
> +                DispatchQueue.main.async {
이 곳에서의 값 변경은 `@Published` 프로퍼티 값의 변경을 초래하고, 이는 뷰의 변경도 발생시킵니다. 뷰의 변경은 메인 쓰레드에서만 일어나야 하기 때문에 `@Published` 프로퍼티 값의 변경 자체가 메인 쓰레드에서 일어나도록 해주었습니다. (그렇게 해주지 않으면 뷰의 변경이 메인 쓰레드가 아닌 다른 쓰레드에서 일어나게 됩니다. 앱이 크래시가 나지는 않지만 뷰 업데이트가 됐다 안됐다 하는 현상을 발견하였습니다.)

2021-11-19 07:32 UTC, shapiro711 commented on ProjectManager/ProjectManager/Presentation/ViewModel/MemoListViewModel.swift
> +                fatalError(error.localizedDescription)
사실 저희가 에러처리를 나중에 한번에 하려했었습니다... 시간이 부족해서 미처 처리를 하지 못했네요...! 나중에 리펙토링을 하더라도 fatalError를 사용한 부분이 남아 있을 수도 있으니 다음부터는 아예 사용을 자제해보겠습니다 :)

2021-11-19 07:53 UTC, shapiro711 commented
@jungseungyeo
안녕하세요 린생~!!
린생이 말씀해주신 부분을 토대로 변경을 조금 해서 다시 푸시를 했습니다.
해결하지 못한 부분도 있는데요...! 린생의 의견이 궁금해요 ~

## 변동 사항
1. UseCase에 있는 메서드들의 네이밍 변경 - 린생의 말씀대로 상호작용을 통해 일어나는 행위를 토대로 이름을 변경해보았습니다.
2. ViewModel의 상태값을 이용한 처리 - SwiftUI 특성상 Bool 값을 이용하는 부분이 많아 기존의 코드에서 변경을 어떻게 할지 감이 잘 오지 않았습니다. 대신 메모를 가져올때 로딩을 나타내주는 indicator를 추가하고 이때 ViewModel이 상태값을 가지고 있도록 추가해보았습니다.

## 해결하지 못한 부분
1. Repository Protocol을 제네릭을 이용하여 하나로 합치는 부분
이 부분은 제네릭을 이용하려하다 보니 associate type을 사용하게 되었습니다. 이렇게 되다 보니 UseCase에서 추상화된 Repository를 가질 수 없게 되어 의존성 역전을 이용하지 못하게 되었습니다. 저희가 시도했던 방법에 대한 코드를 아래 첨부해볼게요!
<img width="800" alt="스크린샷 2021-11-19 오후 4 47 48" src="https://user-images.githubusercontent.com/57553889/142585416-5f1e211c-6e38-4972-b848-b50380f99c47.png">
<img width="1034" alt="2021-11-19_4 50 03" src="https://user-images.githubusercontent.com/57553889/142585460-3d7b5e62-b3bd-4754-a557-190898c269dc.png">
<img width="708" alt="스크린샷 2021-11-19 오후 4 51 02" src="https://user-images.githubusercontent.com/57553889/142585547-f05ee5c0-684b-4a20-a619-e5d0013b4e86.png">

위와 같이 의존성을 지켜보러 추상화된 타입을 사용하기 위해 노력을 해봤는데요...
결국 DomainLayer에서 DataLayer를 의존하게 되는 결과가 발생했습니다.
저희는 일단 의존성을 지키는게 좋겠다고 생각하여 원래의 코드로 돌려놓은 상태입니다.

린생이 말씀하신 부분에 대해 저희가 방향을 잘못 잡았을까요...?

2021-11-20 01:35 UTC, jungseungyeo commented
안녕하세요 샤피로, 코든 

적용 한 부분은 너무 잘해셨어요! Repository에서 추상화를 적용하는 부분에서 어려움을 느껴지는거 같아요. associate type을 사용하면 추상활를 사용하는데 좋지만 의존성을 주입하는데 힘들죠?

그래서 associate type을 사용하지 않고 사용하는 방법이 좋은거 같아요. 

repository가 구지 모델을 타임 캐스팅을 할 필요하는 없지 않을까 하는 생각이 들어요. 저 layer에서 타임을 캐스팅하면 무스한 많은 repository가 생성되는 형태가 되어 하나의 protocol이 아닌 중간 layer에서 서로 다른 protocol을 사용하여 하나의 형태를 가져가지 못하기 때문에 추상화가 필요하다는 말이였습니다.

저는 아래와 같이 예시를 한번 적용해 봤어요

```

protocol Entityable: Codable {}

protocol RepositoryModelable {
    func add(entity: Entityable, completion: @escaping (Result<Entityable, Error>) -> Void)
    func delete(entity: Entityable, completion: @escaping (Result<Entityable, Error>) -> Void)
    func update(entity: Entityable, completion: @escaping (Result<Entityable, Error>) -> Void)
    func fetch(completion: @escaping (Result<[Entityable], Error>) -> Void)
}

class Repository: RepositoryModelable {
    
    private let historyStorageable: HistoryStorageable
    
    init(historyStorageable: HistoryStorageable) {
        self.historyStorageable = historyStorageable
    }
    
    func add(entity: Entityable, completion: @escaping (Result<Entityable, Error>) -> Void) {
            
    }
    
    func delete(entity: Entityable, completion: @escaping (Result<Entityable, Error>) -> Void) {}
    func update(entity: Entityable, completion: @escaping (Result<Entityable, Error>) -> Void) {}
    func fetch(completion: @escaping (Result<[Entityable], Error>) -> Void) {
        historyStorageable.fetch { result in
            switch result {
            case .success(let memo):
                completion(.success(memo))
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }
}

struct Memo: Entityable {}

protocol HistoryStorageable {
    func fetch(completion: @escaping(Result<[Memo], Error>) -> Void)
    func fetchLast(completion: @escaping(Result<Memo, Error>) -> Void)
}

class UseCase {
    private let repository: RepositoryModelable
    
    init(respository: RepositoryModelable) {
        self.repository = respository
    }
}

```

코든과 샤피로의 코드를 보고 작성해 보았는데요, UseCase 타입 캐스팅을 하는 형태를 생각해보았어요. 아니면 viewModel까지 넘겨주어도 좋을거같아요.  이번 프로젝트를 하면서 고민한 포인트를 항상 기억해주시면 좋을거같아요. 업무에서도 각 layer 단에서 어떻게 clean하게 만드는지에 따라 유지 보수 및 관리 측면에서 좋을거같아요. 정말 고생하셨습니다. :)

2021-11-20 01:36 UTC, jungseungyeo approved these changes

2021-11-20 01:36 UTC, merged