프로젝트 관리 앱 [STEP 2] 예거
yagom-academy/ios-project-manager pull request #81
Opened 2022-03-02 19:23 UTC by Jager-yoo

안녕하세요 그린! 💚 @GREENOVER

구두로 대화를 나누며 `스텝2` 진도를 세분화했는데요. 😄 

- 스텝 2-1 -> `모델 타입 구현`
- 스텝 2-2 -> `기본 UI 구현`
- 스텝 2-3 -> `Cell 간의 이동, 삭제, 수정 등의 비즈니스 로직 구현`

첫 번째 `모델 타입 구현`이 완료돼서 PR 드립니다~!

바로 Local DB 모델을 만들기 위해 `Realm`을 적용해야 하나 고민했는데요. 😅 
프로젝트 요구 사항을 보니 아래와 같은 내용이 있더라구요.

> ✅ 할일의 모든 변경사항은 디스크에 저장하지 않고 앱 종료 후 다시 실행하면 빈 화면을 출력합니다

그 말인즉슨, 데이터를 디바이스에 저장하지 않고 메모리에 머물다가, 종료 시 휘발되도록 구현하라는 것으로 이해했습니다.
그래서 Realm 을 바로 적용하지 않고, 일단 Collection 타입으로 기초 모델을 구현했습니다. 👍🏻 

제주 여행🌴 잘 다녀오시고 천천히 코멘트 주셔도 괜찮습니다.
SwiftUI 공부하고 있겠습니다! ㅎㅎㅎ

<br>

# 🔥 고민한 부분

## 1️⃣ Firebase Realtime -> Firestore 전환

- 제게 조언해주신 대로, Remote DB 용도로 사용할 기능을 Realtime 에서 `Firestore`로 변경했습니다.

- 이 과정에서 둘의 차이가 어떤 것인지 공부해봤는데요. 가장 큰 차이는 [과금 모델](https://firebase.google.com/pricing?hl=ko)이라고 생각했습니다.

  - `Free tier`에서는 둘 다 약 1GB 정도의 데이터만 저장할 수 있는데요.

  - Firestore 는 `하루 CRUD 횟수`에 제한이 있고 Realtime 은 저장된 데이터 크기, 다운로드 크기에 제한이 있습니다.

  - 즉, 큰 단위의 데이터 요청이 자주 발생한다면 Firestore 가 유리하고, 가벼운 데이터이지만 CRUD 요청이 많이 발생한다면 Realtime 이 유리합니다.

  - 이번 프로젝트에서 다루는 데이터는 `text` 뿐이고 이미지조차 없기 때문에, `데이터 크기는 작지만, CRUD 요청이 많이 발생할 것`입니다.

  - 만약 `과금 모델만을 고려하면 Realtime 을 사용하는 게 유리한 선택`이지만, 그럼에도 저는 Firebase 의 최신 DB인 Firestore를 선택해 경험해보고자 합니다.

<p align="left"><img src="https://user-images.githubusercontent.com/71127966/156418104-ca47c24a-0123-479f-815e-535b02ea3bfc.png" width="70%"></p>

<br>

## 2️⃣ SwiftLint 추가

- 린트는 `SPM`을 지원하지 않습니다.

- 린트를 세팅하기 위해 `코코아팟`을 추가하기엔, 의존성 도구가 2개로 나뉘어져 관리의 불편함이 생길 거라 생각했습니다.

- [린트 공식 리드미](https://github.com/realm/SwiftLint#using-homebrew)를 참고하여, `Homebrew`를 이용해 린트 설치를 쉽게 완료했습니다. (자세한 과정은 리드미에 정리했습니다. 😄)

- [SwiftLint Rule Directory](https://realm.github.io/SwiftLint/rule-directory.html)를 꼼꼼히 확인하며, 매력적인(?) 옵션을 다양하게 골라봤습니다. 🛍️ 

<p align="left"><img src="https://user-images.githubusercontent.com/71127966/156408060-a8ca8935-bea8-48b2-b8c3-23d433adc73a.png" width="50%"></p>

<br>

## 3️⃣ '할일'을 표현하기 위한 Task, TaskStatus 타입 구현

- 이번 프로젝트에서 다뤄야 하는 주요 `Entity`는 `할일(Task)`입니다.

- Entity 객체 간의 Identity 를 구별하기 위해 `id` 값을 let 프로퍼티로 선언했습니다.

- 그 외의 title, body, dueDate, status 는 변경될 수 있는 값이므로, var 프로퍼티로 선언했습니다.

- id 는 불변이지만, 그 외의 프로퍼티는 자주 수정될 수 있으므로, 값타입인 `구조체`에서 `mutating` 키워드를 붙이기 보다는, `클래스` 타입으로 모델을 구현했습니다.

- Task 인스턴스가 생성될 때, id 는 String 타입으로 자동 생성되도록 `이니셜라이저`를 만들었습니다.

- 기한(dueDate)은 `Firestore`와의 연동을 고려하여, Date 타입으로 입력 받은 후 `TimeInterval(Double)` 타입으로 변환합니다.

- Task 가 생성될 때는 기본적으로 `TODO` status 로 설정됩니다.

- Task 인스턴스 간의 `동일성(id 매칭)`을 확인할 때 `==` 연산자를 사용할 수 있도록 `Equatable` 프로토콜을 채택했습니다.

```swift
class Task: Equatable {
    
    let id: String
    var title: String
    var body: String
    var dueDate: TimeInterval
    var status: TaskStatus
    
    init(title: String, body: String, dueDate: Date) {
        self.id = UUID().uuidString
        self.title = title
        self.body = body
        self.dueDate = dueDate.timeIntervalSince1970
        self.status = .todo
    }
    
    static func == (lhs: Task, rhs: Task) -> Bool {
        return lhs.id == rhs.id
    }
}

enum TaskStatus {
    
    case todo
    case doing
    case done
}
```

<br>

## 4️⃣ 데이터 관리를 담당하는 TaskManager 타입과 추상화 프로토콜 구현

- TaskManager 클래스는 할일(Task)들을 `배열` 형태로 가지고 있습니다.

- 추후 3개의 `UITableView(List)`를 구현할 때 `DataSource`로서 데이터를 전달해야 하므로, Status 별로 배열을 필터링해주는 연산 프로퍼티를 3개 구현했습니다.

- 할일(Task)을 보여줄 때, dueDate 가 `오래된 순서대로 정렬`될 수 있도록, Property Observer `didSet`을 사용했습니다.

- 전체 데이터에 해당하는 tasks 배열이 항상 오래된 순서대로 정렬되어 있으므로, 연산 프로퍼티의 리턴값으로 나오는 배열에서도 정렬을 유지할 것입니다. 😄 

- TaskManager `기능의 추상화`를 위해 TaskManageable 프로토콜 구현했습니다.

```swift
class TaskManager: TaskManageable {
    
    private var tasks = [Task]() {
        didSet {
            tasks.sort { $0.dueDate < $1.dueDate }
        }
    }
    var todoTasks: [Task] {
        return tasks.filter { $0.status == .todo }
    }
    var doingTasks: [Task] {
        return tasks.filter { $0.status == .doing }
    }
    var doneTasks: [Task] {
        return tasks.filter { $0.status == .done }
    }
    
    func createTask(title: String, body: String, dueDate: Date) {
        let newTask = Task(title: title, body: body, dueDate: dueDate)
        tasks.append(newTask)
    }
    
    func modifyTask(target: Task, title: String, body: String, dueDate: Date) {
        target.title = title
        target.body = body
        target.dueDate = dueDate.timeIntervalSince1970
    }
    
    func changeTaskStatus(target: Task, to status: TaskStatus) {
        target.status = status
    }
    
    func deleteTask(target: Task) {
        tasks.removeAll(where: { $0 == target })
    }
}
```

<br>

# 🤔 궁금한 부분

## 📅 날짜(dueDate) 프로퍼티의 타입을 무엇으로 지정하는 게 편리할까요?

- 할일(Task) Entity 에서 `날짜 데이터`에 해당하는 dueDate 프로퍼티의 타입을 어떻게 해야 `Firestore 와의 연동`이 편리할지 고민했습니다.

- Firestore 연동을 테스트할 때, `Date` 타입으로 날짜를 저장해봤는데요!
콘솔에서는 `Timestamp` 라는 타입으로 저장이 되는 걸 확인했습니다.
처음 보는 타입이라서, 원래 있던 건가 싶었는데, Firebase 모듈이 있어야만 사용할 수 있는 타입이더라구요.

- 저는 날짜를 다룰 때, `절대값` 형태인 `TimeInterval` 타입으로 다루는 게 좋다고 (개인적으로) 생각하고 있습니다.
그 이유는, TimeZone, 시차에 상관없이 정확하게 같은 날짜/시간을 나타낼 수 있다고 생각하고 있고, 또한 TimeInterval 타입이 `Double 타입`의 Type Alias. 즉, `숫자`이기 때문에 다루기가 편리하더라구요. 😄 

- 그래서 이번에도 Date 타입을 `timeIntervalSince1970` 형태로 바꿔서 `TimeInterval` 타입의 프로퍼티로 구현했습니다.

- ✋🏻 질문드리고 싶은 점은 -> `Firebase` 뿐만 아니라, 통상적인 Remote DB 에서 `날짜 데이터`를 저장할 때는 어떤 타입/형태를 사용하는 게 좋을까요??

<p align="left"><img src="https://user-images.githubusercontent.com/71127966/156431364-9ef309ad-a753-4c3d-9749-a66763fc1a97.png" width="100%"></p>

<p align="left"><img src="https://user-images.githubusercontent.com/71127966/156430807-61439cc5-d71e-42d1-a4eb-ee6ce50821a9.png" width="100%"></p>

2022-03-04 06:30 UTC, GREENOVER requested changes
@Jager-yoo 
스텝2-1 고생하셨습니다 예거!!
전체적으로 일감을 나누고 그에 대해 하나씩 해가니 첫 단추를 아주 잘 끼우고 시작하시는것 같습니다ㅎㅎ
전체적으로 마이너한 코드 리뷰에 대해 남겨봤습니다🙌
한번 쓰윽~ 확인 해보시면 될것 같아요ㅎㅎ
***
### 칭찬 드리고 싶은 부분
- 가벼운 부분도 놓치지 않고 딥하게 고민하는 러닝 💯
- 파일 및 코드를 관심사에 따라 잘 분리하셔서 가독성이 높습니다 💯
- 전체적으로 네이밍이 좋아요 💯
- 혼자 플젝으로 하더라도 SwiftLint, 리드미 최고 💯
***
### 궁금하신 부분에 대한 저의 의견
#### 날짜(dueDate) 프로퍼티의 타입을 무엇으로 지정하는 게 편리할까요?
- 저와 현업은 대부분 우선 Timestamp 타입으로 해당 날짜에 대해 디비값을 정의하고 사용합니다.
Timestamp 타입으로 디코딩하고 필요한 곳에서는 말씀하신대로 Double 이든 String이든 원하는데로 바꿔서 사용합니다.
물론 예거의 말대로 DB에서도 Number로 정의하고 각 클라와 상의한다면 문제가 없겠죠.
그런데 왜 Timestamp를 사용하는것이 권장될까요?
반대로 예거가 생각하는 Number의 장점이 요 세밀한 시간을 요하는곳에서도 장점을 발휘할진 잘 모르겠습니다🤔
Timestamp가 저는 더 간편하고 정확하다고 생각해요.
DB는 iOS만 다루는게 아닌 다른 모든 클라에서도 다루고 또한 DB는 백엔드에서도 관리하고 해당 DB의 필드값을 더 확실하게
볼 수 있어야 한다고 생각해요.
Number로 지정하게 된다면 Timestamp보다 해당 값을 각 클라에서 다루거나 또한 DB에서도 트래킹하거나 보기 불편하지 않을까 생각합니다!
***
고생 많으셨어요ㅎㅎ
다음 스텝으로 가도 크게 문제가 되진 않지만 그래도 수정될 수 있지 않을까 하는 부분도 있어 Request Changes로 남겨보겠습니다!
(예를 들어 에러에 대한 설계가 빠졌다던지...?!)
수정 후 재요청 혹은 머지 요청을 해주세요 ㅎㅎ
화이팅입니다🙌

2022-03-04 06:30 UTC, GREENOVER commented on ProjectManager/ProjectManager/Utility/TaskManager.swift
> +    func changeTaskStatus(target: Task, to status: TaskStatus) {
Task에 관한 메서드들에서 에러가 발생하는 경우는 없을까요?🙋🏻

2022-03-04 06:30 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/ContentView.swift
> +                // let database = Firestore.firestore()
현재 사용되지 않는 주석들은 제거하는게 좋습니다🙋🏻
추가로, 요런 사이드이펙트를 발생시키는 코드는 뷰에 있는것은 지양해야합니다😀

2022-03-04 06:30 UTC, GREENOVER commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +        let doneTarget = taskManager.todoTasks.last!
강제추출을 하지 않고는 안될까요~?🤔

2022-03-04 06:30 UTC, GREENOVER commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +class ProjectManagerTests: XCTestCase {
전체적으로 테스트 코드를 잘 사용하셨네요!
실패에 대한 테스트 검증들도 이뤄지면 더 좋겠습니다🤔

2022-03-04 06:30 UTC, GREENOVER commented on README.md
> +# ⚙️ STEP 2 - 모델 타입 구현
리드미 작성 최고입니다 정말ㅎㅎ

2022-03-04 17:17 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Model/Task.swift
> +    var dueDate: TimeInterval
`Timestamp` 타입으로 정의하면, Firebase 콘솔 또는 내부 코드에서 `dateFormatter` 를 이용한 변환 작업 없이도, 직관적으로 날짜를 확인할 수 있다는 장점이 있습니다!

Timestamp 타입으로 변경했습니다! 😄 
- 해당 커밋 -> https://github.com/yagom-academy/ios-project-manager/pull/81/commits/5204003145220f08af63f8ef3eb9f3fd11ac45c8

Timestamp 타입은 `import Firebase`를 해줘야 사용할 수가 있었습니다.
> 정확하게는 `import FirebaseFirestore` 만 해도 사용할 순 있습니다. 😉

그래서 리팩토링의 영향을 받는 3개 파일(Task.swift, TaskManager.swift, ProjectManagerTests.swift)에서 `import Firebase`를 해줬습니다.

또한 `Date <-> Timestamp` 타입 간의 변환을 하기 위해서 [FirebaseFirestore Framework Reference 
Timestamp](https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/Timestamp)를 참고하여 진행했습니다. 😄 

### 🙋🏻‍♂️ 여기서 다시 질문이 있는데요!

기존에는 `AppDelegate.swift` 하고 `ContentView.swift` -> 이렇게 2개 파일에서만 `firebase` 모듈을 import 하고 있었습니다.
하지만 Timestamp 타입을 사용하기 위해, 3개 파일에 import firebase 를 해줬습니다.

리팩토링 하기 전에 비해서, `firebase 에 대한 의존성`이 프로젝트 여기저기에 많이 추가된 느낌인데요.
Timestamp 타입을 사용하기 위해, 프로젝트 곳곳에 firebase 의존성 부여를 하는 게 괜찮은 걸까요?? 🤔

2022-03-04 17:38 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Model/Task.swift
> +class Task: Equatable {
처음에는 Task 타입을 `구조체`로 선언했는데요!
Task 인스턴스는 id 프로퍼티를 제외하고는 전부 `변경될 수 있는` 프로퍼티더라구요. 😅 

그리고 TaskManager 타입에서 Task 인스턴스를 `수정`하게 되는 메서드를 구현해야 했는데요.
이때, 메서드의 파라미터로 타겟 Task 를 받게 되는데, 만약 Task 가 `값타입`이라면, 아래 캡처와 같이, 타겟의 프로퍼티를 변경해줄 수 없었습니다.

이를 극복하려면 `inout` 을 사용해야 할 것 같았는데요... 그러면 코드가 지저분해질 것 같더라구요. 😢 

![image](https://user-images.githubusercontent.com/71127966/156812523-25c645e8-9482-4d9d-839e-316b6e5d8f50.png)

게다가, 지난 리뷰어 중에서 이런 늬앙스의 조언을 해주신 분이 계세요.

> `값타입`을 사용할 때 `mutating` 키워드가 들어가게 되면(프로퍼티를 변경해야 한다면) -> 그건 값타입을 값타입 답게 사용하지 못하는 것이다. 그럴 거면 차라리 `클래스`를 사용해라.

또한, `Core Data`를 사용하여 Entity 를 만들면, 기본적으로 `클래스`가 나오잖아요?
그래서 모델 타입에 `클래스`를 사용하는 것이 그렇게 어색하게 느껴지진 않더라구요. ㅎㅎㅎ

혹시 제 의견 중에 잘못된 점이나, 그럼에도 `구조체`를 추천하시는 이유가 있다면, 꼭 알려주시면 감사하겠습니다!! 🥺

2022-03-04 17:54 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Utility/TaskManager.swift
> +        tasks.removeAll(where: { $0 == target })
아 ㅎㅎㅎ 저도 이 코드 쓸 때 `removeAll` 메서드 사용이 좀 어색한 것 같다는 생각을 잠깐 했는데.. 😅 
역시 예리하시군요...

제가 removeAll(where:) 메서드를 사용한 이유는, 다른 remove 메서드들은 `index`를 파라미터로 받기 때문에, 제가 삭제할 타겟 인스턴스가 배열에서 어떤 Index 를 갖는지 찾은 뒤에, remove 를 해줘야 하더라구요!

위와 같은 과정이 불필요하다고 생각하던 와중에, `클로저`를 파라미터로 받는 `removeAll(where:)`를 발견하게 됐습니다. ㅎㅎㅎ
만약 변경하게 된다면, 아래와 같은 코드를 써볼 수 있을 것 같은데요, 좀 더 간단하거나 직관적인 코드가 있을까요..? 🤔 

```swift
func deleteTask(target: Task) {
    guard let index = tasks.firstIndex(of: target) else { return }
    tasks.remove(at: index)
}
```

2022-03-04 18:17 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Utility/TaskManager.swift
> +    func createTask(title: String, body: String, dueDate: Date) {
저는 개인적으로 메서드 시그니처가 너무 길지만 않다면(대략 99글자), 한 줄에 적는 편입니다! 😄 
하지만 코멘트 주셔서 정말 감사합니다! ㅎㅎ

아마 이번 프로젝트에서도 `하이브리드(?)`로 진행할 것 같아요!
코멘트 정말 감사합니다. 👍🏻

2022-03-04 18:53 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Utility/TaskManager.swift
> +    func changeTaskStatus(target: Task, to status: TaskStatus) {
아마 파라미터로 `타겟 Task`를 받는 메서드에서는 에러 발생의 가능성이 있을 것 같습니다!
예를 들면, 파라미터로 집어 넣는 Task 인스턴스가, 그 사이에 어떤 이유로 인해 `이미 deinit` 됐을 수도 있으니까요!

이런 경우를 커버하려면, 메서드 내부에서 Task 가 `nil`인지 검사해줘야 할 것 같은데요!
-> 옵셔널 바인딩이 들어와야 하고 -> 파라미터가 `Task?` 가 되어야 할 것 같습니다.

```swift
// target 파라미터가 옵셔널인 Task? 로 들어오게 해서, 내부에서 옵셔널 바인딩 진행
func modifyTask(target: Task?, title: String, body: String, dueDate: Date) throws {
    guard let target = target else {
        throw TaskManagerError.taskIsNil // 여기서 에러 처리를 해볼까요?
    }
    
    target.title = title
    target.body = body
    target.dueDate = Timestamp(date: dueDate)
}
```

이렇게 하려니까 좀 우려되는 점은...
target 파라미터에 `nil`을 넣으라고 만든 메서드가 아닌데, nil 을 넣을 수 있는 선택권(?)이 생긴다는 점입니다.

어차피 해당 메서드가 호출되기 전에, 옵셔널 바인딩이 이뤄질 거라면, 거기에서 에러를 던지는 게 나을까요? 🤔

2022-03-04 18:57 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/ContentView.swift
> +                // let database = Firestore.firestore()
불필요한 주석 제거했습니다!
동시에 `Firebase` 모듈도 같이 제거했습니다. 추후에 필요한 시점에서 다시 import 하겠습니다! 👍🏻

2022-03-04 19:02 UTC, Jager-yoo commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +        let doneTarget = taskManager.todoTasks.last!
테스트 코드 쪽이라서, 조금은 프리하게(?) `암시적 추출 옵셔널`과 `강제 추출`을 사용했습니다. 😅 
각 테스트에 앞서 5개의 Task 인스턴스를 생성하고, 테스트 환경을 통제하고 있기 때문에
`확실하게 nil 이 발생하지 않는 경우` -> 라고 생각했습니다.

그럼에도 `강제 추출`의 사용은 지양하고 옵셔널 바인딩을 해줘야 할까요..?

2022-03-04 19:08 UTC, Jager-yoo commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +class ProjectManagerTests: XCTestCase {
감사합니다! ㅎㅎ
혹시 `실패에 대한 검증`이 구체적으로 어떤 것인지 더 알려주실 수 있을까요??

스텝 2-1 까지 작성한 코드에서, 저는 아직 guard let 과 같은 `옵셔널 바인딩` 조차 한 번도 사용하지 않아서
그렇다할 `실패 경우`가 없었거든요 😢 (그래서 아직 `에러 타입`도 없습니다..)

이런 경우에도 실패에 대한 테스트 코드를 준비해야 할까요??

2022-03-04 23:57 UTC, GREENOVER commented on ProjectManager/ProjectManager/Model/Task.swift
> +    var dueDate: TimeInterval
엇.. 제가 의도와 조금 다르게 전달된것 같아요..!
모델에서 TimeStamp 타입으로 받을 필요는 없습니다.
모델에서는 Date 타입으로 가져가고 DB와 소통하면 됩니다.
예를들어 디코딩 시, 
```swift
sampleDate = try container.decode(sampleDate.self, forKey: . sampleDate)
  .dateValue()
```
대략 이런식으로 Timestamp에 대해 Date 타입으로 변환해줄 수 있습니다🙋🏻
이렇게 된다면 TimeStamp를 쓰기위해 Firebase 라이브러리를 의존한곳(모델 외 다른 부분)에서 더이상 의존할 필요도 없을것 같습니다!

2022-03-05 00:02 UTC, GREENOVER commented on ProjectManager/ProjectManager/Model/Task.swift
> +class Task: Equatable {
아하 뭐가 맞다 틀리다는 아니였습니다!
정말 궁금해서 여쭤봤어요 ㅎㅎ 어떤 의도를 가지고 하셨는지가 저도 궁금해서요~!
답변에 대해 잘 이해했고 확고한 의도와 기준을 가지고 진행한 좋은 방향이라고 생각합니다.
그거와 별개로 저는 mutating 키워드때문에 값타임인 구조체대신 클래스를 택하는것이 더 괜찮은지는 잘 모르겠습니다🤔사실 그거에 깊게 고민을 안해봤었던것 같네요! (저도 고민해보겠습니다😀)
이대로 진행하셔도 좋을것 같습니다!

2022-03-05 00:02 UTC, GREENOVER commented on ProjectManager/ProjectManager/Utility/TaskManager.swift
> +        tasks.removeAll(where: { $0 == target })
맞습니다. 한단계 더 거치는 경향은 있죠.
대신 저는 지금 예시로 보여준 코딩이 적절하다고 생각해요.
else를 타게되면 에러처리들을 해줘야하기에 꼭 필요한 부분이 아닐까 싶구요..!

2022-03-05 00:03 UTC, GREENOVER commented on ProjectManager/ProjectManager/Utility/TaskManager.swift
> +    func createTask(title: String, body: String, dueDate: Date) {
넵!!! 좋습니다ㅎㅎ👍👍👍

2022-03-05 00:06 UTC, GREENOVER commented on ProjectManager/ProjectManager/Utility/TaskManager.swift
> +    func changeTaskStatus(target: Task, to status: TaskStatus) {
아하 설계에 따라 달라지겠지만,
저는 옵셔널로 받고 해당 말씀주신것처럼 else에서 task가 없을때의 에러 처리를 던져줄것 같아요!
물론 예거의 기획 방향도 전혀 문제될거 없고 지금 말씀하신 nil 파라미터 기준권을 본다면 더 맞는 코딩입니다.
이것도 스타일의 차이겠지만 한 부분에서 다 처리를 할 수 있기에 여러 부분 안거치고 그냥 modifyTask만 호출해 그 안에서 내부적으로 해주는게 좀 더 응집도를 높이지 않나 라는 생각을 가지고 처리해주는 경향이 있습니다🤔

2022-03-05 00:07 UTC, GREENOVER commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +        let doneTarget = taskManager.todoTasks.last!
아하 예거의 말씀대로 꼭 해줘야할 필요는 없습니다!
저는 다만 강제추출은 확실하게 발생하지 않는다고 확신해도 휴먼에러라는걸 무시 못하는 경향도 있기에..
테스트 코드여서 문제될건 없지만 습관 자체를 강제추출을 하지 않도록 해주고 있습니다~!

2022-03-05 00:10 UTC, GREENOVER commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +class ProjectManagerTests: XCTestCase {
아하 단순히 제가 말씀드린건 지금 XCTAssertTrue/XCTAssertEqual 과 반대되는 상황을 뜻했습니다.
정말 정말 단순하게 보자면
```swift
func test_Task_인스턴스_5개_생성_검증() {
        let result = taskManager.todoTasks.count
        XCTAssertEqual(result, 5)
    }
```
요 코드에서 result,6 으로 결과값과 기대값을 다르게 했을때 실패도 검증되는지 그런 부분을 의미했습니다~!🙋🏻

2022-03-05 06:31 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Model/Task.swift
> +class Task: Equatable {
넵 ㅎㅎ 의도에 대해 질문하신 것 같아서, 저도 꼼꼼하게 답변 적어봤습니다! 😄 
`클래스`를 선택한 이유에 대해 다시 정리해볼 기회가 됐어요! 리드미로도 잘 옮겨두겠습니다 ㅎㅎ

2022-03-05 06:51 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Model/Task.swift
> +    var dueDate: TimeInterval
아! 이해했습니다 ㅎㅎㅎ
모델에서 `Date` 타입으로 사용하라는 말씀이셨군요!
그러면 나중에 Firebase 로 업로드할 때도, 편리할 것 같아요. 😄 

왜냐면, 지난 번에 연동 테스트했을 때, Date 타입으로 업로드하니까, Firebase 에서는 알아서 `Timestamp` 타입으로 저장되어 있더라구요!
그리고 Firebase 에서 데이터를 가져올 때 다시 Date 타입으로 변환하기 위해, `dateValue()` 메서드를 사용하면 될 것 같구요 ㅎㅎ

알려주셔서 감사합니다!
다시 리팩토링했고, 파일 3개에서 Firebase 의존성도 제거했습니다! 👍🏻  

<img width="624" alt="image" src="https://user-images.githubusercontent.com/71127966/156872104-98cd8197-9468-4c6d-9d3e-3f35e4d4e6eb.png">

2022-03-05 06:53 UTC, GREENOVER commented on ProjectManager/ProjectManager/Model/Task.swift
> +    var dueDate: TimeInterval
제가 전달을 모호하게 해버린 불찰이였는데 이해해주셔서 감사합니다!👍
리팩토링 커밋도 확인했습니다~!👍

2022-03-05 07:21 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Utility/TaskManager.swift
> +        tasks.removeAll(where: { $0 == target })
넵! 리팩토링 진행하면서, `Error 타입` 또한 만들었습니다.
삭제할 대상이 tasks 배열에서 존재하지 않는 경우 에러를 던질 수 있도록 만들었습니다. 👍🏻 

```swift
func deleteTask(target: Task) throws {
    guard let targetIndex = tasks.firstIndex(of: target) else {
        throw TaskManagerError.noTaskFound
    }
    
    tasks.remove(at: targetIndex)
}
```

2022-03-05 07:24 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Utility/TaskManager.swift
> +    func changeTaskStatus(target: Task, to status: TaskStatus) {
말씀해주신 대로 `응집도`를 높이려면, 옵셔널 바인딩을 메서드 외부가 아니라 내부에서 하는 게 낫겠더라구요!
일단 파라미터는 옵셔널을 붙여서 받고, 내부에서 검증하면 되니까요 ㅎㅎㅎ

하여, Task 수정에 관한 아래 2개의 메서드의 target 파라미터에 옵셔널을 붙이고
`내부에서 옵셔널 바인딩하면서 에러도 던질 수 있게 리팩토링`해주었습니다. 😄 

```swift
func modifyTask(target: Task?, title: String, body: String, dueDate: Date) throws {
    guard let target = target else {
        throw TaskManagerError.taskIsNil
    }
    
    target.title = title
    target.body = body
    target.dueDate = dueDate
}

func changeTaskStatus(target: Task?, to status: TaskStatus) throws {
    guard let target = target else {
        throw TaskManagerError.taskIsNil
    }
    
    target.status = status
}
```

2022-03-05 07:28 UTC, Jager-yoo commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +        let doneTarget = taskManager.todoTasks.last!
감사합니다! 테스트 코드에서는 암시적 추출과 강제 추출을 사용하는 방향으로 해보겠습니다. 😉 
대신 이번 리팩토링에서 Task 수정/삭제 메서드들이 전부 `throws` 를 달게 되면서,
테스트 코드에서 `try`와 함께 사용해야 하더라구요.

여기서는 에러가 발생해도 뭔가를 처리해줘야 하는 건 아니라서
`XCTAssertNoThrow`를 사용해서, 메서드가 에러를 던지지 않음 또한 테스트의 일부로 포함시키는 식으로 만들어 봤습니다.
테스트 코드에서는 이 정도만 해두어도 괜찮을까요? 🤔 

```swift
// 아래와 같은 식으로, try 가 붙어야 하는 메서드는 XCTAssertNoThrow 로 감쌌습니다.

func test_Task_status_변경_검증() {
    let doingTarget = taskManager.todoTasks.first!
    let doneTarget = taskManager.todoTasks.last!
    XCTAssertNoThrow(try taskManager.changeTaskStatus(target: doingTarget, to: .doing))
    XCTAssertNoThrow(try taskManager.changeTaskStatus(target: doneTarget, to: .done))
    XCTAssertTrue(taskManager.doingTasks.first! == doingTarget)
    XCTAssertTrue(taskManager.doneTasks.first! == doneTarget)
}
```

2022-03-05 07:51 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Utility/TaskManager.swift
> +        tasks.removeAll(where: { $0 == target })
`수정` 메서드들은 파라미터를 옵셔널인 `Task?`로 받고 -> 내부에서 옵셔널 바인딩을 해주며 에러를 던지게 해놨는데
`삭제` 메서드는 옵셔널로 받지 않고 또 다른 에러를 던지는 게 좀 어색해보이더라구요.

그래서 삭제 메서드도 옵셔널로 받고 내부에서 바인딩하며 `동일한 에러`를 던지도록 만들었습니다!
에러 case 중에서 `noTaskFound`는 삭제했어요!
왜냐면 ... Task 가 배열에서 안 찾아지면.. 그게 곧 `nil` 이라서 그런 거잖아요..?
결국 같은 에러라고 생각하여, 심플함을 위해 하나만 쓰기로 결정했습니다! 😄 

```swift
func deleteTask(target: Task?) throws {
    guard let target = target else {
        throw TaskManagerError.taskIsNil
    }
    
    tasks.removeAll(where: { $0 == target })
}
```

2022-03-05 09:30 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Utility/TaskManager.swift
> +        tasks.removeAll(where: { $0 == target })
자꾸 변경해서 죄송하네요..ㅎㅎ
`removeAll(where:)` 메서드의 단점이 있더라구요.
뭐냐면... 아무것도 삭제하지 않았더라도 에러를 던지지 않는다는 점입니다.

있으면 삭제하고, 없으면 마는.. 그렇게 작동하더라구요.
즉, `에러를 제대로 캐치해줄 수 없다`고 판단하여, 결국 아래와 같은 모습이 됐습니다.

guard문 부분에서 던질 수 있는 에러도, 엄밀하게 구분해줄 필요가 있을 것 같아서
다시 에러 케이스를 2개(taskIsNil, noTaskFound)로 분리시켜두었습니다! 😄 

```swift
func deleteTask(target: Task?) throws {
    guard let target = target else {
        throw TaskManagerError.taskIsNil
    }
    
    guard let targetIndex = tasks.firstIndex(of: target) else {
        throw TaskManagerError.noTaskFound
    }
    
    tasks.remove(at: targetIndex)
}
```

2022-03-05 09:57 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Model/Task.swift
> +class Task: Equatable {
### ⚠️ 모델을 클래스로 구현한 경우의 단점

테스트 케이스 작성 중에 있었던 일을 정리합니다! 😄 

- `이미 삭제된 Task` 를 수정하려고 하면 -> Error 가 발생하는 경우를 테스트하려고 했는데요!
분명 delete 메서드로 삭제를 시켰는데, 수정은 정상적으로 이뤄지는 일이 생겼습니다.
- 확인해보니, `tasks 배열`에서는 삭제가 됐지만, 53번째 줄에서 `지역변수`(let target = ~)로 삭제 대상인 Task 인스턴스를 잡아두었는데요.
이게 해당 인스턴스의 `Reference Count`를 올리기 때문에, 인스턴스가 deinit 되지 않고 메모리에 살아있기 때문이었습니다.

![image](https://user-images.githubusercontent.com/71127966/156877866-b023baa7-bcc4-4cc4-85be-c031920a1561.png)

- 이를 해결하기 위해, 지역변수가 Reference count 를 올리지 않도록 `weak var`를 사용하여 의도한 테스트 결과를 만들어낼 수 있었습니다.
- ✅ 알게된 점 -> **모델로 클래스 타입을 쓰면, 의도치 않게 인스턴스의 Reference count 가 올라갈 수 있습니다.**
즉, dataSource 역할을 하는 배열에서는 사라져있지만, 인스턴스는 살아있는 경우(메모리 누수💧)가 발생할 수 있다는 점을 알게 됐습니다!

![image](https://user-images.githubusercontent.com/71127966/156878033-57afcdf5-4297-4a67-9f8d-832e57f0fc14.png)

2022-03-05 10:01 UTC, Jager-yoo commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +class ProjectManagerTests: XCTestCase {
에러 타입을 추가하고, `메서드가 실패하는 경우(에러 throw)`에 대한 테스트 메서드를 3개 추가했습니다! 👍🏻 

<img width="726" alt="image" src="https://user-images.githubusercontent.com/71127966/156878502-2f4a8f81-5ab7-41ab-ad65-7042a37a0ac1.png">

2022-03-05 10:35 UTC, Jager-yoo commented on README.md
> +# ⚙️ STEP 2 - 모델 타입 구현
리팩토링에 대한 내용도 리드미에 추가했습니다!

2022-03-05 12:24 UTC, GREENOVER commented on ProjectManager/ProjectManagerTests/ProjectManagerTests.swift
> +        let doneTarget = taskManager.todoTasks.last!
네 괜찮습니다 ㅎㅎ
추후 테스트 코드는 계속 리팩토링 되면서 진행될 여지가 있으니 그때그때 개선해보면 좋겠습니다!

2022-03-06 06:49 UTC, GREENOVER approved these changes
주말까지 고생하셨습니다 예거!!
스텝 2-1 이상없이 개선됨을 확인하여 다음 스텝 2-2로 넘어가시죠 ㅎㅎ
마이너한 한가지 코멘트만 남겨두어서 이후 스텝에서 같이 고민해보시죠!
다음 스텝도 화이팅입니다🙌

2022-03-06 06:49 UTC, GREENOVER commented on ProjectManager/ProjectManager/Utility/TaskManagerError.swift
> +    case noTaskFound
다른 케이스를 나타내는건가요?
에러 타입에서 케이스만 보면 같은 Task가 없다는 같은 에러로 보여져서요..!🙋🏻
실제 사용부에서 이해는 갔으나 네이밍이 조금 변하면 어떨까합니다🤔

2022-03-06 06:49 UTC, merged

2022-03-06 10:42 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Utility/TaskManagerError.swift
> +    case noTaskFound
- `TaskIsNil` -> 이건 말 그대로, 메서드 내부에서 옵셔널 바인딩을 했는데 `nil` 이 잡혀서 else문으로 빠지는 경우의 에러입니다!

- `noTaskFound` -> 이건 tasks 배열에서 Task 를 찾을 수 없는 경우인데요!
아래 Task 삭제 메서드에서, `index`를 찾은 뒤, index 를 통해 인스턴스를 삭제하는 로직에서
만약 index 가 없는 경우엔 어떤 에러 처리를 해주지.. 고민하다 `noTaskFound` 케이스를 만들게 됐습니다.

```swift
func deleteTask(target: Task?) throws {
    guard let target = target else {
        throw TaskManagerError.taskIsNil
    }
    
    guard let targetIndex = tasks.firstIndex(of: target) else {
        throw TaskManagerError.noTaskFound // tasks 배열에서 타겟 인스턴스를 찾지 못함
    }
    
    tasks.remove(at: targetIndex)
}
```

하지만 말씀해주신 대로, 둘은 비슷한 속성입니다.. 배열에서 Task 인스턴스를 찾을 수 없다는 말은, 곧 `nil` 이 됐다는 것이니까요 ㅎㅎㅎ
해당 에러 케이스는 제거하고, `삭제` 메서드의 guard문 2개에서는 동일한 에러 케이스를 던지는 것으로 심플하게 가겠습니다!