프로젝트 관리 앱 [STEP 2-1] 차차
yagom-academy/ios-project-manager pull request #82
Opened 2022-03-03 08:46 UTC by ChaminLee

안녕하세요 또치! @TTOzzi 
이번에 MVVM 구조에 대해서 처음 공부해보고 구현해봤는데요! 
처음이다보니 다소 어색한 부분이 많을거라고 생각합니다...
많은 조언 부탁드리겠습니다 🙇🏻‍♂️

디스코드에서 말씀드린 것 처럼 아래 세 단계로 진행해보고자 합니다! 

[UIKIt + MVVM]
- STEP 2-1: model, viewModel 구현
- STEP 2-2: view + 바인딩 구현 

[RxSwift + MVVM]
- STEP 2-3: RxSwift를 이용한 리팩터링

시간이 많진 않겠지만... 말씀주신 것 처럼 우선순위에 집중하여 진행해보겠습니다~!

--- 
## 📱 구조

![image](https://user-images.githubusercontent.com/45652743/156524776-a0172ad3-47e6-4ed5-a97e-e69d7d31a181.png)

대략적인 MVVM 구조의 흐름을 구상해보고 코드 구현을 시작해봤습니다!

## 🔥 고민했던 점

### 1️⃣  MVVM 패턴의 구조

MVVM 구조를 구현함에 있어 View ↔  ViewModel 사이에서 데이터 변화를 관측하고, 스스로 UI를 변경할 수 있도록 하기 위한 방법들에 대해 고민해봤습니다. 

- Observable 구현
    - Rx와 가장 닮아있는 방식이라고 생각했으며 동시에 Rx를 구현하는...? 방법이지 않을까 생각이 들었습니다.
    - 이에 커스텀하게 Observable을 만들 경우, 추후에 operator를 직접 만들어야 하는 경우가 발생할 것 같아서 현재로서는 선택하지 않게 되었습니다.
- Protocol
    - Protocol을 통해 구현하는 방식은 delegate pattern 처럼 동작하고 있다고 생각했습니다.
    - delegate를 할당해주어야 하며, 그나마 delegate pattern은 다른 부분에서 경험해본 방법이어서 이번에는 다른 방법을 사용해보려고 했습니다
- Closure
    - ViewModel내에 closure를 정의하고 호출이 필요한 곳에 위치시켜둔 후, ViewController에서 해당 클로저를 구현하여 작동하는 방식입니다.
    - 여러 자료들을 봤을 때, Rx없이 구현하기에 가장 보편적인 방법이라고 생각했습니다.

그래서 이번에 UIKit+MVVM으로 프로젝트를 구현하기 위해서는 closure 방식을 선택했습니다. 

### 2️⃣  Clean Architecture

MVVM에 대해 공부하다보니 Clean Architecture가 따라오는 것 같아 이를 함께 적용해봤습니다. 

- ViewModel: 화면에 필요한 데이터를 제공하는 역할
- Domain: 앱의 실행에 있어 필요한 비즈니스 로직을 수행하는 역할
- Repository: 데이터를 불러오는 역할

역할들을 나누어, View ↔ ViewModel ↔  Domain ↔  Repository 구조로 구성해보았습니다. 

요구사항에 따라 현재는 memory 기반의 repository가 위치해있지만, 이후에 Local/Remote DB가 올 것을 대비하여 Repository 프로토콜을 구현하여 추상화 해주었습니다. 이러한 추상화를 통해 추후 Remote Repository가 위치했을 때에도 mock Repository를 두어 Domain의 로직을 테스트 할 수 있다는 장점이 있다는 것을 학습했습니다

또한 Domain에 해당하는 `ToDoManager` 의 역할, ViewModel인 `ToDoViewModel` 도 마찬가지로 핵심 역할을 추상화하였습니다.   

### 3️⃣ Unit Test 코드 작성

비즈니스 로직을 담당하는 Domain의 `ToDoManager`의 Unit Test를 진행했습니다. 

현재는 memory 기반의 repository이기 때문에 별도의 mock repository를 두지는 않았으며, 추후 remote repository가 위치하게 될 경우, unit test 코드 또한 변경해주고자 합니다.

## 🤔 궁금한 점

### 1️⃣ MVVM 구조가 잘 구현되어있는지 궁금합니다!

우선은 ViewModel이 로직을 가지지 않도록 하고, Domain이 비즈니스 로직을 가지도록 했습니다. viewModel에서 실제로 사용되는 데이터 배열인 todos를 filtering 하거나, index 위치의 값을 가져오는 행위를 viewmodel이 하고 있는데, 이러한 부분에 있어 문제가 없을지 궁금합니다! (이 또한 비즈니스 로직이라고 보고 Domain으로 분리해야하는 걸까요??)

처음이다보니... 전체적으로 MVVM 패턴에서 model과 viewModel의 구현이 올바르게 되었는지 궁금합니다!

또한 개선할 부분이 있다면 어떻게 개선해 볼 수 있는지 힌트 주시면 감사하겠습니다🙏🏻

### 2️⃣ ViewModel내의 Closure들에 대해

여러 레퍼런스를 찾아보니 viewModel내의 closure는 view가 받아야 할 데이터 혹은 이벤트를 output과 같은 형태로 ViewController에게 전달해주고 있다는 생각이 들었습니다. 그렇다면 어떠한 action에 대한 output이 필요한 경우가 있다면 이를 closure로 모두 정의해두어야 하는 것인지 궁금합니다. 
(ex. 버튼이 hidden되어야 할 때, modal이 올라와야 할 때 등..)

아직 공부해보진 못했지만 이것이 추후 Rx의 Input/Output 구조와 연관이 있을지도 궁금합니다!

---

감사합니다! 🙏

2022-03-04 14:55 UTC, TTOzzi requested changes
안녕하세요 차차~! 🙇 
전체적으로 코드가 깔끔하고 읽기 쉽게 짜여져서 리뷰하기 편하네요!
좋은 구조를 짜기 위해 고민하신 흔적이 보이는 것 같습니다 😊

### 🧐 궁금한 점
> 여러 레퍼런스를 찾아보니 viewModel내의 closure는 view가 받아야 할 데이터 혹은 이벤트를 output과 같은 형태로 ViewController에게 전달해주고 있다는 생각이 들었습니다. 그렇다면 어떠한 action에 대한 output이 필요한 경우가 있다면 이를 closure로 모두 정의해두어야 하는 것인지 궁금합니다.
(ex. 버튼이 hidden되어야 할 때, modal이 올라와야 할 때 등..)

저는 MVVM은 뷰, 뷰모델, 모델의 역할만 명확하게 나눌 수 있다면 어떤 형태로 구현하던 상관없다고 생각해서 이런 질문에 답변드리기가 조금 조심스럽네요 😅 (제가 답변드린 것을 정답처럼 생각하실까봐...)
아무래도 input, output을 명확하게 나눈 구조가 뷰모델을 봤을 때, 이 뷰모델이 어떤 이벤트를 받아 어떻게 처리하고 그 결과를 어떻게 반환하는지 명확하게 파악할 수 있어 보편적으로 많이들 사용하시는 것 같습니다.
action(input)에 대해서 output은 정의하되, 모든 output을 뷰 컴포넌트 별로 따로따로 정의해주기 보단 어느 정도 공통된 부분을 묶어서 처리하는 것 같아요 🤔 
(Rx에서 input/output을 구현하는 것도 비슷해요!)

PR 내용에 남겨주신 설명, 질문 대부분이 남겨드린 코멘트로 해결되었다고 생각하는데요.
혹시나 제가 놓친 부분이 있거나 이해가 어려운 부분이 있다면 말씀해주세요! 🙏 
고생하셨습니다 🙇

2022-03-04 14:55 UTC, TTOzzi commented on ProjectManager/ProjectManager/ViewModel/ToDoViewModel.swift
> +            todos.sort { $0.deadline < $1.deadline }
항상 정렬된 상태의 `todos` 배열이 필요한 것이라면, `todoManager`로 부터 받아올 때 정렬된 배열을 받아오는 게 더 좋을 것 같아요 🤔 
현재 `todos` 배열을 업데이트하는 로직도 항상 `todoManager`를 통해 받아오는 것 같기도 하구요.

2022-03-04 14:55 UTC, TTOzzi commented on ProjectManager/ProjectManager/ViewModel/ToDoViewModel.swift
> +    }
아직 뷰에서 뷰모델을 사용하는 코드가 없어서 이 뷰모델이 어떻게 사용될지 가늠이 잘 안되네요 🤔 
전부 인자로 `ToDo` 타입을 받고 있는데, 뷰에서 `Todo` 정보를 모두 알고있고 `Todo`를 조합해서 뷰모델로 넘겨주는 걸까요? 👀 
이 부분은 뷰모델을 사용하는 부분이 구현되면 좀 더 자세히 피드백 드릴 수 있을 것 같아요.
차차님께서 구현하시면서 구조가 바뀔 수도 있구요 🙂

2022-03-04 14:55 UTC, TTOzzi commented on ProjectManager/ProjectManager/ViewModel/ToDoViewModel.swift
> +    }
`fetch` 메서드를 뷰에서 들어오는 사용자 이벤트(input)이라고 생각하면, 결과값으로 반환되는 output이
```swift
            throw CollectionError.indexOutOfRange
```
와
```swift
        return fetchedTodo
```
로 두 개인 것 같은데요.
`fetch`를 호출하는 곳(뷰)에서 각각 에러를 처리하는 로직(try-catch)을 처리하기 보단, 위에서 클로저로 정의해주신 것처럼 output을 만들어 공통으로 처리해주는 게 좋을 것 같아요.
요건 뷰에서 뷰모델을 사용하는 로직을 구현하면서 어떤 차이가 있을지 좀 더 고민해보아요 🙂

2022-03-04 14:55 UTC, TTOzzi commented on ProjectManager/ProjectManager/ViewModel/ToDoViewModel.swift
> +        }
뷰모델에서 갖고 있는 `todos` 배열이 항상 데이터의 원천과 동일하다는 것이 보장된다면 여기서 이 로직을 처리해도 크게 문제는 없겠으나, 만약 (지금은 구현되지 않았지만)서버에서 데이터를 관리해서 데이터의 원천과 일치하지 않을 여지가 있다면 `todoManager`를 통해 필요한 `ToDo` 정보를 받아오는 게 좋을 것 같아요 🤔

2022-03-04 14:55 UTC, TTOzzi commented on ProjectManager/ProjectManagerTests/ToDoManagerTests.swift
> +        todoManager = ToDoManager(repository: repository)
작성된 테스트가 `ToDoManager`에 대한 독립적인 테스트임을 보장할 수 있을까요? 👀 
지금은 아래의 테스트 케이스가 실패했을 때, `ToDoManager`의 로직이 문제인 것인지 `ToDoRepository`의 로직이 문제인 것인지 확인을 해야할 것 같아요 🤔 
추상화 계층을 나누고, 의존성을 주입해주어 테스트가 가능한 구조를 만들어 주는 것 까진 잘 해주셨으니, 모의 객체를 만들어 단위 테스트를 하는 방법에 대해 찾아보시면 좋을 것 같아요!

2022-03-04 14:55 UTC, TTOzzi commented on ProjectManager/ProjectManagerTests/ToDoManagerTests.swift
> +        XCTAssertEqual(todos[0].state, .waiting)
필요하다면 테스트 target에만 테스트를 위해 `ToDo` 타입에 `Equatable`을 채택하는 코드를 작성해줄 수도 있습니다 🙂

2022-03-04 16:34 UTC, ChaminLee commented on ProjectManager/ProjectManager/Domain/ToDoManager.swift
> +class ToDoManager: ToDoMangeable {
놓치지 않고 `final` 키워드 명시해주도록 하겠습니다!

2022-03-04 16:48 UTC, ChaminLee commented on ProjectManager/ProjectManager/Model/ToDo.swift
> +    let deadline: TimeInterval
추후에 FireStore를 쓸 경우를 고민했었는데요...! FireStore에서는 시간이 `TimeStamp`라는 타입으로 표현된다고 하여 처음에는 raw한 Timstamp의 `.seconds`를 사용하려고 했습니다!

![image](https://user-images.githubusercontent.com/45652743/156804592-2c5b996d-fbb4-438a-beae-c3ad12c0cfdb.png)

문서를 좀 더 살펴보니 `Date` 타입으로 쉽게 변환가능한 메서드가 있어 deadline 또한 `Date` 타입으로 변경하고자 합니다!

2022-03-04 17:03 UTC, ChaminLee commented on ProjectManager/ProjectManager/Protocol/ToDoMangeable.swift
> +    var repository: Repository { get set }
`repository`를 변경하는 일은 없을 것 같습니다..! `get` 만 명시해주도록 하겠습니다!

2022-03-04 17:06 UTC, ChaminLee commented on ProjectManager/ProjectManager/Protocol/ToDoMangeable.swift
> +    init(repository: Repository)
중요한 역할과 책임을 추려내는 것이 추상화의 목적이라고 생각합니다! 

`TaskMangeable`내에 repository 프로퍼티를 넣은 이유는 데이터의 원천인 repository를 알고 있어야 할 것이라고 생각했기 때문입니다! 

생성자의 경우는 repository의 의존성 주입을 생성자 주입 방식으로 강제하고자 넣어주었는데, 굳이 생성자까지는 강제할 필요가 없을 것 같네요! 생성자는 제거해주도록 하겠습니다~!

2022-03-04 17:12 UTC, ChaminLee commented on ProjectManager/ProjectManager/ViewModel/ToDoViewModel.swift
> +    var didSelectTodo: ((ToDo) -> Void)?
넵 맞습니다! 

`didSelectTask`의 경우 `Task`를 넘겨주게 되는데, tableView에서 특정 cell을 터치할 때 세부 화면을 보여줘야 하는 요구사항이 있었습니다. 이 때 세부 정보를 알려주고자 특정한 `Task`를 보내주려고 했습니다!

2022-03-04 17:17 UTC, ChaminLee commented on ProjectManager/ProjectManager/ViewModel/ToDoViewModel.swift
> +    private var todoManager: ToDoManager
헷갈려서 프로토콜(`ToDoMangeable `)이 아니라 매니저를 직접 타입으로 명시해버렸네요... 😢 

toDoManager 이외에도 `TaskManager` 내의 repository 또한 할당 이후 변경되지 않으니 let으로 변경해주도록 하겠습니다!

2022-03-04 17:23 UTC, ChaminLee commented on ProjectManager/ProjectManager/Protocol/ViewModel.swift
> +protocol ViewModel {
`TaskViewModel`로 네이밍을 변경해주었습니다. 

추가적으로 이 프로토콜을 채택하는 타입의 이름은 테이블에 대한 뷰모델이기 때문에 `TaskListViewModel`로 함께 수정했습니다!

2022-03-04 17:24 UTC, ChaminLee commented on ProjectManager/ProjectManager/Protocol/Repository.swift
> +protocol Repository {
말씀주신 것 처럼 명확하지 않은 부분이 있었던 것 같습니다!

`Task-`를 붙여서 `TaskRepository`라고 조금 더 의미를 명확하게 개선해봤습니다!

2022-03-04 17:44 UTC, ChaminLee commented on ProjectManager/ProjectManager/Error/CollectionError.swift
> +    }
해당 프로토콜을 채택해주었습니다~!

2022-03-04 17:48 UTC, ChaminLee commented on ProjectManager/ProjectManager/ViewModel/ToDoViewModel.swift
> +            todos.sort { $0.deadline < $1.deadline }
비즈니스 로직을 담당하는 `taskManager`에서 정렬하여 리턴해주도록 수정했습니다!

```swift
func fetchAll() -> [Task] {
    let tasks = taskRepository.fetchAll()
    return tasks.sorted { $0.deadline < $1.deadline }
}
```

2022-03-07 05:26 UTC, ChaminLee commented on ProjectManager/ProjectManager/ViewModel/ToDoViewModel.swift
> +    }
create의 경우 파라미터를 변경해주었습니다!

다른 update, delete, changeState의 경우에는 현재 view가 데이터를 알지 못하기 때문에, viewmodel의 fetch 메서드를 통해 얻어오고자 했습니다. 이를 통해 특정 Index의 `Task`를 얻어오면 그 때 이를 활용해서 update, delete, changeState에 파라미터로 넘겨주려고 합니다!

2022-03-07 05:32 UTC, ChaminLee commented on ProjectManager/ProjectManager/ViewModel/ToDoViewModel.swift
> +    }
fetch의 경우 특정한 Index의 데이터를 불러오는 역할을 하고 있습니다. fetch를 통해 task를 얻어 update, delete, changeState의 요청을 하기도 하며, tableView의 cellForRowAt 내에 cell의 content를 구성할 때도 fetch를 이용하여 데이터를 얻어오고자 했습니다! 

이에 output을 만드려고 하니 하나의 메서드 안에 두 개의 아웃풋이 생기게 될 것 같아 completion 을 통해 값을 전달해주려고 합니다! 이렇게 구현해도 문제가 없을지 궁금합니다! 

(safe indexing 때문에 생긴 optional을 처리하려다가 에러 반환이나 이와 같은 고민을 하게 된 것 같습니다 😢 )

2022-03-07 05:42 UTC, ChaminLee commented on ProjectManager/ProjectManager/Protocol/ViewModel.swift
> +    func count(of state: ToDoState) -> Int
말씀주신 것 처럼 최대한 view의 관점으로 변경해보았습니다~!

- create -> `createTask(title: String, description: String, deadline: Date)`
- update -> `updateRow(with task: Task)`
- delete -> `deleteRow(with task: Task)`
- changeState -> `move(task: Task, to state: TaskState)`
- fetch -> `task(at index: Int, with state: TaskState, completion: (Task) -> Void)`

2022-03-07 05:48 UTC, ChaminLee commented on ProjectManager/ProjectManager/ViewModel/ToDoViewModel.swift
> +        }
말씀주신 것 처럼 데이터의 원천과 불일치할 경우를 대비하여 `TaskManager`내에 `fetch()` 메서드를 만들어 특정한 `Task` 정보를 받아오도록 수정했습니다~!

2022-03-07 06:42 UTC, ChaminLee commented on ProjectManager/ProjectManagerTests/ToDoManagerTests.swift
> +        todoManager = ToDoManager(repository: repository)
말씀하신 것 처럼 mockRepository를 생성하여 주입해주는 방식으로 수정해보았습니다. 

네트워킹을 할 때는 가짜 네트워킹을 통해 미리 정해진 답을 반환하도록 하는 방식으로 이전에 테스트를 했었는데요! 지금처럼 in-memory일 때는 어떤 식으로 mock 객체 내의 메서드를 구성해야할지 감이 잘 잡히지가 않네요...! 

우선 해당 메서드가 호출되는 횟수를 Int로 측정하는 방식 혹은 동일한 로직을 구현한 mock을 사용하는 것 두 가지가 사용된다고 찾아봤습니다!
([참고링크](https://academy.realm.io/kr/posts/making-mock-objects-more-useful-try-swift-2017/))

생각하기로는 메서드의 호출 횟수를 측정하여 비교하는 것은 CRUD에 대한 테스트의 큰 의미가 없다고 생각되어 동일한 로직을 구현한 mock을 사용하여 테스트해주었습니다. 이렇게 로직은 같지만 mock 객체를 구현하여 주입하게 되면 독립적인 테스트가 되었다고 볼 수 있을까요..?

2022-03-07 06:59 UTC, ChaminLee commented on ProjectManager/ProjectManagerTests/ToDoManagerTests.swift
> +        XCTAssertEqual(todos[0].state, .waiting)
오.. 그렇게도 비교할 수 있군요..! 좀 더 편리하게 비교해 볼 수 있겠네요! 

```swift
extension Task: Equatable {
    public static func == (lhs: Task, rhs: Task) -> Bool {
        return lhs.id == rhs.id &&
               lhs.title == rhs.title &&
               lhs.description == rhs.description &&
               lhs.deadline == rhs.deadline &&
               lhs.state == rhs.state
    }
}
```

위 처럼 테스트 내에서 `Equatable` 프로토콜을 채택하여 인스턴스 간에 `==` 비교가 가능하도록 해주었습니다! 
(테스트 내에서 extension을 구현해도 실제 프로덕션 코드에는 영향이 없음을 확인하였습니다 😄 )

2022-03-07 14:08 UTC, TTOzzi commented on ProjectManager/ProjectManagerTests/Test Doubles/MockTaskMemoryRepository.swift
> +class MockTaskMemoryRepository: TaskRepository {
> 말씀하신 것 처럼 mockRepository를 생성하여 주입해주는 방식으로 수정해보았습니다.
네트워킹을 할 때는 가짜 네트워킹을 통해 미리 정해진 답을 반환하도록 하는 방식으로 이전에 테스트를 했었는데요! 지금처럼 in-memory일 때는 어떤 식으로 mock 객체 내의 메서드를 구성해야할지 감이 잘 잡히지가 않네요...!
우선 해당 메서드가 호출되는 횟수를 Int로 측정하는 방식 혹은 동일한 로직을 구현한 mock을 사용하는 것 두 가지가 사용된다고 찾아봤습니다!
([참고링크](https://academy.realm.io/kr/posts/making-mock-objects-more-useful-try-swift-2017/))
생각하기로는 메서드의 호출 횟수를 측정하여 비교하는 것은 CRUD에 대한 테스트의 큰 의미가 없다고 생각되어 동일한 로직을 구현한 mock을 사용하여 테스트해주었습니다. 이렇게 로직은 같지만 mock 객체를 구현하여 주입하게 되면 독립적인 테스트가 되었다고 볼 수 있을까요..?

이것도 파일이 사라져서.. 요기다 달게요 😢 
지금 구현하신 `MockTaskMemoryRepository`는 이름만 다를 뿐 실제 객체와 동일한 로직을 가진 것으로 보이는데요.
`TaskManager` 가 의존성을 가지는 `TaskRepository` 과의 상호작용이 정상적으로 이루어지는지를 확인하는 것에 중점을 두시면 좀 더 간단하게 테스트를 바꿔볼 수 있을 것 같아요 🤔 
`TaskManager`의 `create`, `update`, `delete`, `changeState` 메서드는 사실상 `taskRepository`의 메서드를 그대로 인자와 함께 호출하는 정도니, `MockTaskMemoryRepository` 내부에 전달된 `task`를 확인할 수 있는 프로퍼티를 `createdTask`, `updatedTask`, `deletedTask` 같은 식으로 하나씩 두고 확인할 수 있을 것 같구요.
`fetchAll`과 `fetch`는 `taskRepository`의 `fetchAll` 메서드 반환값을 활용하니, `MockTaskMemoryRepository` 내부에 반환값이 될 `[Task]` 타입의 프로퍼티를 선언해두고, 생성 시점에 집어넣어줘서 사용할 수 있을 것 같아요.

뭔가 글로 설명하려니 굉장히 장황하네요 😅
간단하게 정리하면! 지금처럼 다른 메서드를 테스트하기 위해 `create`, `fetchAll`를 부르지 않고 테스트할 방법을 생각해보시면 좋을 것 같습니다!

2022-03-07 14:13 UTC, merged