프로젝트 관리 앱 [STEP 2-1] Ari
yagom-academy/ios-project-manager pull request #83
Opened 2022-03-03 21:31 UTC by leeari95

안녕하세요. 라이언(@ryan-son) 🦁 아리(@leeari95)입니다~
ViewModel 까지 구현하고 PR 보내드립니다.
알아보기 쉽도록 UML도 끄적여보았어요...ㅎㅎ
처음에 Rx를 활용해서 ViewModel을 구현해보려고 했는데...
생각처럼 쉽지 않아서 일단 Rx없이 Observable만 구현해서 해보았습니다...
알려주신 RxDataSource도 봤는데, 아직 Rx가 익숙치가 않아서.. 어렵네요. 😅
결국엔 하다가 뇌정지가 와서 직접 구현하는 것으로 방향을 바꾸었습니다.

ViewModel을 각 TableView마다 매핑시켜줄 생각으로 설계를 해보았습니다.
처음이라 부족하겠지만... 잘부탁드리겠습니다🙇🏻‍♀️

## UML

![](https://i.imgur.com/7IRh2qu.png)

## 고민했던 점

> 클린 아키텍처
* 추후에 추가할 저장소인 CoreData나 Firestore를 갈아끼울 수 있도록 기능들을 프로토콜을 활용하여 추상화 시켜보았습니다.
* 클린 아키텍처는 아래 링크를 참고했습니다.
* https://tech.olx.com/clean-architecture-and-mvvm-on-ios-c9d167d9f5b3

> 타입 간단 요약
* `Project`
    * cell에 표시될 요소입니다. 추후 데이터를 쉽게 찾아서 편집할 수 있도록 고유 식별자인 UUID를 추가해주었고, 상태값을 가지도록 status를 추가해주었습니다.
* `MemoryStorage`
    * 배열을 가지고있는 스토리지입니다.
* `MemoryRepository`
    * MemoryStorage를 소유하고 있는 저장소입니다. UseCase와 Storage의 인터페이스 역할을 합니다.
* `MemoryUseCase`
    * 비즈니스 로직이 포함되어있는 타입입니다.
* `ProjectListViewModel`
    * 테이블뷰에 보여줄 Project 배열을 가지고있습니다.
    * View에서 input 메소드를 호출하여 이벤트를 받을때마다 UseCase의 기능을 호출하고 이후 Observable에 값을 할당해주고 있습니다.
    * 직접 설계해둔 Observable은 바인딩 이후 값이 바뀌는 시점에 listener를 호출합니다.

## 궁금했던 것 / 조언을 얻고 싶은 점

* 클린 아키텍처에 맞춰서 제가 만든 타입들이 잘 설계된 것이 맞는지.. 라이언의 의견은 어떠신지 여쭤보고 싶습니다.
* 현재의 ViewModel 구조에서 Rx로 적용해보고 싶은데, 어떤 것부터 손봐야할지 감이 안오네요... 직접 구현한 Observable말고 RxSwift의 Observable을 사용해보려고 했는데... 실패했습니다. 조언이 필요합니다...🥲
* ViewModel도 테스트해보려고 해보았는데... 아직은 기능이 단순해서인지.. 아니면 제가 설계를 이상하게[?] 한건 아닌지.. 
  제대로 한게 맞는지 감이 안잡히네요. 한번 살펴봐주시면 감사하겠습니다!

2022-03-07 17:31 UTC, ryan-son requested changes
아리, 반응형 프로그래밍 세계에 오신 것을 환영합니다. 생소한 개념을 처음 학습해보시고 적용해보시느라 고생 많으셨어요. 

> 궁금했던 것 / 조언을 얻고 싶은 점
> 클린 아키텍처에 맞춰서 제가 만든 타입들이 잘 설계된 것이 맞는지.. 라이언의 의견은 어떠신지 여쭤보고 싶습니다.

이미 회의실에서 이야기 나눈 바와 같이, Clean architecture에서 사용되는 용어들을 활용하고 있지만, 약간 어색한 점들이 있기는 합니다. 예를 들어, Repository와 Storage가 동일한 프로토콜 요구사항과 구현 내용을 가지고 있는 점이 있네요. 자세한 내용은 이야기 나누었으니 리팩토링을 거친 후에 다시 이야기해보면 좋을 것 같습니다.

> 현재의 ViewModel 구조가 적절한 구조인지 라이언의 조언이 필요합니다...🥲

- `ViewModel` 입장에서 input과 output을 다시 생각해보고, 어떤 것을 View로부터 받아야 useCase로 잘 전달해줄 수 있을지, useCase에서 받은 내용을 어떤 방식으로 View에 전달할 수 있도록 발행(publish)할 수 있는지 고민해보신다면 현재 구조에서 어떻게 변경해야할지 답이 나올거에요. 개별 코멘트도 한 번 참고해보세요~

> ViewModel도 테스트해보려고 해보았는데... 아직은 기능이 단순해서인지.. 아니면 제가 설계를 이상하게[?] 한건 아닌지.. 제대로 한게 맞는지 감이 안잡히네요. 한번 살펴봐주시면 감사하겠습니다!

- `ViewModel`을 리팩토링한 후 이야기 나누면 더 좋을 것 같아요. 미리 간략하게만 이야기하면 Mock 형식의 UseCase를 구현하여 ViewModel에 주입한 후 onNext 이벤트를 통해 각 subject에 이벤트를 전달하면 원하는 동작이 바인딩되어 잘 수행되는지 확인해보면 될 것 같네요. 

회의실에서 이미 아래 내용들에 대해 이야기 나누어 보았으니, 아래 질문들은 회고에 활용해보시면 좋을 것 같습니다.

## 좋았던 점
- 구조가 Clean architecture에 기반해 나뉘어 있어 탐색하기 편했습니다.
- Clean architecture를 학습해보시고 적용을 도전해본 점
- 단위 테스트를 고려하여 테스트 가능한 구조로 설계하고 구현하신 점

## 질문
1. Repository가 Data layer에서 떨어진 이유?
2. memory의 의미?
3. Memory storage, memory repository의 용도?
4. 희망 RxSwift 활용 정도
5. CUD 시 completion을 사용하는 이유
6. ViewModel의 input/output 기준?
7. XCTAssertTrue를 선호하는 이유

## 보완할 수 있는 점
1. 한 요소를 표현하는 엔티티는 하나가 아니어도 됨. 엔티티 분리 Network (DTO) / CoreData / Domain
2. 테스트 메서드명 보완
3. MemoryStorage 보다 더 명확한 이름 (역할을 기반으로 - 이 앱의 메모리스토리지는 향후에도 이 친구 하나일까?)
4. Filter.first < first(where:) / id값이 있으므로 indices를 살필 필요 없지 않은가?
5. RxSwift 사용 시 Completion 대신 대안 활용 가능 (여기에선 Single이 적합해보임)
6. Repositoryable, Storageable, UseCase보다 적합한 이름 찾기 (명사형도 하나의 옵션)
7. Input도 Output처럼 메서드보다는 스트림 형식으로 전달되는 것이 적절하지 않을까요?
8. 접근제한 설정

그럼 계속해서 화이팅입니다! 💪 궁금한 점 있으시면 언제든지 말씀해주세요~ 😉

2022-03-07 17:31 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Presentation/ViewModel/ProjectListViewModel.swift
> +        }
Subject 요소들을 잘 정의하고, 생성자에서 바인딩해준다면 이 메서드들은 제거할 수 있을 것 같아요.

2022-03-07 17:31 UTC, ryan-son commented on ProjectManager/ProjectManagerTests/MemoryUseCaseTests.swift
> +    var sut = MemoryUseCase()
1. 프로토콜을 통해 추상화를 해주었으니 최대한 활용해보는 것도 나쁘지 않겠어요.
```swift
var sut: UseCase?
```
2. 각 테스트 케이스(메서드) 실행 전후로 sut 인스턴스를 동일하게 초기 상태로 만들어주기 위해 `setUpWithError()`, `tearDownWithError()`를 활용해볼 수 있을 것 같아요.

2022-03-07 17:31 UTC, ryan-son commented on ProjectManager/ProjectManagerTests/MemoryUseCaseTests.swift
> +    func test_create_3() {
given, when, then 기반으로 Behavior Driven Development (BDD) 방식을 취했으니 해당 내용으로 메서드 이름을 지어준다면 그 자체가 해당 타입의 기능 명세가 될 수 있겠네요. 어떤 테스트를 통해 어떤 기능을 검증하는 것인지 알아볼 수 있도록 더 명확한 메서드 이름을 지어주는 것이 좋겠어요.

2022-03-07 17:31 UTC, ryan-son commented on ProjectManager/ProjectManagerTests/MemoryUseCaseTests.swift
> +        let newProject = Project(id: project.id, title: "수정", description: "수정 내용", date: Date(), status: .doing)
여러 프로젝트 인스턴스가 존재하는 상태에서 특정 id를 가지는 인스턴스를 수정하였을 때 해당 id를 가진 인스턴스가 수정됐다는 것을 검증해보는 것도 의미 있을 것 같아요.

2022-03-07 17:31 UTC, ryan-son commented on ProjectManager/ProjectManagerTests/MemoryUseCaseTests.swift
> +        XCTAssertTrue(sut.fetch().count == 1)
`XCTAssertEqual(_:_:)`보다 `XCTAssertTrue(_:)`를 선호하시는 것 같네요. 이유가 있나요~? 순전히 취향이라 무엇이 더 좋다, 맞다 같은 개념은 아니라는 것을 먼저 말씀드려요!

2022-03-08 07:02 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Data/Repositories/MemoryRepository.swift
> +final class MemoryRepository {
VolatileRepository 라는 이름은 어떨까요??

2022-03-08 07:04 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Data/Storages/MemoryStorage.swift
> +        completion?(item)
단순히 사용하기 편리해서 completion을 정의해주었는데, 저번에 회의실에서 추천해주셨던, completion을 대체할 수 있는 Single 타입으로 모두 리팩토링 진행하였습니다!

2022-03-08 07:05 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Data/Storages/MemoryStorage.swift
> +            .filter { projects[$0].id == item.id }.first
오.. 그렇네요 한번 이부분도 추가해보도록 하겠습니다!
의견 감사합니다! 😁

2022-03-08 07:05 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Data/Storages/Storageable.swift
> +protocol Storageable {
하하.. 네이밍은 언제나 어렵네요. 다시한번 고민해보도록 할게요 😅

2022-03-08 07:10 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Domain/Entities/Project.swift
> +    }
라이언이 적어주신 방식과 별 차이는 없지만, struct의 경우 따로 init을 적지 않아도 기본 이니셜라이저가 생성되는 것으로 알고 있습니다.
그래서 기본 이니셜라이저를 사용함과 동시에 extension으로 init을 추가하여 기본 이니셜라이저 말고도 추가된 이니셜라이저가 있다는 것을 의미하기 위해서 저런식으로 코드작성을 했던 것 같습니다.

2022-03-08 07:14 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Extensions/Date+extension.swift
> +        let calendar = Calendar.current
오.. 전혀 몰랐어요!
찾아보니까,
`currnt`를 사용한 캘린더는 설정에서 캘린더 종류를 바꿔도 적용되지 않고,
`autoupdatingCurrent`의 경우는 적용이 된다고 하네요.
따라서 아이폰에서 설정되어 있는 달력을 기준으로 값을 리턴할 수 있도록 이부분을 고쳐보아야겠어요.
감사합니다

2022-03-08 07:17 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Presentation/ViewModel/ProjectListViewModel.swift
> +    var errorMessage = PublishSubject<String>()
이부분... 개선해보려고 했는데... 감이 잘안잡히네요 ㅠㅠ 제가 원하는 방식으로 구현할 수 있을지 모르겠어요.
inserted외에 updated는 두가지 요소가 필요한데요.. (업데이트한 프로젝트타입, 인덱스패스) 
이 경우에는 값을 어떻게 바인딩 해주어야할지.... 감이 잘 안잡혀요. 도와주세요 🥲

2022-03-08 07:19 UTC, leeari95 commented on ProjectManager/ProjectManagerTests/MemoryUseCaseTests.swift
> +    var sut = MemoryUseCase()
초기 상태로 만들어주지 않아도 테스트에는 지장이 없어서 일부로 빼두었었는데요.
이 부분도 저번에 온라인 리뷰 듣고 개선해보았습니다. 의견 감사합니다~ 😁

2022-03-08 07:20 UTC, leeari95 commented on ProjectManager/ProjectManagerTests/MemoryUseCaseTests.swift
> +    func test_create_3() {
제목은 간단할 수록 좋을 거 같다는 제 생각은 큰 오산이였네요 ㅋㅋㅋ
제가 생각해도 저 제목은... 애매한 것 같아요. 라이언 의견 듣고 테스트케이스 제목도 개선해보았습니다.
given, when, then 기반으로 이름을 지으니 수월했어요!
꿀팁 감사합니다 😊

2022-03-08 07:20 UTC, leeari95 commented on ProjectManager/ProjectManagerTests/MemoryUseCaseTests.swift
> +        let newProject = Project(id: project.id, title: "수정", description: "수정 내용", date: Date(), status: .doing)
네! 이부분도 추가하여 개선해보았습니다!

2022-03-08 07:21 UTC, leeari95 commented on ProjectManager/ProjectManagerTests/MemoryUseCaseTests.swift
> +        XCTAssertTrue(sut.fetch().count == 1)
이유가 특별하게 있는 것은 아니지만, 취향인 것 같습니다.
Equal보다 True가 읽기 더 편해보여서.. 였습니다 😄

2022-03-08 07:27 UTC, leeari95 commented on ProjectManager/ProjectManager/Sources/Data/Storages/MemoryStorage.swift
> +            .filter { projects[$0].id == item.id }.first
그리고 filter.first의 경우 인덱스 값이 필요한 상황이여서. firstIndex로 대체하였습니다. 감사합니다 😁

2022-03-09 07:26 UTC, leeari95 commented
안녕하세요. 라이언🦁
일단 수정하는데까지 리팩토링 진행해보았는데...
리팩토링 하면서 ViewModel 부분 메소드 대신 스트림 형식으로 개선해보려고 하는데,
약간 이해 안되는 점이 있어서... 질문 남겨봅니다.🥲

## 수정사항

-  테스트 메서드명 보완
-  Memory보다 더 명확한 이름으로 개선
-  Completion 대신 RxSwift로 활용하여 개선
-  Repositoryable, Storageable, UseCase보다 적합한 이름 찾기

## 질문

### Input도 Output처럼 스트림 형식으로 개선해보기 실패
- 예를 들어 뷰에서 '프로젝트를 수정하겠다' 라는 이벤트를 주는 동시에 해당하는 indexPath와 수정된 데이터인 Project 타입을 전달해주어야 하는데, 이 부분을 어떤식으로 바인딩을 해주어야 하는지 감이 오질 않습니다.
	- 그러니까 ViewModel을 init 하는 동시에 바인딩을 어떤식으로 해주어야 하는지...가 전혀 감이 안잡히네요. 메소드로 해주던 기능을 어떻게 Stream 형식으로 전달해줄 수 있는지.. 조언좀 부탁드립니다.

### Single로 리팩토링 하면서 발생한 테스트 코드 경고문제
- 기존에 Completion으로 데이터를 반환하던 부분을 Single을 활용해서 바꾸어 주었는데, Test코드를 확인해보니 반환값을 사용하지 않는다는 경고문이 뜹니다. 이 부분을 어떻게 개선해볼 수 있을까요..? 
	- Test 관련해서 검색해보았는데, RxTest나 RxBlocking을 활용해서 테스트 코드를 작성하는 것 같은데... 아직 Rx도 완벽하게 이해하지 못하는 상황에서 Test코드 까지 생각하려니까 좀 벅찬 느낌이네요... 😭

### DateFormatter에 대한 성능이슈
- DateFormatter에 대한 성능이슈에 대한 링크 주신 부분 잘보았습니다. 감사합니다! 그러면, extension 부분을 static하게 바꾸어주어야 할까요? 아니면... 따로 싱글턴 객체를 만드는 것이 좋을까요? 어떤게 좋은 방법인지 잘 판단이 안서네요. 이 부분도 이야기 같이 나눠주셨으면 합니다!

### 이외 네이밍 개선 부분
- 네이밍을 일단 개선해보긴 했는데, 정말 이름 짓기가 어렵다고 느껴지네요. 어려운 이유가 일단 아직 MVVM 구조 자체 완벽한 이해가 부족한 것 같아서 더 그런 것 같습니다. 한번 살펴봐주시면 감사하겠습니다.

2022-03-10 04:22 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Data/Repositories/MemoryRepository.swift
> +final class MemoryRepository {
타입이 어떤 특징을 가지고 있는지 설명하는 것도 나쁘지 않지만 어떤 역할을 수행하는지 (어떤 엔티티를 관리하는가? 등)에 대한 설명을 추가해서 이름을 지어보는건 어떨까요?

2022-03-10 04:24 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Data/Storages/MemoryStorage.swift
> +        completion?(item)
이 메서드가 반환한 Single은 어떤 타입에서 누가 구독해서 이용하나요? 계획이 궁금합니다~

2022-03-10 04:26 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Domain/Entities/Project.swift
> +    }
현재 작성하신 내용을 보면 `date`는 주입 받은 인스턴스를 사용하지 않고 항상 `Date()`를 사용하고 있네요!

2022-03-10 04:27 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Extensions/Date+extension.swift
> +        let calendar = Calendar.current
어제 이야기 나누어본 내용이네요. 적용하는 상황에 맞게 사용해봅시다~ 😉

2022-03-10 04:28 UTC, ryan-son commented on ProjectManager/ProjectManager/Sources/Presentation/ViewModel/ProjectListViewModel.swift
> +    var errorMessage = PublishSubject<String>()
어제 이야기 나누어본대로 이번에는 `RxCocoa`를 이용해 테이블뷰를 바인딩하기 용이한 일반적인 구조로 적용해봅시다~!

2022-03-10 04:31 UTC, ryan-son commented on ProjectManager/ProjectManagerTests/MemoryUseCaseTests.swift
> +        let newProject = Project(id: project.id, title: "수정", description: "수정 내용", date: Date(), status: .doing)
이벤트를 발행하는 인스턴스라면 구독을 통해 수신한 값을 검증하는 형태로 수행하면 됩니다~!

2022-03-10 04:44 UTC, ryan-son commented
아리, 고생 많으셨습니다! 지금은 UI 요소가 없는 상태에서 Rx를 다루다보니 생소하게 느껴질 수 있지만, 프로젝트를 진행해 나가시면서 더 친숙해지실 거에요. 질문해주신 내용은 개별 코멘트와 아래 내용을 참고해보세요.

> ### Input도 Output처럼 스트림 형식으로 개선해보기 실패

- 어제 회의실에서 이야기 나누어본대로, `Project` 배열을 다루는 Subject를 마련해보시면 방향성이 보일거라고 생각합니다!

> ### Single로 리팩토링 하면서 발생한 테스트 코드 경고문제

- 누가 이 반환값을 무엇을 위해 활용할 것인지 고민해보는 것이 선행되어야할 것 같아요. 테스트에서도 활용하지 않는다면 무엇을 위해 반환하는지 고민해봅시다.
- 반환값을 활용하지 않는다면 `@discardableResult` 어노테이션을 활용해볼 수 있습니다. 

> ### DateFormatter에 대한 성능이슈

- 이야기 나누어 본 부분이네요. 이 내용은 제가 링크 달아드린 내용들처럼 의견이 분분하니 자신만의 기준을 잡는 것이 중요하다고 생각해요. 생성 비용이 걱정된다면 공식문서에서 thread safety를 보장한다고 밝히고 있으므로 공용 인스턴스를 마련해서 사용해도 되겠습니다. 그렇게 생각하지 않는다면 기존 방식을 계속 이용하시면 되겠습니다.

다음 스텝에서 만나요~~ 화이팅 ! 💪

2022-03-10 04:44 UTC, merged