프로젝트 관리 앱 [STEP 2-1] 아샌, 앨리
yagom-academy/ios-project-manager pull request #87
Opened 2022-03-07 14:07 UTC by Allie-e

안녕하세요. 찰리! 👾 @kcharliek
아샌(@ICS-Asan), 앨리(@Allie-e)입니다. 

지난 번 말씀 드렸던 STEP2-1 UI 구현이 완료되어 PR 올립니다! 

이번에도 리뷰 잘 부탁드려요!  🙏🏻

감사합니다!!

# 💻  구현 내용

### < CellManagable프로토콜 구현 >

> custom cell을 등록하고 재사용하기 위해서는 identifier을 만들고 관리할 필요가 있었습니다.
identifier는 String 타입이라 하드코딩이 될 것 같다고 판단하여 초기에는 타입 프로퍼티로 `static let identifier = String(describing: ProjectListCell.self)`를 가지고 있었습니다.
전역으로 상수를 만들어 놓는 것 보다 더 간편한 방법을 생각하다가 프로토콜 기본구현으로 번거로운 작업을 처리하는 방법을 생각해냈습니다.
그래서 `register` 메서드의 경우에는 사용하고자 하는 cell의 클래스만 입력하면 간단하게 cell을 등록할 수 있게 하였습니다.
그리고 `dequeueReusableCell` 메서드에서 `register`메서드에서 사용되는 identifier의 형태와 동일하게 넣어주고 입력받은 cell의 타입으로 타입캐스팅을 하는 과정까지 포함하여 구현하였습니다.
이러한 과정을 통해 identifier를 따로 생성할 필요 없이 사용하고자 하는 cell의 클래스만으로 조금 더 간결하게 사용할 수 있게 되었습니다.
> 

### < ProjectListTablaView/HeaderView의 재사용 >

> 지난 PR이후 같이 얘기를 나누면서 공통된 부분은 재사용할 수 있게 구현하여 사용하면 편할 것 같다는 생각을 했습니다.
먼저 `ToDo`, `Doing`, `Done`의  목록들이 같은 형태의 TableView에서 내용이 각기 다른 모습을 취하고 있다고 판단했습니다.
그래서 `ProjectListTableView`를 구현한 뒤 `MainViewController` 에서 3개의 테이블 뷰를 만드는데 사용하였습니다.
그리고 `dataSource`를 담당하는 클래스는 각각 구현한 뒤 채택해 주었고, `delegate`의 경우에는 cell선택시 화면전환이 필요하고 `delegate` 메서드는 공통으로 구현할 수 있다고 생각해서 `ViewController`에 채택하여 구현하였습니다.
`TableView`의 `HeaderView`의 경우에도 같은 형태에 `title`만 다르기 때문에 공통적인 부분을 구현한 뒤 이니셜라이저에서 `title`을 받도록 하여 각각 다른 `title`을 가진 `HeaderView`를 생성 및 사용할 수 있도록 구현하였습니다.
> 

### < ProjectFormView의 재사용 >

> 이 부분도 지난번에 말씀드린대로 지난 프로젝트에서 겪은 단점들로 인해 공통뷰를 구현한 뒤 각 ViewController에 얹는 식으로 구현을 해봤습니다.
이러한 방법으로 구현을 하니 뷰 자체를 구성하는 코드만 따로 구현할 수 있었습니다.
그리고 아직은 데이터가 존재하지 않아 구현하지는 않았지만 뷰의 내용을 다루는 코드를 구분할 수 있어 관리하기도 편하고 가독성 측면에서도 더 좋다는 것을 느끼게 되었습니다.
> 

## 🔫 Trouble Shooting

### < Cell 사이의 간격 설정 >

`문제` TableView의 Header의 크기를 설정해도 간격이 줄지 않는 문제가 있었습니다.

![image](https://user-images.githubusercontent.com/83864058/157048606-0460c7e5-5b8b-4d81-9900-5a56aced205c.png)

```swift
// DataSource/Delegate
func numberOfSections(in tableView: UITableView) -> Int {
    return 30
  }

func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
    return 7
}
```

`해결` TableView의 style을 `grouped`로 하면 header, footer 공간이 자동으로 생성되어서 사용하지 않을 부분을 nil로 설정해주고 tableView의 `sectionFooterHeight/sectionHeaderHeight`를 `0`으로 설정해주는 방법으로 해결했습니다.

![image](https://user-images.githubusercontent.com/83864058/157048651-2427f356-808b-4ce4-a900-6feaf8c00923.png)

```swift
// DataSource/Delegate
func numberOfSections(in tableView: UITableView) -> Int {
    return 30
}

func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
    return 7
}

func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
    let view = UIView()
    view.backgroundColor = .systemGreen
    return view
}

func tableView(_ tableView: UITableView, viewForFooterInSection section: Int) -> UIView? {
    return nil
}

// TableView Initializer
init(title: String) {
    super.init(frame: .zero, style: .grouped)
    sectionFooterHeight = 0
    backgroundColor = .secondarySystemBackground
}
```

### < Button에 Action이 등록되지 않는 문제 >

`문제` Button 생성시 action을 등록해도 의도한대로 작동하지 않는 문제가 있었습니다.

```swift
private let addButton: UIBarButtonItem = {
	let button = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(tabAddButton123))
	
	return button
}()
private func setupNavigationBar() {
    navigationItem.title = "Project Manager"
    navigationItem.rightBarButtonItem = addButton
}

@objc func tabAddButton123() {
    print("눌림")
    present(AddViewController(), animated: true, completion: nil)
}
```

`해결` Button이 생성되는 시점이 문제가 되지 않을까 라는 의문에서 두가지 방법을 해봤는데 둘다 정상작동하는 것을 확인했고 두번째 방법인 navigationItem에 넣을 시점에 생성해서 할당하는 방식으로 수정해주었습니다.

1. addButton을 `lazy var`로 선언
    
    ```swift
    private lazy var addButton: UIBarButtonItem = {
    	let button = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(tabAddButton123))
    	
    	return button
    }()
    ```
    
2. navigationItem에 넣을 시점에 생성해서 할당
    
    ```swift
    private func setupNavigationBar() {
        navigationItem.title = "Project Manager"
        navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(tabAddButton123))
    }
    ```
    

### < NavigationBar 넣기 >

`문제` 할일을 추가하고 수정하는 화면을 구현할 때 navigationBar를 넣어주는 방법을 아래와같이 고민해보았습니다.

`해결`

- **방법1** : NavigationController 생성 후 해당 컨트롤러로 모달로 띄우는 방법 (실패!)
    - NavigationController의 View를 만들어 놓은 View로 할당
    - 화면은 뜨지만 NavigationBar가 나타나지 않는다
- **방법2** : 기존 ViewController에 NavigationBar 만들어서 넣기(without AutoLayout) (실패!)
    - 기존 크기만큼 뷰는 생기지만 위에 빈 공간이 생긴 채 아래에 생긴다
        
![image](https://user-images.githubusercontent.com/83864058/157048758-428ef24e-d80e-42e2-b41e-39cfd9272f85.png)
        
![image](https://user-images.githubusercontent.com/83864058/157048786-58e34020-fd47-435a-a449-5b510ef9f317.png)
        

 - `navigationBar.translatesAutoresizingMaskIntoConstraints = false`를 주면 뷰는 나오지만 NavigationBar는 나오지 않았다
      
  
![image](https://user-images.githubusercontent.com/83864058/157048994-dae102c0-a0cb-4f25-b52d-b9e03cd52daa.png)

        
- **방법3** : 기존 ViewController에 NavigationBar 만들어서 넣기(크기 지정해서 생성) (실패!)
    - width를 view의 width에 맞췄지만 절반만 나왔다
        
        ```swift
        let navigationBar = UINavigationBar(frame: CGRect(x: 0, y: 0, width: view.frame.size.width, height: 50))
        ```
        
![image](https://user-images.githubusercontent.com/83864058/157049337-589afd7d-6650-4408-9c7b-bcc61d69e4af.png)

        
- **방법4** : 사이즈를 zero로 시작한 다음 AutoLayout으로 크기를 지정 `성공!`
    - navigationBar의 leading, trailing, top을 view와 맞춰주었더니 해결되었습니다!
        
        ```swift
        let navigationBar: UINavigationBar = {
            let navigationBar = UINavigationBar(frame: .zero)
            navigationBar.translatesAutoresizingMaskIntoConstraints = false
            ...
            return navigationBar
        }()
        
        //NavigationBar x축 위치 모호하다는 에러 발생
        view.addSubview(navigationBar)
        navigationBar.widthAnchor.constraint(equalTo: view.widthAnchor).isActive = true
        navigationBar.heightAnchor.constraint(equalToConstant: 50).isActive = true
        navigationBar.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        
        view.addSubview(addView)
        addView.translatesAutoresizingMaskIntoConstraints = false
        addView.topAnchor.constraint(equalTo: navigationBar.bottomAnchor, constant: 5).isActive = true
        
        // 에러 없이 정상 작동
        view.addSubview(navigationBar)
        navigationBar.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
        navigationBar.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
        navigationBar.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        ```
        

### < Cell을 long press 했을 때 발생한 에러 >

`문제` 셀을 꾹 눌렀을 때 아래와같은 로그가 찍혔습니다.

![image](https://user-images.githubusercontent.com/83864058/157049373-883bd168-cc76-4d5f-b552-66025fc97c28.png)

cell을 long press 했을 때 print 찍어 확인해 본 결과 두번 눌린다는 것을 확인했습니다.

```swift
@objc func presentToDoLongPressMenu(_ longPresss: UILongPressGestureRecognizer) {
     print("longPressTest")
}
```

![image](https://user-images.githubusercontent.com/83864058/157049406-59ac122b-7bd9-454a-9f8c-49fec77426fa.png)

`해결` 원하는 시점에 longpress에 대한 action을 하도록 조건문 내부로 코드위치를 수정해주었습니다.

```swift
if longPresss.state == .began {
    let alert = makePopoverAlert(with: sectionTitles)
    alert.popoverPresentationController?.sourceView = doneTableView.cellForRow(at: indexPath)
    present(alert, animated: true)
}
```

꾹 누르면 `.began` , 누른채로 커서를 움직이면 `.changed`, 클릭 끝난 시점 `.ended` !

## ❓   질문할 내용

### < Cell 선택후 해제 방법 >

셀을 눌렀을 때, `didSelectRowAt()` 메서드가 호출되면서 select된 상태로 머물러 있는데 수정화면을 내렸을 때와 다른 섹션(Doing, Done)의 셀을 선택했을 때 기존에 select 된 상태를 해제해주고싶었습니다.

가장 이상적인 시점은 선택된 채로 있다가 수정화면이 내려가면 deselect되는 것이라 생각했습니다.
하지만 EditViewController가 Modal로 띄워지고 화면 전체를 가리는 것이 아니라 ViewLifeCycle에 관련된 메서드는 호출되지 않아 정확히 원하는 시점에 deselect되도록 만드는 것이 어려웠습니다.

그래서 저희가 고민하면서 나름의 대안으로 생각한 것이 아래의 2가지  [...]

2022-03-08 14:38 UTC, kcharliek commented
## 고민하신 내용에 대해

1. Cell 사이의 간격 설정 

Row가 아닌 Section을 N개로 설정하고, header로 spacing을 처리한 것으로 이해했습니다. 분명 좋은 아이디어이고요. 저도 방법이 도무지 없을 때 사용한 경험이 있는 스타일입니다. 우선 이 아이디어를 생각해내셨다는데에 잘했다는 말씀을 드립니다.

하지만 논리상으로 Grouping을 생각해보았을 때 Section은 1개가 맞습니다. 그러므로 Row로 관리하는 것이 정석이라고 할 수 있습니다.
그렇다면 Spacing을 구현하면서 Row로 처리하는 방법은 무엇일까요. Spacing을 Cell 안에 그리면 됩니다 ..! Cell 하단에 LineView같은 것을 두는 것 입니다. 그렇다면 사용자에게는 Spacing처럼 보이게 되겠죠. 실제로 이렇게 많이 개발합니다.

다른 방법으로는 별개의 SpacingCell을 두는 방법입니다. 자주 사용하지는 않지만, 고민해볼 수 있는 방법입니다. 단점으로는 numberOfRow계산이 복잡해진다는 것이 있습니다.

이외 내용에 이견없습니다. 잘해주셨어요~!

2022-03-08 14:45 UTC, kcharliek commented
## 질문 내용에 대해

Cell 선택후 해제 방법

저도 말씀하신 두가지 방법 모두 사용합니다. 그런데 대부분 바로 deselect를 했던 것 같습니다. (이건 취향의 문제입니다, 개발과는 관련없습니다.)
두 번 째의 지연 deselect하는 방법은 RxSwift를 이용한다면 actionAfterDismiss 를 Observing하는 식으로 해서 처리할 수도 있겠네요. closure방식도 그다지 억지스러워 보이지 않습니다. 한번 가능한데로 구현해보시죠~~

2022-03-08 14:49 UTC, kcharliek commented on ProjectManager/ProjectManager/Controller/MainViewController.swift
> +    private let toDoDataSource = ToDoDataSource()
UITableViewDataSource 구현을 별도 객체로 분리하셨군요!
이러한 방식이 분명 장점이 되는 경우가 있습니다.
이렇게 분리하는 것이 정말 유익한지 한번 고민 해봐주시고요. 제 별도 코멘트는 마지막 완성 시점에 다시 드리겠습니다.
좋은 경험이 되실 것 같네요 :)

2022-03-08 14:51 UTC, kcharliek commented on ProjectManager/ProjectManager/Controller/EditProjectViewController.swift
> +            navigationBar.leadingAnchor.constraint(equalTo: view.leadingAnchor),
코드로 UI개발 편-안하네요👍

2022-03-08 14:56 UTC, kcharliek commented on ProjectManager/ProjectManager/View/ProjectFormView.swift
> +    required init?(coder: NSCoder) {
여기도 채워주면 좋을 것 같습니다. 누군가 인터페이스빌더로 개발하고 싶을 수도 있으니까요.

2022-03-08 14:58 UTC, kcharliek commented on ProjectManager/ProjectManager/View/ProjectListCell.swift
> +    func setupLabelText(title: String, preview: String, date: String) {
접근제어자에 따른 메서드 배치 순서에 대해 고민하신 부분이 있을까요.
internal level이 private보다 아래에 있는 것에 대해 의도하신 것인지 궁금합니다.

2022-03-08 15:00 UTC, kcharliek commented on ProjectManager/ProjectManager/View/ProjectListHeaderView.swift
> +    func countProject(number: Int) {
countProject 라는 이름이 어색하게 느껴집니다.

count가 동사가 되는데, 'project의 개수를 센다' 로 읽히네요. `updateProjectCount(_ count: Int)` 정도 어떨까요.

2022-03-08 15:01 UTC, kcharliek requested changes
Project Cell을 Section 으로 관리하는 것이 아닌, 단일 Section + Row N개로 관리하는 것을 필수 수정 내용으로 하겠습니다.

그 외 UI코드 아주 깔끔해보입니다. 전반적으로 잘해주셨어요~~!

2022-03-10 06:40 UTC, ICS-Asan commented on ProjectManager/ProjectManager/View/ProjectFormView.swift
> +    required init?(coder: NSCoder) {
`required init?`을 사용한다는 것은 스토리보드나 xib파일로 뷰를 구현하고자 할 때 사용하는 것으로 알고 있습니다.
만약 그렇다면 기존에 뷰를 구현하는 코드가 필요가 없어지는 것 같다고 생각되어 새로운 파일을 생성하고 기존 구현된 것을 삭제하는 것이 더 괜찮지 않을까 생각했습니다.
혹시 이런 생각이 틀린건지 궁금합니다.
그래서 저희가 위의 생각을 바탕으로 수정안을 생각해본 것은 `required init?`에 `attribute(@available(*, unavailable))`를 달아 사용되지 않을 이니셜라이저라고 명시하는 것입니다.
저희의 수정안과 이해한 것에 대해서 어떻게 생각하실까요?

2022-03-10 06:42 UTC, ICS-Asan commented on ProjectManager/ProjectManager/Protocol/CellManagable.swift
> +protocol CellManagable {
저희도 현재 구현된 부분이 재사용에 관련된 것들이라 좋은 네이밍이라 생각됩니다!!
감사합니다!!

2022-03-10 06:45 UTC, Allie-e commented on ProjectManager/ProjectManager/View/ProjectListCell.swift
> +    func setupLabelText(title: String, preview: String, date: String) {
private이 붙은 메서드들끼리 모아서 배치해놓았는데 level에 따른 순서는 신경쓰지 못했습니다~ 코멘트를 보고 저희끼리 이야기를 나누어 보았는데 저는 internal level이 private보다 아래에 위치하도록 작성해왔고, 아샌은 반대로 작성해왔습니다.
일반적으로 어떤 기준으로 순서를 잡아주는지 궁금합니다 🤔

2022-03-10 06:48 UTC, Allie-e commented on ProjectManager/ProjectManager/View/ProjectListHeaderView.swift
> +    func countProject(number: Int) {
말씀해주신대로 네이밍이 좀 어색한 느낌이 있는 것 같아요! 추천해주신 네이밍 좋은 것 같아서 반영하도록 하겠습니다! 😊✔️

2022-03-10 06:51 UTC, ICS-Asan commented on ProjectManager/ProjectManager/Controller/MainViewController.swift
> +        guard let indexPath = doingTableView.indexPathForRow(at: locationInView) else { return }
cell이 재사용되고 있기 때문에 cell에 등록을 하면 어떤 tableView의 cell인지 판단해야하는 과정이 필요하다고 생각되었습니다.
각 tableView마다 띄워야 하는 메뉴가 다르고 추후에 다른 tableView에 옮기는 작업이 필요하게 될텐데 모든 과정을 조건마다 분기처리를 하면 불편하지 않을까? 라는 생각에서 이렇게 구현해봤습니다.

2022-03-10 07:05 UTC, ICS-Asan commented on ProjectManager/ProjectManager/Controller/MainViewController.swift
> +    private let toDoDataSource = ToDoDataSource()
저희가 생각한 장점은 각 TableView에 필요한 data들을 따로 관리할 수 있고, 어떤 TableView인지 판단하지 않아도 되어 코드가 조금 더 간결해지는 장점이 있다고 생각해서 이렇게 분리해서 사용하고자 했습니다.
혹시 ViewController가 UITableViewDataSource를 채택하지 않고 따로 객체가 있는 것에 대해 의문을 주신거라면 따로 나눴을 때 ViewController가 복잡해지지 않고 위와 같이 사용했을 때 `dataSourece = self`와 동일한 역할을 하고있지 않나 생각을 해봤습니다.

2022-03-11 01:10 UTC, kcharliek commented on ProjectManager/ProjectManager/View/ProjectFormView.swift
> +    required init?(coder: NSCoder) {
음성으로 답변드렸습니다.

2022-03-11 01:11 UTC, kcharliek commented on ProjectManager/ProjectManager/View/ProjectListCell.swift
> +    func setupLabelText(title: String, preview: String, date: String) {
음성 답변 드렸습니다.

2022-03-11 01:12 UTC, kcharliek approved these changes

2022-03-11 08:47 UTC, merged