프로젝트 관리 앱 [STEP 2-2] 예거
yagom-academy/ios-project-manager pull request #88
Opened 2022-03-08 10:25 UTC by Jager-yoo

안녕하세요 그린! 💚 @GREENOVER
UI 구현에 해당하는 `스텝2-2` PR 제출합니다!

- ~스텝 2-1~ -> `모델 타입 구현`
- 스텝 2-2 -> `기본 UI 구현`
- 스텝 2-3 -> `Cell 간의 이동, 삭제, 수정 등의 비즈니스 로직 구현`

SwiftUI 에서 원하는 화면을 만들어내기가 까다로워서, 아직 `할일 추가/수정 화면`을 만들지 못했습니다. 😢 
그린과 논의하면서 다시 방향 설정을 해보고 싶어요. 많은 도움 부탁드립니다. 🙏🏻 

+ 코드가 많이 변경될 것 같아서, 이번 스텝 `리드미`는 리팩토링 하면서 작성하겠습니다!

<br>

# 🔥 고민한 부분

## 1️⃣ Navigation Bar 형태는 Section 으로 구현

- SwiftUI 에서 한 화면에 `List` 를 3개 넣는 것은 어렵지 않았습니다. (HStack 안에 List 3개 넣으면 끝)

- 이제 이 위에 `"ProjectManager"` 라는 Title 과 add(+) 버튼이 있는 `NavigationBar`를 올리면 되겠구나~ 라고 생각하며
`NavigationView`로 전체 화면을 감싸주었는데요.
갑자기 화면이 왼쪽으로 확 쏠리면서, 납작해지는 현상이 생겼습니다. 😱 (아래 이미지) 

<p align="left"><img src="https://user-images.githubusercontent.com/71127966/157198942-2293b2e6-5ef9-45e3-934f-74de495f2fd8.png" width="80%"></p>

|NavigationView 적용 전|NavigationView 적용 후|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/71127966/157197544-1f61bf85-58d3-45ac-9989-c1ddb4377ba6.png)|![image](https://user-images.githubusercontent.com/71127966/157197572-a9400207-3c59-4edf-a01c-381ca5039231.png)|

- 해당 이슈에 대한 원인은 찾지 못했고, 짐작가는 건 `iPad 전용앱`에서는 `NavigationView`를 사용할 수 없는 것인지 가설만 세워두었습니다. 😅 

- NavigationView 를 사용하지 못하면, 어떻게 저 `Bar`를 구현할까 고민했는데요.
`Section`에 HStack 을 넣고 Text, Button, Spacer 를 활용해보기로 했습니다.

- 오토레이아웃 없이 `Spacer`만 가지고 Button 을 우측에 자연스럽게 배치하면서 + Title 의 중앙정렬을 유지하기가 쉽지 않았습니다.
결국 동일한 버튼을 Title 양쪽에 배치하고, 하나는 `히든 처리`하는 식으로 어설프게 완성했습니다. 😢 

![image](https://user-images.githubusercontent.com/71127966/157200458-d9a81f7c-b95e-4d29-8247-55e96d6b87a6.png)

<br>

## 2️⃣ List 위에 있는 Header 구현

- List 위에 세부 Title 하고 할일의 개수를 실시간으로 표현하는 동그라미 Label 을 만들어야 했는데요.
List 를 스크롤 할 때, 같이 움직이는 게 아니라 `고정`되어 있으면 좋겠다고 생각했습니다.

- 위에서 NavigationView 가 의도한 대로 구현되지 않았던 경험(...) 때문에, List 를 포함해 `VStack`으로 감싸고, List 위에는 HStack 을 넣어서 세부 Title, 동그라미 Label 을 구현했습니다.

![image](https://user-images.githubusercontent.com/71127966/157203967-3bd99d79-024e-4897-a669-f380f5a8b389.png)

- 동그라미 Label 에선 이런 고민이 있었습니다.
  - Label 을 동그란 모양으로 만들기 위해 `clipShape(Circle())` 메서드를 사용했습니다.
  - 숫자의 자리수가 커지면, 동그라미도 같이 커지는 걸 막기 위해 `frame`을 적당한 크기로 고정했습니다.
  - 숫자가 100 이상(세 자리 수)으로 커지는 경우, 가독성이 떨어지므로, `삼항연산자`를 사용해서 `99+`가 표시되도록 했습니다.
  - 다크 모드 대응을 위해 `Color.primary`를 사용했고, 글자 색과 배경 색이 반대이므로, `colorInvert()` 메서드를 사용하여 글자 색을 반전시켰습니다.

|숫자 자리수 대응|다크 모드 대응|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/71127966/157205824-0bf9649e-8600-45ca-947d-7af149c6fa76.png)|![image](https://user-images.githubusercontent.com/71127966/157207013-dfcbbd51-567f-498d-a3b3-ed75318a230a.png)|

<br>

## 3️⃣ List 의 Row 사이에 간격 넣는 방법?

- 요구사항에서는 Row(Cell) 사이사이에 약간의 `간격`이 있습니다. 색상도 옅은 회색으로 조금 다르구요!
SwiftUI 에서 Row 사이의 간격을 어떻게 넣을 수 있는지 몇 시간을 찾아 헤맸는데요... 결국 적당한 방법을 찾지 못했습니다.

- 비슷하게라도 해보자 싶어, 높이를 최소한으로 축소한 `Spacer()`를 각 Row 사이사이에 끼워넣어 봤는데요.
의도한 대로 높이가 줄어들지도 않고(아무리 줄여도 12pt 미만으로 줄어들지 않았습니다), background 색상도 잘 안 먹혔습니다.

- 게다가, List 삭제를 위해 ForEach 뒤에 붙인 `onDelete` 메서드 때문에, `삭제 가능한 간격`처럼 작동하더라구요. 😅 
의도한 바와 전혀 다르기 때문에, 결국 코드를 다 빼버렸습니다. 😢 

|Spacer 로 만들어낸 간격|실제 구현된 모습|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/71127966/157209085-32a9f361-1037-4c81-9f30-ef18d2bed7ef.png)|![image](https://user-images.githubusercontent.com/71127966/157209139-11611a7b-5fc3-4bdb-8130-9c5f9a4a5d60.png)|

<br>

## 4️⃣ 현재 날짜와 하루 차이가 나는 걸 판단하는 로직

- 요구사항을 보면, `기한`이 지난 날짜는 빨간색으로 글자 색을 변경해줘야 합니다.

- 저는 할일(Task) Entity 에서 날짜는 `Date` 타입으로 선언했습니다.
이를 활용하기 위해, Date 타입의 `extension`을 아래와 같이 구현했습니다.

- [DateFormatter 인스턴스 생성 비용](https://sarunw.com/posts/how-expensive-is-dateformatter/)을 줄이기 위해, private static let 으로 만들고 `locale, timeZone, dateStyle` 을 설정해줬습니다.
Date 인스턴스를 포맷팅된 String 타입으로 만들어주는 연산 프로퍼티인 `dateString`을 구현했습니다.

- `isOverdue` 연산 프로퍼티가, `Date 인스턴스의 기한이 하루 이상 지났는지 판단`해주는 기능을 합니다.
dateString 으로, 포맷팅된 String 으로 바꾼 걸 다시 Date 타입으로 변환해서 `'시간' 데이터 없이 '날짜' 데이터만 남긴 상태로 크기 비교`를 합니다.
이때, 옵셔널에 `nil`이 잡히더라도, 비교는 가능하도록 닐병합연산자 넣어줬습니다.

```swift
extension Date {
    
    private static let dateFormatter: DateFormatter = {
        let dateFormatter = DateFormatter()
        dateFormatter.locale = Locale(identifier: "ko_KR")
        dateFormatter.timeZone = .autoupdatingCurrent
        dateFormatter.dateStyle = .medium
        return dateFormatter
    }()
    
    var dateString: String {
        return Self.dateFormatter.string(from: self)
    }
    
    var isOverdue: Bool {
        let targetDate = Self.dateFormatter.date(from: self.dateString) ?? Date(timeIntervalSince1970: self.timeIntervalSince1970)
        let currentDate = Self.dateFormatter.date(from: Date().dateString) ?? Date()
        return targetDate < currentDate
    }
}
```

<br>

# 🤔 궁금한 부분

## 1️⃣ 위에서 정리한 UI 구현 방법에 대한 그린의 의견이 궁금합니다!

- 특히, `iPad 전용앱`에서는 화면 전체 크기의 NavigationView 를 만들 수 없는 것인지와, `Section` 을 사용하여 정적인 Header 를 구현한 점이 괜찮은지 궁금합니다! 😄 

- 또한, SwiftUI 에서는 화면을 전환할 때 [NavigationLink](https://developer.apple.com/documentation/swiftui/navigationlink)를 사용하는 것 같은데요!
NavigationView 로 감싼 View 안에서만 작동하더라구요...
저는 `할일 추가 버튼(+)`이 눌리면, 커스텀하게 만든 화면을 띄워주는 걸 생각했는데, NavigationView 로 감싸면, 화면이 이상하게 뒤틀려 버려서, 구현할 수가 없었습니다. 😢 
어떻게 하면 좋을지.. 그린하고 논의해보고 싶어요! 🙏🏻 

<br>

## 2️⃣ SwiftUI 최신 메서드를 사용하기 위해, 앱의 최소 지원 버전을 'iOS 15.0' 으로 올리는 게 좋을까요?

- 엄청난 삽질을 하며... SwiftUI 에 어떤 메서드가 있는지 살펴보고 있는데요. ⛑️ 
편리한 메서드들은 `iOS 15.0 이상`에서만 사용할 수 있다는 경고가 되게 빈번하게 뜨더라구요. 😅 

- `if #available(iOS 15.0, *)` 와 같은 버전 분기처리를 해줄 순 있지만, 그래도 그 이하의 버전에서도 작동은 하게 만들어야 하잖아요? ㅎㅎ..
결국 iOS 15.0 메서드를 사용하지 않는 방향이 연습하기에도 좋을 것 같다고 생각했어요.

- 그린은 회사 또는 개인용 앱을 SwiftUI 로 구현한다면, `최소 버전`을 어떻게 잡으시나요?
속시원하게 iOS 15.0 이상으로 올려버리면 안 되는 거겠죠..? ㅎㅎ..

2022-03-09 12:33 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/ContentView.swift
>  struct ContentView: View {
디폴트 이름을 일단 사용하고 있었는데, 역시 바꿔주는 게 좋겠군요..!!

다른 View 들은, `특정 영역에 대한 책임`이 있기 때문에, TaskListView, TaskListRowView -> 이런 식으로 명확하게 네이밍을 지을 수 있었는데요!

뭐랄까 `ContentView` 역할은, 특정 UI 하나만 담는 게 아니라, 다른 모든 View 를 담아주는 `메인 ~ 전체` 느낌이 있어서
바꿔본다면, `MainTaskView` 같은 네이밍이 떠올라요... 근데 이런 네이밍은 ContentView 와 큰 차이는 없는 것 같아요. 😢 
오히려 "Task" 라는 단어가 들어가니까, '메인 할일' 이라는 늬앙스가 된 것 같아서 오해를 일으킬 수도 있겠어요.

혹시 그린이라면 어떻게 리네이밍하셨을 것 같으신가요? 🤔

2022-03-09 12:50 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/MainHeaderView.swift
> +                    .hidden()
- iPad 의 Landscape 모드에서는 NavigationView 의 `스타일`이 디폴트로 `columns`로 지정된다는 걸 알게 됐습니다..!
  - [navigationViewStyle(_:) 공식 문서](https://developer.apple.com/documentation/swiftui/view/navigationviewstyle(_:))
- 또한, `navigationViewStyle` 프로퍼티를 `stack`으로 변경해주면, 넓은 화면에서도 `single-column`을 구현할 수 있다는 것도 알게 됐습니다.
- 위 방법과 `toolbar`를 활용하여, 할일 추가(+) 버튼을 자연스럽게 구현했습니다. padding, Geometry 둘 다 사용하지 않을 수 있었습니다! 😄 

![image](https://user-images.githubusercontent.com/71127966/157442987-be60a486-a5ff-42c9-a72f-794a7a7426cd.png)

![image](https://user-images.githubusercontent.com/71127966/157443571-1d78d950-f552-43eb-93b5-30ffce05bbc8.png)

2022-03-09 13:00 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Model/Task.swift
>      let id: String
저도 SwiftLint Rule 중에서 변수의 글자수를 제한하는 게 디폴트로 들어가있다고는 들은 것 같은데
빌드할 때, `id`에서 경고가 나오는 걸 확인하지 못했습니다.

SwiftLint Rule 공식 문서로 들어가서, [Identifier Name](https://realm.github.io/SwiftLint/identifier_name.html)를 확인해봤는데요!
디폴트로 켜진 Rule 이지만 `"id" 는 제외한다`는 내용이 적혀있었습니다! 😄 

실험을 위해, 임시로 "ab" 라는 변수를 만들어봤는데요, 바로 경고가 뜨는 걸 볼 수 있었습니다!

![image](https://user-images.githubusercontent.com/71127966/157446037-264ef083-8747-4c9d-ad3e-7b2bffdb3d9f.png)

![image](https://user-images.githubusercontent.com/71127966/157445906-cf896fb7-a0f6-4069-bf9d-e5528097e6b5.png)

2022-03-09 13:20 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Model/Task.swift
> +
할일(Task) 인스턴스가 메모리에서 해제되기 직전에 `deinit`이 호출됩니다!
유저가 Row 를 `스와이프해서 삭제`하는 경우에 `불려야` 합니다! (그걸 확인하기 위해 코드에 넣어두었습니다.)

2022-03-09 13:25 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/ContentView.swift
> +                TaskListView(tasks: taskManager.todoTasks, taskStatus: .done)
지금은 각 ListView 들이 제대로 보여지는지 더미 데이터를 넣어둔 상황입니다!
그래서 세 타입의 파라미터를 보면, `taskStatus`는 다르지만, 넣어주는 `tasks 배열`은 전부 동일한 상황입니다. 😢 

이 내용은 화면과 로직이 다 완성되면, 리팩토링할 예정입니다!
그때 `ForEach`를 사용해서 반복문으로 입력해주도록 하겠습니다! ㅎㅎㅎ

2022-03-09 13:51 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +        .background(Color(UIColor.systemGray6))
`요구사항`에서의 백그라운드 색상을 맞추기 위해서였습니다!
해당 background 코드를 지우고 빌드를 돌려보면, 아래 이미지 처럼, 많이 어두운 회색이 나오더라구요!

그래서 SwiftUI 에서 기본 제공하는 `Color.gray` 색상을 적용해봤는데요, 더 어두워지더라구요. 😅 

Color 에는 lightGray 또는 systemGray1~6 같이, 좀 더 세밀한(?) 색상이 없기 때문에
이니셜라이저를 통해 `UIColor` 의 색상을 사용하여, `요구사항`과 가장 비슷한 색상을 선택한 것입니다! 👍🏻 

|디폴트|Color.gray|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/71127966/157452001-620e7ae0-6f06-4dcb-9a3e-87efcf4a9724.png)|![image](https://user-images.githubusercontent.com/71127966/157454458-36adbe55-c0fc-4101-ae2a-f6d89b7fd7fc.png)|

2022-03-09 14:35 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Model/Task.swift
> +class Task: Identifiable, Equatable {
제가 `스텝1`에서는 Task 타입에 `Identifiable`을 채택해주지 않았었는데요!
그 상태로 `List`를 구현하려고 하니까, 아래와 같은 에러가 뜨더라구요!

<img width="996" alt="image" src="https://user-images.githubusercontent.com/71127966/157459085-15af239f-c4a2-471b-a294-3e52868ce3cc.png">

그래서 조금 더 찾아보니, 애플의 Article [Displaying Data in Lists](https://developer.apple.com/documentation/swiftui/displaying-data-in-lists)에서, 아래와 같은 내용을 찾을 수 있었습니다!

> List 의 멤버로 쓰이는 데이터는 반드시 유니크해야 한다.
> 그러면 SwiftUI 가 자동으로 삽입, 삭제, 이동 같은 데이터의 변화에 대한 애니메이션을 만들어낼 수 있다.
> List 멤버 타입이 `Identifiable` 프로토콜을 채택하게 만들거나... (중략)

![image](https://user-images.githubusercontent.com/71127966/157460544-32d4435e-fe03-4fe1-9d6e-a4e4f6028b2f.png)

2022-03-09 14:56 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +    private var taskListHeader: String {
맞습니다! `taskListHeaderTitle`로 네이밍 수정했습니다! 😄

2022-03-09 23:47 UTC, GREENOVER commented on ProjectManager/ProjectManager/Model/Task.swift
>      let id: String
아하 그러면 제 엑코가 인덱싱을 잘 못했나봅니다😹

2022-03-09 23:49 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/ContentView.swift
>  struct ContentView: View {
저라면 정말 간단하게 MainView 혹은 HomeView라고 칭해볼수도 있을것같습니다!

2022-03-10 05:32 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/ContentView.swift
>  struct ContentView: View {
오 괜찮겠군요 ㅎㅎㅎ ContentView -> `MainView` 으로 네이밍 수정했습니다! 😄

2022-03-10 06:25 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +    @State var tasks: [Task]
여기도 처음에는 `@State` 없이 평범한 var 였는데요, `.onDelete` 메서드에서 tasks 배열에서 원소를 삭제하려고 시도하니까

> Cannot use mutating member on immutable value: 'self' is immutable

이런 에러가 뜨더라구요!

<img width="897" alt="image" src="https://user-images.githubusercontent.com/71127966/157596824-65ffd2d4-6ec5-4ece-b956-9e781c8a0d10.png">

그 이유는, SwiftUI 가 레이아웃을 꾸밀 때 `구조체(값타입)`를 사용하기 때문인데요.
구조체 안에 들어있는 변수(var)를 타입 내부에서 바꾸려고 하니까 `immutable` 이라는 에러가 뜨는 것이었습니다. 💡

참고 삼아, [Hacking with Swift 유튜브 영상](https://youtu.be/stSB04C4iS4?t=655)을 보고 있었는데
이런 상황에서 변수 앞에 `@State`를 붙여주면, SwiftUI 가 별도로 관리하면서 변화를 관찰하고, 구조체를 recreate 해주고, 자동으로 UI 를 업데이트 해준다는 내용이 있었습니다.

위 내용을 참고해서, tasks 변수 앞에 `@State` 어노테이션을 붙이니까, 컴파일 에러도 사라지고, Row 를 삭제했을 때 HeaderTitle 에 있는 `동그라미 count 라벨` 또한 자동으로 업데이트되는 모습을 확인할 수 있었습니다!

하지만, 위 영상이나 [State 공식 문서](https://developer.apple.com/documentation/swiftui/state), [참고 블로그](https://onelife2live.tistory.com/40?category=741790)를 더 확인해보니
'`state property`는 View 를 instantiate 할 때 초기화하지 말라'고 대놓고  써있더라구요.
애초에 그걸 방지하기 위해 `private 접근제어`를 꼭 붙여서 쓰라고 권고하고 있었습니다. 😅 

![image](https://user-images.githubusercontent.com/71127966/157601283-9dad81b3-74e6-40de-ab0e-01998e6fc58c.png)

저는 공식적인 가이드와 완전 반대로 state property 를 사용했던 것이더라구요.. ㅎㅎㅎ
`propertyWrapper` 사용법을 조금 더 공부해보고 리팩토링하고자 합니다!

2022-03-10 08:40 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/ContentView.swift
> +    ])
맞습니다! 테스트를 위한 가짜 데이터(?)들을 어디에 둘지 모르겠어서, 우선 눈에 보이는 곳에 넣어두었습니다. 😢 

리팩토링하면서, `MainView` 타입 내부에서 `뷰모델` 역할을 하던 TaskManager 인스턴스를 제거하고
MainView 가 instantiate 될 때, `생성자 주입`을 받을 때 초기화되도록 변경했습니다.

```swift
struct MainView: View {
    
    let taskManager: TaskManager
    
    var body: some View {
    ...
    }
}
```

가짜 데이터(mockTasks)는 SceneDelegate.swift 파일에 private 하게 옮겨두었습니다.
그리고 `rootView`를 설정하는 코드에서 가짜 데이터를 들고 `생성자 주입`되도록 만들었습니다.

```swift
let hostingVC = UIHostingController(rootView: MainView(taskManager: TaskManager(tasks: mockTasks)))
```

그런데 이렇게 코드를 고치니까, `MainView` 내부에 있던 `프리뷰` 타입에서도 전부 생성자 주입이 필요하더라구요. 😅 
하지만 가짜 데이터는 SceneDelegate 클래스 내부의 프로퍼티로 넣어두었기 때문에, MainView 에서 접근할 수가 없었습니다.
-> 그래서 MainView 의 프리뷰를 없애게 되었습니다...?

결론이 좀 이상하지만... 😢 
UI 확인을 위한 가짜 데이터를 이렇게 다루는 게 맞을까요..??

2022-03-10 08:51 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/ContentView.swift
> +    ])
네 맞습니다!
해당 방향이 더 맞을것 같아요.
다만 프리뷰에 대해서는 크게 고려하지 않아도 될것 같아요.
넣어줄 수 없다면 목데이터를 그냥 바로 프리뷰에 넣는 식으로도 가능하니 사용하자면 없애지 않고도 사용할 수 있긴합니다!
다만 저는 프리뷰를 거의 안씁니다..
데이터가 많아지고 뷰에 그려질것이 많아지게 되면 프리뷰가 제대로 나오지 않는 엑코의 문제인지.. 가 있기에 그냥 방대한 앱에서는 빌드 돌리는게 더 빠르더라구요🥲

2022-03-10 08:56 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/ContentView.swift
> +    ])
맞아요 저도 처음 SwiftUI 접했을 때는 `프리뷰`가 마냥 편리하고 좋아보였는데...
그려질 게 많아지다보니 자꾸 멈추고 `Resume` 버튼 2번 씩 눌러줘야 해서.. 어느새 저도 프리뷰 보다는 [Command + R] 눌러서 직접 시뮬레이터로 보는 게 더 편하더라구요! 😄 

감사합니다!!

2022-03-10 18:35 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +    }
좋은 리팩토링 포인트네요! 👍🏻 
`모델 타입`에 해당하는, TaskStatus 열거형 내의 연산 프로퍼티로 위치를 이동시켰습니다!

- https://github.com/yagom-academy/ios-project-manager/pull/88/commits/54e132b1975b9d7bc2ad2b80823d839a2f9cde4f

2022-03-10 18:38 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +                Text(tasks.count / 100 < 1 ? "\(tasks.count)" : "99+")
여기서도 좋은 코멘트 감사합니다! 😄 👍🏻 
해당 계산하는 로직을, 같은 타입 내의 `private 연산 프로퍼티`로 분리시켰습니다.
네이밍은 `tasksCount`로 지어줬습니다!

- https://github.com/yagom-academy/ios-project-manager/pull/88/commits/54e132b1975b9d7bc2ad2b80823d839a2f9cde4f

2022-03-10 18:56 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +                    // 캡쳐된 연산 프로퍼티인 tasks 배열 내에서만 삭제되므로, 할일 인스턴스는 완전 삭제되지 않은 상태임
tasks 프로퍼티가 `@State` 어노테이션을 붙일 수 없는 `연산 프로퍼티`로 변경되면서, `onDelete` 메서드 내의 코드가 아래와 같이 변경됐습니다!

```swift
.onDelete { indexSet in
    guard let targetIndex = indexSet.first else { return } // IndexSet 타입을 Int 타입으로 바꿔줍니다.
    try? taskManager.deleteTask(target: tasks[targetIndex]) // 뷰모델 역할을 하는 taskManager 의 메서드를 호출합니다.
}
```

이렇게 변경되면 `액션이 View 가 아닌 다른 곳에서 이뤄진다` 라고 볼 수 있는 걸까요?! 🤔

2022-03-10 19:10 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Model/Task.swift
> +
이번 `스텝 2-2` 리팩토링에서 가장 걸림돌이 되고 있는 부분이 여기네요. 😅 

List 의 Row 를 삭제하는 `onDelete` 메서드 내에서 `뷰모델` 역할을 하는 taskManager 의 deleteTask 메서드를 호출해서, 할일 데이터의 source 가 되는 `tasks` 배열에서 삭제시키고 있는데요!

또한 tasks 배열에는 `@Published` 어노테이션을 붙여서, 값이 변경되면 UI 가 다시 그려질 수 있도록 만들었습니다.
(값이 변경되면 -> TaskListView 를 구성하는 연산 프로퍼티가 여러 번 호출되는 걸 확인했습니다.)

```swift
class TaskManager: ObservableObject, TaskManageable {
    @Published private var tasks = [Task]()
    ...
}
```

하지만 제 예상과 다르게, tasks 배열에서 할일 인스턴스를 지워주더라도, `deinit`이 호출되지 않았습니다.
Reference Count 가 `0`이 되지 않았기 때문이라고 생각하여, 도대체 몇 개를 가지고 있는 건지 확인하기 위해
`lldb`에서 "la s refcount [클래스 타입의 인스턴스]" 명령어를 활용해서, 삭제 대상인 할일 인스턴스를 찍어봤는데요!

![image](https://user-images.githubusercontent.com/71127966/157735148-00bb8f9c-dcca-45c8-a3d5-8c2d29965b45.png)

위 이미지 처럼, `강한 참조(strong)가 7개 까지` 올라가있고, 언제 만들어진지도 모르겠는 `unowned, weak 또한 각각 1씩 존재`했습니다.

해결 방법을 찾아보다가, 시간이 계속 지체되어 그린에게 질문을 드리게 됐습니다! 😢 

- 모델 타입을 클래스로 구현해서, 계속 이런 어려움이 발생하는 것인지
- List 의 Row 를  구성하는 tasks 배열이 연산 프로퍼티로 만들어져서 그런 것인지
- 어떻게 하면 할일(Task) 인스턴스의 Reference Count 를 바로 0 으로 만들어서 deinit 시킬 수 있을지

조언을 부탁드립니다! 🙏🏻

2022-03-10 23:41 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +                    // 캡쳐된 연산 프로퍼티인 tasks 배열 내에서만 삭제되므로, 할일 인스턴스는 완전 삭제되지 않은 상태임
네 제가 의도하여 말씀드린 바와 일치합니다!

2022-03-11 00:18 UTC, GREENOVER commented on ProjectManager/ProjectManager/Model/Task.swift
> +
우선 저도 합리적으로 의심은 드는 부분은 클래스 참조 타입이라 그럴것 같긴합니다.
SceneDelegate에서 mockData로 task를 집어 넣어주고 ForEach를 돈다던가 하는 부분에서 BR을 찍고 스텝별로 넘어가보면 비정상적으로 강한참조가 8, 9 , 12까지 올라갔다 해제되는걸 볼 수 있습니다.
아마도 실제로 뷰를 구성해주고 그려주는 과정에서 task가 많이 참조되는걸로 짐작이 될것 같습니다.
그렇기에 첫번째로 추측하신 이유가 원인이지 않을까라는 의심이 듭니다.
또한 추측하신 2번째도 원인이 될 순 있을것 같습니다. taskListView를 계속 연속적으로 그려주고 있는 와중에 접근하게 되면 계속 task에 대해 참조하여 판단하고 사용함으로 참조값이 올라갈 순 있을것 같습니다.
아마 구조체로 변경을 해보는 작업을 하여 추측한 가설에 대해 검증해보는게 가장 빠를것 같다고 생각합니다.
더불어, 현재 뷰에 task 연산 프로퍼티들을 뷰에 위치 시키는게 아닌 모델 혹은 뷰모델쪽에서 판단하여 뷰는 정말 로직 판단 없이 갈아끼울 뷰만 올려줄 수 있는 방향으로 간다면 이러한 참조도 줄일 수 있지 않을까 생각됩니다🙋🏻

2022-03-14 13:09 UTC, Jager-yoo commented
안녕하세요 그린! 💚 오랜만에 코멘트를 남기네요.. @GREENOVER 

클래스로 구현한 `Task 인스턴스가 deinit 되지 않는 이슈`에 오랜 시간 매달려 있었지만, 결국 해결하지 못했습니다. 😢 
그 과정에서 제가 `SwiftUI 기초`를 너무 모른다는 생각이 들어서, 다양한 `WWDC 영상`과 각종 유튜브를 시청하며 공부하며 지냈어요! ㅎㅎ

- 🍎 WWDC 20
  - [Introduction to SwiftUI](https://developer.apple.com/videos/play/wwdc2020/10119/)
  - [Data Essentials in SwiftUI](https://developer.apple.com/videos/play/wwdc2020/10040/)
  - [App essentials in SwiftUI](https://developer.apple.com/videos/play/wwdc2020/10037/)
- 🍎 WWDC 19
  - [Data Flow Through SwiftUI](https://developer.apple.com/videos/play/wwdc2019/226/)
  - [SwiftUI Essentials](https://developer.apple.com/videos/play/wwdc2019/216/)
- 유튜브
  - [SwiftUI Tutorial: What's the difference between @State, @ObjectBinding, and @EnvironmentObject?](https://youtu.be/stSB04C4iS4) 외 다수

어느새 2주가 끝나고, 새로운 프로젝트가 열렸는데요, 앞으로 `Realm`, `Firebase` 적용이 남은 만큼
일단 Task 인스턴스에 대한 것에 집착하지 말고, `화면이랑 로직` 부터 완성했습니다!

새로운 PR 을 제출하기 보다는, 기존 것에 코멘트를 추가합니다! 🙏🏻 잘 부탁드립니다!

<br>

# 📱 기능 시연

https://user-images.githubusercontent.com/71127966/158143234-6d20086a-e19d-44d8-ac97-f5883db37b83.mp4

<br>

# 🔥 고민한 부분

## 1️⃣ @EnvironmentObject 활용한 viewModel 역할을 하는 taskManager 인스턴스의 사용

- 클래스로 구현한 TaskManager 타입은 앱에서 활용하는 할일 `데이터의 근원(source)`이 되는 tasks 배열과, 연산 프로퍼티, 할일의 `CRUD 메서드`를 모두 가지고 있습니다.

- 모든 View 에서 `taskManager 인스턴스`가 필요한 게 아니고, `CRUD 기능`이 필요한 몇 개의 View 에서만 필요하므로, 번거로운 `의존성 주입` 없이, 필요한 View 에서 즉시 사용할 수 있도록 [@EnvironmentObject](https://developer.apple.com/documentation/swiftui/environmentobject) property wrapper 활용했습니다.

<br>

## 2️⃣ 할일 인스턴스가 수정됐다는 신호를 받기 위해 Task 타입에 ObservableObject 프로토콜 채택

- 기존에는 TaskManager 타입이 가지고 있는 tasks 프로퍼티에만 [@Published](https://developer.apple.com/documentation/combine/published) property wrapper 를 붙였는데요.
Task 의 배열은 원소의 '추가', '삭제'에 대한 신호는 주지만, '수정'하는 경우엔 신호를 주지 않더라구요.
따라서 `View 가 re-render 되지 않는 이슈`가 있었습니다.

```swift
// Task 의 배열은 원소의 '추가', '삭제'에 대한 신호는 주지만, '수정' 신호를 주진 못한다.
@Published private var tasks = [Task]()
```

- 개별 Task 인스턴스의 프로퍼티가 수정됐을 때에도 화면이 다시 그려지도록, Task 타입에도 `ObservableObject 프로토콜`을 채택해주었습니다.
그리고 변경되지 않을 `id`를 제외한 모든 프로퍼티에 `@Published`를 붙였습니다.

```swift
class Task: ObservableObject, Identifiable, Equatable {
    
    let id: String
    @Published var title: String
    @Published var body: String
    @Published var dueDate: Date
    @Published var status: TaskStatus
    ...
}
```

- 여기까지만 진행하니까, 할일을 수정했을 때, 해당 Row 의 View 는 변경됐으나, dueDate 가 빠른 순서대로 List 의 순서가 재정렬되지는 않았습니다.

- 그 이유는, `List 의 순서`는 단순히 Task 가 수정되는 것에 영향을 받지 않고, 더 상위 객체인 taskManager 의 `연산 프로퍼티`에 의해 정해지고 있어서 였습니다. 🧐
따라서 List 순서 재정렬을 위해서는, taskManager 에 Publisher 변경 사항이 있을 거라고 코드로 신호를 보내야 했습니다.
  - ❤️ [문제 해결에 큰 도움을 준 스택 오버 플로우 링크](https://stackoverflow.com/questions/57459727/why-is-an-observedobject-array-not-updated-in-my-swiftui-application)

```swift
taskManager.objectWillChange.send() // taskManager 인스턴스가 관리하는 Publisher 에 변경이 있을 거라는 신호를 미리 보냄
try? taskManager.editTask(target: selectedTask, title: newTaskTitle, body: newTaskBody, dueDate: newTaskDueDate)
```

<br>

## 3️⃣ Row 의 Tap 가능한 영역 늘리기

- 이론적으로, List 의 `Row 영역 전체`에 대한 `onTapGesture` 를 활성화 해주려면 List 클로저가 바로 뒤에 .onTapGesture modifier 를 붙이면 되는데요.

```swift
// List 의 Row 영역 전체를 Tap 가능한 영역으로 만들기
List {
    ForEach(...)
}.onTapGesture {
    // 탭 됐을 때 액션
}
```

- 프로젝트에서는 Row 가 탭되면, 해당 Row 에 들어있는 `Task 인스턴스`의 정보가 필요하기 때문에, 아예 Task 타입을 프로퍼티로 갖고 있는 `TaskListRowView` 타입에서 .onTapGesture 를 구현해줬는데요.
비주얼 디버거로 확인해보니, `탭 가능한 영역`이 Text 가 위치하는 VStack 크기에 불과할 만큼 좁았습니다.

- 탭 가능한 영역을 Row 의 넓이 만큼 확장해 주기 위해서, `Spacer()`를 추가했는데요.
이상하게 Spacer() 부분은 onTapGesture 가 작동하지 않았습니다.
관련하여 검색을 해보니, [contentShape](https://developer.apple.com/documentation/swiftui/view/contentshape(_:eofill:)) 사용한 해결 방법을 찾을 수 있었습니다.

  - ❤️ [SwiftUI can't tap in Spacer of HStack](https://stackoverflow.com/questions/57191013/swiftui-cant-tap-in-spacer-of-hstack)

```swift
HStack {
    VStack(alignment: .leading, spacing: 5) {
        // Text 내용 코드
    }
    Spacer()
}
.contentShape(Rectangle()) // hit testing 가능한 영역을 사각형 모양으로 만든다
.onTapGesture {
    isTaskEditingViewShowing.toggle() // 탭되면 Bool 타입의 State 변경시킨다
}
.sheet(isPresented: $isTaskEditingViewShowing) {
    TaskEditingView(...) // State 가 바뀌면, TaskEditingView 화면이 Modal 로 올라온다
}
```

|Tap 가능 영역 확장 전|Tap 가능 영역 확장 후|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/71127966/158175788-4022c959-c508-49e8-be19-89a97b5ea986.png)|![image](https://user-images.githubusercontent.com/71127966/158176877-6cf8d222-0827-49bd-bcc7-8ef0a4b475e6.png)|

<br>

## 4️⃣ 앱 사용성을 위한 사소한 기능들

- 새로운 할일을 추가하거나, 수정할 때, `Title`이 비어있지 않으면서 + 동시에 내용(body)이 1,000 글자를 넘지 않는 경우에만 다음 액션을 취할 수 있도록 `validation 로직`을 넣었습니다.
조건을 만족하지 못하면, 버튼이 disabled 돼서 누를 수 없는 상태로 머물다가, 조건이 충족되면 enabled 됩니다. 😄 

- 할일이 생성, 수정, 이동할 때, ⚡번쩍! 하면서 변하는 게 좀 어색하더라구요.
SwiftUI 에서는 `애니메이션` 넣는 게 상당히 편리한 걸 알게 돼서, `withAnimation` 코드를 추가해봤습니다. 😄 

- List 에 아무런 할일이 없는 경우, 너무 허전해보이더라구요. 🍂 
그래서 `ListPlaceholderView` 를 추가로 구현해서, 간단한 조건문을 통해 View 를 갈아끼우는 식으로 만들었습니다.

<br>

# 🤔 궁금한 부분

## 1️⃣ objectWillChange.send() 메서드 사용은 자제해야 할까요?

- 위에서 제가 큰 도움을 받았다고 언급한 [스택 오버 플로우](https://stackoverflow.com/questions/57459727/why-is-an-observedobject-array-not-updated-in-my-swiftui-application)에 이런 내용이 있더라구요!

> 추천하는 방법은 아니지만(not recommended), 수동으로(manually) notification 를 보내어 View 를 다시 그릴 수 있다.

![image](https://user-images.githubusercontent.com/71127966/158168394-4b17c8c0-1eaa-452b-829a-0c4c5edd5a53.png)

- 저도 아직 모델 타입이 `클래스`이기 때문에, `objectWillChange.send()` 메서드를 사용하여 View 를 다시 그려주는 로직을 `강제`했다고 생각합니다.
✋🏻 질문은, 스택 오버 플로우에서 언급된 것 처럼, `objectWillChange.send()` 메서드는 최대한 사용하지 않는 게 좋을까요? 🤔 

<br>

## 2️⃣ Task Row 가 이동한 뒤에 잠시 동안 '잔상'이 남는 이슈

- 위 `기능 시연` 영상에서 할일의 status 를 변경하는 부분을 잘 보시면, Row(Cell)이 이동한 뒤에, 잠시 동안 `잔상`이 남는 걸 볼 수 있습니다.
살짝 버벅이는 느낌을 주기 때문에, 앱의 사용성을 악화시키는 찝찝한 이슈인데요. 😢 

- Row 가 이동하는 로직을 되짚어 보면, `Task 인스턴스의 status 프로퍼티를 변경한다` -> `taskManager 에게 Publisher 객체가 변경될 거라는 신호를 보낸다` -> `화면이 다시 그려지면서, List 를 구성하기 위한 연산 프로퍼티가 re-computed 되고, Row 가 이동한다` 이렇게 3단계인데요.

- ✋🏻 위 로직에 대한 연산이 너무 과해서 잔상이 남는 것일까요?
어떻게 하면 이런 부자연스러운 이슈를 없애거나, 최소화할 수 있을까요? 🤔 

```swift
// Row 이동 버튼
Button {
    withAnimation {
        taskManager.objectWillChange.send()
        try? taskManager.changeTaskStatus(target: task, to: status)
    }
} label: {
    Text("Move to \(status.headerTitle)")
}
```

2022-03-15 05:09 UTC, GREENOVER requested changes
@Jager-yoo 
스텝 2-3까지 한번에 처리하느라 힘드셨을텐데 고생 많으셨습니다!
그럼 여기서 저도 스텝 2-3에 대한 리뷰까지 한번 같이 해볼께요!!ㅎㅎ
전체적으로 기능에 대한 구현은 잘 해주셔서 디테일한 부분에서 필요한 리팩토링에 대해 주로 코멘트 남겨봤습니다🙌
***
### 궁금하신 부분에 대한 저의 의견
1. objectWillChange.send() 메서드 사용은 자제해야 할까요?
- 이에 대한 사용으로 찾아보신것처럼 뷰를 다시 그려주는 로직이 단순 class여서 이를 해결하기 위한 방법으로 가져간다면 적절한 선택은 아닐것 같습니다.
찾아보신것처럼 많은 리스크를 감수한다고 생각해요.
이에 대한 리스크는 전반적으로 뷰의 버벅임 및 성능에 좋지 않은 영향을 끼칩니다.
다른 해결책이 필요하지 않을까 싶어요🥲
2. Task Row 가 이동한 뒤에 잠시 동안 '잔상'이 남는 이슈
- 우선 가장 중요한 키 포인트는 뷰를 그려주는데 오래걸린다가 가장 주요 원인일것 같아요.
갱신을 하고 뷰를 다시 그려주는데 오래걸리는 느낌이 들어요.
그럼 그 원인이 어떤거 때문에 발생하는지 추측해보자면 마지막에 언급해주신 것처럼
연산이 많이 걸립니다. 연산이 왜 많이 걸릴까 생각해보면,
뷰 안에서 너무 많은걸 해주고 있습니다.
코멘트로도 조금 남겨보았지만 뷰 안에서 뷰모델이 할일을 해주고 있는 경향이 있습니다.
현재 뷰모델이라고 부를만한 친구가 딱히 없어 보이는것도 앞으로의 방향에서 괜찮을지 모르겠습니다🤔
또한 뷰안에 연산 프로퍼티들도 많고 계속 뷰를 그려줄때 이러한 요소들이 부자연스러움을 만들지 않나 생각듭니다.
추가로 1번의 궁금하신 포인트도 이러한거에 여파가 되지 않나 싶습니다!
한번 전체적으로 뷰에 대해 고민해보는 시간이 필요해 보입니다🤔
***
스텝2-3까지 한번에 하시느라 조금 코멘트 및 내용이 많네요..!!
그래도 중요한 부분이니 개선해보시면 좋겠습니다ㅎㅎ
수정 후 리뷰 재요청을 해주시면 감사하겠습니다🙌
화이팅입니다!!👏

2022-03-15 14:01 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/MainView.swift
> +    @State private var isTaskCreatingViewShowing: Bool = false
넵! 만들면서도 "is" 하고 "showing" 사이가 너무 멀어서 좀 어색했네요.. 😅 

WWDC 영상을 보다가 영감을 얻은 부분이 있는데
`isTaskCreating`, `isTaskEditing` -> 이런 state 네이밍은 어떨까요? 🤔 
또는 `isCreatingTask`, `isEditingTask` -> 이런 것도 생각해봤습니다.

기존에는 View 까지 붙은 풀네임을 사용하려다 보니 정직하게 길어졌는데요.
사실 Modal 을 올리는 행위는 할일을 만들거나(Creating), 수정하기(Editing) 위한 것이니까,
그런 `행위 여부`를 state 이름에 녹여도 괜찮을까 싶네요! (View 의 이름에도 "~ing" 표현을 쓰기도 했구요 ㅎㅎ)

<img width="144" alt="image" src="https://user-images.githubusercontent.com/71127966/158394375-f3ea12f4-7fce-4d9a-87d0-77e6d7ead86b.png">

2022-03-15 14:04 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +                TaskListPlaceholderView(taskStatus: taskStatus)
사실 이 부분도 조금 고민이 있었습니다. 😅 

`조건문`에 따라, 어떤 View 를 보여줄지 결정하는 로직이 들어가있는 것인데
여기는 `View`인데 이런 로직이 들어와 있어도 괜찮나 싶더라구요.. 😢 

그래도 코드를 최대한 간소화하고자 연산 프로퍼티인 `isTasksNotEmpty` 까지 만들면서 진행했는데요!
화면 갈아끼우는 로직은 View 에 있어도 괜찮은 걸까요?
아니면 이런 로직도 엄밀히는 viewModel 로 가야 하는 걸까요?

2022-03-15 14:19 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/MainView.swift
> +                TaskListView(taskStatus: .done)
아이고.. 리팩토링 할 수 있는 기회가 왔는데 캐치를 못했네요. ㅜㅜ
심지어 `TaskStatus` 열거형에 `CaseIterable` 프로토콜까지 채택해두고..ㅎㅎ..

아래와 같이 리팩토링 했습니다!
[ForEach 구조체](https://developer.apple.com/documentation/swiftui/foreach) 공식 문서를 보면, 데이터가 `Identifiable` 프로토콜을 채택하거나, ForEach 이니셜라이저에 `id` 파라미터를 넣어주라고 되어 있습니다.

![image](https://user-images.githubusercontent.com/71127966/158397326-2a3ea862-f07c-4727-a27a-b45b2b590d64.png)

프로토콜을 채택하면, TaskStatus 열거형 타입 내부에 `id` 프로퍼티를 만들어놔야 하는데, 열거형은 저장 프로퍼티(stored properties)를 가질 수가 없으므로, 골치아파져서...

이니셜라이저에 `id: \.self` -> 이 코드를 넣어서 ForEach 를 완성했습니다! 👍🏻 

```swift
ForEach(TaskStatus.allCases, id: \.self) { status in
    TaskListView(taskStatus: status)
}
```

2022-03-15 17:45 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskCreatingView.swift
> +                TextEditor(text: $newTaskBody)
SwiftUI 에서 제공하는 [TextEditor](https://developer.apple.com/documentation/swiftui/texteditor)에는 `Placeholder` 기능이 없어서, 이 부분을 좀 아쉽게 처리하고 넘어갔네요.. 😅 

이전 프로젝트인 `<오픈마켓>` 당시에도, 비슷한 문제 해결 경험이 있습니다.
UIKit 에서 제공하는 [UITextView](https://developer.apple.com/documentation/uikit/uitextview)에도 똑같이 Placeholder 기능이 없어서, 별도의 View 를 `Z축으로` UITextView 위에 올리고, 내용이 채워지면 `isHidden` 처리를 해주는 식으로 만들었던 경험이 있거든요 ㅎㅎㅎ

SwiftUI 에서도 비슷한 방식으로 만들어보려 했는데, `ZStack` 이라는 아주 편리한 기능이 있는 반면에, `isHidden` 프로퍼티가 없었습니다. 🤷🏻‍♂️ (정말 이해 안 되는 부분...)
- 구글링을 해보니 `isHidden`을 대체하기 위한 다양한 접근 방법이 있더라구요. [Dynamically hiding view in SwiftUI](https://stackoverflow.com/questions/56490250/dynamically-hiding-view-in-swiftui)

저는 View 의 `투명도`를 조절하는 `opacity` modifier 를 사용했습니다!
해당 리팩토링을 진행하며, TextEditor 자체를 별도의 구조체인 TextEditorWithPlaceholder 로 파일 분리했으며
(지금은 2개인) Modal View 들에서도 재사용할 수 있게 만들었습니다! 😄 👍🏻 

https://user-images.githubusercontent.com/71127966/158437488-aa3eb851-3d60-4e33-ada8-888a9b7eba5d.mov

2022-03-15 21:21 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/MainView.swift
> +    @State private var isTaskCreatingViewShowing: Bool = false
네! 그 네이밍도 괜찮아 보입니다 ㅎㅎ

2022-03-15 21:25 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +                TaskListPlaceholderView(taskStatus: taskStatus)
정말 현실적으로 뷰에서 조건문의 로직을 빼는건 이상향이고 사이즈가 커질수록 불가능에 가까울거라 생각해요ㅠ
간단한 조건문정도의 로직은 전 괜찮다고 생각합니다! 성능에도 별 영향이 없구요.
뷰에서 들어가지 않아야할 로직은 대표적으로 연산 로직 및 뷰에서의 메서드 직접 호출을 통한 것들이라고 생각합니다🙋‍♂️

2022-03-16 00:01 UTC, GREENOVER commented
@Jager-yoo 
예거 하나 캐치한게 있습니다!
잔상이 남는게 제가 테스트를 해봤는데 아마 contextMenu를 이용해서 그런것 같습니다.
contextMenu를 사용하여 동작에 대한 뷰를 띄워주고 동작을 시키면 사실 해당 contextMenu로 띄운 moving을 해주는 뷰에 대한 의존성이
바로 사라지지 않아서 그런것 같아요.
아마 overlay로 뷰를 직접 그려주거나 한다면 이 문제는 해결될거라 봅니다.
실제로 해봤는데 되더라구요..!
참고하시면 될것 같습니다🙌

2022-03-16 03:57 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/MainView.swift
> +    @State private var isTaskCreatingViewShowing: Bool = false
감사합니다! 네이밍 수정했습니다. 😄

2022-03-16 05:26 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskEditingView.swift
> +struct TaskEditingView: View {
맞습니다! 2개의 ModalView 를 하나로 통합하는 리팩토링을 완료했습니다. 👍🏻 하면서 많이 배웠어요.. ㅎㅎㅎ

Creating(생성) + Editing(수정) -> 2개의 기능이 통합된 View 를 어떻게 네이밍할까 고민했는데요!
View 자체가 Task 를 생성/수정하는 `폼(Form)`의 재사용 느낌을 강조하는 식으로, 중립적으로 만들었어요! -> `TaskFormingView`

파라미터로 selectedTask 를 받는데요!
`수정` 하는 경우엔 Task 인스턴스를 파라미터로 받고, `생성`하는 경우엔 `nil`을 넣어주도록 처리했습니다.

또한 `mode` 라는 argument label 을 만들어서, 이어지는 isTaskCreating/Editing 과 함께 영어 문장처럼 읽히도록 만들었습니다.

```swift
// Task 생성
TaskFormingView(selectedTask: nil, mode: $isTaskCreating)

// Task 수정
TaskFormingView(selectedTask: task, mode: $isTaskEditing)
```

2022-03-16 05:28 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskEditingView.swift
> +    @State private var newTaskBody: String
동의합니다!
TaskCreatingView + TaskEditingView -> `TaskFormingView` 하나로 통합하면서
내부에서 사용하는 State 프로퍼티들의 네이밍을 중립적으로 수정했습니다. 👍🏻 

```swift
@State private var taskTitle: String
@State private var taskDueDate: Date
@State private var taskBody: String
```

2022-03-16 05:48 UTC, Jager-yoo commented on ProjectManager/ProjectManager/Utility/TaskManager.swift
> +        return title.isEmpty == false && body.count <= 1000
동의합니다!
중립적인 의미만 들어갈 수 있도록 네이밍 수정해주었습니다! 👍🏻 

```swift
func validateTask(title: String, body: String) -> Bool
```

2022-03-17 13:06 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskCreatingView.swift
> +            }
제가 `아이패드 Pro(12.9 인치)`로 작업을 하고 있어서, 더 작은 아이패드에서 어떻게 되는 지를 체크를 못 했네요. 😢 

사실 큰 아이패드에서는 `TextEditor`의 frame 이 알아서 조절되는 효과가 있길래 (아래 영상처럼)
"SwiftUI 는 키보드 대응이 자동으로 되나보다... 신기하다." -> 이렇게 생각하고 넘어갔습니다. 😅 

https://user-images.githubusercontent.com/71127966/158812137-0b1bd5ad-c1a8-4d0f-86b3-ada03a896157.mp4

그리고 키보드 대응에 거의 반나절을 사용해서 좀 어설프지만 해내긴 했네요..
일단 UIKit 처럼 keyBoardWillShow, keyBoardWillHide 노티를 받아주기 위한 `KeyboardResponder` 타입을 구현했구요.

`제목(Title)` 부분까지는 키보드가 올라올 수 없으므로, 제목에 focus 를 잡고 키보드를 올렸을 높이를 유지,
`내용(body)` 부분에 focus 를 잡고 키보드를 올리면 대응이 되도록 만들었습니다.

[@FocusState](https://developer.apple.com/documentation/swiftui/focusstate)라는 편리해보이는 property wrapper 를 찾았는데, 아쉽게도 `iOS 15.0` 버전 이상부터 사용 가능했습니다. 😢 

그래서 state property `isTextEditorFocused` 를 만들고, `onTapGesture` 을 사용해서, focus 가 `내용(body)`에 들어가있는지 판단해주는 로직을 만들었습니다.

그리고 만들던 도중, 키보드가 안 올라왔는데도 `padding`이 작동하는 이슈가 있었는데요,
알고보니 `자동완성 툴바`가 올라와있는 것 또한 키보드가 올라온 것으로 인식하더라구요. 🤷🏻‍♂️ 

<img width="507" alt="아이패드 자동완성 툴바도 키보드로 인식" src="https://user-images.githubusercontent.com/71127966/158813629-565c15d2-5108-4bc3-971a-ee5215b26205.png">

그래서, `자동완성 툴바는 무시`할 수 있도록, `height 가 70 이상인 경우`에만 키보드가 올라오는 거로 인식하는 로직을 추가했습니다.
(자동완성 툴바의 height 가 69.0 으로 나와서, 70으로 잡았습니다.)

```swift
// 자동완성 툴바 무시할 수 있는 연산 프로퍼티
private var isRegularKeyboard: Bool {
    return keyboardResponder.currentHeight > 70
}
```

아래는 구현 결과입니다!! 😄 

## 아이패드 미니

https://user-images.githubusercontent.com/71127966/158814173-4cd3cbc3-7152-473a-a955-170613220b3c.mp4

## 아이패드 Pro (12.9인치)

https://user-images.githubusercontent.com/71127966/158814222-b6da1d6b-f644-4e54-a9a6-5cc0c7230981.mp4

2022-03-22 03:22 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +    }
드디어 `MVVM 리팩토링`을 마무리했습니다!

뼈대가 되는 View 구조체들이 프로퍼티로 `@EnvironmentObject`, `@StateObject`만 갖고, 그 외의 비즈니스 로직이나 상수는 전부 뷰모델 내로 이동시켰습니다! 👍🏻 

```swift
struct TaskListView: View {
    @EnvironmentObject var taskManager: TaskManager
    @StateObject private var taskListViewModel: TaskListViewModel
    // 나머지 코드...
}
```

2022-03-22 05:16 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskListRowView.swift
> +                            try? taskManager.changeTaskStatus(target: task, to: status)
저때는 에러 처리까지 해볼 여유가 부족해서, 우선 `try?` 로 처리하고 넘어갔었습니다! 😅 

MVVM 리팩토링을 마치고, 이제 작업을 끝냈습니다!
에러 발생 시, `Alert` 를 띄워서, 사용자에게 앱 종료 후 문의를 안내하도록 했습니다. 😄 

<p align="left"><img src="https://user-images.githubusercontent.com/71127966/159407922-8a96bc6d-506b-45a2-a80d-2cd496ec49d0.png" width="40%"></p> 

```swift
// 별도의 파일에 열거형과 static let 으로 Alert 구조체를 미리 만들어뒀습니다. for 재사용
enum AlertManager {
    
    static let errorAlert = Alert(
        title: Text("에러가 발생했어요 🥺"),
        message: Text("앱 종료 후, 개발자에게 문의해주세요"),
        dismissButton: .default(Text("알겠어요"))
    )
}

// 사용하는 부분 예시
.alert(isPresented: $taskListRowViewModel.isErrorOccurred) {
    AlertManager.errorAlert
}
```

Alert 를 띄울 때, 굳이 `뷰모델`을 통해 시키지 않고, `전역으로 사용할 수 있는 Alert 구조체를 바로 사용하는 구조`로 만들었는데요!
괜찮을까요~? 🤔

2022-03-22 05:17 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskEditingView.swift
> +                            try? taskManager.editTask(target: selectedTask, title: newTaskTitle, body: newTaskBody, dueDate: newTaskDueDate)
이 부분도 [위 코멘트](https://github.com/yagom-academy/ios-project-manager/pull/88#discussion_r831777834) 맥락대로, `Alert` 보여줄 수 있도록 처리했습니다!

이제 코드에 더 이상 `try?` 는 없습니다. ㅎㅎㅎ

2022-03-22 09:46 UTC, GREENOVER approved these changes
고생 많으셨습니다!
전체적으로 코드가 이전보다 훨씬 더 MVVM 스러워 졌으며 아주아주 많이 개선되었습니다ㅎㅎ
크게 코멘트 달 부분이 없음으로 다음 스텝 진행해봐도 좋을것 같습니다! 👍

2022-03-22 09:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/TaskFormingView.swift
> +struct TaskFormingView: View {
TaskFormView가 조금 더 자연스럽지 않나라는 의견이 있습니다🤔

2022-03-22 09:46 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/TaskListRowView.swift
> +            }
이건 스타일의 차이이기도 하고 성능을 미묘하게 올릴 수 있는 방법이기도 한데요..!
하위의 뷰들을 아주 잘게 private struct View로 쪼개서 사용한다면 body check 시간이 줄어들고 컴파일 속도가 개선될 여지가 있습니다!
또한 실제 런타임에서도 성능이 좋습니다🙌
지금 정도도 당연히 문제는 없고 잘게 어디까지 쪼개야하는지 이건 정말 선택 사항이고 자신만의 기준을 차차 찾아가면 좋을것 같습니다!

2022-03-22 09:47 UTC, merged

2022-03-22 09:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/TaskListRowView.swift
> +                            try? taskManager.changeTaskStatus(target: task, to: status)
네 좋습니다!
이 부분 코드리뷰 하면서 봤었는데.. 제가 여기 코멘트들을 놓쳤군요😭
토스트 메시지나 얼럿, 모달 같이 공통된 API들은 하신것과 같이 전역적으로 빼서 사용하는것 좋고
저도 딱 이런 형태는 아니지만 전역적으로 사용하는 기조로 사용하고 있습니다!

2022-03-22 10:07 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskFormingView.swift
> +struct TaskFormingView: View {
동의합니다!
instantiate 하는 부분에서, 메서드의 파라미터 `mode`에 인자를 넣을 때 `"Creating/Editing"` 이라는 현재 진행형 늬앙스가 사용되므로, View 구조체 자체가 현재 진행형 단어를 가질 필요가 없을 것 같아요! 😄 

- TaskFormingView -> `TaskFormView` 로 네이밍 수정했습니다! https://github.com/Jager-yoo/ios-project-manager/commit/6b7524dc1ee3c85209da82e01f6783eaaf3e5e03

```swift
// 할일을 '생성'하는(Creating) Modal 로서 호출할 때
TaskFormView(selectedTask: nil, mode: $mainViewModel.isTaskCreating)

// 할일을 '수정'하는(Editing) Modal 로서 호출할 때
TaskFormView(selectedTask: taskListRowViewModel.task, mode: $taskListRowViewModel.isTaskEditing)
```

2022-03-22 10:33 UTC, Jager-yoo commented on ProjectManager/ProjectManager/View/TaskListRowView.swift
> +            }
SwiftUI 관련 WWDC 에서는 View 가 구조체로 아주 가볍기 때문에, 쪼개서 사용하는 것에 부담을 갖지 말라는 내용이 강조되더라구요.

그래서 저도 최대한 분리하기 위해, `View`라는 그룹 안에 `UIComponents`라는 별도의 그룹을 또 만들어서
그 안에 마이너한 View 구조체들을 모아두면서 진행했습니다.

<p align="left"><img src="https://user-images.githubusercontent.com/71127966/159460967-e1b7d35d-d9b6-4d11-ad48-e3c95027b13a.png" width="50%"></p> 

그린이 말씀해주신 부분도 별도로 분리하고 싶었는데요 😢 
이미 저 뷰의 이름이 `TaskListRowView`라서, 여기서 더 분리하면 그 아래 onTapGesture, sheet, onLongPressGesture -> 이런 인터랙션 부분 바로 위까지 잘라서 `PureTaskListRowView`라고 이름을 지어야겠다~ 생각했습니다.

실제로 파일을 분리까지 했는데, MVVM 모델이 적용되어 있다보니, `뷰모델`을 분리한 구조체에 파라미터로 넣어줘야 하더라구요.
넣어주는 거 까진 문제가 아닌데... 
제가 뷰모델을 `private extension`으로 nested 하게 구현해놨다 보니, 분리한 View 구조체 파일에서는 뷰모델을 아예 알지 못하기 때문에 ... 골치 아파지더라구요. 🤦🏻‍♂️ 

이래서 `뷰모델`을 nested 하게 구현하지 말고 별도 파일로 둬야했던 걸까요 ㅎㅎㅎ
리팩토링은 다음 스텝 가서도 계속 고민해볼게요! 감사합니다. 😄