Step 1 : 프로젝트 할일 리스트 구현 (찌루루, 태태)
yagom-academy/ios-project-manager pull request #9
Opened 2021-04-08 13:43 UTC by uuu1101

안녕하세요 도미닉 ! @AppleCEO  🙌
겨우 겨우 구현을 해서.. 💦 11일만에 PR을 보내네요.🚀
리뷰 잘 부탁드립니다 ! 

## 구현사항 🔥

### MainViewController ( 리스트 화면 ) ❗️
- 테이블 뷰 3개를 stack view 에 넣어 기본 UI 를 구성하였습니다. ( header view 는 stack view 바깥 상단에 위치 )
- 기한 지난 날짜 색상 변경은 determineColor 메서드를 통해 바꿔주도록 하였습니다.
- 오른쪽 위 + 버튼 클릭 했을 때와 각각의 셀 클릭 시 나타나는 화면은 DetailViewController 로 구현하였습니다.
- dragDelegate, dropDelegate 를 채택하여 드래그앤 드롭이 가능하도록 하였습니다.
- 각 셀의 스와이프 삭제 구현
- MainViewController 에서 headerView 를 직접 참조하고 있어 드래그 드롭으로 개수가 변경될 때 함께 update 되도록 구현하였습니다.

### DetailViewController ( 추가 및 수정 화면 ) ❗️
- addShadow 메서드를 이용하여 title 과 body 작성하는 부분의 그림자를 넣어주었습니다.
- isEdit 값(수정을 하러 들어온건지, 추가를 하러들어온건지를 구분하기 위함)을 이용해서 DetailViewController 화면의 navigation bar item 이 결정되도록 하였습니다.
    > isEdit = true 이면 cancel, false 이면 edit 으로 표시됨
    > main 리스트 화면에서 + 를 눌러서 띄우게 되면 isEdit 은 기본적으로 false 
    > 셀에서 클릭하여 띄우게 되면 isEdit 은 true 
- edit 버튼을 클릭하기전에는 수정이 불가능하고, 클릭하면 각각의 view(textfield, textview, datepicker) 가 userInteraction 이 가능하도록 토글
- done 버튼을 클릭하면 isEdit 이 true 일경우 화면에 입력된 값을 가져와서 list 에 업데이트하고, isEdit 이 false 이면 새로 append 하여 추가해줍니다. 추가된 todo는 무조건 todoList 에 추가됩니다.
- 모든 수정 이후에는 NotificationCenter 를 통해 tableView 와 headerView 를 reload 해줍니다.

## 고민사항 🤔

- 해당 UI 를 collectionView 로도 구현 가능하고, tableView로도 구현 가능한데 각각의 장점이나 단점이 있을까요?

2021-04-09 03:04 UTC, AppleCEO requested changes
찌루루 & 태태 고생하셨습니다.
노력해서 step1을 완성하신 것 축하드립니다!
고생한 흔적이 많이 보이는 코드들이었습니다.
개선할 점들 남겨놨습니다. 고민하고 성장해보아요!

2021-04-09 03:04 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/Todos.swift
> +              todo = doingList[indexPath.row]
메모를 드래그하다가 이 부분에서 Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444
라는 오류가 발생했어요.
어떤 이유인지 알아보고 개선해 볼 수 있을까요?

2021-04-09 03:04 UTC, AppleCEO commented on ProjectManager/ProjectManager/Model/Todos.swift
> +            }
이 부분 가드문이 너무 많이있는 것 같아요.
어떤 식으로 개선해 볼 수 있을까요?

2021-04-12 10:10 UTC, jae57 commented on ProjectManager/ProjectManager/Controller/MainViewController.swift
> +        }
if 문의 경우 조건에 맞을 때까지 순서대로 체크해가면서 내려가는 반면 
switch문의 경우는 맞는 case( break를 사용한다는 전제 )로 바로 이동하기 때문에 비용적인 측면에서 switch 문이 유리할 거 같습니다.
if 문을 사용한 데에는 별다른 이유는 없었습니다. switch 문으로 수정하는게 좋을거같네요!

2021-04-13 10:25 UTC, uuu1101 commented
안녕하세요 ! 도미닉 @AppleCEO 🙌
리뷰 받은 내용을 토대로 수정해보았습니다. 🔥

# 수정 내용 
>이 부분 조금 복잡한 것 같네요. 함수로 빼내던지 switch문을 사용하던지해서 개선해볼 수 있을까요?
- 다중 if문을 switch문으로 변경하였습니다. if문이 많아지면, 코드를 이해하는데 헷갈리고, 이해하기 힘들 수도 있다고 생각이 들었어요.

>메모를 드래그하다가 이 부분에서 Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444
라는 오류가 발생했어요.
어떤 이유인지 알아보고 개선해 볼 수 있을까요?
- 이 부분은 저희도 확인을 하였는데, drag가 올바른 위치로 drop 되지 않았을 때, 화면상에서는 셀이 그대로 존재하는걸로 보이지만,
실제로는 drag를 시작할 때 해당 List에서 todo를 삭제하기 때문에 존재하지않는 셀을 handling 하려고 해서 발생하는 에러로 확인되었습니다.
따라서, delete 해주는 부분을 completion Handler 안에 넣어서, drag가 올바르게 실행되면 해당 todo를 List에서 삭제해주도록 수정하였습니다. 

>이 부분 가드문이 너무 많이있는 것 같아요.
어떤 식으로 개선해 볼 수 있을까요?
- 이 부분에서 error, data, todo가 잘 들어오는지 확인하는 작업을 하고 다시 guard 문을 병합하는 과정을 생략해서 다시 수정해주었습니다 ! 

>저는 extension을 선언하는 것을 선호하지 않아요.
이 기능을 사용하지 않는 String, DataFormatter 변수들에도 해당 기능이 추가되면서 무거워지는 느낌이 드는 것 같습니다.
따로 이런 하드코딩 문자열들을 묶어놓을 enum 타입을 만든다던지 날짜를 바꾸는 기능을 하는 객체를 만들어보는 것은 어떨까요?
- 이 부분에 대해서도 해당 기능이 추가되면서 무거워지는 부분에 대해서 동감합니다. 👍
 enum 타입과 dateConverter 라는 객체를 만들어주었습니다.
 
 # 구현 사항
- 화면에서 각각의 할일들의 위치를 변경할 수 없어서 , 위치를 변경할 수 있도록 해당 기능을 추가해주었습니다. 👀
해당 코드는 dargDelegate에 있습니다.

2021-04-13 13:51 UTC, merged

2021-04-13 13:52 UTC, AppleCEO commented
고생하셨습니다!