프로젝트 관리 앱 [STEP 2-1] July
yagom-academy/ios-project-manager pull request #92
Opened 2022-03-08 19:56 UTC by July911

안녕하세요 또치 ! (@TTOzzi )
정말 ... 12시전에 보내보려했으나 .. 능력부족으로 늦은 시간에 PR 을 보내게 되었습니다 ! 
이전에 말씀드린 것 처럼 step2-1 은 MVVM과 데이터 통신 객체를 만들어주었습니다.
MVVM도, FireStore도 처음이라 많이 헷갈렸고, 어떻게 인터페이스를 뚫어줘야할지 고민이 많이 되었습니다.
RxSwift로의 리팩토링은 Step2-2에서 할 예정입니다! 

## 1️⃣ Repository -> UseCase -> ViewModel  깊이의 문제 

Repository 에서 데이터를 받아와서 UseCase( 앱의 주요 기능) 그리고 ViewModel(뷰 관련 로직)까지 가는 길이 너무 깊다고 생각이 들었습니다.
기존에 MVC로만 구현을 하다가 MVVM으로 하려니 적응이 안되는건지 아니면 정말 (과하게)깊은건지 고민이 많이 되었습니다. 

## 2️⃣ 중복구현의 문제 

```swift
protocol DataRepository {
    
    var list: [Listable] { get set }
    
    func creat(attributes: [String: Any])
    
    func read(identifier: String) -> Listable?
    
    func update(
        identifier: String,
        how attributes: [String: Any]
    ) 
    
    func delete(identifier: String)
    
    func fetch()
}
```

```swift
protocol CRUDUseCase {

    func createProject(attributes: [String: Any])
    
    func readProject(identifier: String) -> Listable?
    
    func updateProject(
        identifier: String,
        how attributes: [String: Any]
    )
    
    func deleteProject(identifier: String)
    
    func sortProjectProgressState(state: ProgressState) -> [Listable]
}
```

일단 Repository 에 CRUD 기능을 구현을 해놓고 , UseCase가 앱의 주요 기능이라는 말을 듣고 생각해보니 이 역시도 CRUD 기능이여서 네이밍만 다르게 .. 주고 중복(?)구현을 해주었는데, 또치라면 어떻게 하셨을지 궁금합니다. 

## 3️⃣ 파일 정리 

![스크린샷 2022-03-09 오전 4 49 44](https://user-images.githubusercontent.com/90888402/157313888-be5a4903-e732-40de-bd63-45beff92b6f7.jpg)

Presentation 영역의 View와 ViewModel , Domain 영역의 UseCase, Data영역에 Repository를 넣어주었습니다.

## 4️⃣

![스크린샷 2022-03-09 오전 4 54 59](https://user-images.githubusercontent.com/90888402/157314622-e8f4159a-2a59-4fd6-8d55-4e5cbd8c0159.jpg)

MVVM관련 자료를 찾아보다가, UseCase는 Repository 를 가지지 않고 프로토콜을 소유한다고 하는 글을 보았는데 그게 무슨뜻인지 잘 이해가 가지 않습니다. 
이렇게 해주는게 프로토콜을 소유한다고 보아도 되는걸까요?

2022-03-09 16:19 UTC, TTOzzi requested changes
안녕하세요 줄라이! 🙇 
MVVM 도 처음인데, 이렇게 많은 기술스택을 적용해야 한다니 많이 도전적인 스텝이군요.. 🤔 
전에도 말씀드렸듯이 선택과 집중이 필요할 것 같습니다 ㅎㅎ

### Repository -> UseCase -> ViewModel 깊이의 문제

> Repository 에서 데이터를 받아와서 UseCase( 앱의 주요 기능) 그리고 ViewModel(뷰 관련 로직)까지 가는 길이 너무 깊다고 생각이 들었습니다.
> 기존에 MVC로만 구현을 하다가 MVVM으로 하려니 적응이 안되는건지 아니면 정말 (과하게)깊은건지 고민이 많이 되었습니다.

지금까지 구현하신 코드(Repostory~UseCase)론 각각의 계층이 어떤 역할을 하는지 알고 계시고, 그 역할대로 잘 구현하신 것 같아요.
다만 지금은 UseCase에 비즈니스 로직이 거의 없고, ViewModel이 구현되지 않아 과하게 계층화가 되었다고 생각하실 수 있을 것 같습니다 :thinking:
데이터의 원천에서 데이터를 가져오는 로직과 그 데이터를 처리하는 비즈니스 로직, 그리고 사용자로부터 이벤트를 받아 전달해주는 로직을 명확하게 분리하는 것을 생각하면서 지금 미구현된 부분을 구현하시다 보면 지금 해둔 계층화가 마냥 의미 없진 않았다는 것을 느끼실 수 있을 것 같아요.

### 중복구현의 문제

> 일단 Repository 에 CRUD 기능을 구현을 해놓고 , UseCase가 앱의 주요 기능이라는 말을 듣고 생각해보니 이 역시도 CRUD 기능이여서 네이밍만 다르게 .. 주고 중복(?)구현을 해주었는데, 또치라면 어떻게 하셨을지 궁금합니다.

요건 코멘트로도 남겨두긴 했는데, ViewModel에서 UseCase를 사용하는 부분이 구현된 후 좀 더 자세한 피드백을 드릴 수 있을 것 같습니다 🙏 
줄라이가 구현하시면서 필요에 의해 UseCase의 구현부가 바뀔 수도 있구요 :slightly_smiling_face:

### 추상화와 의존성 주입

> MVVM관련 자료를 찾아보다가, UseCase는 Repository 를 가지지 않고 프로토콜을 소유한다고 하는 글을 보았는데 그게 무슨뜻인지 잘 이해가 가지 않습니다.
> 이렇게 해주는게 프로토콜을 소유한다고 보아도 되는걸까요?

넵! 구현하신 것처럼 프로토콜로 추상화하여 주입하는 방식을 이야기하는 것 같습니다.
UseCase는 Repository의 인터페이스만 알고 있고, Repository가 어디서 데이터를 가져오던 UseCase에서 알고있는 인터페이스만 맞춰준다면 동일하게 동작할 수 있도록요!

남겨드린 코멘트에서 이해가 어려운 부분이 있거나, 제가 놓친 부분이 있다면 언제든지 말씀해주세요!
새로운 개념을 적용하느라 많이 어려웠을 것 같은데 고생하셨습니다!! 🙇

2022-03-10 06:53 UTC, July911 commented on ProjectManager/ProjectManager/Cores/SceneDelegate.swift
> +        window?.rootViewController = mainViewController
테스트를 위해서 수정했다가 고치지 못한거 같습니다 . 감사합니다 !!!

2022-03-10 06:53 UTC, July911 commented on ProjectManager/ProjectManager/Data/Database/CoreDataRepository.swift
> +    private let context = (UIApplication.shared.delegate as? AppDelegate)?.persistentContainer.viewContext
이니셜라이저를 통해 주입받도록 수정했습니다. 의존성을 줄일 수 있는 방법을 알려주셔서 감사합니다 :)

2022-03-10 06:54 UTC, July911 commented on ProjectManager/ProjectManager/Data/Database/CoreDataRepository.swift
> +    func creat(attributes: [String : Any]) {
..민망하네요 ..수정했습니다 .!

2022-03-10 06:54 UTC, July911 commented on ProjectManager/ProjectManager/Data/Database/CoreDataRepository.swift
> +                print(error.localizedDescription)
if DEBUG 라는게 있었네요 ..감사합니다 ! snippet 에 등록해놓고 유용하게 쓰겠습니다 !

2022-03-10 06:55 UTC, July911 commented on ProjectManager/ProjectManager/Data/Database/CoreDataRepository.swift
> +                print(error.localizedDescription)
print 문을 모두 바꿔주었습니다 !

2022-03-10 06:55 UTC, July911 commented on ProjectManager/ProjectManager/Data/Database/CoreDataRepository.swift
> +    var list = [Listable]()
프로토콜 기본구현에서 list를 삭제하고, private(set) 을 사용하였습니다 !

2022-03-10 06:56 UTC, July911 commented on ProjectManager/ProjectManager/Data/Database/FireBaseRepositoryr.swift
> +    var dataBase = Firestore.firestore()
상수로 선언해주고 접근 제어자도 수정했습니다 ! 인터페이스만 알도록 계층을 분리한다는 개념을 이해하는데 큰 도움이 되었습니다 감사합니다 !

2022-03-10 06:57 UTC, July911 commented on ProjectManager/ProjectManager/Data/Database/FireBaseRepositoryr.swift
> +    var list = [Listable]()
수정했습니다 !

2022-03-10 06:58 UTC, July911 commented on ProjectManager/ProjectManager/Data/Database/FireBaseRepositoryr.swift
> +        to collectionReference: String = "ProjectManager"
다른 Collection을 등록할 일이 추후에 생길 수도 있어서 이렇게 구현했습니다. 또한 ProjectManager 라는 콜렉션을 대부분의 상황에서 쓸 것 같아 기본값으로 남겨두었습니다 !

2022-03-10 06:58 UTC, July911 commented on ProjectManager/ProjectManager/Data/Database/FireBaseRepositoryr.swift
> +        return Firestore.firestore().collection(collectionReference)
수정했습니다 ! ...

2022-03-10 07:01 UTC, July911 commented on ProjectManager/ProjectManager/Data/Database/RepositoryChecker.swift
> +    }
현재 Repository 의 상태를 나타낼 수 있도록 static으로 구현했습니다. private init 같은 경우는 불필요한 인스턴스 생성을 막아주기 위해서 넣었습니다 !

2022-03-10 07:02 UTC, July911 commented on ProjectManager/ProjectManager/Data/Database/RepositoryFactory.swift
> +    public func assignListManger(repository: RepositoryType) -> DataRepository {
수정했습니다. 컨벤션을 모두 접근제어자를 붙여줄까 하다가 private만 붙여주는 방향으로 바꾸었습니다 !

2022-03-10 07:03 UTC, July911 commented on ProjectManager/ProjectManager/Data/Project.swift
> +    var progressState: String
UUID.uuidstring을 통해 identifier 를 만들어주고 , fireStore 의 document 이름으로 설정하려고 이렇게 구현했으나, 더 윗 단에서 UUID를 내려주면 될 것 같습니다. 수정했습니다 !

2022-03-10 07:04 UTC, July911 commented on ProjectManager/ProjectManager/Data/Project.swift
> +}
앗 .. 이런게 있었군요 .. 감사합니다 !

2022-03-10 07:04 UTC, July911 commented on ProjectManager/ProjectManager/Data/Protocol/DataRepository.swift
> +    var list: [Listable] { get set }
인터페이스로만 소통하도록 하였습니다 ! list는 private으로 감춰주고, 프로토콜 기본구현에서 제외시켰습니다 !

2022-03-10 07:05 UTC, July911 commented on ProjectManager/ProjectManager/Domain/CRUDUseCase.swift
> +protocol CRUDUseCase {
MVVM 의 useCase 사용이 처음이라 .. 조금 더 직관적이고 구체적인 이름이 떠오르질 않습니다 ... 도와주세요 ..

2022-03-10 07:16 UTC, July911 commented on ProjectManager/ProjectManager/Domain/CRUDUseCase.swift
> +    func sortProjectProgressState(state: ProgressState) -> [Listable]
ViewModel을 구현하지 않아 아직 이해는 잘 안되지만 적용해보도록 하겠습니다 !

2022-03-10 11:28 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Database/CoreDataRepository.swift
> +    private(set) var list = [Listable]()
`DataRepository` 프로토콜의 조건으로 `list` 가 없어졌으니 그냥 `private` 으로 선언해줘도 될 것 같아요.

2022-03-10 11:28 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Database/FireBaseRepositoryr.swift
> +                    lists.append(project ?? Project(name: "", detail: "", deadline: Date(), indentifier: "123", progressState: ProgressState.doing.description))
받아온 데이터를 `Project` 로 변환하는데에 실패했다면, 더미 데이터를 넣어주기보단 잘못된 데이터로 간주하고 무시하거나 에러 처리를 해줘야 하지 않을까요? 🤔

2022-03-10 11:28 UTC, TTOzzi commented on ProjectManager/ProjectManager/Data/Database/RepositoryFactory.swift
> +    enum DatabaseError: Error, CaseIterable {
요기 `CaseIterable`은 어떤 의도로 채택해주셨는지 궁금해요! 👀

2022-03-10 11:28 UTC, TTOzzi commented on ProjectManager/ProjectManager/Domain/CRUDUseCase.swift
> +protocol CRUDUseCase {
음 그냥 단순하게 `Project`를 관리하는 `UseCase`이니 `ProjectManageUseCase` 정도는 어떨까요? 라고 하려 했는데 구체타입과 이름이 겹치는군요 🤔 
요런 추상화 계층을 두기 위한 프로토콜은 `구체타입 이름 - Type`(`ProjectManagerUseCaseType`) 으로 네이밍하기도 합니다.

2022-03-10 11:30 UTC, TTOzzi approved these changes
고생하셨습니다~! 🙇 
일단 머지해달라고 요청해주셨으니 머지할게요!
수정하지 못한 부분은 다음 스텝에서 채워보아요 🚀

2022-03-10 11:31 UTC, merged