프로젝트관리앱 [STEP 2-2] 신나
yagom-academy/ios-project-manager pull request #93
Opened 2022-03-09 01:26 UTC by smart8612

안녕하세요 그린 @GREENOVER ! 신나 @smart8612 입니다!~ 

프로젝트 관리앱 프로젝트 Step 2-2 UI레이아웃 구현에 대한 리뷰 부탁드리고자 PR 요청을 올립니다!
구현하다보니 Step 2-3 의 내용도 조금 포함되었습니다. ㅜㅜ
잘부탁드립니다!

## 고민해본 점

### 프로젝트의 View 를 다음의 구조로 모듈화 시켜서 구현해보았습니다.

![IMG_8E2B0CC6EC0F-1](https://user-images.githubusercontent.com/25794814/157353842-3608b2f4-9833-44fb-9ac7-9d4f055df65f.jpeg)

![IMG_B2699DFDD93A-1](https://user-images.githubusercontent.com/25794814/157353872-480a159f-f040-4a29-b3df-5c260f74b5e2.jpeg)

![IMG_1A96886EF230-1](https://user-images.githubusercontent.com/25794814/157353908-e7de034d-10b7-44ab-86a5-4258f78f71a5.jpeg)

---

****NavigationView****

> ContentView.swift 파일에 구현되었습니다.
> 
- 내비게이션 계층 구조에서 보이는 경로를 나타내는 View 스택을 제시하기 위한 View 입니다.
- 현재 View의 컨테이너를 NavigationView로 감싸주어 Navigation Bar 에 필요기능을 구현하였습니다.
- [https://developer.apple.com/documentation/swiftui/navigationview[](https://developer.apple.com/documentation/swiftui/view/navigationviewstyle(_:))](https://developer.apple.com/documentation/swiftui/navigationview)
- iPad 에서 Navigation View 를 사용했을 때 자동으로 SplitView의 컬럼 스타일이 사용되는 문제점이 있었습니다.
- 확인해보니 Navigation View 도 스타일을 지정해줄 수 있어서 일반적인 Navigation 스타일을 의미하는 Stack 으로 설정해주었습니다.
- [https://developer.apple.com/documentation/swiftui/view/navigationviewstyle(_:)[](https://stackoverflow.com/questions/69196530/swiftui-changing-navigation-bar-background-color-for-inline-navigationbartitledi)](https://developer.apple.com/documentation/swiftui/view/navigationviewstyle(_:))
- Navigation Bar Button Item 추가하기위해 ToolBar 를 활용하였습니다.

**Navigation Title**

- View modifier 중에서 ``navigationTitle`` 를 사용하여 지정해주었습니다.
- [https://stackoverflow.com/questions/69196530/swiftui-changing-navigation-bar-background-color-for-inline-navigationbartitledi[](https://developer.apple.com/documentation/swiftui/displaying-data-in-lists)](https://stackoverflow.com/questions/69196530/swiftui-changing-navigation-bar-background-color-for-inline-navigationbartitledi)

---

**List**

> TaskListView.swift 파일에 구현되었습니다.
> 
- Iteration 을 위해 Entity 타입을 준비해줘야 하는 과정이 있었습니다,
- 이전에 엔티티 타입에 Identifiable 프로토콜을 채택해주었기에
- List View 로 감싸고 View 내부에서 ForEach View 로 Iteration 돌려주어 View를 생성해줄 수 있었습니다.
- [https://developer.apple.com/documentation/swiftui/displaying-data-in-lists[](https://developer.apple.com/documentation/swiftui/view/sheet(ispresented:ondismiss:content:))](https://developer.apple.com/documentation/swiftui/displaying-data-in-lists)

**Cell**

> TaskRowView.swift 파일에 구현되었습니다.
> 
- 하나의 셀에 들어갈 레이아웃을 분리해서 디자인 해주었습니다.
- 글자수를 제어하기 위해 linelimit 수정자를 사용해보았습니다.

**Stack View**

- 생성자를 통해 alignment, spacing 등을 조정할 수 있었습니다.

**sheet, alert 등등**

- 띄어줄 때 Modifier 를 사용합니다.
- 선언형 프레임워크 답게, View 의 State 등의 상태 조건을 바꾸어 Sheet 등을 띄우는 구조로 되어있었습니다.
- [https://developer.apple.com/documentation/swiftui/view/sheet(ispresented:ondismiss:content:)[](https://levelup.gitconnected.com/how-to-show-text-inside-a-circle-with-swiftui-93a375d571f8)](https://developer.apple.com/documentation/swiftui/view/sheet(ispresented:ondismiss:content:))

**Shape 모양 숫자 View 만들기**

- SwiftUI 에서 ZStack 을 사용하여 겹처진 UI 를 구현할 수 있습니다
- overlay, background 와 같은 View 수정자를 활용해서도 겹처진 UI를 구현할 수 있었습니다.
- background 를 사용하면 위에 나와있는 View의 intrinsic 크기에 맞춰진다는 점을 고려하여
- background 를 통해 숫자와 곂처진 원형 모양의 UI 를 구현해보았습니다.
- [https://levelup.gitconnected.com/how-to-show-text-inside-a-circle-with-swiftui-93a375d571f8[](https://developer.apple.com/documentation/swiftui/ellipse/swipeactions(edge:allowsfullswipe:content:)/)](https://levelup.gitconnected.com/how-to-show-text-inside-a-circle-with-swiftui-93a375d571f8)

---

### SwipeAction에서의 고민

- SwiftUI 상에서 List Cell에 SwipeAction 기능을 추가하기 위해 공식문서를 찾았지만 문제가 있었습니다.
- SwiftUI 상에서 SwipeAction에 대한 수정자들은 iOS15 이상만을 지원한다는 점이었습니다.
- [https://developer.apple.com/documentation/swiftui/ellipse/swipeactions(edge:allowsfullswipe:content:)/[](https://developer.apple.com/documentation/swiftui/view/contextmenu(menuitems:))](https://developer.apple.com/documentation/swiftui/ellipse/swipeactions(edge:allowsfullswipe:content:)/)
- 우리는 iOS 14 도 지원해야 했기 때문에 대안으로 List에서 ForEach View에 onDelete 수정자를 활용하여 삭제 swipe action 을 추가하는 방향으로 판단하였습니다
    
        
<img width="648" alt="Screen Shot 2022-03-09 at 9 58 54 AM" src="https://user-images.githubusercontent.com/25794814/157354057-6e8b09a5-d497-4477-8c02-c013c0b6a3c3.png">

### 셀 길게 눌렀을 때 task status 전환 기능 구현

> TaskListView.swift 에 구현되었습니다.
> 
- popover, pagesheet 중 요건 사항이 열려있어서 어느 것으로 구현할 까 고민해보았습니다.
- 그러던 중 Apple 의 노트, 메일 등의 앱에서 어떤 방식을 차용하고 있는지 찾아보게 되었습니다
- SwiftUI 가 제공하는 방식 중에서 가장 유사하게 동작하는 메커니즘으로 contextMenu 를 찾을 수 있었습니다.
- [https://developer.apple.com/documentation/swiftui/view/contextmenu(menuitems:)[](https://stackoverflow.com/questions/69653554/get-attributegraph-cycle-detected-error-when-changing-disabled-state-of-text/69653555#69653555)](https://developer.apple.com/documentation/swiftui/view/contextmenu(menuitems:))

![Untitled](https://user-images.githubusercontent.com/25794814/157354138-e5fc7c6d-b0f4-4746-bf0a-dadecb0be916.png)

---

## 문제 상황을 해결해본 점

### Task 내용을 수정하고 수정 내용을 취소했을 때 Cycle 감지 오류가 발생하는 문제가 있었습니다.

<img width="701" alt="Screen Shot 2022-03-09 at 9 52 32 AM" src="https://user-images.githubusercontent.com/25794814/157354208-80a723ae-0482-4a32-afb0-0d62b4787a85.png">

<img width="650" alt="Screen Shot 2022-03-09 at 9 51 46 AM" src="https://user-images.githubusercontent.com/25794814/157354197-aacd1ffe-4608-4e00-a9c1-94181919d863.png">

- StackOverFlow 를 통해 탐색한 결과 키보드가 보이는 상황(TextEditor가 FirstResponder일 때)에서 편집 기능을 비활성화 시킬 경우 문제가 발생하는 케이스임을 확인할 수 있었습니다.
- 키보드 사라짐에 대한 제어 역할은 어플리케이션이 갖고 있기 때문에 편집기능 비활성화 시키기 전에 키보드를 사라지게 하는 작업을 선 수행하여 위 문제를 해결하였습니다.
- [https://stackoverflow.com/questions/69653554/get-attributegraph-cycle-detected-error-when-changing-disabled-state-of-text/69653555#69653555](https://stackoverflow.com/questions/69653554/get-attributegraph-cycle-detected-error-when-changing-disabled-state-of-text/69653555#69653555)

---

## 의문을 가진 점

- ViewModel이 Logic 과 Data 를 캡슐화 하고 있기에 ContentView 하위 계층간에 공통으로 사용된다는 측면에서 EnvironmentObject를 채택해보았습니다. View 하위 계층에서 공통으로 사용할 싱글턴 패턴과 유사하게 동작하게 되기에 각 모듈화된 View 타입에 ViewModel 을 주입해줄 필요가 없어진다는 측면을 고려해서 도입 했는데, 이 방식으로 구현할 때 제가 생각하지 못한 어떤 문제점이 있을지 판단이 잘 서지 않습니다.
- 현재 프로젝트 중 새로운 Task 를 생성하는 작업에서 TaskFormView UI가 나타내는 상태값을 상위 View인 TaskCreateView 에 선언된 state 값(title, date, description)을 하위 view에서 binding 하는 형태로 설계하게 되었습니다.
원래는 TaskFormView에 직접 state 값을 선언하여 외부에서 이 View 의 프로퍼티를 통해 UI 값을 불러오도록 설계하고 싶었는데, 이상하게 프로퍼티를 통해 불러와지지 않는 문제점이 있었기 때문입니다.

2022-03-09 11:26 UTC, GREENOVER requested changes
@smart8612 
스텝 2-2 고생하셨습니다 신나!👍
전체적으로 잘 이해하고 구현을 완성도 있게 많이 해주셨네요!
뷰를 잘 나눠서 가독성도 좋았습니다ㅎㅎ
조금 코멘트가 있긴한데 대부분 스타일에 관한 마이너한 부분이긴 합니다.
***
### 칭찬 드리고 싶은 부분
- 뷰를 잘게 잘 쪼개서 구조적으로 만드신점 💯
- 뷰모델과 뷰의 관심사를 잘 분리해서 가져가신점 💯
- UI에 대해 이질감이 없이 잘 구현해주신점 💯
***
### 고민하셨던 부분에 대한 저의 의견
1. 프로젝트의 View 를 다음의 구조로 모듈화 시켜서 구현해보았습니다.
- 전체적으로 잘 이해되었고 올바른 방향으로 잘 해주셨다고 생각합니다.
다만 코멘트에서도 남겨보았는데 뷰 전환에서 Navigation 방식이 없는것 같은데 Navigation 뷰로 구성해주신 부분이 궁금합니다!
제가 혹시 놓쳤거나 잘못 이해한 부분이 있으면 말씀해주세요ㅎㅎ
또한 뷰들을 잘 나눠주셨는데 프로퍼티보단 뷰 구조체로 만들어 사용하는게 좀 더 적절하고 성능상 이점이 있다고 생각합니다.
한 뷰에 프로퍼티들이 body 체크 시간도 높아지고 컴파일 타임에 불리하다고 생각합니다.
2. SwipeAction에서의 고민
- 지금 방향도 올바르고 좋다 생각합니다.
다만 SwipeAction에 대해 알아보신것처럼 iOS 15 이상에서 지원하기에 그 밑에서 사용못해서 그 방향으로 가신다면,
하나 방법은 있습니다.
Gesture를 직접 스와이프 액션처럼 구현해주는것입니다.
해줄순 있지만 그렇게 뷰에서 해줄 필요가 있을까란 생각이 있기에 지금 방향이 더 적합하지 않나 생각합니다.
3. 셀 길게 눌렀을 때 task status 전환 기능 구현
- 오! 좋습니다ㅎㅎ 덧붙일 코멘트가 없습니다!
***
### 의문을 가지신점에 대한 저의 의견
1. ViewModel이 Logic 과 Data 를 캡슐화 하고 있기에 ContentView 하위 계층간에 공통으로 사용된다는 측면에서 EnvironmentObject를 채택해보았습니다. View 하위 계층에서 공통으로 사용할 싱글턴 패턴과 유사하게 동작하게 되기에 각 모듈화된 View 타입에 ViewModel 을 주입해줄 필요가 없어진다는 측면을 고려해서 도입 했는데, 이 방식으로 구현할 때 제가 생각하지 못한 어떤 문제점이 있을지 판단이 잘 서지 않습니다
- 음 저도 이부분에서 생각을 해봤을때 우선 현재 방식에서 문제가 되는 부분은 크게 없습니다.
다만 추후 뷰가 많아지고 서로 독립적으로 되어야할때 사실 후자쪽에 말씀하셨던것처럼 뷰에 뷰모델을 주입할 필요가 없지만 나중에 뷰에서 독립적인 테스트가 될까? 라는 생각도 있습니다.
또한 이렇게되면 한 뷰 모델에서 모든걸 가져가야하기 때문에 비대해지지 않을까 싶습니다.
정리하자면 지금 정도에서는 전혀 문제가 없지만 뷰에 뷰모델을 주입해 사용하는게 대중적으로 MVVM의 근본적인 방향이라고는 생각합니다!
2. 현재 프로젝트 중 새로운 Task 를 생성하는 작업에서 TaskFormView UI가 나타내는 상태값을 상위 View인 TaskCreateView 에 선언된 state 값(title, date, description)을 하위 view에서 binding 하는 형태로 설계하게 되었습니다.
원래는 TaskFormView에 직접 state 값을 선언하여 외부에서 이 View 의 프로퍼티를 통해 UI 값을 불러오도록 설계하고 싶었는데, 이상하게 프로퍼티를 통해 불러와지지 않는 문제점이 있었기 때문입니다.
- 아마 하위단으로 연결되는 뷰에서는 겪으신것처럼 state를 직접 선언해 프로퍼티로 연결해줘도 어떻게 최초값으론 불러지더라도 이후 변화되는 값에 대한 트래킹과 리렌더링은 안되긴할거에요..!
흐음.. 올바른 방향으로 수정을 해주셨는데 근본적으로 안되는 문제에 대한 원인을 탐구해보자면 SwiftUI에서의 뷰 구조와 프로퍼티 바인딩에 대해 좀 더 학습해보면 실마리가 나오지 않을까 싶습니다🤔
***
신나 바쁘신데 완성도 있는 스텝2-2 고생하셨어요 정말 ㅎㅎ
코멘트와 답변을 달아봤는데 한번 쭉 확인 및 수정해보시고 리뷰 재요청을 주시면 감사하겠습니다!
화이팅입니다🙌

2022-03-10 06:30 UTC, smart8612 commented on ProjectManager/ProjectManager/View/ContentView.swift
>  struct ContentView: View {
* 동의합니다 해당 View 의 역할을 잘 설명하지 못하는 네이밍인 것 같습니다!
* ProjectManagerMainView 로 네이밍 수정 진행하였습니다!
* (플젝 초기에 SwiftUI View 로 템플릿 생성한 타입을 그대로 사용해서 이런 네이밍이 유지되었습니다 ㅎㅎ )

2022-03-10 06:44 UTC, smart8612 commented on ProjectManager/ProjectManager/View/ContentView.swift
> +    @State private var isShowingSheet = false
* [SwiftUI - State and Data Flow](https://developer.apple.com/documentation/swiftui/state-and-data-flow) 에서 자세한 역할을 찾아볼 수 있었습니다.`

### @EnvironmentObject
* [reference](https://developer.apple.com/documentation/swiftui/environmentobject)
* `@EnvironmentObject` 는 현재 프로젝트의 ViewModel 처럼 `ObservableObject` 프로토콜을 충족하는 외부의 모델 데이터를 연결하는데 사용되는 `property wrapper` 이며 윈도우의 환경변수처럼 `environment` 에 담겨져 있는 `ObservableObject` 의 데이터를 불러오는데 사용됩니다.
* `@EnvironmentObject` 의 특징으로 부모 혹은 자식 View 간에 observable object 를 공급할 수 있습니다.

### @State
* 일시적인 UI 상태값을 관리할 때 사용되는 property wrapper 입니다.
* SwiftUI 상에서 값을 읽고(read) 쓸 수(write) 있습니다
* 값을 읽고 쓸 수 있는 수단이기에 값을 읽을 때에는 [wrappedValue](https://developer.apple.com/documentatio.n/swiftui/state/wrappedvalue) 바인딩 하기위해 $ 표시를 사용합니다.

2022-03-10 06:47 UTC, smart8612 commented on ProjectManager/ProjectManager/View/ContentView.swift
> +    @State private var isShowingSheet = false
추가적으로 위 코드에서 @State 는 sheet 를 보여주기 위한 이벤트 발생 근원 데이터의 목적으로 사용하고 있었습니다.
다시 말해서 버튼이 클릭되면 -> @State 불리언 변수의 값을 변경하고 -> @State 값이 변경 되었을 때 영향을 받는 View (sheet) 를 다시 그린다! 라는 동작 논리 입니다!

2022-03-10 06:56 UTC, smart8612 commented on ProjectManager/ProjectManager/View/ContentView.swift
> +    @State private var isShowingSheet = false
* 위 네이밍을 참조했던 공식 문서 예시 자료가 존재합니다!
* [sheet(isPresented:onDismiss:content:)](https://developer.apple.com/documentation/swiftui/view/sheet(ispresented:ondismiss:content:))
* 하지만 위 변수가 UI가 보이는지 안보이는지의 상태를 의미하는 변수이기에 진행형의 ing 를 사용하는 것이 저의 눈에도 어색해보였습니다.
* 따라서 isShowSheet 로 네이밍 수정하였습니다!
<img width="616" alt="Screen Shot 2022-03-10 at 3 55 04 PM" src="https://user-images.githubusercontent.com/25794814/157605986-409305a2-888f-42de-9c24-8a3f61716ff6.png">

2022-03-10 07:07 UTC, smart8612 commented on ProjectManager/ProjectManager/View/ContentView.swift
> +                TaskListView(name: "DONE", taskType: .done)
* 동의합니다. TaskStatus 열거형 타입에 CaseIterable 프토로콜을 붙여서 케이스 순회가 가능하도록 구현해두었습니다.
* ForEach 를 통해 열거형 타입의 케이스를 스스로 순회하면서 View를 그리도록 선언해두었습니다!
* 추가적으로 이전 TaskListView 생성자에서 받고있는 name 파라미터도 제거하여 taskType 하나의 정보만으로 처리할 수 있도록 생성자를 수정하였습니다!
<img width="426" alt="Screen Shot 2022-03-10 at 4 07 01 PM" src="https://user-images.githubusercontent.com/25794814/157607600-c18bd899-3e5d-432b-8b8f-5d4e321f8f4b.png">

2022-03-10 07:17 UTC, smart8612 commented on ProjectManager/ProjectManager/View/ContentView.swift
> +        NavigationView {
* SwiftUI NavigationView 는 PresentationContainer의 일종으로 사용자가 계층적 구조의 앱에서 여러 부분을 손쉽게 이동할 수 있는 인터페이스 구조를 제공합니다.
* [PresentationContainer](https://developer.apple.com/documentation/swiftui/presentation-containers)
* [NavigationView](https://developer.apple.com/documentation/swiftui/navigationview/)
* UIKit 에서 가장 유사한 개념으로 UINavigationController 가 존재합니다.
* 상단에 Navigation Bar 를 추가하여 Title 과 Bar Button 을 표현하면 기획 상의 이미지와 가장 유사하게 동작할 수 있다고 생각하였습니다.
* UIKit 에서도 UIView의 일종인 Navigation Bar를 직접 화면에 올려서 제어하는 방식도 있지만 Navigation Controller 를 활용하면 더욱 효율적으로 구현할 수 있었던 경험이 있었습니다.
* SwiftUI 에서 이와 유사한 논리로 앱에서 계층적 View 탐색을 사용하지는 않으나 Navigation Bar를 손쉽게 제어할 수 있도록 Navigation View 를 도입해보았습니다.

2022-03-10 08:18 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskRowView.swift
> +struct TaskRowView: View {
동의합니다! 네이밍을 TaskListRowView 로 수정 진행하였습니다!~

2022-03-10 08:21 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +                            contextMenuView(task, taskType)
* TaskListContextMenuView 타입의 별도의 View 로 분리해주었습니다.
* 외부에서는 contextMenu 가 호출된 cell이 갖은 Task 만 TaskListContextMenuView 로 넘겨주었을 때, 스스로 처리하도록 모듈화 구현 시키는 방향으로 개선시켜보았습니다
<img width="662" alt="Screen Shot 2022-03-10 at 5 21 28 PM" src="https://user-images.githubusercontent.com/25794814/157618685-0ef13949-2185-4fd6-b45d-80bf42399ec2.png">
!

2022-03-10 08:22 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +                viewModel.remove(tasks[indexSet])
고맙습니다!~ 최대한 View에 로직이 보이지 않도록 분리해주려고 시도해보고 있습니다!~

2022-03-10 08:46 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskRowView.swift
> +    }()
* dateFormatter 인스턴스를 ViewModel 로 이동 구현하였습니다.
* 외부에서 ViewModel에게 task 를 던져주면 포멧팅된 date 를 반환하도록 API 를 설계해보았습니다만...
* 단방향 데이터 흐름을 깨고 있어서 좀 더 다른 방식을 추가적으로 고민해보고 있습니다. ㅠㅠ

2022-03-10 08:47 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskRowView.swift
> +    }()
<img width="524" alt="Screen Shot 2022-03-10 at 5 47 02 PM" src="https://user-images.githubusercontent.com/25794814/157624412-e54090ca-fdef-4db1-a20e-57ceec5b6542.png">
<img width="494" alt="Screen Shot 2022-03-10 at 5 47 11 PM" src="https://user-images.githubusercontent.com/25794814/157624512-3e9fca7e-827e-4482-b814-318d7aa324a9.png">

2022-03-10 08:55 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +                            contextMenuView(task, taskType)
훨씬 좋네요 👍👍👍

2022-03-10 08:57 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/TaskRowView.swift
> +    }()
아하 단방향의 데이터 흐름을 깬다고 말씀하신게 어떤 포인트인지 구체적으로 알 수 있을까요~?🙋🏻

2022-03-10 09:00 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +    private var taskList: some View {
* 연산 프로퍼티가 아닌 별도의 View로 분리 구현해주고 있는데 확실히 가시적인 퍼포먼스 차이가 존재합니다.
* 기존의 방식에서는 task 상태를 옮길 때 UI 응답이 약간 느렸는데, 지금은 빠르게 응답하고 있습니다!
* 말 그대로 대박입니다!

2022-03-10 09:01 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskListView.swift
> +            taskList
별도의 View 타입으로 분리 구현 하면서 View 접미사가 붙도록 네이밍 진행해보았습니다!

2022-03-10 09:02 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskRowView.swift
> +            dueDate
별도의 View 타입으로 분리 구현 하면서 View 접미사가 붙도록 네이밍 진행해보았습니다!

2022-03-10 09:04 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskRowView.swift
> +        let validDate = Calendar.current.date(byAdding: .day, value: -1, to: Date())!
앗! 저거 임시로 적어둔 코드 였는데, 제가 리팩터링 할 때 누락했나봅니다!~
해당 로직을 ViewModel 로 이동하면서 guard 구문을 통한 옵셔널 바인딩을 진행하였습니다!
<img width="489" alt="Screen Shot 2022-03-10 at 6 04 01 PM" src="https://user-images.githubusercontent.com/25794814/157627826-6295d1b2-9311-4774-a941-0175abe542a5.png">

2022-03-10 09:06 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskRowView.swift
> +        }
제안해주신 방법이 더 효율적인 표현으로 인정합니다!!~
그린이 제안해주신 방식으로 코드를 개선시켰습니다!
<img width="572" alt="Screen Shot 2022-03-10 at 6 06 31 PM" src="https://user-images.githubusercontent.com/25794814/157628258-b979f39c-3cb6-4d7a-9d47-8468e2427bb0.png">

2022-03-10 09:08 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskRowView.swift
> +    private var dueDate: some View {
View 로 분리 구현 진행하였습니다!~
<img width="416" alt="Screen Shot 2022-03-10 at 6 07 37 PM" src="https://user-images.githubusercontent.com/25794814/157628436-46c12fb7-e692-4885-b513-f656a31c2a60.png">

2022-03-10 09:14 UTC, smart8612 commented on ProjectManager/ProjectManager/Model/Entity/TaskStatus.swift
> +    var id: UUID { UUID() }
swiftlint config 의 type_name 에서 최소 2개 이상으로 설정해줌으로써 오류 메시지 문제를 해결하였습니다!

2022-03-10 11:22 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskRowView.swift
> +    }()
View 에서 갖고 있던 task 를 다시 ViewModel 이 전달 받아서 가공하고 다시 View 에게 전달하는 처리 과정이 MVC 패턴에서 Controller 중간 객체가 일처리하는 흐름과 유사하게 느껴졌습니다!

2022-03-10 11:46 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskFormView.swift
> +            descriptionEditor
모두 연산 프로퍼티가 아닌 별도의 View 구조체 타입으로 분리 구현해주었습니다!
![Screen Shot 2022-03-10 at 8 46 04 PM](https://user-images.githubusercontent.com/25794814/157655512-975303ad-19c5-4e52-b9ea-3ffe3198a1dd.png)

2022-03-10 11:52 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/TaskRowView.swift
> +    }()
아하 그런거라면 저는 조금 의견이 다른데,
애초에 View에서는 task를 갖고 있지 않는것이 더 맞지 않을까해요🤔
뷰는 정말 딱 뷰모델을 얹어주고 갈아끼우고 나타내주는,
사용자의 인터렉션만 받아올 수 있는 그이상의 역할을 하지 않는것이 적합하지 않을까합니다🤔

2022-03-11 00:35 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskDetailView.swift
> +                            }
View 의 선언부에 복잡한 로직이 들어가지 않도록 최대한 분리 구현 해주었습니다!
기본적으로는 로직을 ViewModel 을 통해 분리하는 기조를 가졌지만
View 에 표현되는 기능의 경우 함수 분리를 진행해주었습니다.

2022-03-11 00:47 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskCreateView.swift
> +        let taskForm = TaskFormView(title: $title, date: $date, description: $description)
변수로 분리해서 재사용할 부분이 없어서 해당 코드 부분이 제거 되었습니다!

2022-03-11 01:00 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskDetailView.swift
> +    @State private var title: String
### 참조
* [SwiftUI - Managing User Interface State](https://developer.apple.com/documentation/swiftui/managing-user-interface-state)
* View 계층 구조 내에서 각 View 의 데이터를 캡슐화 하여 View를 재사용할 수 있도록 만들어줍니다.
<img width="453" alt="Screen Shot 2022-03-11 at 9 54 39 AM" src="https://user-images.githubusercontent.com/25794814/157780807-bb61b402-e82e-4751-88bc-81524082febb.png">

### @Binding
* 상위 View에 선언된 State 를 하위 View 에서 공유하여 사용할 수 있습니다.
* Binding property wrapper 를 사용했을 때 상위 View의 각종 상태값을 하위 View 에서 참조할 수 있다는 의미입니다.

### @State
* View에서 변경할 수 있는 임시 값을 보관하는 변수를 선언할 때 사용되는 property wrapper 입니다.

2022-03-11 01:03 UTC, smart8612 commented on ProjectManager/ProjectManager/ViewModel/ProjectManagerViewModel.swift
> +        try? model.create(newTask)
이거 수정해보려고 했는데, SwiftUI View 에서 예외처리가 쉽지 않은 것 같습니다.
우선 이전 버전의 SwiftUI 에서는 각종 Alert, Sheet 등을 modifier 가 아닌 별도의 View 형태로 제공했던 것 같은데, 현재의 SwiftUI 에서는 modifier 형태로 제공하면서, 함수 내에서 별도의 View 가 없으면 Alert 등을 띄우기 어려운 상태입니다 ㅜㅜ

2022-03-12 01:58 UTC, GREENOVER approved these changes
고생하셨습니다 신나!
전체적으로 훨씬 더 분리가 잘되었고 개선 리팩토링이 훌륭합니다👍
마이너한 코멘트 몇개 달아보았어요ㅎㅎ
아.. 이전 리뷰에서 코멘트 못한게 있더라구요ㅠ
```swift
enum TaskMemoryManagerError: Error {
    case taskNotExist
}
```
요 Error는 뷰 내부에 위치시킬 필요는 없을것 같습니다!
전반적으로 리팩토링이 잘되었는데 뷰 구조체 내부에 뷰를 위한 요소뿐 아니라 너무 다양한 친구들이 담겨있는 부분이 좀 있더라구요!
그 부분들 한번 이후 스텝에서 체크해보면 좋겠습니다😀
머지하겠습니다🙌

2022-03-12 01:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/TaskListViewModule/TaskListContainerView.swift
> +    }
실제로 이 프로퍼티는 어떻게 어디서 사용되나요?🙋🏻

2022-03-12 01:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/ProjectManagerMainView.swift
> +    }
요 메서드를 별도로 따로 뺀 이유가 있을까요?
28번째 라인에서 `Button(action: { sheetViewModel.toggleSheetCondition() }`과 같이 바로 사용할 수도 있을것 같아서요🙋🏻

2022-03-12 01:58 UTC, GREENOVER commented on ProjectManager/ProjectManager/View/TaskFormDetailSheetView.swift
> +    }
정말 스타일의 차이기는 한데 가독성을 신경써주셔서 별도 프라이빗 메서드로 따로 구현체를 빼고 호출해준 이유일까요~?🙋🏻
위에 코멘트에서 언급한것처럼 바로 구현체를 action에서 넣어주는것과 요런 방식에서 성능의 차이는 없을까요?🤔
뷰에 이러한 메서드가 내부적으로 존재하는게 의도하신건지 궁금합니다😀

2022-03-12 01:58 UTC, merged

2022-03-15 01:12 UTC, smart8612 commented on ProjectManager/ProjectManager/View/TaskListViewModule/TaskListContainerView.swift
> +    }
사용되지 않는 프로퍼티를 정리해주겠습니다!!~

2022-03-15 01:14 UTC, smart8612 commented on ProjectManager/ProjectManager/View/ProjectManagerMainView.swift
> +    }
연산 프로퍼티를 분리해준 것들은 보통의 경우 가독성 측면으로 고려한 부분이 강합니다!
View를 선언한 부분과 행위 코드를 최대한 분리해주고 싶었는데,
가장 이상적으로 ViewModel 을 통해 캡슐화 시켜주고 싶었던 것이 잘 이뤄지지 못한 부분이 있었습니다!