프로젝트 관리 앱 [STEP 2-1] 제리
yagom-academy/ios-project-manager pull request #94
Opened 2022-03-09 11:38 UTC by llghdud921

안녕하세요~ 토니! @Monsteel 
STEP2 마무리해서 제출하고 싶었지만~ 그러지 못해 STEP2-1로 PR 제출드립니다 🥲  
model 테스트, 에러처리, task 수정, 상태 이동, 세부적인 View 표현 등등 많은 기능을 구현하지 못했지만 이러다간 영영 제출못할것같아서 미완성으로 제출드립니다 😭  
잘부탁드리고 항상 감사드립니다 토니 😊

## 설계
![스크린샷 2022-03-09 오후 5 25 27](https://user-images.githubusercontent.com/40068674/157432200-52019a5e-6e86-47f6-abf2-931b992c16ea.png)

### Model Layer  
- **TaskRepository**  
    TaskEntity List 프로퍼티와 입출력을 담당하는 타입.  
    현재 DB 연결이 되어있지 않아 `TaskEntity` List는 빈 배열로 정의되어있습니다.
    
- **TaskEntity**  
    DB나 API에서 내려오는 데이터 구조에 맞추어 Parsing하게끔 정의된 타입.  
    Task 타입과 Mapping을 위한 메소드가 구현되어있습니다.
    

### ViewModel Layer  
- **TaskEnvironment**  
    ViewModel에서 Model 타입의 `TaskRepository`를 가지고있는 타입으로 두 계층을 연결하는 역할입니다. 
    
- **TaskViewModel**  
    Task list 프로퍼티와 해당 프로퍼티 관련 로직을 수행하는 ViewModel 타입.  
    `@ObservableObejct`를 채택하고 Task list 변경을 관찰할 수 있도록 `tasks`를 `@Published`로 선언하였습니다.
    
- **Task**  
    View에 보여지는 프로퍼티와 관련된 로직을 수행을 위한 Property로 구성된 class 타입  
    `@ObservableObejct` 채택하고 변경을 관찰할 프로퍼티를 `@Published`로 선언하였습니다.
    

### View Layer  
- **MainScene**
    `TaskViewModel` 객체를 가지고있는 View타입  
    `TaskViewModel`을 `@EnvironmentObject`  선언하여 데이터가 변경될 시에 자동으로 뷰가 업데이트되도록 구현하였습니다.
    
## 구현 화면
- **Task 추가 기능**
![Simulator Screen Recording - iPad Pro (12 9-inch) (5th generation) - 2022-03-09 at 19 45 42 (1)](https://user-images.githubusercontent.com/40068674/157432624-1266dea5-2e07-4890-a5ae-a8088ef6e5b7.gif)

- **Task 삭제 기능**
![Simulator Screen Recording - iPad Pro (12 9-inch) (5th generation) - 2022-03-09 at 19 47 31](https://user-images.githubusercontent.com/40068674/157432789-1ae2f0ec-20e8-45de-8fa4-1b9943dda138.gif)

- **Task contextMenu (이동 X)**
![Simulator Screen Recording - iPad Pro (12 9-inch) (5th generation) - 2022-03-09 at 19 47 52](https://user-images.githubusercontent.com/40068674/157432769-b93fd502-a3df-4c35-87c4-1a2c6e7c0b51.gif)

# 고민했던 점

### MVVM 구조  
- local , remote DataBase 와 연결을 위해 DB에서 내려주는 타입으로 구현되는 Entity와 View에서 사용하기 위한 ViewModel 내부의 Model을 구분해주었습니다.
- ViewModel내부에 Model의 Repository를 주입시키기 위한 Environment 타입을 정의하였습니다.

### View를 분리해서 정의  
- SwiftUI로 View를 구현하면서 View가 굉장히 많이 생겨서 최대한 View를 분리하면서 정의하였습니다.
- Scene은 화면을 구성하는 View들을 모아두는 기준으로 분리하였고 그 외 Scene을 구성하는 View는 Views폴더에 모아두었습니다.

### EnvironmentObject vs ObservableObject  
- View layer에 `ViewModel` 객체를 주입하는 과정에서 데이터의 흐름을 관리하기 쉬운 `ObservableObject` - `ObservedObject` property wrapper를 적용하였습니다.
- 하지만 View 분리하는 과정에서 `ViewModel`을 전달하는 코드가 너무 많아지고 `ViewModel`은 view 전역에서 사용하고 있어 `EnvionmentObject`로 적용하였습니다.

## 조언을 얻고 싶은 부분

### View에서 ViewModel의 값이 바뀌어도 View가 업데이트 되지않는 문제
Insert, delete는 문제없는데 데이터를 update하는 경우 View를 잘못구성한건지 ViewModel내 데이터값이 바뀌어도 view를 다시 그려주지 않았습니다. Task status를 변경하는 로직에도 View를 다시 그려주지 않았습니다.
View 구현과정은 아래와 같습니다.
- ViewModel은 ObservableObject로 구현
- SceneDelegate에서 ViewModel을 environmentObject로 저장
- MainScene내 viewModel을 EnvironmentObject로 구성

![스크린샷 2022-03-09 오후 8 19 56](https://user-images.githubusercontent.com/40068674/157433799-a6e312c6-2281-4d05-9c7e-4541dc62d1c6.png)
![스크린샷 2022-03-09 오후 8 20 14](https://user-images.githubusercontent.com/40068674/157433706-ab86e80e-0cf6-4f88-8b72-f3c00b1bda12.png)
디버깅을 통해 data값도 확인하였고 여러방향으로 개선해보려고 했으나 해결하지 못하였습니다ㅠㅠ
View의 구조상 문제라 판단하여 PR로 피드백받아 이문제를 해결하기 위해 프로젝트를 잠시 중단하고 미완성인 상태로 제출하게 되었습니다 😭
감사합니다 :)

2022-03-10 13:01 UTC, Monsteel requested changes
@llghdud921 
안녕하세요 제리~
새로운 개념인 ViewModel의 개념을 접하시고, 적용하시느라 수고 많으셨습니다~!☀️

ViewModel이 역할을 하는지, 그리고 ViewModel 안의 method, state, env는 각각 어떤 역할을 수행하는지 등 전체적인 개념에 대해 잘 이해하시고 계신것 같아 보입니다~! 🔥 (제리 최고 🤩)

다만, 구현에 있어서는 살짝 아쉬운 부분들이 보이기도 하는데요,
전체적인 개념에 대한 이해도가 충분히 있으셔서, 이 부분에 대해서는 크게 걱정하지는 않습니다~ 🙌
조금만 함께 고민해보는 시간을 가져보면, 좋은 코드가 나올 수 있을것 같아요~ 🙋🏻‍♂️

그리고 View를 잘게 나누신 부분도 인상깊었습니다. 👍👍
View를 잘게 나누게 되면 가독성은 물론, 성능적으로 큰 이점을 볼 수 있습니다.
실제로 View의 크기가 너무 비대해져, 컴파일러가 타입을 추론하지 못해 오류가 발생하기도 합니다 😭

과하다 싶을 수도 있지만, 잘게 그리고 관심사 별로 잘 나누어 주신 것 같아요 🎉

EnvironmentObject 와 ObservableObject 차이를 이해하고, EnvironmentObject 를 채택하여 적용해주신 부분도~! 인상깊었습니다 ☀️

이번 Step의 주된 리뷰 대상이 코드의 구조에 관련된 내용이라 comment로 남기기에는 어려움이 있어 보입니다ㅠ 😓
앞서 discord DM을 통해 말씀드렸듯, `View에서 ViewModel의 값이 바뀌어도 View가 업데이트 되지않는 문제`와 함께 discord를 통해서 함께 고민해보는 시간을 통해서 리뷰를 진행하면 어떨까 합니다 ☀️

DM확인해 보시고, 편하신 시간 말씀주시면 감사하겠습니다 🙏

2022-03-15 06:45 UTC, llghdud921 commented
안녕하세요 토니~!~!
지난번에 토니가 조언주신 방법으로 수정을 해보았습니다! 너무 늦게 수정해서 죄송할따름입니다...
남은 기능은 STEP2-2로 구현해서 PR드릴 예정입니다 ☺️

## 궁금한 점
![Simulator Screen Recording - iPad Pro (12 9-inch) (5th generation) - 2022-03-15 at 15 12 53](https://user-images.githubusercontent.com/40068674/158319138-992bcb54-373c-44f8-8033-66d0ce6e477e.gif)
contextMenu를 이용하여 status를 변경하면 0.5초간 잔상이 남습니다ㅠㅠ 
view내에서 연산 프로퍼티를 사용하는 것에 성능이슈가 있을 수 있다하여 개선도 해보았는데 여전히 해당 현상있어서 혹시 해결할 수 있는 키워드가 있는지 여쭤봅니다!

2022-03-15 15:21 UTC, Monsteel requested changes
안녕하세요 제리~! 🐭
리뷰가 늦어져 죄송합니다~! 🙏

기능 작동에 이상없음을 확인하였고,
각 뷰들을 별도의 struct로 구분하여, 가독성이 좋고 각 뷰의 역할을 명확히 알 수 있도록 코드를 작성해주신 부분이 인상깊었습니다. 🚀

하지만 각 하위 뷰들이 `@EnvironmentObject` 의 특성을 활용하여 거의 모든 화면에서
`taskViewModel`에 대해 높은 의존성을 가지고 있는 화면들이 보입니다.

이런 의도로 `@EnvironmentObject`를 사용하는건 적절치 않아 보입니다. 🤔
각각 역할을 분리하고, 변경사항에 유연한 코드를 작성하는데에 방해가 되기 때문인데요,

확인 후 검토해 보시고, 어떤 방식으로 해결하면 좋을지 고민해보면 좋을것 같습니다! 🙏

== 

그리고 남겨주신 질문에 대한 답변 드립니다!

별도의 환경에서 해당 상황을 다시 재연해 보았더니, 동일한 문제가 발생하는 것으로 보아,
제리가 구현한 View의 문제는 아닌것으로 보여지며,
`contextMenu`와 적용된 `listStyle`의 조합의 경우 발생하는 swiftUI의 자체적인 버그로 보여집니다.🥲

해당문제는 `popover`라는 비슷한 개념으로 대체하여 사용하거나, listStyle 변경을 통해 해결하는 등 해당 조합을 사용하지 않고 우회하여 해결하는 방법들이 있을것 같습니다. 😭

시원하게 해결할 수 있는 방법을 말씀드리지 못해 죄송합니다 😓

아래 코멘트 내용들을 포함하여 위에 말씀드린 부분 확인해보시고, 다시 리뷰 요청 주시면 감사하겠습니다 🙏

2022-03-15 15:21 UTC, Monsteel commented on ProjectManager/ProjectManager/View/Views/TaskListView.swift
> +    var tasks: [Task]
`taskViewModel`에 있는 내용을 `tasks`로 받는 이유가 있나요?!
`taskStatus`를 기준으로 자체적으로 판단할수도 있고, `taskViewModel`에 대해서 의존을 포기할수도 있습니다.

2022-03-17 07:34 UTC, llghdud921 commented on ProjectManager/ProjectManager/View/Views/DoneButtonView.swift
> +    @EnvironmentObject private var taskViewModel: TaskViewModel
확장성과 재사용성을 고려하여 클로저를 이용해 `DoneButton`의 작동 코드는 해당 View를 호출하는 `AddScene`에서 작성하도록 개선하였습니다 :)

2022-03-17 07:35 UTC, llghdud921 commented on ProjectManager/ProjectManager/View/Views/TaskListView.swift
> +    var tasks: [Task]
확장성과 재사용성을 고려하여 클로저를 이용해 `DoneButton`의 작동 코드는 해당 View를 호출하는 `AddScene`에서 작성하도록 개선하였습니다 :)

2022-03-17 07:40 UTC, llghdud921 commented on ProjectManager/ProjectManager/View/Views/TaskListView.swift
> +    var tasks: [Task]
contextMenu 버그를 해결해보려고 한번 시도해보았는데요.. 차이없음을 깨달았습니다 🤣
해당 SwiftUI 버그는 PopOver로 변경하여 해결되었습니다 :)

2022-03-17 07:45 UTC, llghdud921 commented
안녕하세요 토니~ 🤗
피드백 주신 부분에 대해 답변이 코멘트 답변과 아래에 작성되어있고 그에대한 수정이 완료되어 머지 요청드립니다! 감사합니다~!

>각 하위 뷰들이 @EnvironmentObject 의 특성을 활용하여 거의 모든 화면에서
taskViewModel에 대해 높은 의존성을 가지고 있는 화면들이 보입니다.

@EnvironmentObject로 작성했던 ViewModel 주입을 @ObservedObject를 사용하여 개선하였습니다.
이렇게 작성하니 ViewModel의 흐름을 파악할 수 있는 장점이 있었습니다 :)

2022-03-17 08:02 UTC, Monsteel approved these changes
안녕하세요 제리🐭 ~! 
Step2도 수고많으셨습니다~! ViewModel의 흐름을 파악하시다니 👀
아주 잘 진행하고 계신듯 하여..! 든든합니다~! 🍚

수고많으셨습니다 🎉

2022-03-17 08:06 UTC, merged