Step2
yagom-academy/ios-project-manager pull request #95
Opened 2022-03-10 04:34 UTC by yeahg-dev

# 🍒 고민한 점

## 1. MVC 설계
![Project Manager App - MVC](https://user-images.githubusercontent.com/81469717/157584738-5c216c4d-6d67-46a4-8f7f-d0185e6e56f3.jpeg)

이번 프로젝트에서 철저하게 MVC패턴을 따르는 객체 설계를 해보고 싶었습니다. 그래서 어떻게 하면 하나의 객체가 Model/Controller/View 중 하나의 역할만 할 수 있도록 할지 고민을 많이 해보게되었습니다.

- **Model : 앱이 무엇인지, 화면에 필요한 데이터와 비지니스 로직을 관리**
- **View** : 화면에 보여준다
- **Controller** : 사용자에게 Model을 어떻게 보여줄건지 전달, 뷰의 이벤트를 모델에게 전달

고민한 끝에, 루트 뷰컨트롤러인 `StoryBoardVC`만 **모델인 `ProjectManager` 를 참조할 수 있도록 설계**했습니다. 그리고 나머지 뷰 컨트롤러는 **뷰의 이벤트를 `StoryBoardVC` 에게 전달**만하고, **Model을 사용자에게 보여주기위해 가공해서 View에 전달하는 역할**만 수행하도록 했습니다. 그 의도는 아래와 같습니다.

- 하나의 Scene에서 여러개의 뷰컨틀롤러가 모델을 참조할 경우, 뷰의 변화가 있어서 모델에게 알려줘야 할 때 누락되기 쉬울 것 같다고 생각했습니다.
- 비지니스 로직을 한 객체에서만 핸들하면 통제하기가 용이할 것이라 생각했습니다.

그래서 다른 뷰컨트롤러들에서 뷰로 사용자 이벤트가 들어오면 델리게이트 패턴을 통해서 StorBoardVC로 전달하도록 설계했습니다. 

## 2. `TODO` `DOING` `DONE` 의 TableView들 구현 방법

`TODO` `DOING` `DONE` 상태에 따라 프로젝트를 나열하는 테이블 뷰가 3개인 UI인데요~

아래 두 가지 방법을 고민했습니다. 

1. **하나의 뷰컨트롤러에 세 개의 tableview를 배치해서, 하나의 뷰컨이 3개의 tableView를 관리하는 방법**
    - 셀에 대한 공통되는 행동을 하나의 tableviewDelegate로 구현 할 수 있는 장점
    - 공통적 행동(수정, 삭제, 상태 변경)을 공유 할 수 있음
    - 모델과 직접적으로 메세지를 주고 받을 수 있음
2. **✅ 각 테이블뷰를 하나의 컨트롤러가 관리하는 방법**
    - 상태마다 뷰컨을 따로 만들어서 관리하는 것이 확장에 유리함

1번의 장점에도 불구하고 확장성 있는 설계를 하고 싶어서 2번 방법으로 구현을 해보았는데요~
(구현한 결과 PrjectBoardVC들에서 ProjectBoardVC로 이벤트를 전달하기 위해 델리게이트를 사용하게되면서 괜히 설계가 더 복잡해졌다는 느낌을 받았습니다🥲)

셀의 삭제, 프로젝트 상태 변경 popover, 상세화면 띄우기와 같은 행동은 3개의 뷰컨에서 공통적으로 사용되기 때문에 비슷한 코드가 재사용되는 상황이 나왔습니다. 또 이렇게 겹치는 코드를 보니 어떻게 하면 공통화해줄 수 있을까 고민이 되었습니다! 

각 뷰컨에 대한 상위 뷰컨을 만들어서 상속을 활용할지, 프로토콜을 사용할지, 아니면 이대로도 괜찮은지...
엘림이라면 어떻게 해주셨을지 엘림의 의견이 궁금합니다!😃

<br>

# 🍋 트러블 슈팅

## 언어설정에 따른 datePicker가 적용되지 않는 문제

`datePicker.locale` 의 default는 `.autoupdatingCurrent` 인데요, `autoupdatingCurrent` 프로퍼티가 기기의 언어 설정을 반영하지 못하는 이슈가 있었습니다. (지역 설정은 정상적으로 반영되었습니다)

예를 들어 언어 [설정]에서 [iPad]언어를 한국어로 바꾸어주었는데도 datePicker의 UI는 영어로 나옵니다. `.autoupdatingCurrent` 을 프린트 해본 결과 “en-KR”이 나옥, 언어는 반영이 되지 않는 버그를 확인했습니다. 

### 해결방법

직접 preferredLanguage를 가져온 다음, Locale identifier를 수동으로 합성하여 새로운 Locale 객체를 만들어주었습니다.

```swift
private var datePicker: UIDatePicker = {
        let datePicker = UIDatePicker()
        datePicker.translatesAutoresizingMaskIntoConstraints = false
        datePicker.datePickerMode = .date
        datePicker.preferredDatePickerStyle = .wheels
				// 직접 preferredLanguage를 가져옴
        var preferredLanguage = Locale.preferredLanguages.first
        let currentRegionIdentifier: Substring? = NSLocale.current.identifier.split(separator: "_").last
        if let languageCode = preferredLanguage, let regionCode = currentRegionIdentifier {
            let deviceLocaleIdentifier = "\(languageCode)_\(regionCode)"
            datePicker.locale = Locale(identifier: deviceLocaleIdentifier)
            return datePicker
        }
        return datePicker
    }()
```
<br>

# ❓ 궁금한 점

### 1. NavigationBar를 subview해주어도 SafeAreaLayoutGuide는 변경되지 않는 상황

NavigationController를 사용하지 않고 NavigationBar만 사용하기 위해 NavigationBar를 View에 addSubview해주었습니다. 그런데 테이블뷰의 레이아웃을 잡아주려고 `safeAreaLayoutGuide.topAnchor` 에 제약을 주었더니 아래와 같이 되었었는데요.

![simulator_screenshot_9E6B7505-3372-4F18-9D47-E30427E4B524](https://user-images.githubusercontent.com/81469717/157584905-c5d7b90e-cd85-43fb-9faa-746ca0666380.png)

애플이 제공하는 컨트롤러 API를 사용하지 않고 직접 넣어줄 경우에는 `safeAreaLayoutGuide` 가 변화하지 않는 걸까요??

### 2. 테이블뷰와 테이블 뷰 Celll 간의 Seperator 구현 방법

<img width="778" alt="스크린샷 2022-03-10 오후 12 13 38" src="https://user-images.githubusercontent.com/81469717/157584787-8cea7a46-6630-4595-898c-400f8a29d4f1.png">

헤더와 셀 사이의 선(seperator)를 구현하기 위해 `UITableView` 와 `UITableViewDelegate` 의 API를 찾아보았는데 이에 대한 API는 따로 제공해주지 않는걸 발견했습니다. 

SectionHeaderView의 `draw` 메서드에서 직접 저 선을 구현해주어야 할까요?

### 3. Header와 테이블뷰 사이의 빈틈

Header와 테이블뷰 사이의 빈틈은 어떻게 없애줄 수 있을까요?

<img width="630" alt="스크린샷 2022-03-10 오후 12 31 14" src="https://user-images.githubusercontent.com/81469717/157585014-72a60ef7-d553-42f7-a827-fd7574e63079.png">

Header는 TableViewDelegate가 관리하는 객체라 어떻게 레이아웃을 조정해주어야할지 궁급합니다!

<br>

### 해결하지 못한 부분

- [ ]  셀 사이의 spacing 구현
- [ ]  테이블뷰 헤더의 프로젝트 갯수를 나타내는 뱃지
- [ ]  프로젝트 상세화면과 생성화면의 TextField, TextView의 그림자 효과

PR제출 후에 방법 계속 모색해보겠습니다!

2022-03-12 13:18 UTC, lina0322 requested changes
안녕하세요, 릴리!
이번 프로젝트도 정말 고생 많으셨습니다~
예상보다 시간이 많이 걸린 프로젝트가 되었네요.
기획에 비해 많은 스텝을 나가진 못했지만, 그 안에서 많은 것을 배웠던 프로젝트이길 바랍니다!
또 시간이 난다면 drag & drop도 재미있는 기능이기 때문에 나중에 해보셨으면 좋겠어요😀

<img width="200" alt="스크린샷 2022-03-12 오후 10 13 09" src="https://user-images.githubusercontent.com/49546979/158019317-353db7b8-7eee-46dd-838d-6bfe094b36eb.png">

프로젝트 실행해보았을 때, 라벨이 짤리는 모습이 보이네요! 이 부분도 수정 부탁드립니다.

또, 궁굼한 점으로 남겨주었던 1번은 safeArea의 영역에 대해서 다시 한번 공부해보시면 답이 나올 것 같고,
2번은 같은 경우에는 릴리가 생각한 방법이 간편하고 좋다는 생각이드네요~

아래 코멘트에도 남겼지만, todo-doing-done이 똑같은 코드를 가지고 있는데 각각 설계된 점이나
detail-creator도 비슷한 코드를 가지고 있어서 함께 사용이 될 수 있을 것 같은데 각각 설계되어 있었어요!
이런 부분을 왜 이렇게 하게 되었는지에 대해 좀 더 자세히 설명해주시면 좋을 것 같네요😀

리뷰로 남긴 내용중에 이해가 안 가는 부분이나, 추가로 궁금한게 생기면 언제든지 DM 주세요!
해결 안되는 부분들도 DM 주시면 함께 고민해 보죠~

다시 한 번 이번 프로젝트 고생많으셨고, 수정 할 수 있는 곳까지는 해봅시다! 화이팅💕

2022-03-12 13:18 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +        self.stackViewBackgroundView.addSubview(stackView)
stackView 자체에 background color를 설정할 수 도 있을텐데, 이렇게 작업한 이유가 있나요??🤔

2022-03-12 13:18 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +    }
특정 delegate만 여기서 configure해주고 있네요?🙂

2022-03-12 13:18 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +}
어떤 동작을 하려고 한건지 설명 부탁드려도 될까요🙏

2022-03-12 13:18 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +
컨벤션을 맞추려면 여기 빈줄은 없애는게 맞나욥??

2022-03-12 13:18 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +        todoViewController.updateView()
현재는 todo에만 프로젝트를 생성할 수 있네요!ㅎㅎ doing이나 done에서 생성하려면 어떻게 할 수 있을까요?

2022-03-12 13:18 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +    func updateProject(of identifier: UUID, with content: [String : Any]) {
위에서 status 써준 것 처럼 content를 써주는 것도 좋을 것 같네요🙂

2022-03-12 13:18 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectCreatorViewController.swift
> +class ProjectCreatorViewController: UIViewController {
final 키워드에 대해 알아보면 좋을 것 같아요!🤧

2022-03-12 13:18 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectCreatorViewController.swift
> +    weak var delegate: ProjectBoardViewController?
weak를 사용하지 않으면 어떻게 될까요?!

2022-03-12 13:18 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectDetailViewController.swift
> +class ProjectDetailViewController: UIViewController {
Detail과 Creator가 비슷한 화면과 동작을 가지고 있는데, 하나의 viewController로 사용하려면 어떻게 할 수 있을까요?😀

2022-03-12 13:18 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/TodoProjectTableViewController.swift
> +class TodoProjectTableViewController: UIViewController {
tableViewController라는 이름때문에 UITableViewController를 상속한 것 처럼 보이네요!
또, UITableViewController를 상속하지 않고 UIViewController를 상속한 이유가 있을까요?☺️

2022-03-14 05:49 UTC, yeahg-dev commented on ProjectManager/ProjectManager/App Life Cycle/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
UI를 코드로만 작성하는 연습을 해보고 싶어서 스토리보드 없이 했습니다!

2022-03-14 05:55 UTC, yeahg-dev commented on ProjectManager/ProjectManager/App Life Cycle/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
질문에서 턱 막혀버려서,, window와 scene의 차이를 공식문서를 보며 공부해보았는데요!
window는 기기 스크린에 보여지는 컨테츠의 컨테이너 역할을 하는 객체이고, 사용자 이벤트를 받고 연관된 뷰나 뷰컨틀롤러에게 이벤트를 전달하는 역할을 하는 것으로 이해했습니다. 
scene은 하나의 UI인스턴스를 나타내는 단위라고 어렴풋이 이해했는데요. 아이패드와 같이 split view를 제공하는 환경에서 왼쪽 화면, 오른쪽 화면을 각각의 UI인스턴스라고 보는 것이 맞을 까요??
![3335652_dark@2x](https://user-images.githubusercontent.com/81469717/158113315-306af577-33b3-451a-a655-d42cece7a633.png)

2022-03-14 06:02 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +    private let doneViewController = DoneProjectTableViewController()
현재는 todo, doing, done 테이블뷰가 모두 동일한 행동을 제공하지만, 추후에 각 테이블뷰마다 다른 행동을 구현할 수 도 있는 경우를 생각해서 3개의 클래스로 정의해주었습니다.
그런데 엘림의 말대로 동일 클래스에 이니셜라이저에서 status를 주입받는 방법으로 구현한뒤, 추후에 기능확장이 있을 때는 이 뷰 컨트롤러를 상속하는 방법도 생각할 수 있을 것 같아요!

2022-03-14 06:06 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +        navigationBar.translatesAutoresizingMaskIntoConstraints = false
navigationBar의 위치를 오토레이아웃으로 잡아주기 위해서 translatesAutoresizingMaskIntoConstraints를 false로 적용해주었습니다. 코드로 작성한 UI의 translatesAutoresizingMaskIntoConstraints값은 디폴트가 true인데, 오토레이아웃을 사용하면 autoresizing에 관련한 제약과 오토레이아웃 제약이 충돌한다고 알고 있습니다. 그래서 false로 변경했습니다

2022-03-14 06:07 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +       let backgroundView = UIView()
수정했습니😊

2022-03-14 06:09 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +
사용자 정의 타입 정의후, 첫번째 라인의 코드 사이의 줄 바꿈에 대한 컨벤션이 들쑥날쑥했네요😅
첫번째 코드라인 앞에서는 한 줄 띄우는 컨벤션으로 전체 통일 하겠습니다~

2022-03-14 06:23 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +    private lazy var stackView: UIStackView = {
stackView를 `UIStackView(arrangedSubviews: )`이니셜라이저로 생성해주고 싶은데, 그렇게 하기 위해선 스택뷰의 서브뷰들인 label 프로퍼티에 접근할 수 있어야하는데요~ lazy로 하지 않으면 label프로퍼티에 접근이 불가하기때문에 lazy로 선언해주었습니다.
음..역할을 포괄하는 네이밍이 좀 어려운데요🥲 `contentStackView`면 의미를 나타내기 괜찮을까요??

2022-03-14 06:28 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +        stackView.spacing = 7
`distribution`은 스택뷰 axis의 방향축대로 서브뷰들을 어떻게 채울건지 정하는 프로퍼티이고, `alignment`는 스택뷰 axis의 반대 방향축으로 서브뷰를 어떻게 배치할건지 정하는 프로퍼티입니다!
`spacing`은 서브뷰 사이의 간격을 몇을 줄 건지 정하는 프로퍼티입니다!

2022-03-14 06:30 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +        self.configureStackViewLayout()
전에 리뷰해주셨던 리뷰어께서 현업에서는 `self`를 명시적으로 붙여준다고 하셔서, 저도 그 컨벤션을 따라보고 있습니다!

2022-03-14 06:33 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +        self.stackViewBackgroundView.addSubview(stackView)
stackView 자체에 backgroundColor를 지정을 못한다고 생각해서 따로 containerView를 만들어줬었습니다.
`stackViewBackgroundView`는 굳이 필요없는 객체인 것 같습니다~! 수정할게요!

2022-03-14 08:53 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +        self.view = .init()
뷰컨트롤러의 `view`프로퍼티에 뷰를 초기화해서 할당해주는 작업입니다.

2022-03-14 08:55 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +        self.configureView()
`configureView`에서 하는 작업이 뷰를 생성하고, 백그라운드 컬러를 지정하고, `translatesAutoresizingMaskIntoConstraints`를 false로 지정해주는 작업인데요~ 이 작업들은 레이아웃을 정해주는 코드가 아니기때문에, 뷰가 로드되기 전에 해주어도 되는 작업들이라서 `loadView`에서 처리하게 역할을 분리해주었습니다!

2022-03-14 14:53 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +    private let stackViewBackgroundView: UIView = {
`stackViewBackgroundView`는 삭제하고 대신 `tableStackView`의 백그라운드컬러를 지정해주었습니다.

2022-03-14 14:58 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +}
UIBarPositioningDelegate의 메서드로 윈도우에서 navigationBar의 위치를 설정해주는 메서드로 알고 있습니다!

2022-03-15 07:07 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +        let navigationItem = UINavigationItem(title: "Project Manager")
네임스페이스로 관리하도록 수정했습니다😊

2022-03-15 07:08 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +    }
`configureProjectViewControllerDelegate()`로 네이밍을 수정하면 괜찮을까요?

2022-03-15 07:18 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +        todoViewController.updateView()
`LocalDataBase` 프로토콜의 `func create(with content: [String: Any])`는 공통인터페이스로 모델 타입에 상관없이 키-값을 인자로 만들게 했습니다. 그래서 projectSource의 `create(with content: [String: Any])`구현에서 status또한 설정해 줄 수 있도록 수정했습니다.

```swift
 func create(with content: [String: Any]) {
        let identifier = UUID()
        let newProject = Project(identifier: identifier,
                                 title: content["title"] as? String,
                                 deadline: content["deadline"] as? Date,
                                 description: content["description"] as? String,
                                 status: content["status"] as? Status) // status도 설정 가능
        projects.updateValue(newProject, forKey: identifier.uuidString)
    }
```

2022-03-15 07:22 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +    func updateProject(of identifier: UUID, with content: [String : Any]) {
`updateProjectContent`로 좀 더 명확하게 수정했습니다😊

2022-03-15 07:24 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectDetailViewController.swift
> +class ProjectDetailViewController: UIViewController {
`ProjectViewController`라는 클래스를 구현해서, 이 안에서 모드를 스위칭 할 수 있게끔 수정해보았습니다!

2022-03-16 10:36 UTC, lina0322 commented on ProjectManager/ProjectManager/App Life Cycle/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
오, 좋은 흐름으로 가고있네요. 혹시 릴리 Scene Delegate에 대해서 알고있나요??🤔

2022-03-16 10:38 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +        self.configureStackViewLayout()
이런건 정말 개인차가 심한 것 같아요ㅎㅎ 저는 앞에 self를 붙이지 않습니다.
이유는 강한 참조가 발생할 수 있을 떄 사용해서 구분하기 위해서이긴 합니당ㅎㅎ
선택은 릴리의 몫이지만, 아마 들어가는 회사 컨벤션을 따르게 되겠쥬~?

2022-03-16 10:40 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +        self.view = .init()
viewController의 view를 초기화해서 할당해줄 필요가 있나요?

2022-03-16 10:41 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +        self.configureView()
super를 호출하지 않아도 되나요?ㅎㅎ
또, translatesAutoresizingMaskIntoConstraints나 백그라운드 컬러를 지정하는 것을 굳이 loadView에서 해야하나 하는 의문이 들긴하네요🤧

2022-03-16 10:46 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/TodoProjectTableViewController.swift
> +class TodoProjectTableViewController: UIViewController {
네, 저는 피하는게 좋다고 생각되어요☺️

2022-03-16 10:47 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +}
navigation controller를 사용하지 않고 navigationBar만 올린 이유가 있나용?

2022-03-16 11:00 UTC, lina0322 approved these changes
안녕하세요, 릴리~~
이렇게 이어서 보니 더 반갑네요ㅋㅋㅋㅋ
짧은 시간 안에 정말 많은 변화와 발전이 있었어요!

추가로 리뷰 남겼으니까 확인해보고 편하게 메세지 주세욥~
다음 스텝도 해야할 것 같아서 너무 세세하게 달지는 않았어요. 
여기서 수정해도 좋고, 다음 스텝에 수정해서 함께 올려줘도 좋을 것 같아요.
편한대로 해서 디엠주시고요!!(원하면 머지하고, 다음 스텝에서 작업해도 된다는 뜻 입니답!)

지금처럼 또 궁금한거나 어려운 것 있으면 펀하게 메세지 주세요~~🙇🏻‍♀️

2022-03-16 11:27 UTC, merged

2022-03-17 05:51 UTC, yeahg-dev commented on ProjectManager/ProjectManager/App Life Cycle/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
음... 어떤 역할을 하는지 잘 모르겠습니닷...🥲

2022-03-17 06:07 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/TodoProjectTableViewController.swift
> +class TodoProjectTableViewController: UIViewController {
`ProjectListViewController`로 수정했습니당!

2022-03-17 06:07 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +    private let doneViewController = ProjectTableViewController(status: .done)
릴리 굿... 티엠아이...?😍

2022-03-17 06:09 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +    }
후자가 더 심플하고 직관적이었던 것 같아요😙

2022-03-17 06:13 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectTableViewController.swift
> +    private var dataSource: UITableViewDiffableDataSource<Section,Project>!
diffableDataSource에 접근해서 사용하기 전에 `configureDataSource`를 호출해서 할당해준다고 생각해서 괜찮을거라 생각했어요..! 
그래도 옵셔널로 해주는 것이 더 안전하겠죠..?

2022-03-17 06:15 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectTableViewController.swift
> +        super.viewDidLoad()
> Your custom implementation of this method should not call super.
이라고 되어있어서 호출하지 않았습니다~

2022-03-17 06:16 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectTableViewController.swift
> +        ])
띄어쓰기를 말씀하신걸까요?

2022-03-17 06:30 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectTableViewController.swift
> +            let projectCell = self.projectTableView.dequeueReusableCell(withClass: ProjectTableViewCell.self, for: indexPath)
style share guide 컨벤션에 따라 수정해주었습니다.

2022-03-17 06:32 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectViewController.swift
> +
넵!!!

2022-03-17 06:33 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectTableViewController.swift
> +                                style: .default) { [weak self] _ in
클로저가 캡쳐하면서 self인 뷰컨트롤러도 Reference count를 1 늘려준다고 알고 있습니다.

2022-03-17 06:34 UTC, yeahg-dev commented on ProjectManager/ProjectManager/Controller/ProjectTableViewController.swift
> +            return UIAlertAction()
빈 액션이 화면에 나올 것 같은데요~ case가 none일때도 처리를 해주어야해서 음,,, placeholder액션이라도 넣어주는 것이 좋을까요??

2022-03-17 06:58 UTC, yeahg-dev commented on ProjectManager/ProjectManager/View/ProjectTableViewHeaderView.swift
> +    }
`init(frame:)` 은 UIView의 이니셜라이져인데요, 
인자로 전달받은 frame으로 위치와 사이즈를 결정한 새로운 객체를 만들어서 반환하는 역할을 합니다.
`init(coder:)`NSCoding프로토콜의 이니셜라이저인데요, 코드로 뷰를 생성할 때 사용해하는 지정이니셜라이저입니다.
인터페이스빌더로 UI를 만들거나, xib 파일로 생성할 때 그 파일의 코드를 뷰로 번역(deseriailization)하면서 만드는 초기자라고 알고 있습니다. 스토리보드가 호출하는 이니셜라이져이기 때문에 저희 코드에서는 실행이 되지 않아서 fatal처리가 되어도 괜찮지 않을까...? 했는데요~
제가 혹시 잘 못 알고 있는 걸까요?🥲

2022-03-17 10:56 UTC, lina0322 commented on ProjectManager/ProjectManager/App Life Cycle/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
시간이 된다면 Scene Delegate와 App Delegate의 차이, Scene Delegate가 등장한 이유
버전에 따른 두 Delegate의 적용 방법 등을 찾아보면 좋겠어요🙏
이번엔 여기까지 하죠~😉

2022-03-17 10:57 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectBoardViewController.swift
> +    private let doneViewController = ProjectTableViewController(status: .done)
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ Look Good to Me👍

2022-03-17 10:58 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectTableViewController.swift
> +        super.viewDidLoad()
음, 저의 의문은 그런거였어요. 
ViewController에서 view는 자동으로 만들어주는데 굳이 self.view를 init하고 loadView()를 호출할 필요가 있는가..?🤔
릴리의 의견이 궁금합니다! 왜 view를 굳이 init하였나요??

2022-03-17 10:59 UTC, lina0322 commented on ProjectManager/ProjectManager/Controller/ProjectTableViewController.swift
> +        ])
하나의 `NSLayoutConstraint.activate([])` 안에 작성할 수 있는데, 항목별로 나눈 것 같아서요. 
내부에 줄 바꿈만으로도 구분이 가능할 것 같다는 생각이 들었어요😀

2022-03-17 11:01 UTC, lina0322 commented on ProjectManager/ProjectManager/View/ProjectTableViewHeaderView.swift
> +    }
릴리의 코드에는 사실 스토리보드가 없어서ㅎㅎ 큰 문제가 되진 않을 것 같습니다.
그래도 fatal을 처리하기보다 `init(frame: CGRect)`과 같은 내용을 넣어주는 것도 좋을 것 같아요!
앞으로 스토리보드를 사용하게 될 때의 습관을 위해서라고나 할까요?!