프로젝트 관리 앱 [STEP2] 호박
yagom-academy/ios-project-manager pull request #96
Opened 2022-03-10 07:48 UTC by hoBahk

안녕하세요 토니! 🙌  @Monsteel 
스텝2 구현하여 PR 보내드립니다.

MVVM과 SwiftUI가 처음이라 부족하지만 리뷰 부탁드립니다~😄

## 🤔 고민한 점

### 1. ViewModel 타입
ViewModel에 맞는 데이터 타입을 하나 더 만들어서 사용하려고 하였으나,    
뷰에서 사용하는 데이터와 실제 모델의 데이터가 같아 뷰모델을 위한 데이터 타입을 만들지 않고 로직 내부에서 사용하는 모델을 그대로 사용하였습니다.

### 2. 메인화면의 상단바를 네비게이션으로 해야하는가?
네비게이션으로 해야할지 따로 바형태로 뷰를 만들어야할지 고민했지만,   
아이패드 전용앱으로서 Todo, Doing, Done 세가지의 리스트를 하나의 화면에서 보여주는 것이 중점이고 현재의 방향에서 네비게이션뷰가 사용될 일이 없다고 판단하였습니다. 이런 이유로 네비게이션으로 상단바를 따로 만들어 주었습니다.

### 3. dismiss하는 방식
뷰를 dismiss하는 방식을 두가지를 고민하였습니다.   
첫번째는 보여주는 뷰의 상태를 수정해서 스스로 닫도록 하는 방법입니다.
보여주고 닫아야 하는 뷰에 environment property를 추가하여 presentationMode를 수정할 수 있도록 해주고 뷰를 닫아야할 때 dismiss를 호출합니다.

```swift
// environment property 추가
@Environment(\.presentationMode) var presentationMode

// 뷰 dismiss
self.presentationMode.wrappedValue.dismiss()
```

두번째 방법은 바인딩을 이용하는 것입니다.   
새로 띄운 뷰를 호출한 뷰에 바인딩을 전달하는 것으로 바인딩된 값을 띄워준 뷰에서 false로 하게 되면 뷰가 닫힙니다.

```swift
// 새로운 뷰를 띄우도록 하는 뷰에서 설정
@State private var isShowTaskDetailView = false

.sheet(isPresented: $isShowTaskDetailView, onDismiss: nil) { 
    TaskDetailView(isShowTaskDetailView: $isShowTaskDetailView, task: task)
}

// 띄울 뷰
@Binding var isShowTaskDetailView: Bool

self.isShowTaskDetailView = false
```

### 4. SwipeActions
List의 row를 삭제하기 위해 SwipeActions를 사용하려고 하였으나 SwipeActions은 iOS15 이상부터 지원하는데 현재 프로젝트의 타겟 버전을 iOS14으로 설정하였기 때문에 사용하지 못했습니다.   
그래서 아래의 버전도 사용할 수 있는 `onDelete`를 사용하였습니다. SwipeActions가 이미지 버튼을 만들 수 있는 등 여러 기능이 있어 사용하고 싶었지만 1-3년 이후에나 사용할 수 있을 것 같네요..ㅎ

## 🤚 질문 드리고 싶은 점

### 1. MVVM 설계
제 나름대로 MVVM이라고 설계를 해보았습니다. 공부할 때는 이해가 된 것 같다가도 막상 적용하려고 하니 만만치 않네요..ㅎ  
MVVM이 제대로 설계된 것이 맞는지 확인 부탁드리겠습니다! 🙏

### 2. View 나누는 법
뷰를 나누는 것이 좋다고 하여서 뷰를 제 나름대로 나누어 봤습니다. 뷰를 이런식으로 나누는 것이 맞는지 모르겠습니다..!
View를 나눈 것에 대해서 팁 주시면 감사하겠습니다~! 🙏

감사합니다~

2022-03-11 02:34 UTC, Monsteel requested changes
안녕하세요 호박~~! :sunny:
좋은 금요일 아침입니다~ :raised_hands:
비록 하늘은 흐리지만, 커피 한잔에 여유를 즐기고 싶은 아침이네요~! :coffee:️

우선 Step2 진행하시느라 수고 많으셨습니다~! :tada:
보내주신 PR도 잘 확인했습니다.

호박이 어떤 고민을 하셨는지, 담백하게 남겨주셔서 확인하기 쉬웠고 빠르게 파악할 수 있었어요~! :sunny:

호박이 고민했던 부분같은 경우도 전체적으로 이유가 있고, 효용의 가치를 비교해 봤을때 높은 쪽으로 잘 판단하셔서 결정 하신듯 해 보입니다~! :+1:

이어서 호박이 주신 질문에 대해 답변을 남겨보자면
> **1. MVVM 설계**
제 나름대로 MVVM이라고 설계를 해보았습니다. 공부할 때는 이해가 된 것 같다가도 막상 적용하려고 하니 만만치 않네요..ㅎ  
MVVM이 제대로 설계된 것이 맞는지 확인 부탁드리겠습니다! :pray:

MVVM이 무엇인지 너무나도 잘 이해하신것 같고, 그 이해도를 바탕으로 코드에도 잘 녹여내 주신것 같아요~! :raised_hands:
이번 프로젝트에서 여러 케이스를 구현해 보면서, mvvm을 잘 이해하고 계신지 저도 followup하고 있겠습니다. 너무 걱정 않으셔도 되고,
지금 현 코드는 mvvm을 잘 나타내고 있다고 생각해요

> **2. View 나누는 법**
뷰를 나누는 것이 좋다고 하여서 뷰를 제 나름대로 나누어 봤습니다. 뷰를 이런식으로 나누는 것이 맞는지 모르겠습니다..!
View를 나눈 것에 대해서 팁 주시면 감사하겠습니다~! :pray:

저는 일반적으로 View를 나눌 때 별도의 Struct 사용을 지향하는 편 인데요,
사용부에 대한 가시성이 높고(변수들과 헷갈릴 수 있다는 부작용이 있어요), 뷰를 포함하여 뷰가 가지고 있는 상태들에 대해서도 분리할 수 있기 때문입니다.
호박이 나누어 주신 방법도 좋아요~! 특히 private를 사용하여 access scope를 줄여준 부분이 인상깊었습니다 :raised_hands: :raised_hands:

코드가 전체적으로 군더더기 없이 담백한 느낌이 듭니다 :rocket:
다만, 몇가지 고민해보면 좋을것 같은 부분들을 코멘트로 남겨보았습니다 :raised_hands:

한번 확인 부탁드립니다 :pray:

2022-03-11 02:34 UTC, Monsteel commented on ProjectManager/ProjectManager/Service/TaskManager.swift
> +    func updateTaskState(to task: Task, from progressStatus: ProgressStatus) {
`Task`를 전체로 받으신 이유가 있을까요?! 🤔
불필요한 데이터를 제외하고 필요한 데이터들만 추려서 가져오는건 어떨까요?! 🙌

2022-03-11 02:34 UTC, Monsteel commented on ProjectManager/ProjectManager/Service/TaskManager.swift
> +    func updateTask(_ task: Task, title: String, description: String, deadline: Date) {
이 부분도 `Task`를 전체로 받으신 이유가 있을까요?! 🤔
불필요한 데이터를 제외하고 필요한 데이터들만 추려서 가져오는건 어떨까요?! 🙌

2022-03-11 02:34 UTC, Monsteel commented on ProjectManager/ProjectManager/Service/TaskManager.swift
> +    func updateTask(_ task: Task, title: String, description: String, deadline: Date) {
이 부분도 `Task`를 전체로 받으신 이유가 있을까요?! 🤔
불필요한 데이터를 제외하고 필요한 데이터들만 추려서 가져오는건 어떨까요?! 🙌

2022-03-11 02:34 UTC, Monsteel commented on ProjectManager/ProjectManager/Model/ProgressStatus.swift
> +enum ProgressStatus: String {
`ProgressStatus`는 `Task`안에 종속되는 개념으로 보여집니다.👀
`Task`안으로 구현부를 옮겨서 `Task.ProgressStatus` 형태로 접근할 수 있도록 하여 Task안에 종속되는 개념으로 인식되게 하는건 어떨까요 🤔

2022-03-11 03:09 UTC, hoBahk commented on ProjectManager/ProjectManager/Service/TaskManager.swift
> +    func updateTaskState(to task: Task, from progressStatus: ProgressStatus) {
아하 Task 전체를 받을 필요가 없고 id 만 받아오면 되겠네요..!
수정했습니다~ 😄

2022-03-11 03:10 UTC, hoBahk commented on ProjectManager/ProjectManager/Service/TaskManager.swift
> +    func updateTask(_ task: Task, title: String, description: String, deadline: Date) {
이것도 id만 받아오도록 수정했습니다~

2022-03-11 03:13 UTC, hoBahk commented on ProjectManager/ProjectManager/Model/ProgressStatus.swift
> +enum ProgressStatus: String {
좋은 방법인 것 같아요! 👍
이름도 ProgressStatus라고 지어서 Task의 ProgressStatus인지 한눈에 보기 힘들겠네요 😓
Task.ProgressStatus이라고 사용하면 Task의 ProgressStatus인것을 바로 알 수 있을 것 같아요.
감사합니다~ 🙏

2022-03-13 08:15 UTC, hoBahk commented
안녕하세요 토니 🙌 @Monsteel 

말씀주셨던 코멘트에 따라서 코드를 리팩터링 해보았습니다.

>저는 일반적으로 View를 나눌 때 별도의 Struct 사용을 지향하는 편 인데요,
사용부에 대한 가시성이 높고(변수들과 헷갈릴 수 있다는 부작용이 있어요), 뷰를 포함하여 뷰가 가지고 있는 상태들에 대해서도 분리할 수 있기 때문입니다.

뷰를 프로퍼티로 나누는 것이 아닌 구조체를 통해서 나누어 보았습니다.
뷰로 나누던 와중에 뷰를 나눈 구조체마다 프로퍼티가 너무 많아지는 단점이 있어서 필요한 프로퍼티만 남기고 Task 상세화면에 대한 뷰모델을 따로 만들어서 프로퍼티 및 로직을 관리하도록 했습니다~
또한 다른 곳에서도 뷰에 로직이 있는 부분들을 뷰모델에 옮기고 호출하도록 했습니다!

코드에 코멘트 달아주신 것도 토니가 추천해주신 방식으로 수정해보았습니다.

너무 늦게 수정해서 죄송합니다..ㅠㅠ
감사합니다! 🙏

2022-03-13 09:13 UTC, Monsteel approved these changes
안녕하세요 🎃 ~!
주말까지 고생이 많으셨네요 🙌

Step2 수고많으셨습니다~!~!

2022-03-13 09:13 UTC, merged