프로젝트 관리 앱 [STEP2] 고사리
yagom-academy/ios-project-manager pull request #98
Opened 2022-03-10 20:07 UTC by FIIIIN

안녕하세요, 제이슨👾 @ehgud0670

디엠으로 말씀드렸듯이 일단은 PR을 제출하는 게 맞다고 판단해서, 부족하지만 요청드립니다...!

언제나 감사합니다!!

---

## 0. 구현내용

- 브랜치
    - step2-1: MVC 기능구현
    - step2-2: Controller와 View 분리
- 주요 구현 기능
- [X]  설명의 길이에 따라서 Cell의 높이가 동적으로 변하도록 구현
- [X]  TODO 추가, 섹션이동, 수정, 삭제 기능 구현
- [X]  뷰 바깥 탭으로 창이 사라지지 않도록 기능 차단

---

## 1. 고민한 점

> 1-1.
> 
- 매번 tableView를 확인하여 section을 매칭해주는 방식이 과하게 중복된다고 느꼈습니다.
    - NSObject를 채택한 MainTableView 타입 내부에 tableView와 section을 함께 선언하는 것으로
        1. `UITableViewDataSource`, `UITableViewDelegate` 파일분리
        2. section 매칭 중복코드 삭제, `TodoSection 케이스 추가에 대한 유연성` 확보
        를 의도하였습니다.
        

> 1-2.
> 
- EditController에서 추가되는 데이터를 MainController로 거치지 않고 (이벤트를 전달하듯) DataProvider에게 전달하도록 설계하였습니다.
    - MainController와 EditController의 DataProvider 인스턴스 주소값이 달라서 생기는 문제는, 전자가 본인이 소유한 인스턴스를 후자에게 주입해주는 방법으로 해결하였습니다.

> 1-3.
> 
- 아이패드의 키보드를 사용할 경우, ModalView 밖을 터치하여 원치 않게 작성 중인 정보가 사라지는 것을 방지하고자 했습니다.
    - 뷰 밖을 터치했을 때 창이 사라지는 기능을 의도적으로 차단하기 위해 `EditController`는 `UIAdaptivePresentationControllerDelegate`를 채택하였습니다.
    
    참고링크: [Modernizing Your UI for iOS 13](https://developer.apple.com/videos/play/wwdc2019/224/)
    

> 1-4.
> 
- 매직넘버 분리, `self.` 첨가, `internal` 메서드, 프로퍼티 상단 노출 등, 컨벤션 규칙을 동일하게 적용하였습니다.

---

## 2. 해결이 되지 않은 점

> 2-1.
> 

뷰 디버깅 과정에서 TableView의 Header 위로 정체 모를 빈 공간이 확인되었습니다. ~~이게... 뭘까요?~~

참고 사진은 아래 첨부합니다.

<img src="https://i.imgur.com/C0hUHak.png" width="60%"/><br/>

<img src="https://i.imgur.com/IV8nSG5.png" width="60%"/>  

---

## 3. 조언을 얻고 싶은 부분

> 3-1.
> 

MVVM를 계속 강구해보았지만 ViewModel에는 UIKit을 임폿하지 않는다는 대전제 아래, 현재 코드에서 ViewModel을 분리하는 방법을 떠올리지 못했습니다. ViewModel에 대해 다르게 접근해보는 게 좋을까요..?😭

2022-03-11 01:08 UTC, ehgud0670 commented
네!! 오늘 밤이나 내일중으로 리뷰하도록 하겠습니다. 감사합니다.

2022-03-12 23:17 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +    }()
lazy 키워드를 왜 사용했는지 궁금합니다. 🧐
만약 사용 이유가 뷰컨트롤러 생성 이전에 프로퍼티들에 접근하기 위한 단순 목적이라면, 이번 기회에
(1) lazy 키워드를 언제 사용하는지
(2) lazy 키워드를 사용할때 주의할 점
에 대해 알아두셨으면 좋겠습니다.

위의 경우는 lazy var를 보다는 let 을 쓰는게 맞습니다. :)
다른 lazy var 를 쓴 변수들도 모두 바꿔주세요!!

2022-03-12 23:35 UTC, ehgud0670 commented
> 2-1.
뷰 디버깅 과정에서 TableView의 Header 위로 정체 모를 빈 공간이 확인되었습니다. 이게... 뭘까요?
참고 사진은 아래 첨부합니다.

=> 다른 리뷰이에게 들었는데 iOS15에서만 나타나는 이슈라고 합니다. 찾아서 해결하시면 될 것 같아요! :)

2022-03-13 00:05 UTC, ehgud0670 requested changes
피드백 확인 부탁드립니다! 수고 하셨습니다. :)

2022-03-13 00:05 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +    var beingEditedTodoSection: TodoSection?
이런 모델값들은 모두 뷰모델(여기서는 DataProvider)안에 집어넣어주셔야 합니다. ViewController에서는 프로퍼티가 뷰모델만 보이는 것이 제일 깔금합니다. 따라서 EditController 만의 뷰모델(여기서는 DataProvider)을 만들어주시면 되겠네요.

2022-03-13 00:05 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +class EditController: UIViewController, UIAdaptivePresentationControllerDelegate {
왜 Controller라고만 지으셨는지는 모르겠는데 다른 사람도 보기 쉽도록 EditViewController라고 하는게 좋을 듯 합니다. :)

2022-03-13 00:05 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +    weak var dataProvider: DataProvider?
dataProvider를 MainViewController의 객체를 주입받는 것 말고, EditController만의 DataProvider를 만드시는게 낫습니다. 
그럼 weak 키워드도 필요없겠습니다.
왜 EditController만의 DataProvider를 만드는게 나을까요?

2022-03-13 00:05 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Controller/MainController.swift
> +        self.doneTableView.setDelegate(delegate: self)
이런것들은 배열화해서 forEach문을 사용하시는게 좋을 것 같아요.

2022-03-13 00:08 UTC, ehgud0670 commented
> 1-1. 매번 tableView를 확인하여 section을 매칭해주는 방식이 과하게 중복된다고 느꼈습니다.
NSObject를 채택한 MainTableView 타입 내부에 tableView와 section을 함께 선언하는 것으로
UITableViewDataSource, UITableViewDelegate 파일분리
section 매칭 중복코드 삭제, TodoSection 케이스 추가에 대한 유연성 확보
를 의도하였습니다.

그럼 section이란 enum을 이용하여 테이블뷰를 배열화해서 코드 구현하시는 건 어떨까요? section과 테이블뷰 관계에 대한 데이터값은 뷰모델이 가지고 있게 하고요.

2022-03-13 00:11 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +    var beingEditedTodoSection: TodoSection?
그럼 DataProvider도 weak 로 선언 안하셔도 되겠습니다. :)

2022-03-13 00:17 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +        )
이런 건 따로 분리해도 되겠네요~

2022-03-13 00:17 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +        if self.beingEditedTodoUUID != nil, self.beingEditedTodoSection != nil {
이런 조건문은 가독성 있는 하나의 valid 메소드로 분리해도 되겠습니다.

2022-03-13 00:18 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +        }
150줄부터 156줄 까지도 하나의 메소드로 분리하면 좋겠네요.

2022-03-13 00:24 UTC, ehgud0670 commented
3-1.
MVVM를 계속 강구해보았지만 ViewModel에는 UIKit을 임폿하지 않는다는 대전제 아래, 현재 코드에서 ViewModel을 분리하는 방법을 떠올리지 못했습니다. ViewModel에 대해 다르게 접근해보는 게 좋을까요..?😭

=> 힘들면 UIKit를 일단 임포트하셔도 됩니다. 역할만 일단 제대로 기준잡고 뷰모델 만드시면 될 것 같아요. 저희 근데 MVVM으로 만들자고 했는데 DataProvider라는 객체는 어떤 것일까요? ViewModel의 역할을 하는 객체일까요?

2022-03-13 01:58 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Controller/MainController.swift
> +        let selectedTodo = selectedTodos[indexPath.row]
그냥 배열에 접근하는 것은 크래시가 날 위험이 있습니다. 크래시가 나지 않으려면 어떤 방법이 있을까요? (hint. 딕셔너리에 safe 하게 접근하기)

2022-03-13 02:12 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Extension/UIKit/UITableView+Extension.swift
> +}
extension 으로 메소드 잘 만드셨네요! 😄

2022-03-15 17:51 UTC, FIIIIN commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +        self.isModalInPresentation = hasChanges
`addTarget` 메서드를 사용해서 값이 바뀔 때마다 상태값을 바꿔주도록 수정하였습니다!
hasChanges를 사용하였던 `isModalInPresentation` 프로퍼티 또한 동일하게 수정하였습니다🤓

2022-03-15 17:54 UTC, FIIIIN commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +}
위의 코멘트와 동일하게 답 드릴 수 있을 것 같습니다...!

다만 이 경우는 EditController에서 사용되는 상수값만을 가지고 있는 것으로 확인되는데, 제가 잘못 이해한 부분이 있는 걸까요?

2022-03-15 17:58 UTC, FIIIIN commented on ProjectManager/ProjectManager/Service/DataFormatter.swift
> +    }
지금 떠오르는 방법은 Section에 따라 각각의 Todo 배열을 가지도록 하는 것 정도인데, `지금의 방식`과 `각각의 배열을 가지는 것`이 어떤 차이를 가질까요?

2022-03-16 12:16 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Scene/Main/MainTableView.swift
> +    }()
뷰에는 뷰를 구현 및 렌더링하는데 필요한 값이나 메소드만 구현하면 된다는 말씀입니다.
DataProvider는 모델로서 뷰가 가지고 있으면 안되는데(Cell의 경우에는 뷰모델 정도 허용됩니다) 해당 MainTableView 가 많은 역할을 하는 바람에 어쩔수 없이 dataprovider를 가지고 있게 되어서 코멘트 드렸습니다 :)

2022-03-16 12:21 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Scene/Main/MainTableView.swift
> +    }()
어떤 의미를 가질수 있냐면 각 객체(뷰, 뷰모델)가 각자의 역할을 한다면 각 역할에 맞게 다른 곳에서도 재사용할수 있고 코드가 있어야 할 곳에 있게 되어 나중에 많이 안고쳐도 되는 장점이 있겠습니다. SRP에 맞게 잘 작성하면 팀원들도 오해하지 않고 잘 코드를 읽을 수 있게 되고요.

2022-03-16 12:25 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Service/DataFormatter.swift
> +    }
훨씬 효율적이죠. 고민해보세요 :)

2022-03-16 12:27 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +    weak var dataProvider: DataProvider?
일단 EditVC의 뷰모델이 모델값을 들고 있다가 MainVC 에게 잘만 넘겨주면 해결될 문제일 것 같은데 어떻게 생각하시나요.

2022-03-16 12:38 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +}
말씀하신 것처럼 EditContoller에서만 쓰이는 상수들이므로, 해당 enum을 EditController 안쪽에 nested하게 위치시키는게 나을 것 같다는 말씀입니다 :)

2022-03-17 16:40 UTC, FIIIIN commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +    var beingEditedTodoSection: TodoSection?
우선 불필요하게 분리되어 있는 두 변수를 todo라는 변수로 통일해주었습니다. 다만 이 방법 또한 ViewController가 프로퍼티로 뷰 모델만 가지는 것이 깔끔하다는 이야기에는 잘 부합하지 못해 보이는데요, DataProvider가 가지고 있는 todoList를 인터널로 선언하여 값을 사용하는 방법 정도가 떠오르는데 현재의 방식보다 후자가 말씀하신 이야기와 부합할까요?

2022-03-17 17:04 UTC, FIIIIN commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +    weak var dataProvider: DataProvider?
제가 설계한 뷰 모델(DataProvider)은 DB(TodoList)와 단방향 소통을 하고 있는데, 이때 EditVC가 개별적인 뷰 모델을 가지는 것이 어떤 의미인지 모르겠습니다😭
만약 제가 추측하는 대로 EditVC와 MainVC가 참조관계(?)인 편이 자연스러워서 EditVC가 직접 뷰 모델과 소통하는 것이 부자연스럽다면, EditVC에서 만들어진 모델값을 바로 MainVC에게 넘겨주는 것으로 충분할 것 같다고 생각했습니다.

2022-03-19 14:37 UTC, FIIIIN commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +    }()
이유는 회의실에서 말씀드린 내용과 일치하며, 아래에는 lazy 키워드의 주의할 점에 대해서만 적어보겠습니다..!

lazy stored property는 처음 사용되기 전에는 연산되지 않는다는 특징이 있으며, 이 특징으로 인해 멀티 스레드 환경에서 lazy 프로퍼티에게 접근할 경우 이니셜라이즈가 한 번만 불린다고 보장할 수 없습니다.

> If a property marked with the lazy modifier is accessed by multiple threads simultaneously and the property hasn’t yet been initialized, there’s no guarantee that the property will be initialized only once.

참고링크
* [Swift globals and static members are atomic and lazily computed](https://www.jessesquires.com/blog/2020/07/16/swift-globals-and-static-members-are-atomic-and-lazily-computed/)
* [the swift programming language: Properties](https://docs.swift.org/swift-book/LanguageGuide/Properties.html)

2022-03-19 14:47 UTC, FIIIIN commented on ProjectManager/ProjectManager/Scene/Main/MainTableView.swift
> +    }()
제이슨과의 화상미팅으로 말씀하신 내용이 아래와 같다고 정리해보았습니다.

---
UITableViewDataSource나 UITableViewDelegate를 ViewModel이 채택하거나, 개별 파일로 분리할 경우,
  1. 뷰가 부담해야 하는 책임이 나누어지기 때문에 단일 책임 원칙에 부합하며
  2. 뷰모델 혹은 개별 파일이 여전히 UI 독립적이기 때문에 testable합니다.

ViewModel이 일대일 관계가 되는 것이 저어된다면 subViewModel을 ViewModel이 가짐으로써 일대다 관계를 유지할 수도 있습니다.

2022-03-19 17:59 UTC, FIIIIN commented on ProjectManager/ProjectManager/Service/DataFormatter.swift
> +    }
말씀드렸던 대로 딕셔너리의 key로 분류하여 비효율적인 filter 과정을 삭제하는 방향으로 리팩토링 진행하겠습니다👍

2022-03-19 19:38 UTC, FIIIIN commented on ProjectManager/ProjectManager/Controller/MainController.swift
> +        let selectedTodo = selectedTodos[indexPath.row]
위에 말씀드렸던 대로 리팩토링 진행하여 현재는 DataFormatter 객체가 삭제되는 방향으로 수정되었습니다!

2022-03-20 15:14 UTC, FIIIIN commented
안녕하세요 제이슨~! @ehgud0670
말씀해주시거나 이야기 나누었던 내용의 적용을 모두 마쳤습니다👍
제이슨과의 화상미팅 덕분에 갈피를 잡고 진행할 수 있었습니다. 감사합니다!!

MVVM의 ViewModel은 UI Independent하기 때문에, testable해짐과 동시에 재활용성이 향상된다는 점이 가장 주목할 지점이라고 생각하게 되었습니다. 따라서 코멘트에 적어주신 내용대로 UIKit을 필요에 따라 import 하려하나, 이 부분은 시간 상의 문제로 다음 스탭의 Rx를 적용하는 과정에서 진행하게 될 듯합니다.

이야기가 있었으나 제가 놓친 개선사항이 있다면 언제든지 디엠 부탁드릴게요🤓👏

2022-03-21 09:27 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Scene/Main/MainTableView.swift
> +    }()
UITableViewDataSource를 채택한것만 testable 하다고 할 수 있겠습니다. 
UITableViewDelegate는 view가 있어야 함수가 호출되겠네요 :)

2022-03-21 09:28 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Controller/EditController.swift
> +    var beingEditedTodoSection: TodoSection?
네 일단 모두 뷰모델에 넣어주시면 됩니다 :)
internal로 할지 private 으로 하고 메소드(or 연산프로퍼티)로 표현할지는 고사리가 선택하면 될 것 같아요.

2022-03-21 09:29 UTC, ehgud0670 commented
코드는 집 가서 볼게요~

2022-03-21 09:45 UTC, ehgud0670 approved these changes

2022-03-21 09:45 UTC, merged