프로젝트 매니저 [STEP 2-2] yeha
yagom-academy/ios-project-manager pull request #99
Opened 2022-03-11 02:53 UTC by ye-ha

안녕하세요, 제이슨! @ehgud0670
코어데이터 연결하는 부분은 현재 진행 중이며, 화면 구현한 부분 먼저 PR 요청 드립니다. 
감사합니다! 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️

# 고민했던 점,

## Collection View 내부에 Table View 구현

- 프로젝트 요구사항을 분석할 때, 열을 3개로 고정하는 것보다 이름과 개수를 원하는 대로 생성할 수 있는게 좋지 않을까 고민했었습니다. 추후에 제이슨이 말씀해주셔서 바로 적용하게 되었습니다.
- Collection View의 cell 내에 Table View가 생성되는 형태로 구현하게 되었습니다.
- 네비게이션 우측의 + 버튼을 누르면 Table View를 담고 있는 Collection View Cell이 추가됩니다.

# 해결이 되지 않은 점

아래의 기능은 아직 구현하지 못해 이번 PR에는 포함되지 않았습니다. 

- 모달에서 새로운 할 일을 저장하는 기능
    - 현재 모달은 `TaskDetailViewController` 입니다.
    - 이 파일 내부에서 저장하도록 구현해야 하는데, 이 부분에서 어떻게 데이터를 넘겨야 할지 어려워서 헤매고 있습니다.
- cell을 터치 → 수정할 수 있는 기능, cell을 길게 터치 → 팝오버 표시하는 기능
- 스와이프
- 지역화

# 조언을 얻고 싶은 점

## View Model에서 사용될 타입

- View Model은 화면에 그려질 때 사용할 데이터를 가지고 있으며, 관리하는 역할이라고 생각했습니다.
- 현재 Entity의 프로퍼티는 다음과 같습니다.
    
    ```swift
    class TaskEntity: Identifiable {
        var id: UUID
        var title: String
        var body: String
        var dueDate: Date
        var lastModifiedDate: Date
    ```
    
- 그래서 UI 구성 요소에 `dueDate`을 넣어줄 때, 포맷팅이 필요합니다. 포맷팅을 안하더라도 아래처럼 String으로 변환을 해줘야 합니다. 
    
    ```swift
    extension TaskCollectionViewCell: UITableViewDataSource {
        func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
            guard let cell = tableView.dequeueReusableCell(
                    withIdentifier: "cell",
                    for: indexPath) as? TaskTableViewCell else { return UITableViewCell() }
            if let task = taskList?.items[indexPath.row] {
                **cell.titleLabel?.text = task.title
                cell.bodyLabel?.text = task.body
                cell.dateLabel?.text = task.dueDate.description**
                return cell
            }
            return UITableViewCell()
        }
    }
    ```
    
- 화면을 그릴 때 사용하기 위해 View Model 내에 임시로 데이터를 할당했습니다.
    - 직접 Entity를 생성하는 형태로 만들었었는데요. Entity 타입을 따르고 있기 때문에, View Model에서 포맷팅한 String 타입을 넣어줄 수 없다는 문제가 있었습니다.
- 제가 생각하는 View Model의 역할을 하기 위해 View Model 내에 Presentation Layer에서만 쓰이는 데이터 타입을 정의해서 사용하는 것을 시도해보았습니다.
    
    ```swift
    class TaskList: Identifiable {
        var id: String
        var title: String
        var items: [Task]
    
        init(title: String, items: [Task] = []) {
            self.id = UUID().uuidString
            self.title = title
            self.items = items
        }
    }
    
    class Task: Identifiable {
        var id: String
        var title: String
        var body: String
        var dueDate: String
        var lastModifiedDate: String
    
        init(title: String, dueDate: String, lastModifiedDate: String, body: String = "") {
            self.id = UUID().uuidString
            self.title = title
            self.body = body
            self.dueDate = dueDate
            self.lastModifiedDate = lastModifiedDate
        }
    }
    ```
    
    ```swift
    lazy var taskLists: [TaskList] = [
            TaskList(title: "test",
                     items: [Task(title: "task title",
                                  dueDate: formatDate(Date()),
                                  lastModifiedDate: formatDate(Date()))])
        ]
    ```
    
- 이 방법이 적절한지, 더 좋은 방법이 있을지, 제이슨은 이런 상황에서 주로 어떤 방법을 사용하셨는지 궁금합니다.

## 화면 구성, 이에 따른 파일 분리, 폴더링
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/60090790/157787808-3d6a503d-1a28-41b5-98a8-60659d63796f.png">

- Form Sheet으로 띄워지는 모달도 View Controller로 만들어야 내부 UI 구성요소를 사용하거나 저장 및 수정하는 기능을 구현할 수 있을 것이라고 생각해서 `TaskDetailViewController` 로 분리했습니다.
- 위와 같은 이유로 Table View Cell 내부의 title, body, date 를 IBOutlet으로 연결해서 사용하기 위해 `TaskTableViewCell`을 따로 생성했습니다.
- 제가 더 생각해 볼 부분이나 다른 방법이 있는지 궁금합니다.

- 추가로 제이슨은 `Info.plist`나 `.storyboard` 파일을 어디에 두시는지 궁금합니다.

2022-03-13 01:27 UTC, ehgud0670 commented
<img width="259" alt="스크린샷 2022-03-13 오전 10 25 30" src="https://user-images.githubusercontent.com/38216027/158040886-e8eb90f0-31b9-4769-9328-f74d4a6feeb6.png">
<img width="517" alt="스크린샷 2022-03-13 오전 10 25 36" src="https://user-images.githubusercontent.com/38216027/158040889-c3b31cd0-1c77-4cf5-929d-3470686767c7.png">

예하! 파일 Path가 예하 로컬 폴더로 되어있어서 읽지 못하는것 같아요! 수정 부탁드립니다 :)

2022-03-13 02:24 UTC, ehgud0670 requested changes
운동 갔다가 다시 리뷰하겠습니다. 고생하셨어요 :)

2022-03-13 02:24 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
> +        //        }
이전 코드는 주석처리하면 안됩니다. 지워주세요.

2022-03-13 02:24 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +}
셀이 TableView를 갖고 있으므로 DataSource 역할을 채택한 것 이해합니다. 
하지만 뷰는 최대한 멍청하게 만드는 것이 맞습니다. ViewModel을 따로 만들어 DataSource를 옮기거나, 독자적인 DataSource객체를 만드는 것이 더 적절해 보입니다.

2022-03-13 02:24 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +        if let task = taskList?.items[indexPath.row] {
safe하게 딕셔너리에 접근할 방법은 없을까요~? 잘못 접근하면 크래시 발생해서요!

2022-03-13 02:24 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +    weak var parentViewController: TaskCollectionViewController?
아직 할당도 안하고 있는 것 같은데 parentVC를 프로퍼티를 둘 필요는 없는 것 같습니다. 
그리고 **웬만해선** 하위객체가 상위객체를 알 필요는 없습니다! 의존성이 생기고 코드라 더러워져서요.

2022-03-13 02:24 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +
셀이 재사용될 때마다 뷰에 할당된 데이터들을 초기화해야 합니다. 현재 그런 처리는 없네요. hint. prepareReuse

2022-03-13 10:27 UTC, ehgud0670 requested changes
예하, 고생하셨습니다!
그럼 피드백 확인 부탁드립니다. 🙏

2022-03-13 10:27 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Entries/SceneDelegate.swift
> +        viewController?.setViewModel(viewModel)
이 부분도 새로운 메소드나 연산 프로퍼티로 분리하면 깔끔하겠네요 :)

2022-03-13 10:27 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +        TaskListCountImageView.image = UIImage(systemName: "\(taskList?.items.count ?? 0).circle.fill")
여기 프로퍼티는 왜 대문자로 시작하는지 궁금하네요. 🧐

2022-03-13 10:27 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
>      }
`didLoaded` 보다는 `reloadTaskList` 나 `requestTaskList`, `executeTaskList`라고 하는게 나을듯 합니다.

그리고 현재는 구현이 안되어 있는데 Repository에서 모델 데이터가 준비되었을때, 뷰컨트롤러가 뷰모델을 바라보고 있다가 reloadData를 호출될 수 있어야 합니다. RxSwift 를 쓰기 전이라면 다른 방법을 쓰셔도 되고, 모두 좋은 방법입니다.

2022-03-13 10:27 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +            cell.dateLabel?.text = task.dueDate
요 부분  cell 이 메소드를 따로 만들어 코드를 한 줄로 줄이는 건 어떨까요?

2022-03-13 10:27 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskTableViewCell.swift
> +class TaskTableViewCell: UITableViewCell {
final로 명시하면 좋은 점을 혹시 아실까요? 어떤 클래스는 final로 되어있고, 어떤 클래스는 final 로 되어 있지 않네요. 🥲(상속이 없음에도 불구하고)

2022-03-13 10:27 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Data/TaskDataRepository.swift
> +    func convertDataModelToEntity(dataModel: TaskDataModel) -> TaskListEntity {
내부에서만 쓰시는 거면 private으로 감추는 것이 좋습니다 :)

2022-03-13 11:00 UTC, ehgud0670 commented
# 조언 얻고 싶은 점 

> 제가 생각하는 View Model의 역할을 하기 위해 View Model 내에 Presentation Layer에서만 쓰이는 데이터 타입을 정의해서 사용하는 것을 시도해보았습니다.

=> 네, 이것도 괜찮은 방법이네요. 다만 실질적인 모델을 UseCase가 가지고 있는 상황에서 또 Presented 된 모델을 뷰모델이 가지고 있는 것은 나중에 상태관리할 때 헷갈리거나 버그가 날 수도 있을듯 합니다. 곰튀김님의 [final_mvvm](https://github.com/iamchiwon/mvvm_final/blob/master/UTCTime/UTCTime/View/ViewModel.swift)에서도 보시면 viewmodel이 모델값을 가지고 있진 않고 포매팅해서 rxswift 를 통해 방출만 하고 있습니다. (제가 전 회사에서 Interactor[서버에 요청을 보내는 역할의 객체]라는 녀석과 ViewModel이 각각 모델을 들고 있고, 서로 sync가 되지 않아 버그를 냈던 적이 있습니다.. 😅 )
하지만 상태관리(서로 싱크만 잘 된다면)만 잘 한다면 뷰모델이 포맷팅한 모델을 갖고 있고, 동시에 UseCase 가 모델을 들고 있어도 되겠습니다. 

> 이 방법이 적절한지, 더 좋은 방법이 있을지, 제이슨은 이런 상황에서 주로 어떤 방법을 사용하셨는지 궁금합니다.

=> 저는 주로 뷰모델이 모델을 들고 있고 뷰에 값을 입힐 때, 뷰모델로 메소드나 연산프로퍼티를 따로 만들어 프레젠팅된 값을 넘기곤 했습니다. 
정답은 없는 듯 합니다. 예하가 구현하신 것도, 제가 구현한 것도 모두 테스트 가능하네요.

창피하지만 제가 작성했었던 [뷰모델](https://github.com/ehgud0670/airbnb-02/blob/jason/iOS/Airbnb/Airbnb/ViewModels/PriceViewModel.swift)을 참고차 보여드립니다. 이건 참고용인거지, 예하가 생각하는 제일 나은 방법으로 구현하시면 되겠습니다. 😄

> 제가 더 생각해 볼 부분이나 다른 방법이 있는지 궁금합니다.

* 네, 이 방법도 괜찮아 보입니다. 다른 방법도 있겠지만 괜찮다 싶으면 그대로 구현하시면 되겠습니다.
* 그리고 지금은 화면이 2개라서 괜찮지만 스토리보드를 나누시는 것이 좋습니다. 스토리보드에는 해당 기능의 관련된 화면들만 만드시는 것이 좋아요.
왜냐하면 협업할 때 서로 다른 작업을 같은 스토리보드에서 진행하고 깃헙에 PR을 올린다면 깃 충돌이 나기 때문입니다. 스토리보드에 깃 충돌나면 답도 없거든요. 😅

> 추가로 제이슨은 Info.plist나 .storyboard 파일을 어디에 두시는지 궁금합니다.

저는 Info.plist는 그대로 두고 스토리보드만 폴더(group)를 만들어 관리하곤 합니다. 그리고 호출하기 쉽게 StotyBoardName이라는 enum까지 만드는 편입니다.

2022-03-13 23:41 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
> +        //        }
앗.. 지웠습니다!

2022-03-13 23:47 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +        if let task = taskList?.items[indexPath.row] {
```
guard let task = taskList?.items[indexPath.row] else { return UITableViewCell() }
```
이렇게 guard문으로 처리하는 방법을 말씀하신 걸까요?
만약 맞다면 guard문의 조건과 return하는 부분이 약간 달라서 if let처리가 낫지 않을까? 하는 생각에서 진행했던 것인데요! 제이슨이 보시기엔 어떤가요?

2022-03-13 23:51 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +    weak var parentViewController: TaskCollectionViewController?
collectionView 메서드 내에서 할당하고 있지만, 없어도 잘 동작하네요.😣 하위객체가 상위객체를 알 필요가 없는 부분도 놓쳤습니다..! 삭제했습니다.

2022-03-14 00:05 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +        TaskListCountImageView.image = UIImage(systemName: "\(taskList?.items.count ?? 0).circle.fill")
실수했습니다. 😣 소문자로 시작하도록 변경했습니다.

2022-03-14 00:07 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
> +    }
앗, 맞습니다. 위 프로퍼티는 self를 명시해주어야 해서 아래도 self를 명시하도록 수정했습니다!

2022-03-14 00:12 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
> +    }
엇 아닙니다. 제가 잘못 봤네요. 위에는 이름이 같아 self 를 붙일수 밖에 없군요. 이러한 경우라면 아래 코드는 self를 붙이지 않으셔도 됩니다!

2022-03-14 00:13 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
> +    }
내부 프로퍼티나 메소드를 사용할때 self를 붙이는 스타일도 있고, 아닌 스타일도 있는데 
안붙이는 스타일 가이드를 따르시는 것 같네요. 그럼 꼭 필요한 상황이 아니라면 안 붙이면 되겠습니다 ☺️

2022-03-14 00:19 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewController.swift
> +        return viewModel?.countTaskList() ?? .zero
countOfTaskList 라고 변경했습니다! 

메서드명이 동사로 시작하도록 지은 것인데, 지금처럼 개수를 반환하는 상황에서는 명사형이 어느 정도 허용되는 편인가요? 
공부했던 코드들에서도 메서드명이 그냥 count로 시작하는 경우가 있었어서 궁금합니다. 

추가로 개수를 반환하는 기능을 프로퍼티로 만들까 고민도 했었는데요!  
외부에서 task list의 개수를 알려달라고 요청하는 상황이라 메서드 호출은 자연스러운데, 
프로퍼티로 접근하는 것은 외부에서 요청하는 것보다 직접 가져다가 쓰는 것 같다는 생각했습니다. 
이 고민에 대해 제이슨은 어떻게 생각하시나요?

2022-03-14 00:24 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewController.swift
> +        return viewModel?.countTaskList() ?? .zero
네, 스위프트에서 뭔가를 리턴하는 경우에는 대개 자바처럼 get 메소드로 네이밍하지 않고 명사형으로 메소드를 짓곤 합니다. 
그리고 해당 메소드에 넣어줘야 할 매개변수가 없다면, 연산 프로퍼티로 표현해도 될 것 같아요. 외부에서 read only 만 할 수 있는 장점이 있습니다.

2022-03-14 00:43 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewController.swift
> +                for: indexPath) as? TaskCollectionViewCell else { return UICollectionViewCell() }
```
protocol Reusable: AnyObject {
    static var reuseIdentifier: String { get }
}

extension Reusable where Self: UIView {
    static var reuseIdentifier: String {
        return String(describing: self)
    }
}
``` 
두 cell이 각각 Reusable 프로토콜을 채택하게 하고, 스토리보드에서 각 클래스의 이름을 identifier로 지정해보았습니다. 혹시 다른 방법도 있을까요? 
그동안 코드로 화면을 그려 왔어서 이렇게 스토리보드 + extension을 활용하는건 처음이라 궁금합니다. 

<img width="257" alt="image" src="https://user-images.githubusercontent.com/60090790/158086714-508b2535-17cc-450c-9699-34c43d7ad3c5.png">

2022-03-14 02:38 UTC, ye-ha commented on ProjectManager/ProjectManager/Data/TaskDataRepository.swift
> +    func convertDataModelToEntity(dataModel: TaskDataModel) -> TaskListEntity {
해당 메서드와 setValue 메서드 모두 private으로 지정했습니다!

2022-03-14 03:50 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskTableViewCell.swift
> +class TaskTableViewCell: UITableViewCell {
메서드나 프로퍼티나 클래스 등에 final 키워드를 붙이게 되면 override를 하지 못하게 할 수 있다고 알고 있습니다. override를 하게 되면 런타임에 어떤 메서드를 실행할지 결정하게 되는데, final을 명시함으로써 컴파일 타임에 어떤 메서드를 실행할지 결정하게 되어 상대적으로 성능상에 이점이 있다고 알고 있습니다. 

접근제어나 final 등의 키워드를 붙여주는 것이 아직 손에 완전히 익지 않아 중간중간 많이 빠뜨렸습니다. 😣
다른 코멘트로 남겨주신 모델 클래스는 변경 가능성이 있어서, 모델 관련 클래스를 제외하고 final 붙였습니다!

2022-03-14 03:56 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewController.swift
> +        return viewModel?.countTaskList() ?? .zero
이 부분이 항상 궁금했었는데, 이번에 명쾌해졌네요! 😄👍

2022-03-14 04:04 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
> +    func createTask(_ task: TaskEntity, in taskList: String)
이 부분도 어떻게 하는 것이 맞을지 고민했던 부분이라 말씀 해 주신 내용이 답이 되었습니다!
업데이트나 삭제는 `updateTaskList`, `deleteTaskList` 으로 고치면 되겠다고 생각했는데요.
`create` 이나 `make` 이 객체 및 자료구조를 만들 때 사용하는 것이라면.. 혹시 `addNewTaskList` 같은 이름은 어떤가요?

2022-03-14 04:06 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewController.swift
> +        }
이 부분도 guard로 고쳤습니다! 😄

2022-03-14 04:12 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
> +    func createTask(_ task: TaskEntity, in taskList: String)
이 부분도 어떻게 하는 것이 맞을지 고민했던 부분이라 말씀 해 주신 내용이 답이 되었습니다!
`addNewTaskList`, `updateTaskList`, `deleteTaskList` 으로 고치려고 생각하고 있습니다.
`create` 이나 `make` 가 객체 및 자료구조를 만들 때 사용하는 표현이니 현재 상황에서는 사용이 어색하다 라고 이해했는데 맞을까요?

2022-03-14 11:03 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +        if let task = taskList?.items[indexPath.row] {
```swift
extension Collection {

    /// Returns the element at the specified index if it is within bounds, otherwise nil.
    subscript (safe index: Index) -> Element? {
        return indices.contains(index) ? self[index] : nil
    }
}
```
=> 제가 말씀드린 건 이런거 였습니다. 저도 어디서 보고 좋은 것 같아서 사용하고 있어요. 굳이 안 바꾸셔도 되고 참고차 말씀드렸어요! 😁

https://stackoverflow.com/a/30593673

2022-03-14 11:14 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewController.swift
> +                for: indexPath) as? TaskCollectionViewCell else { return UICollectionViewCell() }
네, 그렇게 하시는 것이 맞습니다. 
그리고 xib 를 쓰는 경우에는 해당 파일로 그대로 가져오는 방법도 있더라고요. 참고 부탁드립니다 :)

> example

```swift
extension UITableView {
    
    func registerCell<T: UITableViewCell>(cellType: T.Type) {
        let identifier = String(describing: T.self)
        let nib        = UINib(nibName: identifier, bundle: nil)
        
        if cellType.isExistNibFile { self.register(nib, forCellReuseIdentifier: identifier) }
        else                       { self.register(cellType, forCellReuseIdentifier: identifier) }
    }
}

extension UIView {
    static var isExistNibFile: Bool {
        let nibName = String(describing: self)
        return Bundle.main.path(forResource: nibName, ofType: "nib") != nil
    }
```
=> 예를 들어 CustomCell.swift, CustomCell.xib를 만들어서 사용할 때, 따로 reuseIdentifer 지정하지 않고 바로 써서 좋더라고요.
이건 제 코드가 아니고 다른 동료께서 쓴 방법인데 좋아보여 참고차 공유드립니다!

2022-03-14 11:18 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
> +    func createTask(_ task: TaskEntity, in taskList: String)
넵 맞습니다! 하지만 정답은 없는 것 같고 저만 어색하게 느낄수 있다고 생각도 되네요.. 
일단 저도 계속 고민해보고 질문도 해보고 하겠습니다.

2022-03-14 11:19 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
>      }
맨처음에는 load() 나중에 다시 리로드할 때는 reload() 라는 식으로 해도 되겠네요. 제가 보기엔 메소드 성격이 과거형이 아니라 load 를 해주는 메소드로 보여서요.

2022-03-14 11:20 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +            cell.dateLabel?.text = task.dueDate
`cell.update(with: task)` 이런식으로요!

2022-03-15 05:11 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
> +    func createTask(_ task: TaskEntity, in taskList: String)
CRUD에 해당하는 단어만 쓰는 것보다는 수정하는 것이 좋다고 생각되었습니다! 말씀 해 주신 내용도 충분히 이해가 되었고, `add`도 의미를 잘 담을 수 있는 것 같아 `addNewTaskList`, `updateTaskList`, `deleteTaskList` 로 고쳤습니다! 😄

2022-03-15 05:18 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +            cell.dateLabel?.text = task.dueDate
이 부분은 메서드로 분리할 때 한 번에 하려고 두었는데, 코멘트를 추가로 달아주셨군요! 감사합니다 ✨
메서드로 분리할까 하다가 말씀 해 주신 예시도 좋아보여서 `TaskTableViewCell` 의 extension 내 `update` 메서드로 분리했습니다! 
멀리 두면 보기 힘들 것 같아서 호출되는 곳 근처, 바로 아래 배치했는데 어떤가요??
```
        guard let task = taskList?.items[indexPath.row] else { return UITableViewCell() }
        cell.update(with: task)
        return cell
    }
}

extension TaskTableViewCell {
    func update(with task: Task) {
        self.titleLabel?.text = task.title
        self.bodyLabel?.text = task.body
        self.dateLabel?.text = task.dueDate
    }
}

```

2022-03-15 05:42 UTC, ye-ha commented on ProjectManager/ProjectManager/Entries/SceneDelegate.swift
> +        viewController?.setViewModel(viewModel)
모두 연산 프로퍼티로 분리했습니다. window 관련된 부분은 `configureWindow`메서드로 분리했습니다!

2022-03-15 06:15 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewController.swift
> +        present(alertController, animated: true)
`configureAddAction`, `configureCancelAction`, `insertItem` 메서드로 각각 분리했습니다!

2022-03-15 07:40 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +
각 cell 내에 `prepareForReuse`메서드 재정의해서 초기화했습니다!
[공식 문서](https://developer.apple.com/documentation/uikit/uitableviewcell/1623223-prepareforreuse)에서 해당 메서드에 대해 ` To avoid potential performance issues, you should only reset attributes of the cell that are not related to content, for example, alpha, editing, and selection state. ` 라고 언급했더라고요. 
검색하다가 [What is the correct way to use prepareForReuse?](https://stackoverflow.com/questions/40773208/what-is-the-correct-way-to-use-prepareforreuse) 라는 글을 보고 저도  `prepareForReuse`메서드 내에서 초기화하는 방법을 택했는데요! 
제이슨은 어떻게 생각하시나요? 🤔

2022-03-15 08:09 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewController.swift
> +        if let task = viewModel?.taskLists[indexPath.item] {
우선 `TaskCollectionViewController`에서는 말씀해 주신 것처럼 메서드를 통해 데이터를 받도록 변경했습니다. 그런데 `TaskCollectionViewCell` 에서는 ViewModel을 모르는 상황이라 TableView Cell을 구성할 때는 해당 메서드를 사용하지 못했습니다. 이걸 어떻게 풀어가야 할지 고민이 됩니다.

2022-03-15 08:11 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewController.swift
> +                for: indexPath) as? TaskCollectionViewCell else { return UICollectionViewCell() }
오, 처음 보는 방법이에요. 참고하겠습니다. 감사합니다!

2022-03-15 09:26 UTC, ye-ha commented on ProjectManager/ProjectManager/Domain/TaskEntity.swift
> +class TaskListEntity: Identifiable {
Objective-C와 호환될 필요가 있거나 데이터의 identity 관련 제어를 해야 할 때는 class를 사용하고, 클래스를 사용할 일이 없을 때는 기본적으로 struct를 사용한다고 알고 있습니다. 
모델을 struct로 구현하게 되면, 여러 인스턴스를 생성했을 때 (값 타입이기 때문에) 서로에게 영향을 주지 않기 때문에 잘못 변경될 위험이 없어서 일까요? 
서로 인스턴스 생성 방식 (값, 참조) 이 다르기 때문에 기본적으로 사용해야 하는 데이터의 스타일에 따라 다른 선택을 해야 할 것 같다는 생각을 했습니다. 이번 앱을 생각했을 때, 모델 타입을 바탕으로 여러 인스턴스를 만들어서 사용한다면 서로 참조할 이유가 없는 상황에서는 개별로 취급되어야 하기 때문에 struct여야 할 것 같습니다.

---
코어데이터의 TaskDataModel Entity 내부의 items attribute가 [TaskEntity] 타입입니다. TaskEntity가 NSObject를 상속받기 위해 TaskEntity를 class로 바꾸었었습니다. 그 과정에서 한 번에 바꾸어 주었던 기억이 납니다.. 
알려 주셨던 [mvvm_final](https://github.com/iamchiwon/mvvm_final) 처럼 Data, Repository 쪽 (제 상황에서는 코어데이터)에서 사용되는 (class) Entity를 하나 두고, 추가로 (struct) Model을 따로 주어야 겠다고 생각했습니다.

2022-03-15 09:31 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
>  }
코멘트 남겨 주신 대로 분리했습니다! 
CoreData를 위한 class Entity 분리를 염두에 두고 있어서 Presentation 폴더에 있는 것이 어색하게 느껴져서 Domain 폴더에 넣었습니다.

2022-03-15 09:35 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
>      }
reloadTaskList 로 변경했습니다. 새롭게 남겨 주신 내용도 좋네요 😄 현재는 viewModel 이니셜라이저에서 load 하고 있어서 후에 메서드를 분리할 때 사용하겠습니다!

2022-03-15 09:41 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +        if let task = taskList?.items[indexPath.row] {
오 🤩 cell에서 메서드를 통해 데이터 받는 부분은 viewModel 쪽에도 적용해 보았습니다!

2022-03-15 09:47 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +}
현재 CollectionView 내에 TableView가 존재하고 있어서 DataSource를 분리하고 누가 가지고 있게 할지, 스토리보드 상에서 DataSource 소유를 연결해 주어야 해서 CollectionViewController가 가지고 있게 해야 할지.. 이 부분이 약간 어렵습니다. 
<img width="291" alt="image" src="https://user-images.githubusercontent.com/60090790/158350922-1308f8d7-6179-4458-bb25-1a9cdc0ea04a.png">

2022-03-15 11:41 UTC, ye-ha commented on ProjectManager/ProjectManager/Presentation/TaskViewModel.swift
> +                                                            lastModifiedDate: formatDate(Date()))])]
말씀해 주신 대로 메서드를 사용하기 위해 lazy 키워드를 사용했습니다. 😣 단지 이 이유를 위해 사용하는 것이 적절하지 않았군요.. 
lazy 키워드를 붙이게 되면 사용되기 전까지 메모리에 올라가지 않습니다. 인스타그램의 스토리 같은 부분(누르기 전까지는 로드할 필요가 없는 부분)을 구현할 때 사용하면 좋을 것 같습니다.  처음 필요할 때만 계산되고 그 후에는 값이 저장되기 때문에 특성을 알고 사용해야 할 것 같습니다. 
lazy 프로퍼티의 클로저는 @noescape으로 간주되어 즉시 적용되고 retain cycle이 발생하지 않지만, lazy 프로퍼티가 클로저 타입이라면 [weak self] 등을 해주어 메모리 누수를 방지해야 합니다.

2022-03-15 14:13 UTC, ye-ha commented on ProjectManager/ProjectManager/Domain/TaskEntity.swift
> +class TaskListEntity: Identifiable {
현재 곰튀김님 강의를 참고하여 `Entity (데이터베이스 모델)`, `Model(실제 데이터로써 역할을 수행하는 모델)` 로 분리해 보았습니다. 
`viewModel` 내에서 날짜에 관련된 포맷팅을 하고 싶었는데, 현재 이차원 배열을 다루다 보니 쉽지 않아서 현재 `FetchTaskUseCase`에서 해주고 있습니다.🤔
```
    private func convertToTaskList(from taskListModel: [TaskListModel]) -> [TaskList] {
        return taskListModel.compactMap { taskListModel in
            let taskList = TaskList(id: taskListModel.id.uuidString,
                                    title: taskListModel.title,
                                    items: self.convertToTask(from: taskListModel.items),
                                    lastModifiedDate: taskListModel.lastModifiedDate.formatToString())
            return taskList
        }
    }
   ```

2022-03-15 14:53 UTC, ye-ha commented
리뷰를 꼼꼼히 남겨 주셔서 리팩터링과 공부하는 시간이 길었습니다. 
남겨 주신 코멘트를 보고 UseCase와 ViewModel이 하나의 데이터를 바라보도록 변경했습니다. 

추가로 storyboard도 폴더를 만들고, 분리를 했습니다. 분리나 네이밍이 적절한지 궁금합니다. 
StotyBoardName이라는 enum도 만드신다고 하셨는데, `SceneDelegate`에서 사용하기 편하도록 만드는 것일까요? 
현재 코드에서는 쓰일 만한 곳이 아래 코드 정도라서.. 어떻게 쓰이는지 궁금합니다! 
```
let storyboard = UIStoryboard(name: "Main", bundle: nil)
```

2022-03-16 12:49 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +}
음, 스토리보드에서의 DataSource 연결을 지우고, tableview의 dataSource 지정을 코드로 하면 될텐데 안되실까요?

2022-03-16 12:53 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewCell.swift
> +
네 좋습니다. 셀은 재사용되는 뷰이기 때문에, 이 메소드로 초기화하지 않으면 스크롤시 셀에 이전에 할당된 데이터값이 뷰에 표현이 됩니다.
참고차 말씀 드렸습니다~!

2022-03-16 13:18 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Presentation/TaskCollectionViewController.swift
> +        if let task = viewModel?.taskLists[indexPath.item] {
TaskCollectionViewCell만의 ViewModel을 만들면 될 것 같은데 어떠신가요?

2022-03-16 13:28 UTC, ehgud0670 commented on ProjectManager/ProjectManager/Domain/TaskEntity.swift
> +class TaskListEntity: Identifiable {
> 모델을 struct로 구현하게 되면, 여러 인스턴스를 생성했을 때 (값 타입이기 때문에) 서로에게 영향을 주지 않기 때문에 잘못 변경될 위험이 없어서 일까요?

정확합니다. 👍😄💯

2022-03-18 09:54 UTC, merged